KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/animate.f File Reference
animate.f File Reference
Functions/Subroutines
subroutine animate
subroutine hbubble
subroutine drwstl (IP, TAU1, TAU2, IPASS)
subroutine getstr
subroutine getbrst
subroutine dmpfrm
subroutine setfrm
subroutine drobjt
subroutine drwire
subroutine aniview
subroutine setstat (THTA, PHII, ZFAC, XCTR, YCTR)
subroutine setvue2
subroutine spfit (YOUT, NOUT, YIN, NIN)
subroutine splint (XA, YA, Y2A, N, X, Y)
subroutine spline (X, Y, N, YP1, YPN, Y2)
subroutine openpf (IEXIT, IUNIT, TEXT)
subroutine draw_state (kdump, ldump, ifprof, THT, phj, ZFAC, XCT, YCT, nre)
Function/Subroutine Documentation
subroutine animate ()
Definition at line 3 of file animate.f.
References aniview().
subroutine aniview ()
Definition at line 648 of file animate.f.
References draw_state(), grab_window_pix(), i, j, mouse(), openpf(), prs(), prsii(), rei(), reiii(), rerr(), rerrr(), res(), scrdmp(), setfrm(), setstat(), and spfit().
subroutine dmpfrm ()
Definition at line 367 of file animate.f.
References i.
subroutine draw_state (kdump, ldump, logical ifprof, THT, phj, ZFAC, XCT, YCT, nre)
Definition at line 1050 of file animate.f.
References blank(), clear(), drmesh(), getfld(), gswrit(), i, plotit(), prs(), reii(), setstat(), setstate(), and setwrk().
subroutine drobjt ()
Definition at line 409 of file animate.f.
References beginb(), color, drawc(), endp(), fillp(), getpts(), i, iflip(), movec(), penw(), xiso(), xisom(), yiso(), and yisom().
subroutine drwire ()
Definition at line 616 of file animate.f.
References color, drawc(), movec(), xiso(), and yiso().
subroutine drwstl (IP, TAU1, TAU2, IPASS)
Definition at line 123 of file animate.f.
References color, drawc(), icolor1(), j, movec(), xiso(), and yiso().
subroutine getbrst ()
Definition at line 279 of file animate.f.
References copy(), i, prs(), rerr(), rerrr(), res(), and ziso().
subroutine getstr ()
Definition at line 227 of file animate.f.
References blank(), chcopy(), copy(), i, indx1(), j, ltrunc(), n, and openf().
subroutine hbubble ()
Definition at line 19 of file animate.f.
References dmpfrm(), drobjt(), drwire(), drwstl(), prs(), res(), and setfrm().
subroutine openpf (IEXIT, IUNIT, character*30 TEXT)
Definition at line 1026 of file animate.f.
References res().
subroutine setfrm ()
Definition at line 394 of file animate.f.
References clear(), drfram(), and drmesh().
subroutine setstat (THTA, PHII, ZFAC, XCTR, YCTR)
Definition at line 840 of file animate.f.
References setvue2(), xiso(), xphy(), yiso(), and yphy().
subroutine setvue2 ()
Definition at line 912 of file animate.f.
subroutine spfit (dimension(1) YOUT, NOUT, dimension(1) YIN, NIN)
Definition at line 941 of file animate.f.
References i, spline(), and splint().
subroutine spline (dimension(n) X, dimension(n) Y, N, YP1, YPN, dimension(n) Y2)
Definition at line 995 of file animate.f.
References i, and n.
subroutine splint (dimension(n) XA, dimension(n) YA, dimension(n) Y2A, N, X, Y)
Definition at line 966 of file animate.f.
References n.