KTH framework for Nek5000 toolboxes; testing version: Toolbox/driver/avg_spt/avg_spt_debug.f File Reference
avg_spt_debug.f File Reference
Functions/Subroutines
subroutine vis_ownership
subroutine seq_out
subroutine stat_output_mapping
Function/Subroutine Documentation
subroutine seq_out ()
Definition at line 55 of file avg_spt_debug.f.
References crecv(), and csend().
subroutine stat_output_mapping ()
Definition at line 99 of file avg_spt_debug.f.
References crecv(), csend(), and lelt.
subroutine vis_ownership ()
Definition at line 11 of file avg_spt_debug.f.
References lelt, ly1, lz1, outpost(), and rzero().