KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/avg/avg.c File Reference
avg.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <ctype.h>
#include <float.h>
#include <time.h>
#include <unistd.h>
Macros
#define MAX_BUF 512
#define TRUE 1
#define FALSE 0
#define TAG_VAL 6.54321
#define EPS 0.000001
#define MAX_NAME 80
#define SWAP(a, b) temp=(a); (a)=(b); (b)=temp;
#define MAX(x, y) ((x)>(y)) ? (x) : (y)
#define MIN(x, y) ((x)<(y)) ? (x) : (y)
Functions
void byte_reverse (float *buf, int n)
void rvec_axpy (register float *arg1, register float *arg2, register float scale, register int n)
void rvec_zero (register float *arg1, register int n)
void main (int argc, char **argv)
Macro Definition Documentation
#define EPS 0.000001
Definition at line 52 of file avg.c.
#define FALSE 0
Definition at line 50 of file avg.c.
#define MAX (x, y) ((x)>(y)) ? (x) : (y)
Definition at line 56 of file avg.c.
#define MAX_BUF 512
Definition at line 48 of file avg.c.
#define MAX_NAME 80
Definition at line 53 of file avg.c.
#define MIN (x, y) ((x)<(y)) ? (x) : (y)
Definition at line 57 of file avg.c.
#define SWAP (a, b) temp=(a); (a)=(b); (b)=temp;
Definition at line 55 of file avg.c.
#define TAG_VAL 6.54321
Definition at line 51 of file avg.c.
#define TRUE 1
Definition at line 49 of file avg.c.
Function Documentation
void byte_reverse (float * buf, int n)
Definition at line 69 of file avg.c.
References exit(), printf(), ptr, and SWAP.
void main (int argc, char ** argv)
Definition at line 127 of file avg.c.
References byte_reverse(), EPS, exit(), FALSE, i, malloc(), MAX, MAX_BUF, MAX_NAME, MIN, npts, printf(), rvec_axpy(), rvec_zero(), TAG_VAL, and TRUE.
void rvec_axpy (register float * arg1, register float * arg2, register float scale, register int n)
Definition at line 96 of file avg.c.
void rvec_zero (register float * arg1, register int n)
Definition at line 112 of file avg.c.