KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/avg.f File Reference
avg.f File Reference
Functions/Subroutines
program fld_avg
subroutine add2 (x, y, n)
subroutine copy (x, y, n)
subroutine sub2 (x, y, n)
subroutine add2sq (x, y, n)
subroutine izero (x, n)
subroutine rzero (x, n)
subroutine cmult (x, c, n)
subroutine vsqrt (x, n)
subroutine blank (x, n)
function glmin (x, n)
function glmax (x, n)
function ltrunc (STRING, L)
subroutine chcopy (A, B, N)
logical function if_byte_swap_test (bytetest)
subroutine get_data (x, n, if_byte_sw, fname)
subroutine out_data (x, n, if_byte_sw, fname, y)
subroutine outl (x, n, name)
subroutine stat (x, n, name)
Function/Subroutine Documentation
subroutine add2 (real, dimension(1) x, real, dimension(1) y, n)
Definition at line 100 of file avg.f.
References i, and n.
subroutine add2sq (real, dimension(1) x, real, dimension(1) y, n)
Definition at line 124 of file avg.f.
References i, and n.
subroutine blank (character*1, dimension(1) x, n)
Definition at line 169 of file avg.f.
References i, and n.
subroutine chcopy (character*1, dimension(1) A, character*1, dimension(1) B, N)
Definition at line 216 of file avg.f.
References i, and n.
subroutine cmult (real, dimension(1) x, real c, n)
Definition at line 148 of file avg.f.
References i, and n.
subroutine copy (real, dimension(1) x, real, dimension(1) y, n)
Definition at line 108 of file avg.f.
References i, and n.
program fld_avg ()
Definition at line 1 of file avg.f.
References add2(), add2sq(), blank(), cmult(), exit(), get_data(), n, nx, out_data(), outl(), rzero(), scale(), stat(), sub2(), and vsqrt().
subroutine get_data (real*4, dimension(1) x, n, logical if_byte_sw, character*40 fname)
Definition at line 237 of file avg.f.
References byte_close, byte_open, byte_read, byte_reverse, chcopy(), izero(), ltrunc(), and n.
function glmax (real, dimension(1) x, n)
Definition at line 189 of file avg.f.
References glmax(), i, and n.
function glmin (real, dimension(1) x, n)
Definition at line 177 of file avg.f.
References glmin(), i, and n.
logical function if_byte_swap_test (real*4 bytetest)
Definition at line 223 of file avg.f.
References if_byte_swap_test().
subroutine izero (integer, dimension(1) x, n)
Definition at line 132 of file avg.f.
References i, and n.
function ltrunc (character*1, dimension(l) STRING, L)
Definition at line 201 of file avg.f.
References i, and ltrunc().
subroutine out_data (real*4, dimension(1) x, n, logical if_byte_sw, character*40 fname, real*4, dimension(1) y)
Definition at line 270 of file avg.f.
References byte_close, byte_open, byte_reverse, byte_write, copy(), and n.
subroutine outl (real, dimension(1) x, n, character*3 name)
Definition at line 296 of file avg.f.
References n.
subroutine rzero (real, dimension(1) x, n)
Definition at line 140 of file avg.f.
References i, and n.
subroutine stat (real, dimension(n,1) x, n, character*3 name)
Definition at line 307 of file avg.f.
References glmax(), glmin(), and n.
subroutine sub2 (real, dimension(1) x, real, dimension(1) y, n)
Definition at line 116 of file avg.f.
References i, and n.
subroutine vsqrt (real, dimension(1) x, n)
Definition at line 156 of file avg.f.
References i, and n.