KTH framework for Nek5000 toolboxes; testing version: Toolbox/driver/avg_spt/avg_spt_usr.f File Reference
avg_spt_usr.f File Reference
Functions/Subroutines
subroutine user_stat_init (ctrs, cell, lctrs1, lctrs2, nelsort)
subroutine user_stat_trnsv (lvel, dudx, dvdx, dwdx, vort)
subroutine user_stat_compute (slvel, slp, tmpvel, tmppr, dudx, dvdx, dwdx, lnvar, npos, alpha, beta)
Function/Subroutine Documentation
subroutine user_stat_compute (real, dimension(lx1,ly1,lz1,lelt,3) slvel, real, dimension(lx1,ly1,lz1,lelt) slp, real, dimension(lx1,ly1,lz1,lelt,3) tmpvel, real, dimension(lx1,ly1,lz1,lelt) tmppr, real, dimension(lx1,ly1,lz1,lelt,3) dudx, real, dimension(lx1,ly1,lz1,lelt,3) dvdx, real, dimension(lx1,ly1,lz1,lelt,3) dwdx, integer lnvar, integer npos, real alpha, real beta)
Definition at line 223 of file avg_spt_usr.f.
subroutine user_stat_init (real, dimension(lctrs1,lctrs2) ctrs, integer, dimension(lctrs2) cell, integer lctrs1, integer lctrs2, integer nelsort)
Definition at line 12 of file avg_spt_usr.f.
References copy(), exitt(), ftovec(), ifill(), and izero().
subroutine user_stat_trnsv (real, dimension(lx1,ly1,lz1,lelt,3) lvel, real, dimension(lx1,ly1,lz1,lelt,3) dudx, real, dimension(lx1,ly1,lz1,lelt,3) dvdx, real, dimension(lx1,ly1,lz1,lelt,3) dwdx, real, dimension(lx1,ly1,lz1,lelt,3) vort)
Definition at line 171 of file avg_spt_usr.f.
References copy(), gradm1(), and sub3().