KTH framework for Nek5000 toolboxes; testing version: Toolbox/driver/avg_spt/avg_spt.f File Reference
avg_spt.f File Reference
Framework for Nek5000 toolboxes » Toolbox » Driver module » Spatial average routines.
Set of subroutines for global spatial averaging.
Functions/Subroutines
subroutine avgs_init ()
Initialise spatial averaging of elements.
subroutine avgs_end ()
Finalise spatial averaging of elements.
subroutine avgs_init_local (ctrs, cell, ninseg, ind, ifseg, lctrs1, lctrs2, nseg)
Generate local element mapping.
subroutine avgs_init_coord (nseg)
Reshuffle coordinate arrays.
subroutine stat_init_global (ctrs, owner, cell, ninseg, ind, ifseg, lctrs1, lctrs2, nseg)
subroutine stat_init_int1d ()
subroutine stat_reshufflev (rvar, var, n)
subroutine stat_compute_1dav1 (lvar, npos, alpha, beta)
subroutine stat_compute_1dav2 (lvar1, lvar2, npos, alpha, beta)
subroutine stat_compute
subroutine stat_comm_map ()
subroutine stat_gl_collation
subroutine msgwaitstat (imsg, status)
subroutine senddata (dstid)
subroutine sendmap (dstid)
subroutine colldata (recmap, n, recdata)
subroutine get_send_no (dstid, tosend, st_own, st_lnum, nid)
subroutine trnsfm_recmap (recmap, recsize)
Detailed Description
Set of subroutines for global spatial averaging.
Author
Prabal Singh Negi
Adam Peplinski
Date
Jun 9, 2016
Definition in file avg_spt.f.
Function/Subroutine Documentation
subroutine colldata (integer, dimension(n) recmap, integer n, real, dimension(stat_lm1,stat_lm1,lelt*stat_lvar) recdata)
Definition at line 2263 of file avg_spt.f.
References add2().
subroutine get_send_no (integer dstid, integer tosend, integer, dimension(1) st_own, integer st_lnum, integer nid)
Definition at line 2294 of file avg_spt.f.
subroutine msgwaitstat (integer imsg, integer, dimension(mpi_status_size) status)
Definition at line 2167 of file avg_spt.f.
References mpi_wait().
subroutine senddata (integer dstid)
Definition at line 2181 of file avg_spt.f.
References copy(), csend(), and rzero().
subroutine sendmap (integer dstid)
Definition at line 2232 of file avg_spt.f.
References csend().
subroutine stat_comm_map ()
Definition at line 1940 of file avg_spt.f.
References get_send_no(), ibcastn(), icopy(), ifill(), ivgl_running_sum(), izero(), and lelt.
subroutine stat_compute ()
Definition at line 1174 of file avg_spt.f.
References add2(), col3(), copy(), lelt, ly1, lz1, mappr(), stat_compute_1dav1(), stat_compute_1dav2(), stat_reshufflev(), user_stat_compute(), and user_stat_trnsv().
subroutine stat_compute_1dav1 (real, dimension(lx1,ly1,lz1,lelt) lvar, integer npos, real alpha, real beta)
Definition at line 1019 of file avg_spt.f.
References add2sxy(), exitt(), lelt, and rzero().
subroutine stat_compute_1dav2 (real, dimension(lx1,ly1,lz1,lelt) lvar1, real, dimension(lx1,ly1,lz1,lelt) lvar2, integer npos, real alpha, real beta)
Definition at line 1098 of file avg_spt.f.
References add2sxy(), exitt(), lelt, and rzero().
subroutine stat_gl_collation ()
Definition at line 2044 of file avg_spt.f.
References add2(), colldata(), invcol2(), mpi_get_count(), msgwait(), msgwaitstat(), nekgsync(), senddata(), sendmap(), and trnsfm_recmap().
subroutine stat_init_global (real, dimension(lctrs1,lctrs2) ctrs, integer, dimension(lctrs2) owner, integer, dimension(lctrs2) cell, integer, dimension(lctrs2) ninseg, integer, dimension(lctrs2) ind, logical, dimension(lctrs2) ifseg, integer lctrs1, integer lctrs2, integer nseg)
Definition at line 443 of file avg_spt.f.
References copy(), csend(), exitt(), ifill(), iswap_ip(), lelt, msgwait(), and tuple_sort().
subroutine stat_init_int1d ()
Definition at line 790 of file avg_spt.f.
References add2(), copy(), exitt(), mxm(), rone(), rzero(), stat_reshufflev(), vsq(), and vsqrt().
subroutine stat_reshufflev (real, dimension(stat_nm1,stat_nm2,stat_nm3,lelt) rvar, real, dimension(lx1,ly1,lz1,lelt) var, integer n)
Definition at line 960 of file avg_spt.f.
subroutine trnsfm_recmap (integer, dimension(lelt) recmap, integer recsize)
Definition at line 2315 of file avg_spt.f.