KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/cmt/bc.f File Reference
bc.f File Reference
Boundary condition routines.
Functions/Subroutines
subroutine a5adiabatic_wall (eflx, f, e, dU, wstate)
subroutine a51duadia (flux, f, ie, dU, wstate)
subroutine a52duadia (flux, f, ie, dU, wstate)
subroutine a53duadia (flux, f, ie, dU, wstate)
subroutine inviscidbc (wminus, wbc, nstate)
Determining rind state for Dirichlet boundary conditions.
subroutine bcflux (flux, agradu, qminus)
Determining IGU contribution to boundary flux. 0 for artificial viscosity, and strictly interior for physical viscosity.
Detailed Description
Boundary condition routines.
Definition in file bc.f.
Function/Subroutine Documentation
subroutine a51duadia (real, dimension (nx1*ny1*nz1) flux, integer f, ie, real, dimension (nx1*nz1,2*ndim,nelt,toteq,3) dU, real, dimension(nx1*nz1,2*ndim,nelt,nqq) wstate)
Definition at line 218 of file bc.f.
References i.
subroutine a52duadia (real, dimension (nx1*ny1*nz1) flux, integer f, ie, real, dimension (nx1*nz1,2*ndim,nelt,toteq,3) dU, real, dimension(nx1*nz1,2*ndim,nelt,nqq) wstate)
Definition at line 268 of file bc.f.
References i.
subroutine a53duadia (real, dimension (nx1*ny1*nz1) flux, integer f, ie, real, dimension (nx1*nz1,2*ndim,nelt,toteq,3) dU, real, dimension(nx1*nz1,2*ndim,nelt,nqq) wstate)
Definition at line 318 of file bc.f.
References i.
subroutine a5adiabatic_wall (real, dimension (nx1*nz1,2*ndim,nelt) eflx, integer f, integer e, real, dimension (nx1*nz1,2*ndim,nelt,toteq) dU, real, dimension(nx1*nz1,2*ndim,nelt,nqq) wstate)
Definition at line 190 of file bc.f.
References a51duadia(), a52duadia(), a53duadia(), add2col2(), lz1, and rzero().