KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/big_post.f File Reference
big_post.f File Reference
Functions/Subroutines
program tst
subroutine get_velocity (u, v, w, e)
subroutine get_coords (x, y, z, e)
subroutine get_scalar (s, ei, nx, inew)
subroutine get_exyz (ex, ey, ez, eg, nelx, nely, nelz)
subroutine zwgl (Z, W, NP)
subroutine zwgll (Z, W, NP)
subroutine zwgj (Z, W, NP, ALPHA, BETA)
subroutine zwgjd (Z, W, NP, ALPHA, BETA)
subroutine zwglj (Z, W, NP, ALPHA, BETA)
subroutine zwgljd (Z, W, NP, ALPHA, BETA)
double precision function endw1 (N, ALPHA, BETA)
double precision function endw2 (N, ALPHA, BETA)
double precision function gammaf (X)
double precision function pnormj (N, ALPHA, BETA)
subroutine jacg (XJAC, NP, ALPHA, BETA)
subroutine jacobf (POLY, PDER, POLYM1, PDERM1, POLYM2, PDERM2, N, ALP, BET, X)
real function hgj (II, Z, ZGJ, NP, ALPHA, BETA)
double precision function hgjd (II, Z, ZGJ, NP, ALPHA, BETA)
real function hglj (II, Z, ZGLJ, NP, ALPHA, BETA)
double precision function hgljd (I, Z, ZGLJ, NP, ALPHA, BETA)
subroutine dgj (D, DT, Z, NZ, NZD, ALPHA, BETA)
subroutine dgjd (D, DT, Z, NZ, NZD, ALPHA, BETA)
subroutine dglj (D, DT, Z, NZ, NZD, ALPHA, BETA)
subroutine dgljd (D, DT, Z, NZ, NZD, ALPHA, BETA)
subroutine dgll (D, DT, Z, NZ, NZD)
real function hgll (I, Z, ZGLL, NZ)
real function hgl (I, Z, ZGL, NZ)
real function pnleg (Z, N)
real function pndleg (Z, N)
subroutine dgllgl (D, DT, ZM1, ZM2, IM12, NZM1, NZM2, ND1, ND2)
subroutine dgljgj (D, DT, ZGL, ZG, IGLG, NPGL, NPG, ND1, ND2, ALPHA, BETA)
subroutine dgljgjd (D, DT, ZGL, ZG, IGLG, NPGL, NPG, ND1, ND2, ALPHA, BETA)
subroutine iglm (I12, IT12, Z1, Z2, NZ1, NZ2, ND1, ND2)
subroutine igllm (I12, IT12, Z1, Z2, NZ1, NZ2, ND1, ND2)
subroutine igjm (I12, IT12, Z1, Z2, NZ1, NZ2, ND1, ND2, ALPHA, BETA)
subroutine igljm (I12, IT12, Z1, Z2, NZ1, NZ2, ND1, ND2, ALPHA, BETA)
function mod1 (i, n)
Function/Subroutine Documentation
subroutine dgj (real, dimension(nzd,nzd) D, real, dimension(nzd,nzd) DT, real, dimension(1) Z, NZ, NZD, real ALPHA, real BETA)
Definition at line 738 of file big_post.f.
References dgjd(), i, j, and nz.
subroutine dgjd (double precision, dimension(nzd,nzd) D, double precision, dimension(nzd,nzd) DT, double precision, dimension(1) Z, NZ, NZD, double precision ALPHA, double precision BETA)
Definition at line 779 of file big_post.f.
References i, j, jacobf(), n, and nz.
subroutine dglj (real, dimension(nzd,nzd) D, real, dimension(nzd,nzd) DT, real, dimension(1) Z, NZ, NZD, real ALPHA, real BETA)
Definition at line 817 of file big_post.f.
References dgljd(), i, j, and nz.
subroutine dgljd (double precision, dimension(nzd,nzd) D, double precision, dimension(nzd,nzd) DT, double precision, dimension(1) Z, NZ, NZD, double precision ALPHA, double precision BETA)
Definition at line 858 of file big_post.f.
References i, j, jacobf(), n, and nz.
subroutine dgljgj (real, dimension(nd2,nd1) D, real, dimension(nd1,nd2) DT, real, dimension(nd1) ZGL, real, dimension(nd2) ZG, real, dimension(nd2,nd1) IGLG, NPGL, NPG, ND1, ND2, ALPHA, BETA)
Definition at line 1070 of file big_post.f.
References alpha, beta, dgljgjd(), i, and j.
subroutine dgljgjd (double precision, dimension(nd2,nd1) D, double precision, dimension(nd1,nd2) DT, double precision, dimension(nd1) ZGL, double precision, dimension(nd2) ZG, double precision, dimension(nd2,nd1) IGLG, NPGL, NPG, ND1, ND2, double precision ALPHA, double precision BETA)
Definition at line 1121 of file big_post.f.
References i, j, and jacobf().
subroutine dgll (real, dimension(nzd,nzd) D, real, dimension(nzd,nzd) DT, real, dimension(1) Z, NZ, NZD)
Definition at line 904 of file big_post.f.
References i, j, n, nz, and pnleg().
subroutine dgllgl (real, dimension(nd2,nd1) D, real, dimension(nd1,nd2) DT, real, dimension(nd1) ZM1, real, dimension(nd2) ZM2, real, dimension(nd2,nd1) IM12, NZM1, NZM2, ND1, ND2)
Definition at line 1035 of file big_post.f.
References pnleg().
double precision function endw1 (N, double precision ALPHA, double precision BETA)
Definition at line 396 of file big_post.f.
References alpha, beta, gammaf(), i, and n.
double precision function endw2 (N, double precision ALPHA, double precision BETA)
Definition at line 440 of file big_post.f.
References alpha, beta, gammaf(), i, and n.
double precision function gammaf (double precision X)
Definition at line 484 of file big_post.f.
References gammaf().
subroutine get_coords (x, y, z, e)
Definition at line 11 of file big_post.f.
subroutine get_exyz (integer ex, integer ey, integer ez, integer eg, nelx, nely, nelz)
Definition at line 106 of file big_post.f.
References mod1().
subroutine get_scalar (real, dimension(nx*nx*nx) s, integer ei, nx, inew)
Definition at line 15 of file big_post.f.
References exit(), get_coords(), get_exyz(), get_velocity(), i, j, nx, rr, and zwgll().
subroutine get_velocity (u, v, w, e)
Definition at line 7 of file big_post.f.
real function hgj (II, real Z, real, dimension(1) ZGJ, NP, real ALPHA, real BETA)
Definition at line 632 of file big_post.f.
References hgj(), hgjd(), and i.
double precision function hgjd (II, double precision Z, double precision, dimension(1) ZGJ, NP, double precision ALPHA, double precision BETA)
Definition at line 659 of file big_post.f.
References hgjd(), and jacobf().
real function hgl (I, Z, real, dimension(1) ZGL, NZ)
Definition at line 959 of file big_post.f.
References hgl(), i, n, nz, pndleg(), and pnleg().
real function hglj (II, real Z, real, dimension(1) ZGLJ, NP, real ALPHA, real BETA)
Definition at line 683 of file big_post.f.
References hglj(), hgljd(), and i.
double precision function hgljd (I, double precision Z, double precision, dimension(1) ZGLJ, NP, double precision ALPHA, double precision BETA)
Definition at line 710 of file big_post.f.
References hgljd(), i, jacobf(), and n.
real function hgll (I, Z, real, dimension(1) ZGLL, NZ)
Definition at line 938 of file big_post.f.
References hgll(), i, n, nz, pndleg(), and pnleg().
subroutine igjm (real, dimension(nd2,nd1) I12, real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, NZ1, NZ2, ND1, ND2, ALPHA, BETA)
Definition at line 1224 of file big_post.f.
References alpha, beta, hgj(), i, and j.
subroutine igljm (real, dimension(nd2,nd1) I12, real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, NZ1, NZ2, ND1, ND2, ALPHA, BETA)
Definition at line 1250 of file big_post.f.
References alpha, beta, hglj(), i, and j.
subroutine igllm (real, dimension(nd2,nd1) I12, real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, NZ1, NZ2, ND1, ND2)
Definition at line 1199 of file big_post.f.
References hgll(), i, and j.
subroutine iglm (real, dimension(nd2,nd1) I12, real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, NZ1, NZ2, ND1, ND2)
Definition at line 1174 of file big_post.f.
References hgl(), i, and j.
subroutine jacg (double precision, dimension(1) XJAC, NP, ALPHA, BETA)
Definition at line 534 of file big_post.f.
References alpha, beta, i, j, jacobf(), n, and swap().
subroutine jacobf (POLY, PDER, POLYM1, PDERM1, POLYM2, PDERM2, N, ALP, BET, X)
Definition at line 592 of file big_post.f.
References n.
function mod1 (i, n)
Definition at line 1276 of file big_post.f.
References i, mod1(), and n.
real function pndleg (Z, N)
Definition at line 1009 of file big_post.f.
References n, and pndleg().
real function pnleg (Z, N)
Definition at line 978 of file big_post.f.
References n, and pnleg().
double precision function pnormj (N, double precision ALPHA, double precision BETA)
Definition at line 508 of file big_post.f.
References gammaf(), i, n, and pnormj().
program tst ()
Definition at line 1 of file big_post.f.
References get_scalar(), and nx.
subroutine zwgj (real, dimension(1) Z, real, dimension(1) W, NP, real ALPHA, real BETA)
Definition at line 242 of file big_post.f.
References i, and zwgjd().
subroutine zwgjd (double precision, dimension(1) Z, double precision, dimension(1) W, NP, double precision ALPHA, double precision BETA)
Definition at line 271 of file big_post.f.
References gammaf(), i, jacg(), jacobf(), n, and pnormj().
subroutine zwgl (real, dimension(1) Z, real, dimension(1) W, NP)
Definition at line 208 of file big_post.f.
References alpha, beta, and zwgj().
subroutine zwglj (real, dimension(1) Z, real, dimension(1) W, NP, real ALPHA, real BETA)
Definition at line 323 of file big_post.f.
References i, and zwgljd().
subroutine zwgljd (double precision, dimension(1) Z, double precision, dimension(1) W, NP, double precision ALPHA, double precision BETA)
Definition at line 352 of file big_post.f.
References endw1(), endw2(), i, jacobf(), n, and zwgjd().
subroutine zwgll (real, dimension(1) Z, real, dimension(1) W, NP)
Definition at line 225 of file big_post.f.
References alpha, beta, and zwglj().