KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/bit_mask.c File Reference
bit_mask.c File Reference
#include "const.h"
#include "bit_mask.h"
#include "error.h"
Functions
void bm_to_proc (register char *ptr, int p_mask, register int *msg_list)
int ct_bits (register char *ptr, int n)
int div_ceil (register int numer, register int denom)
int len_bit_mask (register int num_items)
void set_bit_mask (register int *bm, int len, int val)
int len_buf (int item_size, int num_items)
Function Documentation
void bm_to_proc (register char * ptr, int p_mask, register int * msg_list)
Definition at line 37 of file bit_mask.c.
References i, and tmp.
int ct_bits (register char * ptr, int n)
Definition at line 106 of file bit_mask.c.
References i, n, and tmp.
int div_ceil (register int numer, register int denom)
Definition at line 138 of file bit_mask.c.
References error_msg_fatal().
int len_bit_mask (register int num_items)
Definition at line 164 of file bit_mask.c.
References error_msg_fatal(), and tmp.
int len_buf (int item_size, int num_items)
Definition at line 229 of file bit_mask.c.
References tmp.
void set_bit_mask (register int * bm, int len, int val)
Definition at line 194 of file bit_mask.c.
References error_msg_fatal(), i, and len_bit_mask().