KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/blase.f File Reference
blase.f File Reference
Functions/Subroutines
real *8 function dasum (n, sx, incx)
subroutine daxpy (n, sa, sx, incx, sy, incy)
subroutine dcopy (n, sx, incx, sy, incy)
real *8 function ddot (n, sx, incx, sy, incy)
subroutine dgemm (TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine dgemv (trans, m, n, alpha, a, lda, x, incx, beta, y, incy)
subroutine dger (M, N, ALPHA, X, INCX, Y, INCY, A, LDA)
real *8 function dnrm2 (n, sx, incx)
subroutine drot (n, sx, incx, sy, incy, c, s)
subroutine drotg (sa, sb, c, s)
subroutine dscal (n, sa, sx, incx)
subroutine dswap (n, sx, incx, sy, incy)
subroutine dsymm (SIDE, UPLO, M, N, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine dsymv (UPLO, N, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine dsyr2 (UPLO, N, ALPHA, X, INCX, Y, INCY, A, LDA)
subroutine dsyr2k (UPLO, TRANS, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine dsyrk (UPLO, TRANS, N, K, ALPHA, A, LDA, BETA, C, LDC)
subroutine dtrmm (SIDE, UPLO, TRANSA, DIAG, M, N, ALPHA, A, LDA, B, LDB)
subroutine dtrmv (UPLO, TRANS, DIAG, N, A, LDA, X, INCX)
subroutine dtrsm (SIDE, UPLO, TRANSA, DIAG, M, N, ALPHA, A, LDA, B, LDB)
subroutine dtrsv (uplo, trans, diag, n, a, lda, x, incx)
integer function idamax (n, sx, incx)
integer function isamax (n, sx, incx)
logical function lsame (CA, CB)
real function sasum (n, sx, incx)
subroutine saxpy (n, sa, sx, incx, sy, incy)
subroutine scopy (n, sx, incx, sy, incy)
real function sdot (n, sx, incx, sy, incy)
subroutine sgemm (TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine sgemv (trans, m, n, alpha, a, lda, x, incx, beta, y, incy)
subroutine sger (M, N, ALPHA, X, INCX, Y, INCY, A, LDA)
real function snrm2 (n, sx, incx)
subroutine srot (n, sx, incx, sy, incy, c, s)
subroutine srotg (sa, sb, c, s)
subroutine sscal (n, sa, sx, incx)
subroutine sswap (n, sx, incx, sy, incy)
subroutine ssymm (SIDE, UPLO, M, N, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine ssymv (UPLO, N, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine ssyr2 (UPLO, N, ALPHA, X, INCX, Y, INCY, A, LDA)
subroutine ssyr2k (UPLO, TRANS, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine ssyrk (UPLO, TRANS, N, K, ALPHA, A, LDA, BETA, C, LDC)
subroutine strmm (SIDE, UPLO, TRANSA, DIAG, M, N, ALPHA, A, LDA, B, LDB)
subroutine strmv (UPLO, TRANS, DIAG, N, A, LDA, X, INCX)
subroutine strsm (SIDE, UPLO, TRANSA, DIAG, M, N, ALPHA, A, LDA, B, LDB)
subroutine strsv (uplo, trans, diag, n, a, lda, x, incx)
subroutine xerbla (srname, info)
Function/Subroutine Documentation
real*8 function dasum (integer n, real*8, dimension(1) sx, integer incx)
Definition at line 3 of file blase.f.
References dasum().
subroutine daxpy (integer n, real*8 sa, real*8, dimension(1) sx, integer incx, real*8, dimension(1) sy, integer incy)
Definition at line 46 of file blase.f.
subroutine dcopy (integer n, real*8, dimension(1) sx, integer incx, real*8, dimension(1) sy, integer incy)
Definition at line 94 of file blase.f.
real*8 function ddot (integer n, real*8, dimension(1) sx, integer incx, real*8, dimension(1) sy, integer incy)
Definition at line 141 of file blase.f.
References beta, and ddot().
subroutine dgemm (character*1 TRANSA, character*1 TRANSB, integer M, integer N, integer K, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(ldb, *) B, integer LDB, double precision BETA, double precision, dimension(ldc, *) C, integer LDC)
Definition at line 190 of file blase.f.
References beta, and xerbla().
subroutine dgemv (character*1 trans, integer m, integer n, real*8 alpha, real, dimension(lda, *) a, integer lda, real, dimension(*) x, integer incx, real*8 beta, real, dimension(*) y, integer incy)
Definition at line 504 of file blase.f.
References xerbla().
subroutine dger (integer M, integer N, double precision ALPHA, double precision, dimension(*) X, integer INCX, double precision, dimension(*) Y, integer INCY, double precision, dimension(lda, *) A, integer LDA)
Definition at line 764 of file blase.f.
References xerbla().
real*8 function dnrm2 (integer n, real*8, dimension(1) sx, integer incx)
Definition at line 922 of file blase.f.
References dnrm2().
subroutine drot (integer n, real*8, dimension(1) sx, integer incx, real*8, dimension(1) sy, integer incy, real*8 c, real*8 s)
Definition at line 1051 of file blase.f.
subroutine drotg (real*8 sa, real*8 sb, real*8 c, real*8 s)
Definition at line 1088 of file blase.f.
subroutine dscal (integer n, real*8 sa, real*8, dimension(1) sx, integer incx)
Definition at line 1115 of file blase.f.
subroutine dswap (integer n, real*8, dimension(1) sx, integer incx, real*8, dimension(1) sy, integer incy)
Definition at line 1157 of file blase.f.
References beta, and tmp.
subroutine dsymm (character*1 SIDE, character*1 UPLO, integer M, integer N, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(ldb, *) B, integer LDB, double precision BETA, double precision, dimension(ldc, *) C, integer LDC)
Definition at line 1219 of file blase.f.
References beta, and xerbla().
subroutine dsymv (character*1 UPLO, integer N, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) X, integer INCX, double precision BETA, double precision, dimension(*) Y, integer INCY)
Definition at line 1513 of file blase.f.
References xerbla().
subroutine dsyr2 (character*1 UPLO, integer N, double precision ALPHA, double precision, dimension(*) X, integer INCX, double precision, dimension(*) Y, integer INCY, double precision, dimension(lda, *) A, integer LDA)
Definition at line 1774 of file blase.f.
References beta, and xerbla().
subroutine dsyr2k (character*1 UPLO, character*1 TRANS, integer N, integer K, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(ldb, *) B, integer LDB, double precision BETA, double precision, dimension(ldc, *) C, integer LDC)
Definition at line 2005 of file blase.f.
References beta, and xerbla().
subroutine dsyrk (character*1 UPLO, character*1 TRANS, integer N, integer K, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision BETA, double precision, dimension(ldc, *) C, integer LDC)
Definition at line 2332 of file blase.f.
References xerbla().
subroutine dtrmm (character*1 SIDE, character*1 UPLO, character*1 TRANSA, character*1 DIAG, integer M, integer N, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(ldb, *) B, integer LDB)
Definition at line 2626 of file blase.f.
References xerbla().
subroutine dtrmv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) X, integer INCX)
Definition at line 2980 of file blase.f.
References xerbla().
subroutine dtrsm (character*1 SIDE, character*1 UPLO, character*1 TRANSA, character*1 DIAG, integer M, integer N, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(ldb, *) B, integer LDB)
Definition at line 3267 of file blase.f.
References xerbla().
subroutine dtrsv (character*1 uplo, character*1 trans, character*1 diag, integer n, real*8, dimension(lda, *) a, integer lda, real*8, dimension(*) x, integer incx)
Definition at line 3645 of file blase.f.
References xerbla().
integer function idamax (integer n, real*8, dimension(1) sx, integer incx)
Definition at line 3935 of file blase.f.
References idamax().
integer function isamax (integer n, real, dimension(1) sx, integer incx)
Definition at line 3973 of file blase.f.
References isamax().
logical function lsame (character CA, character CB)
Definition at line 4011 of file blase.f.
References lsame().
real function sasum (integer n, real, dimension(1) sx, integer incx)
Definition at line 4097 of file blase.f.
References sasum().
subroutine saxpy (integer n, real sa, real, dimension(1) sx, integer incx, real, dimension(1) sy, integer incy)
Definition at line 4140 of file blase.f.
subroutine scopy (integer n, real, dimension(1) sx, integer incx, real, dimension(1) sy, integer incy)
Definition at line 4188 of file blase.f.
real function sdot (integer n, real, dimension(1) sx, integer incx, real, dimension(1) sy, integer incy)
Definition at line 4235 of file blase.f.
References beta, and sdot().
subroutine sgemm (character*1 TRANSA, character*1 TRANSB, integer M, integer N, integer K, real ALPHA, real, dimension(lda, *) A, integer LDA, real, dimension(ldb, *) B, integer LDB, real BETA, real, dimension(ldc, *) C, integer LDC)
Definition at line 4285 of file blase.f.
References beta, and xerbla().
subroutine sgemv (character*1 trans, integer m, integer n, real alpha, real, dimension(lda, *) a, integer lda, real, dimension(*) x, integer incx, real beta, real, dimension(*) y, integer incy)
Definition at line 4599 of file blase.f.
References xerbla().
subroutine sger (integer M, integer N, real ALPHA, real, dimension(*) X, integer INCX, real, dimension(*) Y, integer INCY, real, dimension(lda, *) A, integer LDA)
Definition at line 4859 of file blase.f.
References xerbla().
real function snrm2 (integer n, real, dimension(1) sx, integer incx)
Definition at line 5017 of file blase.f.
References snrm2().
subroutine srot (integer n, real, dimension(1) sx, integer incx, real, dimension(1) sy, integer incy, real c, real s)
Definition at line 5146 of file blase.f.
subroutine srotg (real sa, real sb, real c, real s)
Definition at line 5183 of file blase.f.
subroutine sscal (integer n, real sa, real, dimension(1) sx, integer incx)
Definition at line 5210 of file blase.f.
subroutine sswap (integer n, real, dimension(1) sx, integer incx, real, dimension(1) sy, integer incy)
Definition at line 5252 of file blase.f.
References beta, and tmp.
subroutine ssymm (character*1 SIDE, character*1 UPLO, integer M, integer N, real ALPHA, real, dimension(lda, *) A, integer LDA, real, dimension(ldb, *) B, integer LDB, real BETA, real, dimension(ldc, *) C, integer LDC)
Definition at line 5314 of file blase.f.
References beta, and xerbla().
subroutine ssymv (character*1 UPLO, integer N, real ALPHA, real, dimension(lda, *) A, integer LDA, real, dimension(*) X, integer INCX, real BETA, real, dimension(*) Y, integer INCY)
Definition at line 5608 of file blase.f.
References xerbla().
subroutine ssyr2 (character*1 UPLO, integer N, real ALPHA, real, dimension(*) X, integer INCX, real, dimension(*) Y, integer INCY, real, dimension(lda, *) A, integer LDA)
Definition at line 5869 of file blase.f.
References beta, and xerbla().
subroutine ssyr2k (character*1 UPLO, character*1 TRANS, integer N, integer K, real ALPHA, real, dimension(lda, *) A, integer LDA, real, dimension(ldb, *) B, integer LDB, real BETA, real, dimension(ldc, *) C, integer LDC)
Definition at line 6100 of file blase.f.
References beta, and xerbla().
subroutine ssyrk (character*1 UPLO, character*1 TRANS, integer N, integer K, real ALPHA, real, dimension(lda, *) A, integer LDA, real BETA, real, dimension(ldc, *) C, integer LDC)
Definition at line 6427 of file blase.f.
References xerbla().
subroutine strmm (character*1 SIDE, character*1 UPLO, character*1 TRANSA, character*1 DIAG, integer M, integer N, real ALPHA, real, dimension(lda, *) A, integer LDA, real, dimension(ldb, *) B, integer LDB)
Definition at line 6721 of file blase.f.
References xerbla().
subroutine strmv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, real, dimension(lda, *) A, integer LDA, real, dimension(*) X, integer INCX)
Definition at line 7075 of file blase.f.
References xerbla().
subroutine strsm (character*1 SIDE, character*1 UPLO, character*1 TRANSA, character*1 DIAG, integer M, integer N, real ALPHA, real, dimension(lda, *) A, integer LDA, real, dimension(ldb, *) B, integer LDB)
Definition at line 7362 of file blase.f.
References xerbla().
subroutine strsv (character*1 uplo, character*1 trans, character*1 diag, integer n, real, dimension(lda, *) a, integer lda, real, dimension(*) x, integer incx)
Definition at line 7740 of file blase.f.
References xerbla().
subroutine xerbla (character*6 srname, integer info)
Definition at line 8030 of file blase.f.