KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/3rd_party/blas.f File Reference
blas.f File Reference
Functions/Subroutines
subroutine caxpy (n, ca, cx, incx, cy, incy)
subroutine ccopy (n, cx, incx, cy, incy)
complex function cdotc (n, cx, incx, cy, incy)
complex function cdotu (n, cx, incx, cy, incy)
subroutine cgbmv (TRANS, M, N, KL, KU, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine cgemm (TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine cgemv (TRANS, M, N, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine cgerc (M, N, ALPHA, X, INCX, Y, INCY, A, LDA)
subroutine cgeru (M, N, ALPHA, X, INCX, Y, INCY, A, LDA)
subroutine chbmv (UPLO, N, K, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine chemm (SIDE, UPLO, M, N, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine chemv (UPLO, N, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine cher2 (UPLO, N, ALPHA, X, INCX, Y, INCY, A, LDA)
subroutine cher2k (UPLO, TRANS, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine cher (UPLO, N, ALPHA, X, INCX, A, LDA)
subroutine cherk (UPLO, TRANS, N, K, ALPHA, A, LDA, BETA, C, LDC)
subroutine chpmv (UPLO, N, ALPHA, AP, X, INCX, BETA, Y, INCY)
subroutine chpr2 (UPLO, N, ALPHA, X, INCX, Y, INCY, AP)
subroutine chpr (UPLO, N, ALPHA, X, INCX, AP)
subroutine crotg (ca, cb, c, s)
subroutine cscal (n, ca, cx, incx)
subroutine csrot (n, cx, incx, cy, incy, c, s)
subroutine csscal (n, sa, cx, incx)
subroutine cswap (n, cx, incx, cy, incy)
subroutine csymm (SIDE, UPLO, M, N, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine csyr2k (UPLO, TRANS, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine csyrk (UPLO, TRANS, N, K, ALPHA, A, LDA, BETA, C, LDC)
subroutine ctbmv (UPLO, TRANS, DIAG, N, K, A, LDA, X, INCX)
subroutine ctbsv (UPLO, TRANS, DIAG, N, K, A, LDA, X, INCX)
subroutine ctpmv (UPLO, TRANS, DIAG, N, AP, X, INCX)
subroutine ctpsv (UPLO, TRANS, DIAG, N, AP, X, INCX)
subroutine ctrmm (SIDE, UPLO, TRANSA, DIAG, M, N, ALPHA, A, LDA, B, LDB)
subroutine ctrmv (UPLO, TRANS, DIAG, N, A, LDA, X, INCX)
subroutine ctrsm (SIDE, UPLO, TRANSA, DIAG, M, N, ALPHA, A, LDA, B, LDB)
subroutine ctrsv (UPLO, TRANS, DIAG, N, A, LDA, X, INCX)
double precision function dasum (n, dx, incx)
subroutine daxpy (n, da, dx, incx, dy, incy)
double precision function dcabs1 (z)
subroutine dcopy (n, dx, incx, dy, incy)
double precision function ddot (n, dx, incx, dy, incy)
subroutine dgbmv (TRANS, M, N, KL, KU, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine dgemm (TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine dgemv (TRANS, M, N, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine dger (M, N, ALPHA, X, INCX, Y, INCY, A, LDA)
double precision function dnrm2 (N, X, INCX)
subroutine drot (n, dx, incx, dy, incy, c, s)
subroutine drotg (da, db, c, s)
subroutine drotm (N, DX, INCX, DY, INCY, DPARAM)
subroutine drotmg (DD1, DD2, DX1, DY1, DPARAM)
subroutine dsbmv (UPLO, N, K, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine dscal (n, da, dx, incx)
double precision function dsdot (N, SX, INCX, SY, INCY)
subroutine dspmv (UPLO, N, ALPHA, AP, X, INCX, BETA, Y, INCY)
subroutine dspr2 (UPLO, N, ALPHA, X, INCX, Y, INCY, AP)
subroutine dspr (UPLO, N, ALPHA, X, INCX, AP)
subroutine dswap (n, dx, incx, dy, incy)
subroutine dsymm (SIDE, UPLO, M, N, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine dsymv (UPLO, N, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine dsyr2 (UPLO, N, ALPHA, X, INCX, Y, INCY, A, LDA)
subroutine dsyr2k (UPLO, TRANS, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine dsyr (UPLO, N, ALPHA, X, INCX, A, LDA)
subroutine dsyrk (UPLO, TRANS, N, K, ALPHA, A, LDA, BETA, C, LDC)
subroutine dtbmv (UPLO, TRANS, DIAG, N, K, A, LDA, X, INCX)
subroutine dtbsv (UPLO, TRANS, DIAG, N, K, A, LDA, X, INCX)
subroutine dtpmv (UPLO, TRANS, DIAG, N, AP, X, INCX)
subroutine dtpsv (UPLO, TRANS, DIAG, N, AP, X, INCX)
subroutine dtrmm (SIDE, UPLO, TRANSA, DIAG, M, N, ALPHA, A, LDA, B, LDB)
subroutine dtrmv (UPLO, TRANS, DIAG, N, A, LDA, X, INCX)
subroutine dtrsm (SIDE, UPLO, TRANSA, DIAG, M, N, ALPHA, A, LDA, B, LDB)
subroutine dtrsv (UPLO, TRANS, DIAG, N, A, LDA, X, INCX)
double precision function dzasum (n, zx, incx)
double precision function dznrm2 (N, X, INCX)
integer function icamax (n, cx, incx)
integer function idamax (n, dx, incx)
integer function isamax (n, sx, incx)
integer function izamax (n, zx, incx)
logical function lsame (CA, CB)
real function sasum (n, sx, incx)
subroutine saxpy (n, sa, sx, incx, sy, incy)
real function scasum (n, cx, incx)
real function scnrm2 (N, X, INCX)
subroutine scopy (n, sx, incx, sy, incy)
real function sdot (n, sx, incx, sy, incy)
real function sdsdot (N, SB, SX, INCX, SY, INCY)
subroutine sgbmv (TRANS, M, N, KL, KU, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine sgemm (TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine sgemv (TRANS, M, N, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine sger (M, N, ALPHA, X, INCX, Y, INCY, A, LDA)
real function snrm2 (N, X, INCX)
subroutine srot (n, sx, incx, sy, incy, c, s)
subroutine srotg (sa, sb, c, s)
subroutine srotm (N, SX, INCX, SY, INCY, SPARAM)
subroutine srotmg (SD1, SD2, SX1, SY1, SPARAM)
subroutine ssbmv (UPLO, N, K, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine sscal (n, sa, sx, incx)
subroutine sspmv (UPLO, N, ALPHA, AP, X, INCX, BETA, Y, INCY)
subroutine sspr2 (UPLO, N, ALPHA, X, INCX, Y, INCY, AP)
subroutine sspr (UPLO, N, ALPHA, X, INCX, AP)
subroutine sswap (n, sx, incx, sy, incy)
subroutine ssymm (SIDE, UPLO, M, N, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine ssymv (UPLO, N, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine ssyr2 (UPLO, N, ALPHA, X, INCX, Y, INCY, A, LDA)
subroutine ssyr2k (UPLO, TRANS, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine ssyr (UPLO, N, ALPHA, X, INCX, A, LDA)
subroutine ssyrk (UPLO, TRANS, N, K, ALPHA, A, LDA, BETA, C, LDC)
subroutine stbmv (UPLO, TRANS, DIAG, N, K, A, LDA, X, INCX)
subroutine stbsv (UPLO, TRANS, DIAG, N, K, A, LDA, X, INCX)
subroutine stpmv (UPLO, TRANS, DIAG, N, AP, X, INCX)
subroutine stpsv (UPLO, TRANS, DIAG, N, AP, X, INCX)
subroutine strmm (SIDE, UPLO, TRANSA, DIAG, M, N, ALPHA, A, LDA, B, LDB)
subroutine strmv (UPLO, TRANS, DIAG, N, A, LDA, X, INCX)
subroutine strsm (SIDE, UPLO, TRANSA, DIAG, M, N, ALPHA, A, LDA, B, LDB)
subroutine strsv (UPLO, TRANS, DIAG, N, A, LDA, X, INCX)
subroutine xerbla (SRNAME, INFO)
subroutine zaxpy (n, za, zx, incx, zy, incy)
subroutine zcopy (n, zx, incx, zy, incy)
double complex function zdotc (n, zx, incx, zy, incy)
double complex function zdotu (n, zx, incx, zy, incy)
subroutine zdrot (n, zx, incx, zy, incy, c, s)
subroutine zdscal (n, da, zx, incx)
subroutine zgbmv (TRANS, M, N, KL, KU, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine zgemm (TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine zgemv (TRANS, M, N, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine zgerc (M, N, ALPHA, X, INCX, Y, INCY, A, LDA)
subroutine zgeru (M, N, ALPHA, X, INCX, Y, INCY, A, LDA)
subroutine zhbmv (UPLO, N, K, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine zhemm (SIDE, UPLO, M, N, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine zhemv (UPLO, N, ALPHA, A, LDA, X, INCX, BETA, Y, INCY)
subroutine zher2 (UPLO, N, ALPHA, X, INCX, Y, INCY, A, LDA)
subroutine zher2k (UPLO, TRANS, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine zher (UPLO, N, ALPHA, X, INCX, A, LDA)
subroutine zherk (UPLO, TRANS, N, K, ALPHA, A, LDA, BETA, C, LDC)
subroutine zhpmv (UPLO, N, ALPHA, AP, X, INCX, BETA, Y, INCY)
subroutine zhpr2 (UPLO, N, ALPHA, X, INCX, Y, INCY, AP)
subroutine zhpr (UPLO, N, ALPHA, X, INCX, AP)
subroutine zrotg (ca, cb, c, s)
subroutine zscal (n, za, zx, incx)
subroutine zswap (n, zx, incx, zy, incy)
subroutine zsymm (SIDE, UPLO, M, N, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine zsyr2k (UPLO, TRANS, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC)
subroutine zsyrk (UPLO, TRANS, N, K, ALPHA, A, LDA, BETA, C, LDC)
subroutine ztbmv (UPLO, TRANS, DIAG, N, K, A, LDA, X, INCX)
subroutine ztbsv (UPLO, TRANS, DIAG, N, K, A, LDA, X, INCX)
subroutine ztpmv (UPLO, TRANS, DIAG, N, AP, X, INCX)
subroutine ztpsv (UPLO, TRANS, DIAG, N, AP, X, INCX)
subroutine ztrmm (SIDE, UPLO, TRANSA, DIAG, M, N, ALPHA, A, LDA, B, LDB)
subroutine ztrmv (UPLO, TRANS, DIAG, N, A, LDA, X, INCX)
subroutine ztrsm (SIDE, UPLO, TRANSA, DIAG, M, N, ALPHA, A, LDA, B, LDB)
subroutine ztrsv (UPLO, TRANS, DIAG, N, A, LDA, X, INCX)
Function/Subroutine Documentation
subroutine caxpy (integer n, complex ca, complex, dimension(*) cx, integer incx, complex, dimension(*) cy, integer incy)
Definition at line 2 of file blas.f.
subroutine ccopy (integer n, complex, dimension(*) cx, integer incx, complex, dimension(*) cy, integer incy)
Definition at line 36 of file blas.f.
complex function cdotc (integer n, complex, dimension(*) cx, integer incx, complex, dimension(*) cy, integer incy)
Definition at line 69 of file blas.f.
complex function cdotu (integer n, complex, dimension(*) cx, integer incx, complex, dimension(*) cy, integer incy)
Definition at line 107 of file blas.f.
subroutine cgbmv (character*1 TRANS, integer M, integer N, integer KL, integer KU, complex ALPHA, complex, dimension(lda, *) A, integer LDA, complex, dimension(*) X, integer INCX, complex BETA, complex, dimension(*) Y, integer INCY)
Definition at line 145 of file blas.f.
References xerbla().
subroutine cgemm (character*1 TRANSA, character*1 TRANSB, integer M, integer N, integer K, complex ALPHA, complex, dimension(lda, *) A, integer LDA, complex, dimension(ldb, *) B, integer LDB, complex BETA, complex, dimension(ldc, *) C, integer LDC)
Definition at line 467 of file blas.f.
References xerbla().
subroutine cgemv (character*1 TRANS, integer M, integer N, complex ALPHA, complex, dimension(lda, *) A, integer LDA, complex, dimension(*) X, integer INCX, complex BETA, complex, dimension(*) Y, integer INCY)
Definition at line 881 of file blas.f.
References xerbla().
subroutine cgerc (integer M, integer N, complex ALPHA, complex, dimension(*) X, integer INCX, complex, dimension(*) Y, integer INCY, complex, dimension(lda, *) A, integer LDA)
Definition at line 1161 of file blas.f.
References xerbla().
subroutine cgeru (integer M, integer N, complex ALPHA, complex, dimension(*) X, integer INCX, complex, dimension(*) Y, integer INCY, complex, dimension(lda, *) A, integer LDA)
Definition at line 1318 of file blas.f.
References xerbla().
subroutine chbmv (character*1 UPLO, integer N, integer K, complex ALPHA, complex, dimension(lda, *) A, integer LDA, complex, dimension(*) X, integer INCX, complex BETA, complex, dimension(*) Y, integer INCY)
Definition at line 1476 of file blas.f.
References xerbla().
subroutine chemm (character*1 SIDE, character*1 UPLO, integer M, integer N, complex ALPHA, complex, dimension(lda, *) A, integer LDA, complex, dimension(ldb, *) B, integer LDB, complex BETA, complex, dimension(ldc, *) C, integer LDC)
Definition at line 1785 of file blas.f.
References xerbla().
subroutine chemv (character*1 UPLO, integer N, complex ALPHA, complex, dimension(lda, *) A, integer LDA, complex, dimension(*) X, integer INCX, complex BETA, complex, dimension(*) Y, integer INCY)
Definition at line 2089 of file blas.f.
References xerbla().
subroutine cher (character*1 UPLO, integer N, real ALPHA, complex, dimension(*) X, integer INCX, complex, dimension(lda, *) A, integer LDA)
Definition at line 2974 of file blas.f.
References xerbla().
subroutine cher2 (character*1 UPLO, integer N, complex ALPHA, complex, dimension(*) X, integer INCX, complex, dimension(*) Y, integer INCY, complex, dimension(lda, *) A, integer LDA)
Definition at line 2354 of file blas.f.
References xerbla().
subroutine cher2k (character*1 UPLO, character*1 TRANS, integer N, integer K, complex ALPHA, complex, dimension(lda, *) A, integer LDA, complex, dimension(ldb, *) B, integer LDB, real BETA, complex, dimension(ldc, *) C, integer LDC)
Definition at line 2604 of file blas.f.
References xerbla().
subroutine cherk (character*1 UPLO, character*1 TRANS, integer N, integer K, real ALPHA, complex, dimension(lda, *) A, integer LDA, real BETA, complex, dimension(ldc, *) C, integer LDC)
Definition at line 3187 of file blas.f.
References xerbla().
subroutine chpmv (character*1 UPLO, integer N, complex ALPHA, complex, dimension(*) AP, complex, dimension(*) X, integer INCX, complex BETA, complex, dimension(*) Y, integer INCY)
Definition at line 3514 of file blas.f.
References xerbla().
subroutine chpr (character*1 UPLO, integer N, real ALPHA, complex, dimension(*) X, integer INCX, complex, dimension(*) AP)
Definition at line 4035 of file blas.f.
References xerbla().
subroutine chpr2 (character*1 UPLO, integer N, complex ALPHA, complex, dimension(*) X, integer INCX, complex, dimension(*) Y, integer INCY, complex, dimension(*) AP)
Definition at line 3784 of file blas.f.
References xerbla().
subroutine crotg (complex ca, complex cb, real c, complex s)
Definition at line 4252 of file blas.f.
subroutine cscal (integer n, complex ca, complex, dimension(*) cx, integer incx)
Definition at line 4272 of file blas.f.
subroutine csrot (integer n, complex, dimension(1) cx, integer incx, complex, dimension(1) cy, integer incy, real c, real s)
Definition at line 4300 of file blas.f.
subroutine csscal (integer n, real sa, complex, dimension(*) cx, integer incx)
Definition at line 4338 of file blas.f.
subroutine cswap (integer n, complex, dimension(*) cx, integer incx, complex, dimension(*) cy, integer incy)
Definition at line 4367 of file blas.f.
subroutine csymm (character*1 SIDE, character*1 UPLO, integer M, integer N, complex ALPHA, complex, dimension(lda, *) A, integer LDA, complex, dimension(ldb, *) B, integer LDB, complex BETA, complex, dimension(ldc, *) C, integer LDC)
Definition at line 4404 of file blas.f.
References xerbla().
subroutine csyr2k (character*1 UPLO, character*1 TRANS, integer N, integer K, complex ALPHA, complex, dimension(lda, *) A, integer LDA, complex, dimension(ldb, *) B, integer LDB, complex BETA, complex, dimension(ldc, *) C, integer LDC)
Definition at line 4700 of file blas.f.
References xerbla().
subroutine csyrk (character*1 UPLO, character*1 TRANS, integer N, integer K, complex ALPHA, complex, dimension(lda, *) A, integer LDA, complex BETA, complex, dimension(ldc, *) C, integer LDC)
Definition at line 5024 of file blas.f.
References xerbla().
subroutine ctbmv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, integer K, complex, dimension(lda, *) A, integer LDA, complex, dimension(*) X, integer INCX)
Definition at line 5316 of file blas.f.
References xerbla().
subroutine ctbsv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, integer K, complex, dimension(lda, *) A, integer LDA, complex, dimension(*) X, integer INCX)
Definition at line 5693 of file blas.f.
References xerbla().
subroutine ctpmv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, complex, dimension(*) AP, complex, dimension(*) X, integer INCX)
Definition at line 6074 of file blas.f.
References xerbla().
subroutine ctpsv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, complex, dimension(*) AP, complex, dimension(*) X, integer INCX)
Definition at line 6412 of file blas.f.
References xerbla().
subroutine ctrmm (character*1 SIDE, character*1 UPLO, character*1 TRANSA, character*1 DIAG, integer M, integer N, complex ALPHA, complex, dimension(lda, *) A, integer LDA, complex, dimension(ldb, *) B, integer LDB)
Definition at line 6754 of file blas.f.
References xerbla().
subroutine ctrmv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, complex, dimension(lda, *) A, integer LDA, complex, dimension(*) X, integer INCX)
Definition at line 7145 of file blas.f.
References xerbla().
subroutine ctrsm (character*1 SIDE, character*1 UPLO, character*1 TRANSA, character*1 DIAG, integer M, integer N, complex ALPHA, complex, dimension(lda, *) A, integer LDA, complex, dimension(ldb, *) B, integer LDB)
Definition at line 7467 of file blas.f.
References xerbla().
subroutine ctrsv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, complex, dimension(lda, *) A, integer LDA, complex, dimension(*) X, integer INCX)
Definition at line 7880 of file blas.f.
References xerbla().
double precision function dasum (integer n, double precision, dimension(*) dx, integer incx)
Definition at line 8204 of file blas.f.
subroutine daxpy (integer n, double precision da, double precision, dimension(*) dx, integer incx, double precision, dimension(*) dy, integer incy)
Definition at line 8247 of file blas.f.
double precision function dcabs1 (double complex z)
Definition at line 8295 of file blas.f.
subroutine dcopy (integer n, double precision, dimension(*) dx, integer incx, double precision, dimension(*) dy, integer incy)
Definition at line 8303 of file blas.f.
double precision function ddot (integer n, double precision, dimension(*) dx, integer incx, double precision, dimension(*) dy, integer incy)
Definition at line 8353 of file blas.f.
subroutine dgbmv (character*1 TRANS, integer M, integer N, integer KL, integer KU, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) X, integer INCX, double precision BETA, double precision, dimension(*) Y, integer INCY)
Definition at line 8403 of file blas.f.
References xerbla().
subroutine dgemm (character*1 TRANSA, character*1 TRANSB, integer M, integer N, integer K, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(ldb, *) B, integer LDB, double precision BETA, double precision, dimension(ldc, *) C, integer LDC)
Definition at line 8703 of file blas.f.
References xerbla().
subroutine dgemv (character*1 TRANS, integer M, integer N, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) X, integer INCX, double precision BETA, double precision, dimension(*) Y, integer INCY)
Definition at line 9016 of file blas.f.
References xerbla().
subroutine dger (integer M, integer N, double precision ALPHA, double precision, dimension(*) X, integer INCX, double precision, dimension(*) Y, integer INCY, double precision, dimension(lda, *) A, integer LDA)
Definition at line 9276 of file blas.f.
References xerbla().
double precision function dnrm2 (integer N, double precision, dimension(*) X, integer INCX)
Definition at line 9433 of file blas.f.
subroutine drot (integer n, double precision, dimension(*) dx, integer incx, double precision, dimension(*) dy, integer incy, double precision c, double precision s)
Definition at line 9493 of file blas.f.
subroutine drotg (double precision da, double precision db, double precision c, double precision s)
Definition at line 9530 of file blas.f.
subroutine drotm (N, double precision, dimension(1) DX, INCX, double precision, dimension(1) DY, INCY, double precision, dimension(5) DPARAM)
Definition at line 9557 of file blas.f.
References i, and n.
subroutine drotmg (double precision DD1, double precision DD2, double precision DX1, double precision DY1, double precision, dimension(5) DPARAM)
Definition at line 9665 of file blas.f.
subroutine dsbmv (character*1 UPLO, integer N, integer K, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) X, integer INCX, double precision BETA, double precision, dimension(*) Y, integer INCY)
Definition at line 9835 of file blas.f.
References xerbla().
subroutine dscal (integer n, double precision da, double precision, dimension(*) dx, integer incx)
Definition at line 10137 of file blas.f.
double precision function dsdot (N, real, dimension(*) SX, INCX, real, dimension(*) SY, INCY)
Definition at line 10181 of file blas.f.
References i, and n.
subroutine dspmv (character*1 UPLO, integer N, double precision ALPHA, double precision, dimension(*) AP, double precision, dimension(*) X, integer INCX, double precision BETA, double precision, dimension(*) Y, integer INCY)
Definition at line 10254 of file blas.f.
References xerbla().
subroutine dspr (character*1 UPLO, integer N, double precision ALPHA, double precision, dimension(*) X, integer INCX, double precision, dimension(*) AP)
Definition at line 10745 of file blas.f.
References xerbla().
subroutine dspr2 (character*1 UPLO, integer N, double precision ALPHA, double precision, dimension(*) X, integer INCX, double precision, dimension(*) Y, integer INCY, double precision, dimension(*) AP)
Definition at line 10516 of file blas.f.
References xerbla().
subroutine dswap (integer n, double precision, dimension(*) dx, integer incx, double precision, dimension(*) dy, integer incy)
Definition at line 10943 of file blas.f.
subroutine dsymm (character*1 SIDE, character*1 UPLO, integer M, integer N, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(ldb, *) B, integer LDB, double precision BETA, double precision, dimension(ldc, *) C, integer LDC)
Definition at line 11000 of file blas.f.
References xerbla().
subroutine dsymv (character*1 UPLO, integer N, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) X, integer INCX, double precision BETA, double precision, dimension(*) Y, integer INCY)
Definition at line 11294 of file blas.f.
References xerbla().
subroutine dsyr (character*1 UPLO, integer N, double precision ALPHA, double precision, dimension(*) X, integer INCX, double precision, dimension(lda, *) A, integer LDA)
Definition at line 12112 of file blas.f.
References xerbla().
subroutine dsyr2 (character*1 UPLO, integer N, double precision ALPHA, double precision, dimension(*) X, integer INCX, double precision, dimension(*) Y, integer INCY, double precision, dimension(lda, *) A, integer LDA)
Definition at line 11555 of file blas.f.
References xerbla().
subroutine dsyr2k (character*1 UPLO, character*1 TRANS, integer N, integer K, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(ldb, *) B, integer LDB, double precision BETA, double precision, dimension(ldc, *) C, integer LDC)
Definition at line 11786 of file blas.f.
References xerbla().
subroutine dsyrk (character*1 UPLO, character*1 TRANS, integer N, integer K, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision BETA, double precision, dimension(ldc, *) C, integer LDC)
Definition at line 12310 of file blas.f.
References xerbla().
subroutine dtbmv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, integer K, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) X, integer INCX)
Definition at line 12603 of file blas.f.
References xerbla().
subroutine dtbsv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, integer K, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) X, integer INCX)
Definition at line 12945 of file blas.f.
References xerbla().
subroutine dtpmv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, double precision, dimension(*) AP, double precision, dimension(*) X, integer INCX)
Definition at line 13291 of file blas.f.
References xerbla().
subroutine dtpsv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, double precision, dimension(*) AP, double precision, dimension(*) X, integer INCX)
Definition at line 13590 of file blas.f.
References xerbla().
subroutine dtrmm (character*1 SIDE, character*1 UPLO, character*1 TRANSA, character*1 DIAG, integer M, integer N, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(ldb, *) B, integer LDB)
Definition at line 13893 of file blas.f.
References xerbla().
subroutine dtrmv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) X, integer INCX)
Definition at line 14247 of file blas.f.
References xerbla().
subroutine dtrsm (character*1 SIDE, character*1 UPLO, character*1 TRANSA, character*1 DIAG, integer M, integer N, double precision ALPHA, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(ldb, *) B, integer LDB)
Definition at line 14534 of file blas.f.
References xerbla().
subroutine dtrsv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) X, integer INCX)
Definition at line 14911 of file blas.f.
References xerbla().
double precision function dzasum (integer n, double complex, dimension(*) zx, integer incx)
Definition at line 15200 of file blas.f.
double precision function dznrm2 (integer N, complex*16, dimension(*) X, integer INCX)
Definition at line 15234 of file blas.f.
integer function icamax (integer n, complex, dimension(*) cx, integer incx)
Definition at line 15301 of file blas.f.
integer function idamax (integer n, double precision, dimension(*) dx, integer incx)
Definition at line 15344 of file blas.f.
integer function isamax (integer n, real, dimension(*) sx, integer incx)
Definition at line 15383 of file blas.f.
integer function izamax (integer n, double complex, dimension(*) zx, integer incx)
Definition at line 15422 of file blas.f.
logical function lsame (character CA, character CB)
Definition at line 15463 of file blas.f.
real function sasum (integer n, real, dimension(*) sx, integer incx)
Definition at line 15550 of file blas.f.
subroutine saxpy (integer n, real sa, real, dimension(*) sx, integer incx, real, dimension(*) sy, integer incy)
Definition at line 15594 of file blas.f.
real function scasum (integer n, complex, dimension(*) cx, integer incx)
Definition at line 15642 of file blas.f.
real function scnrm2 (integer N, complex, dimension(*) X, integer INCX)
Definition at line 15676 of file blas.f.
subroutine scopy (integer n, real, dimension(*) sx, integer incx, real, dimension(*) sy, integer incy)
Definition at line 15743 of file blas.f.
real function sdot (integer n, real, dimension(*) sx, integer incx, real, dimension(*) sy, integer incy)
Definition at line 15793 of file blas.f.
real function sdsdot (N, real SB, real, dimension(*) SX, INCX, real, dimension(*) SY, INCY)
Definition at line 15843 of file blas.f.
References i, and n.
subroutine sgbmv (character*1 TRANS, integer M, integer N, integer KL, integer KU, real ALPHA, real, dimension(lda, *) A, integer LDA, real, dimension(*) X, integer INCX, real BETA, real, dimension(*) Y, integer INCY)
Definition at line 15921 of file blas.f.
References xerbla().
subroutine sgemm (character*1 TRANSA, character*1 TRANSB, integer M, integer N, integer K, real ALPHA, real, dimension(lda, *) A, integer LDA, real, dimension(ldb, *) B, integer LDB, real BETA, real, dimension(ldc, *) C, integer LDC)
Definition at line 16221 of file blas.f.
References xerbla().
subroutine sgemv (character*1 TRANS, integer M, integer N, real ALPHA, real, dimension(lda, *) A, integer LDA, real, dimension(*) X, integer INCX, real BETA, real, dimension(*) Y, integer INCY)
Definition at line 16534 of file blas.f.
References xerbla().
subroutine sger (integer M, integer N, real ALPHA, real, dimension(*) X, integer INCX, real, dimension(*) Y, integer INCY, real, dimension(lda, *) A, integer LDA)
Definition at line 16794 of file blas.f.
References xerbla().
real function snrm2 (integer N, real, dimension(*) X, integer INCX)
Definition at line 16951 of file blas.f.
subroutine srot (integer n, real, dimension(*) sx, integer incx, real, dimension(*) sy, integer incy, real c, real s)
Definition at line 17011 of file blas.f.
subroutine srotg (real sa, real sb, real c, real s)
Definition at line 17048 of file blas.f.
subroutine srotm (N, dimension(1) SX, INCX, dimension(1) SY, INCY, dimension(5) SPARAM)
Definition at line 17075 of file blas.f.
References i, and n.
subroutine srotmg (SD1, SD2, SX1, SY1, dimension(5) SPARAM)
Definition at line 17181 of file blas.f.
subroutine ssbmv (character*1 UPLO, integer N, integer K, real ALPHA, real, dimension(lda, *) A, integer LDA, real, dimension(*) X, integer INCX, real BETA, real, dimension(*) Y, integer INCY)
Definition at line 17348 of file blas.f.
References xerbla().
subroutine sscal (integer n, real sa, real, dimension(*) sx, integer incx)
Definition at line 17650 of file blas.f.
subroutine sspmv (character*1 UPLO, integer N, real ALPHA, real, dimension(*) AP, real, dimension(*) X, integer INCX, real BETA, real, dimension(*) Y, integer INCY)
Definition at line 17693 of file blas.f.
References xerbla().
subroutine sspr (character*1 UPLO, integer N, real ALPHA, real, dimension(*) X, integer INCX, real, dimension(*) AP)
Definition at line 18184 of file blas.f.
References xerbla().
subroutine sspr2 (character*1 UPLO, integer N, real ALPHA, real, dimension(*) X, integer INCX, real, dimension(*) Y, integer INCY, real, dimension(*) AP)
Definition at line 17955 of file blas.f.
References xerbla().
subroutine sswap (integer n, real, dimension(*) sx, integer incx, real, dimension(*) sy, integer incy)
Definition at line 18382 of file blas.f.
subroutine ssymm (character*1 SIDE, character*1 UPLO, integer M, integer N, real ALPHA, real, dimension(lda, *) A, integer LDA, real, dimension(ldb, *) B, integer LDB, real BETA, real, dimension(ldc, *) C, integer LDC)
Definition at line 18439 of file blas.f.
References xerbla().
subroutine ssymv (character*1 UPLO, integer N, real ALPHA, real, dimension(lda, *) A, integer LDA, real, dimension(*) X, integer INCX, real BETA, real, dimension(*) Y, integer INCY)
Definition at line 18733 of file blas.f.
References xerbla().
subroutine ssyr (character*1 UPLO, integer N, real ALPHA, real, dimension(*) X, integer INCX, real, dimension(lda, *) A, integer LDA)
Definition at line 19551 of file blas.f.
References xerbla().
subroutine ssyr2 (character*1 UPLO, integer N, real ALPHA, real, dimension(*) X, integer INCX, real, dimension(*) Y, integer INCY, real, dimension(lda, *) A, integer LDA)
Definition at line 18994 of file blas.f.
References xerbla().
subroutine ssyr2k (character*1 UPLO, character*1 TRANS, integer N, integer K, real ALPHA, real, dimension(lda, *) A, integer LDA, real, dimension(ldb, *) B, integer LDB, real BETA, real, dimension(ldc, *) C, integer LDC)
Definition at line 19225 of file blas.f.
References xerbla().
subroutine ssyrk (character*1 UPLO, character*1 TRANS, integer N, integer K, real ALPHA, real, dimension(lda, *) A, integer LDA, real BETA, real, dimension(ldc, *) C, integer LDC)
Definition at line 19749 of file blas.f.
References xerbla().
subroutine stbmv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, integer K, real, dimension(lda, *) A, integer LDA, real, dimension(*) X, integer INCX)
Definition at line 20042 of file blas.f.
References xerbla().
subroutine stbsv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, integer K, real, dimension(lda, *) A, integer LDA, real, dimension(*) X, integer INCX)
Definition at line 20384 of file blas.f.
References xerbla().
subroutine stpmv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, real, dimension(*) AP, real, dimension(*) X, integer INCX)
Definition at line 20730 of file blas.f.
References xerbla().
subroutine stpsv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, real, dimension(*) AP, real, dimension(*) X, integer INCX)
Definition at line 21029 of file blas.f.
References xerbla().
subroutine strmm (character*1 SIDE, character*1 UPLO, character*1 TRANSA, character*1 DIAG, integer M, integer N, real ALPHA, real, dimension(lda, *) A, integer LDA, real, dimension(ldb, *) B, integer LDB)
Definition at line 21332 of file blas.f.
References xerbla().
subroutine strmv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, real, dimension(lda, *) A, integer LDA, real, dimension(*) X, integer INCX)
Definition at line 21686 of file blas.f.
References xerbla().
subroutine strsm (character*1 SIDE, character*1 UPLO, character*1 TRANSA, character*1 DIAG, integer M, integer N, real ALPHA, real, dimension(lda, *) A, integer LDA, real, dimension(ldb, *) B, integer LDB)
Definition at line 21973 of file blas.f.
References xerbla().
subroutine strsv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, real, dimension(lda, *) A, integer LDA, real, dimension(*) X, integer INCX)
Definition at line 22350 of file blas.f.
References xerbla().
subroutine xerbla (character*6 SRNAME, integer INFO)
Definition at line 22639 of file blas.f.
subroutine zaxpy (integer n, double complex za, double complex, dimension(*) zx, integer incx, double complex, dimension(*) zy, integer incy)
Definition at line 22682 of file blas.f.
subroutine zcopy (integer n, double complex, dimension(*) zx, integer incx, double complex, dimension(*) zy, integer incy)
Definition at line 22716 of file blas.f.
double complex function zdotc (integer n, double complex, dimension(*) zx, integer incx, double complex, dimension(*) zy, integer incy)
Definition at line 22749 of file blas.f.
double complex function zdotu (integer n, double complex, dimension(*) zx, integer incx, double complex, dimension(*) zy, integer incy)
Definition at line 22785 of file blas.f.
subroutine zdrot (integer n, double complex, dimension(1) zx, integer incx, double complex, dimension(1) zy, integer incy, double precision c, double precision s)
Definition at line 22821 of file blas.f.
subroutine zdscal (integer n, double precision da, double complex, dimension(*) zx, integer incx)
Definition at line 22859 of file blas.f.
subroutine zgbmv (character*1 TRANS, integer M, integer N, integer KL, integer KU, complex*16 ALPHA, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(*) X, integer INCX, complex*16 BETA, complex*16, dimension(*) Y, integer INCY)
Definition at line 22890 of file blas.f.
References xerbla().
subroutine zgemm (character*1 TRANSA, character*1 TRANSB, integer M, integer N, integer K, complex*16 ALPHA, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(ldb, *) B, integer LDB, complex*16 BETA, complex*16, dimension(ldc, *) C, integer LDC)
Definition at line 23212 of file blas.f.
References xerbla().
subroutine zgemv (character*1 TRANS, integer M, integer N, complex*16 ALPHA, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(*) X, integer INCX, complex*16 BETA, complex*16, dimension(*) Y, integer INCY)
Definition at line 23627 of file blas.f.
References xerbla().
subroutine zgerc (integer M, integer N, complex*16 ALPHA, complex*16, dimension(*) X, integer INCX, complex*16, dimension(*) Y, integer INCY, complex*16, dimension(lda, *) A, integer LDA)
Definition at line 23907 of file blas.f.
References xerbla().
subroutine zgeru (integer M, integer N, complex*16 ALPHA, complex*16, dimension(*) X, integer INCX, complex*16, dimension(*) Y, integer INCY, complex*16, dimension(lda, *) A, integer LDA)
Definition at line 24064 of file blas.f.
References xerbla().
subroutine zhbmv (character*1 UPLO, integer N, integer K, complex*16 ALPHA, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(*) X, integer INCX, complex*16 BETA, complex*16, dimension(*) Y, integer INCY)
Definition at line 24222 of file blas.f.
References xerbla().
subroutine zhemm (character*1 SIDE, character*1 UPLO, integer M, integer N, complex*16 ALPHA, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(ldb, *) B, integer LDB, complex*16 BETA, complex*16, dimension(ldc, *) C, integer LDC)
Definition at line 24531 of file blas.f.
References xerbla().
subroutine zhemv (character*1 UPLO, integer N, complex*16 ALPHA, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(*) X, integer INCX, complex*16 BETA, complex*16, dimension(*) Y, integer INCY)
Definition at line 24835 of file blas.f.
References xerbla().
subroutine zher (character*1 UPLO, integer N, double precision ALPHA, complex*16, dimension(*) X, integer INCX, complex*16, dimension(lda, *) A, integer LDA)
Definition at line 25721 of file blas.f.
References xerbla().
subroutine zher2 (character*1 UPLO, integer N, complex*16 ALPHA, complex*16, dimension(*) X, integer INCX, complex*16, dimension(*) Y, integer INCY, complex*16, dimension(lda, *) A, integer LDA)
Definition at line 25100 of file blas.f.
References xerbla().
subroutine zher2k (character UPLO, character TRANS, integer N, integer K, complex*16 ALPHA, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(ldb, *) B, integer LDB, double precision BETA, complex*16, dimension(ldc, *) C, integer LDC)
Definition at line 25350 of file blas.f.
References xerbla().
subroutine zherk (character UPLO, character TRANS, integer N, integer K, double precision ALPHA, complex*16, dimension(lda, *) A, integer LDA, double precision BETA, complex*16, dimension(ldc, *) C, integer LDC)
Definition at line 25933 of file blas.f.
References xerbla().
subroutine zhpmv (character*1 UPLO, integer N, complex*16 ALPHA, complex*16, dimension(*) AP, complex*16, dimension(*) X, integer INCX, complex*16 BETA, complex*16, dimension(*) Y, integer INCY)
Definition at line 26263 of file blas.f.
References xerbla().
subroutine zhpr (character*1 UPLO, integer N, double precision ALPHA, complex*16, dimension(*) X, integer INCX, complex*16, dimension(*) AP)
Definition at line 26784 of file blas.f.
References xerbla().
subroutine zhpr2 (character*1 UPLO, integer N, complex*16 ALPHA, complex*16, dimension(*) X, integer INCX, complex*16, dimension(*) Y, integer INCY, complex*16, dimension(*) AP)
Definition at line 26533 of file blas.f.
References xerbla().
subroutine zrotg (double complex ca, double complex cb, double precision c, double complex s)
Definition at line 27001 of file blas.f.
subroutine zscal (integer n, double complex za, double complex, dimension(*) zx, integer incx)
Definition at line 27022 of file blas.f.
subroutine zswap (integer n, double complex, dimension(*) zx, integer incx, double complex, dimension(*) zy, integer incy)
Definition at line 27051 of file blas.f.
subroutine zsymm (character*1 SIDE, character*1 UPLO, integer M, integer N, complex*16 ALPHA, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(ldb, *) B, integer LDB, complex*16 BETA, complex*16, dimension(ldc, *) C, integer LDC)
Definition at line 27088 of file blas.f.
References xerbla().
subroutine zsyr2k (character*1 UPLO, character*1 TRANS, integer N, integer K, complex*16 ALPHA, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(ldb, *) B, integer LDB, complex*16 BETA, complex*16, dimension(ldc, *) C, integer LDC)
Definition at line 27384 of file blas.f.
References xerbla().
subroutine zsyrk (character*1 UPLO, character*1 TRANS, integer N, integer K, complex*16 ALPHA, complex*16, dimension(lda, *) A, integer LDA, complex*16 BETA, complex*16, dimension(ldc, *) C, integer LDC)
Definition at line 27708 of file blas.f.
References xerbla().
subroutine ztbmv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, integer K, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(*) X, integer INCX)
Definition at line 28000 of file blas.f.
References xerbla().
subroutine ztbsv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, integer K, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(*) X, integer INCX)
Definition at line 28377 of file blas.f.
References xerbla().
subroutine ztpmv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, complex*16, dimension(*) AP, complex*16, dimension(*) X, integer INCX)
Definition at line 28758 of file blas.f.
References xerbla().
subroutine ztpsv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, complex*16, dimension(*) AP, complex*16, dimension(*) X, integer INCX)
Definition at line 29096 of file blas.f.
References xerbla().
subroutine ztrmm (character*1 SIDE, character*1 UPLO, character*1 TRANSA, character*1 DIAG, integer M, integer N, complex*16 ALPHA, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(ldb, *) B, integer LDB)
Definition at line 29438 of file blas.f.
References xerbla().
subroutine ztrmv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(*) X, integer INCX)
Definition at line 29829 of file blas.f.
References xerbla().
subroutine ztrsm (character*1 SIDE, character*1 UPLO, character*1 TRANSA, character*1 DIAG, integer M, integer N, complex*16 ALPHA, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(ldb, *) B, integer LDB)
Definition at line 30151 of file blas.f.
References xerbla().
subroutine ztrsv (character*1 UPLO, character*1 TRANS, character*1 DIAG, integer N, complex*16, dimension(lda, *) A, integer LDA, complex*16, dimension(*) X, integer INCX)
Definition at line 30564 of file blas.f.
References xerbla().