KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/bound.f File Reference
bound.f File Reference
Functions/Subroutines
subroutine overlap (iel, iside, ielo, isideo)
subroutine inflow (IEL, ISIDE, IF, cbcI)
subroutine letbc (f, e, ifld, bclab)
subroutine chkbcs
subroutine fndsida (kside, ke, iside, ie, if)
subroutine qchk (ie, iside, je, jside, ifld)
function i_periodic (iside, ie, ifld, bclab)
subroutine getnormals (unx, uny, unz, ie, is, x, y, z, ld, ndim)
subroutine vcross_normal (u, r2, v, w)
subroutine out_cent
subroutine user_bc1
subroutine user_bc2
subroutine user_bc
subroutine set_match_p (je, jf, ie, if)
function get_dist_ctr (x, y, z, f, ndim)
subroutine autoperiodz (dir, tol, cb_clear, xyz, m)
subroutine bound
subroutine semi_init_bcs (maxlev, needbc, if1)
subroutine first_bc_menu (needbc, if1)
subroutine rehighlight (e, f, jlevel)
subroutine rezoom
subroutine black_out_level
subroutine set_up_level (num_on_this_level, ifld, jlevel)
subroutine check_end_level (icontinue, jlevel, ifld)
subroutine flash_side_a (ifade, iflash, e, f, fcorns, jlevel, ifld)
subroutine flash_element_b (ifade, iflash, e, f, jlevel, ifld, fcorns)
subroutine set_bc_fld (ifld)
subroutine autoperiod
subroutine autoperiod1 (nfail, tol)
subroutine autoperiod2 (nfail, tol)
subroutine get_vec_side (vec3, iside, ie)
subroutine fndsidb (kside, ke, iside, ie, if, tol)
function dif_rel_inf_norm (x, y, n)
Function/Subroutine Documentation
subroutine autoperiod ()
Definition at line 2116 of file bound.f.
References autoperiod1(), autoperiod2(), autoperiodz(), capit(), gencen(), mkside(), prs(), and res().
subroutine autoperiod1 (nfail, tol)
Definition at line 2162 of file bound.f.
References fndsidb(), gencen(), get_lattice_per_bc(), if(), letbc(), mkside(), and rzero().
subroutine autoperiod2 (nfail, tol)
Definition at line 2247 of file bound.f.
References fndsidb(), gencen(), get_lattice_per_bc(), if(), mkside(), and rzero().
subroutine autoperiodz (character*1 dir, tol, character*3 cb_clear, real, dimension(27,nelm) xyz, m)
Definition at line 952 of file bound.f.
References get_dist_ctr(), glmax(), glmin(), izero(), n, scale(), set_match_p(), vlmax(), and vlmin().
subroutine black_out_level ()
Definition at line 1264 of file bound.f.
References beginp(), color, draw(), endp(), fillp(), xphy(), and yphy().
subroutine bound ()
Definition at line 1066 of file bound.f.
References drelev(), first_bc_menu(), i, if(), period_check(), prs(), semi_init_bcs(), and set_bc_fld().
subroutine check_end_level (icontinue, jlevel, ifld)
Definition at line 1310 of file bound.f.
References prs().
subroutine chkbcs ()
Definition at line 296 of file bound.f.
References dif_rel_inf_norm(), if(), j, overlap(), prii(), prs(), and qchk().
function dif_rel_inf_norm (real, dimension(n) x, real, dimension(n) y, n)
Definition at line 2467 of file bound.f.
References dmax, i, and n.
subroutine first_bc_menu (needbc, if1)
Definition at line 1176 of file bound.f.
References chkbcs(), menu(), mesgen(), period_check(), prexit(), and prs().
subroutine flash_element_b (ifade, iflash, integer e, integer f, jlevel, ifld, integer, dimension (4,6) fcorns)
Definition at line 1408 of file bound.f.
References color, drawc(), drawed(), drawsc(), drelev(), ff(), letbc(), movec(), movesc(), xisom(), xphy(), xscr(), yisom(), yphy(), and yscr().
subroutine flash_side_a (ifade, iflash, integer e, integer f, integer, dimension (4,6) fcorns, jlevel, ifld)
Definition at line 1371 of file bound.f.
References color, drawc(), drelev(), ff(), hilites(), letbc(), movec(), xisom(), xphy(), xscr(), yisom(), yphy(), and yscr().
subroutine fndsida (kside, ke, iside, ie, if)
Definition at line 465 of file bound.f.
References copy(), cross(), dist2(), dotprod(), gencen(), if(), mkside(), norm3d(), and prs().
subroutine fndsidb (kside, ke, iside, ie, if, tol)
Definition at line 2351 of file bound.f.
References copy(), cross(), dist2(), dotprod(), get_vec_side(), if(), and norm3d().
function get_dist_ctr (real, dimension(3,3,3) x, real, dimension(3,3,3) y, real, dimension(3,3,3) z, integer f, ndim)
Definition at line 914 of file bound.f.
References facind(), i, i0, j, and nz.
subroutine get_vec_side (real, dimension(3) vec3, iside, ie)
Definition at line 2317 of file bound.f.
References cross(), and norm3d().
subroutine getnormals (unx, uny, unz, ie, is, real, dimension(ld,8) x, real, dimension(ld,8) y, real, dimension(ld,8) z, ld, ndim)
Definition at line 621 of file bound.f.
References vcross_normal().
function i_periodic (iside, ie, ifld, character*1, dimension(2) bclab)
Definition at line 589 of file bound.f.
References fndsida(), letbc(), prs(), and prsii().
subroutine inflow (IEL, ISIDE, IF, character*3 cbcI)
Definition at line 62 of file bound.f.
References i, if(), overlap(), prs(), prsis(), and res().
subroutine letbc (integer f, integer e, ifld, character bclab)
Definition at line 264 of file bound.f.
References beginp(), draw(), endp(), fillp(), and gwrite().
subroutine out_cent ()
Definition at line 702 of file bound.f.
References gencen().
subroutine overlap (iel, iside, ielo, isideo)
Definition at line 19 of file bound.f.
References prs(), rmax(), and rmin().
subroutine qchk (ie, iside, je, jside, ifld)
Definition at line 579 of file bound.f.
References j.
subroutine rehighlight (integer e, integer f, jlevel)
Definition at line 1215 of file bound.f.
References color, drawed(), drawsc(), movec(), and movesc().
subroutine rezoom ()
Definition at line 1248 of file bound.f.
References drawel(), drgrid(), drmenu(), refresh(), and setzoom().
subroutine semi_init_bcs (maxlev, needbc, if1)
Definition at line 1108 of file bound.f.
References letbc().
subroutine set_bc_fld (ifld)
Definition at line 1460 of file bound.f.
References autoperiod(), blank(), check_end_level(), copy(), flash_element_b(), flash_side_a(), fndsida(), i, inflow(), letbc(), menu(), mouse(), overlap(), prs(), prsi(), prsii(), rehighlight(), rei(), rer(), res(), rezoom(), rmin(), rzero(), set_up_level(), and xscr().
subroutine set_match_p (je, jf, ie, if)
Definition at line 887 of file bound.f.
subroutine set_up_level (num_on_this_level, ifld, jlevel)
Definition at line 1279 of file bound.f.
References black_out_level(), color, drawel(), drawis(), drelev(), and letbc().
subroutine user_bc ()
Definition at line 828 of file bound.f.
References nx, nz, and rzero().
subroutine user_bc1 ()
Definition at line 722 of file bound.f.
References getnormals(), and i_periodic().
subroutine user_bc2 ()
Definition at line 773 of file bound.f.
References getnormals(), nx, nz, and rzero().
subroutine vcross_normal (real, dimension(3) u, r2, real, dimension(3) v, real, dimension(3) w)
Definition at line 679 of file bound.f.