KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/bss_malloc.c File Reference
bss_malloc.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "const.h"
#include "types.h"
#include "ivec.h"
#include "error.h"
#include "bss_malloc.h"
Functions
void * malloc (size_t size)
void perm_init (void)
void * perm_malloc (size_t size)
void perm_free (void *ptr)
void perm_stats (void)
int perm_frees (void)
int perm_calls (void)
void bss_init (void)
void * bss_malloc (size_t size)
void bss_free (void *ptr)
void bss_stats (void)
int bss_frees (void)
int bss_calls (void)
Function Documentation
int bss_calls (void)
Definition at line 453 of file bss_malloc.c.
void bss_free (void * ptr)
Definition at line 368 of file bss_malloc.c.
References error_msg_warning().
int bss_frees (void)
Definition at line 437 of file bss_malloc.c.
void bss_init (void)
Definition at line 290 of file bss_malloc.c.
void* bss_malloc (size_t size)
Definition at line 312 of file bss_malloc.c.
References error_msg_fatal(), error_msg_warning(), malloc(), and tmp.
void bss_stats (void)
Definition at line 395 of file bss_malloc.c.
References giop(), my_id, num_nodes, printf(), and vals.
void* malloc (size_t size)
int perm_calls (void)
Definition at line 270 of file bss_malloc.c.
void perm_free (void * ptr)
Definition at line 185 of file bss_malloc.c.
References error_msg_warning().
int perm_frees (void)
Definition at line 254 of file bss_malloc.c.
void perm_init (void)
Definition at line 107 of file bss_malloc.c.
void* perm_malloc (size_t size)
Definition at line 129 of file bss_malloc.c.
References error_msg_fatal(), error_msg_warning(), malloc(), and tmp.
void perm_stats (void)
Definition at line 212 of file bss_malloc.c.
References giop(), my_id, num_nodes, printf(), and vals.