KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/build1.f File Reference
build1.f File Reference
Functions/Subroutines
subroutine newel (xmouse, ymouse, button, ierr)
subroutine set_auto_curve (e, iobjs)
subroutine chk_polar (e)
subroutine chk_obj (e, iobjs)
subroutine chk_neighbor (e)
subroutine clockw_chk (e, ierr)
subroutine getside (je, js, xp, yp)
subroutine delelq (idel)
subroutine delel (idel)
subroutine copyel (isrc, ides)
subroutine copyel_p (isrc, ides)
subroutine copyelbc_p (isrc, ides)
subroutine copyelbc (isrc, ides)
subroutine copyel0 (isrc, ides)
subroutine copyel2 (isrc, ides)
subroutine model (iel)
subroutine blatch2 (xm, ym, cm, em, ec, vc, nc)
subroutine model2d
subroutine chkjac_e (ierr, e)
subroutine drised (iel, iedge, iflip)
subroutine drawis (iel)
subroutine drawel (iel)
subroutine mkside_e (e)
subroutine mkside
function crss2d (xy1, xy2, xy0)
function round (x)
subroutine blatch (xmouse, ymouse, icmin, ielmin)
subroutine sortel
subroutine fillpf (iCOLOR)
subroutine drawel_color (iel, ICOLOR)
subroutine hmt_drawel_color (iel, ICOLOR)
subroutine hmt_drawel_color_nln (iel, ICOLOR)
subroutine flipel (ieg, fplane)
subroutine reflect_mesh
subroutine substitute_el (xyzbox, nelold)
function rad_circ (x0i, x1i, x2i, y0i, y1i, y2i)
subroutine side_to_obj (iobj, xo, yo, e, side)
subroutine convert_m_to_c_e (f, e, rad_mx)
subroutine convert_m_to_c_all
subroutine convert_m_to_c_allr (rmx)
Function/Subroutine Documentation
subroutine blatch (xmouse, ymouse, icmin, ielmin)
Definition at line 1509 of file build1.f.
References rmin().
subroutine blatch2 (xm, ym, integer cm, integer em, integer, dimension(nel) ec, integer, dimension(nel) vc, nc)
Definition at line 853 of file build1.f.
subroutine chk_neighbor (integer e)
Definition at line 305 of file build1.f.
References copy(), getside(), and mod1().
subroutine chk_obj (integer e, integer, dimension(4) iobjs)
Definition at line 217 of file build1.f.
References copy(), dist2(), i, latchob(), mod1(), and rad_circ().
subroutine chk_polar (integer e)
Definition at line 155 of file build1.f.
References drawel(), and mod1().
subroutine chkjac_e (ierr, integer e)
Definition at line 1046 of file build1.f.
subroutine clockw_chk (integer e, ierr)
Definition at line 341 of file build1.f.
References crss2d(), and i.
subroutine convert_m_to_c_all ()
Definition at line 2582 of file build1.f.
References convert_m_to_c_e(), prs(), and rer().
subroutine convert_m_to_c_allr (rmx)
Definition at line 2599 of file build1.f.
References convert_m_to_c_e().
subroutine convert_m_to_c_e (integer f, integer e, rad_mx)
Definition at line 2552 of file build1.f.
References rad_circ(), and rzero().
subroutine copyel (isrc, ides)
Definition at line 479 of file build1.f.
References copyel0(), copyel2(), and copyelbc().
subroutine copyel0 (isrc, ides)
Definition at line 534 of file build1.f.
References prs().
subroutine copyel2 (isrc, ides)
Definition at line 548 of file build1.f.
References chcopy(), copy(), i, if(), and prs().
subroutine copyel_p (isrc, ides)
Definition at line 488 of file build1.f.
References copyel0(), copyel2(), and copyelbc_p().
subroutine copyelbc (isrc, ides)
Definition at line 517 of file build1.f.
References i, and j.
subroutine copyelbc_p (isrc, ides)
Definition at line 497 of file build1.f.
References copy(), and i.
function crss2d (real, dimension(2) xy1, real, dimension(2) xy2, real, dimension(2) xy0)
Definition at line 1462 of file build1.f.
References crss2d().
subroutine delel (idel)
Definition at line 450 of file build1.f.
References blank(), copyel(), and prs().
subroutine delelq (idel)
Definition at line 421 of file build1.f.
References copyel().
subroutine drawel (iel)
Definition at line 1158 of file build1.f.
References beginb(), cmult(), color, drawc(), endp(), fillp(), getpts(), gwrite(), i, iabs, j, movec(), prsi(), sort(), tmp, xiso(), xisom(), yiso(), yisom(), and ziso().
subroutine drawel_color (iel, ICOLOR)
Definition at line 1576 of file build1.f.
References beginb(), cmult(), color, drawc(), endp(), fillp(), getpts(), gwrite(), i, iabs, j, movec(), sort(), tmp, xiso(), xisom(), yiso(), yisom(), and ziso().
subroutine drawis (iel)
Definition at line 1112 of file build1.f.
References beginb(), color, drised(), endp(), fillp(), i, iabs, xisom(), xphy(), xscr(), yisom(), yphy(), and yscr().
subroutine drised (iel, iedge, iflip)
Definition at line 1054 of file build1.f.
References drawc(), getpts(), i, iflip(), movec(), xisom(), xphy(), xscr(), yisom(), yphy(), and yscr().
subroutine fillpf (iCOLOR)
Definition at line 1562 of file build1.f.
References prs(), and rei().
subroutine flipel (ieg, character*1 fplane)
Definition at line 2192 of file build1.f.
References i, if(), and j.
subroutine getside (je, js, xp, yp)
Definition at line 378 of file build1.f.
References rmin().
subroutine hmt_drawel_color (iel, ICOLOR)
Definition at line 1780 of file build1.f.
References beginb(), cmult(), color, drawc(), endp(), fillp(), getpts(), hmt_fillp(), i, iabs, j, movec(), sort(), tmp, xiso(), xisom(), yiso(), yisom(), and ziso().
subroutine hmt_drawel_color_nln (iel, integer ICOLOR)
Definition at line 1985 of file build1.f.
References beginb(), cmult(), color, drawc(), endp(), fillp(), getpts(), hmt_color(), hmt_fillp(), i, iabs, j, movec(), sort(), tmp, xiso(), xisom(), yiso(), yisom(), and ziso().
subroutine mkside ()
Definition at line 1418 of file build1.f.
subroutine mkside_e (integer e)
Definition at line 1373 of file build1.f.
subroutine model (iel)
Definition at line 603 of file build1.f.
References blatch(), color, drawc(), drawel(), drawis(), i, model2d(), mouse(), movec(), prs(), prsi(), prsis(), rerr(), rmin(), vlsum(), and xscr().
subroutine model2d ()
Definition at line 939 of file build1.f.
References blatch(), blatch2(), chkjac_e(), copyel(), dist2(), gencen(), i, j, latchob(), mouse(), prs(), prsii(), redraw_mesh(), rerr(), and xscr().
subroutine newel (xmouse, ymouse, button, ierr)
Definition at line 3 of file build1.f.
References beginb(), blatch(), clockw_chk(), color, drawc(), drawel(), drawis(), endp(), fillp(), i, mkside_e(), mouse(), offrub(), prs(), prsi(), prsiii(), prsrr(), rerr(), round(), rubber(), set_auto_curve(), sgvis(), sortel(), and xphy().
function rad_circ (x0i, x1i, x2i, y0i, y1i, y2i)
Definition at line 2472 of file build1.f.
subroutine reflect_mesh ()
Definition at line 2377 of file build1.f.
References flipel(), and menu().
function round (x)
Definition at line 1474 of file build1.f.
References ax().
subroutine set_auto_curve (integer e, dimension(8) iobjs)
Definition at line 136 of file build1.f.
References blank(), chk_neighbor(), chk_obj(), chk_polar(), drawel(), and rzero().
subroutine side_to_obj (iobj, xo, yo, integer e, integer side)
Definition at line 2524 of file build1.f.
References dist2(), j, and latchob().
subroutine sortel ()
Definition at line 1540 of file build1.f.
References iswap(), and sort().
subroutine substitute_el (real, dimension(6) xyzbox, nelold)
Definition at line 2410 of file build1.f.
References copyel(), and prs().