KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/build2.f File Reference
build2.f File Reference
Functions/Subroutines
subroutine mid_3d (xm, x0, x1)
subroutine midside_convert_all
subroutine midside_clean (xm, x0, x1, linear)
subroutine midside_refine (xmp, x0p, x1p, xmi, x0, x1, linear)
subroutine cirmesh
subroutine outcirmesh (xcs, ycs, zcs, radius)
subroutine crtbox2d (xcs, ycs, zcs, radius)
subroutine sphmesh
subroutine sphere (xcs, ycs, zcs, hemi, mesh, radius)
subroutine crtbox (xcs, ycs, zcs, hemi, mesh, radius)
subroutine rotat2 (x, y, z, n, dir, angle)
subroutine rounder (x, n)
subroutine trans2 (x, y, z, xyzoff, n)
subroutine genmesh
subroutine genele (xyz)
subroutine rotate (xyz, n, dir, angle)
subroutine transl (xyz, xyzoff, n)
subroutine get_lattice_0 (d, r, x)
subroutine get_vert_lattice (x, d, x0)
subroutine permute_dia (x, p)
subroutine get_vert_dia (x, d, x0)
subroutine get_vert_fcc_lat (p, d, c0)
subroutine get_vert_tet (x, d, x0)
subroutine sdl_element_dia (v, xdia, rad)
subroutine sdl_element_tet (v, xtet, rad)
subroutine build_tet_saddle (v, xi, d, r, if_sph_ctr)
subroutine tet_saddle_element (v, x1, x2, x3, x4, r)
subroutine dia_sdle (v, x1, x2, x3, x4, x5, x6, r)
subroutine build_dia_saddle (v, xi, d, r, if_sph_ctr)
subroutine saddle_tet (d, rad, x0, if_sph_ctr)
subroutine saddle_dia (d, rad, x0, if_sph_ctr)
subroutine saddle_lat (d, rad, x0)
subroutine get_lattice_per_bc
subroutine shift_xyz (p, ai, n)
subroutine outmat (a, m, n, name5, k)
subroutine sdl_element_dodec (v, xrhm, rad)
subroutine rhombic_dodec (d, x0, if_sph_ctr)
subroutine rhomboid (ve, v1, v2, v4)
function tet_chk (q)
function triple_prod (v1, v2, v3)
subroutine vswap2 (x, y, n)
subroutine edge_tet_sdl (v, nt, p, i0, i1, k0, k1, d, rad)
subroutine crnr_tet_sdl (v, nt, p, i0, k0, k1, k2, d, rad)
subroutine saddle_fcc (d, radi, x0)
subroutine add3s2 (x, y, z, c, n)
subroutine facind (kx1, kx2, ky1, ky2, kz1, kz2, nx1, ny1, nz1, iface)
subroutine sfacind (kx1, kx2, ky1, ky2, kz1, kz2, nx1, ny1, nz1, iface)
subroutine non_reg_tet_mod (v, x1, x2, x3, r)
subroutine sph_intersect (xi, x0, x1, xc, r)
subroutine nw_sphmesh
subroutine sph_wall_elmt
subroutine sph_w_gt_fc (xt, ntp, nlev, pface)
subroutine sph_wall_elmt1 (r0, h0, xvi, zvi, xt, x0, rads, ntp, tsph)
subroutine sph_wall_elmt2 (r0, h0, xvi, zvi, xt, x0, rads, ntp, tsph)
subroutine sph_wall_elmt3 (r0, h0, xvi, zvi, xt, x0, rads, ntp, tsph)
subroutine sph_combine_d (xi, r0, x0, x1, xs1)
subroutine user_s (xu, xf, xo, eg, face)
subroutine permute_xyz (x, y, z, n)
subroutine el_convert (e, xr, yr, zr)
subroutine el_convert_2to3 (e, xr, yr, zr)
subroutine sc_central_shell (r1, r2, e)
subroutine sc_transition_shell (r1, r2, e)
subroutine sc_std_shell (r1, r2, e)
subroutine sc_cartesian_shell (r1, r2, e, ifsix)
subroutine sc_cartesian_shell_a (r1, r2, e, ifsix)
subroutine sc_cartesian_shell_b (r1, r2, e, ifsix)
subroutine sc_cartesian_shell_c (r1, r2, e, ifsix)
subroutine sc_pipe_section (radii, nr, e, ifsix)
subroutine convert_top_to_mid (e)
subroutine rep_rotate_mesh2
subroutine do_rep_rotate_meshg (e0, e1, angle_deg, nrep, normal)
subroutine do_rep_rotate_mesh (e0, e1, angle_deg, nrep, axisr)
subroutine octquad_split_submesh (e0, e1, ifoct)
subroutine mesh4to3 (p9, idir)
subroutine proj2plane (x, x0, p1, p2, p3, tol)
subroutine proj2line (x, p0, p1)
subroutine build_corner_mesh (p9, nrefine)
subroutine build_center_mesh (p9, nrefine)
subroutine skin_fcc_spheres (rt, r0, nrefine)
subroutine fcc_x8
subroutine fcc_base (p9, rt, r0, r1, nrefine)
subroutine fcc2
subroutine fcc_set_bcs (r0)
subroutine sc_set_bc_etc
subroutine copy_el_to_safe_haven (e_safe)
subroutine free_safe_haven (e_safe)
subroutine sc_make_sphere_cap (radii, nr)
subroutine sc_6x6_modification (radii, nr, ne_cap)
Function/Subroutine Documentation
subroutine add3s2 (real, dimension(1) x, real, dimension(1) y, real, dimension(1) z, c, n)
Definition at line 2013 of file build2.f.
References i, and n.
subroutine build_center_mesh (real, dimension(3,9) p9, nrefine)
Definition at line 3919 of file build2.f.
References cfill(), copyel(), do_rep_rotate_meshg(), gen_rotate_mat_3d(), i, mxm(), octquad_split_submesh(), rone(), sub2(), and translate_sub_mesh().
subroutine build_corner_mesh (real, dimension(3,9) p9, nrefine)
Definition at line 3860 of file build2.f.
References copyel(), do_rep_rotate_mesh(), do_rep_rotate_meshg(), i, octquad_split_submesh(), rone(), rzero(), and translate_sub_mesh().
subroutine build_dia_saddle (real, dimension(3*8,24) v, real, dimension(3,6) xi, d, r, logical if_sph_ctr)
Definition at line 1510 of file build2.f.
References copy(), dia_sdle(), prs(), and shift_xyz().
subroutine build_tet_saddle (real, dimension(3*8,12) v, real, dimension(3,4) xi, d, r, logical if_sph_ctr)
Definition at line 1369 of file build2.f.
References copy(), prs(), shift_xyz(), tet_chk(), and tet_saddle_element().
subroutine cirmesh ()
Definition at line 136 of file build2.f.
References capit(), crtbox2d(), outcirmesh(), prs(), rer(), rerr(), res(), rzero(), and trans2().
subroutine convert_top_to_mid (integer e)
Definition at line 3605 of file build2.f.
References genxyz_e().
subroutine copy_el_to_safe_haven (integer e_safe)
Definition at line 4218 of file build2.f.
References copy_sub_mesh().
subroutine crnr_tet_sdl (real, dimension(3,8,288) v, nt, real, dimension(3,8,2) p, i0, k0, k1, k2, d, rad)
Definition at line 1927 of file build2.f.
References build_tet_saddle(), copy(), i0, sdl_element_tet(), tet_chk(), and vswap2().
subroutine crtbox (dimension(4,24) xcs, dimension(4,24) ycs, dimension(4,24) zcs, character*1 hemi, mesh, radius)
Definition at line 693 of file build2.f.
References copy(), rotat2(), and rounder().
subroutine crtbox2d (dimension(2,4) xcs, dimension(2,4) ycs, dimension(2,4) zcs, radius)
Definition at line 313 of file build2.f.
subroutine dia_sdle (real, dimension(3,8) v, real, dimension(3) x1, real, dimension(3) x2, real, dimension(3) x3, real, dimension(3) x4, real, dimension(3) x5, real, dimension(3) x6, r)
Definition at line 1479 of file build2.f.
References add2(), cmult(), i, sub3(), and vlsc2().
subroutine do_rep_rotate_mesh (integer e0, integer e1, angle_deg, nrep, character*1 axisr)
Definition at line 3684 of file build2.f.
References copy_sub_mesh(), i, and rotate_submesh_3d().
subroutine do_rep_rotate_meshg (integer e0, integer e1, angle_deg, nrep, real, dimension(3) normal)
Definition at line 3655 of file build2.f.
References copy_sub_mesh(), i, and rotate_el_vec().
subroutine edge_tet_sdl (real, dimension(3,8,288) v, nt, real, dimension(3,8,2) p, i0, i1, k0, k1, d, rad)
Definition at line 1899 of file build2.f.
References build_tet_saddle(), copy(), i0, sdl_element_tet(), tet_chk(), and vswap2().
subroutine el_convert (integer e, real, dimension(8) xr, real, dimension(8) yr, real, dimension(8) zr)
Definition at line 3000 of file build2.f.
References i.
subroutine el_convert_2to3 (integer e, real, dimension(8) xr, real, dimension(8) yr, real, dimension(8) zr)
Definition at line 3017 of file build2.f.
References i, and mod1().
subroutine facind (kx1, kx2, ky1, ky2, kz1, kz2, nx1, ny1, nz1, iface)
Definition at line 2021 of file build2.f.
subroutine fcc2 ()
Definition at line 4139 of file build2.f.
References build_center_mesh(), build_corner_mesh(), fcc_base(), fcc_set_bcs(), fcc_x8(), and skin_fcc_spheres().
subroutine fcc_base (real, dimension(3,9) p9, rt, r0, r1, nrefine)
Definition at line 4059 of file build2.f.
References do_rep_rotate_mesh(), do_rep_rotate_meshg(), mesh4to3(), octquad_split_submesh(), proj2line(), proj2plane(), rone(), rotate_submesh_3d(), sc_std_shell(), and translate_sub_mesh().
subroutine fcc_set_bcs (r0)
Definition at line 4174 of file build2.f.
subroutine fcc_x8 ()
Definition at line 4049 of file build2.f.
References do_rep_rotate_mesh().
subroutine free_safe_haven (integer e_safe)
Definition at line 4234 of file build2.f.
subroutine genele (dimension(3,8) xyz)
Definition at line 952 of file build2.f.
References i.
subroutine genmesh ()
Definition at line 896 of file build2.f.
References copy(), genele(), i, rotate(), and transl().
subroutine get_lattice_0 (d, r, real, dimension(3) x)
Definition at line 1024 of file build2.f.
References prs(), rerr(), and rerrr().
subroutine get_lattice_per_bc ()
Definition at line 1665 of file build2.f.
References get_vert_tet(), norm3d(), prs(), res(), rzero(), and sub3().
subroutine get_vert_dia (real, dimension(3,6) x, d, real, dimension(3) x0)
Definition at line 1122 of file build2.f.
References copy(), get_vert_lattice(), and i.
subroutine get_vert_fcc_lat (real, dimension(3,8,2) p, d, real, dimension(3) c0)
Definition at line 1172 of file build2.f.
References copy(), i, and j.
subroutine get_vert_lattice (real, dimension(3,8) x, d, real, dimension(3) x0)
Definition at line 1037 of file build2.f.
References copy(), and get_vert_tet().
subroutine get_vert_tet (real, dimension(3,4) x, d, real, dimension(3) x0)
Definition at line 1212 of file build2.f.
References i.
subroutine mesh4to3 (real, dimension(3,9) p9, idir)
Definition at line 3783 of file build2.f.
References i, and j.
subroutine mid_3d (real, dimension(3) xm, real, dimension(3) x0, real, dimension(3) x1)
Definition at line 31 of file build2.f.
References add3(), and cmult().
subroutine midside_clean (real, dimension(3) xm, real, dimension(3) x0, real, dimension(3) x1, linear)
Definition at line 50 of file build2.f.
References add3s2(), dot(), mid_3d(), normalize(), sub3(), test(), and vcross_normal().
subroutine midside_convert_all ()
Definition at line 41 of file build2.f.
References fix_m_curve().
subroutine midside_refine (real, dimension(3) xmp, real, dimension(3) x0p, real, dimension(3) x1p, real, dimension(3) xmi, real, dimension(3) x0, real, dimension(3) x1, linear)
Definition at line 89 of file build2.f.
References add3s2(), alpha, copy(), mid_3d(), midside_clean(), normalize(), sub3(), and vcross_normal().
subroutine non_reg_tet_mod (real, dimension(3) v, real, dimension(3) x1, real, dimension(3) x2, real, dimension(3) x3, r)
Definition at line 2067 of file build2.f.
References add2s2(), add3s2(), copy(), i, sub3(), and vlsc2().
subroutine nw_sphmesh ()
Definition at line 2142 of file build2.f.
References redraw_mesh(), and sph_wall_elmt().
subroutine octquad_split_submesh (integer e0, integer e1, logical ifoct)
Definition at line 3707 of file build2.f.
References curcnt(), gencen(), octsplite(), prs(), qsplite(), rint(), sort(), and swapel().
subroutine outcirmesh (dimension(3,1) xcs, dimension(3,1) ycs, dimension(3,1) zcs, radius)
Definition at line 294 of file build2.f.
subroutine outmat (real, dimension(m,n) a, m, n, character*5 name5, k)
Definition at line 1713 of file build2.f.
References i, j, and n.
subroutine permute_dia (real, dimension(3,6) x, real, dimension(3,6) p)
Definition at line 1075 of file build2.f.
References copy(), outmat(), prs(), and res().
subroutine permute_xyz (real, dimension(n) x, real, dimension(n) y, real, dimension(n) z, n)
Definition at line 2982 of file build2.f.
References i, and n.
subroutine proj2line (real, dimension(3) x, real, dimension(3) p0, real, dimension(3) p1)
Definition at line 3843 of file build2.f.
References alpha, dot(), i, norm3d(), and sub3().
subroutine proj2plane (real, dimension(3) x, real, dimension(3) x0, real, dimension(3) p1, real, dimension(3) p2, real, dimension(3) p3, tol)
Definition at line 3818 of file build2.f.
References alpha, chsign(), dot(), sub3(), and vcross_normal().
subroutine rep_rotate_mesh2 ()
Definition at line 3634 of file build2.f.
References capit(), do_rep_rotate_mesh(), prs(), rei(), rer(), and res().
subroutine rhombic_dodec (d, real, dimension(3) x0, logical if_sph_ctr)
Definition at line 1780 of file build2.f.
References cmult(), get_vert_tet(), i, norm3d(), rhomboid(), rzero(), scale(), and sdl_element_dodec().
subroutine rhomboid (real, dimension(3,0:7) ve, real, dimension(3) v1, real, dimension(3) v2, real, dimension(3) v4)
Definition at line 1823 of file build2.f.
References add3(), rzero(), and triple_prod().
subroutine rotat2 (dimension(1) x, dimension(1) y, dimension(1) z, n, character*1 dir, angle)
Definition at line 823 of file build2.f.
References i, n, and rzero().
subroutine rotate (dimension(3,1) xyz, n, character*1 dir, angle)
Definition at line 967 of file build2.f.
References i, n, and rzero().
subroutine rounder (dimension(1) x, n)
Definition at line 868 of file build2.f.
References i, and n.
subroutine saddle_dia (d, rad, real, dimension(3) x0, logical if_sph_ctr)
Definition at line 1591 of file build2.f.
References build_dia_saddle(), get_vert_dia(), and sdl_element_dia().
subroutine saddle_fcc (d, radi, real, dimension(3) x0)
Definition at line 1954 of file build2.f.
References build_dia_saddle(), crnr_tet_sdl(), edge_tet_sdl(), get_vert_fcc_lat(), permute_dia(), and sdl_element_dia().
subroutine saddle_lat (d, rad, real, dimension(3) x0)
Definition at line 1606 of file build2.f.
References build_dia_saddle(), build_tet_saddle(), copy(), get_vert_lattice(), i, norm3d(), prs(), res(), rzero(), sdl_element_dia(), sdl_element_tet(), shift_xyz(), sub2(), and sub3().
subroutine saddle_tet (d, rad, real, dimension(3) x0, logical if_sph_ctr)
Definition at line 1576 of file build2.f.
References build_tet_saddle(), get_vert_tet(), and sdl_element_tet().
subroutine sc_6x6_modification (real, dimension(nr) radii, nr, ne_cap)
Definition at line 4316 of file build2.f.
References copy_el_to_safe_haven(), copy_sub_mesh(), mark(), and split().
subroutine sc_cartesian_shell (r1, r2, integer e, logical ifsix)
Definition at line 3210 of file build2.f.
References sc_cartesian_shell_a(), sc_cartesian_shell_b(), and sc_cartesian_shell_c().
subroutine sc_cartesian_shell_a (r1, r2, integer e, logical ifsix)
Definition at line 3228 of file build2.f.
References el_convert(), permute_xyz(), and rzero().
subroutine sc_cartesian_shell_b (r1, r2, integer e, logical ifsix)
Definition at line 3292 of file build2.f.
References el_convert(), genxyz_e(), permute_xyz(), and rzero().
subroutine sc_cartesian_shell_c (r1, r2, integer e, logical ifsix)
Definition at line 3381 of file build2.f.
References el_convert(), permute_xyz(), and rzero().
subroutine sc_central_shell (r1, r2, integer e)
Definition at line 3035 of file build2.f.
References el_convert(), rr, and rzero().
subroutine sc_make_sphere_cap (real, dimension(nr) radii, nr)
Definition at line 4246 of file build2.f.
References i, prs(), sc_6x6_modification(), sc_cartesian_shell(), sc_central_shell(), sc_pipe_section(), sc_set_bc_etc(), sc_std_shell(), and sc_transition_shell().
subroutine sc_pipe_section (real, dimension(nr) radii, nr, integer e, logical ifsix)
Definition at line 3442 of file build2.f.
References cfill(), convert_top_to_mid(), el_convert_2to3(), i, rr, and rzero().
subroutine sc_set_bc_etc ()
Definition at line 4199 of file build2.f.
subroutine sc_std_shell (r1, r2, integer e)
Definition at line 3138 of file build2.f.
References el_convert(), permute_xyz(), and rzero().
subroutine sc_transition_shell (r1, r2, integer e)
Definition at line 3072 of file build2.f.
References el_convert(), permute_xyz(), rr, and rzero().
subroutine sdl_element_dia (real, dimension(3,8,24) v, real, dimension(3,6) xdia, rad)
Definition at line 1254 of file build2.f.
References i, j, mod1(), and rzero().
subroutine sdl_element_dodec (real, dimension(3,8,4) v, real, dimension(3,4) xrhm, rad)
Definition at line 1730 of file build2.f.
References i, j, mod1(), and rzero().
subroutine sdl_element_tet (real, dimension(3,8,12) v, real, dimension(3,4) xtet, rad)
Definition at line 1312 of file build2.f.
References i, j, mod1(), and rzero().
subroutine sfacind (kx1, kx2, ky1, ky2, kz1, kz2, nx1, ny1, nz1, iface)
Definition at line 2044 of file build2.f.
subroutine shift_xyz (real, dimension(3,n) p, real, dimension(3) ai, n)
Definition at line 1695 of file build2.f.
References i, and n.
subroutine skin_fcc_spheres (rt, r0, nrefine)
Definition at line 3997 of file build2.f.
References do_rep_rotate_mesh(), octquad_split_submesh(), rotate_submesh_3d(), sc_std_shell(), and translate_sub_mesh().
subroutine sph_combine_d (real, dimension(3) xi, r0, real, dimension(3) x0, real, dimension(3) x1, real, dimension(0:3) xs1)
Definition at line 2881 of file build2.f.
References add2s1(), alpha, copy(), dot(), i, normalize(), rzero(), sph_intersect(), sub3(), and vlsc2().
subroutine sph_intersect (real, dimension(3) xi, real, dimension(3) x0, real, dimension(3) x1, real, dimension(3) xc, real r)
Definition at line 2099 of file build2.f.
References add2(), add2s2(), cmult(), copy(), dot(), scale(), and sub3().
subroutine sph_w_gt_fc (real, dimension(3,ntp,ntp,6,nlev) xt, ntp, nlev, integer pface)
Definition at line 2221 of file build2.f.
References i, and j.
subroutine sph_wall_elmt ()
Definition at line 2150 of file build2.f.
References blank(), prs(), res(), sph_wall_elmt1(), sph_wall_elmt2(), sph_wall_elmt3(), and translate_sub_mesh().
subroutine sph_wall_elmt1 (real r0, real h0, real, dimension(3) xvi, real, dimension(5) zvi, real, dimension(3,25,6,4) xt, real, dimension(3,3) x0, real, dimension(0:3) rads, ntp, real, dimension(3) tsph)
Definition at line 2311 of file build2.f.
References copy_sub_mesh(), i, j, ja, mod1(), rotate_submesh_2d(), rzero(), sph_intersect(), and user_s().
subroutine sph_wall_elmt2 (real r0, real h0, real, dimension(3) xvi, real, dimension(5) zvi, real, dimension(3,ntp*ntp,6,4) xt, real, dimension(3,3) x0, real, dimension(0:3) rads, ntp, real, dimension(3) tsph)
Definition at line 2527 of file build2.f.
References i, ia, j, ja, mod1(), rzero(), sph_intersect(), sph_w_gt_fc(), and user_s().
subroutine sph_wall_elmt3 (real r0, real h0, real, dimension(3) xvi, real, dimension(5) zvi, real, dimension(3,ntp*ntp,6,4) xt, real, dimension(3,3) x0, real, dimension(0:3) rads, ntp, real, dimension(3) tsph)
Definition at line 2708 of file build2.f.
References i, ia, j, ja, mod1(), rzero(), sph_intersect(), sph_w_gt_fc(), and user_s().
subroutine sphere (dimension(4,24) xcs, dimension(4,24) ycs, dimension(4,24) zcs, character*1 hemi, mesh, radius)
Definition at line 540 of file build2.f.
References copy(), prs(), rotat2(), and rounder().
subroutine sphmesh ()
Definition at line 331 of file build2.f.
References capit(), crtbox(), fcc2(), get_lattice_0(), i, j, mod1(), prs(), prsr(), rer(), rerrr(), res(), rhombic_dodec(), rzero(), saddle_dia(), saddle_lat(), saddle_tet(), sc_make_sphere_cap(), sphere(), and trans2().
function tet_chk (real, dimension(3,0:3) q)
Definition at line 1843 of file build2.f.
References i, sub3(), and triple_prod().
subroutine tet_saddle_element (real, dimension(3,8) v, real, dimension(3) x1, real, dimension(3) x2, real, dimension(3) x3, real, dimension(3) x4, r)
Definition at line 1428 of file build2.f.
References add2(), cmult(), copy(), i, non_reg_tet_mod(), sub3(), and vlsc2().
subroutine trans2 (dimension(1) x, dimension(1) y, dimension(1) z, dimension(3) xyzoff, n)
Definition at line 884 of file build2.f.
References i, and n.
subroutine transl (dimension(3,1) xyz, dimension(3) xyzoff, n)
Definition at line 1012 of file build2.f.
References i, and n.
function triple_prod (real, dimension(3) v1, real, dimension(3) v2, real, dimension(3) v3)
Definition at line 1863 of file build2.f.
References cross(), and dot().
subroutine user_s (real, dimension(3) xu, real, dimension(3) xf, real, dimension(3) xo, integer eg, integer face)
Definition at line 2943 of file build2.f.
References sph_combine_d().
subroutine vswap2 (real, dimension(1) x, real, dimension(1) y, n)
Definition at line 1887 of file build2.f.
References i, and n.