KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/build.f File Reference
build.f File Reference
Functions/Subroutines
subroutine build
subroutine build0
subroutine build1
subroutine build2
subroutine readat
subroutine setscl
subroutine imp_mesh (ifquery_displace)
subroutine readscan (key, len_key, io)
function imp_geom (x, y, z, ld, numapt, letapt, igroup, ndim, nel, io)
function imp_curv (nc, cc, c, ndim, nel, nelo, io)
function imp_bc (cbc, bc, ibc, ndim, neln, nel, io)
subroutine new_out (fname, lname, gv, ncrnr, xyz, ind)
integer function i_finds (list, ig, n)
integer function i_findu (list, ig, n)
function i_findu_zero (list, ig, n)
subroutine imp_mesh_vtx
subroutine imp_mesh_vtk
subroutine check_spj
logical function ifclose (ie, is, je, js)
subroutine chk_seg (g1, e1, g2, e2, ie, is, je, js)
subroutine chk_segs (ifok, icond, ie, is, je, js)
subroutine chk_right_hand (nl)
subroutine special_delete
subroutine list_delete
subroutine special_delete_cyls
subroutine set_std_bcs (nelo)
subroutine parse_e_hdr (iel, numapt, letapt, igroup, string)
subroutine set_main_menu
subroutine cell_cell_connectivity
subroutine find_ee (ee, nf, nel, clist_i, clist_j, cell, nv, ndim)
subroutine unique_vertex2 (cell, dx, ndim, nel, q, ind, ninseg, ifseg, wk)
subroutine makecell (cell, nv, nel, dx, ndim, wk, i_n, j_n, j_o)
subroutine set_d2a (dx, x, y, z, nv, nel, ndim)
subroutine set_d2 (dx, nv, nel, ndim)
subroutine iranku (a, p, n)
subroutine tuple_swapt_ip (x, m, n, p, t1, t2)
subroutine iswapt_ip (x, p, n)
subroutine self_chk (cell, nv, nel, flag)
subroutine outmatti (u, m, n, name6, nid, ic)
subroutine outmati (u, m, n, name6, nid, ic)
subroutine outmatx (u, m, n, name6, nid)
subroutine cell2v (i0, i1, ic, nic, jc, njc, cell, nv, ncell, type, wk)
subroutine cell2v1 (ic, i0, i1, jc, njc, cell, nv, ncell, type, wk)
subroutine isortg (a, ind, n)
subroutine get_ee_face (jf, je, f, e, ee, nf)
subroutine chker
subroutine chker2 (cell, nv, nel)
subroutine get_flow_heat (ifflow, ifheat, nlogic, io)
subroutine delete
subroutine set_igroup (nelv_i, nelt_i)
Function/Subroutine Documentation
subroutine build ()
Definition at line 18 of file build.f.
References build0(), build1(), build2(), imp_mesh(), and set_igroup().
subroutine build0 ()
Definition at line 52 of file build.f.
References chk_right_hand(), drawel(), drawis(), drcovr(), drelev(), drgrid(), gnable(), i, legend(), nx, nz, prs(), readat(), setscl(), sortel(), xphy(), and yphy().
subroutine build1 ()
Definition at line 166 of file build.f.
References chk_right_hand(), copyel(), curves(), delete(), drawel(), drawis(), drelev(), drgrid(), gencen(), glomod(), i, if(), imp_mesh(), imp_mesh_vtk(), imp_mesh_vtx(), menu(), mesh_edit(), mkside(), model(), newel(), prs(), prsi(), prsis(), redraw_mesh(), redraw_mesh_small(), reflect_mesh(), rer(), set_main_menu(), setgrd(), setobj(), setzoom(), and sortel().
subroutine build2 ()
Definition at line 463 of file build.f.
References bound(), cell_cell_connectivity(), check_spj(), gingrd(), mesgen(), mkside(), sgvis(), and vprops().
subroutine cell2v (i0, i1, integer, dimension(1) ic, nic, integer, dimension(1) jc, njc, integer, dimension(nv,ncell) cell, nv, ncell, integer type, integer, dimension(1) wk)
Definition at line 3273 of file build.f.
References cell2v1(), i0, iglmax(), iglmin(), and prexit().
subroutine cell2v1 (integer, dimension(i0:i1) ic, i0, i1, integer, dimension(1) jc, njc, integer, dimension(nv,ncell) cell, nv, ncell, integer type, integer, dimension(i0:i1) wk)
Definition at line 3298 of file build.f.
References i, i0, izero(), and j.
subroutine cell_cell_connectivity ()
Definition at line 2686 of file build.f.
References cell2v(), chker(), chker2(), find_ee(), get_ee_face(), i, i0, makecell(), prexit(), prs(), and set_d2a().
subroutine check_spj ()
Definition at line 2034 of file build.f.
References chk_seg(), and chk_segs().
subroutine chk_right_hand (nl)
Definition at line 2328 of file build.f.
References crss2d(), i, and prsi().
subroutine chk_seg (g1, e1, g2, e2, ie, is, je, js)
Definition at line 2147 of file build.f.
References scale().
subroutine chk_segs (logical ifok, icond, ie, is, je, js)
Definition at line 2200 of file build.f.
References cross(), dotprod(), i, j, mod1(), norm3d(), sub3(), and vcross_normal().
subroutine chker ()
Definition at line 3428 of file build.f.
References i, prs(), and res().
subroutine chker2 (integer, dimension(nv,nel) cell, nv, nel)
Definition at line 3458 of file build.f.
References prs(), and res().
subroutine delete ()
Definition at line 3500 of file build.f.
References delel(), drawel(), drawis(), drgrid(), drmenu(), drwbox(), i, list_delete(), mouse(), prs(), prsi(), refresh(), res(), rmin(), special_delete_cyls(), and xphy().
subroutine find_ee (integer, dimension(nf,nel) ee, nf, nel, integer, dimension(1) clist_i, integer, dimension(1) clist_j, integer, dimension(nv,nel) cell, nv, ndim)
Definition at line 2758 of file build.f.
References i, i0, iglmax(), iglmin(), isortg(), n, and prexit().
subroutine get_ee_face (jf, je, integer f, integer e, integer, dimension(nf,1) ee, nf)
Definition at line 3410 of file build.f.
References i.
subroutine get_flow_heat (logical ifflow, logical ifheat, nlogic, io)
Definition at line 3484 of file build.f.
References capit(), i, and indx1().
integer function i_finds (integer, dimension(1) list, integer ig, integer n)
Definition at line 1640 of file build.f.
References exitt(), i_findu(), and j.
integer function i_findu (integer, dimension(1) list, integer ig, integer n)
Definition at line 1674 of file build.f.
function i_findu_zero (integer, dimension(1) list, integer ig, integer n)
Definition at line 1690 of file build.f.
logical function ifclose (ie, is, je, js)
Definition at line 2120 of file build.f.
function imp_bc (character*3, dimension (6,1) cbc, real, dimension (5,6,1) bc, integer, dimension (6,1) ibc, ndim, neln, nel, io)
Definition at line 1456 of file build.f.
References blank(), capit(), indx1(), ltrunc(), and prs().
function imp_curv (nc, character*1, dimension(12,1) cc, real, dimension(6,12,1) c, ndim, nel, nelo, io)
Definition at line 1401 of file build.f.
References blank(), i, and rzero().
function imp_geom (real, dimension(8,ld) x, real, dimension(8,ld) y, real, dimension(8,ld) z, ld, integer, dimension(1) numapt, character*1, dimension(1) letapt, integer, dimension(1) igroup, ndim, nel, io)
Definition at line 1345 of file build.f.
subroutine imp_mesh (logical ifquery_displace)
Definition at line 1113 of file build.f.
References blank(), chcopy(), gencen(), get_flow_heat(), i, imp_bc(), imp_curv(), imp_geom(), indx1(), ltrunc(), prii(), prs(), prsii(), readscan(), rerr(), rerrr(), res(), substitute_el(), and translate_sub_mesh().
subroutine imp_mesh_vtk ()
Definition at line 1854 of file build.f.
References blank(), i, i_findu_zero(), indx1(), j, prs(), prsi(), prsii(), res(), and set_std_bcs().
subroutine imp_mesh_vtx ()
Definition at line 1706 of file build.f.
References blank(), glmax(), glmin(), i, indx1(), j, prs(), prsi(), prsii(), prsis(), prsrr(), and res().
subroutine iranku (integer, dimension(1) a, integer, dimension(1) p, n)
Definition at line 3066 of file build.f.
References isortg(), iswapt_ip(), and n.
subroutine isortg (integer, dimension(1) a, integer, dimension(1) ind, n)
Definition at line 3357 of file build.f.
References i, j, and n.
subroutine iswapt_ip (integer, dimension(1) x, integer, dimension(1) p, n)
Definition at line 3134 of file build.f.
References exitt(), j, and n.
subroutine list_delete ()
Definition at line 2424 of file build.f.
References blank(), copyel(), izero(), prs(), prsis(), and res().
subroutine makecell (integer, dimension(1) cell, nv, nel, real, dimension (1) dx, ndim, real, dimension (1) wk, integer, dimension(1) i_n, integer, dimension(1) j_n, integer, dimension(1) j_o)
Definition at line 2966 of file build.f.
References iranku(), n, self_chk(), and unique_vertex2().
subroutine new_out (fname, lname, integer, dimension(ncrnr,1) gv, ncrnr, real, dimension(1) xyz, integer, dimension(1) ind)
Definition at line 1529 of file build.f.
References blank(), chcopy(), i, irank(), j, prs(), and swap().
subroutine outmati (integer, dimension(m,n) u, m, n, character*6 name6, nid, ic)
Definition at line 3224 of file build.f.
References i, j, and n.
subroutine outmatti (integer, dimension(m,n) u, m, n, character*6 name6, nid, ic)
Definition at line 3205 of file build.f.
References i, j, and n.
subroutine outmatx (real, dimension(m,n) u, m, n, character*6 name6, nid)
Definition at line 3253 of file build.f.
References i, j, and n.
subroutine parse_e_hdr (iel, numapt, character*1 letapt, igroup, character*80 string)
Definition at line 2537 of file build.f.
References blank(), chcopy(), i0, indx1(), ltrunc(), and nindx1().
subroutine readat ()
Definition at line 568 of file build.f.
References blank(), capit(), ddummy(), devex(), exitt(), i, if(), indx1(), parse_e_hdr(), prs(), prsii(), rer(), and res().
subroutine readscan (character*80 key, len_key, io)
Definition at line 1321 of file build.f.
References blank(), i, indx1(), and ltrunc().
subroutine self_chk (integer, dimension(nv,nel) cell, nv, nel, integer flag)
Definition at line 3173 of file build.f.
References exitt(), i, j, outmati(), outmatti(), and prexit().
subroutine set_d2 (real, dimension(0:ndim,nv,nel) dx, nv, nel, ndim)
Definition at line 3027 of file build.f.
References i, j, and n.
subroutine set_d2a (real, dimension(0:ndim,nv,nel) dx, real, dimension(8,nel) x, real, dimension(8,nel) y, real, dimension(8,nel) z, nv, nel, ndim)
Definition at line 2999 of file build.f.
References i, and set_d2().
subroutine set_igroup (nelv_i, nelt_i)
Definition at line 3639 of file build.f.
References i.
subroutine set_main_menu ()
Definition at line 2600 of file build.f.
subroutine set_std_bcs (nelo)
Definition at line 2519 of file build.f.
subroutine setscl ()
Definition at line 943 of file build.f.
References clear(), color, draw(), drawc(), drgrid(), gingrd(), i, mouse(), move(), movec(), prs(), refresh(), rer(), rerr(), xphy(), and yphy().
subroutine special_delete ()
Definition at line 2371 of file build.f.
References copyel(), i, izero(), and prsis().
subroutine special_delete_cyls ()
Definition at line 2466 of file build.f.
References copyel(), i, izero(), and prsis().
subroutine tuple_swapt_ip (real, dimension(m,n) x, m, n, integer, dimension(1) p, real, dimension(m) t1, real, dimension(m) t2)
Definition at line 3095 of file build.f.
References copy(), exitt(), j, and n.
subroutine unique_vertex2 (integer, dimension(1) cell, real, dimension(0:ndim,1) dx, ndim, nel, q, integer, dimension(1) ind, integer, dimension(1) ninseg, logical, dimension(1) ifseg, real, dimension(0:ndim,1) wk)
Definition at line 2872 of file build.f.
References i, icopy(), iswap_ip(), j, n, self_chk(), tuple_sort(), and tuple_swapt_ip().