KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/byte_mpi.f File Reference
byte_mpi.f File Reference
Functions/Subroutines
subroutine byte_sync_mpi (mpi_fh)
subroutine byte_open_mpi (fnamei, mpi_fh, ifro, ierr)
subroutine byte_read_mpi (buf, icount, iorank, mpi_fh, ierr)
subroutine byte_write_mpi (buf, icount, iorank, mpi_fh, ierr)
subroutine byte_close_mpi (mpi_fh, ierr)
subroutine byte_set_view (ioff_in, mpi_fh)
Function/Subroutine Documentation
byte_close_mpi()
subroutine byte_close_mpi (mpi_fh, ierr)
Definition at line 84 of file byte_mpi.f.
References exitti().
byte_open_mpi()
subroutine byte_open_mpi (character, dimension(*) fnamei, mpi_fh, logical ifro, ierr)
Definition at line 13 of file byte_mpi.f.
References chcopy(), exitti(), and ltrunc().
byte_read_mpi()
subroutine byte_read_mpi (real*4, dimension(1) buf, icount, iorank, mpi_fh, ierr)
Definition at line 48 of file byte_mpi.f.
References exitti().
byte_set_view()
subroutine byte_set_view (integer*8 ioff_in, mpi_fh)
Definition at line 97 of file byte_mpi.f.
References exitti().
byte_sync_mpi()
subroutine byte_sync_mpi (mpi_fh)
Definition at line 2 of file byte_mpi.f.
References exitti().
byte_write_mpi()
subroutine byte_write_mpi (real*4, dimension(1) buf, icount, iorank, mpi_fh, ierr)
Definition at line 65 of file byte_mpi.f.
References exitti().