KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/calcz.f File Reference
calcz.f File Reference
Functions/Subroutines
subroutine calcz (d, e, n, dmax, dmin, z, ierr)
function pythag (a, b)
subroutine ident (a, n)
Function/Subroutine Documentation
calcz()
subroutine calcz (real, dimension(n) d, real, dimension(n) e, n, dmax, dmin, real, dimension(n,n) z, ierr)
Definition at line 3 of file calcz.f.
References ident(), and pythag().
ident()
subroutine ident (real, dimension(n,n) a, n)
Definition at line 147 of file calcz.f.
References rzero().
pythag()
function pythag (a, b)
Definition at line 129 of file calcz.f.