KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/coef.f File Reference
coef.f File Reference
Functions/Subroutines
subroutine genwz
subroutine geom1 (xm3, ym3, zm3)
subroutine glmapm3 (xm3, ym3, zm3)
subroutine glmapm1
subroutine geodat1
subroutine geom2
subroutine xyzrst (xrm1, yrm1, zrm1, xsm1, ysm1, zsm1, XTM1, YTM1, ZTM1, IFAXIS)
subroutine chkjac (jac, n, iel, X, Y, Z, ND, IERR)
subroutine volume
subroutine setarea
subroutine area2
subroutine setwgtr (wgtr1, wgtr2, wgtr3, wgtr4)
subroutine area3
subroutine lagmass
subroutine setinvm
subroutine maprs (y, x, xa, nrest, iel)
subroutine map31 (y, x, iel)
subroutine map13 (y, x, iel)
subroutine map12 (y, x, iel)
subroutine map21t (y, x, iel)
subroutine map21e (y, x, iel)
subroutine out_xyz_el (x, y, z, e)
subroutine out_fld_el (x, e, c2)
subroutine outxm3j (xm3, ym3, jm3)
subroutine invmt (A, B, AA, N)
subroutine lubksb (A, N, NP, INDX, B)
subroutine ludcmp (A, N, NP, INDX, D)
subroutine set_unr
Function/Subroutine Documentation
area2()
subroutine area2 ()
Definition at line 1066 of file coef.f.
References lelt, ly1, lz1, and setwgtr().
area3()
subroutine area3 ()
Definition at line 1188 of file coef.f.
References dot(), facexv(), lelt, ly1, lz1, unitvec(), vcross(), and vdot3().
chkjac()
subroutine chkjac (real, dimension(n) jac, n, iel, real, dimension(1) X, real, dimension(1) Y, real, dimension(1) Z, ND, IERR)
Definition at line 965 of file coef.f.
genwz()
subroutine genwz ()
Definition at line 2 of file coef.f.
References copy(), dglj(), dgljgj(), dgll(), dgllgl(), igjm(), igljm(), igllm(), iglm(), invmt(), ly1, lz1, mxm(), rzero(), zwgj(), zwgl(), zwglj(), and zwgll().
geodat1()
subroutine geodat1 ()
Definition at line 670 of file coef.f.
References cfill(), col2(), col3(), invcol3(), invers2(), lelt, ly1, lz1, rzero(), setarea(), setaxw1(), vdot2(), vdot3(), and xyzrst().
geom1()
subroutine geom1 (dimension(lx3,ly3,lz3,1) xm3, dimension(lx3,ly3,lz3,1) ym3, dimension(lx3,ly3,lz3,1) zm3)
Definition at line 361 of file coef.f.
References geodat1(), glmapm1(), and glmapm3().
geom2()
subroutine geom2 ()
Definition at line 823 of file coef.f.
References col2(), col3(), copy(), invers2(), map12(), rone(), rzero(), and setaxw2().
glmapm1()
subroutine glmapm1 ()
Definition at line 575 of file coef.f.
References addcol3(), addcol4(), ascol5(), chkjac(), chsign(), copy(), exitt(), iglsum(), invers2(), lelt, ly1, lz1, outpost(), rone(), rzero(), subcol3(), subcol4(), and xyzrst().
glmapm3()
subroutine glmapm3 (dimension(lx3,ly3,lz3,1) xm3, dimension(lx3,ly3,lz3,1) ym3, dimension(lx3,ly3,lz3,1) zm3)
Definition at line 391 of file coef.f.
References addcol3(), addcol4(), ascol5(), chkjac(), chsign(), copy(), exitt(), iglsum(), invers2(), lelt, ly1, lz1, map31(), mxm(), outpost(), rone(), rzero(), subcol3(), and subcol4().
invmt()
subroutine invmt (real, dimension(n,n) A, real, dimension(n,n) B, real, dimension(n,n) AA, N)
Definition at line 1696 of file coef.f.
References copy(), lubksb(), and ludcmp().
lagmass()
subroutine lagmass ()
Definition at line 1315 of file coef.f.
References copy(), ly1, and lz1.
lubksb()
subroutine lubksb (real, dimension(np,np) A, N, NP, integer, dimension(n) INDX, real, dimension(n) B)
Definition at line 1718 of file coef.f.
ludcmp()
subroutine ludcmp (real, dimension(np,np) A, N, NP, integer, dimension(n) INDX, D)
Definition at line 1746 of file coef.f.
References exitt().
map12()
subroutine map12 (real, dimension(lx2,ly2,lz2) y, real, dimension(lx1,ly1,lz1) x, iel)
Definition at line 1530 of file coef.f.
References copy(), ly1, lz1, and mxm().
map13()
subroutine map13 (real, dimension(lx3,ly3,lz3) y, real, dimension(lx1,ly1,lz1) x, iel)
Definition at line 1493 of file coef.f.
References copy(), ly1, lz1, and mxm().
map21e()
subroutine map21e (real, dimension(lx1,ly1,lz1) y, real, dimension(lx2,ly2,lz2) x, iel)
Definition at line 1609 of file coef.f.
References copy(), ly1, lz1, and mxm().
map21t()
subroutine map21t (real, dimension(lx1,ly1,lz1) y, real, dimension(lx2,ly2,lz2) x, iel)
Definition at line 1568 of file coef.f.
References copy(), ly1, lz1, and mxm().
map31()
subroutine map31 (real, dimension(lx1,ly1,lz1) y, real, dimension(lx3,ly3,lz3) x, iel)
Definition at line 1450 of file coef.f.
References copy(), ly1, lz1, and mxm().
maprs()
subroutine maprs (real, dimension(lx1,ly1,lz1) y, real, dimension(nrest,nrest,nrest) x, real, dimension(lx1,nrest,nrest) xa, nrest, iel)
Definition at line 1381 of file coef.f.
References copy(), igljm(), igllm(), ly1, lz1, mxm(), zwglj(), and zwgll().
out_fld_el()
subroutine out_fld_el (real, dimension(lx1,ly1,lz1,lelt) x, integer e, character*2 c2)
Definition at line 1659 of file coef.f.
References ly1, and lz1.
out_xyz_el()
subroutine out_xyz_el (real, dimension(1) x, real, dimension(1) y, real, dimension(1) z, integer e)
Definition at line 1647 of file coef.f.
References out_fld_el().
outxm3j()
subroutine outxm3j (real, dimension(lx1,ly1,lz1,lelv) xm3, real, dimension(lx1,ly1,lz1,lelv) ym3, real, dimension(lx1,ly1,lz1,lelv) jm3)
Definition at line 1676 of file coef.f.
References outmat().
set_unr()
subroutine set_unr ()
Definition at line 1811 of file coef.f.
References dsset(), ly1, and lz1.
setarea()
subroutine setarea ()
Definition at line 1043 of file coef.f.
References area2(), area3(), lz1, rzero(), and rzero3().
setinvm()
subroutine setinvm ()
Definition at line 1334 of file coef.f.
References copy(), dssum(), invcol1(), ly1, and lz1.
setwgtr()
subroutine setwgtr (dimension(lx1,1) wgtr1, dimension(ly1,1) wgtr2, dimension(lx1,1) wgtr3, dimension(ly1,1) wgtr4)
Definition at line 1135 of file coef.f.
References copy(), lelt, ly1, and lz1.
volume()
subroutine volume ()
Definition at line 1003 of file coef.f.
References glsum(), ly1, lz1, and vlsum().
xyzrst()
subroutine xyzrst (dimension(lx1,ly1,lz1,1) xrm1, dimension(lx1,ly1,lz1,1) yrm1, dimension(lx1,ly1,lz1,1) zrm1, dimension(lx1,ly1,lz1,1) xsm1, dimension(lx1,ly1,lz1,1) ysm1, dimension(lx1,ly1,lz1,1) zsm1, dimension(lx1,ly1,lz1,1) XTM1, dimension(lx1,ly1,lz1,1) YTM1, dimension(lx1,ly1,lz1,1) ZTM1, logical IFAXIS)
Definition at line 917 of file coef.f.
References ly1, lz1, mxm(), rone(), rzero(), and setaxdy().