KTH framework for Nek5000 toolboxes; testing version: Nek5000/jl/comm_test.c File Reference
comm_test.c File Reference
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include "name.h"
#include "fail.h"
#include "types.h"
#include "gs_defs.h"
#include "comm.h"
Functions
int main (int narg, char *arg[])
Function Documentation
int main (int narg, char * arg[])
Definition at line 10 of file comm_test.c.
References comm_init(), comm_scan(), gs_slong, comm::id, printf(), slong, test(), and ulong.