KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/conduct.f File Reference
conduct.f File Reference
Functions/Subroutines
subroutine cdscal (igeom)
subroutine makeuq
subroutine setqvol (bql)
subroutine nekuq (bql, iel)
subroutine convab
subroutine makeabq
subroutine makebdq
subroutine lagscal
subroutine outfldrq (x, txt10, ichk)
subroutine cdscal_expl (igeom)
subroutine diffab
subroutine set_eta_alpha2
subroutine fwght (msk1, mult)
subroutine dg_setup
subroutine dg_setup2 (mask)
subroutine cdscal_dg (igeom)
Function/Subroutine Documentation
cdscal()
subroutine cdscal (igeom)
Definition at line 3 of file conduct.f.
References add2(), axhelm(), bcdirsc(), bcneusc(), cdscal_dg(), cmult(), cvgnlps(), hsolve(), lagscal(), lelt, ly1, lz1, makeq(), sethlm(), sub2(), and sub3().
cdscal_dg()
subroutine cdscal_dg (igeom)
Definition at line 606 of file conduct.f.
References add2(), bcdirsc(), conv_bdry_dg_weak(), dg_setup2(), hmholtz_dg(), hxdg_surfa(), lagscal(), lelt, ly1, lz1, makeq(), rzero(), and sethlm().
cdscal_expl()
subroutine cdscal_expl (igeom)
Definition at line 378 of file conduct.f.
References add2(), bcdirsc(), bcneusc(), col2(), dssum(), invcol3(), lagscal(), lelt, ly1, lz1, makeq(), and sethlm().
convab()
subroutine convab ()
Definition at line 210 of file conduct.f.
References convop(), lelt, ly1, and lz1.
dg_setup()
subroutine dg_setup ()
Definition at line 551 of file conduct.f.
References dg_set_fc_ptr(), geom_reset(), invers2(), lelt, ly1, lz1, set_dg_wgts(), set_unr(), and setup_dg_gs().
dg_setup2()
subroutine dg_setup2 (real, dimension(1) mask)
Definition at line 586 of file conduct.f.
References fwght(), lelt, ly1, lz1, and set_eta_alpha2().
diffab()
subroutine diffab ()
Definition at line 442 of file conduct.f.
References axhelm(), lelt, ly1, lz1, rzero(), and sub2().
fwght()
subroutine fwght (real, dimension(lx1,ly1,lz1) msk1, real, dimension(lx1,ly1,lz1,1) mult)
Definition at line 523 of file conduct.f.
References lelt, ly1, and lz1.
lagscal()
subroutine lagscal ()
Definition at line 300 of file conduct.f.
References copy(), ly1, and lz1.
makeabq()
subroutine makeabq ()
Definition at line 236 of file conduct.f.
References ly1, and lz1.
makebdq()
subroutine makebdq ()
Definition at line 260 of file conduct.f.
References addcol3(), lelt, ly1, and lz1.
makeuq()
subroutine makeuq ()
Definition at line 111 of file conduct.f.
References col2(), ly1, lz1, and setqvol().
nekuq()
subroutine nekuq (real, dimension(lx1,ly1,lz1,lelt) bql, iel)
Definition at line 181 of file conduct.f.
References ly1, lz1, and nekasgn().
outfldrq()
subroutine outfldrq (real, dimension(lx1,ly1,lz1,lelt) x, character*10 txt10, ichk)
Definition at line 317 of file conduct.f.
References checkit(), glmax(), glmin(), ly1, and lz1.
set_eta_alpha2()
subroutine set_eta_alpha2 ()
Definition at line 477 of file conduct.f.
References dsset(), ly1, and lz1.
setqvol()
subroutine setqvol (real, dimension(lx1*ly1*lz1,lelt) bql)
Definition at line 136 of file conduct.f.
References dnekclock(), ly1, lz1, and nekuq().