KTH framework for Nek5000 toolboxes; testing version: Toolbox/utility/conht/conht_tools.f File Reference
conht_tools.f File Reference
Set of utilities related to conjugated heat transfer to build single scalar product for velocity nad temperature.
Functions/Subroutines
subroutine cht_register ()
Register conjugated heat transfer tools module.
subroutine cht_init ()
Initilise conjugated heat transfer tools module.
logical function cht_is_initialised ()
Check if module was initialised.
subroutine cht_forcing (ffx, ffy, ffz, ix, iy, iz, ieg)
Calcualte forcing ralted to conjugated heat transfer.
subroutine cht_cpfld_set ()
Set cpfld coefficient for given type of simulation.
subroutine cht_oprzero (a1, a2, a3, a4)
Zero velocity and temperature vectors.
subroutine cht_opcopy (a1, a2, a3, a4, b1, b2, b3, b4)
Copy vectors A=B (velocity and temperature)
subroutine cht_opadd2 (a1, a2, a3, a4, b1, b2, b3, b4)
Add velocity and temperature vectors A = A+B.
subroutine cht_opsub2 (a1, a2, a3, a4, b1, b2, b3, b4)
Subtract vectors A = A-B (velocity and temperature)
subroutine cht_opsub3 (a1, a2, a3, a4, b1, b2, b3, b4, c1, c2, c3, c4)
Subtract vectors A = B-C (velocity and temperature)
subroutine cht_opcmult (a1, a2, a3, a4, const)
Multiply vector by constant A = c*A (single coeff. for velocity and temperature)
subroutine cht_opcmult2c (a1, a2, a3, a4, const1, const2)
Multiply vector by constant A = c*A with separate const. for velocity and temperature.
subroutine cht_opadd2cm (a1, a2, a3, a4, b1, b2, b3, b4, coeff)
Vector summation with scaling A = A+c*B (velocity and temperature)
subroutine cht_opsub2cm (a1, a2, a3, a4, b1, b2, b3, b4, coeff)
Vector subtraction with scaling A = A-c*B (velocity and temperature)
subroutine cht_weight_fun (lvx, lvy, lvz, lt, coeff)
Weigth velocity and temperature fields.
real function cht_glsc2_wt (b1, b2, b3, b4, x1, x2, x3, x4, wt)
Global inner product of velocity and temperature fields.
Detailed Description
Set of utilities related to conjugated heat transfer to build single scalar product for velocity nad temperature.
Author
Clio Saglietti, Adam Peplinski
Date
Mar 4, 2019
Definition in file conht_tools.f.
Function/Subroutine Documentation
cht_cpfld_set()
subroutine cht_cpfld_set
Set cpfld coefficient for given type of simulation.
Definition at line 206 of file conht_tools.f.
cht_forcing()
subroutine cht_forcing (real ffx, real ffy, real ffz, integer ix, integer iy, integer iz, integer ieg)
Calcualte forcing ralted to conjugated heat transfer.
Parameters
[in,out] ffx,ffy,ffz forcing; x,y,z component
[in] ix,iy,iz GLL point index
[in] ieg global element number
Definition at line 160 of file conht_tools.f.
References gllel().
cht_glsc2_wt()
real function cht_glsc2_wt (real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) b4, real, dimension(1) x1, real, dimension(1) x2, real, dimension(1) x3, real, dimension(1) x4, real, dimension(1) wt)
Global inner product of velocity and temperature fields.
Parameters
[in] b1,b2,b3 vlocity field 1
[in] b4 temperature field 1
[in] x1,x2,x3 vlocity field 2
[in] x4 temperature field 2
[in] wt mass matrix
Returns
cht_glsc2_wt
Definition at line 590 of file conht_tools.f.
References glsum().
cht_init()
subroutine cht_init
Initilise conjugated heat transfer tools module.
Note
This routine should be called in frame_usr_init
Definition at line 82 of file conht_tools.f.
References gradm1(), mntr_warn(), and rprm_rp_get().
cht_is_initialised()
logical function cht_is_initialised
Check if module was initialised.
Returns
cht_is_initialised
Definition at line 144 of file conht_tools.f.
cht_opadd2()
subroutine cht_opadd2 (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) b4)
Add velocity and temperature vectors A = A+B.
Parameters
[in,out] a1,a2,a3 vlocity field 1
[in,out] a4 temperature field 1
[in] b1,b2,b3 vlocity field 2
[in] b4 temperature field 2
Definition at line 310 of file conht_tools.f.
References add2().
cht_opadd2cm()
subroutine cht_opadd2cm (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) b4, real coeff)
Vector summation with scaling A = A+c*B (velocity and temperature)
Parameters
[in,out] a1,a2,a3 vlocity field 1
[in,out] a4 temperature field 1
[in] b1,b2,b3 vlocity field 2
[in] b4 temperature field 2
[in] coeff scaling coefficient
Definition at line 469 of file conht_tools.f.
cht_opcmult()
subroutine cht_opcmult (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4, real const)
Multiply vector by constant A = c*A (single coeff. for velocity and temperature)
Parameters
[in,out] a1,a2,a3 vlocity fields
[in,out] a4 temperature field
[in] const coefficient
Definition at line 405 of file conht_tools.f.
References cmult().
cht_opcmult2c()
subroutine cht_opcmult2c (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4, real const1, real const2)
Multiply vector by constant A = c*A with separate const. for velocity and temperature.
Parameters
[in,out] a1,a2,a3 vlocity fields
[in,out] a4 temperature field
[in] const1 velocity coefficient
[in] const2 temperature coefficient
Definition at line 437 of file conht_tools.f.
References cmult().
cht_opcopy()
subroutine cht_opcopy (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) b4)
Copy vectors A=B (velocity and temperature)
Parameters
[out] a1,a2,a3 vlocity field 1
[out] a4 temperature field 1
[in] b1,b2,b3 vlocity field 2
[in] b4 temperature field 2
Definition at line 279 of file conht_tools.f.
References copy().
cht_oprzero()
subroutine cht_oprzero (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4)
Zero velocity and temperature vectors.
Parameters
[in,out] a1,a2,a3 vlocity field 1
[in,out] a4 temperature field 1
Definition at line 249 of file conht_tools.f.
References rzero().
cht_opsub2()
subroutine cht_opsub2 (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) b4)
Subtract vectors A = A-B (velocity and temperature)
Parameters
[in,out] a1,a2,a3 vlocity field 1
[in,out] a4 temperature field 1
[in] b1,b2,b3 vlocity field 2
[in] b4 temperature field 2
Definition at line 341 of file conht_tools.f.
References sub2().
cht_opsub2cm()
subroutine cht_opsub2cm (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) b4, real coeff)
Vector subtraction with scaling A = A-c*B (velocity and temperature)
Parameters
[in,out] a1,a2,a3 vlocity field 1
[in,out] a4 temperature field 1
[in] b1,b2,b3 vlocity field 2
[in] b4 temperature field 2
[in] coeff scaling coefficient
Definition at line 515 of file conht_tools.f.
cht_opsub3()
subroutine cht_opsub3 (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) a4, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) b4, real, dimension(1) c1, real, dimension(1) c2, real, dimension(1) c3, real, dimension(1) c4)
Subtract vectors A = B-C (velocity and temperature)
Parameters
[out] a1,a2,a3 vlocity field 1
[out] a4 temperature field 1
[in] b1,b2,b3 vlocity field 2
[in] b4 temperature field 2
[in] c1,c2,c3 vlocity field 3
[in] c4 temperature field 3
Definition at line 374 of file conht_tools.f.
References sub3().
cht_register()
subroutine cht_register
Register conjugated heat transfer tools module.
Note
This routine should be called in frame_usr_register
Definition at line 12 of file conht_tools.f.
References mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), mntr_warn(), rprm_rp_reg(), rprm_sec_reg(), and rprm_sec_set_act().
cht_weight_fun()
subroutine cht_weight_fun (real, dimension(1) lvx, real, dimension(1) lvy, real, dimension(1) lvz, real, dimension(1) lt, real coeff)
Weigth velocity and temperature fields.
Parameters
[in,out] lvx,lvy,lvz vlocity fields
[in,out] lt temperature field
[in] coeff scaling coefficient
Definition at line 559 of file conht_tools.f.
References cht_opcmult2c().