KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/connect1.f File Reference
connect1.f File Reference
Functions/Subroutines
subroutine setup_topo
subroutine initds
subroutine setedge
subroutine dsset (nx, ny, nz)
subroutine genxyzl
subroutine verify
subroutine setside
subroutine verrhe
function volum0 (P1, P2, P3, P0)
function crss2d (XY1, XY2, XY0)
subroutine facind (kx1, kx2, ky1, ky2, kz1, kz2, nx, ny, nz, iface)
subroutine facindr (kx1, kx2, ky1, ky2, kz1, kz2, nx, ny, nz, iface)
subroutine facev (a, ie, iface, val, nx, ny, nz)
subroutine ifacev (a, ie, iface, val, nx, ny, nz)
subroutine facec (a, b, ie, iface, nx, ny, nz, nel)
subroutine combin2 (glnm1, glnm2, nglob)
subroutine outfldio (x, txt10)
subroutine outfldi (x, txt10)
subroutine outfldr (x, txt10)
subroutine checkit (idum)
subroutine outfldro (x, txt10, ichk)
subroutine outfldrv (x, txt10, ichk)
subroutine outfldrv0 (x, txt10, ichk)
subroutine outfldrp0 (x, txt10, ichk)
subroutine outfldrp (x, txt10, ichk)
subroutine outmatp (a, m, n, name6, ie)
subroutine gs_chkr (glo_num)
subroutine setup_mesh_dssum
subroutine outfldnx (x, txt10, nx, ny)
Function/Subroutine Documentation
checkit()
subroutine checkit (idum)
Definition at line 1268 of file connect1.f.
combin2()
subroutine combin2 (glnm1, glnm2, nglob)
Definition at line 1130 of file connect1.f.
References exitt().
crss2d()
function crss2d (real, dimension(2) XY1, real, dimension(2) XY2, real, dimension(2) XY0)
Definition at line 1021 of file connect1.f.
dsset()
subroutine dsset (nx, ny, nz)
Definition at line 558 of file connect1.f.
facec()
subroutine facec (dimension(nx,ny,nz,nel) a, dimension(nx,ny,nz,nel) b, ie, iface, nx, ny, nz, nel)
Definition at line 1114 of file connect1.f.
References facind().
facev()
subroutine facev (dimension(nx,ny,nz,lelt) a, ie, iface, val, nx, ny, nz)
Definition at line 1082 of file connect1.f.
References facind(), and lelt.
facind()
subroutine facind (kx1, kx2, ky1, ky2, kz1, kz2, nx, ny, nz, iface)
Definition at line 1033 of file connect1.f.
facindr()
subroutine facindr (kx1, kx2, ky1, ky2, kz1, kz2, nx, ny, nz, iface)
Definition at line 1050 of file connect1.f.
genxyzl()
subroutine genxyzl ()
Definition at line 721 of file connect1.f.
References rzero().
gs_chkr()
subroutine gs_chkr (integer, dimension(lx1,ly1,lz1,lelt) glo_num)
Definition at line 1588 of file connect1.f.
References iglmax(), ly1, and lz1.
ifacev()
subroutine ifacev (integer, dimension(nx,ny,nz,lelt) a, ie, iface, integer val, nx, ny, nz)
Definition at line 1098 of file connect1.f.
References facind().
initds()
subroutine initds ()
Definition at line 180 of file connect1.f.
outfldi()
subroutine outfldi (integer, dimension(lx1,ly1,lz1,lelt) x, character*10 txt10)
Definition at line 1166 of file connect1.f.
References blank(), and ly1.
outfldio()
subroutine outfldio (integer, dimension(lx1,ly1,lz1,lelt) x, character*10 txt10)
Definition at line 1138 of file connect1.f.
References ly1, and lz1.
outfldnx()
subroutine outfldnx (real, dimension(nx,ny,4) x, character*10 txt10, nx, ny)
Definition at line 1735 of file connect1.f.
outfldr()
subroutine outfldr (real, dimension(lx1,ly1,lz1,lelt) x, character*10 txt10)
Definition at line 1217 of file connect1.f.
References blank(), and ly1.
outfldro()
subroutine outfldro (real, dimension(lx1,ly1,lz1,lelt) x, character*10 txt10, ichk)
Definition at line 1274 of file connect1.f.
References checkit(), glmax(), glmin(), ly1, and lz1.
outfldrp()
subroutine outfldrp (real, dimension(lx2,ly2,lz2,lelt) x, character*10 txt10, ichk)
Definition at line 1503 of file connect1.f.
References checkit(), glmax(), and glmin().
outfldrp0()
subroutine outfldrp0 (real, dimension(lx2,ly2,lz2,lelt) x, character*10 txt10, ichk)
Definition at line 1445 of file connect1.f.
References checkit(), glmax(), and glmin().
outfldrv()
subroutine outfldrv (real, dimension(lx1,ly1,lz1,lelt) x, character*10 txt10, ichk)
Definition at line 1328 of file connect1.f.
References checkit(), glmax(), glmin(), ly1, and lz1.
outfldrv0()
subroutine outfldrv0 (real, dimension(lx1,ly1,lz1,lelt) x, character*10 txt10, ichk)
Definition at line 1387 of file connect1.f.
References checkit(), glmax(), glmin(), ly1, and lz1.
outmatp()
subroutine outmatp (real, dimension(m,n) a, m, n, character*6 name6, ie)
Definition at line 1563 of file connect1.f.
References flush_io(), and iglmax().
setedge()
subroutine setedge ()
Definition at line 228 of file connect1.f.
References izero().
setside()
subroutine setside ()
Definition at line 821 of file connect1.f.
References cmult(), mod1(), and rzero().
setup_mesh_dssum()
subroutine setup_mesh_dssum ()
Definition at line 1619 of file connect1.f.
References cfill(), dot(), dsop(), facexs(), facexv(), icopy(), iglmax(), lelt, ly1, lz1, opdssum(), rzero(), and setupds().
setup_topo()
subroutine setup_topo ()
Definition at line 3 of file connect1.f.
References cbcmesh(), chkaxcb(), copy(), dsset(), dssum(), gen_gtp_vertex(), genxyzl(), get_vert(), glmax(), initds(), invcol1(), lelt, ly1, lz1, rone(), setcdof(), setedge(), setrzer(), setside(), setupds(), and verify().
verify()
subroutine verify ()
Definition at line 805 of file connect1.f.
References verrhe().
verrhe()
subroutine verrhe ()
Definition at line 895 of file connect1.f.
References crss2d(), exitt(), gllog(), and volum0().
volum0()
function volum0 (real, dimension(3) P1, real, dimension(3) P2, real, dimension(3) P3, real, dimension(3) P0)
Definition at line 989 of file connect1.f.