KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/connect2.f File Reference
connect2.f File Reference
Functions/Subroutines
subroutine readat
subroutine rdparam
subroutine rdmesh
subroutine rdcurve
subroutine rdbdry
subroutine rdicdf
subroutine rdmatp
subroutine rdhist
subroutine rdout
subroutine rdobj
subroutine vrdsmsh
subroutine vrdsmshx
subroutine rotat2 (xyz, angle, npts)
subroutine scale (xyzl, nl)
subroutine inrtia (xyzi, cg, xyzl, n, itype)
subroutine volume2 (vol, xyz, n)
subroutine findcg (cg, xyz, n)
subroutine divide (list1, list2, nl1, nl2, ifok, list, nl, xyzi, cg, WGT)
subroutine bin_rd1 (ifbswap)
subroutine buf_to_xyz (buf, e, ifbswap, ierr)
subroutine buf_to_curve (buf)
subroutine buf_to_bc (cbl, bl, buf)
subroutine bin_rd1_mesh (ifbswap)
subroutine bin_rd1_curve (ifbswap)
subroutine bin_rd1_bc (cbl, bl, ifbswap)
subroutine bufchk (buf, n)
subroutine buf_close_outv
subroutine buf_close_out
subroutine open_bin_file (ifbswap)
subroutine chk_xyz
subroutine chk_nel
subroutine cscan (sout, key, nk)
Function/Subroutine Documentation
subroutine bin_rd1 (logical ifbswap)
Definition at line 2177 of file connect2.f.
References bin_rd1_bc(), bin_rd1_curve(), bin_rd1_mesh(), blank(), byte_close, dnekclock(), err_chk(), lelt, and nekgsync().
subroutine bin_rd1_bc (character*3, dimension(6,lelt) cbl, real, dimension(5,6,lelt) bl, logical ifbswap)
Definition at line 2494 of file connect2.f.
References buf_close_outv(), buf_to_bc(), byte_read, byte_reverse, byte_reverse8, copyi4(), crecv(), csend(), err_chk(), exitt(), and nekgsync().
subroutine bin_rd1_curve (logical ifbswap)
Definition at line 2409 of file connect2.f.
References buf_close_out(), buf_to_curve(), byte_read, byte_reverse, byte_reverse8, copyi4(), crecv(), csend(), err_chk(), exitt(), and nekgsync().
subroutine bin_rd1_mesh (logical ifbswap)
Definition at line 2339 of file connect2.f.
References buf_to_xyz(), byte_read, crecv(), csend(), err_chk(), exitt(), and nekgsync().
subroutine buf_close_out ()
Definition at line 2627 of file connect2.f.
References csend().
subroutine buf_close_outv ()
Definition at line 2605 of file connect2.f.
References csend().
subroutine buf_to_bc (character*3, dimension(6,lelt) cbl, real, dimension(5,6,lelt) bl, integer, dimension(30) buf)
Definition at line 2297 of file connect2.f.
References chcopy(), copy(), copy4r(), and copyi4().
subroutine buf_to_curve (integer, dimension(30) buf)
Definition at line 2267 of file connect2.f.
References chcopy(), copy(), copy4r(), and copyi4().
subroutine buf_to_xyz (integer, dimension(0:49) buf, integer e, logical ifbswap, ierr)
Definition at line 2225 of file connect2.f.
References byte_reverse, byte_reverse8, copy(), copy4r(), and copyi4().
subroutine bufchk (real, dimension(n) buf, integer n)
Definition at line 2596 of file connect2.f.
subroutine chk_nel ()
Definition at line 2721 of file connect2.f.
References exitt(), iglmax(), and lelt.
subroutine chk_xyz ()
Definition at line 2707 of file connect2.f.
subroutine cscan (character*132 sout, character*132 key, nk)
Definition at line 2771 of file connect2.f.
References blank(), chcopy(), and indx1().
subroutine divide (dimension(lelt) list1, dimension(lelt) list2, nl1, nl2, logical ifok, dimension(lelt) list, nl, dimension(3) xyzi, dimension(3,lelt) cg, dimension(1) WGT)
Definition at line 2034 of file connect2.f.
References col2(), fmdian(), igop(), lelt, and list.
subroutine findcg (dimension(3,1) cg, dimension(3,8,1) xyz, n)
Definition at line 2014 of file connect2.f.
References cmult(), n, rzero(), and tmp.
subroutine inrtia (dimension(3) xyzi, dimension(3) cg, dimension(3,1) xyzl, n, itype)
Definition at line 1914 of file connect2.f.
References gop(), and n.
subroutine open_bin_file (logical ifbswap)
Definition at line 2648 of file connect2.f.
References bcast(), byte_open, byte_read, chcopy(), err_chk(), exitti(), indx2(), and izero().
subroutine rdbdry ()
Definition at line 896 of file connect2.f.
References blank(), capit(), exitt(), indx1(), lelt, and rzero().
subroutine rdcurve ()
Definition at line 803 of file connect2.f.
References blank(), exitt(), lelt, and rzero().
subroutine rdhist ()
Definition at line 1191 of file connect2.f.
References bcast(), blank(), err_chk(), exitt(), and izero().
subroutine rdicdf ()
Definition at line 1075 of file connect2.f.
References bcast(), blank(), capit(), exitti(), iglmax(), and indx1().
subroutine rdmatp ()
Definition at line 1142 of file connect2.f.
References bcast(), exitt(), izero(), and rzero().
subroutine rdmesh ()
Definition at line 713 of file connect2.f.
References exitt(), and rzero().
subroutine rdobj ()
Definition at line 1349 of file connect2.f.
References bcast(), and err_chk().
subroutine rdout ()
Definition at line 1265 of file connect2.f.
References bcast(), exitt(), exitti(), iglmax(), and lfalse().
subroutine rdparam ()
Definition at line 202 of file connect2.f.
References bcast(), capit(), exitt(), exitti(), indx1(), ly1, and lz1.
subroutine readat ()
Definition at line 3 of file connect2.f.
References bcast(), bin_rd1(), chk_nel(), cscan(), echopar(), exitt(), exitti(), flush_io(), genbox(), lelt, mapelpr(), nekgsync(), nekmoab_import(), open_bin_file(), rdbdry(), rdcurve(), rdhist(), rdicdf(), rdmatp(), rdmesh(), rdobj(), rdout(), rdparam(), and readat_new().
subroutine rotat2 (dimension(3,1) xyz, angle, npts)
Definition at line 1820 of file connect2.f.
References copy(), mod1(), mxm(), npts, and rzero().
subroutine scale (dimension(3,8,lelt) xyzl, nl)
Definition at line 1867 of file connect2.f.
References glsum(), gop(), inrtia(), lelt, rzero(), and volume2().
subroutine volume2 (dimension(1) vol, dimension(3,2,2,2,1) xyz, n)
Definition at line 1963 of file connect2.f.
References j, and n.
subroutine vrdsmsh ()
Definition at line 1404 of file connect2.f.
References col2(), copy(), dsop(), dssum(), exitt(), facev(), glmax(), glmin(), gop(), iglsum(), lelt, ly1, lz1, qmask(), rone(), sub2(), tmp, vlmax(), and vlmin().
subroutine vrdsmshx ()
Definition at line 1634 of file connect2.f.
References col2(), copy(), dsop(), dssum(), facev(), glmax(), glmin(), lelt, ly1, lz1, qmask(), rone(), sub2(), vlmax(), and vlmin().