KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/convect.f File Reference
convect.f File Reference
Functions/Subroutines
subroutine setup_convect (igeom)
subroutine char_conv (p0, u, ulag, bm, bmlag, msk, c, cs, gsl)
subroutine char_conv1 (p0, u, bmnv, n, ulag, ln, gsl, c, m, cs, nc, ct, u1, r1, r2, r3, r4, bmsk, bdivw, bdwt, bmass, bmst, bm, bmlag)
subroutine int_vel (c_t, t0, c, n, nc, ct, nid)
subroutine conv_rhs (du, u, c, bmsk, bmst, bdwt, gsl)
subroutine convop_fst_3d (du, u, c, mx, md, nel)
subroutine convop_fst_2d (du, u, c, mx, md, nel)
subroutine grad_rstd (ur, us, ut, u, mx, md, if3d, ju)
subroutine intp_rstd (ju, u, mx, md, if3d, idir)
subroutine gen_int (jgl, jgt, mp, np, w)
subroutine gen_dgl (dgl, dgt, mp, np, w)
subroutine lim_chk (n, m, avar5, lvar5, sub_name10)
subroutine get_int_ptr (ip, mx, md)
subroutine get_dgl_ptr (ip, mx, md)
subroutine set_conv_char (ct, c, ux, uy, uz, nelc, tau, ifnew)
subroutine set_ct_cvx (ct, c, m, u, v, w, tau, nc, mc, nelc, ifnew)
subroutine grad_rst (ur, us, ut, u, md, if3d)
subroutine convect_new (bdu, u, ifuf, cx, cy, cz, ifcf)
subroutine convect_cons (bdu, u, ifuf, cx, cy, cz, ifcf)
subroutine set_convect_cons (cx, cy, cz, ux, uy, uz)
subroutine set_convect_new (cr, cs, ct, ux, uy, uz)
subroutine set_char_mask (mask, u, v, w)
subroutine advchar
subroutine convch
subroutine convop_cons_3d (du, u, c, mx, md, nel)
subroutine convop_cons_2d (du, u, c, mx, md, nel)
subroutine iface_vert_int8 (fa, va, jz0, jz1, nel)
subroutine set_binv (bmnv, hmsk, n)
subroutine set_bdivw (bdivw, hmsk, n)
subroutine set_bmass (bmass, hmsk, n)
subroutine setup_dg_gs (dgh, nx, ny, nz, nel, melg, vertex)
subroutine dg_set_fc_ptr
subroutine full2face (faceary, vol_ary)
subroutine face2full (vol_ary, faceary)
subroutine add_face2full (vol_ary, faceary)
subroutine conv_rhs_dg_aliased (du, u, c)
subroutine map_faced (ju, u, mx, md, fdim, idir)
subroutine fbinvert (rhs)
subroutine grad_rstd_ta (du, ur, us, ut, md, if3d)
subroutine set_dg_wgts
subroutine conv_rhs_dg (du, u, c)
subroutine convect_dg (du, u, ifuf, cr, cs, ct, ifcf)
subroutine convop_weak (du, u, cr, cs, ct, mx, md, nel)
subroutine conv_bdry_dg_weak (du, u)
subroutine conv_rhs_dg_weak (du, u, cr, cs, ct)
Function/Subroutine Documentation
add_face2full()
subroutine add_face2full (real, dimension(lx1,ly1,lz1,lelt) vol_ary, real, dimension(lx1*lz1,2*ldim,lelt) faceary)
Definition at line 1493 of file convect.f.
advchar()
subroutine advchar ()
Definition at line 1037 of file convect.f.
References cfill(), char_conv(), col2(), dnekclock(), lelt, ly1, and lz1.
char_conv()
subroutine char_conv (real, dimension(1) p0, real, dimension(1) u, real, dimension(1) ulag, real, dimension(1) bm, real, dimension(1) bmlag, real, dimension(1) msk, real, dimension(1) c, real, dimension(0:1) cs, integer gsl)
Definition at line 91 of file convect.f.
References char_conv1(), lelt, ly1, and lz1.
char_conv1()
subroutine char_conv1 (real, dimension(n) p0, real, dimension(n) u, real, dimension(n,1) bmnv, n, real, dimension(ln,1) ulag, ln, integer gsl, real, dimension(m,0:nc) c, m, real, dimension(0:nc) cs, nc, real, dimension(m) ct, real, dimension(n) u1, real, dimension(n) r1, real, dimension(n) r2, real, dimension(n) r3, real, dimension(n) r4, real, dimension(n) bmsk, real, dimension(n,1) bdivw, real, dimension(n) bdwt, bmass, bmst, real, dimension(n) bm, real, dimension(ln,1) bmlag)
Definition at line 134 of file convect.f.
References add3s12(), col2(), conv_rhs(), int_vel(), invcol2(), invcol3(), rzero(), and vlsum().
conv_bdry_dg_weak()
subroutine conv_bdry_dg_weak (real, dimension(1) du, real, dimension(1) u)
Definition at line 1862 of file convect.f.
References full2face(), lelt, ly1, lz1, map_faced(), and rzero().
conv_rhs()
subroutine conv_rhs (real, dimension(1) du, real, dimension(1) u, real, dimension(1) c, real, dimension(1) bmsk, bmst, real, dimension(1) bdwt, integer gsl)
Definition at line 281 of file convect.f.
References col2(), conv_rhs_dg(), conv_rhs_dg_aliased(), convop_cons_2d(), convop_cons_3d(), convop_fst_2d(), convop_fst_3d(), ly1, lz1, rzero(), and subcol3().
conv_rhs_dg()
subroutine conv_rhs_dg (real, dimension(1) du, real, dimension(1) u, real, dimension(ldd*lelv,3) c)
Definition at line 1713 of file convect.f.
References add_face2full(), col2(), conv_rhs_dg_weak(), fbinvert(), full2face(), lelt, ly1, lz1, map_faced(), and rzero().
conv_rhs_dg_aliased()
subroutine conv_rhs_dg_aliased (real, dimension(1) du, real, dimension(1) u, real, dimension(1) c)
Definition at line 1510 of file convect.f.
References add_face2full(), col2(), convop_cons_2d(), convop_cons_3d(), convop_fst_2d(), convop_fst_3d(), fbinvert(), full2face(), lelt, ly1, lz1, and rzero().
conv_rhs_dg_weak()
subroutine conv_rhs_dg_weak (real, dimension(1) du, real, dimension(1) u, real, dimension(1) cr, real, dimension(1) cs, real, dimension(1) ct)
Definition at line 1949 of file convect.f.
References convop_weak(), copy(), full2face(), lelt, ly1, lz1, map_faced(), and rzero().
convch()
subroutine convch ()
Definition at line 1098 of file convect.f.
References char_conv(), dnekclock(), lelt, ly1, and lz1.
convect_cons()
subroutine convect_cons (real, dimension(1) bdu, real, dimension(1) u, logical ifuf, real, dimension(1) cx, real, dimension(1) cy, real, dimension(1) cz, logical ifcf)
Definition at line 820 of file convect.f.
References col2(), exitt(), grad_rst(), intp_rstd(), ly1, lz1, rzero(), and set_dealias_rx().
convect_dg()
subroutine convect_dg (real, dimension(1) du, real, dimension(1) u, logical ifuf, real, dimension(1) cr, real, dimension(1) cs, real, dimension(1) ct, logical ifcf)
Definition at line 1800 of file convect.f.
References conv_rhs_dg_weak().
convect_new()
subroutine convect_new (real, dimension(1) bdu, real, dimension(1) u, logical ifuf, real, dimension(1) cx, real, dimension(1) cy, real, dimension(1) cz, logical ifcf)
Definition at line 727 of file convect.f.
References copy(), grad_rst(), intp_rstd(), ly1, lz1, and set_dealias_rx().
convop_cons_2d()
subroutine convop_cons_2d (real, dimension(mx*mx,nel) du, real, dimension(mx*mx,nel) u, real, dimension(md*md,nel,2) c, mx, md, nel)
Definition at line 1193 of file convect.f.
References grad_rst(), intp_rstd(), lim_chk(), and rzero().
convop_cons_3d()
subroutine convop_cons_3d (real, dimension(mx*mx*mx,nel) du, real, dimension(mx*mx*mx,nel) u, real, dimension(md*md*md,nel,3) c, mx, md, nel)
Definition at line 1138 of file convect.f.
References grad_rst(), intp_rstd(), lim_chk(), and rzero().
convop_fst_2d()
subroutine convop_fst_2d (real, dimension(mx*mx,nel) du, real, dimension(mx*mx,nel) u, real, dimension(md*md,nel,2) c, mx, md, nel)
Definition at line 367 of file convect.f.
References grad_rstd(), intp_rstd(), and lim_chk().
convop_fst_3d()
subroutine convop_fst_3d (real, dimension(mx*mx*mx,nel) du, real, dimension(mx*mx*mx,nel) u, real, dimension(md*md*md,nel,3) c, mx, md, nel)
Definition at line 325 of file convect.f.
References grad_rstd(), intp_rstd(), and lim_chk().
convop_weak()
subroutine convop_weak (real, dimension(lxx,nel) du, real, dimension(lxx,nel) u, real, dimension(ldd,nel) cr, real, dimension(ldd,nel) cs, real, dimension(ldd,nel) ct, mx, md, nel)
Definition at line 1811 of file convect.f.
References grad_rstd_ta(), intp_rstd(), lim_chk(), ly1, and lz1.
dg_set_fc_ptr()
subroutine dg_set_fc_ptr ()
Definition at line 1408 of file convect.f.
References dsset(), ly1, and lz1.
face2full()
subroutine face2full (real, dimension(lx1,ly1,lz1,lelt) vol_ary, real, dimension(lx1*lz1,2*ldim,lelt) faceary)
Definition at line 1473 of file convect.f.
References ly1, lz1, and rzero().
fbinvert()
subroutine fbinvert (real, dimension(lx1,ly1,lz1,lelt) rhs)
Definition at line 1628 of file convect.f.
References lelt, ly1, and lz1.
full2face()
subroutine full2face (real, dimension(lx1*lz1,2*ldim,lelt) faceary, real, dimension(lx1,ly1,lz1,lelt) vol_ary)
Definition at line 1455 of file convect.f.
gen_dgl()
subroutine gen_dgl (real, dimension(mp,np) dgl, real, dimension(np*mp) dgt, mp, np, real, dimension(1) w)
Definition at line 503 of file convect.f.
References fd_weights_full(), lim_chk(), transpose(), and zwgl().
gen_int()
subroutine gen_int (real, dimension(mp,np) jgl, real, dimension(np*mp) jgt, mp, np, real, dimension(1) w)
Definition at line 470 of file convect.f.
References fd_weights_full(), transpose(), zwgl(), and zwgll().
get_dgl_ptr()
subroutine get_dgl_ptr (ip, mx, md)
Definition at line 594 of file convect.f.
References gen_dgl(), and lim_chk().
get_int_ptr()
subroutine get_int_ptr (ip, mx, md)
Definition at line 556 of file convect.f.
References gen_int(), and lim_chk().
grad_rst()
subroutine grad_rst (real, dimension(1) ur, real, dimension(1) us, real, dimension(1) ut, real, dimension(1) u, md, logical if3d)
Definition at line 703 of file convect.f.
References get_dgl_ptr(), local_grad2(), and local_grad3().
grad_rstd()
subroutine grad_rstd (real, dimension(1) ur, real, dimension(1) us, real, dimension(1) ut, real, dimension(1) u, mx, md, logical if3d, real, dimension(1) ju)
Definition at line 409 of file convect.f.
References get_dgl_ptr(), intp_rstd(), local_grad2(), and local_grad3().
grad_rstd_ta()
subroutine grad_rstd_ta (du, real, dimension(1) ur, real, dimension(1) us, real, dimension(1) ut, md, logical if3d)
Definition at line 1653 of file convect.f.
References get_dgl_ptr(), and gradrta().
iface_vert_int8()
subroutine iface_vert_int8 (integer*8, dimension(lx1*lz1,2*ldim,nel) fa, integer*8, dimension(0:lx1+1,0:ly1+1,jz0:jz1,nel) va, jz0, jz1, nel)
Definition at line 1254 of file convect.f.
References facind(), i8zero(), ly1, and lz1.
int_vel()
subroutine int_vel (real, dimension(n) c_t, t0, real, dimension(n,0:nc) c, n, nc, real, dimension(0:nc) ct, nid)
Definition at line 249 of file convect.f.
References exitt(), fd_weights_full(), and rzero().
intp_rstd()
subroutine intp_rstd (real, dimension(1) ju, real, dimension(1) u, mx, md, logical if3d, idir)
Definition at line 435 of file convect.f.
References get_int_ptr(), lim_chk(), and specmpn().
lim_chk()
subroutine lim_chk (n, m, character*5 avar5, character*5 lvar5, character*10 sub_name10)
Definition at line 542 of file convect.f.
References exitti().
map_faced()
subroutine map_faced (real, dimension(1) ju, real, dimension(1) u, mx, md, integer fdim, idir)
Definition at line 1582 of file convect.f.
References get_int_ptr(), lim_chk(), and mxm().
set_bdivw()
subroutine set_bdivw (real, dimension(n,lorder) bdivw, real, dimension(n) hmsk, n)
Definition at line 1331 of file convect.f.
References add2(), col2(), copy(), gradm1(), lelt, ly1, and lz1.
set_binv()
subroutine set_binv (real, dimension(n,lorder) bmnv, real, dimension(n) hmsk, n)
Definition at line 1308 of file convect.f.
References copy().
set_bmass()
subroutine set_bmass (real, dimension(n,lorder) bmass, real, dimension(n) hmsk, n)
Definition at line 1360 of file convect.f.
References copy().
set_char_mask()
subroutine set_char_mask (real, dimension(lxyz1,1) mask, real, dimension(lxyz1,1) u, real, dimension(lxyz1,1) v, real, dimension(lxyz1,1) w)
Definition at line 992 of file convect.f.
References dsop(), faccl3(), facev(), faddcl3(), fcaver(), lelt, ly1, lz1, rone(), and rzero().
set_conv_char()
subroutine set_conv_char (real, dimension(0:1) ct, real, dimension(1) c, real, dimension(1) ux, real, dimension(1) uy, real, dimension(1) uz, integer nelc, tau, logical ifnew)
Definition at line 632 of file convect.f.
References exitti(), and set_ct_cvx().
set_convect_cons()
subroutine set_convect_cons (real, dimension(ltd,1) cx, real, dimension(ltd,1) cy, real, dimension(ltd,1) cz, real, dimension(lxy,1) ux, real, dimension(lxy,1) uy, real, dimension(lxy,1) uz)
Definition at line 906 of file convect.f.
References intp_rstd(), ly1, lz1, and set_dealias_rx().
set_convect_new()
subroutine set_convect_new (real, dimension(ltd,1) cr, real, dimension(ltd,1) cs, real, dimension(ltd,1) ct, real, dimension(lxy,1) ux, real, dimension(lxy,1) uy, real, dimension(lxy,1) uz)
Definition at line 934 of file convect.f.
References intp_rstd(), ly1, lz1, and set_dealias_rx().
set_ct_cvx()
subroutine set_ct_cvx (real, dimension(0:1) ct, real, dimension(m,1) c, m, real, dimension(1) u, real, dimension(1) v, real, dimension(1) w, tau, nc, mc, nelc, logical ifnew)
Definition at line 663 of file convect.f.
References copy(), set_convect_cons(), and set_convect_new().
set_dg_wgts()
subroutine set_dg_wgts ()
Definition at line 1673 of file convect.f.
References copy(), ly1, lz1, and zwgl().
setup_convect()
subroutine setup_convect (igeom)
Definition at line 32 of file convect.f.
References exitti(), lelt, ly1, lz1, opsub3(), rone(), rzero(), set_bdivw(), set_binv(), set_bmass(), set_char_mask(), set_conv_char(), set_convect_cons(), and set_convect_new().
setup_dg_gs()
subroutine setup_dg_gs (integer dgh, nx, ny, nz, nel, melg, integer, dimension(1) vertex)
Definition at line 1377 of file convect.f.
References iface_vert_int8(), lelt, ly1, lz1, and set_vert().