KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/crs.f File Reference
crs.f File Reference
Functions/Subroutines
subroutine spy_csrmat (ia, ja, n, name9)
subroutine rint (a, n)
subroutine iint (a, n)
subroutine cfill (a, b, n)
subroutine lfalse (a, n)
subroutine period_coinc (vertex, start_pt, nv)
subroutine find_match (vlist, iface, ie, jf, je)
subroutine reset_v (vertex, v1, v2, nv)
subroutine out_csrmat (acsr, ia, ja, n, name)
subroutine period_check (ifld)
subroutine period_bc_check (if_any_per)
subroutine out_csr_matl (ia, ja, vals, n)
Function/Subroutine Documentation
subroutine cfill (real, dimension(1) a, b, n)
Definition at line 47 of file crs.f.
References i, and n.
subroutine find_match (integer, dimension(4,2) vlist, iface, ie, jf, je)
Definition at line 148 of file crs.f.
References dmin, mod1(), and rzero().
subroutine iint (integer, dimension(1) a, n)
Definition at line 39 of file crs.f.
References i, and n.
subroutine lfalse (logical, dimension(1) a, n)
Definition at line 56 of file crs.f.
References i, and n.
subroutine out_csr_matl (integer, dimension(1) ia, integer, dimension(1) ja, real*8, dimension(1) vals, n)
Definition at line 363 of file crs.f.
References i, j, and n.
subroutine out_csrmat (real, dimension(1) acsr, integer, dimension(1) ia, integer, dimension(1) ja, n, character*9 name)
Definition at line 244 of file crs.f.
References blank(), i, j, and n.
subroutine period_bc_check (logical if_any_per)
Definition at line 329 of file crs.f.
subroutine period_check (ifld)
Definition at line 279 of file crs.f.
References blank(), prs(), and rzero().
subroutine period_coinc (integer, dimension(1) vertex, integer, dimension(1) start_pt, integer nv)
Definition at line 64 of file crs.f.
References blank(), find_match(), i, prs(), and reset_v().
subroutine reset_v (integer, dimension(1) vertex, integer v1, integer v2, nv)
Definition at line 229 of file crs.f.
References i.
subroutine rint (real, dimension(1) a, n)
Definition at line 31 of file crs.f.
References i, and n.
subroutine spy_csrmat (integer, dimension(1) ia, integer, dimension(1) ja, n, character*9 name9)
Definition at line 4 of file crs.f.
References blank(), i, j, and n.