KTH framework for Nek5000 toolboxes; testing version: Nek5000/jl/crystal_test.c File Reference
crystal_test.c File Reference
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "c99.h"
#include "name.h"
#include "fail.h"
#include "types.h"
#include "comm.h"
#include "mem.h"
#include "crystal.h"
Functions
int main (int narg, char *arg[])
Function Documentation
int main (int narg, char * arg[])
Definition at line 13 of file crystal_test.c.
References buffer_reserve, comm_init(), crystal_free, crystal_init, crystal_router, data(), crystal::data, diagnostic(), fail(), i, comm::id, array::n, comm::np, printf(), array::ptr, and uint.