KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/curve.f File Reference
curve.f File Reference
Functions/Subroutines
subroutine curves
subroutine mesgen
subroutine getedg (isid, iels)
subroutine export (iedge, iel)
subroutine stretch_sphere
subroutine find_long_edges
function long_edge_e (e)
subroutine hexagon_tile
subroutine hex_transition_3d_e (el, en)
subroutine hex_transition_3d
subroutine hexagon_refine_e (e, en)
subroutine hexagon_refine
subroutine rotate_element (e, kface)
subroutine get_el2 (nlist, elist)
subroutine get_els (nlist, elist)
subroutine get_els_bc (nlist, elist)
subroutine fix_m_curve_old (e)
subroutine fix_m_curve (e)
subroutine s2vec (x, y, z, u, v, w, r)
subroutine make_top (xl, yl, zl, r)
subroutine make_core (xl, yl, zl, r)
subroutine filled_sphere_oct
subroutine make_top_2d (xl, yl, zl, r)
subroutine make_core_2d (xl, yl, zl, r)
subroutine filled_cyl_quadrant
function blend_circ_in_box (x, y, r0, x0i, x1i, y0i, y1i)
function in_triangle (p, a, b, c)
subroutine x27_to_e
subroutine std_transform (t0, t1)
subroutine get_x27max (xmin, xmax, ymin, ymax, zmin, zmax)
subroutine make_arc_circ
subroutine circle_in_arc_transform_0 (r1)
Function/Subroutine Documentation
function blend_circ_in_box (x, y, r0, x0i, x1i, y0i, y1i)
Definition at line 1741 of file curve.f.
References cmult(), i, and in_triangle().
subroutine circle_in_arc_transform_0 (r1)
Definition at line 1978 of file curve.f.
References get_x27max(), i, n, redraw_mesh(), and x27_to_e().
subroutine curves ()
Definition at line 18 of file curve.f.
References cirmesh(), color, convert_m_to_c_all(), drawel(), export(), filled_cyl_quadrant(), filled_sphere_oct(), fix_m_curve(), gencen(), genmesh(), getedg(), gwrite(), hex_transition_3d(), hexagon_refine(), hexagon_tile(), i, make_arc_circ(), menu(), mouse(), nw_sphmesh(), prs(), redraw_mesh(), renum_special(), rer(), rzero(), sphmesh(), stretch_sphere(), vertadj(), vlsum(), and xdot().
subroutine export (iedge, iel)
Definition at line 460 of file curve.f.
References drawel(), i, and prs().
subroutine filled_cyl_quadrant ()
Definition at line 1696 of file curve.f.
References make_core_2d(), make_top_2d(), msplite(), prs(), reii(), rer(), and vertadj().
subroutine filled_sphere_oct ()
Definition at line 1507 of file curve.f.
References copyel(), make_core(), make_top(), msplite(), prs(), reii(), rer(), rone(), and rotate_el_vec().
subroutine find_long_edges ()
Definition at line 653 of file curve.f.
References long_edge_e().
subroutine fix_m_curve (integer e)
Definition at line 1271 of file curve.f.
References copy(), drawel(), i, j, and rzero().
subroutine fix_m_curve_old (integer e)
Definition at line 1243 of file curve.f.
subroutine get_el2 (nlist, integer, dimension(1) elist)
Definition at line 1116 of file curve.f.
References get_els(), i, and izero().
subroutine get_els (nlist, integer, dimension(1) elist)
Definition at line 1136 of file curve.f.
References drwbox(), get_els_bc(), mouse(), prs(), rerr(), xphy(), and yphy().
subroutine get_els_bc (nlist, integer, dimension(1) elist)
Definition at line 1218 of file curve.f.
subroutine get_x27max (xmin, xmax, ymin, ymax, zmin, zmax)
Definition at line 1912 of file curve.f.
References glmax(), glmin(), and n.
subroutine getedg (isid, iels)
Definition at line 387 of file curve.f.
References i, mod1(), mouse(), prs(), rmin(), and xscr().
subroutine hex_transition_3d ()
Definition at line 878 of file curve.f.
References find_long_edges(), gencen(), hex_transition_3d_e(), and rotate_element().
subroutine hex_transition_3d_e (integer el, integer en)
Definition at line 799 of file curve.f.
References copyel(), drawel(), evalsc(), genxyz_e(), i, nx, and nz.
subroutine hexagon_refine ()
Definition at line 988 of file curve.f.
References find_long_edges(), gen_neigh(), gencen(), get_el2(), hexagon_refine_e(), and redraw_mesh().
subroutine hexagon_refine_e (integer e, integer en)
Definition at line 900 of file curve.f.
References copyel(), drawel(), evalsc(), genxyz_e(), i, j, nx, and nz.
subroutine hexagon_tile ()
Definition at line 688 of file curve.f.
References cadd(), cmult2(), drawel(), drwbox(), i, j, mouse(), outmat(), prs(), rzero(), xphy(), and yphy().
function in_triangle (real, dimension(2) p, real, dimension(2) a, real, dimension(2) b, real, dimension(2) c)
Definition at line 1802 of file curve.f.
References sub3(), and vlsc2().
function long_edge_e (integer e)
Definition at line 664 of file curve.f.
References i.
subroutine make_arc_circ ()
Definition at line 1926 of file curve.f.
References circle_in_arc_transform_0(), fix_m_curve(), gencen(), get_x27max(), prs(), rei(), and std_transform().
subroutine make_core (real, dimension(3,3,3) xl, real, dimension(3,3,3) yl, real, dimension(3,3,3) zl, r)
Definition at line 1410 of file curve.f.
References blank(), j, linquad(), rzero(), s2vec(), and xyzlin().
subroutine make_core_2d (real, dimension(3,3,3) xl, real, dimension(3,3,3) yl, real, dimension(3,3,3) zl, r)
Definition at line 1620 of file curve.f.
References blank(), j, linquad(), rzero(), s2vec(), and xyzlin().
subroutine make_top (real, dimension(3,3,3) xl, real, dimension(3,3,3) yl, real, dimension(3,3,3) zl, r)
Definition at line 1358 of file curve.f.
References blank(), chcopy(), copy(), copyel(), rzero(), and s2vec().
subroutine make_top_2d (real, dimension(3,3,3) xl, real, dimension(3,3,3) yl, real, dimension(3,3,3) zl, r)
Definition at line 1560 of file curve.f.
References blank(), copy(), copyel(), rzero(), and s2vec().
subroutine mesgen ()
Definition at line 227 of file curve.f.
References color, drawc(), drawed(), getpts(), hard(), i, j, movec(), nohard(), nx, nz, prs(), and prsis().
subroutine rotate_element (integer e, kface)
Definition at line 1058 of file curve.f.
References copy(), copyel(), i, and prsii().
subroutine s2vec (x, y, z, u, v, w, r)
Definition at line 1340 of file curve.f.
subroutine std_transform (t0, t1)
Definition at line 1859 of file curve.f.
References gencen(), glmax(), glmin(), i, n, redraw_mesh(), rr, and x27_to_e().
subroutine stretch_sphere ()
Definition at line 562 of file curve.f.
References i, prs(), rer(), rerrr(), and rr.
subroutine x27_to_e ()
Definition at line 1828 of file curve.f.
References q_to_neklin().