KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/cvode_driver.f File Reference
cvode_driver.f File Reference
Functions/Subroutines
subroutine cv_setsize
subroutine cv_init
subroutine cdscal_cvode
subroutine fcvjtimes (V, FJV, TT, Y, FY, H, IPAR, RPAR, WORK, IER)
subroutine cv_upd_v
subroutine cv_upd_w
subroutine cv_upd_coor
subroutine fcvfun (time_, y, ydot, ipar, rpar, ier)
subroutine cv_eval_geom
subroutine cv_settime
subroutine cv_pstat
subroutine cv_rstat
Function/Subroutine Documentation
subroutine cdscal_cvode ()
Definition at line 21 of file cvode_driver.f.
References cfill(), copy(), create_comm(), cv_eval_geom(), cv_pstat(), cv_rstat(), cvunpack(), dnekclock_sync(), exitt(), j, ly1, lz1, setup_convect(), and vlmax().
subroutine cv_eval_geom ()
Definition at line 624 of file cvode_driver.f.
References geodat1(), geom2(), glmapm1(), setdef(), setinvm(), and volume().
subroutine cv_init ()
Definition at line 12 of file cvode_driver.f.
References exitt().
subroutine cv_pstat ()
Definition at line 661 of file cvode_driver.f.
subroutine cv_rstat ()
Definition at line 697 of file cvode_driver.f.
subroutine cv_setsize ()
Definition at line 3 of file cvode_driver.f.
References exitt().
subroutine cv_settime ()
Definition at line 637 of file cvode_driver.f.
References rzero(), and setabbd().
subroutine cv_upd_coor ()
Definition at line 467 of file cvode_driver.f.
References add3(), ly1, lz1, and sumab().
subroutine cv_upd_v ()
Definition at line 412 of file cvode_driver.f.
References ly1, lz1, and sumab().
subroutine cv_upd_w ()
Definition at line 440 of file cvode_driver.f.
References ly1, lz1, and sumab().
subroutine fcvfun (real time_, real, dimension(1) y, real, dimension(1) ydot, integer*8, dimension(1) ipar, real, dimension(1) rpar, ier)
Definition at line 504 of file cvode_driver.f.
References col2(), col3(), copy(), cv_eval_geom(), cv_settime(), cv_upd_coor(), cv_upd_v(), cv_upd_w(), cvunpack(), dnekclock(), dssum(), invcol3(), lelt, ly1, lz1, makeq(), nvec_dssum(), set_convect_new(), sub2(), and vprops().
subroutine fcvjtimes (real, dimension(*) V, real, dimension(*) FJV, real TT, real, dimension(*) Y, real, dimension(*) FY, real H, integer*8, dimension(1) IPAR, real, dimension(1) RPAR, real, dimension(*) WORK, IER)
Definition at line 360 of file cvode_driver.f.
References dnorm(), fcvfun(), and glsum().