KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/d1ops.f File Reference
d1ops.f File Reference
Functions/Subroutines
subroutine semhat (a, b, c, d, dp, jp, z, n, w)
subroutine fd_weights_full (xx, x, n, m, c)
Function/Subroutine Documentation
subroutine fd_weights_full (xx, real, dimension(0:n) x, n, m, real, dimension(0:n,0:m) c)
Definition at line 57 of file d1ops.f.
References i, j, and n.
subroutine semhat (real, dimension(0:n,0:n) a, real, dimension(0:n) b, real, dimension(0:n,0:n) c, real, dimension(0:n,0:n) d, real, dimension(0:n,1:n-1) dp, real, dimension(0:n,1:n-1) jp, real, dimension(0:n) z, n, real, dimension(0:1) w)
Definition at line 3 of file d1ops.f.
References fd_weights_full(), i, j, n, rzero(), and zwgll().