KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/dc.f File Reference
dc.f File Reference
Functions/Subroutines
subroutine draw_circ1 (x3, y3, z3, r)
Function/Subroutine Documentation
subroutine draw_circ1 (x3, y3, z3, r)
Definition at line 3 of file dc.f.
References drawc(), i, movec(), n, xiso(), and yiso().