KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/cmt/diagnostics.f File Reference
diagnostics.f File Reference
Functions/Subroutines
subroutine printalot (e, f, lu, pileoffaces)
subroutine matout_rowsum (ab, na, nb)
subroutine out_fld_nek (wfnav)
subroutine out_pvar_nek (wfnav)
subroutine dumpresidue (wfnav, inmbr)
subroutine mass_balance (if3d)
subroutine torque_calc_cmt (scale, x0, ifdout, iftout)
subroutine comp_sij_cmt (sij, nij, ur, us, ut, vr, vs, vt, wr, ws, wt)
Function/Subroutine Documentation
subroutine comp_sij_cmt (real, dimension(lx1*ly1*lz1,nij,lelt) sij, nij, real, dimension (1) ur, real, dimension (1) us, real, dimension (1) ut, real, dimension (1) vr, real, dimension (1) vs, real, dimension (1) vt, real, dimension (1) wr, real, dimension (1) ws, real, dimension (1) wt)
Definition at line 508 of file diagnostics.f.
References copy(), i, local_grad2(), local_grad3(), ly1, lz1, n, and setaxdy().
subroutine dumpresidue (character*32 wfnav, integer inmbr)
Definition at line 130 of file diagnostics.f.
subroutine mass_balance (logical if3d)
Definition at line 217 of file diagnostics.f.
References glsum(), i, lelt, ly1, and lz1.
subroutine matout_rowsum (real, dimension(na,nb) ab, integer na, integer nb)
Definition at line 58 of file diagnostics.f.
References i.
subroutine out_fld_nek (wfnav)
Definition at line 70 of file diagnostics.f.
References copy(), exitti(), lelt, ly1, lz1, n, and outpost2().
subroutine out_pvar_nek (wfnav)
Definition at line 96 of file diagnostics.f.
References copy(), exitti(), i, lelt, ly1, lz1, mixtperf_g_cpr(), mixtperf_po_gptto(), mixtperf_to_cptuvw(), n, and outpost2().
subroutine printalot (integer e, integer f, integer lu, real, dimension(nx1*nz1,2*ndim,nelt,toteq) pileoffaces)
Definition at line 2 of file diagnostics.f.
References full2face_cmt(), i, and lz1.
subroutine torque_calc_cmt (scale, real, dimension(3) x0, logical ifdout, logical iftout)
Definition at line 265 of file diagnostics.f.
References cadd2(), cfill(), cmult(), comp_sij_cmt(), copy(), drgtrq(), glmax(), glmin(), gop(), i, i0, iglmax(), lelt, ly1, lz1, n, and scale().