KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/cmt/diffusive_cmt.f File Reference
diffusive_cmt.f File Reference
routines for diffusive fluxes. Some surface. Some volume. All pain. Jacobians and other factorizations.
Functions/Subroutines
subroutine fluxj_ns (flux, gradu, e, eq)
Navier-Stokes, so no mass diffusion. uservp provides properties. Implemented via maxima-generated code
subroutine fluxj_evm (flux, du, e, eq)
viscous flux jacobian for entropy viscosity Euler regularization of Guermond and Popov (2014) SIAM JAM 74(2) that do NOT overlap with the compressible Navier-Stokes equations (NS).
subroutine half_iku_cmt (res, diffh, e)
subroutine compute_transport_props
subroutine a51klduldxk (flux, dU, ie)
subroutine a52klduldxk (flux, dU, ie)
subroutine a53klduldxk (flux, dU, ie)
subroutine a21klduldxk (flux, dU, ie)
subroutine a22klduldxk (flux, dU, ie)
subroutine a23klduldxk (flux, dU, ie)
subroutine a31klduldxk (flux, dU, ie)
subroutine a32klduldxk (flux, dU, ie)
subroutine a33klduldxk (flux, dU, ie)
subroutine a41klduldxk (flux, dU, ie)
subroutine a42klduldxk (flux, dU, ie)
subroutine a43klduldxk (flux, dU, ie)
subroutine imqqtu (ummcu, uminus, uplus)
ummcu =
subroutine imqqtu_dirichlet (umubc, wminus, wplus)
umubc =
subroutine agradu (flux, du, e, eq)
flux = dU = dU
Detailed Description
routines for diffusive fluxes. Some surface. Some volume. All pain. Jacobians and other factorizations.
Definition in file diffusive_cmt.f.
Function/Subroutine Documentation
subroutine a21klduldxk (real, dimension(nx1*ny1*nz1) flux, real, dimension(nx1*ny1*nz1,toteq,3) dU, ie)
Definition at line 497 of file diffusive_cmt.f.
References i, ly1, and lz1.
subroutine a22klduldxk (real, dimension(nx1*ny1*nz1) flux, real, dimension(nx1*ny1*nz1,toteq,3) dU, ie)
Definition at line 524 of file diffusive_cmt.f.
References i, ly1, and lz1.
subroutine a23klduldxk (real, dimension(nx1*ny1*nz1) flux, real, dimension(nx1*ny1*nz1,toteq,3) dU, ie)
Definition at line 545 of file diffusive_cmt.f.
References i, ly1, and lz1.
subroutine a31klduldxk (real, dimension(nx1*ny1*nz1) flux, real, dimension(nx1*ny1*nz1,toteq,3) dU, ie)
Definition at line 567 of file diffusive_cmt.f.
References i, ly1, and lz1.
subroutine a32klduldxk (real, dimension(nx1*ny1*nz1) flux, real, dimension(nx1*ny1*nz1,toteq,3) dU, ie)
Definition at line 588 of file diffusive_cmt.f.
References i, ly1, and lz1.
subroutine a33klduldxk (real, dimension(nx1*ny1*nz1) flux, real, dimension(nx1*ny1*nz1,toteq,3) dU, ie)
Definition at line 615 of file diffusive_cmt.f.
References i, ly1, and lz1.
subroutine a41klduldxk (real, dimension(nx1*ny1*nz1) flux, real, dimension(nx1*ny1*nz1,toteq,3) dU, ie)
Definition at line 637 of file diffusive_cmt.f.
References i, ly1, and lz1.
subroutine a42klduldxk (real, dimension(nx1*ny1*nz1) flux, real, dimension(nx1*ny1*nz1,toteq,3) dU, ie)
Definition at line 658 of file diffusive_cmt.f.
References i, ly1, and lz1.
subroutine a43klduldxk (real, dimension(nx1*ny1*nz1) flux, real, dimension(nx1*ny1*nz1,toteq,3) dU, ie)
Definition at line 679 of file diffusive_cmt.f.
References i, ly1, and lz1.
subroutine a51klduldxk (real, dimension(nx1*ny1*nz1) flux, real, dimension(nx1*ny1*nz1,toteq,3) dU, ie)
Definition at line 363 of file diffusive_cmt.f.
References i, ly1, and lz1.
subroutine a52klduldxk (real, dimension(nx1*ny1*nz1) flux, real, dimension(nx1*ny1*nz1,toteq,3) dU, ie)
Definition at line 408 of file diffusive_cmt.f.
References i, ly1, and lz1.
subroutine a53klduldxk (real, dimension(nx1*ny1*nz1) flux, real, dimension(nx1*ny1*nz1,toteq,3) dU, ie)
Definition at line 452 of file diffusive_cmt.f.
References i, ly1, and lz1.
subroutine compute_transport_props ()
Definition at line 323 of file diffusive_cmt.f.
References cmtasgn(), i, and nekasgn().
subroutine fluxj_evm (real, dimension(nx1*ny1*nz1,ndim) flux, real, dimension(nx1*ny1*nz1,toteq,ndim) du, integer e, integer eq)
viscous flux jacobian for entropy viscosity Euler regularization of Guermond and Popov (2014) SIAM JAM 74(2) that do NOT overlap with the compressible Navier-Stokes equations (NS).
Definition at line 235 of file diffusive_cmt.f.
References addcol3(), col2(), col4(), copy(), invcol2(), ly1, lz1, n, sub2(), vdot2(), and vdot3().
subroutine fluxj_ns (real, dimension(nx1*ny1*nz1,ndim) flux, real, dimension(nx1*ny1*nz1,toteq,ndim) gradu, integer e, integer eq)
Navier-Stokes, so no mass diffusion. uservp provides properties. Implemented via maxima-generated code
Definition at line 158 of file diffusive_cmt.f.
References a21klduldxk(), a22klduldxk(), a23klduldxk(), a31klduldxk(), a32klduldxk(), a33klduldxk(), a41klduldxk(), a42klduldxk(), a43klduldxk(), a51klduldxk(), a52klduldxk(), a53klduldxk(), ly1, lz1, n, and rzero().
subroutine half_iku_cmt (real, dimension(nx1,ny1,nz1) res, real, dimension(nx1*ny1*nz1,ndim) diffh, integer e)
Definition at line 300 of file diffusive_cmt.f.
References col2(), gradm11_t(), and n.