KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/dprocmap.f File Reference
dprocmap.f File Reference
Functions/Subroutines
subroutine dprocmapinit ()
subroutine dprocmapput (ibuf, lbuf, ioff, ieg)
subroutine dprocmapget (ibuf, ieg)
subroutine dprocmapfind (il, nids, ieg)
integer function lsearch_ur (a, n, k)
integer function gllnid (ieg)
integer function gllel (ieg)
Function/Subroutine Documentation
dprocmapfind()
subroutine dprocmapfind (il, nids, ieg)
Definition at line 129 of file dprocmap.f.
dprocmapget()
subroutine dprocmapget (integer, dimension(2) ibuf, ieg)
Definition at line 68 of file dprocmap.f.
References dprocmapfind(), exitti(), icopy(), ifill(), and lsearch_ur().
dprocmapinit()
subroutine dprocmapinit
Definition at line 11 of file dprocmap.f.
References exitti().
dprocmapput()
subroutine dprocmapput (integer, dimension(lbuf) ibuf, lbuf, ioff, ieg)
Definition at line 40 of file dprocmap.f.
References dprocmapfind(), exitti(), and icopy().
gllel()
integer function gllel (ieg)
Definition at line 183 of file dprocmap.f.
References dprocmapget().
gllnid()
integer function gllnid (ieg)
Definition at line 161 of file dprocmap.f.
References dprocmapget().
lsearch_ur()
integer function lsearch_ur (integer, dimension(n) a, integer n, integer k)
Definition at line 145 of file dprocmap.f.