KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/cmt/drive2_cmt.f File Reference
drive2_cmt.f File Reference
mid-level initialization drivers. Not long for this world.
Functions/Subroutines
subroutine nek_cmt_init
subroutine izero8 (a, n)
subroutine setup_cmt_param
Detailed Description
mid-level initialization drivers. Not long for this world.
Definition in file drive2_cmt.f.
Function/Subroutine Documentation
subroutine izero8 (integer*8, dimension(1) a, n)
Definition at line 26 of file drive2_cmt.f.
References i, and n.
subroutine nek_cmt_init ()
Definition at line 4 of file drive2_cmt.f.
References exitt(), and setup_cmt_commo().
subroutine setup_cmt_param ()
Definition at line 34 of file drive2_cmt.f.
References mixtperf_cp_cvr(), mixtperf_g_cpr(), mixtperf_ho_cptuvw(), and mixtperf_r_m().