KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/drive2.f File Reference
drive2.f File Reference
Functions/Subroutines
subroutine initdim
subroutine initdat
subroutine comment
subroutine setvar
subroutine echopar
subroutine gengeom (igeom)
subroutine files
subroutine settime
subroutine geneig (igeom)
subroutine fluid (igeom)
subroutine heat (igeom)
subroutine heat_cvode (igeom)
subroutine meshv (igeom)
subroutine rescont (ind)
subroutine rstartc (ind)
subroutine time00
subroutine runstat
subroutine pprint_all (s, n_in, io)
subroutine opcount (ICALL)
subroutine dofcnt
subroutine vol_flow
subroutine compute_vol_soln (vxc, vyc, vzc, prc)
subroutine plan2_vol (vxc, vyc, vzc, prc)
subroutine plan3_vol (vxc, vyc, vzc, prc)
subroutine plan4_vol (vxc, vyc, vzc, prc)
subroutine a_dmp
subroutine outrio (v, n, io)
subroutine reset_prop
Function/Subroutine Documentation
a_dmp()
subroutine a_dmp ()
Definition at line 1941 of file drive2.f.
References axhelm(), lelt, ly1, lz1, outrio(), rone(), and rzero().
comment()
subroutine comment ()
Definition at line 91 of file drive2.f.
References dnekclock().
compute_vol_soln()
subroutine compute_vol_soln (real, dimension(lx1,ly1,lz1,lelv) vxc, real, dimension(lx1,ly1,lz1,lelv) vyc, real, dimension(lx1,ly1,lz1,lelv) vzc, real, dimension(lx2,ly2,lz2,lelv) prc)
Definition at line 1678 of file drive2.f.
References glmax(), glmin(), glsc2(), ly1, lz1, plan3_vol(), and plan4_vol().
dofcnt()
subroutine dofcnt ()
Definition at line 1528 of file drive2.f.
References glsc2(), glsum(), ly1, and lz1.
echopar()
subroutine echopar ()
Definition at line 282 of file drive2.f.
References blank(), exitt(), and ltrunc().
files()
subroutine files ()
Definition at line 440 of file drive2.f.
References blank(), chcopy(), indx1(), and ltrunc().
fluid()
subroutine fluid (igeom)
Definition at line 685 of file drive2.f.
References chkptol(), plan1(), plan3(), plan4(), plan5(), printdiverr(), settolv(), unorm(), and vol_flow().
geneig()
subroutine geneig (igeom)
Definition at line 633 of file drive2.f.
References eigenv(), and esteig().
gengeom()
subroutine gengeom (igeom)
Definition at line 362 of file drive2.f.
References col2(), dssum(), einit(), gencoor(), geom1(), geom2(), lagmass(), lelt, setdef(), setinvm(), sfastax(), updcoor(), updmsys(), and volume().
heat()
subroutine heat (igeom)
Definition at line 759 of file drive2.f.
References cdscal(), settolt(), and unorm().
heat_cvode()
subroutine heat_cvode (igeom)
Definition at line 802 of file drive2.f.
References cdscal_cvode().
initdat()
subroutine initdat ()
Definition at line 35 of file drive2.f.
References blank(), lelt, ly1, lz1, and rzero().
initdim()
subroutine initdim ()
Definition at line 2 of file drive2.f.
References lelt, ly1, and lz1.
meshv()
subroutine meshv (igeom)
Definition at line 827 of file drive2.f.
References elasolv(), mvbdry(), and updmsys().
opcount()
subroutine opcount (ICALL)
Definition at line 1470 of file drive2.f.
References chswapr(), crecv(), csend(), drcopy(), gop(), iswap(), and sort().
outrio()
subroutine outrio (real, dimension(1) v, n, io)
Definition at line 1964 of file drive2.f.
plan2_vol()
subroutine plan2_vol (real, dimension(lx1,ly1,lz1,lelv) vxc, real, dimension(lx1,ly1,lz1,lelv) vyc, real, dimension(lx1,ly1,lz1,lelv) vzc, real, dimension(lx2,ly2,lz2,lelv) prc)
Definition at line 1740 of file drive2.f.
References add2col2(), cdtp(), ctolspl(), hmholtz(), ly1, lz1, opchsgn(), opgrad(), ophinv(), ortho(), rone(), rzero(), and sethlm().
plan3_vol()
subroutine plan3_vol (real, dimension(lx1,ly1,lz1,lelv) vxc, real, dimension(lx1,ly1,lz1,lelv) vyc, real, dimension(lx1,ly1,lz1,lelv) vzc, real, dimension(lx2,ly2,lz2,lelv) prc)
Definition at line 1799 of file drive2.f.
References chsign(), cmult(), cmult2(), copy(), esolver(), invers2(), ly1, lz1, opadd2(), opbinv(), opdiv(), opgradt(), ophinv(), ortho(), rzero(), sethlm(), and ssnormd().
plan4_vol()
subroutine plan4_vol (real, dimension(lx1,ly1,lz1,lelv) vxc, real, dimension(lx1,ly1,lz1,lelv) vyc, real, dimension(lx1,ly1,lz1,lelv) vzc, real, dimension(lx1,ly1,lz1,lelv) prc)
Definition at line 1879 of file drive2.f.
References add2col2(), cdtp(), col2(), ctolspl(), hmholtz(), invers2(), ly1, lz1, opchsgn(), opgrad(), ophinv(), ortho(), redo_split_vis(), rzero(), sethlm(), and split_vis().
pprint_all()
subroutine pprint_all (character*1, dimension(n_in) s, n_in, io)
Definition at line 1429 of file drive2.f.
References blank(), crecv(), csend(), ltrunc(), and nekgsync().
rescont()
subroutine rescont (ind)
Definition at line 849 of file drive2.f.
References rstartc().
reset_prop()
subroutine reset_prop ()
Definition at line 1978 of file drive2.f.
References cfill(), lelt, ly1, and lz1.
rstartc()
subroutine rstartc (ind)
Definition at line 869 of file drive2.f.
References exitt(), geom1(), geom2(), ly1, lz1, setinvm(), updmsys(), and volume().
runstat()
subroutine runstat ()
Definition at line 1123 of file drive2.f.
References blank(), dnekclock(), gop(), nek_comm_getstat, and pprint_all().
settime()
subroutine settime ()
Definition at line 567 of file drive2.f.
References rzero(), setabbd(), setbd(), setdt(), and setordbd().
setvar()
subroutine setvar ()
Definition at line 147 of file drive2.f.
References exitt(), rzero(), and setchar().
time00()
subroutine time00 ()
Definition at line 1046 of file drive2.f.
vol_flow()
subroutine vol_flow ()
Definition at line 1565 of file drive2.f.
References add2s2(), compute_vol_soln(), copy(), exitt(), glsc2(), ly1, lz1, and scale().