KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/cmt/drive1_cmt.f File Reference
drive1_cmt.f File Reference
high-level driver for CMT-nek
Functions/Subroutines
subroutine cmt_nek_advance
subroutine compute_rhs_and_dt
Compute right-hand-side of the semidiscrete conservation law Store it in res1.
subroutine set_tstep_coef
Compute coefficients for Runge-Kutta stages [TVDRK]}.
subroutine cmt_flow_ics
subroutine print_cmt_timers
subroutine init_cmt_timers
Detailed Description
high-level driver for CMT-nek
Definition in file drive1_cmt.f.
Function/Subroutine Documentation
subroutine cmt_flow_ics ()
Definition at line 279 of file drive1_cmt.f.
References copy(), lelt, n, and rzero().
subroutine cmt_nek_advance ()
Definition at line 12 of file drive1_cmt.f.
References cmt_flow_ics(), cmt_ics(), compute_grid_h(), compute_mesh_h(), compute_primitive_vars(), compute_rhs_and_dt(), compute_transport_props(), copy(), dnekclock(), i, init_cmt_timers(), lelt, ly1, lz1, mass_balance(), n, and out_fld_nek().
subroutine compute_rhs_and_dt ()
Compute right-hand-side of the semidiscrete conservation law Store it in res1.
Restrict via to get primitive and conserved variables on interior faces and neighbor faces ; store in CMTSURFLX
res1+= on face points
res1+=
res1+= for each equation (inner), one element at a time (outer)
res1+=
Definition at line 111 of file drive1_cmt.f.
References cmtusrf(), compute_forcing(), compute_gradients(), compute_grid_h(), compute_mesh_h(), compute_primitive_vars(), compute_transport_props(), convective_cmt(), fluxes_full_field(), igtu_cmt(), igu_cmt(), imqqtu(), imqqtu_dirichlet(), lelt, ly1, lz1, rzero(), set_alias_rx(), set_dealias_face(), set_tstep_coef(), setdtcmt(), surface_integral_full(), and viscous_cmt().
subroutine init_cmt_timers ()
Definition at line 321 of file drive1_cmt.f.
subroutine print_cmt_timers ()
Definition at line 303 of file drive1_cmt.f.
References glsum().
subroutine set_tstep_coef ()
Compute coefficients for Runge-Kutta stages [TVDRK]}.
Definition at line 260 of file drive1_cmt.f.