KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/drive.f File Reference
drive.f File Reference
Functions/Subroutines
program nekton
Function/Subroutine Documentation
program nekton ()
Definition at line 1 of file drive.f.
References exitt(), nek_end(), nek_init(), and nek_solve().