KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/cmt/driver3_cmt.f File Reference
driver3_cmt.f File Reference
Functions/Subroutines
subroutine compute_primitive_vars
subroutine tdstate (e, energy)
subroutine cmtasgn (ix, iy, iz, e)
subroutine cmt_ics
subroutine cmtuic
Function/Subroutine Documentation
subroutine cmt_ics ()
Definition at line 128 of file driver3_cmt.f.
References cmtuic(), glmax(), glmin(), lelt, and rzero().
subroutine cmtasgn (ix, iy, iz, integer e)
Definition at line 99 of file driver3_cmt.f.
subroutine cmtuic ()
Definition at line 209 of file driver3_cmt.f.
References cmtasgn(), i, and nekasgn().
subroutine compute_primitive_vars ()
Definition at line 2 of file driver3_cmt.f.
References cmult(), copy(), invcol2(), invcol3(), ly1, lz1, set_convect_cons(), sub3(), tdstate(), vdot2(), and vdot3().
subroutine tdstate (integer e, real, dimension(nx1,ny1,nz1) energy)
Definition at line 66 of file driver3_cmt.f.
References cmtasgn(), i, and nekasgn().