KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/drive1.f File Reference
drive1.f File Reference
Functions/Subroutines
subroutine nek_init (intracomm)
subroutine nek_solve
subroutine nek_advance
subroutine nek_end
subroutine nek__multi_advance (kstep, msteps)
Function/Subroutine Documentation
nek__multi_advance()
subroutine nek__multi_advance (kstep, msteps)
Definition at line 340 of file drive1.f.
References bcopy(), chk_outflow(), nek_advance(), and userchk_set_xfer().
nek_advance()
subroutine nek_advance ()
Definition at line 232 of file drive1.f.
References cfl_check(), comment(), fluid(), fluidp(), geneig(), gengeom(), heat(), heat_cvode(), heatp(), induct(), ly1, lz1, meshv(), multimesh_create(), nekgsync(), q_filter(), qthermal(), rzero(), setprop(), setsolv(), settime(), setup_convect(), and userchk_set_xfer().
nek_end()
subroutine nek_end ()
Definition at line 325 of file drive1.f.
References in_situ_end(), and runstat().
nek_init()
subroutine nek_init (intracomm)
Definition at line 3 of file drive1.f.
References bcmask(), bcopy(), chk_outflow(), comment(), cv_init(), cv_setsize(), dg_setup(), dnekclock(), dnekclock_sync(), dofcnt(), estrat(), files(), g25d_init(), geneig(), gengeom(), genwz(), geom_reset(), get_session_info(), gfdm_init(), in_situ_init(), initdat(), initdim(), lelt, opcount(), readat(), set_overlap(), setics(), setlog(), setprop(), setup_mesh_dssum(), setup_topo(), setvar(), sstest(), time00(), userchk_set_xfer(), and vrdsmsh().
nek_solve()
subroutine nek_solve ()
Definition at line 165 of file drive1.f.
References check_ioinfo(), comment(), dnekgflops(), in_situ_check(), nek__multi_advance(), nek_comm_settings, nek_comm_startstat, nekgsync(), prepost(), and set_outfld().