KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/3rd_party/dsygv.f File Reference
dsygv.f File Reference
Functions/Subroutines
subroutine dsygv (ITYPE, JOBZ, UPLO, N, A, LDA, B, LDB, W, WORK, LWORK, INFO)
subroutine dsytd2 (UPLO, N, A, LDA, D, E, TAU, INFO)
subroutine dsytrd (UPLO, N, A, LDA, D, E, TAU, WORK, LWORK, INFO)
integer function ieeeck (ISPEC, ZERO, ONE)
integer function ilaenv (ISPEC, NAME, OPTS, N1, N2, N3, N4)
logical function xlsame (CA, CB)
subroutine xxerbla (SRNAME, INFO)
subroutine dlae2 (A, B, C, RT1, RT2)
subroutine dlaev2 (A, B, C, RT1, RT2, CS1, SN1)
double precision function dlamch (CMACH)
subroutine dlamc1 (BETA, T, RND, IEEE1)
subroutine dlamc2 (BETA, T, RND, EPS, EMIN, RMIN, EMAX, RMAX)
double precision function dlamc3 (A, B)
subroutine dlamc4 (EMIN, START, BASE)
subroutine dlamc5 (BETA, P, EMIN, IEEE, EMAX, RMAX)
double precision function dlanst (NORM, N, D, E)
double precision function dlansy (NORM, UPLO, N, A, LDA, WORK)
double precision function dlapy2 (X, Y)
subroutine dlarfb (SIDE, TRANS, DIRECT, STOREV, M, N, K, V, LDV, T, LDT, C, LDC, WORK, LDWORK)
subroutine dlarf (SIDE, M, N, V, INCV, TAU, C, LDC, WORK)
subroutine dlarfg (N, ALPHA, X, INCX, TAU)
subroutine dlarft (DIRECT, STOREV, N, K, V, LDV, TAU, T, LDT)
subroutine dlartg (F, G, CS, SN, R)
subroutine dlascl (TYPE, KL, KU, CFROM, CTO, M, N, A, LDA, INFO)
subroutine dlaset (UPLO, M, N, ALPHA, BETA, A, LDA)
subroutine dlasr (SIDE, PIVOT, DIRECT, M, N, C, S, A, LDA)
subroutine dlasrt (ID, N, D, INFO)
subroutine dlassq (N, X, INCX, SCALE, SUMSQ)
subroutine dlatrd (UPLO, N, NB, A, LDA, E, TAU, W, LDW)
subroutine dorg2l (M, N, K, A, LDA, TAU, WORK, INFO)
subroutine dorg2r (M, N, K, A, LDA, TAU, WORK, INFO)
subroutine dorgql (M, N, K, A, LDA, TAU, WORK, LWORK, INFO)
subroutine dorgqr (M, N, K, A, LDA, TAU, WORK, LWORK, INFO)
subroutine dorgtr (UPLO, N, A, LDA, TAU, WORK, LWORK, INFO)
subroutine dpotf2 (UPLO, N, A, LDA, INFO)
subroutine dpotrf (UPLO, N, A, LDA, INFO)
subroutine dsteqr (COMPZ, N, D, E, Z, LDZ, WORK, INFO)
subroutine dsterf (N, D, E, INFO)
subroutine dsyev (JOBZ, UPLO, N, A, LDA, W, WORK, LWORK, INFO)
subroutine dsygs2 (ITYPE, UPLO, N, A, LDA, B, LDB, INFO)
subroutine dsygst (ITYPE, UPLO, N, A, LDA, B, LDB, INFO)
Function/Subroutine Documentation
subroutine dlae2 (double precision A, double precision B, double precision C, double precision RT1, double precision RT2)
Definition at line 1601 of file dsygv.f.
subroutine dlaev2 (double precision A, double precision B, double precision C, double precision RT1, double precision RT2, double precision CS1, double precision SN1)
Definition at line 1725 of file dsygv.f.
subroutine dlamc1 (integer BETA, integer T, logical RND, logical IEEE1)
Definition at line 2025 of file dsygv.f.
subroutine dlamc2 (integer BETA, integer T, logical RND, double precision EPS, integer EMIN, double precision RMIN, integer EMAX, double precision RMAX)
Definition at line 2212 of file dsygv.f.
References dlamc1(), dlamc4(), and dlamc5().
double precision function dlamc3 (double precision A, double precision B)
Definition at line 2471 of file dsygv.f.
subroutine dlamc4 (integer EMIN, double precision START, integer BASE)
Definition at line 2509 of file dsygv.f.
subroutine dlamc5 (integer BETA, integer P, integer EMIN, logical IEEE, integer EMAX, double precision RMAX)
Definition at line 2593 of file dsygv.f.
double precision function dlamch (character CMACH)
Definition at line 1895 of file dsygv.f.
References dlamc2().
double precision function dlanst (character NORM, integer N, double precision, dimension(*) D, double precision, dimension(*) E)
Definition at line 2752 of file dsygv.f.
References dlassq().
double precision function dlansy (character NORM, character UPLO, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) WORK)
Definition at line 2877 of file dsygv.f.
References dlassq().
double precision function dlapy2 (double precision X, double precision Y)
Definition at line 3051 of file dsygv.f.
subroutine dlarf (character SIDE, integer M, integer N, double precision, dimension(*) V, integer INCV, double precision TAU, double precision, dimension(ldc, *) C, integer LDC, double precision, dimension(*) WORK)
Definition at line 3693 of file dsygv.f.
References dgemv(), and dger().
subroutine dlarfb (character SIDE, character TRANS, character DIRECT, character STOREV, integer M, integer N, integer K, double precision, dimension(ldv, *) V, integer LDV, double precision, dimension(ldt, *) T, integer LDT, double precision, dimension(ldc, *) C, integer LDC, double precision, dimension(ldwork, *) WORK, integer LDWORK)
Definition at line 3106 of file dsygv.f.
References dcopy(), dgemm(), and dtrmm().
subroutine dlarfg (integer N, double precision ALPHA, double precision, dimension(*) X, integer INCX, double precision TAU)
Definition at line 3809 of file dsygv.f.
References dscal().
subroutine dlarft (character DIRECT, character STOREV, integer N, integer K, double precision, dimension(ldv, *) V, integer LDV, double precision, dimension(*) TAU, double precision, dimension(ldt, *) T, integer LDT)
Definition at line 3947 of file dsygv.f.
References dgemv(), and dtrmv().
subroutine dlartg (double precision F, double precision G, double precision CS, double precision SN, double precision R)
Definition at line 4165 of file dsygv.f.
subroutine dlascl (character TYPE, integer KL, integer KU, double precision CFROM, double precision CTO, integer M, integer N, double precision, dimension(lda, *) A, integer LDA, integer INFO)
Definition at line 4308 of file dsygv.f.
References xerbla().
subroutine dlaset (character UPLO, integer M, integer N, double precision ALPHA, double precision BETA, double precision, dimension(lda, *) A, integer LDA)
Definition at line 4576 of file dsygv.f.
subroutine dlasr (character SIDE, character PIVOT, character DIRECT, integer M, integer N, double precision, dimension(*) C, double precision, dimension(*) S, double precision, dimension(lda, *) A, integer LDA)
Definition at line 4691 of file dsygv.f.
References xerbla().
subroutine dlasrt (character ID, integer N, double precision, dimension(*) D, integer INFO)
Definition at line 5016 of file dsygv.f.
References i, and xerbla().
subroutine dlassq (integer N, double precision, dimension(*) X, integer INCX, double precision SCALE, double precision SUMSQ)
Definition at line 5260 of file dsygv.f.
subroutine dlatrd (character UPLO, integer N, integer NB, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) E, double precision, dimension(*) TAU, double precision, dimension(ldw, *) W, integer LDW)
Definition at line 5349 of file dsygv.f.
References daxpy(), dgemv(), dlarfg(), dscal(), and dsymv().
subroutine dorg2l (integer M, integer N, integer K, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) TAU, double precision, dimension(*) WORK, integer INFO)
Definition at line 5608 of file dsygv.f.
References dlarf(), dscal(), and xerbla().
subroutine dorg2r (integer M, integer N, integer K, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) TAU, double precision, dimension(*) WORK, integer INFO)
Definition at line 5736 of file dsygv.f.
References dlarf(), dscal(), and xerbla().
subroutine dorgql (integer M, integer N, integer K, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) TAU, double precision, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 5866 of file dsygv.f.
References dlarfb(), dlarft(), dorg2l(), nx, and xerbla().
subroutine dorgqr (integer M, integer N, integer K, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) TAU, double precision, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 6080 of file dsygv.f.
References dlarfb(), dlarft(), dorg2r(), nx, and xerbla().
subroutine dorgtr (character UPLO, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) TAU, double precision, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 6297 of file dsygv.f.
References dorgql(), dorgqr(), and xerbla().
subroutine dpotf2 (character UPLO, integer N, double precision, dimension(lda, *) A, integer LDA, integer INFO)
Definition at line 6481 of file dsygv.f.
References dgemv(), dscal(), and xerbla().
subroutine dpotrf (character UPLO, integer N, double precision, dimension(lda, *) A, integer LDA, integer INFO)
Definition at line 6649 of file dsygv.f.
References dgemm(), dpotf2(), dsyrk(), dtrsm(), and xerbla().
subroutine dsteqr (character COMPZ, integer N, double precision, dimension(*) D, double precision, dimension(*) E, double precision, dimension(ldz, *) Z, integer LDZ, double precision, dimension(*) WORK, integer INFO)
Definition at line 6833 of file dsygv.f.
References dlae2(), dlaev2(), dlartg(), dlascl(), dlaset(), dlasr(), dlasrt(), dswap(), and xerbla().
subroutine dsterf (integer N, double precision, dimension(*) D, double precision, dimension(*) E, integer INFO)
Definition at line 7334 of file dsygv.f.
References dlae2(), dlascl(), dlasrt(), and xerbla().
subroutine dsyev (character JOBZ, character UPLO, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) W, double precision, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 7699 of file dsygv.f.
References dlascl(), dorgtr(), dscal(), dsteqr(), dsterf(), dsytrd(), and xerbla().
subroutine dsygs2 (integer ITYPE, character UPLO, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(ldb, *) B, integer LDB, integer INFO)
Definition at line 7912 of file dsygv.f.
References daxpy(), dscal(), dsyr2(), dtrmv(), dtrsv(), and xerbla().
subroutine dsygst (integer ITYPE, character UPLO, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(ldb, *) B, integer LDB, integer INFO)
Definition at line 8124 of file dsygv.f.
References dsygs2(), dsymm(), dsyr2k(), dtrmm(), dtrsm(), and xerbla().
subroutine dsygv (integer ITYPE, character JOBZ, character UPLO, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(ldb, *) B, integer LDB, double precision, dimension(*) W, double precision, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 3 of file dsygv.f.
References dpotrf(), dsyev(), dsygst(), dtrmm(), dtrsm(), and xerbla().
subroutine dsytd2 (character UPLO, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) D, double precision, dimension(*) E, double precision, dimension(*) TAU, integer INFO)
Definition at line 229 of file dsygv.f.
References daxpy(), dlarfg(), dsymv(), dsyr2(), and xerbla().
subroutine dsytrd (character UPLO, integer N, double precision, dimension(lda, *) A, integer LDA, double precision, dimension(*) D, double precision, dimension(*) E, double precision, dimension(*) TAU, double precision, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 478 of file dsygv.f.
References dlatrd(), dsyr2k(), dsytd2(), nx, and xerbla().
integer function ieeeck (integer ISPEC, real ZERO, real ONE)
Definition at line 773 of file dsygv.f.
integer function ilaenv (integer ISPEC, character*(*) NAME, character*(*) OPTS, integer N1, integer N2, integer N3, integer N4)
Definition at line 922 of file dsygv.f.
logical function xlsame (character CA, character CB)
Definition at line 1468 of file dsygv.f.
subroutine xxerbla (character*6 SRNAME, integer INFO)
Definition at line 1555 of file dsygv.f.