KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/edit.f File Reference
edit.f File Reference
Functions/Subroutines
subroutine mesh_edit
subroutine dom_spline
subroutine dom_draw_bdry (npdom, xdom)
subroutine dom_mv_vtx (ein, nin, ddom, xdom, npdom)
subroutine dom_def (ifdomdef)
subroutine dom_el_inside (ein, nin, ddom, xdom, npdom)
function dom_dist (dlist, xdom, npdom, x, y)
function dline (x, x1, x2, x0)
subroutine dom_delete (ein, nin, ddom, xdom, npdom)
Function/Subroutine Documentation
function dline (real, dimension(2) x, real, dimension(2) x1, real, dimension(2) x2, real, dimension(2) x0)
Definition at line 309 of file edit.f.
References sub3().
subroutine dom_def (logical ifdomdef)
Definition at line 122 of file edit.f.
References dom_el_inside(), draw(), mouse2(), move(), prs(), res(), and xscr().
subroutine dom_delete (integer, dimension(nin) ein, nin, real, dimension(npdom-1,nin) ddom, real, dimension(2,npdom) xdom, npdom)
Definition at line 334 of file edit.f.
References copyel(), i, izero(), and prsis().
function dom_dist (real, dimension(npdom-1) dlist, real, dimension(2,npdom) xdom, npdom, x, y)
Definition at line 272 of file edit.f.
References dline(), and j.
subroutine dom_draw_bdry (npdom, real, dimension(2,npdom) xdom)
Definition at line 64 of file edit.f.
References draw(), move(), and prsrr().
subroutine dom_el_inside (integer, dimension(1) ein, nin, real, dimension(npdom-1,1) ddom, real, dimension(2,npdom) xdom, npdom)
Definition at line 181 of file edit.f.
References dom_dist(), i, and prs().
subroutine dom_mv_vtx (integer, dimension(nin) ein, nin, real, dimension(npdom-1,nin) ddom, real, dimension(2,npdom) xdom, npdom)
Definition at line 76 of file edit.f.
References i, mouse2(), prs(), prsi(), and rmin().
subroutine dom_spline ()
Definition at line 60 of file edit.f.
subroutine mesh_edit ()
Definition at line 3 of file edit.f.
References dom_def(), dom_delete(), dom_draw_bdry(), dom_mv_vtx(), dom_spline(), drawel(), drgrid(), menu(), prs(), and refresh().