KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/eigsolv.f File Reference
eigsolv.f File Reference
Functions/Subroutines
subroutine esteig
subroutine eigenv
subroutine alpham1 (ALPHA, MASK, MULT, H1, H2, ISD)
subroutine gammam1 (GAMMA, MASK, MULT, H1, H2, ISD)
subroutine alpham2 (ALPHA, H1, H2, H2INV, INLOC)
subroutine gammam2 (GAMMA, H1, H2, H2INV, INLOC)
subroutine startx1 (X1, Y1, MASK, MULT, NEL)
subroutine startx2 (X2, Y2)
Function/Subroutine Documentation
alpham1()
subroutine alpham1 (ALPHA, real, dimension (lx1,ly1,lz1,1) MASK, real, dimension (lx1,ly1,lz1,1) MULT, real, dimension (lx1,ly1,lz1,1) H1, real, dimension (lx1,ly1,lz1,1) H2, ISD)
Definition at line 204 of file eigsolv.f.
References axhelm(), cmult(), col2(), col3(), copy(), dssum(), glsc3(), hmholtz(), lelt, ly1, lz1, and startx1().
alpham2()
subroutine alpham2 (ALPHA, real, dimension (lx1,ly1,lz1,1) H1, real, dimension (lx1,ly1,lz1,1) H2, real, dimension(lx1,ly1,lz1,1) H2INV, INLOC)
Definition at line 310 of file eigsolv.f.
References cdabdtp(), cmult(), col2(), col3(), glsc2(), startx2(), and uzawa().
eigenv()
subroutine eigenv ()
Definition at line 91 of file eigsolv.f.
References alpham1(), alpham2(), gammam1(), gammam2(), gammasf(), invers2(), lelt, ly1, lz1, rone(), rzero(), and sethlm().
esteig()
subroutine esteig ()
Definition at line 9 of file eigsolv.f.
References glmax(), glmin(), ly1, and lz1.
gammam1()
subroutine gammam1 (GAMMA, real, dimension (lx1,ly1,lz1,1) MASK, real, dimension (lx1,ly1,lz1,1) MULT, real, dimension (lx1,ly1,lz1,1) H1, real, dimension (lx1,ly1,lz1,1) H2, ISD)
Definition at line 259 of file eigsolv.f.
References axhelm(), cmult(), col2(), col3(), dssum(), glsc3(), lelt, ly1, lz1, and startx1().
gammam2()
subroutine gammam2 (GAMMA, real, dimension (lx1,ly1,lz1,1) H1, real, dimension (lx1,ly1,lz1,1) H2, real, dimension (lx1,ly1,lz1,1) H2INV, INLOC)
Definition at line 355 of file eigsolv.f.
References cdabdtp(), cmult(), glsc2(), invcol3(), and startx2().
startx1()
subroutine startx1 (real, dimension (lx1,ly1,lz1,1) X1, real, dimension (lx1,ly1,lz1,1) Y1, real, dimension (lx1,ly1,lz1,1) MASK, real, dimension (lx1,ly1,lz1,1) MULT, NEL)
Definition at line 398 of file eigsolv.f.
References add2s2(), cmult(), col2(), col3(), copy(), dssum(), glamax(), glsc3(), ly1, lz1, and rand_fld_h1().
startx2()
subroutine startx2 (real, dimension (lx2,ly2,lz2,lelv) X2, real, dimension (lx2,ly2,lz2,lelv) Y2)
Definition at line 430 of file eigsolv.f.
References cmult(), col3(), copy(), glsc2(), and ortho().