KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/cmt/eqnsolver_cmt.f File Reference
eqnsolver_cmt.f File Reference
Functions/Subroutines
subroutine viscous_cmt (e, eq)
subroutine igtu_cmt (qminus, ummcu, hface)
subroutine convective_cmt (e, eq)
subroutine evaluate_dealiased_conv_h (e, eq)
subroutine evaluate_aliased_conv_h (e, eq)
subroutine flux_div_integral_dealiased (e, eq)
subroutine flux_div_integral_aliased (e, eq)
subroutine compute_forcing (e, eq_num)
subroutine cmtusrf (e)
Function/Subroutine Documentation
subroutine cmtusrf (integer e)
Definition at line 442 of file eqnsolver_cmt.f.
References cmtasgn(), i, j, n, nekasgn(), rzero(), and userf().
subroutine compute_forcing (integer e, integer eq_num)
Definition at line 383 of file eqnsolver_cmt.f.
References col2(), copy(), gradl_rst(), i, j, rzero(), sub2(), and subcol3().
subroutine convective_cmt (integer e, integer eq)
Definition at line 122 of file eqnsolver_cmt.f.
References copy(), evaluate_aliased_conv_h(), evaluate_dealiased_conv_h(), flux_div_integral_aliased(), flux_div_integral_dealiased(), n, and rzero().
subroutine evaluate_aliased_conv_h (integer e, integer eq)
Definition at line 213 of file eqnsolver_cmt.f.
References add2col2(), col2(), copy(), exitt(), j, and n.
subroutine evaluate_dealiased_conv_h (integer e, integer eq)
Definition at line 147 of file eqnsolver_cmt.f.
References add2col2(), col2(), copy(), exitt(), intp_rstd(), j, and n.
subroutine flux_div_integral_aliased (integer e, integer eq)
Definition at line 327 of file eqnsolver_cmt.f.
References add2col2(), copy(), get_dgll_ptr(), j, local_grad2_t(), local_grad3_t(), rzero(), and sub2().
subroutine flux_div_integral_dealiased (integer e, integer eq)
Definition at line 266 of file eqnsolver_cmt.f.
References add2col2(), get_dgl_ptr(), intp_rstd(), j, local_grad2_t(), local_grad3_t(), rzero(), and sub2().
subroutine igtu_cmt (real, dimension(nx1*nz1,2*ndim,nelt,*) qminus, real, dimension(nx1*nz1*2*ndim,nelt,toteq) ummcu, real, dimension(nx1*nz1*2*ndim*nelt,toteq,3) hface)
Definition at line 44 of file eqnsolver_cmt.f.
References add2(), add_face2full_cmt(), agradu_sfc(), cmult(), col2(), col3(), gradm1_t(), j, lelt, ly1, lz1, and rzero().
subroutine viscous_cmt (integer e, integer eq)
Definition at line 2 of file eqnsolver_cmt.f.
References diffh2graduf(), fluxj_vol(), half_iku_cmt(), lelt, and lz1.