KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/error.c File Reference
error.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include "const.h"
#include "error.h"
Functions
void error_msg_fatal_ (char *msg)
void error_msg_fatal (char *msg,...)
void error_msg_warning (char *msg,...)
Function Documentation
void error_msg_fatal (char * msg, ...)
Definition at line 66 of file error.c.
References comm_terminate(), my_id, and printf().
void error_msg_fatal_ (char * msg)
Definition at line 50 of file error.c.
References error_msg_fatal().
void error_msg_warning (char * msg, ...)
Definition at line 140 of file error.c.
References my_id, and printf().