KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/exo2nek/exo2nek.f File Reference
exo2nek.f File Reference
Functions/Subroutines
program exo2nek
subroutine read_input_name
subroutine exodus_read
subroutine convert
subroutine gen_re2
subroutine open_re2
subroutine write_xyz
subroutine write_curve
subroutine write_bc
subroutine close_re2
subroutine gen_rea_midside_e (e)
subroutine map2reg (ur, n, u, nel)
subroutine map2reg_2di_e (uf, n, uc, m)
subroutine map2reg_3di_e (uf, n, uc, m)
subroutine gen_int_gz (j, jt, g, n, z, m)
subroutine blank (A, N)
subroutine exitt
subroutine copy (a, b, n)
subroutine chcopy (a, b, n)
subroutine icopy (a, b, n)
subroutine fd_weights_full (xx, x, n, m, c)
subroutine transpose (a, lda, b, ldb)
function ltrunc (string, l)
subroutine zuni (z, np)
subroutine rzero (a, n)
Function/Subroutine Documentation
subroutine blank (character*1, dimension(1) A, N)
Definition at line 674 of file exo2nek.f.
References i, and n.
subroutine chcopy (character*1, dimension(1) a, character*1, dimension(1) b, n)
Definition at line 702 of file exo2nek.f.
References i, and n.
subroutine close_re2 ()
Definition at line 506 of file exo2nek.f.
References byte_close.
subroutine convert ()
Definition at line 223 of file exo2nek.f.
References blank(), i, and rzero().
subroutine copy (real, dimension(1) a, real, dimension(1) b, n)
Definition at line 692 of file exo2nek.f.
References i, and n.
subroutine exitt ()
Definition at line 686 of file exo2nek.f.
program exo2nek ()
Definition at line 1 of file exo2nek.f.
References convert(), exodus_read(), gen_re2(), and read_input_name().
subroutine exodus_read ()
Definition at line 37 of file exo2nek.f.
References i, and j.
subroutine fd_weights_full (xx, real, dimension(0:n) x, n, m, real, dimension(0:n,0:m) c)
Definition at line 718 of file exo2nek.f.
References i, j, and n.
subroutine gen_int_gz (real, dimension(n,m) j, real, dimension(m,n) jt, real, dimension(n) g, n, real, dimension(m) z, m)
Definition at line 653 of file exo2nek.f.
References fd_weights_full(), i, n, and transpose().
subroutine gen_re2 ()
Definition at line 313 of file exo2nek.f.
References close_re2(), open_re2(), write_bc(), write_curve(), and write_xyz().
subroutine gen_rea_midside_e (integer e)
Definition at line 513 of file exo2nek.f.
References chcopy(), copy(), i, j, and map2reg().
subroutine icopy (integer, dimension(1) a, integer, dimension(1) b, n)
Definition at line 710 of file exo2nek.f.
References i, and n.
function ltrunc (character*1, dimension(l) string, l)
Definition at line 787 of file exo2nek.f.
References i, and ltrunc().
subroutine map2reg (real, dimension(1) ur, n, real, dimension(3*3*3,1) u, nel)
Definition at line 569 of file exo2nek.f.
References map2reg_2di_e(), map2reg_3di_e(), and n.
subroutine map2reg_2di_e (real, dimension(n,n) uf, n, real, dimension(m,m) uc, m)
Definition at line 590 of file exo2nek.f.
References gen_int_gz(), j, mxmf2(), n, zuni(), and zwgll().
subroutine map2reg_3di_e (real, dimension(n,n,n) uf, n, real, dimension(m,m,m) uc, m)
Definition at line 616 of file exo2nek.f.
References gen_int_gz(), j, mxmf2(), n, zuni(), and zwgll().
subroutine open_re2 ()
Definition at line 329 of file exo2nek.f.
References blank(), byte_open, byte_write, chcopy(), and ltrunc().
subroutine read_input_name ()
Definition at line 13 of file exo2nek.f.
References blank(), chcopy(), and ltrunc().
subroutine rzero (real, dimension(1) a, n)
Definition at line 818 of file exo2nek.f.
References i, and n.
subroutine transpose (real, dimension(lda,1) a, lda, real, dimension(ldb,1) b, ldb)
Definition at line 775 of file exo2nek.f.
References i, and j.
subroutine write_bc ()
Definition at line 461 of file exo2nek.f.
References blank(), byte_write, chcopy(), and copy().
subroutine write_curve ()
Definition at line 418 of file exo2nek.f.
References blank(), byte_write, chcopy(), copy(), and gen_rea_midside_e().
subroutine write_xyz ()
Definition at line 356 of file exo2nek.f.
References byte_write, copy(), i, and j.
subroutine zuni (real, dimension(1) z, np)
Definition at line 802 of file exo2nek.f.
References i.