KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/cmt/face.f File Reference
face.f File Reference
Functions/Subroutines
subroutine iface_vert_int8cmt (nx, ny, nz, fa, va, jz0, jz1, nel)
subroutine setup_cmt_gs (dg_hndl, nx, ny, nz, nel, melg, vertex, gnv, gnf)
subroutine setup_cmt_commo
subroutine cmt_set_fc_ptr (nel, nx, ny, nz, nface, iface)
subroutine full2face_cmt (nel, nx, ny, nz, iface, faces, vols)
subroutine add_face2full_cmt (nel, nx, ny, nz, iface, vols, faces)
Function/Subroutine Documentation
subroutine add_face2full_cmt (integer nel, integer nx, integer ny, integer nz, integer, dimension(nx*nz*2*ldim,*) iface, real, dimension (nx,ny,nz ,nel) vols, real, dimension(nx*nz ,2*ldim,*) faces)
Definition at line 188 of file face.f.
References n.
subroutine cmt_set_fc_ptr (integer nel, integer nx, integer ny, integer nz, integer nface, integer, dimension(nx*nz*2*ldim,*) iface)
Definition at line 108 of file face.f.
References dsset(), and i.
subroutine full2face_cmt (integer nel, integer nx, integer ny, integer nz, integer, dimension(nx*nz*2*ldim,1) iface, real, dimension(nx*nz ,2*ldim,nel) faces, real, dimension (nx,ny,nz ,1) vols)
Definition at line 159 of file face.f.
References n.
subroutine iface_vert_int8cmt (nx, ny, nz, integer*8, dimension(nx*nz,2*ndim,nel) fa, integer*8, dimension(0:nx+1,0:ny+1,jz0:jz1,nel) va, jz0, jz1, nel)
Definition at line 3 of file face.f.
References facind(), i, izero8(), n, nx, and nz.
subroutine setup_cmt_commo ()
Definition at line 89 of file face.f.
References cmt_set_fc_ptr(), lelt, ly1, lz1, and setup_cmt_gs().
subroutine setup_cmt_gs (integer dg_hndl, nx, ny, nz, nel, melg, integer, dimension(*) vertex, integer*8, dimension(*) gnv, integer*8, dimension(*) gnf)
Definition at line 58 of file face.f.
References gs_setup, iface_vert_int8cmt(), nx, nz, and set_vert().