KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/fasts.f File Reference
fasts.f File Reference
Functions/Subroutines
subroutine local_solves_fdm (u, v)
subroutine fastdm1 (r, df, sr, ss, st, w1, w2)
subroutine tensr3 (v, nv, u, nu, A, Bt, Ct, w)
subroutine s_face_to_int (x, c)
subroutine dface_ext (x)
subroutine dface_add1si (x, c)
subroutine init_weight_op
subroutine do_weight_op (x)
Function/Subroutine Documentation
dface_add1si()
subroutine dface_add1si (real, dimension(lx1,ly1,lz1,1) x, c)
Definition at line 261 of file fasts.f.
References ly1, and lz1.
dface_ext()
subroutine dface_ext (real, dimension(lx1,ly1,lz1,1) x)
Definition at line 213 of file fasts.f.
References ly1, and lz1.
do_weight_op()
subroutine do_weight_op (real, dimension(0:lx1-1,0:ly1-1,0:lz1-1,1) x)
Definition at line 405 of file fasts.f.
fastdm1()
subroutine fastdm1 (real, dimension(1) r, real, dimension(1) df, real, dimension(lxx,2) sr, real, dimension(lxx,2) ss, real, dimension(lxx,2) st, real, dimension(1) w1, real, dimension(1) w2)
Definition at line 97 of file fasts.f.
References col2(), ly1, lz1, and tensr3().
init_weight_op()
subroutine init_weight_op ()
Definition at line 311 of file fasts.f.
References dface_add1si(), dface_ext(), dssum(), ly1, lz1, rzero(), and s_face_to_int().
local_solves_fdm()
subroutine local_solves_fdm (real, dimension(lx2,ly2,lz2,lelv) u, real, dimension(lx2,ly2,lz2,lelv) v)
Definition at line 3 of file fasts.f.
References dface_add1si(), dface_ext(), dnekclock(), do_weight_op(), dssum(), fastdm1(), ly1, lz1, rzero(), and s_face_to_int().
s_face_to_int()
subroutine s_face_to_int (real, dimension(lx1,ly1,lz1,1) x, c)
Definition at line 165 of file fasts.f.
References ly1, and lz1.
tensr3()
subroutine tensr3 (real, dimension(nv,nv,nv) v, nv, real, dimension(nu,nu,nu) u, nu, real, dimension(1) A, real, dimension(1) Bt, real, dimension(1) Ct, real, dimension(1) w)
Definition at line 126 of file fasts.f.
References exitt(), and mxm().