KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/cmt/filters_cmt.f File Reference
filters_cmt.f File Reference
Functions/Subroutines
subroutine filter_cmtvar (continuous)
subroutine filtercv (f, nx, nz, w1, w2, ft, if3d, dmax)
subroutine userfilt_bubble (intv, zpts, nx, nio)
subroutine userfilt (intv, zpts, nx, nio)
Function/Subroutine Documentation
subroutine filter_cmtvar (logical continuous)
Definition at line 3 of file filters_cmt.f.
References filtercv(), lz1, userfilt(), and userfilt_bubble().
subroutine filtercv (real, dimension(nx,nx) f, nx, nz, real, dimension(1) w1, real, dimension(1) w2, real, dimension(nx,nx) ft, logical if3d, dmax)
Definition at line 60 of file filters_cmt.f.
References copy(), dmax, i, j, lelt, ly1, lz1, mxm(), nx, nz, sub3(), transpose(), and vlamax().
subroutine userfilt (real, dimension(nx,nx) intv, real, dimension(nx) zpts, nx, nio)
Definition at line 191 of file filters_cmt.f.
References copy(), exitt(), gaujordf(), ident(), j, legendre_poly(), mxm(), n, nx, and transpose().
subroutine userfilt_bubble (real, dimension(nx,nx) intv, real, dimension(nx) zpts, nx, nio)
Definition at line 124 of file filters_cmt.f.
References copy(), exitt(), gaujordf(), ident(), j, legendre_poly(), mxm(), n, nx, and transpose().