KTH framework for Nek5000 toolboxes; testing version: Nek5000/jl/findpts_el_2_test2.c File Reference
findpts_el_2_test2.c File Reference
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <float.h>
#include <string.h>
#include "c99.h"
#include "types.h"
#include "name.h"
#include "fail.h"
#include "mem.h"
#include "tensor.h"
#include "poly.h"
#include "lob_bnd.h"
#include "obbox.h"
#include "findpts_el.h"
#include "rand_elt_test.h"
#include "rdtsc.h"
Macros
#define USE_HW_COUNTER 0
#define REPEAT 10000
#define NR 7
#define TNR 8
#define NS 8
#define TNS 9
#define TNTOT (TNR*TNS)
#define MR (4*NR)
#define MS (4*NS)
#define NPT 256
#define TOL 1024*DBL_EPSILON
Functions
int main ()
Macro Definition Documentation
#define MR (4*NR)
Definition at line 33 of file findpts_el_2_test2.c.
#define MS (4*NS)
Definition at line 34 of file findpts_el_2_test2.c.
#define NPT 256
Definition at line 39 of file findpts_el_2_test2.c.
#define NR 7
Definition at line 28 of file findpts_el_2_test2.c.
#define NS 8
Definition at line 30 of file findpts_el_2_test2.c.
#define REPEAT 10000
Definition at line 26 of file findpts_el_2_test2.c.
#define TNR 8
Definition at line 29 of file findpts_el_2_test2.c.
#define TNS 9
Definition at line 31 of file findpts_el_2_test2.c.
#define TNTOT (TNR*TNS)
Definition at line 32 of file findpts_el_2_test2.c.
#define TOL 1024*DBL_EPSILON
Definition at line 42 of file findpts_el_2_test2.c.
#define USE_HW_COUNTER 0
Definition at line 20 of file findpts_el_2_test2.c.
Function Documentation
int main ()
Definition at line 52 of file findpts_el_2_test2.c.
References findpts_el_pt_2::dist2, findpts_el_2, findpts_el_free_2, findpts_el_setup_2, findpts_el_pt_2::flags, i, i0, findpts_el_data_2::lag, findpts_el_data_2::lag_data, lobatto_nodes, n, NPT, NR, printf(), findpts_el_pt_2::r, rand_elt_2(), REPEAT, TNR, TNS, TNTOT, x, findpts_el_pt_2::x, and y().