KTH framework for Nek5000 toolboxes; testing version: Nek5000/jl/ext/findpts_local_ext.c File Reference
findpts_local_ext.c File Reference
#include <stddef.h>
#include <stdlib.h>
#include <float.h>
#include <math.h>
#include <string.h>
#include "../c99.h"
#include "../name.h"
#include "../fail.h"
#include "../mem.h"
#include "../types.h"
#include "../poly.h"
#include "../obbox.h"
#include "../findpts_el.h"
#include "../findpts_local.h"
Data Structures
struct findpts_local_data
Macros
#define findpts_local_setup PREFIXED_NAME(findpts_local_setup)
#define findpts_local_free PREFIXED_NAME(findpts_local_free)
#define findpts_local PREFIXED_NAME(findpts_local)
#define findpts_local_eval PREFIXED_NAME(findpts_local_eval)
Functions
struct findpts_local_data * findpts_local_setup (const unsigned dim, const double *const elx[], const unsigned n[], const uint nel, const unsigned m[], const double bbox_tol, const uint max_hash_size, const uint npt_max, const double newt_tol)
void findpts_local_free (struct findpts_local_data *p)
void findpts_local (uint *const code_base, const unsigned code_stride, uint *const el_base, const unsigned el_stride, double *const r_base, const unsigned r_stride, double *const dist2_base, const unsigned dist2_stride, const double *const x_base[], const unsigned x_stride[], const uint npt, struct findpts_local_data *const p)
void findpts_local_eval (double *const out_base, const unsigned out_stride, const uint *const el_base, const unsigned el_stride, const double *const r_base, const unsigned r_stride, const uint npt, const double *const in, struct findpts_local_data *const p)
Macro Definition Documentation
#define findpts_local PREFIXED_NAME(findpts_local)
Definition at line 18 of file findpts_local_ext.c.
#define findpts_local_eval PREFIXED_NAME(findpts_local_eval)
Definition at line 19 of file findpts_local_ext.c.
#define findpts_local_free PREFIXED_NAME(findpts_local_free)
Definition at line 17 of file findpts_local_ext.c.
#define findpts_local_setup PREFIXED_NAME(findpts_local_setup)
Definition at line 16 of file findpts_local_ext.c.
Function Documentation
void findpts_local (uint *const code_base, const unsigned code_stride, uint *const el_base, const unsigned el_stride, double *const r_base, const unsigned r_stride, double *const dist2_base, const unsigned dist2_stride, const double *const x_base[], const unsigned x_stride[], const uint npt, struct findpts_local_data *const p)
Definition at line 58 of file findpts_local_ext.c.
References findpts_local_data::buf, findpts_local_data::d2, findpts_local_data::d3, findpts_local_data::dim, findpts_local_2(), findpts_local_3(), and findpts_local_data::fld.
void findpts_local_eval (double *const out_base, const unsigned out_stride, const uint *const el_base, const unsigned el_stride, const double *const r_base, const unsigned r_stride, const uint npt, const double *const in, struct findpts_local_data *const p)
Definition at line 80 of file findpts_local_ext.c.
References findpts_local_data::d2, findpts_local_data::d3, findpts_local_data::dim, findpts_local_eval_2(), findpts_local_eval_3(), and findpts_local_data::fld.
void findpts_local_free (struct findpts_local_data * p)
Definition at line 50 of file findpts_local_ext.c.
References findpts_local_data::buf, buffer_free, findpts_local_data::d2, findpts_local_data::d3, findpts_local_data::dim, findpts_local_free_2(), findpts_local_free_3(), and findpts_local_data::fld.
struct findpts_local_data* findpts_local_setup (const unsigned dim, const double *const elx[], const unsigned n[], const uint nel, const unsigned m[], const double bbox_tol, const uint max_hash_size, const uint npt_max, const double newt_tol)
Definition at line 30 of file findpts_local_ext.c.
References findpts_local_data::buf, findpts_local_data::d2, findpts_local_data::d3, findpts_local_data::dim, findpts_local_setup_2(), findpts_local_setup_3(), findpts_local_data::fld, and tmalloc.