KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/g3d.f File Reference
g3d.f File Reference
Functions/Subroutines
subroutine drisog
subroutine evline (UV, UVP, HIK, N1, N1D, NPT, NSKIP)
subroutine hilight (IE, icolr)
subroutine hilight2 (IE, icolr)
Function/Subroutine Documentation
subroutine drisog ()
Definition at line 18 of file g3d.f.
References color, evline(), hlegn(), i, nx, nz, penw(), rescal(), and vdraw3a().
subroutine evline (real, dimension(npt) UV, real, dimension(1) UVP, real, dimension(n1d,npt) HIK, N1, N1D, NPT, NSKIP)
Definition at line 199 of file g3d.f.
References i.
subroutine hilight (IE, icolr)
Definition at line 228 of file g3d.f.
References color, evline(), hlegn(), nx, nz, penw(), prs(), and vdraw3a().
subroutine hilight2 (IE, icolr)
Definition at line 387 of file g3d.f.
References color, evline(), hlegn(), nx, nz, penw(), and vdraw3a().