KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/genbox.f File Reference
genbox.f File Reference
Functions/Subroutines
subroutine genbox
subroutine gen_gtp_vertex (vertex, ncrnr)
subroutine getbox (x, y, z, nfld)
subroutine mapbox (melx, mely, melz)
subroutine makebox (x, y, z, nfld)
subroutine geti1 (i, iend, io)
subroutine geti2 (i1, i2, iend, io)
subroutine geti3 (i1, i2, i3, iend, io)
subroutine getr2 (r1, r2, iend, io)
subroutine getr3 (r1, r2, r3, iend, io)
subroutine getrv (r, n, iend, io)
subroutine getiv (r, n, iend, io)
subroutine getcv0 (c, m, n, iend, io)
subroutine getcv (c, m, n, iend, io)
subroutine gets (c, n, iend, io)
subroutine get_multi_seg (nelxyz, x, y, z, m, if3d)
subroutine geometric_x (x, n, x0, x1, gain)
subroutine get_xyz_distribution (x, nelx)
subroutine scannocom (iend, infile)
function ilsum (x, n)
subroutine jjnt (x, n)
subroutine bcpbox (nfld)
subroutine outbox_mesh
Function/Subroutine Documentation
subroutine bcpbox (nfld)
Definition at line 898 of file genbox.f.
References bcast().
subroutine gen_gtp_vertex (integer, dimension(2**ldim,1) vertex, ncrnr)
Definition at line 68 of file genbox.f.
References get_exyz(), and jjnt().
subroutine genbox ()
Definition at line 3 of file genbox.f.
References bcpbox(), blank(), chcopy(), exitt(), getbox(), geti1(), getrv(), gets(), iabs, ltrunc(), makebox(), and mapbox().
subroutine geometric_x (real, dimension(0:n) x, n, x0, x1, gain)
Definition at line 792 of file genbox.f.
References n, and scale().
subroutine get_multi_seg (integer, dimension(3) nelxyz, real, dimension(0:m) x, real, dimension(0:m) y, real, dimension(0:m) z, m, logical if3d)
Definition at line 729 of file genbox.f.
References exitt(), geometric_x(), geti1(), getiv(), getrv(), and ilsum().
subroutine get_xyz_distribution (real, dimension(0:2) x, nelx)
Definition at line 811 of file genbox.f.
References cadd(), cmult(), and scale().
subroutine getbox (real, dimension(0:1) x, real, dimension(0:1) y, real, dimension(0:1) z, nfld)
Definition at line 142 of file genbox.f.
References exitt(), get_multi_seg(), getcv(), geti2(), geti3(), getr2(), getr3(), getrv(), gets(), and scale().
subroutine getcv (character*1, dimension(m,n) c, m, n, iend, io)
Definition at line 683 of file genbox.f.
References n, and scannocom().
subroutine getcv0 (character*1, dimension(m,n) c, m, n, iend, io)
Definition at line 654 of file genbox.f.
References n, and scannocom().
subroutine geti1 (i, iend, io)
Definition at line 534 of file genbox.f.
References scannocom().
subroutine geti2 (i1, i2, iend, io)
Definition at line 546 of file genbox.f.
References scannocom().
subroutine geti3 (i1, i2, i3, iend, io)
Definition at line 558 of file genbox.f.
References scannocom().
subroutine getiv (integer, dimension(n) r, n, iend, io)
Definition at line 624 of file genbox.f.
References ifill(), n, and scannocom().
subroutine getr2 (r1, r2, iend, io)
Definition at line 570 of file genbox.f.
References scannocom().
subroutine getr3 (r1, r2, r3, iend, io)
Definition at line 582 of file genbox.f.
References scannocom().
subroutine getrv (real, dimension(n) r, n, iend, io)
Definition at line 594 of file genbox.f.
References cfill(), n, and scannocom().
subroutine gets (character*1, dimension(n) c, n, iend, io)
Definition at line 715 of file genbox.f.
References n, and scannocom().
function ilsum (integer, dimension(1) x, n)
Definition at line 881 of file genbox.f.
References n.
subroutine jjnt (integer, dimension(1) x, n)
Definition at line 890 of file genbox.f.
References n.
subroutine makebox (real, dimension(0:1) x, real, dimension(0:1) y, real, dimension(0:1) z, nfld)
Definition at line 372 of file genbox.f.
References copy(), lelt, mod1(), and rzero().
subroutine mapbox (melx, mely, melz)
Definition at line 341 of file genbox.f.
References exitt(), lelt, and mapelpr().
subroutine outbox_mesh ()
Definition at line 928 of file genbox.f.
subroutine scannocom (iend, infile)
Definition at line 843 of file genbox.f.
References blank(), indx1(), and ltrunc().