KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/genmap/genmap.f File Reference
genmap.f File Reference
Functions/Subroutines
program genmap
subroutine makemesh (cell, nelv, nelt, irnk, dx, cbc, bc, ndim, wk)
subroutine linearmsh (cell, nelv, nelt, ndim)
subroutine exitti (name, ie)
subroutine exitt (ie)
subroutine cscan_dxyz (dx, nelt, nelv, ndim, ifbinary, ifbswap)
subroutine set_d2 (dx, nvrt, nel, ndim)
subroutine cscan_bcs (cbc, bc, nelv, nelt, ndim)
subroutine rd_bc (cbc, bc, nel, ndim, ifield, io)
subroutine blank (s, n)
function ltrunc (s, n)
integer function indx1 (s1, s2, l2)
subroutine cscan (sout, key, nk)
subroutine readwrite (sout, key, nk)
subroutine readwrite2 (sout, key1, nk1, key2, nk2)
integer function log2 (k)
function iglmin (a, n)
function ivlmax (a, n)
function iglmax (a, n)
function glmax (a, n)
function glmin (a, n)
subroutine icopy (x, y, n)
subroutine cmult2 (x, y, c, n)
subroutine copy (x, y, n)
subroutine copy8 (x, y, n)
subroutine izero (x, n)
subroutine cfill (x, c, n)
subroutine rint (x, n)
subroutine jjnt (x, n)
subroutine ifill (x, c, n)
subroutine icadd (x, c, n)
subroutine cadd (x, c, n)
subroutine cmult (x, c, n)
subroutine chcopy (x, y, n)
subroutine getreafile (prompt, ifbinary, io, ierr)
subroutine isort (a, ind, n)
subroutine iswap_ip (x, p, n)
subroutine iswapt_ip (x, p, n)
subroutine sort (a, p, n)
subroutine csr_sort_colj (ia, ja, n, ind)
subroutine out_csrmati (ia, ja, n, name9)
subroutine iranku (a, rank, n, p)
subroutine rec_bisect (elist, pmap, order, mo, cell, nv, nel, ndim, ia, da, w1, w2, w3)
subroutine fill_order (order, mo, cell, nv, nel)
subroutine count_sep (count, order, nsep, elist, cell, nv, n1, n2)
subroutine bipart_sort (n1, n2, pmap, order, mo, elist, nel, cell, nv, p, c, w1, w2)
subroutine part_clean (order, nsep, elist, cell, nv, n1, n2, count, wk)
subroutine ident_sep (order, mo, elist, cell, nv, n1, n2)
subroutine outmatti (u, m, n, name6, nid, ic)
subroutine outmati (u, m, n, name6, nid, ic)
subroutine outmat (u, m, n, name6, nid)
subroutine out_mapfile (pmap, nel, cell, nv, nrnk, noutflow)
subroutine dmp_mapfile (pmap, nel, depth, cell, nv, nrnk, npts, noutflow)
subroutine ituple_sort (a, lda, n, key, nkey, ind, aa)
subroutine tuple_sort (a, lda, n, key, nkey, ind, aa)
logical function iftuple_ialtb (a, b, key, nkey)
logical function iftuple_altb (a, b, key, nkey)
logical function iftuple_ianeb (a, b, key, nkey)
logical function iftuple_iaeqb (a, b, key, nkey)
subroutine tuple_swapt_ip (x, m, n, p, t1, t2)
subroutine set_outflow (no, order, mo, cell, nv, nel, nrnk, cbc, nfc, ic, i0, i1, jc)
subroutine assign_order (cell, nv, nel, order)
subroutine periodic_vtx (cell, nv, nel, irnk, dx, ndim, cbc, bc, nfc, iper, jmin)
subroutine find_connctd_pairs (jmin, nvf, e, f, je, jf, cell, nv, dx, ndim, nel)
subroutine out_order (order, mo, elist, cell, nv, n1, n2)
subroutine out_a (a)
subroutine set_a (a)
subroutine outaij (ia, ja, n, name6, key)
function ipush (stack, val)
function ipop (nout, stack)
logical function is_connected (jactive, n0, ia, ja, n, jstack)
subroutine spec_bis (pmap, f, ia, ja, va, n, d, u, r, p2, w, rr, ev, m, ndim)
subroutine sbisect (pmap, f, p, w, n)
subroutine glanczos (rr, n, diag, upper, niter, f, ia, ja, va, r, p, w)
subroutine ax (y, x, ia, ja, va, n)
subroutine ortho1 (p, n)
subroutine lanczos2 (v1, rr, n, ev, d, u, m)
subroutine calcvec (diag, upper, d, e, n, imin, imax, z)
subroutine ident (a, n)
subroutine rzero (a, n)
function glsc2 (x, y, n)
subroutine add2s2 (a, b, c, n)
subroutine add2s1 (a, b, c, n)
subroutine reverse_p (p, n)
subroutine unique_vertex2 (cell, dx, ndim, nel, q, ind, ninseg, ifseg, wk)
subroutine out_geofile (dx, ndim, nv, nel, pmap, io)
subroutine self_chk (cell, nv, nel, flag)
subroutine mult_chk (dx, ndim, nv, nel, cell, nrnk)
subroutine rd_bc_bin (cbc, bc, nelv, nelt, ifbswap)
subroutine buf_to_bc (cbl, bl, buf, nelt)
subroutine buf_to_xyz (buf, xc, yc, zc, e, ifbswap, ndim, wdsizi)
subroutine outcheck (buf, nwds)
subroutine open_bin_file (ifbswap, nelgt, ndim, nelgv, wdsizi)
logical function if_byte_swap_test (bytetest)
subroutine copyi4 (a, b, n)
subroutine copy4 (a, b, n)
subroutine copy4r (a, b, n)
subroutine copy48r (a, b, n)
integer function indx132 (S1, S2, L2)
subroutine cell2v (i0, i1, ic, nic, jc, njc, cell, nv, ncell, type, wk)
subroutine cell2v1 (ic, i0, i1, jc, njc, cell, nv, ncell, type, wk)
subroutine greedy (pmap, cell, nv, nelv, nelt, ndim, ic, jc, ip, ep, ne, pb)
subroutine build_proc_el (ip, ep, ne, pmap, pmax, nel)
function indxi (list, item, n)
subroutine c2c (ic2c, jc2c, vc2c, cell, nv, nel, iv2c, jv2c, nn, wk)
subroutine c2cs (ic2c, jc2c, vc2c, iv2c, jv2c, k0, k1, cell, nv, ie0, ie1, nee, ic2t, jc2t)
subroutine outbc (cbc, bc, nel, ndim, name6)
subroutine breadth_first_fill (p, np)
subroutine cell_plot (dx, cell, nv, ndim, nel, io_in)
subroutine spec_bis_conn (pmap, n1, n2, c, elist, nv, nel, cell, ndim, w1, w2)
subroutine sort_count (pmap, elist, n1, n2, nel, w1, wk)
subroutine assign_gllnid (gllnid, iunsort, nelgt, nelgv, np)
subroutine maptest (pmap, nelgv, nelgt, name10, gllnid, wk)
subroutine outcell (cell, dx, n, ndim)
subroutine face_chk (face_conn, cell, nv, ncell, nic, njc, v2cind, v2c, w3)
subroutine find_v2 (v2, e1, e2, cell, nel, nv, ind, jc)
subroutine fix_geom (cell, e1, v1, e2, v2, ind, jc, nel, nv)
function mod1 (i, n)
Function/Subroutine Documentation
subroutine add2s1 (real, dimension(1) a, real, dimension(1) b, c, n)
Definition at line 2859 of file genmap.f.
References i, and n.
subroutine add2s2 (real, dimension(1) a, real, dimension(1) b, c, n)
Definition at line 2851 of file genmap.f.
References i, and n.
subroutine assign_gllnid (integer, dimension(1) gllnid, integer, dimension(1) iunsort, integer nelgt, nelgv, integer np)
Definition at line 4382 of file genmap.f.
References exitti(), isort(), iswapt_ip(), ivlmax(), and log2().
subroutine assign_order (integer, dimension(nv,nel) cell, nv, nel, integer, dimension(1) order)
Definition at line 2020 of file genmap.f.
References i, and j.
subroutine ax (real, dimension(1) y, real, dimension(1) x, integer, dimension(0:1) ia, integer, dimension(1) ja, integer, dimension(1) va, n)
Definition at line 2647 of file genmap.f.
References i, j, and n.
subroutine bipart_sort (n1, n2, integer, dimension(nel) pmap, integer, dimension(1) order, mo, integer, dimension(nel) elist, nel, integer, dimension(nv,1) cell, nv, p, integer, dimension(nv,1) c, integer, dimension(1) w1, integer, dimension(1) w2)
Definition at line 1337 of file genmap.f.
References count_sep(), i, icadd(), icopy(), ident_sep(), ifill(), iglmax(), isort(), iswap_ip(), npts, self_chk(), and spec_bis_conn().
subroutine blank (character*1, dimension(1) s, n)
Definition at line 624 of file genmap.f.
References i, and n.
subroutine breadth_first_fill (integer, dimension(0:1) p, np)
Definition at line 3933 of file genmap.f.
References i, and log2().
subroutine buf_to_bc (character*3, dimension(6,nelt) cbl, real*8, dimension(5,6,nelt) bl, integer, dimension(30) buf, nelt)
Definition at line 3245 of file genmap.f.
References chcopy(), copy(), copy48r(), and copyi4().
subroutine buf_to_xyz (integer, dimension(0:49) buf, real, dimension(8) xc, real, dimension(8) yc, real, dimension(8) zc, integer e, logical ifbswap, ndim, integer wdsizi)
Definition at line 3279 of file genmap.f.
References byte_reverse, byte_reverse8, copy(), copy4r(), copyi4(), and exitti().
subroutine build_proc_el (integer, dimension(0:1) ip, integer, dimension(1) ep, integer, dimension(0:1) ne, integer, dimension(1) pmap, integer pmax, nel)
Definition at line 3719 of file genmap.f.
References izero().
subroutine c2c (integer, dimension(1) ic2c, integer, dimension(1) jc2c, integer, dimension(1) vc2c, integer, dimension(nv,nel) cell, nv, nel, integer, dimension(1) iv2c, integer, dimension(1) jv2c, nn, integer, dimension(1) wk)
Definition at line 3763 of file genmap.f.
References c2cs(), cell2v(), exitt(), i0, indxi(), j, and outmati().
subroutine c2cs (integer, dimension(1) ic2c, integer, dimension(1) jc2c, integer, dimension(1) vc2c, integer, dimension(k0:k1) iv2c, integer, dimension(1) jv2c, k0, k1, integer, dimension(nv,1) cell, nv, ie0, ie1, integer, dimension(ie0:ie1) nee, integer, dimension(ie0:ie1+1) ic2t, integer, dimension(1) jc2t)
Definition at line 3834 of file genmap.f.
References i0, indxi(), and izero().
subroutine cadd (real, dimension(1) x, c, n)
Definition at line 864 of file genmap.f.
References i, and n.
subroutine calcvec (real, dimension(n) diag, real, dimension(n) upper, real, dimension(n) d, real, dimension(n) e, n, imin, imax, real, dimension(n,n) z)
Definition at line 2708 of file genmap.f.
References cmult(), copy(), dmax, dmin, glsc2(), i, ident(), n, and scale().
subroutine cell2v (i0, i1, integer, dimension(1) ic, nic, integer, dimension(1) jc, njc, integer, dimension(nv,ncell) cell, nv, ncell, integer type, integer, dimension(1) wk)
Definition at line 3478 of file genmap.f.
References cell2v1(), i0, iglmax(), and iglmin().
subroutine cell2v1 (integer, dimension(i0:i1) ic, i0, i1, integer, dimension(1) jc, njc, integer, dimension(nv,ncell) cell, nv, ncell, integer type, integer, dimension(i0:i1) wk)
Definition at line 3508 of file genmap.f.
References i, i0, izero(), and j.
subroutine cell_plot (real, dimension(0:ndim,1) dx, integer, dimension(nv,nel) cell, nv, ndim, nel, io_in)
Definition at line 3957 of file genmap.f.
References j.
subroutine cfill (real, dimension(1) x, c, n)
Definition at line 824 of file genmap.f.
References i, and n.
subroutine chcopy (character*1, dimension(1) x, character*1, dimension(1) y, n)
Definition at line 880 of file genmap.f.
References i, and n.
subroutine cmult (real, dimension(1) x, c, n)
Definition at line 872 of file genmap.f.
References i, and n.
subroutine cmult2 (real, dimension(1) x, real, dimension(1) y, c, n)
Definition at line 792 of file genmap.f.
References i, and n.
subroutine copy (real, dimension(1) x, real, dimension(1) y, n)
Definition at line 800 of file genmap.f.
References i, and n.
subroutine copy4 (real*4, dimension(1) a, real*4, dimension(1) b, n)
Definition at line 3432 of file genmap.f.
References i, and n.
subroutine copy48r (real*8, dimension(1) a, real*4, dimension(1) b, n)
Definition at line 3450 of file genmap.f.
References i, and n.
subroutine copy4r (real, dimension(1) a, real*4, dimension(1) b, n)
Definition at line 3441 of file genmap.f.
References i, and n.
subroutine copy8 (real*8, dimension(1) x, real*8, dimension(1) y, n)
Definition at line 808 of file genmap.f.
References i, and n.
subroutine copyi4 (integer, dimension(1) a, real, dimension(1) b, n)
Definition at line 3424 of file genmap.f.
References i, and n.
subroutine count_sep (integer, dimension(1) count, integer, dimension(1) order, nsep, integer, dimension(1) elist, integer, dimension(nv,1) cell, nv, n1, n2)
Definition at line 1277 of file genmap.f.
References i, izero(), and j.
subroutine cscan (character*80 sout, character*80 key, nk)
Definition at line 662 of file genmap.f.
References blank(), chcopy(), i, and indx1().
subroutine cscan_bcs (character*3, dimension(6,nelt) cbc, real*8, dimension (5,6,nelt) bc, nelv, nelt, ndim)
Definition at line 517 of file genmap.f.
References cscan(), indx1(), and rd_bc().
subroutine cscan_dxyz (real, dimension(1) dx, nelt, nelv, ndim, logical ifbinary, logical ifbswap)
Definition at line 370 of file genmap.f.
References buf_to_xyz(), byte_read, cscan(), exitt(), open_bin_file(), and set_d2().
subroutine csr_sort_colj (integer, dimension(0:1) ia, integer, dimension(1) ja, n, ind)
Definition at line 1114 of file genmap.f.
References i, isort(), and n.
subroutine dmp_mapfile (integer, dimension(nel) pmap, nel, integer depth, integer, dimension(nv,nel) cell, nv, nrnk, npts, noutflow)
Definition at line 1663 of file genmap.f.
References chcopy(), ltrunc(), and npts.
subroutine exitt (ie)
Definition at line 362 of file genmap.f.
subroutine exitti (character*40 name, ie)
Definition at line 353 of file genmap.f.
subroutine face_chk (logical face_conn, integer, dimension(nv,ncell) cell, nv, ncell, nic, njc, integer, dimension(1) v2cind, integer, dimension(1) v2c, integer, dimension(200) w3)
Definition at line 4507 of file genmap.f.
References cell2v(), find_v2(), fix_geom(), i, i0, isort(), and j.
subroutine fill_order (integer, dimension(1) order, mo, integer, dimension(nv,nel) cell, nv, nel)
Definition at line 1246 of file genmap.f.
References i.
subroutine find_connctd_pairs (integer, dimension(1) jmin, nvf, integer e, integer f, je, jf, integer, dimension(nv,1) cell, nv, real, dimension(0:ndim,nv,1) dx, ndim, nel)
Definition at line 2157 of file genmap.f.
References copy(), exitt(), i, icopy(), j, and outmat().
subroutine find_v2 (integer v2, integer e1, integer e2, integer, dimension(nv,nel) cell, nel, nv, integer, dimension(1) ind, integer, dimension(1) jc)
Definition at line 4606 of file genmap.f.
References j.
subroutine fix_geom (integer, dimension(nv,nel) cell, integer e1, integer v1, integer e2, integer v2, integer, dimension(1) ind, integer, dimension(1) jc, nel, nv)
Definition at line 4643 of file genmap.f.
References j.
program genmap ()
Definition at line 72 of file genmap.f.
References assign_order(), exit(), face_chk(), fill_order(), i, iranku(), isort(), iswap_ip(), izero(), makemesh(), mult_chk(), npts, out_mapfile(), periodic_vtx(), rec_bisect(), reverse_p(), and self_chk().
subroutine getreafile (character*1, dimension(1) prompt, logical ifbinary, io, ierr)
Definition at line 888 of file genmap.f.
References blank(), chcopy(), indx1(), and ltrunc().
subroutine glanczos (real, dimension(n,1) rr, n, real, dimension(1) diag, real, dimension(1) upper, niter, real, dimension(1) f, integer, dimension(1) ia, integer, dimension(1) ja, integer, dimension(1) va, real, dimension(1) r, real, dimension(1) p, real, dimension(1) w)
Definition at line 2573 of file genmap.f.
References add2s1(), add2s2(), alpha, ax(), beta, cmult2(), copy(), glsc2(), n, ortho1(), and rzero().
function glmax (real, dimension(1) a, n)
Definition at line 764 of file genmap.f.
References glmax(), i, and n.
function glmin (real, dimension(1) a, n)
Definition at line 774 of file genmap.f.
References glmin(), i, and n.
function glsc2 (real, dimension(1) x, real, dimension(1) y, n)
Definition at line 2840 of file genmap.f.
References glsc2(), i, and n.
subroutine greedy (integer, dimension(1) pmap, integer, dimension (nv,1) cell, nv, nelv, nelt, ndim, integer, dimension(1) ic, integer, dimension(1) jc, integer, dimension(0:1) ip, integer, dimension(1) ep, integer, dimension(0:nelv) ne, integer, dimension(1) pb)
Definition at line 3567 of file genmap.f.
References breadth_first_fill(), build_proc_el(), exitt(), i, iglmax(), iglmin(), izero(), and j.
subroutine icadd (integer, dimension(1) x, integer c, n)
Definition at line 856 of file genmap.f.
References i, and n.
subroutine icopy (integer, dimension(1) x, integer, dimension(1) y, n)
Definition at line 784 of file genmap.f.
References i, and n.
subroutine ident (real, dimension(n,n) a, n)
Definition at line 2823 of file genmap.f.
References i, n, and rzero().
subroutine ident_sep (integer, dimension(1) order, mo, integer, dimension(1) elist, integer, dimension(nv,1) cell, nv, n1, n2)
Definition at line 1491 of file genmap.f.
References i, j, and mod1().
logical function if_byte_swap_test (real*4 bytetest)
Definition at line 3401 of file genmap.f.
References byte_reverse, exitti(), and if_byte_swap_test().
subroutine ifill (integer, dimension(1) x, integer c, n)
Definition at line 848 of file genmap.f.
References i, and n.
logical function iftuple_altb (real, dimension(1) a, real, dimension(1) b, integer, dimension(nkey) key, nkey)
Definition at line 1839 of file genmap.f.
References i, and iftuple_altb().
logical function iftuple_iaeqb (integer, dimension(1) a, integer, dimension(1) b, integer, dimension(nkey) key, nkey)
Definition at line 1872 of file genmap.f.
References i.
logical function iftuple_ialtb (integer, dimension(1) a, integer, dimension(1) b, integer, dimension(nkey) key, nkey)
Definition at line 1821 of file genmap.f.
References i, and iftuple_ialtb().
logical function iftuple_ianeb (integer, dimension(1) a, integer, dimension(1) b, integer, dimension(nkey) key, nkey)
Definition at line 1857 of file genmap.f.
References i, and iftuple_ianeb().
function iglmax (integer, dimension(1) a, n)
Definition at line 754 of file genmap.f.
References i, iglmax(), and n.
function iglmin (integer, dimension(1) a, n)
Definition at line 734 of file genmap.f.
References i, iglmin(), and n.
integer function indx1 (character*80 s1, character*80 s2, l2)
Definition at line 644 of file genmap.f.
References i, and indx1().
integer function indx132 (character*132 S1, character*132 S2, L2)
Definition at line 3460 of file genmap.f.
References i.
function indxi (integer, dimension(1) list, item, n)
Definition at line 3749 of file genmap.f.
References j, and n.
function ipop (nout, integer, dimension(0:1) stack)
Definition at line 2418 of file genmap.f.
References n.
function ipush (integer, dimension(0:1) stack, integer val)
Definition at line 2400 of file genmap.f.
References n.
subroutine iranku (integer, dimension(1) a, integer rank, n, integer, dimension(1) p)
Definition at line 1148 of file genmap.f.
References ia, isort(), iswapt_ip(), and n.
logical function is_connected (integer, dimension(n) jactive, n0, integer, dimension(0:n) ia, integer, dimension(1) ja, n, integer, dimension(0:n) jstack)
Definition at line 2436 of file genmap.f.
References ev, i, ipop(), ipush(), izero(), j, n, and rr.
subroutine isort (integer, dimension(1) a, integer, dimension(1) ind, n)
Definition at line 935 of file genmap.f.
References i, j, and n.
subroutine iswap_ip (integer, dimension(1) x, integer, dimension(1) p, n)
Definition at line 988 of file genmap.f.
References exitt(), j, and n.
subroutine iswapt_ip (integer, dimension(1) x, integer, dimension(1) p, n)
Definition at line 1024 of file genmap.f.
References exitt(), j, and n.
subroutine ituple_sort (integer, dimension(lda,n) a, lda, n, integer, dimension(nkey) key, nkey, integer, dimension(1) ind, integer, dimension(lda) aa)
Definition at line 1699 of file genmap.f.
References i, icopy(), j, and n.
function ivlmax (integer, dimension(1) a, n)
Definition at line 744 of file genmap.f.
References i, ivlmax(), and n.
subroutine izero (integer, dimension(1) x, n)
Definition at line 816 of file genmap.f.
References i, and n.
subroutine jjnt (integer, dimension(1) x, n)
Definition at line 840 of file genmap.f.
References i, and n.
subroutine lanczos2 (real, dimension(1) v1, real, dimension(n,1) rr, n, real, dimension(m,1) ev, real, dimension(1) d, real, dimension(1) u, m)
Definition at line 2681 of file genmap.f.
References add2s2(), calcvec(), j, n, and rzero().
subroutine linearmsh (integer, dimension(2,1) cell, nelv, nelt, ndim)
Definition at line 331 of file genmap.f.
integer function log2 (k)
Definition at line 725 of file genmap.f.
References log2().
function ltrunc (character*1, dimension(1) s, n)
Definition at line 632 of file genmap.f.
References j, ltrunc(), and n.
subroutine makemesh (integer, dimension(1) cell, nelv, nelt, irnk, real, dimension (1) dx, character*3, dimension (6,1) cbc, real*8, dimension (5,6,1) bc, ndim, real, dimension (1) wk)
Definition at line 207 of file genmap.f.
References byte_close, byte_read, byte_reverse, byte_reverse8, chcopy(), copy8(), cscan_bcs(), cscan_dxyz(), exitti(), getreafile(), iranku(), linearmsh(), npts, rd_bc_bin(), self_chk(), and unique_vertex2().
subroutine maptest (integer, dimension(1) pmap, nelgv, nelgt, character*10 name10, integer, dimension(1) gllnid, integer, dimension(2,0:1) wk)
Definition at line 4463 of file genmap.f.
References assign_gllnid(), and izero().
function mod1 (i, n)
Definition at line 4670 of file genmap.f.
References i, mod1(), and n.
subroutine mult_chk (real, dimension(0:ndim,nv,nel) dx, ndim, nv, nel, integer, dimension(nv,nel) cell, nrnk)
Definition at line 3045 of file genmap.f.
References i, and rzero().
subroutine open_bin_file (logical ifbswap, nelgt, ndim, nelgv, integer wdsizi)
Definition at line 3341 of file genmap.f.
References byte_open, byte_read, chcopy(), exitti(), izero(), and ltrunc().
subroutine ortho1 (real, dimension(1) p, n)
Definition at line 2663 of file genmap.f.
References i, and n.
subroutine out_a (character*1, dimension(7,4,16,16) a)
Definition at line 2335 of file genmap.f.
References i, and j.
subroutine out_csrmati (integer, dimension(0:1) ia, integer, dimension(1) ja, n, character*9 name9)
Definition at line 1126 of file genmap.f.
References i, and n.
subroutine out_geofile (real, dimension(0:ndim,nv,nel) dx, ndim, nv, nel, integer, dimension(nel) pmap, io)
Definition at line 2992 of file genmap.f.
References i.
subroutine out_mapfile (integer, dimension(nel) pmap, nel, integer, dimension(nv,nel) cell, nv, nrnk, noutflow)
Definition at line 1651 of file genmap.f.
References dmp_mapfile(), log2(), and npts.
subroutine out_order (integer, dimension(1) order, mo, integer, dimension(1) elist, integer, dimension(nv,16,16) cell, nv, n1, n2)
Definition at line 2284 of file genmap.f.
References i, j, out_a(), and set_a().
subroutine outaij (integer, dimension(0:n) ia, integer, dimension(1) ja, n, character*6 name6, key)
Definition at line 2376 of file genmap.f.
References i, j, and n.
subroutine outbc (character*3, dimension(6,1) cbc, real*8, dimension(5,6,1) bc, nel, ndim, character*6 name6)
Definition at line 3917 of file genmap.f.
subroutine outcell (integer, dimension(n) cell, real, dimension(0:ndim,n) dx, n, ndim)
Definition at line 4493 of file genmap.f.
References i, and n.
subroutine outcheck (real, dimension(nwds) buf, integer nwds)
Definition at line 3327 of file genmap.f.
References i.
subroutine outmat (real, dimension(m,n) u, m, n, character*6 name6, nid)
Definition at line 1631 of file genmap.f.
References i, j, and n.
subroutine outmati (integer, dimension(m,n) u, m, n, character*6 name6, nid, ic)
Definition at line 1602 of file genmap.f.
References i, j, and n.
subroutine outmatti (integer, dimension(m,n) u, m, n, character*6 name6, nid, ic)
Definition at line 1583 of file genmap.f.
References i, j, and n.
subroutine part_clean (integer, dimension(1) order, nsep, integer, dimension(1) elist, integer, dimension(nv,1) cell, nv, n1, n2, integer, dimension(1) count, integer, dimension(1) wk)
Definition at line 1446 of file genmap.f.
References count_sep(), i, iglmax(), isort(), and iswap_ip().
subroutine periodic_vtx (integer, dimension(nv,nel) cell, nv, nel, irnk, real, dimension(0:ndim,nv,nel) dx, ndim, character*3, dimension(6,nel) cbc, real*8, dimension (5,6,nel) bc, nfc, integer, dimension(ndim,1) iper, integer, dimension(1) jmin)
Definition at line 2040 of file genmap.f.
References exitt(), find_connctd_pairs(), i, iranku(), izero(), jjnt(), npts, and self_chk().
subroutine rd_bc (character*3, dimension(6,nel) cbc, real*8, dimension(5,6,nel) bc, nel, ndim, ifield, io)
Definition at line 552 of file genmap.f.
References exitt().
subroutine rd_bc_bin (character*3, dimension(6,lelm) cbc, real*8, dimension (5,6,lelm) bc, nelv, nelt, logical ifbswap)
Definition at line 3185 of file genmap.f.
References buf_to_bc(), byte_read, byte_reverse, byte_reverse8, and exitti().
subroutine readwrite (character*80 sout, character*80 key, nk)
Definition at line 682 of file genmap.f.
References blank(), i, indx1(), and ltrunc().
subroutine readwrite2 (character*80 sout, character*80 key1, nk1, character*80 key2, nk2)
Definition at line 703 of file genmap.f.
References blank(), i, indx1(), and ltrunc().
subroutine rec_bisect (integer, dimension(1) elist, integer, dimension(1) pmap, integer, dimension(1) order, mo, integer, dimension(nv,nel) cell, nv, nel, ndim, integer, dimension(0:1) ia, integer, dimension(0:1) da, integer, dimension(1) w1, integer, dimension(1) w2, integer, dimension(1) w3)
Definition at line 1178 of file genmap.f.
References bipart_sort(), i, log2(), and n.
subroutine reverse_p (integer, dimension(n) p, n)
Definition at line 2868 of file genmap.f.
References i, and n.
subroutine rint (real, dimension(1) x, n)
Definition at line 832 of file genmap.f.
References i, and n.
subroutine rzero (real, dimension(1) a, n)
Definition at line 2832 of file genmap.f.
References i, and n.
subroutine sbisect (integer, dimension(n) pmap, real, dimension(n) f, integer, dimension(n) p, integer, dimension(n) w, n)
Definition at line 2546 of file genmap.f.
References i, iswap_ip(), jjnt(), n, and sort().
subroutine self_chk (integer, dimension(nv,nel) cell, nv, nel, integer flag)
Definition at line 3016 of file genmap.f.
References exitt(), i, j, and outmati().
subroutine set_a (character*1, dimension(7,4,16,16) a)
Definition at line 2352 of file genmap.f.
References blank().
subroutine set_d2 (real, dimension(0:ndim,nvrt,nel) dx, nvrt, nel, ndim)
Definition at line 480 of file genmap.f.
References i, j, and n.
subroutine set_outflow (no, integer, dimension(1) order, mo, integer, dimension(nv,nel) cell, nv, nel, nrnk, character*3, dimension(6,nel) cbc, nfc, integer, dimension(i0:i1) ic, i0, i1, integer, dimension(1) jc)
Definition at line 1927 of file genmap.f.
References i, iranku(), j, npts, and self_chk().
subroutine sort (real, dimension(1) a, integer, dimension(1) p, n)
Definition at line 1063 of file genmap.f.
References i, j, and n.
subroutine sort_count (integer, dimension(nel) pmap, integer, dimension(nel) elist, integer n1, integer n2, nel, integer, dimension(1) w1, integer, dimension(1) wk)
Definition at line 4344 of file genmap.f.
References i, and ituple_sort().
subroutine spec_bis (integer, dimension(n) pmap, real, dimension(n) f, integer, dimension(0:n) ia, integer, dimension(1) ja, integer, dimension(1) va, n, real, dimension(m) d, real, dimension(m) u, real, dimension(n) r, real, dimension(n) p2, real, dimension(n) w, real, dimension(n,m) rr, ev, m, ndim)
Definition at line 2509 of file genmap.f.
References cmult(), ev, glanczos(), glsc2(), i, lanczos2(), n, ortho1(), rint(), and sbisect().
subroutine spec_bis_conn (integer, dimension(nel) pmap, integer n1, integer n2, integer, dimension(nv,nel) c, integer, dimension(nel) elist, nv, nel, integer, dimension(nv,1) cell, integer ndim, integer, dimension(1) w1, integer, dimension(1) w2)
Definition at line 4001 of file genmap.f.
References c2c(), count_sep(), ev, i, i0, icopy(), iswap_ip(), ituple_sort(), izero(), j, jjnt(), rr, sort_count(), and spec_bis().
subroutine tuple_sort (real, dimension(lda,n) a, lda, n, integer, dimension(nkey) key, nkey, integer, dimension(1) ind, real, dimension(lda) aa)
Definition at line 1759 of file genmap.f.
References copy(), i, j, and n.
subroutine tuple_swapt_ip (real, dimension(m,n) x, m, n, integer, dimension(1) p, real, dimension(m) t1, real, dimension(m) t2)
Definition at line 1887 of file genmap.f.
References copy(), exitt(), i0, j, and n.
subroutine unique_vertex2 (integer, dimension(1) cell, real, dimension(0:ndim,1) dx, ndim, nel, q, integer, dimension(1) ind, integer, dimension(1) ninseg, logical, dimension(1) ifseg, real, dimension(0:ndim,1) wk)
Definition at line 2884 of file genmap.f.
References i, icopy(), iswap_ip(), j, n, self_chk(), tuple_sort(), and tuple_swapt_ip().