KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/getfld.f File Reference
getfld.f File Reference
Functions/Subroutines
subroutine getfld (newdump, jerr, if_call_setw, if_call_coef)
subroutine mapdmp (yd, xd, ieg, nxr, nyr, nzr, IF_BYTE_SW)
subroutine vrnvertq (a, n)
function revertq (T, ioldexp, izero)
subroutine vrnvert (a, n)
subroutine copy_byte_sw (y, x, n)
logical function if_byte_swap_test8 (bytetest)
logical function if_byte_swap_test (bytetest)
subroutine openfld (iunit, file, SUFFCH, SUFFI, status, iffmat, ierr)
subroutine reset_xc
subroutine copy4r (a, b, n)
subroutine copy8r (a, b, n)
Function/Subroutine Documentation
subroutine copy4r (real, dimension(1) a, real*4, dimension(1) b, n)
Definition at line 1160 of file getfld.f.
References i, and n.
subroutine copy8r (real, dimension(1) a, real*8, dimension(1) b, n)
Definition at line 1169 of file getfld.f.
References i, and n.
subroutine copy_byte_sw (character*1, dimension(0:3,1) y, character*1, dimension(0:3,1) x, n)
Definition at line 975 of file getfld.f.
References i, j, and n.
subroutine getfld (newdump, jerr, logical if_call_setw, logical if_call_coef)
Definition at line 3 of file getfld.f.
References avg_uvwpt_regular(), blank(), byte_close, byte_open, byte_read, byte_reverse, chcopy(), coef(), copy4r(), exitt(), i, indx1(), izero(), j, ltrunc(), mapdmp(), mapz(), nx, nz, prs(), reset_xc(), setwrk(), vlmax(), and vlmin().
logical function if_byte_swap_test (real*4 bytetest)
Definition at line 1001 of file getfld.f.
References byte_reverse, exitt(), and if_byte_swap_test().
logical function if_byte_swap_test8 (real*8 bytetest)
Definition at line 987 of file getfld.f.
subroutine mapdmp (dimension(nxr,nyr,nzr,nelm) yd, dimension(lxyzr) xd, ieg, nxr, nyr, nzr, logical IF_BYTE_SW)
Definition at line 770 of file getfld.f.
References byte_reverse, copy(), nx, and nz.
subroutine openfld (iunit, character*(*) file, character*4 SUFFCH, integer SUFFI, character*(*) status, logical iffmat, ierr)
Definition at line 1035 of file getfld.f.
References blank(), chcopy(), i, indx1(), izero(), and ltrunc().
subroutine reset_xc ()
Definition at line 1116 of file getfld.f.
References gencen(), i, j, nx, and nz.
function revertq (character*4 T, ioldexp, izero)
Definition at line 809 of file getfld.f.
References blank(), i, ione(), isort(), and izero().
subroutine vrnvert (real*4, dimension(1) a, n)
Definition at line 966 of file getfld.f.
References i, n, and revert().
subroutine vrnvertq (real*4, dimension(1) a, n)
Definition at line 795 of file getfld.f.
References i, izero(), n, and revertq().