KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/gfdm_solve.f File Reference
gfdm_solve.f File Reference
Functions/Subroutines
subroutine gfdm_pres_solv (z, r, ug, wg, kwave2)
Function/Subroutine Documentation
gfdm_pres_solv()
subroutine gfdm_pres_solv (real, dimension (lx2*ly2*lz2*lelv) z, real, dimension (lx2*ly2*lz2*lelv) r, real, dimension(lx2*ly2*lz2*lelv) ug, real, dimension(lx2*ly2*lz2*lelv) wg, real kwave2)
Definition at line 3 of file gfdm_solve.f.
References cexr(), cextr(), col2s2(), copy(), gfdm_set_diagp(), mxm(), swap_ip(), and swapt_ip().