KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/gfdm_par.f File Reference
gfdm_par.f File Reference
Functions/Subroutines
subroutine g25d_init
subroutine gfdm_init (nx, ny, nz, ifemati, kwave2)
subroutine gfdm_check_array_sizes (nx, ny, nz)
subroutine gfdm_mappings (nx, ny, nz)
subroutine assign_tp_numbering_pres (tpn, nex, ney, nez, nx, ny, nz, lglel, nel)
subroutine reassign_tp_numbering (tpn3, tpn2, tpn1, mp, ms, mt, n, ip, is, it, ni, nj, nk)
subroutine cex_setup (part_in, nr, part_out, m, n, nid, np)
subroutine cexr (w, u, m, n, part_out, part_in, msg_id, wdsize, nid, np)
subroutine cextr (u, m, n, w, part_out, part_in, msg_id, wdsize, nid, np)
subroutine cexi (w, u, m, n, part_out, part_in, msg_id, wdsize, nid, np)
subroutine cexti (u, m, n, w, part_out, part_in, msg_id, wdsize, nid, np)
Function/Subroutine Documentation
assign_tp_numbering_pres()
subroutine assign_tp_numbering_pres (integer, dimension(nx,ny,nz,nel) tpn, nex, ney, nez, nx, ny, nz, integer, dimension(nel) lglel, nel)
Definition at line 175 of file gfdm_par.f.
References mod1().
cex_setup()
subroutine cex_setup (integer, dimension(0:np) part_in, nr, integer, dimension(0:np) part_out, m, n, nid, np)
Definition at line 332 of file gfdm_par.f.
References igop().
cexi()
subroutine cexi (integer, dimension(1) w, integer, dimension(m,n) u, m, n, integer, dimension(0:np) part_out, integer, dimension(0:np) part_in, integer, dimension(0:np,2) msg_id, integer wdsize, nid, np)
Definition at line 527 of file gfdm_par.f.
References irecv(), isend(), and msgwait().
cexr()
subroutine cexr (real, dimension(1) w, real, dimension(m,n) u, m, n, integer, dimension(0:np) part_out, integer, dimension(0:np) part_in, integer, dimension(0:np,2) msg_id, integer wdsize, nid, np)
Definition at line 393 of file gfdm_par.f.
References irecv(), isend(), and msgwait().
cexti()
subroutine cexti (integer, dimension(m,n) u, m, n, integer, dimension(1) w, integer, dimension(0:np) part_out, integer, dimension(0:np) part_in, integer, dimension(0:np,2) msg_id, integer wdsize, nid, np)
Definition at line 595 of file gfdm_par.f.
References irecv(), isend(), and msgwait().
cextr()
subroutine cextr (real, dimension(m,n) u, m, n, real, dimension(1) w, integer, dimension(0:np) part_out, integer, dimension(0:np) part_in, integer, dimension(0:np,2) msg_id, integer wdsize, nid, np)
Definition at line 460 of file gfdm_par.f.
References irecv(), isend(), and msgwait().
g25d_init()
subroutine g25d_init ()
Definition at line 3 of file gfdm_par.f.
References exitt().
gfdm_check_array_sizes()
subroutine gfdm_check_array_sizes (nx, ny, nz)
Definition at line 51 of file gfdm_par.f.
References exitt().
gfdm_init()
subroutine gfdm_init (nx, ny, nz, logical ifemati, real kwave2)
Definition at line 12 of file gfdm_par.f.
References gfdm_check_array_sizes(), gfdm_mappings(), and gfdm_ops().
gfdm_mappings()
subroutine gfdm_mappings (nx, ny, nz)
Definition at line 75 of file gfdm_par.f.
References assign_tp_numbering_pres(), cex_setup(), cexi(), icopy(), irank(), iswap_ip(), and reassign_tp_numbering().
reassign_tp_numbering()
subroutine reassign_tp_numbering (integer, dimension(n) tpn3, integer, dimension(n) tpn2, integer, dimension(n) tpn1, mp, ms, mt, n, ip, is, it, ni, nj, nk)
Definition at line 218 of file gfdm_par.f.
References mod1().