KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/gfdm_op.f File Reference
gfdm_op.f File Reference
Functions/Subroutines
subroutine gfdm_ops (nx, ny, nz, kwave2, inew)
subroutine gfdm_set_prs_op (mfld)
subroutine set_1d_e_mat (eigv, eigs, n, length, nel, nxv, nxp, cb0, cbn, dglgt, wglgt, wgl, bw, lbw)
subroutine build_d1d_d (DI, II, dgg1, igg1, wm1, b1d, length, nel, nxv, nxp, wi, ti, cb0, cbn)
subroutine gfdm_set_geom (work, melx, mely, melz)
subroutine gfdm_set_genwz (nx, nxp)
subroutine gfdm_set_bc (cb0, cbn, mfld)
subroutine add2s2mat2p (a, ma, na, i1, j1, b, ldb, s, m, n)
subroutine overflow_chk (n_req, n_avail, var, sub)
subroutine map12q (r2, r1, rt)
subroutine row_mult (A, B, n1, n2)
subroutine a1d (A1, A1t, d2, b2, d1, d1t, wgl, nx)
subroutine set_diaga (da, dat, b, d, w, nx)
subroutine gfdm_chk_size
subroutine set_q_1d (q, m, nx, nel, bc0, bc1)
subroutine set_1d_abq (a, b, q, qt, m, nx, nel, len, bc0, bc1, wk)
subroutine set_ident (eye, ldi, n)
subroutine axpym (x, ldx, y, ldy, a, m, n)
subroutine set_fast_solve_1d (a, b, lam, q, qt, m, nx, nel, len, bc0, bc1, wk)
subroutine set_1d_a_mat (eigv, eigs, mlt, n, len, nel, nx, bc0, bc1, bw, lbw)
subroutine modify_eig (eigv, eigs, q, qt, m, ml, wk)
subroutine gen_1d_mult (mlt, q, qt, ml, m, wk)
subroutine gfdm_set_diagp (eigi, tpn, nn, eigx, l, eigy, m, eigz, n, kwave2)
Function/Subroutine Documentation
a1d()
subroutine a1d (real, dimension(nx,nx) A1, real, dimension(nx,nx) A1t, real, dimension(nx,nx) d2, real, dimension (nx,nx) b2, real, dimension(nx,nx) d1, real, dimension(nx,nx) d1t, real, dimension(nx) wgl, nx)
Definition at line 576 of file gfdm_op.f.
References mxm(), rzero(), and transpose().
add2s2mat2p()
subroutine add2s2mat2p (real, dimension(ma,na) a, ma, na, i1, j1, real, dimension(ldb,1) b, ldb, s, m, n)
Definition at line 515 of file gfdm_op.f.
References mod1().
axpym()
subroutine axpym (real, dimension(ldx,1) x, ldx, real, dimension(ldy,1) y, ldy, a, m, n)
Definition at line 772 of file gfdm_op.f.
build_d1d_d()
subroutine build_d1d_d (real, dimension(1) DI, real, dimension(1) II, real, dimension(1) dgg1, real, dimension(1) igg1, real, dimension(1) wm1, real, dimension(1) b1d, real, dimension(nel) length, nel, nxv, nxp, real, dimension(1) wi, real, dimension(1) ti, character*1 cb0, character*1 cbn)
Definition at line 188 of file gfdm_op.f.
References add2s2(), add2s2mat2p(), invcol1(), mxm(), and rzero().
gen_1d_mult()
subroutine gen_1d_mult (real, dimension(ml) mlt, real, dimension(ml,m) q, real, dimension(m,ml) qt, ml, m, real, dimension(ml) wk)
Definition at line 871 of file gfdm_op.f.
References mxm(), and rone().
gfdm_chk_size()
subroutine gfdm_chk_size ()
Definition at line 637 of file gfdm_op.f.
References exitt().
gfdm_ops()
subroutine gfdm_ops (nx, ny, nz, real kwave2, inew)
Definition at line 3 of file gfdm_op.f.
References gfdm_chk_size(), gfdm_set_diagp(), and gfdm_set_prs_op().
gfdm_set_bc()
subroutine gfdm_set_bc (character*1, dimension(3) cb0, character*1, dimension(3) cbn, mfld)
Definition at line 448 of file gfdm_op.f.
References igop(), and izero().
gfdm_set_diagp()
subroutine gfdm_set_diagp (real, dimension(nn) eigi, integer, dimension(nn) tpn, nn, real, dimension(l) eigx, l, real, dimension(m) eigy, m, real, dimension(n) eigz, n, real kwave2)
Definition at line 887 of file gfdm_op.f.
References glmax(), glmin(), and mod1().
gfdm_set_genwz()
subroutine gfdm_set_genwz (nx, nxp)
Definition at line 399 of file gfdm_op.f.
References a1d(), dgll(), dgllgl(), igllm(), iglm(), ly1, lz1, row_mult(), set_diaga(), transpose(), zwgl(), and zwgll().
gfdm_set_geom()
subroutine gfdm_set_geom (real, dimension(nelx,nely,nelz) work, melx, mely, melz)
Definition at line 343 of file gfdm_op.f.
References cmult(), get_exyz(), glmin(), gop(), ly1, lz1, and rzero().
gfdm_set_prs_op()
subroutine gfdm_set_prs_op (mfld)
Definition at line 46 of file gfdm_op.f.
References exitt(), gfdm_set_bc(), gfdm_set_genwz(), gfdm_set_geom(), ly1, lz1, set_1d_a_mat(), set_1d_e_mat(), and transpose().
map12q()
subroutine map12q (real, dimension(lx2,ly2) r2, real, dimension(lx1,ly1) r1, real, dimension(lx2,lx1) rt)
Definition at line 551 of file gfdm_op.f.
References mxm().
modify_eig()
subroutine modify_eig (real, dimension(1) eigv, real, dimension(1) eigs, real, dimension(ml,m) q, real, dimension(m,ml) qt, m, ml, real, dimension(1) wk)
Definition at line 852 of file gfdm_op.f.
References copy(), and mxm().
overflow_chk()
subroutine overflow_chk (n_req, n_avail, character*3 var, character*6 sub)
Definition at line 532 of file gfdm_op.f.
References exitt(), and mynode().
row_mult()
subroutine row_mult (real, dimension(n1,n2) A, real, dimension(n1) B, n1, n2)
Definition at line 564 of file gfdm_op.f.
set_1d_a_mat()
subroutine set_1d_a_mat (real, dimension(1) eigv, real, dimension(1) eigs, real, dimension(1) mlt, integer n, real, dimension(nel) len, nel, integer nx, character*1 bc0, character*1 bc1, real, dimension(0:lbw) bw, lbw)
Definition at line 801 of file gfdm_op.f.
References exitt(), gen_1d_mult(), lz1, modify_eig(), and set_fast_solve_1d().
set_1d_abq()
subroutine set_1d_abq (real, dimension(m,m) a, real, dimension(m,m) b, real, dimension(m,m) q, real, dimension(m,m) qt, m, nx, nel, real, dimension(nel) len, character*1 bc0, character*1 bc1, real, dimension(1) wk)
Definition at line 712 of file gfdm_op.f.
References axpym(), mxm(), rzero(), semhat(), set_q_1d(), and transpose().
set_1d_e_mat()
subroutine set_1d_e_mat (real, dimension(1) eigv, real, dimension(1) eigs, integer n, real, dimension(nel) length, nel, integer nxv, integer nxp, character*1 cb0, character*1 cbn, real, dimension(1) dglgt, real, dimension(1) wglgt, wgl, real, dimension(0:lbw) bw, lbw)
Definition at line 147 of file gfdm_op.f.
References build_d1d_d(), exitt(), and generalev().
set_diaga()
subroutine set_diaga (real, dimension(nx,nx) da, real, dimension(nx,nx) dat, real, dimension(nx) b, real, dimension(nx,nx) d, real, dimension(nx) w, nx)
Definition at line 612 of file gfdm_op.f.
References transpose().
set_fast_solve_1d()
subroutine set_fast_solve_1d (real, dimension(1) a, real, dimension(1) b, real, dimension(1) lam, real, dimension(1) q, real, dimension(1) qt, m, nx, nel, real, dimension(nel) len, character*1 bc0, character*1 bc1, real, dimension(1) wk)
Definition at line 786 of file gfdm_op.f.
References generalev(), and set_1d_abq().
set_ident()
subroutine set_ident (real, dimension(ldi,1) eye, ldi, n)
Definition at line 758 of file gfdm_op.f.
set_q_1d()
subroutine set_q_1d (real, dimension(nx*nel,1) q, m, nx, nel, character*1 bc0, character*1 bc1)
Definition at line 662 of file gfdm_op.f.
References rzero(), and set_ident().