KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/gfldr.f File Reference
gfldr.f File Reference
Functions/Subroutines
subroutine gfldr (sourcefld)
subroutine gfldr_getxyz (xout, yout, zout, ifbswp)
subroutine gfldr_getfld (out1, out2, out3, nldim, ifldpos, ifbswp)
subroutine gfldr_buf2vi (vi, index, buf, ldim, wds, nel, nxyz)
subroutine gfldr_intp (fieldout, fieldin, iffpts)
Function/Subroutine Documentation
gfldr()
subroutine gfldr (character, dimension(*) sourcefld)
Definition at line 4 of file gfldr.f.
References axis_interp_ic(), byte_close_mpi(), byte_open_mpi(), byte_read_mpi(), dnekclock_sync(), err_chk(), exitt(), exitti(), gfldr_getfld(), gfldr_getxyz(), igl_running_sum(), lelt, ly1, lz1, map_pm1_to_pr(), and mfi_parse_hdr().
gfldr_buf2vi()
subroutine gfldr_buf2vi (real, dimension(*) vi, index, real*4, dimension(*) buf, ldim, integer wds, nel, nxyz)
Definition at line 244 of file gfldr.f.
References copy(), and copy4r().
gfldr_getfld()
subroutine gfldr_getfld (real, dimension(*) out1, real, dimension(*) out2, real, dimension(*) out3, nldim, ifldpos, logical ifbswp)
Definition at line 188 of file gfldr.f.
References byte_read_mpi(), byte_reverse, byte_reverse8, byte_set_view(), gfldr_buf2vi(), gfldr_intp(), ly1, and lz1.
gfldr_getxyz()
subroutine gfldr_getxyz (real, dimension(*) xout, real, dimension(*) yout, real, dimension(*) zout, logical ifbswp)
Definition at line 156 of file gfldr.f.
References byte_read_mpi(), byte_reverse, byte_reverse8, byte_set_view(), and gfldr_buf2vi().
gfldr_intp()
subroutine gfldr_intp (real, dimension(*) fieldout, real, dimension(*) fieldin, logical iffpts)
Definition at line 265 of file gfldr.f.
References ly1, and lz1.