KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/glomod.f File Reference
glomod.f File Reference
Functions/Subroutines
subroutine glomod
subroutine frame (isplit, nframe)
subroutine splitf
subroutine parker (isplit)
subroutine crack (ielcrk, ifacrk, sfrac)
subroutine mark (ielcrk, ifacrk, sfrac, isplit)
subroutine mark2 (ielcrk, ifacrk, sfrac, isplit)
subroutine split (sfrac, isplit)
subroutine vertadj
subroutine vertadj_old
subroutine clpdom
subroutine clipper (Clip, DIR, pts)
subroutine clipper_r (xcyl, ycyl, rcyl, dir)
subroutine stretch
subroutine smoother2 (ncell)
subroutine runlapsm2d (x4, y4, eln, Q, nvv, bndrl, nodcl, d, ncell, itmax)
subroutine runoptsm2d (x4, y4, eln, Q, nvv, bndrl, nodcl, d, ncell, opt, itmax)
subroutine gradf2d (f1, dfdx, x4, y4, siz, opt, hval, ncell, nvv, eln)
subroutine get_jac2d (val, xx, yy, siz)
subroutine get_nodscale (scalek, x4, y4, ncell)
subroutine xtox4 (x4, y4, ncell, flag)
subroutine gennodc (nodc, eln, nv, ncell)
subroutine find_bc_crv2 (b, nv, eln, nvc, ncell)
subroutine smoother (cell, nvc, ia, ja, ww, b, g, x0, x1, y0, y1, z0, z1)
subroutine find_bc_crv (b, nv, cell, nvc, ncell)
subroutine build_adj (ja, ia, n, cell, nvc, ncell, edge, ne, w, wk, ind)
subroutine ituple_sort (a, lda, n, key, nkey, ind, aa)
subroutine tuple_sort (a, lda, n, key, nkey, ind, aa)
logical function iftuple_ialtb (a, b, key, nkey)
logical function iftuple_altb (a, b, key, nkey)
subroutine ituple_s_merge (na, a, lda, n, key, nkey, ind, aa)
function gs_smooth (x, y, z, b, c, a, ja, ia, n, g, gg, s, eps, icall)
subroutine get_gxyz (nv, cell, nvc, ncell, ww, ind, ierr)
subroutine out_matlab (ja, ia, n, io)
subroutine outc (cell, nvc, ncell, k)
subroutine smooth
subroutine find_sm_box (b, nv, x0, x1, y0, y1, z0, z1)
subroutine qb (b, nv, x, x0, x1)
subroutine find_bd_jac (b, nv, cell, nvc, nel, iebad, nebad)
subroutine chk_jacob (nebad, iebad, b, xp, yp, zp, cell, nvc)
subroutine chkjac (IERR, jac, n)
subroutine boundary_graph (g, b, ja, ia, n)
subroutine mult_del (del_list)
subroutine ipsort (ID, N, D, INFO)
subroutine clippern (xyzc, xyzn, DIR, xcl, ycl, zcl, del_list)
subroutine iusort (ID, N, list, INFO)
subroutine stretch_rad
subroutine stretch_theta
subroutine clean_spheres
subroutine rep_rot
subroutine replicate_mesh
subroutine rep_rotate_mesh
subroutine copy_sub_mesh (ie0, ie1, inew)
subroutine translate_sub_mesh (e0, e1, xt, yt, zt)
subroutine get_t1 (t, n)
subroutine gen_rotate_mat_3d (a, normal, angle)
subroutine rotate_el_vec (e, normal, angle)
subroutine rotate_el_3d (e, a)
subroutine rotate_mesh_3d_mat
subroutine rotate_mesh_3d
subroutine rotate_mesh_2d
subroutine rotate_submesh_2d (e0, e1, angle_deg)
subroutine rotate_submesh_3d (e0, e1, angle_deg, axisr)
subroutine template_to_forms
subroutine template_shape (e, et, ef)
subroutine apply_form_3d (xo, xi, jr, js, jt)
subroutine apply_form_2d (xo, xi, jr, js)
subroutine gen_jrst (jr, js, jt, et)
subroutine get_template
subroutine template_mesh
function blend_circ_in_box2 (x, y, r0, x0i, x1i, y0i, y1i)
function in_triangle2 (p, a, b, c)
subroutine stretch_outside_circ
subroutine stretch_outside_circ2 (r0, x0, x1, y0, y1, xmn, xmx, ymn, ymx)
subroutine flatten_edges_outside_circle (r0)
subroutine gencen2 (nel1, nel2)
subroutine fix_internal_bcs
subroutine add2col2 (a, b, c, n)
subroutine invcol1 (A, N)
subroutine cheap_dist (d, ifld, b, dims, eln, nvv, ncell, nnpts)
subroutine domain_sizek (xmin, xmax, ymin, ymax, zmin, zmax, dims, ncell)
function dist3d (a, b, c, x, y, z)
function dist2d (a, b, x, y)
subroutine qqt (eln, nv, ncell, qloc, nnpts)
subroutine qqtavg (eln, nv, ncell, qloc, nodcl, nnpts)
subroutine loctoglob (eln, nv, ncell, qloc, qglob, nnpts)
subroutine globtoloc (eln, nv, ncell, qloc, qglob, nnpts)
subroutine loctoglobmin (eln, nv, ncell, qloc, qglob, nnpts)
subroutine loctoglobmax (eln, nv, ncell, qloc, qglob, nnpts)
subroutine qqtmin (eln, nv, ncell, qloc, nnpts)
subroutine qqtmax (eln, nv, ncell, qloc, nnpts)
subroutine disfun (d, delta, nnpts, ncell)
subroutine restbndrlay (x4, y4, x4b, y4b, d, ncell)
subroutine get_neigh (e1, f1, e2, f2)
subroutine col2 (a, b, n)
Function/Subroutine Documentation
subroutine add2col2 (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, n)
Definition at line 4364 of file glomod.f.
References i, and n.
subroutine apply_form_2d (real, dimension(9) xo, real, dimension(3,3) xi, real, dimension(9,3) jr, real, dimension(9,3) js)
Definition at line 3952 of file glomod.f.
References i, and j.
subroutine apply_form_3d (real, dimension(27) xo, real, dimension(3,3,3) xi, real, dimension(27,3) jr, real, dimension(27,3) js, real, dimension(27,3) jt)
Definition at line 3934 of file glomod.f.
References i, and j.
function blend_circ_in_box2 (x, y, r0, x0i, x1i, y0i, y1i)
Definition at line 4067 of file glomod.f.
References cmult(), i, and in_triangle2().
subroutine boundary_graph (integer, dimension(1) g, integer, dimension(1) b, integer, dimension(1) ja, integer, dimension(1) ia, n)
Definition at line 2806 of file glomod.f.
References i, iglmax(), j, jfill(), n, and prsii().
subroutine build_adj (integer, dimension(1) ja, integer, dimension(1) ia, n, integer, dimension(nvc,ncell) cell, nvc, ncell, integer, dimension(2,ne) edge, ne, integer, dimension(2,1) w, integer, dimension(1) wk, integer, dimension(1) ind)
Definition at line 2066 of file glomod.f.
References i, ituple_s_merge(), and n.
subroutine cheap_dist (real, dimension(2*2*(dims-1),ncell) d, integer ifld, character*3 b, integer dims, integer, dimension(nnpts,ncell) eln, integer nvv, integer ncell, integer nnpts)
Definition at line 4381 of file glomod.f.
References cmult(), dist2d(), dist3d(), dmax, domain_sizek(), glmax(), n, qqtmin(), and rone().
subroutine chk_jacob (nebad, integer, dimension(1) iebad, integer, dimension(1) b, real, dimension(1) xp, real, dimension(1) yp, real, dimension(1) zp, integer, dimension(nvc,1) cell, nvc)
Definition at line 2658 of file glomod.f.
References addcol3(), addcol4(), chkjac(), dgll(), i, j, legend(), mxm(), prs(), res(), rzero(), subcol3(), and subcol4().
subroutine chkjac (IERR, real, dimension(n) jac, n)
Definition at line 2792 of file glomod.f.
References i, and n.
subroutine clean_spheres ()
Definition at line 3356 of file glomod.f.
subroutine clipper (Clip, character*1 DIR, real, dimension(8,nelm) pts)
Definition at line 1376 of file glomod.f.
References copyel(), i, izero(), prs(), and res().
subroutine clipper_r (xcyl, ycyl, rcyl, character*1 dir)
Definition at line 1438 of file glomod.f.
References copyel(), i, izero(), prs(), res(), and rr.
subroutine clippern (real, dimension(3) xyzc, real, dimension(3) xyzn, character*1 DIR, real, dimension(8,1) xcl, real, dimension(8,1) ycl, real, dimension(8,1) zcl, integer, dimension(1) del_list)
Definition at line 3144 of file glomod.f.
References delel(), drawel(), drgrid(), drmenu(), i, iusort(), prs(), prsii(), refresh(), and res().
subroutine clpdom ()
Definition at line 1278 of file glomod.f.
References clipper(), clipper_r(), clippern(), menu(), mult_del(), normalize(), prs(), rer(), rerr(), rerrr(), and res().
subroutine col2 (real, dimension(1) a, real, dimension(1) b, n)
Definition at line 4708 of file glomod.f.
References i, and n.
subroutine copy_sub_mesh (ie0, ie1, inew)
Definition at line 3460 of file glomod.f.
References copyel_p().
subroutine crack (ielcrk, ifacrk, sfrac)
Definition at line 634 of file glomod.f.
References color, gwrite(), mouse(), prs(), rer(), rerr(), rmin(), xscr(), and yscr().
subroutine disfun (real, dimension(ncell*nnpts) d, real delta, integer nnpts, integer ncell)
Definition at line 4648 of file glomod.f.
References cmult(), copy(), and glamax().
function dist2d (a, b, x, y)
Definition at line 4514 of file glomod.f.
References dist2d().
function dist3d (a, b, c, x, y, z)
Definition at line 4504 of file glomod.f.
References dist3d().
subroutine domain_sizek (real xmin, real xmax, real ymin, real ymax, real zmin, real zmax, integer dims, ncell)
Definition at line 4468 of file glomod.f.
References glmax(), and glmin().
subroutine find_bc_crv (integer, dimension(nv) b, nv, integer, dimension(nvc,ncell) cell, nvc, ncell)
Definition at line 2014 of file glomod.f.
References izero().
subroutine find_bc_crv2 (real, dimension(nv) b, nv, integer, dimension(nvc,ncell) eln, nvc, ncell)
Definition at line 1869 of file glomod.f.
References rone().
subroutine find_bd_jac (integer, dimension(nv) b, nv, integer, dimension(nvc,nel) cell, nvc, nel, integer, dimension(nebad) iebad, nebad)
Definition at line 2643 of file glomod.f.
References i, and j.
subroutine find_sm_box (integer, dimension(1) b, nv, x0, x1, y0, y1, z0, z1)
Definition at line 2614 of file glomod.f.
References qb().
subroutine fix_internal_bcs ()
Definition at line 4341 of file glomod.f.
References gen_neigh(), and get_neigh().
subroutine flatten_edges_outside_circle (r0)
Definition at line 4239 of file glomod.f.
References i, rr, and rzero().
subroutine frame (dimension(nelm) isplit, nframe)
Definition at line 157 of file glomod.f.
References copyel(), drawel(), i, mouse(), prs(), prsi(), prsis(), rer(), and rmin().
subroutine gen_jrst (real, dimension(27*3) jr, real, dimension(27*3) js, real, dimension(27*3) jt, integer et)
Definition at line 3968 of file glomod.f.
References gen_int_gz(), i, n, and rr.
subroutine gen_rotate_mat_3d (real, dimension(3,3) a, real, dimension(3) normal, angle)
Definition at line 3542 of file glomod.f.
References alpha, copy(), get_t1(), mxm(), normalize(), rzero(), transpose_r(), and vcross_normal().
subroutine gencen2 (integer nel1, integer nel2)
Definition at line 4263 of file glomod.f.
References genxyz_e(), i, j, prexit(), rzero(), and vsqrt().
subroutine gennodc (real, dimension(nv) nodc, integer, dimension(4,ncell) eln, integer nv, integer ncell)
Definition at line 1846 of file glomod.f.
References izero().
subroutine get_gxyz (nv, integer, dimension(nvc,1) cell, nvc, ncell, integer, dimension(0:1) ww, integer, dimension(1) ind, ierr)
Definition at line 2433 of file glomod.f.
References blank(), chcopy(), indx1(), j, and prs().
subroutine get_jac2d (real val, real, dimension(4) xx, real, dimension(4) yy, integer siz)
Definition at line 1733 of file glomod.f.
References cmult(), col3(), rzero(), and vlsum().
subroutine get_neigh (integer e1, integer f1, integer e2, integer f2)
Definition at line 4695 of file glomod.f.
subroutine get_nodscale (real scalek, real, dimension(4,ncell) x4, real, dimension(4,ncell) y4, integer ncell)
Definition at line 1789 of file glomod.f.
subroutine get_t1 (real, dimension(3) t, real, dimension(3) n)
Definition at line 3498 of file glomod.f.
References alpha, copy(), glamax(), glmax(), glmin(), i, and normalize().
subroutine get_template ()
Definition at line 4001 of file glomod.f.
References copy_sub_mesh(), glmax(), glmin(), and imp_mesh().
subroutine globtoloc (integer, dimension(nnpts,ncell) eln, integer nv, integer ncell, real, dimension(nnpts,ncell) qloc, real, dimension(nv) qglob, integer nnpts)
Definition at line 4567 of file glomod.f.
References rzero().
subroutine glomod ()
Definition at line 18 of file glomod.f.
References clpdom(), crack(), frame(), hex_transition_3d(), hexagon_refine(), mark(), mark2(), menu(), mesh_edit(), mkside(), octspl(), parker(), prs(), redraw_mesh(), rep_rot(), shift(), smooth(), split(), splitf(), stretch(), vertadj(), wind3d(), and zip2().
subroutine gradf2d (real f1, real, dimension(4,ncell,2) dfdx, real, dimension(4,ncell) x4, real, dimension(4,ncell) y4, integer siz, integer opt, hval, ncell, integer nvv, integer, dimension(4,ncell) eln)
Definition at line 1695 of file glomod.f.
References copy(), get_jac2d(), and qqt().
function gs_smooth (real, dimension(1) x, real, dimension(1) y, real, dimension(1) z, integer, dimension(1) b, real, dimension(1) c, real, dimension(1) a, integer, dimension(1) ja, integer, dimension(1) ia, n, integer, dimension(1) g, gg, s, eps, icall)
Definition at line 2327 of file glomod.f.
References gs_smooth(), i, j, n, and scale().
logical function iftuple_altb (real, dimension(1) a, real, dimension(1) b, integer, dimension(nkey) key, nkey)
Definition at line 2283 of file glomod.f.
References i, and iftuple_altb().
logical function iftuple_ialtb (integer, dimension(1) a, integer, dimension(1) b, integer, dimension(nkey) key, nkey)
Definition at line 2265 of file glomod.f.
References i, and iftuple_ialtb().
function in_triangle2 (real, dimension(2) p, real, dimension(2) a, real, dimension(2) b, real, dimension(2) c)
Definition at line 4130 of file glomod.f.
References sub3(), and vlsc2().
subroutine invcol1 (real, dimension(1) A, N)
Definition at line 4373 of file glomod.f.
References i, and n.
subroutine ipsort (character ID, integer N, integer, dimension(1) D, integer INFO)
Definition at line 2901 of file glomod.f.
References i, j, tmp, and xerbla().
subroutine ituple_s_merge (na, integer, dimension(lda,n) a, lda, n, integer, dimension(nkey) key, nkey, integer, dimension(1) ind, integer, dimension(lda) aa)
Definition at line 2301 of file glomod.f.
References ituple_sort(), j, and n.
subroutine ituple_sort (integer, dimension(lda,n) a, lda, n, integer, dimension(nkey) key, nkey, integer, dimension(1) ind, integer, dimension(lda) aa)
Definition at line 2141 of file glomod.f.
References i, icopy(), j, and n.
subroutine iusort (character*1 ID, N, integer, dimension(1) list, INFO)
Definition at line 3226 of file glomod.f.
References i, ipsort(), and n.
subroutine loctoglob (integer, dimension(nnpts,ncell) eln, integer nv, integer ncell, real, dimension(nnpts,ncell) qloc, real, dimension(nv) qglob, integer nnpts)
Definition at line 4551 of file glomod.f.
References rzero().
subroutine loctoglobmax (integer, dimension(nnpts,ncell) eln, integer nv, integer ncell, real, dimension(nnpts,ncell) qloc, real, dimension(nv) qglob, integer nnpts)
Definition at line 4603 of file glomod.f.
References cmult(), and rone().
subroutine loctoglobmin (integer, dimension(nnpts,ncell) eln, integer nv, integer ncell, real, dimension(nnpts,ncell) qloc, real, dimension(nv) qglob, integer nnpts)
Definition at line 4585 of file glomod.f.
References cmult(), and rone().
subroutine mark (ielcrk, ifacrk, sfrac, integer, dimension(nelm) isplit)
Definition at line 696 of file glomod.f.
References gen_neigh(), i, prs(), prsis(), res(), and rmin().
subroutine mark2 (ielcrk, ifacrk, sfrac, integer, dimension(nelm) isplit)
Definition at line 820 of file glomod.f.
References i.
subroutine mult_del (integer, dimension(nelm) del_list)
Definition at line 2841 of file glomod.f.
References delel(), drawel(), drgrid(), drmenu(), i, iusort(), prs(), prsii(), refresh(), and res().
subroutine out_matlab (integer, dimension(1) ja, integer, dimension(1) ia, integer n, io)
Definition at line 2517 of file glomod.f.
References i, and j.
subroutine outc (integer, dimension(nvc,ncell) cell, nvc, ncell, k)
Definition at line 2533 of file glomod.f.
References i, and j.
subroutine parker (integer, dimension(nelm) isplit)
Definition at line 511 of file glomod.f.
References copyel(), drawel(), i, mouse(), prs(), rerr(), rmin(), sortel(), vlsum(), xscr(), and yscr().
subroutine qb (integer, dimension(1) b, nv, real, dimension(1) x, x0, x1)
Definition at line 2628 of file glomod.f.
References i.
subroutine qqt (integer, dimension(nnpts,ncell) eln, integer nv, integer ncell, real, dimension(nnpts,ncell) qloc, integer nnpts)
Definition at line 4524 of file glomod.f.
References globtoloc(), and loctoglob().
subroutine qqtavg (integer, dimension(nnpts,ncell) eln, integer nv, integer ncell, real, dimension(nnpts,ncell) qloc, integer, dimension(nnpts,ncell) nodcl, integer nnpts)
Definition at line 4537 of file glomod.f.
References globtoloc(), invcol2(), and loctoglob().
subroutine qqtmax (integer, dimension(nnpts,ncell) eln, integer nv, integer ncell, real, dimension(nnpts,ncell) qloc, integer nnpts)
Definition at line 4635 of file glomod.f.
References globtoloc(), and loctoglobmax().
subroutine qqtmin (integer, dimension(nnpts,ncell) eln, integer nv, integer ncell, real, dimension(nnpts,ncell) qloc, integer nnpts)
Definition at line 4622 of file glomod.f.
References globtoloc(), and loctoglobmin().
subroutine rep_rot ()
Definition at line 3375 of file glomod.f.
References prs(), rep_rotate_mesh(), replicate_mesh(), res(), rotate_mesh_2d(), rotate_mesh_3d(), and template_mesh().
subroutine rep_rotate_mesh ()
Definition at line 3419 of file glomod.f.
References capit(), copy_sub_mesh(), i, prs(), rei(), rer(), res(), and rotate_submesh_3d().
subroutine replicate_mesh ()
Definition at line 3392 of file glomod.f.
References copy_sub_mesh(), i, prs(), rei(), rerr(), rerrr(), and translate_sub_mesh().
subroutine restbndrlay (real, dimension(4,ncell) x4, real, dimension(4,ncell) y4, real, dimension(4,ncell) x4b, real, dimension(4,ncell) y4b, real, dimension(4,ncell) d, integer ncell)
Definition at line 4672 of file glomod.f.
References add2(), col2(), and sub2().
subroutine rotate_el_3d (integer e, real, dimension(3,3) a)
Definition at line 3600 of file glomod.f.
References i.
subroutine rotate_el_vec (integer e, real, dimension(3) normal, angle)
Definition at line 3585 of file glomod.f.
References gen_rotate_mat_3d(), and rotate_el_3d().
subroutine rotate_mesh_2d ()
Definition at line 3707 of file glomod.f.
References i, prs(), rer(), and rzero().
subroutine rotate_mesh_3d ()
Definition at line 3689 of file glomod.f.
References prs(), rer(), rerrr(), and rotate_el_vec().
subroutine rotate_mesh_3d_mat ()
Definition at line 3637 of file glomod.f.
References i, j, prs(), and rzero().
subroutine rotate_submesh_2d (integer e0, integer e1, angle_deg)
Definition at line 3750 of file glomod.f.
References i, and rzero().
subroutine rotate_submesh_3d (integer e0, integer e1, angle_deg, character*1 axisr)
Definition at line 3791 of file glomod.f.
References i, and rzero().
subroutine runlapsm2d (real, dimension(4,ncell) x4, real, dimension(4,ncell) y4, integer, dimension(4,ncell) eln, Q, integer nvv, real, dimension(ncell*4) bndrl, real, dimension(ncell*4) nodcl, real, dimension(4,ncell) d, integer ncell, integer itmax)
Definition at line 1593 of file glomod.f.
References add2(), col2(), qqtavg(), rzero(), and vlsum().
subroutine runoptsm2d (real, dimension(4,ncell) x4, real, dimension(4,ncell) y4, integer, dimension(4,ncell) eln, Q, integer nvv, real, dimension(ncell*4) bndrl, real, dimension(ncell*4) nodcl, integer, dimension(4,ncell) d, integer ncell, integer opt, integer itmax)
Definition at line 1643 of file glomod.f.
References add2col2(), cmult(), col2(), get_nodscale(), glamax(), gradf2d(), and invcol1().
subroutine smooth ()
Definition at line 2545 of file glomod.f.
References convert_m_to_c_allr(), menu(), prs(), redraw_mesh(), rerr(), smoother2(), and xtox4().
subroutine smoother (integer, dimension(nvc,1) cell, nvc, integer, dimension(1) ia, integer, dimension(1) ja, real, dimension(0:1) ww, integer, dimension(1) b, integer, dimension(1) g, x0, x1, y0, y1, z0, z1)
Definition at line 1905 of file glomod.f.
References boundary_graph(), build_adj(), chk_jacob(), find_bc_crv(), find_bd_jac(), find_sm_box(), get_gxyz(), gs_smooth(), i, izero(), n, prs(), and rerrr().
subroutine smoother2 (integer ncell)
Definition at line 1509 of file glomod.f.
References cheap_dist(), chker2(), copy(), disfun(), find_bc_crv2(), gennodc(), globtoloc(), j, makecell(), n, prs(), reiii(), restbndrlay(), rone(), runlapsm2d(), runoptsm2d(), set_d2a(), and xtox4().
subroutine split (sfrac, integer, dimension(1000) isplit)
Definition at line 833 of file glomod.f.
References copyel(), drawel(), getpts(), i, ia, if(), msplite(), prs(), and sortel().
subroutine splitf ()
Definition at line 430 of file glomod.f.
References copyel(), drawel(), drelev(), i, prs(), rer(), sortel(), and vlsum().
subroutine stretch ()
Definition at line 1504 of file glomod.f.
References shift2().
subroutine stretch_outside_circ ()
Definition at line 4158 of file glomod.f.
References gencen(), glmax(), glmin(), n, prs(), prsrr(), rer(), rerr(), scale(), and stretch_outside_circ2().
subroutine stretch_outside_circ2 (r0, x0, x1, y0, y1, xmn, xmx, ymn, ymx)
Definition at line 4198 of file glomod.f.
References blend_circ_in_box(), flatten_edges_outside_circle(), i, n, redraw_mesh(), and x27_to_e().
subroutine stretch_rad ()
Definition at line 3250 of file glomod.f.
References i, prs(), rer(), res(), and rr.
subroutine stretch_theta ()
Definition at line 3328 of file glomod.f.
References i, prs(), and rer().
subroutine template_mesh ()
Definition at line 4026 of file glomod.f.
References copy_sub_mesh(), get_template(), and template_to_forms().
subroutine template_shape (integer e, integer et, integer ef)
Definition at line 3888 of file glomod.f.
References apply_form_2d(), apply_form_3d(), blank(), copyel_p(), fix_m_curve(), gen_jrst(), q_to_neklin(), and rzero().
subroutine template_to_forms ()
Definition at line 3849 of file glomod.f.
References template_shape().
subroutine translate_sub_mesh (integer e0, integer e1, xt, yt, zt)
Definition at line 3474 of file glomod.f.
References i.
subroutine tuple_sort (real, dimension(lda,n) a, lda, n, integer, dimension(nkey) key, nkey, integer, dimension(1) ind, real, dimension(lda) aa)
Definition at line 2203 of file glomod.f.
References copy(), i, j, and n.
subroutine vertadj ()
Definition at line 1010 of file glomod.f.
References cell_cell_connectivity(), dist2(), gencen(), glmin(), prrrr(), prs(), rmin(), and round().
subroutine vertadj_old ()
Definition at line 1132 of file glomod.f.
References dist2(), gencen(), glmin(), prrrr(), prs(), rmin(), and round().
subroutine xtox4 (real, dimension(4,ncell) x4, real, dimension(4,ncell) y4, integer ncell, integer flag)
Definition at line 1820 of file glomod.f.