KTH framework for Nek5000 toolboxes; testing version: History points driver for toolboxes.
History points driver for toolboxes.
Toolbox » Driver modules for KTH nek5000 platform
History points/particles driver.
Files
file pts_redistribute.f
Set of subroutines to redistribute pionts among processors according to point-element map.
Functions
subroutine pts_timing (nptimb, urbuf, lurbuf, lpbuf, ifutrans)
Point redistribution timing.
subroutine pts_rdst (nptimb, urbuf, lurbuf, lpbuf, ifutrans)
Redistribute points.
subroutine pts_transfer (rbuf, lrbuf, ibuf, libuf, lpts, npts)
Point data transfer.
subroutine pts_map_all (mid, lpts, npts, npoints, nptimb)
Point-process mapping.
subroutine pts_map_set (mid, lpts, istatus, indasg, npts_plist, lplist, npts, nplist)
Point-process mapping for given process set.
Detailed Description
History points/particles driver.
Set of subroutines to work with hpts interpolation routines from Nek5000. Using defined (relatively big) set of points in the domain it allows to redistribute them among processors according to point-to-element mapping and retrive set of variables using spectral interpolation (hpts routines).
Module interface:
This module provides following interface:
pts_timing
pts_rdst
Module memory structures:
This module provides following variables:
pts_crd(LDIM,LHIS) - (real) point coordinates
pts_npts - (integer) local number of points
pts_npoints - (integer) global number of points
pts_ihpts - (integer) findpts_setup handle
Module interface usage:
      subroutine userchk
      include 'SIZE'
      real ubuffer(2,lhis)
!     pts timing and redistribute
      call pts_timing(nptimb,ubuffer,2,lhis,.true.)
      return
      end
      subroutine userchk
      include 'SIZE'
      real ubuffer(2,lhis)
!     main pts interface; point redistribute
      call pts_rdst(nptimb,ubuffer,2,lhis,.true.)
      return
      end
Note
This vesion of the code does not work for number of processors bigger than 2*LX1*LY1*LZ1*LELT.
Check PTSD include file for definition of memeory structures provided by this module.
This module requres findpts_setup to be executed before any of the module routines would be called.
Todo:
This vesion of the code does not take into account error code rcode. This shuld be added later.
Function Documentation
subroutine pts_map_all (integer, dimension(lpts) mid, integer lpts, integer npts, integer npoints, integer nptimb)
Point-process mapping.
Genereate point-process mapping for point redistribution. This routine leaves local number of points npts unchanged.
Parameters
[in,out] mid target proc id; global ordering
[in] lpts array size
[in] npts local number of points
[in] npoints global number of points
[in] nptimb max allowed imbalance
Remarks
This routine uses global scratch space SCRVH
Definition at line 371 of file pts_redistribute.f.
References exitt(), lelt, ly1, lz1, nekgsync(), npts, and pts_map_set().
subroutine pts_map_set (integer, dimension(lpts) mid, integer lpts, integer istatus, integer indasg, integer, dimension(lplist) npts_plist, integer lplist, integer npts, integer nplist)
Point-process mapping for given process set.
Genereate point-process mapping for point redistribution for given process set. This routine leaves local number of points npts unchanged.
Parameters
[in,out] mid target proc id; global ordering
[in] lpts mid array size
[in,out] istatus node status
[in,out] indasg number of points asigned to the node
[in] npts_plist list of processors used
[in] lplist npts_plist array size
[in] npts local number of points
[in] nplist number of processors in the list
Remarks
This routine uses global scratch space SCRCH, SCREV, CTMP0, CTMP1, SCRSF
Definition at line 599 of file pts_redistribute.f.
References exitt(), ibcastn(), icopy(), ivgl_running_sum(), izero(), lelt, ly1, and lz1.
subroutine pts_rdst (integer nptimb, real, dimension(lurbuf,lpbuf) urbuf, integer lurbuf, integer lpbuf, logical ifutrans)
Redistribute points.
Redistribute points according to point-to-element map. This routine assume findpts was alleready called and pts_proc array is filled.
Parameters
[in] nptimb maximal allowed point imbalance
[in,out] urbuf user defined real buffer
[in] lurbuf number of real variables
[in] lpbuf buffer length
[in] ifutrans do we perform user buffer transfer
Remarks
This routine uses global scratch space SCRMG, SCRNS
Definition at line 157 of file pts_redistribute.f.
References exitt(), lelt, ly1, lz1, pts_map_all(), and pts_transfer().
subroutine pts_timing (integer nptimb, real, dimension(lurbuf,lpbuf) urbuf, integer lurbuf, integer lpbuf, logical ifutrans)
Point redistribution timing.
Test interpolation time for single variable before and after point redistribution. This routine assumes physical point coordinates to be provided and stored in pts_crd declared in PTSD include file.
Parameters
[in] nptimb maximal allowed point imbalance
[in,out] urbuf user defined real buffer
[in] lurbuf number of real variables
[in] lpbuf buffer length
[in] ifutrans do we perform user buffer transfer
Note
This routine perform interpolation of x velocity component for timing test.
Definition at line 21 of file pts_redistribute.f.
References findpts, findpts_eval, and pts_rdst().
subroutine pts_transfer (real, dimension(lrbuf,lpts) rbuf, integer lrbuf, integer, dimension(libuf,lpts) ibuf, integer libuf, integer lpts, integer npts)
Point data transfer.
Parameters
[in,out] rbuf real buffer
[in] lrbuf number of real variables
[in,out] ibuf integer buffer
[in] libuf number of integer variables
[in] lpts buffers length
[in,out] npts local number of points
Definition at line 304 of file pts_redistribute.f.