KTH framework for Nek5000 toolboxes; testing version: Multistep checkpointing
Multistep checkpointing
Framework for Nek5000 toolboxes » Toolbox » Input/output module » Checkpointing routines
Multistep checkpointing for DNS, MHD and linear simulations.
Files
file chkpt_mstp.f
Set of multi-file checkpoint routines for DNS, MHD and perturbation simulations.
Functions
subroutine chkpts_register ()
Register multi step checkpointing module.
subroutine chkpts_init
Initialise multi-file checkpoint routines.
logical function chkpts_is_initialised ()
Check if module was initialised.
subroutine chkpts_write ()
Write full file restart set.
subroutine chkpts_read ()
Read full file restart set.
subroutine chkpt_dt_get
Get old simulation time steps and pressure mesh marker.
subroutine chkpt_set_name (fname, fnum, nset, ifile)
Generate set of restart file names in snapshot.
subroutine chkpt_fname (fname, prefix, nset, ifile, ierr)
Generate single restart file name.
subroutine chkpt_restart_write (fname, fnum, ifcoord)
Write checkpoint snapshot.
subroutine chkpt_restart_read (fname, fnum)
Read checkpoint snapshot.
subroutine chkpt_mfo (fname, chktype, ipert)
Write field to the file.
subroutine chkpt_mfi (fname, chktype, ipert)
Read field to the file.
subroutine chkpt_map_gll (xf, yf, nxr, nzr, nel)
Interpolate input on velocity mesh.
subroutine chkpt_map_gl (xf, yf, nxr, nzr, nel)
Interpolate pressure input.
subroutine chkpt_axis_interp_ic ()
Map loaded variables from velocity to axisymmetric mesh.
Detailed Description
Multistep checkpointing for DNS, MHD and linear simulations.
In the case of multistep restart one needs data from NBDINP timestep, where NBDINP is time integration order. I adapt full_restart and full_restart_save subroutines for DNS, MHD and perturbation simulations. There are three possible sets of restart files generated by this module:
'rsX...' storing DNS data,
'rbX...' storing MHD data,
'rpX...' storing perturbation data,
where X is equal to 2*NBDINP and gives a max number of restart files. Only NBDINP files is requiered for restart and there are two file sets to avoid overwritting. Checkpoints are saved in double precission in binary ###.f format.
The possible combinations of files are:
'rsX...' alone for DNS mode,
'rsX...' and 'rbX...' for MHD mode,
'rsX...' and 'rpX...' for perturbation mode.
In the perturbation mode only the first perturbation is written to the checkpoint file. To save disc space the mesh data is written only to the 'rsX...' file. For not moving boundaries (IFMVBD=FALSE) only the first 'rsX...' file in the set contains mehs data. In the similar way in the perturbation mode with fixed base flow (IFBASE=FALSE) only single 'rsX...' file is generated.
Notice for multistep checkpointing runtime parameter chkpFnumber gives the fiel set number, so it can be equal 1 or 2 only.
Module interface:
Global interface list:
Interface provided to checkpoint:
chkpts_register
chkpts_init
chkpts_read
chkpts_write
Module parameters:
Global parameter dependency:
Parameters required by multistep module:
CHKPOINTD:
chpt_step - checkpiont dump frequency (number of time steps)
chpt_ifrst - if restart
chpt_fnum - restart set number
Nek5000 PARAM array
PARAM(27) - if negative number of files is equal NBDINP otherwise chpm_snmax
Function Documentation
chkpt_axis_interp_ic()
subroutine chkpt_axis_interp_ic ()
Map loaded variables from velocity to axisymmetric mesh.
Note
This is version of axis_interp_ic taking into account fact pressure does not have to be written on velocity mesh.
Remarks
This routine uses global scratch space CTMP0.
Definition at line 1331 of file chkpt_mstp.f.
References copy(), invmt(), and mxm().
chkpt_dt_get()
subroutine chkpt_dt_get ()
Get old simulation time steps and pressure mesh marker.
Todo:
Different files could have different chpm_if_pmesh, so it is not the best place to read it
Definition at line 294 of file chkpt_mstp.f.
References addfid(), bcast(), blank(), byte_close, byte_open, byte_read, chkpt_fname(), io_init(), and mntr_check_abort().
chkpt_fname()
subroutine chkpt_fname (character*132 fname, character*3 prefix, integer nset, integer ifile, integer ierr)
Generate single restart file name.
Parameters
[out] fname restart file name
[in] prefix prefix
[in] nset set number
[in] ifile snupshot numer
[out] ierr error mark
Definition at line 454 of file chkpt_mstp.f.
References io_mfo_fname(), and mntr_error().
chkpt_map_gl()
subroutine chkpt_map_gl (real, dimension(lx2,ly2,lz2,nel) xf, real, dimension(nxr,nxr,nzr,nel) yf, integer nxr, integer nzr, integer nel)
Interpolate pressure input.
This is version of mapab modified to work with pressure mesh. It iterpolates fields defined on GL points. Like the orginal routine I assume NXR=NYR=NZR, or NXR=NYR, NZR=1
Parameters
[out] xf output field on pressure mesh
[in] yf input field on pressure mesh
[in] nxr,nzr array sizes
[in] nel element number
Remarks
This routine uses global scratch space CTMP0, CTMPABM2
Definition at line 1267 of file chkpt_mstp.f.
References copy(), iglm(), mxm(), and zwgl().
chkpt_map_gll()
subroutine chkpt_map_gll (real, dimension(lx1,ly1,lz1,nel) xf, real, dimension(nxr,nxr,nzr,nel) yf, integer nxr, integer nzr, integer nel)
Interpolate input on velocity mesh.
This is version of mapab with corrected array sizes. It iterpolates fields defined on GLL points. Like the orginal routine I assume NXR=NYR=NZR, or NXR=NYR, NZR=1
Parameters
[out] xf output field on velocity mesh
[in] yf input field on velocity mesh
[in] nxr,nzr array sizes
[in] nel element number
Remarks
This routine uses global scratch space CTMP0, CTMPABM1
Definition at line 1198 of file chkpt_mstp.f.
References copy(), igllm(), ly1, lz1, mxm(), and zwgll().
chkpt_mfi()
subroutine chkpt_mfi (character*132 fname, integer chktype, integer ipert)
Read field to the file.
This routine is based on mfi but supports perturbation as well. It is optimised for chekpoint reading.
Parameters
[in] fname file name
[in] chktype data type to read (DNS, MHD, preturbation)
[in] ipert index of perturbation field
Remarks
This routine uses global scratch space SCRUZ.
Definition at line 825 of file chkpt_mstp.f.
References chkpt_axis_interp_ic(), chkpt_map_gl(), chkpt_map_gll(), copy(), io_mbyte_close(), io_mfis(), io_mfiv(), lelt, ly1, lz1, map12(), map21t(), mfi_prepare(), mntr_check_abort(), mntr_log(), mntr_logi(), and mntr_logr().
chkpt_mfo()
subroutine chkpt_mfo (character*132 fname, integer chktype, integer ipert)
Write field to the file.
This routine is based on mfo_outfld but does not assume any file numbering. It is optimised for chekpoint writing.
Parameters
[in] fname file name
[in] chktype data type to write (DNS, MHD, perturbation)
[in] ipert index of perturbation field
Note
Only one set of data (DNS, MHD or perturbation) can be saved in single file
Remarks
This routine uses global scratch space SCRCG.
Definition at line 662 of file chkpt_mstp.f.
References copy(), io_mbyte_close(), io_mbyte_open(), io_mfos(), io_mfov(), mfo_write_hdr(), mntr_check_abort(), mntr_log(), mntr_logi(), mntr_logr(), and rzero().
chkpt_restart_read()
subroutine chkpt_restart_read (character*132, dimension(chkptnfmax) fname, integer fnum)
Read checkpoint snapshot.
Parameters
[out] fname restart file name
[in] fnum number of files in snapshot
Definition at line 596 of file chkpt_mstp.f.
References chkpt_mfi(), mntr_abort(), and sioflag().
chkpt_restart_write()
subroutine chkpt_restart_write (character*132, dimension(chkptnfmax) fname, integer fnum, logical ifcoord)
Write checkpoint snapshot.
Parameters
[out] fname restart file name
[in] fnum number of files in snapshot
[in] ifcoord do we save coordinates
Definition at line 504 of file chkpt_mstp.f.
References chkpt_mfo(), and mntr_abort().
chkpt_set_name()
subroutine chkpt_set_name (character*132, dimension(chkptnfmax) fname, integer fnum, integer nset, integer ifile)
Generate set of restart file names in snapshot.
Parameters
[out] fname restart file names
[out] fnum number of files in snapshot
[in] nset set number
[in] ifile snupshot numer
Definition at line 376 of file chkpt_mstp.f.
References chkpt_fname(), and mntr_check_abort().
chkpts_init()
subroutine chkpts_init ()
Initialise multi-file checkpoint routines.
Note
This interface is defined in chkpt_main
Definition at line 57 of file chkpt_mstp.f.
References chkpt_dt_get(), mntr_abort(), and mntr_warn().
chkpts_is_initialised()
logical function chkpts_is_initialised ()
Check if module was initialised.
Returns
chkpts_is_initialised
Definition at line 99 of file chkpt_mstp.f.
References chkpts_is_initialised().
chkpts_read()
subroutine chkpts_read ()
Read full file restart set.
Note
This interface is defined in chkpt_main
This is version of full_restart routine.
Definition at line 214 of file chkpt_mstp.f.
References chcopy(), chkpt_restart_read(), chkpt_set_name(), io_init(), mntr_tmr_add(), and mntr_warn().
chkpts_register()
subroutine chkpts_register ()
Register multi step checkpointing module.
Definition at line 9 of file chkpt_mstp.f.
References mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), mntr_set_step_delay(), mntr_tmr_is_name_reg(), mntr_tmr_reg(), and mntr_warn().
chkpts_write()
subroutine chkpts_write ()
Write full file restart set.
Note
This interface is defined in chkpt_main.
This is version of full_restart_save routine.
Definition at line 114 of file chkpt_mstp.f.
References chcopy(), chkpt_restart_write(), chkpt_set_name(), io_init(), mntr_log(), and mntr_tmr_add().