KTH framework for Nek5000 toolboxes; testing version: Power itertion routines
Power itertion routines
Framework for Nek5000 toolboxes » Toolbox » Tools module » Time stepper routines
Power iteration submodule.
Files
file powerit.f
Set of subroutines to perform power iterations within time stepper.
Functions
subroutine stepper_register ()
Register power iteration module.
subroutine stepper_init ()
Initilise power iteration module.
logical function stepper_is_initialised ()
Check if module was initialised.
subroutine stepper_vsolve
Renormalise vector and check convergence.
subroutine stepper_read (set_in)
Read restart files.
subroutine stepper_write
Write restart files.
Detailed Description
Power iteration submodule.
Warning
This module is not upgraded to stable Nek5000 relese yet
Module interface:\n
Global interface list:
Interface provided to tstepper:
stepper_param_in
stepper_param_out
stepper_vinit
stepper_solve
Module parameters:\n
Global parameter list:
Parameters provided by power iteration submodule (include file - POWERITD):
PWIL2NORM : (real) initial L2 norm of the evolved vector for every cycle
Global parameter dependency:
Parameters required by power iteration submodule:
CHKPOINTD:
IFCHKPTRST : if restart
CHKPTSTEP - checkpiont dump frequency (number of time steps)
CONHT (for conjugated heat transfer):
CHCST_SC, CHCFF_V, CHCFF_T : velocity and temperature scaling factors
CHGRX, CHGRY, CHGRZ : gravitational acceleration
CHRA, CHPR : Rayleight and Prandtl numbers
Module parameter usage:\n
&powerit
 pwil2norm=  1.0000000000000000     ,
 /
Function Documentation
stepper_init()
subroutine stepper_init
Initilise power iteration module.
Note
This interface is called by tst_init
Definition at line 81 of file powerit.f.
References cht_opcmult(), cht_opcopy(), mntr_abort(), mntr_log(), mntr_logr(), mntr_tmr_add(), mntr_warn(), rprm_rp_get(), stepper_read(), and tst_dssum().
stepper_is_initialised()
logical function stepper_is_initialised
Check if module was initialised.
Returns
stepper_is_initialised
Definition at line 163 of file powerit.f.
References stepper_is_initialised().
stepper_read()
subroutine stepper_read (integer set_in)
Read restart files.
Parameters
[in] set_in restart set number
Definition at line 275 of file powerit.f.
References chkpt_restart_read(), chkpt_set_name(), io_init(), and mntr_log().
stepper_register()
subroutine stepper_register
Register power iteration module.
Note
This interface is called by tst_register
Definition at line 11 of file powerit.f.
References mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), mntr_tmr_add(), mntr_tmr_reg(), mntr_warn(), rprm_rp_reg(), rprm_sec_reg(), and rprm_sec_set_act().
stepper_vsolve()
subroutine stepper_vsolve
Renormalise vector and check convergence.
Note
This interface is defined in tstpr_solve
Remarks
This routine uses global scratch space SCRUZ
Definition at line 178 of file powerit.f.
References cht_opcmult(), cht_opcopy(), cht_opsub3(), mntr_log(), mntr_logr(), mntr_tmr_add(), outpost2(), stepper_write(), and tst_dssum().
stepper_write()
subroutine stepper_write
Write restart files.
Definition at line 318 of file powerit.f.
References chkpt_get_fset(), chkpt_restart_write(), chkpt_set_name(), io_init(), and mntr_log().