KTH framework for Nek5000 toolboxes; testing version: Generalised synthetic eddy method module
Generalised synthetic eddy method module
Framework for Nek5000 toolboxes » Toolbox » Utility module » Boundary condition module
Turbulence at inlet generated with divergence-free synthetic eddy method.
Files
file gSyEM.f
Generalised Synthetic Eddy Method.
Functions
subroutine gsem_register ()
Register gSyEM module.
subroutine gsem_init ()
Initilise gSyEM module.
logical function gsem_is_initialised ()
Check if module was initialised.
subroutine gsem_main
Main gSyEM interface.
subroutine gsem_rst_write
Create checkpoint.
subroutine gsem_rst_read
Read from checkpoint.
subroutine gsem_fam_setup ()
Generate family information.
subroutine gsem_prof_read (npoint, poff, rpos, umean, tke, dss)
Read profiles for all familes.
subroutine gsem_face_prof (nfam, poff, rpos, umean, tke, dss, iel, ifc, ifn, dist)
Generate profile information for given family face.
subroutine gsem_gen_elist (elist, neddy, nfam, ifinit)
Generate eddies from the list for a given family.
subroutine gsem_gen_eall (nfam)
Inital generation of all eddies (gsem_mode.eq.1) for a given family.
subroutine gsem_adv_eddy (nfam)
Advect/recycle eddies (gsem_mode.eq.1) for a given family.
subroutine gsem_gen_mall (nfam)
Inital generation of all modes (gsem_mode.eq.3) for a given family.
subroutine gsem_evolve ()
Time evolution of eddies.
subroutine gsem_iso (nfam)
Fill velocity array with eddies; ISO.
subroutine gsem_dairay (nfam)
Fill velocity array with eddies; Dairay.
Detailed Description
Turbulence at inlet generated with divergence-free synthetic eddy method.
This set of routines Poletto, Ruggero: Divergence free development of the synthetic eddy method in order to improve synthetic turbulence for embedded les simulations, PhD Thesis, The University of Manchester, 2015
Module interface:\n
Global interface list:
Interface provided:
gsem_register
gsem_init
gsem_main
Global interface dependency:
Interface required:
usr_gen_eddy
Module interface usage:\n
      subroutine userchk
      include 'TSTEP'           ! ISTEP
!     start framework
      if (istep.eq.0) call frame_start
!     monitor simulation
      call frame_monitor
!     add turbulent inflow
      call gsem_main
!     finalise framework
      if (istep.ge.nsteps.or.lastep.eq.1) then
         call frame_end
      endif
      return
      end
!======================================================================
      subroutine frame_usr_register
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
!     register modules
      call io_register
      call chkpt_register
      call gsem_register
      return
      end subroutine
!======================================================================
      subroutine frame_usr_init
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
!     initialise modules
      call chkpt_init
      call gsem_init
      return
      end subroutine
!======================================================================
      subroutine frame_usr_end
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
      return
      end subroutine
!======================================================================
      subroutine usr_gen_eddy(epos,eps,nfam,ifinit)
      implicit none
      include 'SIZE'
      include 'TSTEP'           ! pi
      include 'GSYEMD'
      ! argument list
      real epos(ldim)
      integer eps(ldim)
      integer nfam
      logical ifinit
      ! local variables
      real rho, theta, vrtmp(ldim)
      integer il
      real yp_cut
      parameter(yp_cut=0.45)
      ! functions
      real mth_ran_rng
!-----------------------------------------------------------------------
      rho = yp_cut*sqrt(mth_ran_rng(0.0,1.0))
      theta = mth_ran_rng(0.,2.0*pi)
      vrtmp(1) = rho*cos(theta)
      vrtmp(2) = rho*sin(theta)
      if (ifinit) then
         vrtmp(ldim) = mth_ran_rng(-gsem_bext(nfam),gsem_bext(nfam))
      else
         vrtmp(ldim) = -gsem_bext(nfam)
      endif
      ! rotate coordinates
      call mth_rot3da(epos,vrtmp,
     $        gsem_raxs(1,nfam),gsem_rang(nfam))
      do il=1,ldim
         rho = mth_ran_rng(0.0,1.0)
         if (rho.gt.0.5) then
            eps(il) = 1
         else
            eps(il) = -1
         endif
      enddo
      return
      end subroutine
!=======================================================================
Module parameters:\n
Global parameter list:
Parameters provided by sponge_box module (include file - SPONGRBD):
Varaible Type Runtime parameter Default value Description
gsem_mode integer _gsyem:mode 1 gSyEM mode
gsem_nfam integer _gsyem:nfam 1 Family number
gsem_neddy(il) integer _gsyem:neddy'il' 10 Numer of eddies of 'il' family
gsem_fambc(il) integer _gsyem:fambc'il' 10 Boundarry index of 'il' family
gsem_famasig(il) real _gsyem:famasig'il' 0.025 Max eddy size of 'il' family
gsem_famisig(il) real _gsyem:famisig'il' 0.025 Min eddy size of 'il' family
gsem_famdirx(il) real _gsyem:famdirx'il' 0.025 X normal component of 'il' family
gsem_famdiry(il) real _gsyem:famdiry'il' 0.025 X normal component of 'il' family
gsem_famdirz(il) real _gsyem:famdirz'il' 0.025 X normal component of 'il' family
Module parameter usage:\n
[_GSYEM]
mode = 1
nfam = 1
neddy01              = 10000
fambc01              = 1
famasig01            = 0.25
famisig01            = 0.0025
famdirx01            = 0.0
famdiry01            = 0.0
famdirz01            = 0.0
Function Documentation
gsem_adv_eddy()
subroutine gsem_adv_eddy (integer nfam)
Advect/recycle eddies (gsem_mode.eq.1) for a given family.
Parameters
[in] nfam family number
Definition at line 1324 of file gSyEM.f.
References gsem_gen_elist(), and mntr_logi().
gsem_dairay()
subroutine gsem_dairay (integer nfam)
Fill velocity array with eddies; Dairay.
Parameters
[in] nfam family number
Todo:
this routine is not done yet
Definition at line 1643 of file gSyEM.f.
gsem_evolve()
subroutine gsem_evolve
Time evolution of eddies.
Definition at line 1417 of file gSyEM.f.
References gsem_adv_eddy(), gsem_dairay(), and gsem_iso().
gsem_face_prof()
subroutine gsem_face_prof (integer nfam, integer, dimension(gsem_nfam_max+1) poff, real, dimension(gsem_npoint_max*gsem_nfam_max) rpos, real, dimension(gsem_npoint_max*gsem_nfam_max) umean, real, dimension(gsem_npoint_max*gsem_nfam_max) tke, real, dimension(gsem_npoint_max*gsem_nfam_max) dss, integer iel, integer ifc, integer ifn, real, dimension(lx1,lz1) dist)
Generate profile information for given family face.
Parameters
[in] nfam family number
[in] poff family profile array offset
[in] rpos position in a profile
[in] umean profile mean velocity
[in] tke profile turbulence kinetic energy
[in] dss profile dissipation rate
[in] iel local element number
[in] ifc face number
[in] ifn face position in gsem_sigma,gsem_umean,gsem_intn arrays
[in] dist point distance form the edge
Definition at line 1117 of file gSyEM.f.
References cmult(), col3(), and copy().
gsem_fam_setup()
subroutine gsem_fam_setup
Generate family information.
This routine generates family information including bounding box size, average coordinates, normal vector
Definition at line 648 of file gSyEM.f.
References cfill(), cmult(), ftovec(), gop(), gsem_face_prof(), gsem_prof_read(), math_etovec(), math_zbqlini(), mntr_abort(), mntr_log(), mntr_logi(), mntr_logr(), mth_rot3da(), and rzero().
gsem_gen_eall()
subroutine gsem_gen_eall (integer nfam)
Inital generation of all eddies (gsem_mode.eq.1) for a given family.
Parameters
[in] nfam family number
Definition at line 1289 of file gSyEM.f.
References gsem_gen_elist(), and mntr_logi().
gsem_gen_elist()
subroutine gsem_gen_elist (integer, dimension(neddy) elist, integer neddy, integer nfam, logical ifinit)
Generate eddies from the list for a given family.
Note
This routine redistributes data among mpi ranks
Parameters
[in] elist list of eddies to be geneated
[in] neddy number of eddies
[in] nfam family number
[in] ifinit intial distribution
Definition at line 1221 of file gSyEM.f.
References bcast(), copy(), icopy(), mntr_check_abort(), mntr_log(), and mntr_logi().
gsem_gen_mall()
subroutine gsem_gen_mall (integer nfam)
Inital generation of all modes (gsem_mode.eq.3) for a given family.
Parameters
[in] nfam family number
Definition at line 1374 of file gSyEM.f.
References bcast(), and mntr_logi().
gsem_init()
subroutine gsem_init
Initilise gSyEM module.
Note
This routine should be called in frame_usr_init
Definition at line 117 of file gSyEM.f.
References gsem_fam_setup(), gsem_gen_eall(), gsem_gen_mall(), gsem_rst_read(), izero(), mntr_abort(), mntr_check_abort(), mntr_mod_is_name_reg(), mntr_tmr_add(), mntr_warn(), rprm_rp_get(), rprm_rp_is_name_reg(), and rprm_sec_is_name_reg().
gsem_is_initialised()
logical function gsem_is_initialised
Check if module was initialised.
Returns
gsem_is_initialised
Definition at line 346 of file gSyEM.f.
gsem_iso()
subroutine gsem_iso (integer nfam)
Fill velocity array with eddies; ISO.
Parameters
[in] nfam family number
Todo:
This routine is way too slow due to work imbalance
Definition at line 1446 of file gSyEM.f.
References cfill(), cmult(), col2(), copy(), ftovec(), gop(), izero(), rzero(), subcol3(), vectof(), and vectof_add().
gsem_main()
subroutine gsem_main
Main gSyEM interface.
Definition at line 359 of file gSyEM.f.
References gsem_evolve(), gsem_rst_write(), and mntr_tmr_add().
gsem_prof_read()
subroutine gsem_prof_read (integer, dimension(gsem_nfam_max) npoint, integer, dimension(gsem_nfam_max+1) poff, real, dimension(gsem_npoint_max*gsem_nfam_max) rpos, real, dimension(gsem_npoint_max*gsem_nfam_max) umean, real, dimension(gsem_npoint_max*gsem_nfam_max) tke, real, dimension(gsem_npoint_max*gsem_nfam_max) dss)
Read profiles for all familes.
Parameters
[out] npoint number of points in profile per family
[out] poff family profile array offset
[out] rpos position in a profile
[out] umean profile mean velocity
[out] tke profile turbulence kinetic energy
[out] dss profile dissipation rate
Definition at line 1024 of file gSyEM.f.
References bcast(), io_file_freeid(), mntr_check_abort(), mntr_log(), mntr_log_local(), and rzero().
gsem_register()
subroutine gsem_register
Register gSyEM module.
Note
This routine should be called in frame_usr_register
Definition at line 14 of file gSyEM.f.
References mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), mntr_tmr_add(), mntr_tmr_is_name_reg(), mntr_tmr_reg(), mntr_warn(), rprm_rp_reg(), rprm_sec_reg(), and rprm_sec_set_act().
gsem_rst_read()
subroutine gsem_rst_read
Read from checkpoint.
In current inplementation all data is duplicated over all nodes, so only master performs I/O
Definition at line 509 of file gSyEM.f.
References bcast(), blank(), byte_close, byte_open, byte_read, byte_reverse, copy(), mntr_check_abort(), and mntr_log().
gsem_rst_write()
subroutine gsem_rst_write
Create checkpoint.
In current inplementation all data is duplicated over all nodes, so only master performs I/O
Definition at line 394 of file gSyEM.f.
References blank(), byte_close, byte_open, byte_write, chkpt_get_fset(), copy(), mntr_check_abort(), mntr_get_step_delay(), mntr_log(), mntr_tmr_add(), and nekgsync().