KTH framework for Nek5000 toolboxes; testing version: Inviscid surface terms
Inviscid surface terms
subroutine ausm_fluxfunction (ntot, nx, ny, nz, nm, fs, rl, ul, vl, wl, pl, al, tl, rr, ur, vr, wr, pr, ar, tr, flx, cpl, cpr)
Computes inviscid numerical surface flux from AUSM+ Riemann solver.
subroutine fluxes_full_field
Restrict and copy face data and compute inviscid numerical flux on face points.
Detailed Description
Function/Subroutine Documentation
subroutine ausm_fluxfunction (integer ntot, real, dimension(ntot) nx, real, dimension(ntot) ny, real, dimension(ntot) nz, real, dimension(ntot) nm, real, dimension(ntot) fs, real, dimension(ntot) rl, real, dimension(ntot) ul, real, dimension(ntot) vl, real, dimension(ntot) wl, real, dimension(ntot) pl, real, dimension(ntot) al, real, dimension(ntot) tl, real, dimension(ntot) rr, real, dimension(ntot) ur, real, dimension(ntot) vr, real, dimension(ntot) wr, real, dimension(ntot) pr, real, dimension(ntot) ar, real, dimension(ntot) tr, real, dimension(ntot,5) flx, real, dimension(ntot) cpl, real, dimension(ntot) cpr)
Computes inviscid numerical surface flux from AUSM+ Riemann solver.
Definition at line 48 of file ausm.f.
References i, invcol2(), and nz.
subroutine fluxes_full_field ()
Restrict and copy face data and compute inviscid numerical flux on face points.
Definition at line 8 of file surface_fluxes.f.
References face_state_commo(), faceu(), fillq(), inviscidbc(), inviscidflux(), lelt, and lz1.