KTH framework for Nek5000 toolboxes; testing version: Surface integrals due to boundary conditions
Surface integrals due to boundary conditions
subroutine inviscidbc (wminus, wbc, nstate)
Determining rind state for Dirichlet boundary conditions.
subroutine bcflux (flux, agradu, qminus)
Determining IGU contribution to boundary flux. 0 for artificial viscosity, and strictly interior for physical viscosity.
subroutine imqqtu_dirichlet (umubc, wminus, wplus)
umubc =
Detailed Description
Function/Subroutine Documentation
subroutine bcflux (real, dimension (nx1*nz1,2*ndim,nelt,toteq) flux, real, dimension(nx1*nz1,2*ndim,nelt,toteq) agradu, real, dimension(*) qminus)
Determining IGU contribution to boundary flux. 0 for artificial viscosity, and strictly interior for physical viscosity.
Definition at line 131 of file bc.f.
References a5adiabatic_wall(), copy(), and rzero().
subroutine imqqtu_dirichlet (real, dimension (nx1*nz1,2*ndim,nelt,toteq) umubc, real, dimension(nx1*nz1,2*ndim,nelt,nqq) wminus, real, dimension (nx1*nz1,2*ndim,nelt,nqq) wplus)
umubc =
Definition at line 41 of file diffusive_cmt.f.
References sub3(), and wallbc2().
subroutine inviscidbc (real, dimension(nx1*nz1,2*ndim,nelt,nstate) wminus, real, dimension(nx1*nz1,2*ndim,nelt,nstate) wbc, integer nstate)
Determining rind state for Dirichlet boundary conditions.
Definition at line 7 of file bc.f.
References exitti(), inflow(), lz1, nx, nz, outflow(), and wallbc_inviscid().