KTH framework for Nek5000 toolboxes; testing version: I/O tools
I/O tools
Framework for Nek5000 toolboxes » Toolbox » Input/output module
Input/Output simple tools.
Files
file io_tools.f
Set of I/O related tools for KTH modules.
file io_tools_block.f
Block data to initialise common block for I/O routines.
Functions
subroutine io_register ()
Register io tool module.
subroutine io_file_freeid (iunit, ierr)
Get free file unit number and store max unit value.
subroutine io_file_close ()
Close all opened files up to sotred max unit numer.
subroutine io_mfo_fname (fname, bname, prefix, ierr)
Generate file name according to nek rulles without opening the file.
subroutine io_mbyte_open (hname, ierr)
Open field file.
subroutine io_mbyte_close (ierr)
Close field file.
subroutine io_mfov (offs, lvx, lvy, lvz, lnx, lny, lnz, lnel, lnelg, lndim)
Write single vector to the file.
subroutine io_mfos (offs, lvs, lnx, lny, lnz, lnel, lnelg, lndim)
Write single scalar to the file.
subroutine io_mfis (offs, uf, lnx, lny, lnz, lnel, ifskip)
Read scalar filed from the file.
Detailed Description
Input/Output simple tools.
Set of I/O speciffic routines for toolbox
Module interface:
Global interface list:
Interface provided:
io_register
io_file_freeid
io_file_close
io_mfo_fname
io_mbyte_open
io_mbyte_close
io_mfov
io_mfos
io_mfiv
io_mfis
Module interface usage:
!======================================================================
      subroutine userchk
      include 'TSTEP'
       if (istep.eq.0) then
!     start framework
         call frame_start
      endif
!     monitor simulation
      call frame_monitor
!     finalise framework
      if (istep.eq.nsteps.or.lastep.eq.1) then
         call frame_end
      endif
      return
      end
!======================================================================
      subroutine frame_usr_register
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
      ! register modules
      call io_register
      return
      end subroutine
!======================================================================
      subroutine frame_usr_init
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
      ! initialise modules
      return
      end subroutine
!======================================================================
      subroutine frame_usr_end
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
      ! finlise modules
      return
      end subroutine
!======================================================================
Function Documentation
io_file_close()
subroutine io_file_close ()
Close all opened files up to sotred max unit numer.
See also
io_file_freeid
Definition at line 81 of file io_tools.f.
io_file_freeid()
subroutine io_file_freeid (integer iunit, integer ierr)
Get free file unit number and store max unit value.
Parameters
[out] iunit file unit
[out] ierr error mark
See also
io_file_close
Definition at line 47 of file io_tools.f.
io_mbyte_close()
subroutine io_mbyte_close (integer ierr)
Close field file.
This routine closes the file (serial or parallel depending on parmeter set by io_init) using Nek5000 C routines.
Parameters
[out] ierr error mark
Definition at line 232 of file io_tools.f.
References byte_close, and byte_close_mpi().
io_mbyte_open()
subroutine io_mbyte_open (character*132 hname, integer ierr)
Open field file.
This routine opens the file (serial or parallel depending on parmeter set by io_init) using Nek5000 C routines. I need it for a number of tools writing restart files that do not directly stick to the numbering scheme used in mfo_open_files.
Parameters
[in] hname file name
[out] ierr error mark
Definition at line 182 of file io_tools.f.
References addfid(), byte_open, byte_open_mpi(), mntr_error(), and mntr_log().
io_mfis()
subroutine io_mfis (integer*8 offs, real, dimension(lnx*lny*lnz,lnel) uf, integer lnx, integer lny, integer lnz, integer lnel, logical ifskip)
Read scalar filed from the file.
This is version of mfi_gets that does not perform interpolation and allows to specify element size.
Parameters
[in,out] offs offset of global vector beginning
[out] uf scalar field
[in] lnx,lny,lnz element size
[in] lnel number of elements
[in] ifskip reading flag (for non-mpi formats)
Remarks
This routine uses global scratch space VRTHOV and SCRNS
Definition at line 666 of file io_tools.f.
References bcast(), byte_read, byte_read_mpi(), byte_reverse, byte_reverse8, byte_set_view(), copy(), copy4r(), csend(), err_chk(), lelt, lim_chk(), ly1, lz1, mntr_abort(), msgwait(), nekgsync(), and rzero().
io_mfo_fname()
subroutine io_mfo_fname (character*132 fname, character*132 bname, character*3 prefix, integer ierr)
Generate file name according to nek rulles without opening the file.
It is a modified version of mfo_open_files from prepost.f but without equivalence and file opening part. I split file name generation and file opening as different tools can require this.
Parameters
[out] fname file name
[in] bname base name
[in] prefix prefix
[out] ierr error mark
Definition at line 109 of file io_tools.f.
References mntr_error().
io_mfos()
subroutine io_mfos (integer*8 offs, real, dimension(lnx,lny,lnz,lnel) lvs, integer lnx, integer lny, integer lnz, integer lnel, integer lnelg, integer lndim)
Write single scalar to the file.
This routine is based on mfo_outfld but can be used for writing 2D sections of 3D simulation.
Parameters
[in,out] offs offset of global vector beginning
[in] lvs scalar to write
[in] lnx,lny,lnz element dimensions
[in] lnel local number of field elements
[in] lnelg global number of filed elements
[in] lndim written domain dimension
Remarks
This routine uses global scratch space SCRUZ.
Definition at line 375 of file io_tools.f.
References byte_set_view(), map2reg_2di_e(), map2reg_3di_e(), mfo_outs(), and mntr_warn().
io_mfov()
subroutine io_mfov (integer*8 offs, real, dimension(lnx,lny,lnz,lnel) lvx, real, dimension(lnx,lny,lnz,lnel) lvy, real, dimension(lnx,lny,lnz,lnel) lvz, integer lnx, integer lny, integer lnz, integer lnel, integer lnelg, integer lndim)
Write single vector to the file.
This routine is based on mfo_outfld but can be used for writing 2D sections of 3D simulation.
Parameters
[in,out] offs offset of global vector beginning
[in] lvx,lvy,lvz vector to write
[in] lnx,lny,lnz element dimensions
[in] lnel local number of filed elements
[in] lnelg global number of filed elements
[in] lndim written domain dimension
Remarks
This routine uses global scratch space SCRUZ.
Definition at line 273 of file io_tools.f.
References byte_set_view(), lelt, map2reg_2di_e(), map2reg_3di_e(), mfo_outv(), and mntr_warn().
io_register()
subroutine io_register ()
Register io tool module.
Note
This routine should be called in frame_usr_register
Definition at line 11 of file io_tools.f.
References mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), and mntr_warn().