KTH framework for Nek5000 toolboxes; testing version: Time stepper routines
Time stepper routines
Framework for Nek5000 toolboxes » Toolbox » Tools module
Time stepper for Nek5000.
Modules
Arnoldi algorithm using parpack
Arnoldi algorithm with PARPACK.
Power itertion routines
Power iteration submodule.
Files
file time_stepper.f
Set of subroutines to use time steppers for power iterations or solution of eigenvalue problem with Arnoldi algorithm.
Functions
subroutine tstpr_param_in (fid)
Read parameters for time stepper and call suitable param_reader of required submodule.
subroutine tstpr_param_out (fid)
Write parameters for time stepper and call suitable param_writer of required submodule.
subroutine tstepper_main
Main time stepper interface.
subroutine tstpr_init
Initialise time stepper and call suitable stepper_vinit of required submodule.
subroutine tstpr_solve
Control time stepper after every nek5000 step and call suitable stepper_vsolve of required submodule.
subroutine tstpr_end
Finalise time stepper.
subroutine tstpr_dssum
Average velocity and temperature at element faces.
Detailed Description
Time stepper for Nek5000.
Warning
This module is not upgraded to stable Nek5000 relese yet
This module implements time stepper method for linear solver in Nek5000 using userchk interface. It allows to perform number of constant lenght cycles providing the result vector to the submodule. There are two possible submodules: power iteration and spectra calculation using Arnoldi algorithm implemented in PARPACK. The initial condition for the next stepping cycle is provided by submodule. Three stepper modes are supported: direct, adjoint, direct+adjoint.
Module interface:
Global interface list:
Interface provided:
tstepper_main
Global interface dependency:
Interface required:
stepper_param_in(iunit)
stepper_param_out(iunit)
stepper_vinit
stepper_solve
Module interface usage:
      subroutine userchk
      include 'TSTEP'
      if (istep.eq.0) then
!     initialise runtime parameters
         call tstpr_param_get
      endif
!     main time stepper interface
      call tstepper_main
      return
      end
Module parameters:
Global parameter list:
Parameters provided by time stepper module (include file - TIME_STEPPERD):
TSTMODE: (integer)
0 : no time stepper
1 : direct mode
2 : adjoint mode
3 : direct+adjoint mode (initial optimal condition)
TSTSTEP : (integer) frequency of calling stepper_vsolve (number of time steps)
TSTCMAX : (integer) maximal number of stepper cycles (meaning of this parameter depends on the applied package; arnoldi vs power iterations)
TSTTOL : (real) convergence tolerance (e.g. PARPACK tolerance for Ritz values)
TSTIFUZAWA : (logical) first step run with UZAWA
Global parameter dependency:
Parameters required by time stepper module:
CONHT (for conjugated heat transfer):
CHCST_SC, CHCFF_V, CHCFF_T : velocity and temperature scaling factors
CHGRX, CHGRY, CHGRZ : gravitational acceleration
CHRA, CHPR : Rayleight and Prandtl numbers
Nek5000 PARAM array
PARAM(12) - time step dt
Nek5000 number of include files;
Todo:
Finish parameter dependency
Module parameter usage:
&tstepper
 tstmode=          1,
 tststep=         40,
 tstcmax=        200,
 tsttol=  1.0000000000000000e-06 ,
 tstifuzawa=t,
 /
Function Documentation
subroutine tstepper_main ()
Main time stepper interface.
Note
This routine should be called in userchk
Definition at line 112 of file time_stepper.f.
References tstpr_init(), and tstpr_solve().
subroutine tstpr_dssum ()
Average velocity and temperature at element faces.
Definition at line 485 of file time_stepper.f.
References col2(), dssum(), opcolv(), and opdssum().
subroutine tstpr_end ()
Finalise time stepper.
Definition at line 461 of file time_stepper.f.
subroutine tstpr_init ()
Initialise time stepper and call suitable stepper_vinit of required submodule.
Definition at line 136 of file time_stepper.f.
References exitt(), rzero(), and stepper_vinit().
subroutine tstpr_param_in (integer fid)
Read parameters for time stepper and call suitable param_reader of required submodule.
Parameters
[in] fid file unit
Note
This routine should be called in runprm_in
Todo:
Check iostat value for missing namelist in the file
See also
readers_writers_page
Definition at line 17 of file time_stepper.f.
References bcast(), err_chk(), and stepper_param_in().
subroutine tstpr_param_out (integer fid)
Write parameters for time stepper and call suitable param_writer of required submodule.
Parameters
[in] fid file unit
Note
This routine should be called in runprm_out
See also
readers_writers_page
Definition at line 80 of file time_stepper.f.
References err_chk(), and stepper_param_out().
subroutine tstpr_solve ()
Control time stepper after every nek5000 step and call suitable stepper_vsolve of required submodule.
Definition at line 297 of file time_stepper.f.
References rzero(), stepper_vsolve(), and tstpr_end().