KTH framework for Nek5000 toolboxes; testing version: Volume integral for viscous fluxes
Volume integral for viscous fluxes
subroutine viscous_cmt (e, eq)
Volume integral for diffusive terms. Compute and store it for one element. Store faces of for IGU.
Detailed Description
Function/Subroutine Documentation
subroutine viscous_cmt (integer e, integer eq)
Volume integral for diffusive terms. Compute and store it for one element. Store faces of for IGU.
Definition at line 8 of file eqnsolver_cmt.f.
References agradu(), diffh2graduf(), half_iku_cmt(), lelt, lz1, and rzero().