KTH framework for Nek5000 toolboxes; testing version: Spatial average routines.
Spatial average routines.
Framework for Nek5000 toolboxes » Toolbox » Driver module
Set of routines for global spatial average of elements.
Files
file avg_spt.f
Set of subroutines for global spatial averaging.
Functions
subroutine avgs_init ()
Initialise spatial averaging of elements.
subroutine avgs_end ()
Finalise spatial averaging of elements.
subroutine avgs_init_local (ctrs, cell, ninseg, ind, ifseg, lctrs1, lctrs2, nseg)
Generate local element mapping.
subroutine avgs_init_coord (nseg)
Reshuffle coordinate arrays.
Detailed Description
Set of routines for global spatial average of elements.
Warning
This module is not upgraded to stable Nek5000 relese yet
Set of routines for global spatial average of elements generating LDIM-1 or LDIM-2 fields.
Module interface:
Global interface list:
Interface provided:
avgs_init
avgs_end
Function Documentation
subroutine avgs_end ()
Finalise spatial averaging of elements.
Definition at line 109 of file avg_spt.f.
subroutine avgs_init ()
Initialise spatial averaging of elements.
This routine performs initialistion of the satial averaging tool. It generated local and global mapping of elements depending on the original and averaged field dimensions.
Remarks
This routine uses global scratch space SCRNS, SCRVH, SCRUZ.
Definition at line 15 of file avg_spt.f.
References avgs_init_coord(), avgs_init_local(), lelt, ly1, lz1, and stat_comm_map().
subroutine avgs_init_coord (integer nseg)
Reshuffle coordinate arrays.
Generate local coordinates of the averaged field. I assume all elements in the set have the same coordinates, so I just pick one of them.
Parameters
[in] nseg number of segments
Definition at line 333 of file avg_spt.f.
References copy(), err_chk(), icopy(), ifill(), io_file_freeid(), and lelt.
subroutine avgs_init_local (real, dimension(lctrs1,lctrs2) ctrs, integer, dimension(lctrs2) cell, integer, dimension(lctrs2) ninseg, integer, dimension(lctrs2) ind, logical, dimension(lctrs2) ifseg, integer lctrs1, integer lctrs2, integer nseg)
Generate local element mapping.
Generate local element mapping based on the user provided element centre and diagonal using multi-dimensional sorting.
Parameters
[out] ctrs sorted element centres and diameters
[out] cell local element numberring
[out] ninseg number of elements in segment
[out] ind sorting index
[out] ifseg segment borders
[in] lctrs1 array size
[in] lctrs2 array size
[out] nseg segment number
Definition at line 172 of file avg_spt.f.
References exitt(), ifill(), io_file_freeid(), iswap_ip(), and tuple_sort().