KTH framework for Nek5000 toolboxes; testing version: Checkpointing for DNS and linear simulations
Checkpointing for DNS and linear simulations
Toolbox » Input/output module for KTH nek5000 platform » Checkpointing routines
Multi-file checkopinting for DNS and linear simulations.
Files
file chkpt_dns_lin.f
Set of multi-file checkpoint routines for DNS and linear.
Functions
subroutine chkpt_init
Initialise multi-file checkpoint routines.
subroutine chkpt_fname (fname, bname, prefix, nset, ierr)
Generate restart file names.
subroutine chkpt_read ()
Read full file restart set.
subroutine chkpt_write ()
Write full file restart set.
subroutine restart_save_pert (iosave, save_size, nfldi)
Save checkpoint variables in a single set of files.
subroutine restart_pert (nfiles, nfilstart)
Load checpoint variables from single set of files.
subroutine mfi_pert (fname, ifile)
Load checkpoint variables from single file.
subroutine axis_interp_ic_full_pres (pm1)
Map loaded variables from velocity to axisymmetric mesh.
subroutine map_pm1_to_pr_pert (pm1, ifile)
Map loaded pressure to the pressure mesh.
Detailed Description
Multi-file checkopinting for DNS and linear simulations.
In the case of multistep time-integration method one needs data from NBDINP timestep. I use standard full_restart and full_restart_save subroutines. There are four 'rs8...' reatart files saved in double precission. Only .f format is supported. In any case two sets of restart files (1-4;5-8) are created.
Attention
To make this varsion to work correctly mod(total_number_of_steps,CHKPTSTEP).ge.NBDINP Otherwise last checkpoint will not be complete.
Module interface:
This module provides following interfaces to checkpoint:
chkpt_init
chkpt_read
chkpt_write
Module parameters:
Global module dependency:
Parameters required by dns_lin module:
CHKPOINTD:
IFCHKPTRST - if restart
CHKPTSTEP - checkpiont dump frequency (number of time steps)
Nek5000 PARAM array
PARAM(66) - write format
PARAM(67) - read format
Function Documentation
subroutine axis_interp_ic_full_pres (real, dimension(lx1,ly1,lz1,lelv) pm1)
Map loaded variables from velocity to axisymmetric mesh.
Parameters
[in] pm1 pressure loaded form the file
Note
This is version of axis_interp_ic taking into account fact pressure does not have to be written on velocity mesh.
Remarks
This routine uses global scratch space CTMP0.
Definition at line 702 of file chkpt_dns_lin.f.
References copy(), and mxm().
subroutine chkpt_fname (character*80, dimension(chkptnrsf) fname, character*132 bname, character*3 prefix, integer nset, integer ierr)
Generate restart file names.
Parameters
[out] fname restart file name
[in] bname base name
[in] prefix prefix
[in] nset file set number
[out] ierr error mark
Definition at line 170 of file chkpt_dns_lin.f.
References io_mfo_fname().
subroutine chkpt_init ()
Initialise multi-file checkpoint routines.
Note
This interface is defined in checkpoint_main
Definition at line 16 of file chkpt_dns_lin.f.
References bcast(), chkpt_fname(), err_chk(), exitt(), and io_file_freeid().
subroutine chkpt_read ()
Read full file restart set.
Note
This interface is defined in checkpoint_main
Definition at line 223 of file chkpt_dns_lin.f.
References bcast(), chcopy(), restart(), and restart_pert().
subroutine chkpt_write ()
Write full file restart set.
Note
This interface is defined in checkpoint_main.
This is version of full_restart_save routine. In additional file it saves the file set number to allow for automatic restart.
Definition at line 286 of file chkpt_dns_lin.f.
References err_chk(), io_file_freeid(), and restart_save_pert().
subroutine map_pm1_to_pr_pert (real, dimension(lx1*ly1*lz1,lelv) pm1, integer ifile)
Map loaded pressure to the pressure mesh.
Parameters
[in] pm1 pressure loaded form the file
[in] ifile field pointer (nonlinear, mhd, perturbation; at the same time file number)
Note
This is version of map_pm1_to_pr including perturbation
Definition at line 776 of file chkpt_dns_lin.f.
References copy(), and map12().
subroutine mfi_pert (character*132 fname, integer ifile)
Load checkpoint variables from single file.
Parameters
[in] fname file name
[in] ifile field pointer (nonlinear, mhd, perturbation; at the same time file number)
Note
This is version of mfi including perturbation field.
Remarks
This routine uses global scratch space SCRNS, SCRCG.
Definition at line 523 of file chkpt_dns_lin.f.
References axis_interp_ic_full_pres(), byte_close, byte_close_mpi(), byte_set_view(), err_chk(), lelt, ly1, lz1, map_pm1_to_pr_pert(), mfi_gets(), mfi_getv(), and mfi_prepare().
subroutine restart_pert (integer nfiles, integer nfilstart)
Load checpoint variables from single set of files.
Parameters
[in] nfiles last file number
[in] nfilstart first file number
Note
This is version of restart routine. It excludes .fld format and adds lower loop bound to allow for ifbase=.false.
Definition at line 472 of file chkpt_dns_lin.f.
References exitt(), mfi_pert(), setup_convect(), and sioflag().
subroutine restart_save_pert (integer iosave, integer save_size, integer nfldi)
Save checkpoint variables in a single set of files.
Parameters
[in] iosave
[in] save_size
[in] nfldi
Note
This is version of restart routine. It
Definition at line 361 of file chkpt_dns_lin.f.
References outpost2().