KTH framework for Nek5000 toolboxes; testing version: Volume integral for inviscid fluxes
Volume integral for inviscid fluxes
subroutine convective_cmt (e, eq)
Convective volume terms formed and differentiated^T here.
subroutine evaluate_dealiased_conv_h (e, eq)
Convective pointwise flux function on fine grid.
subroutine evaluate_aliased_conv_h (e, eq)
subroutine flux_div_integral_dealiased (e, eq)
for equation eq, element e
Detailed Description
Function/Subroutine Documentation
subroutine convective_cmt (integer e, integer eq)
Convective volume terms formed and differentiated^T here.
Definition at line 174 of file eqnsolver_cmt.f.
References copy(), evaluate_aliased_conv_h(), evaluate_dealiased_conv_h(), flux_div_integral_aliased(), flux_div_integral_dealiased(), n, and rzero().
subroutine evaluate_aliased_conv_h (integer e, integer eq)
Definition at line 265 of file eqnsolver_cmt.f.
References add2col2(), col2(), copy(), exitt(), and n.
subroutine evaluate_dealiased_conv_h (integer e, integer eq)
Convective pointwise flux function on fine grid.
Definition at line 201 of file eqnsolver_cmt.f.
References add2col2(), col2(), copy(), exitt(), intp_rstd(), and n.
subroutine flux_div_integral_dealiased (integer e, integer eq)
for equation eq, element e
Definition at line 320 of file eqnsolver_cmt.f.
References add2col2(), get_dgl_ptr(), intp_rstd(), local_grad2_t(), local_grad3_t(), rzero(), and sub2().