KTH framework for Nek5000 toolboxes; testing version: Jacobians for viscous fluxes
Jacobians for viscous fluxes
subroutine agradu (flux, du, e, eq)
flux = dU = dU
Detailed Description
Function/Subroutine Documentation
subroutine agradu (real, dimension(nx1*ny1*nz1,ndim) flux, real, dimension(nx1*ny1*nz1,toteq,ndim) du, integer e, integer eq)
flux = dU = dU
and . and for EVM
, and . for Navier-Stokes
Definition at line 107 of file diffusive_cmt.f.
References col2(), fluxj_evm(), and fluxj_ns().