KTH framework for Nek5000 toolboxes; testing version: Arnoldi algorithm using parpack
Arnoldi algorithm using parpack
Framework for Nek5000 toolboxes » Toolbox » Tools module » Time stepper routines
Arnoldi algorithm with PARPACK.
Files
file arnoldi_arpack.f
Set of subroutines to solve eigenvalue problem with Arnoldi algorithm using PARPACK/ARPACK.
file arnoldi_arpack_io.f
Set of checkpoint routines for arnoldi_arpack module.
Functions
subroutine stepper_param_in (fid)
Read runtime parameters for arnoldi_arpack.
subroutine stepper_param_out (fid)
Write runtime parameters for arnoldi_arpack.
subroutine stepper_vinit
Initialise arnoldi_arpack.
subroutine stepper_vsolve
Create Krylov space, get Ritz values and restart stepper phase.
subroutine arn_esolve
ARPACK postprocessing.
subroutine arn_end
Finalise arnoldi.
subroutine arn_naupd
Interface to pdnaupd.
subroutine arn_rst_save
Take care of savings for restart.
subroutine arn_rst_read
Read from checkpoints.
subroutine arn_write_par (prefix)
Write procesor independent data.
subroutine mfo_arnp
Write procesor independent variables.
subroutine arn_read_par (prefix)
Read procesor independent data.
subroutine mfi_arnp
Read procesor independent variables.
subroutine mfo_arnv (prefix)
Write procesor dependent data (long vectors)
subroutine mfi_arnv (prefix)
Read procesor dependent data (long vectors)
subroutine mfo_singlev (ioflds, nout, offs0, stride, strideB, ur1, ur2, ur3, vect)
Write single Krylov vector to the file.
subroutine mfi_singlev (iofldr, offs0, stride, strideB, ur1, ur2, ur3, vect)
Read single Krylov vector from the file.
Detailed Description
Arnoldi algorithm with PARPACK.
Warning
This module is not upgraded to stable Nek5000 relese yet
Description of the method can be found in [2] [3]
Module interface:
Global interface list:
Interface provided to tstepper:
stepper_param_in
stepper_param_out
stepper_vinit
stepper_solve
Module parameters:
Global parameter list:
Parameters provided by arnoldi_arpack submodule (include file - ARNOLDI_ARPACKD):
ARNKRYLOV : (integer) size of Krylov space
ARNEGV : (integer) number of calculated eigenvalues
ARNISTART : (integer) checkpoint file number for restart (reading)
ARNISTOP : (integer) checkpoint file number for saving data
Global parameter dependency:
Parameters required by arnoldi_arpack submodule:
CHKPOINTD:
IFCHKPTRST : if restart
CHKPTSTEP - checkpiont dump frequency (number of time steps)
TIME_STEPPERD:
TSTMODE :
0 : no arnoldi
1 : direct mode
2 : adjoint mode
3 : initial optimal condition
TSTSTEP : frequency of calling arn_vsolve (number of time steps)
TSTCMAX : maximal number of arnoldi cycles
TSTTOL : PARPACK tolerance for Ritz values
CONHT (for conjugated heat transfer):
CHCST_SC, CHCFF_V, CHCFF_T : velocity and temperature scaling factors
CHGRX, CHGRY, CHGRZ : gravitational acceleration
CHRA, CHPR : Rayleight and Prandtl numbers
Nek5000 PARAM array
PARAM(66) - write format
PARAM(67) - read format
Module parameter usage:
&arpack
 arnkrylov=        100,
 arnegv=         10,
 arnistart=          1,
 arnistop=          2,
 /
Two possible modes are supported:
direct: A*x = lambda*x
inverse: A*x = lambda*M*x, M-mass matrix defining inner product
Inverse mode is preferred as it takes into account inner product Simulation with temperature or passive scalars has to be performed in inverse mode due to speciffic inner product.
ARPACK_DIRECT preprocessing switch between direct and inverse mode.
Attention
This submodule has its own checkpointing routines.
Todo:
This submodule contains binary tar file with modified (restart added) version of PARPACK. This binary file in git is not good idea. Repalce with separate repository for Parpack added by sub.module.
Function Documentation
arn_end()
subroutine arn_end ()
Finalise arnoldi.
Definition at line 549 of file arnoldi_arpack.f.
arn_esolve()
subroutine arn_esolve ()
ARPACK postprocessing.
Definition at line 387 of file arnoldi_arpack.f.
References copy(), err_chk(), exitt(), io_file_freeid(), and outpost2().
arn_naupd()
subroutine arn_naupd ()
Interface to pdnaupd.
Definition at line 571 of file arnoldi_arpack.f.
References col2(), col3(), copy(), exitt(), and tstpr_dssum().
arn_read_par()
subroutine arn_read_par (character*3 prefix)
Read procesor independent data.
Parameters
[in] prefix prefix
Definition at line 217 of file arnoldi_arpack_io.f.
References bcast(), byte_close, err_chk(), io_mfo_fname(), mfi_arnp(), and nekgsync().
arn_rst_read()
subroutine arn_rst_read ()
Read from checkpoints.
Definition at line 45 of file arnoldi_arpack_io.f.
References arn_read_par(), and mfi_arnv().
arn_rst_save()
subroutine arn_rst_save ()
Take care of savings for restart.
Definition at line 9 of file arnoldi_arpack_io.f.
References arn_write_par(), and mfo_arnv().
arn_write_par()
subroutine arn_write_par (character*3 prefix)
Write procesor independent data.
Parameters
[in] prefix prefix
Definition at line 71 of file arnoldi_arpack_io.f.
References byte_close, err_chk(), io_mfo_fname(), mfo_arnp(), and nekgsync().
mfi_arnp()
subroutine mfi_arnp ()
Read procesor independent variables.
Definition at line 431 of file arnoldi_arpack_io.f.
References blank(), byte_read, byte_reverse, copy(), and exitt().
mfi_arnv()
subroutine mfi_arnv (character*3 prefix)
Read procesor dependent data (long vectors)
Parameters
[in] prefix prefix
Remarks
This routine uses global scratch space SCRNS, SCRUZ
Definition at line 683 of file arnoldi_arpack_io.f.
References byte_close, byte_close_mpi(), err_chk(), io_mfo_fname(), lelt, ly1, lz1, mfi_prepare(), mfi_singlev(), and nekgsync().
mfi_singlev()
subroutine mfi_singlev (integer iofldr, integer*8 offs0, integer*8 stride, integer*8 strideB, real, dimension(lx1*lx1*lx1*lelt) ur1, real, dimension(lx1*lx1*lx1*lelt) ur2, real, dimension(lx1*lx1*lx1*lelt) ur3, real, dimension(lvas) vect)
Read single Krylov vector from the file.
Parameters
[in,out] iofldr Vector counter
[in] offs0 global file offset (header +...)
[in] stride single vector length
[in] strideB space saved for processes with lower nid
[in] ur1,ur2,ur3 input arrays
[out] vect Krylov vector
Remarks
This routine uses global scratch space SCRNS
Definition at line 855 of file arnoldi_arpack_io.f.
References byte_set_view(), copy(), lelt, ly1, lz1, mfi_gets(), and mfi_getv().
mfo_arnp()
subroutine mfo_arnp ()
Write procesor independent variables.
Definition at line 139 of file arnoldi_arpack_io.f.
References blank(), byte_write, copy(), get_bytesw_write(), and set_bytesw_write().
mfo_arnv()
subroutine mfo_arnv (character*3 prefix)
Write procesor dependent data (long vectors)
Parameters
[in] prefix prefix
Remarks
This routine uses global scratch space SCRUZ
Definition at line 537 of file arnoldi_arpack_io.f.
References byte_close, byte_close_mpi(), err_chk(), io_mfo_fname(), lelt, mfo_singlev(), and mfo_write_hdr().
mfo_singlev()
subroutine mfo_singlev (integer ioflds, integer nout, integer*8 offs0, integer*8 stride, integer*8 strideB, real, dimension(lxo*lxo*lxo*lelt) ur1, real, dimension(lxo*lxo*lxo*lelt) ur2, real, dimension(lxo*lxo*lxo*lelt) ur3, real, dimension(lvas) vect)
Write single Krylov vector to the file.
Parameters
[in,out] ioflds Vector counter
[in] nout local number of elements to write
[in] offs0 global file offset (header +...)
[in] stride single vector length
[in] strideB space saved for processes with lower nid
[in] ur1,ur2,ur3 output arrays
[in] vect Krylov vector
Definition at line 801 of file arnoldi_arpack_io.f.
References byte_set_view(), copy(), lelt, mfo_outs(), and mfo_outv().
stepper_param_in()
subroutine stepper_param_in (integer fid)
Read runtime parameters for arnoldi_arpack.
Parameters
[in] fid file unit
Note
This interface is defined in tstpr_param_in
Todo:
Check iostat value for missing namelist in the file
See also
readers_writers_page
Definition at line 22 of file arnoldi_arpack.f.
References bcast(), and err_chk().
stepper_param_out()
subroutine stepper_param_out (integer fid)
Write runtime parameters for arnoldi_arpack.
Parameters
[in] fid file unit
Note
This interface is defined in tstpr_param_out
See also
readers_writers_page
Definition at line 78 of file arnoldi_arpack.f.
References err_chk().
stepper_vinit()
subroutine stepper_vinit ()
Initialise arnoldi_arpack.
Note
This interface is defined in tstpr_init
Definition at line 106 of file arnoldi_arpack.f.
References arn_naupd(), arn_rst_read(), col3(), copy(), exitt(), izero(), logfil, mnaitr, mnapps, mnaup2, mnaupd, mneupd, mngets, ndigit, and rzero().
stepper_vsolve()
subroutine stepper_vsolve ()
Create Krylov space, get Ritz values and restart stepper phase.
Note
This interface is defined in tstpr_solve
Definition at line 319 of file arnoldi_arpack.f.
References arn_end(), arn_esolve(), arn_naupd(), arn_rst_save(), col3(), copy(), and exitt().