KTH framework for Nek5000 toolboxes; testing version: Sponge_box module
Sponge_box module
Framework for Nek5000 toolboxes » Toolbox » Utility module » Forcing module
Sponge/fringe for simple box mesh.
Files
file spongebx.f
Sponge/fringe for simple box mesh.
Functions
subroutine spng_register ()
Register sponge_box module.
subroutine spng_init (lvx, lvy, lvz)
Initilise sponge_box module.
logical function spng_is_initialised ()
Check if module was initialised.
subroutine spng_forcing (ffx, ffy, ffz, ix, iy, iz, ieg)
Get sponge forcing.
Detailed Description
Sponge/fringe for simple box mesh.
Set of routines to apply sponge (fringe in periodic domains) for simple box mesh. It calculates a volume forcing
with and beeing non-negative sponge/fringe function, constant in time reference velocity field and current velocity field respectively. 1-dimensional sponge funcion is definde as
where:
- sponge strenght,
- step function mth_stepf,
- left and right box boundaries,
- left and right sponge section width,
- left and right sponge section drop/rise width.
In our implementation each dimension is treated separately and the final 3-dimensional function takes a maximum value of its 1-dimensional components. and can be set to zero.
Module interface:
Global interface list:
Interface provided:
spng_register
spng_init
spng_forcing
spng_is_initialised
Module interface usage:
      subroutine userf  (ix,iy,iz,ieg)
      include 'SIZE'
      include 'NEKUSE'          ! FF[XYZ]
      include 'PARALLEL'        ! GLLEL
      include 'SOLN'            ! V[XYZ]
      ffx = 0.0
      ffy = 0.0
      ffz = 0.0
!     add sponge
      call spng_forcing(ffx,ffy,ffz,ix,iy,iz,ieg)
      return
      end
!-----------------------------------------------------------------------
     subroutine userchk
      implicit none
      include 'SIZE'
      include 'TSTEP'
!     start framework
      if (istep.eq.0) call frame_start
!     monitor simulation
      call frame_monitor
!     finalise framework
      if (istep.eq.nsteps.or.lastep.eq.1) then
         call frame_end
      endif
      return
      end
!======================================================================
      subroutine frame_usr_register
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
!     register modules
      call spng_register
      return
      end subroutine
!======================================================================
      subroutine frame_usr_init
      implicit none
      include 'SIZE'
      include 'FRAMELP'
      ! local variables
      integer nn
      real vtmp(lx1*ly1*lz1*lelt,ldim)
      common /ctmp1/ vtmp
!-----------------------------------------------------------------------
!     initialise modules
      nn = lx1*ly1*lz1*lelt*ldim
      call rzero(vtmp,nn)
      call spng_init(vtmp(1,1),vtmp(1,2),vtmp(1,ndim))
      return
      end subroutine
!======================================================================
      subroutine frame_usr_end
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
      return
      end subroutine
!======================================================================
Module parameters:
Global parameter list:
Parameters provided by sponge_box module (include file - SPONGRBD):
Varaible Type Runtime parameter Default value Description
spng_str real _spongebx:strenght 0.0 sponge strength
spng_wl(1) real _spongebx:widthlx 0.0 sponge left section width; dimension X
spng_wl(2) real _spongebx:widthly 0.0 sponge left section width; dimension Y
spng_wl(3) real _spongebx:widthlz 0.0 sponge left section width; dimension Z
spng_wr(1) real _spongebx:widthrx 0.0 sponge right section width; dimension X
spng_wr(2) real _spongebx:widthry 0.0 sponge right section width; dimension Y
spng_wr(3) real _spongebx:widthrz 0.0 sponge right section width; dimension Z
spng_dl(1) real _spongebx:droplx 0.0 sponge left drop/rise section width; dimension X
spng_dl(2) real _spongebx:droply 0.0 sponge left drop/rise section width; dimension Y
spng_dl(3) real _spongebx:droplz 0.0 sponge left drop/rise section width; dimension Z
spng_dr(1) real _spongebx:droprx 0.0 sponge right drop/rise section width; dimension X
spng_dr(2) real _spongebx:dropry 0.0 sponge right drop/rise section width; dimension Y
spng_dr(3) real _spongebx:droprz 0.0 sponge right drop/rise section width; dimension Z
Module parameter usage:
[_SPONGEBX]
strength = 1.0
widthlx = 4.0
widthly = 0.0
widthlz = 0.0
widthrx = 4.0
widthry = 0.0
widthrz = 0.0
droplx = 2.0
droply = 0.0
droplz = 0.0
droprx = 2.0
dropry = 0.0
droprz = 0.0
Function Documentation
spng_forcing()
subroutine spng_forcing (real ffx, real ffy, real ffz, integer ix, integer iy, integer iz, integer ieg)
Get sponge forcing.
Parameters
[in,out] ffx,ffy,ffz forcing; x,y,z component
[in] ix,iy,iz GLL point index
[in] iel global element number
Definition at line 337 of file spongebx.f.
spng_init()
subroutine spng_init (real, dimension(lx1*ly1*lz1*lelv) lvx, real, dimension(lx1*ly1*lz1*lelv) lvy, real, dimension(lx1*ly1*lz1*lelv) lvz)
Initilise sponge_box module.
Parameters
[in] lvx,lvy,lvz velocity field to be stored as reference field
Note
This routine should be called in userchk during first step after call to frame_rparam
Remarks
This routine uses global scratch space SCRUZ
Definition at line 125 of file spongebx.f.
References copy(), ly1, lz1, mntr_abort(), mntr_log(), mntr_tmr_add(), mntr_warn(), outpost2(), rprm_rp_get(), and rzero().
spng_is_initialised()
logical function spng_is_initialised ()
Check if module was initialised.
Returns
spng_is_initialised
Definition at line 321 of file spongebx.f.
spng_register()
subroutine spng_register ()
Register sponge_box module.
Note
This routine should be called in userchk during first step between calls to frame_start and frame_rparam
Definition at line 12 of file spongebx.f.
References mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), mntr_tmr_add(), mntr_tmr_is_name_reg(), mntr_tmr_reg(), mntr_warn(), rprm_rp_reg(), rprm_sec_reg(), and rprm_sec_set_act().