KTH framework for Nek5000 toolboxes; testing version: Arnoldi algorithm using parpack
Arnoldi algorithm using parpack
Framework for Nek5000 toolboxes » Toolbox » Tools module » Time stepper routines
Arnoldi algorithm with PARPACK.
Files
file arn_arp.f
Set of subroutines to solve eigenvalue problem with Arnoldi algorithm using PARPACK/ARPACK.
file arn_arp_io.f
Set of checkpointing routines for arn_arp module.
Functions
subroutine stepper_register ()
Register Arnoldi ARPACK module.
subroutine stepper_init ()
Initilise Arnoldi ARPACK module.
logical function stepper_is_initialised ()
Check if module was initialised.
subroutine stepper_vsolve
Create Krylov space, get Ritz values and restart stepper phase.
subroutine arn_esolve
ARPACK postprocessing.
subroutine arn_naupd
Interface to pdnaupd.
subroutine arn_rst_save
Write restart files.
subroutine arn_rst_read
Read from checkpoints.
subroutine arn_write_par (prefix)
Write procesor independent data.
subroutine mfo_arnp
Write procesor independent variables.
subroutine arn_read_par (prefix)
Read procesor independent data.
subroutine mfi_arnp
Read procesor independent variables.
subroutine mfo_arnv (prefix)
Write procesor dependent data (long vectors)
subroutine mfi_arnv (prefix)
Read procesor dependent data (long vectors)
subroutine mfo_singlev (ioflds, nout, offs0, stride, strideB, ur1, ur2, ur3, vect)
Write single Krylov vector to the file.
subroutine mfi_singlev (iofldr, offs0, stride, strideB, ur1, ur2, ur3, vect)
Read single Krylov vector from the file.
Detailed Description
Arnoldi algorithm with PARPACK.
Warning
This module is not upgraded to stable Nek5000 relese yet
Description of the method can be found in [3] [4]
Module interface:\n
Global interface list:
Interface provided to tstepper:
stepper_param_in
stepper_param_out
stepper_vinit
stepper_solve
Module parameters:\n
Global parameter list:
Parameters provided by arn_arp submodule (include file - ARN_ARPD):
ARNKRYLOV : (integer) size of Krylov space
ARNEGV : (integer) number of calculated eigenvalues
ARNISTART : (integer) checkpoint file number for restart (reading)
ARNISTOP : (integer) checkpoint file number for saving data
Global parameter dependency:
Parameters required by arn_arp submodule:
CHKPOINTD:
IFCHKPTRST : if restart
CHKPTSTEP - checkpiont dump frequency (number of time steps)
TIME_STEPPERD:
tst_mode :
0 : no arnoldi
1 : direct mode
2 : adjoint mode
3 : initial optimal condition
tst_step : frequency of calling arn_vsolve (number of time steps)
tst_cmax : maximal number of arnoldi cycles
tst_tol : PARPACK tolerance for Ritz values
CONHT (for conjugated heat transfer):
CHCST_SC, CHCFF_V, CHCFF_T : velocity and temperature scaling factors
CHGRX, CHGRY, CHGRZ : gravitational acceleration
CHRA, CHPR : Rayleight and Prandtl numbers
Nek5000 PARAM array
PARAM(66) - write format
PARAM(67) - read format
Module parameter usage:\n
&arpack
 arnkrylov=        100,
 arnegv=         10,
 arnistart=          1,
 arnistop=          2,
 /
Two possible modes are supported:
direct: A*x = lambda*x
inverse: A*x = lambda*M*x, M-mass matrix defining inner product
Inverse mode is preferred as it takes into account inner product Simulation with temperature or passive scalars has to be performed in inverse mode due to speciffic inner product.
ARPACK_DIRECT preprocessing switch between direct and inverse mode.
Attention
This submodule has its own checkpointing routines.
Todo:
This submodule contains binary tar file with modified (restart added) version of PARPACK. This binary file in git is not good idea. Repalce with separate repository for Parpack added by sub.module.
Function Documentation
arn_esolve()
subroutine arn_esolve
ARPACK postprocessing.
Definition at line 387 of file arn_arp.f.
References copy(), io_file_freeid(), mntr_abort(), mntr_check_abort(), mntr_log(), mntr_logi(), and outpost2().
arn_naupd()
subroutine arn_naupd
Interface to pdnaupd.
Definition at line 530 of file arn_arp.f.
References cht_weight_fun(), col2(), col3(), copy(), mntr_abort(), mntr_log(), and tst_dssum().
arn_read_par()
subroutine arn_read_par (character*3 prefix)
Read procesor independent data.
Parameters
[in] prefix prefix
Definition at line 203 of file arn_arp_io.f.
References bcast(), byte_close, io_init(), io_mbyte_open(), io_mfo_fname(), mfi_arnp(), mntr_check_abort(), mntr_error(), mntr_logi(), mntr_warn(), and nekgsync().
arn_rst_read()
subroutine arn_rst_read
Read from checkpoints.
Definition at line 41 of file arn_arp_io.f.
References arn_read_par(), mfi_arnv(), and mntr_log().
arn_rst_save()
subroutine arn_rst_save
Write restart files.
Definition at line 8 of file arn_arp_io.f.
References arn_write_par(), mfo_arnv(), and mntr_logi().
arn_write_par()
subroutine arn_write_par (character*3 prefix)
Write procesor independent data.
Parameters
[in] prefix prefix
Definition at line 64 of file arn_arp_io.f.
References byte_close, io_init(), io_mbyte_open(), io_mfo_fname(), mfo_arnp(), mntr_check_abort(), and nekgsync().
mfi_arnp()
subroutine mfi_arnp
Read procesor independent variables.
Definition at line 421 of file arn_arp_io.f.
References blank(), byte_read, byte_reverse, copy(), and mntr_abort().
mfi_arnv()
subroutine mfi_arnv (character*3 prefix)
Read procesor dependent data (long vectors)
Parameters
[in] prefix prefix
Remarks
This routine uses global scratch space SCRNS, SCRUZ
Definition at line 655 of file arn_arp_io.f.
References io_init(), io_mbyte_close(), io_mfo_fname(), mfi_prepare(), mfi_singlev(), mntr_check_abort(), mntr_log(), mntr_logi(), and mntr_logr().
mfi_singlev()
subroutine mfi_singlev (integer iofldr, integer*8 offs0, integer*8 stride, integer*8 strideB, real, dimension(lx1*lx1*lx1*lelt) ur1, real, dimension(lx1*lx1*lx1*lelt) ur2, real, dimension(lx1*lx1*lx1*lelt) ur3, real, dimension(arna_ls) vect)
Read single Krylov vector from the file.
Parameters
[in,out] iofldr Vector counter
[in] offs0 global file offset (header +...)
[in] stride single vector length
[in] strideB space saved for processes with lower nid
[in] ur1,ur2,ur3 input arrays
[out] vect Krylov vector
Remarks
This routine uses global scratch space SCRNS
Definition at line 821 of file arn_arp_io.f.
References byte_set_view(), copy(), mfi_gets(), and mfi_getv().
mfo_arnp()
subroutine mfo_arnp
Write procesor independent variables.
Definition at line 132 of file arn_arp_io.f.
References blank(), byte_write, and copy().
mfo_arnv()
subroutine mfo_arnv (character*3 prefix)
Write procesor dependent data (long vectors)
Parameters
[in] prefix prefix
Remarks
This routine uses global scratch space SCRUZ
Definition at line 514 of file arn_arp_io.f.
References io_init(), io_mbyte_close(), io_mbyte_open(), io_mfo_fname(), mfo_singlev(), mfo_write_hdr(), mntr_check_abort(), mntr_log(), mntr_logi(), and mntr_logr().
mfo_singlev()
subroutine mfo_singlev (integer ioflds, integer nout, integer*8 offs0, integer*8 stride, integer*8 strideB, real, dimension(lxo*lxo*lxo*lelt) ur1, real, dimension(lxo*lxo*lxo*lelt) ur2, real, dimension(lxo*lxo*lxo*lelt) ur3, real, dimension(arna_ls) vect)
Write single Krylov vector to the file.
Parameters
[in,out] ioflds Vector counter
[in] nout local number of elements to write
[in] offs0 global file offset (header +...)
[in] stride single vector length
[in] strideB space saved for processes with lower nid
[in] ur1,ur2,ur3 output arrays
[in] vect Krylov vector
Definition at line 770 of file arn_arp_io.f.
References byte_set_view(), copy(), mfo_outs(), and mfo_outv().
stepper_init()
subroutine stepper_init
Initilise Arnoldi ARPACK module.
Note
This interface is called by tst_init
Definition at line 97 of file arn_arp.f.
References arn_naupd(), arn_rst_read(), col3(), copy(), izero(), mntr_abort(), mntr_log(), mntr_logi(), mntr_logl(), mntr_logr(), mntr_tmr_add(), mntr_warn(), rprm_rp_get(), and rzero().
stepper_is_initialised()
logical function stepper_is_initialised
Check if module was initialised.
Returns
stepper_is_initialised
Definition at line 302 of file arn_arp.f.
stepper_register()
subroutine stepper_register
Register Arnoldi ARPACK module.
Note
This interface is called by tst_register
Definition at line 24 of file arn_arp.f.
References mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), mntr_tmr_add(), mntr_tmr_reg(), mntr_warn(), rprm_rp_reg(), rprm_sec_reg(), and rprm_sec_set_act().
stepper_vsolve()
subroutine stepper_vsolve
Create Krylov space, get Ritz values and restart stepper phase.
Note
This interface is called by tst_solve
Definition at line 317 of file arn_arp.f.
References arn_esolve(), arn_naupd(), arn_rst_save(), col3(), copy(), mntr_abort(), and mntr_tmr_add().