KTH framework for Nek5000 toolboxes; testing version: Noise_box module
Noise_box module
Framework for Nek5000 toolboxes » Toolbox » Utility module » Forcing module
Add white noise to velocity field at given time in a box.
Files
file noisebx.f
Adding white noise in a box.
Functions
subroutine nseb_register ()
Register noise_box module.
subroutine nseb_init ()
Initilise noise_box module.
logical function nseb_is_initialised ()
Check if module was initialised.
subroutine nseb_noise_add ()
Add noise to velocity field in a box.
Detailed Description
Add white noise to velocity field at given time in a box.
This set of routines adds a white noise in the rectangular box performing global face averaging at the end. To keep the field independent on number of number of processors we use mth_rand insted or ran1 as a random number ganarator. At the end velocity field is smoothed at the element faces.
Module interface:
Global interface list:
Interface provided:
nseb_register
nseb_init
nseb_noise_add
Module interface usage:
      subroutine userchk
      include 'TSTEP'           ! ISTEP
!     start framework
      if (istep.eq.0) call frame_start
!     monitor simulation
      call frame_monitor
!     add noise
      call nseb_noise_add
!     finalise framework
      if (istep.ge.nsteps.or.lastep.eq.1) then
         call frame_end
      endif
      return
      end
!======================================================================
      subroutine frame_usr_register
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
!     register modules
      call nseb_register
      return
      end subroutine
!======================================================================
      subroutine frame_usr_init
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
!     initialise modules
      call nseb_init
      return
      end subroutine
!======================================================================
      subroutine frame_usr_end
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
      return
      end subroutine
!======================================================================
Module parameters:
Global parameter list:
Parameters provided by sponge_box module (include file - SPONGRBD):
Varaible Type Runtime parameter Default value Description
nseb_tim real _noisebx:time 0.0 time to add noise
nseb_amp real _noisebx:amplitude 0.0 noise amplitude
nseb_bmin(1) real _noisebx:boxminx 0.0 position of lower left box corner; dimension X
nseb_bmin(2) real _noisebx:boxminy 0.0 position of lower left box corner; dimension Y
nseb_bmin(3) real _noisebx:boxminz 0.0 position of lower left box corner; dimension Z
nseb_bmax(1) real _noisebx:boxmaxx 0.0 position of upper right box corner; dimension X
nseb_bmax(2) real _noisebx:boxmaxy 0.0 position of upper right box corner; dimension Z
nseb_bmax(3) real _noisebx:boxmaxz 0.0 position of upper right box corner; dimension Y
Module parameter usage:
[_NOISEBX]
time = 0.0
amplitude = 0.0
boxminx = 0.0
boxminy = 0.0
boxminz = 0.0
boxmaxx = 0.0
boxmaxy = 0.0
boxmaxz = 0.0
Function Documentation
nseb_init()
subroutine nseb_init ()
Initilise noise_box module.
Note
This routine should be called in userchk during first step after call to frame_rparam
Remarks
This routine uses global scratch space SCRUZ
Definition at line 103 of file noisebx.f.
References mntr_tmr_add(), mntr_warn(), and rprm_rp_get().
nseb_is_initialised()
logical function nseb_is_initialised ()
Check if module was initialised.
Returns
nseb_is_initialised
Definition at line 179 of file noisebx.f.
nseb_noise_add()
subroutine nseb_noise_add ()
Add noise to velocity field in a box.
Definition at line 192 of file noisebx.f.
References mntr_log(), mntr_tmr_add(), opcolv(), and opdssum().
nseb_register()
subroutine nseb_register ()
Register noise_box module.
Note
This routine should be called in userchk during first step between calls to frame_start and frame_rparam
Definition at line 12 of file noisebx.f.
References mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), mntr_tmr_add(), mntr_tmr_is_name_reg(), mntr_tmr_reg(), mntr_warn(), rprm_rp_reg(), rprm_sec_reg(), and rprm_sec_set_act().