KTH framework for Nek5000 toolboxes; testing version: Line tripping module
Line tripping module
Framework for Nek5000 toolboxes » Toolbox » Utility module » Forcing module
Random volume force along the line.
Files
file trip.f
Tripping function for AMR version of nek5000.
Functions
subroutine trip_register ()
Register tripping module.
subroutine trip_init ()
Initilise tripping module.
logical function trip_is_initialised ()
Check if module was initialised.
subroutine trip_update ()
Update tripping.
subroutine trip_forcing (ffx, ffy, ffz, ix, iy, iz, ieg)
Compute tripping forcing.
subroutine trip_reset ()
Reset tripping.
subroutine trip_1dprj ()
Get 1D projection, array mapping and forcing smoothing.
subroutine trip_rphs_get
Generate set of random phases.
real function trip_ran2 (il)
A simple portable random number generator.
subroutine trip_frcs_get (ifreset)
Generate forcing along 1D line.
Detailed Description
Random volume force along the line.
Set of routines to generate random volume force along the line running in the spanwise direction of the doman to mimic sand paper effect. Its aim is to introduce to the flow low amplitude random noise, that can be used to study e.g. a stability of a boundary layer. This focing is applied only in the eliptical region along the line defined by the smoothing lengths SMTHX and SMTHY and rotated counterclockwise by ROTA angle. This angel is used as well to rotate the force (x- and y-components), so the forcing can be normal to the wall. The smoothing function is defined in the following way:
where
, and
and are here the GLL point coordinates relative to the tripping line. However, the function with limitted support can be easily replaced with simple Gauss profile (see commented lines in trip_1dprj and notice factor 4.0 in the Gauss function necessary to make smoothing lenghts consistent with the original function). The tripping has both steady and unsteeady parts with amplitudes TIAMP and TDAMP respectively, and the forcing is given by:
where
, and
Here and are Fourier series of unit amplitude with NMODE random coefficients. The trip forcing generates noise with a uniform distribution over all frequencies lower than the cutoff frequency corresponding to , where TDT is a time interval between change of the time dependent part of the trip.
This forcing has one continuous time derivative and is independent of the time discretisation. It should be independent as well on the simulation details (e.g. number of mpi ranks or restart flag). It is based on a similar implementation in the SIMSON code [2], and is described in detail in [5].
This tool can simulate number of lines with different set of parameters for each line. The maximal number of lines is given by trip_nline_max in TRIPD include file. In the same way maximal number of Fouries modes per line is given by trip_nmode_max parameter. User havs to adjust values of these variables before compilation of the code.
Module interface:\n
Global interface list:
Interface provided:
trip_register
trip_init
trip_is_initialised
trip_update
trip_forcing
trip_reset
Module interface usage:\n
      subroutine userf  (ix,iy,iz,ieg)
      include 'SIZE'
      include 'NEKUSE'          ! FF[XYZ]
      include 'PARALLEL'        ! GLLEL
      include 'SOLN'            ! V[XYZ]
      integer ix,iy,iz,ieg
      ffx = 0.0
      ffy = 0.0
      ffz = 0.0
!     add tripping
      call trip_forcing(ffx,ffy,ffz,ix,iy,iz,ieg)
      return
      end
!-----------------------------------------------------------------------
      subroutine userchk
      implicit none
      include 'SIZE'            !
      include 'TSTEP'           ! ISTEP, lastep, time
      include 'INPUT'           ! IF3D, PARAM
!     start framework
      if (istep.eq.0) call frame_start
!     monitor simulation
      call frame_monitor
!     save/load files for full-restart
      call chkpt_main
!     for tripping
      call trip_update
!     finalise framework
      if (istep.eq.nsteps.or.lastep.eq.1) then
         call frame_end
      endif
      return
      end
!======================================================================
      subroutine frame_usr_register
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
!     register modules
      call io_register
      call chkpt_register
      call trip_register
      return
      end subroutine
!======================================================================
      subroutine frame_usr_init
      implicit none
      include 'SIZE'
      include 'FRAMELP'
      include 'SOLN'
!-----------------------------------------------------------------------
!     initialise modules
      call chkpt_init
      call trip_init
      return
      end subroutine
!======================================================================
      subroutine frame_usr_end
      implicit none
      include 'SIZE'
      include 'FRAMELP'
!-----------------------------------------------------------------------
!     finalise modules
      return
      end subroutine
!======================================================================
Module parameters:\n
Global parameter list:
Parameters provided by trip_line module (include file - TRIPD):
Varaible Type Runtime parameter Default value Description
trip_nline integer _tripping:nline 0 Number of tripping lines
trip_tiamp real _tripping:tiamp 0.0 Time independent amplitude
trip_tdamp real _tripping:tdamp 0.0 Time dependent amplitude
trip_spos(1,il) real _tripping:sposx'il' 0.0 Starting point X of 'il' line
trip_spos(2,il) real _tripping:sposy'il' 0.0 Starting point Y of 'il' line
trip_spos(3,il) real _tripping:sposz'il' 0.0 Starting point Z of 'il' line
trip_epos(1,il) real _tripping:eposx'il' 0.0 Ending point X of 'il' line
trip_epos(2,il) real _tripping:eposy'il' 0.0 Ending point Y of 'il' line
trip_epos(3,il) real _tripping:eposz'il' 0.0 Ending point Z of 'il' line
trip_smth(1,il) real _tripping:smthx'il' 0.0 Smoothing length X of 'il' line
trip_smth(2,il) real _tripping:smthy'il' 0.0 Smoothing length Y of 'il' line
trip_smth(3,il) real _tripping:smthz'il' 0.0 Smoothing length Z of 'il' line
trip_lext(il) logical _tripping:lext'il' .F. Line extension
trip_rota(il) real _tripping:rota'il' 0.0 Rotation angle of 'il' line
trip_nmode(il) integer _tripping:nmode'il' 0 Number of Fourier modes of 'il' line
trip_tdt(il) real _tripping:tdt'il' 0.0 Time step for tripping of 'il' line
Module parameter usage:\n
[_TRIPPING]             # Runtime paramere section for tripping module
NLINE                = 2                      # Number of tripping lines
TIAMP                = 0.00000000E+00         # Time independent amplitude
TDAMP                = 1.00000000E+01         # Time dependent amplitude
SPOSX01              = 8.30000000E+00         # Starting pont X
SPOSY01              = 3.03500000E+00         # Starting pont Y
SPOSZ01              = 0.00000000E+00         # Starting pont Z
EPOSX01              = 8.30000000E+00         # Ending pont X
EPOSY01              = 3.03500000E+00         # Ending pont Y
EPOSZ01              = 4.50000000E+00         # Ending pont Z
SMTHX01              = 1.36000000E+00         # Smoothing length X
SMTHY01              = 0.34000000E+00         # Smoothing length Y
SMTHZ01              = 0.00000000E+00         # Smoothing length Z
LEXT01               = yes                    # Line extension
ROTA01               = 0.00000000E+00         # Rotation angle in radians
NMODE01              = 16                     # Number of Fourier modes
TDT01                = 0.14000000E+00         # Time step for tripping
SPOSX02              = 8.80000000E+00         # Starting pont X
SPOSY02              = 0.99430000E+00         # Starting pont Y
SPOSZ02              = 0.00000000E+00         # Starting pont Z
EPOSX02              = 8.80000000E+00         # Ending pont X
EPOSY02              = 0.99430000E+00         # Ending pont Y
EPOSZ02              = 4.50000000E+00         # Ending pont Z
SMTHX02              = 0.28000000E+00         # Smoothing length X
SMTHY02              = 0.07000000E+00         # Smoothing length Y
SMTHZ02              = 0.00000000E+00         # Smoothing length Z
SMTHZ02              = 0.20000000E+00         # Smoothing length Z
LEXT02               = no                     # Line extension
ROTA02               = 0.12300000E+00         # Rotation angle in radians
NMODE02              = 76                     # Number of Fourier modes
TDT02                = 0.14000000E+00         # Time step for tripping
Function Documentation
trip_1dprj()
subroutine trip_1dprj
Get 1D projection, array mapping and forcing smoothing.
This routine is just a simple version supporting only lines paralles to z axis. In future it can be generalised.
Remarks
This routine uses global scratch space CTMP0 and CTMP1
Definition at line 376 of file trip.f.
References copy(), ifill(), rzero(), and sort().
trip_forcing()
subroutine trip_forcing (real ffx, real ffy, real ffz, integer ix, integer iy, integer iz, integer ieg)
Compute tripping forcing.
Parameters
[in,out] ffx,ffy,ffz forcing; x,y,z component
[in] ix,iy,iz GLL point index
[in] ieg global element number
Definition at line 310 of file trip.f.
References gllel().
trip_frcs_get()
subroutine trip_frcs_get (logical ifreset)
Generate forcing along 1D line.
Parameters
[in] ifreset reset flag
Definition at line 636 of file trip.f.
References cmult(), copy(), io_file_freeid(), and rzero().
trip_init()
subroutine trip_init
Initilise tripping module.
Note
This routine should be called in frame_usr_init
Definition at line 140 of file trip.f.
References mntr_tmr_add(), mntr_warn(), rprm_rp_get(), trip_1dprj(), trip_frcs_get(), and trip_rphs_get().
trip_is_initialised()
logical function trip_is_initialised
Check if module was initialised.
Returns
trip_is_initialised
Definition at line 264 of file trip.f.
trip_ran2()
real function trip_ran2 (integer il)
A simple portable random number generator.
Requires 32-bit integer arithmetic. Taken from Numerical Recipes, William Press et al. Gives correlation free random numbers but does not have a very large dynamic range, i.e only generates 714025 different numbers. Set seed negative for initialization
Parameters
[in] il line number
Returns
ran
Definition at line 594 of file trip.f.
trip_register()
subroutine trip_register
Register tripping module.
Note
This routine should be called in frame_usr_register
Definition at line 18 of file trip.f.
References mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), mntr_tmr_add(), mntr_tmr_is_name_reg(), mntr_tmr_reg(), mntr_warn(), rprm_rp_reg(), rprm_sec_reg(), and rprm_sec_set_act().
trip_reset()
subroutine trip_reset
Reset tripping.
Definition at line 343 of file trip.f.
References mntr_tmr_add(), trip_1dprj(), and trip_frcs_get().
trip_rphs_get()
subroutine trip_rphs_get
Generate set of random phases.
Definition at line 516 of file trip.f.
References bcast(), copy(), and io_file_freeid().
trip_update()
subroutine trip_update
Update tripping.
Definition at line 277 of file trip.f.
References mntr_tmr_add(), trip_frcs_get(), and trip_rphs_get().