KTH framework for Nek5000 toolboxes; testing version: Viscous surface terms
Viscous surface terms
subroutine imqqtu (ummcu, uminus, uplus)
ummcu =
subroutine igtu_cmt (qminus, ummcu, hface)
Detailed Description
Function/Subroutine Documentation
subroutine igtu_cmt (real, dimension(nx1*nz1,2*ndim,nelt,*) qminus, real, dimension(nx1*nz1*2*ndim,nelt,toteq) ummcu, real, dimension(nx1*nz1*2*ndim*nelt,toteq,3) hface)
Definition at line 53 of file eqnsolver_cmt.f.
References add2(), add_face2full_cmt(), agradu(), cmult(), col2(), col3(), copy(), gradm1_t(), lelt, ly1, lz1, and rzero().
subroutine imqqtu (real, dimension (nx1*nz1*2*ndim*nelt,toteq) ummcu, real, dimension(nx1*nz1*2*ndim*nelt,toteq) uminus, real, dimension (nx1*nz1*2*ndim*nelt,toteq) uplus)
ummcu =
Definition at line 8 of file diffusive_cmt.f.
References add2(), add3(), and cmult().