KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/hmholtz.f File Reference
hmholtz.f File Reference
Functions/Subroutines
subroutine hmholtz (name, u, rhs, h1, h2, mask, mult, imsh, tli, maxit, isd)
subroutine axhelm (au, u, helm1, helm2, imesh, isd)
subroutine setfast (helm1, helm2, imesh)
subroutine sfastax
subroutine setprec (dpcm1, helm1, helm2, imsh, isd)
subroutine chktcg1 (tol, res, h1, h2, mask, mult, imesh, isd)
subroutine cggo (x, f, h1, h2, mask, mult, imsh, tin, maxit, isd, binv, name)
function vlsc32 (r, b, m, n)
subroutine calc (diag, upper, d, e, n, dmax, dmin)
subroutine fdm_h1 (z, r, d, mask, mult, nel, kt, rr)
subroutine set_fdm_prec_h1a_gen
subroutine set_fdm_prec_h1a_els
subroutine set_fdm_prec_h1b (d, h1, h2, nel)
subroutine set_fdm_prec_h1a
subroutine generalev (a, b, lam, n, w)
subroutine outmat2 (a, m, n, k, name)
subroutine rescale_abhalf (a, b, w, n)
subroutine hmholtz_dg (name, u, rhs, h1, h2, mask, tol, maxit)
subroutine cggo_dg (x, f, h1, h2, binv, mask, name, tin, maxit)
subroutine outhmat (h1, h2)
subroutine outmax (a, m, n, name6, ie)
subroutine outmat4 (a, l, m, n, nel, name6, ie)
subroutine ioutmat4 (a, l, m, n, nel, name6, ie)
subroutine ioutfld (a, m, n, nel, name6, ie)
subroutine compute_gradr (ur, us, ut, u)
subroutine compute_gradrta (u, ur, us, ut)
subroutine gradr (ur, us, ut, u, Dr, Dst, Dtt, nr, ns, nt, if3d)
subroutine gradrta (u, ur, us, ut, Drt, Ds, Dt, nr, ns, nt, if3d)
subroutine compute_ugrdu_nhat (uf, ur, us, ut, u)
subroutine face_diff (u, d, gsh_loc, w)
subroutine gmult (ur, us, ut, h1)
subroutine rtna (au, ur, us, ut, uf)
subroutine set_eta_alpha
subroutine hxdg (au, u, h1, h2)
Function/Subroutine Documentation
subroutine axhelm (real, dimension (lx1,ly1,lz1,1) au, real, dimension (lx1,ly1,lz1,1) u, real, dimension (lx1,ly1,lz1,1) helm1, real, dimension (lx1,ly1,lz1,1) helm2, imesh, isd)
Definition at line 80 of file hmholtz.f.
References add2(), add3(), addcol3(), addcol4(), cmult(), col2(), col3(), dnekclock(), hxdg(), j, lelt, ly1, lz1, mxm(), rzero(), setaxdy(), and setfast().
subroutine calc (dimension(n) diag, dimension(n) upper, dimension(n) d, dimension(n) e, n, dmax, dmin)
Definition at line 871 of file hmholtz.f.
References copy(), dmax, dmin, and n.
subroutine cggo (real, dimension(1) x, real, dimension(1) f, real, dimension(1) h1, real, dimension(1) h2, real, dimension(1) mask, real, dimension(1) mult, imsh, tin, maxit, isd, real, dimension(1) binv, character*4 name)
Definition at line 627 of file hmholtz.f.
References add2(), add2s1(), add2s2(), alpha, axhelm(), beta, cadd(), col2(), col3(), copy(), crs_solve_h1(), dssum(), fdm_h1(), glamax(), glmax(), glmin(), glsc2(), glsc3(), glsum(), gop(), h1_overlap_2(), hmh_gmres(), lelt, ly1, lz1, n, ortho(), rzero(), set_fdm_prec_h1b(), setfast(), setprec(), vlsc3(), and vlsc32().
subroutine cggo_dg (real, dimension(1) x, real, dimension(1) f, real, dimension(1) h1, real, dimension(1) h2, real, dimension(1) binv, real, dimension(1) mask, character*4 name, tin, maxit)
Definition at line 1512 of file hmholtz.f.
References add2s1(), add2s2(), alpha, beta, cadd(), col2(), col3(), copy(), glmax(), glmin(), glsc2(), glsum(), gop(), hxdg(), lelt, ly1, lz1, n, rzero(), setprec(), vlsc2(), and vlsc3().
subroutine chktcg1 (tol, real, dimension (lx1,ly1,lz1,1) res, real, dimension (lx1,ly1,lz1,1) h1, real, dimension (lx1,ly1,lz1,1) h2, real, dimension (lx1,ly1,lz1,1) mask, real, dimension (lx1,ly1,lz1,1) mult, imesh, isd)
Definition at line 543 of file hmholtz.f.
References axhelm(), col2(), col3(), copy(), glsc3(), glsum(), lelt, ly1, lz1, rmin(), and rone().
subroutine compute_gradr (real, dimension(nx1*ny1*nz1,nelt) ur, real, dimension(nx1*ny1*nz1,nelt) us, real, dimension(nx1*ny1*nz1,nelt) ut, real, dimension (nx1*ny1*nz1,nelt) u)
Definition at line 1779 of file hmholtz.f.
References gradr().
subroutine compute_gradrta (real, dimension (nx1*ny1*nz1,nelt) u, real, dimension(nx1*ny1*nz1,nelt) ur, real, dimension(nx1*ny1*nz1,nelt) us, real, dimension(nx1*ny1*nz1,nelt) ut)
Definition at line 1800 of file hmholtz.f.
References gradrta().
subroutine compute_ugrdu_nhat (real, dimension(nx1*nz1,2*ndim,lelt,2) uf, real, dimension(nx1,ny1,nz1,nelt) ur, real, dimension(nx1,ny1,nz1,nelt) us, real, dimension(nx1,ny1,nz1,nelt) ut, real, dimension (nx1,ny1,nz1,nelt) u)
Definition at line 1879 of file hmholtz.f.
References dsset().
subroutine face_diff (real, dimension(nx1*nz1*2*ndim*lelt,2) u, integer d, integer gsh_loc, real, dimension(nx1*nz1*2*ndim*lelt,2) w)
Definition at line 1943 of file hmholtz.f.
References gs_op, j, and n.
subroutine fdm_h1 (real, dimension(nx1,ny1,nz1,1) z, real, dimension(nx1,ny1,nz1,1) r, real, dimension(nx1,ny1,nz1,1) d, real, dimension(nx1,ny1,nz1,1) mask, real, dimension(nx1,ny1,nz1,1) mult, nel, integer, dimension(lelt,3) kt, real, dimension(nx1,ny1,nz1,1) rr)
Definition at line 950 of file hmholtz.f.
References col2(), col3(), copy(), dssum(), ly1, lz1, and mxm().
subroutine generalev (real, dimension(n,n) a, real, dimension(n,n) b, real, dimension(n) lam, n, real, dimension(n,n) w)
Definition at line 1383 of file hmholtz.f.
References copy(), dsygv(), exitt(), ly1, lz1, n, outmat2(), and ssygv().
subroutine gmult (real, dimension(nx1*ny1*nz1*nelt) ur, real, dimension(nx1*ny1*nz1*nelt) us, real, dimension(nx1*ny1*nz1*nelt) ut, real, dimension(nx1*ny1*nz1*nelt) h1)
Definition at line 1978 of file hmholtz.f.
subroutine gradr (real, dimension(nr,ns,nt) ur, real, dimension(nr,ns,nt) us, real, dimension(nr,ns,nt) ut, real, dimension (nr,ns,nt) u, real, dimension(nr,nr) Dr, real, dimension(ns,ns) Dst, real, dimension(nt,nt) Dtt, nr, ns, nt, logical if3d)
Definition at line 1823 of file hmholtz.f.
References mxm().
subroutine gradrta (real, dimension (nr,ns,nt) u, real, dimension(nr,ns,nt) ur, real, dimension(nr,ns,nt) us, real, dimension(nr,ns,nt) ut, Drt, Ds, Dt, nr, ns, nt, logical if3d)
Definition at line 1850 of file hmholtz.f.
References mxma().
subroutine hmholtz (character name, real, dimension (lx1,ly1,lz1,1) u, real, dimension (lx1,ly1,lz1,1) rhs, real, dimension (lx1,ly1,lz1,1) h1, real, dimension (lx1,ly1,lz1,1) h2, real, dimension (lx1,ly1,lz1,1) mask, real, dimension (lx1,ly1,lz1,1) mult, imsh, tli, maxit, isd)
Definition at line 3 of file hmholtz.f.
References cggo(), chcopy(), chktcg1(), col2(), dnekclock(), dssum(), hmholtz_dg(), and set_fdm_prec_h1a().
subroutine hmholtz_dg (character name, real, dimension (lx1,ly1,lz1,1) u, real, dimension (lx1,ly1,lz1,1) rhs, real, dimension (lx1,ly1,lz1,1) h1, real, dimension (lx1,ly1,lz1,1) h2, real, dimension (lx1,ly1,lz1,1) mask, tol, maxit)
Definition at line 1481 of file hmholtz.f.
References cggo_dg(), and dnekclock().
subroutine hxdg (real, dimension(1) au, real, dimension(1) u, real, dimension(1) h1, real, dimension(1) h2)
Definition at line 2124 of file hmholtz.f.
References col2(), col4(), compute_gradr(), compute_gradrta(), compute_ugrdu_nhat(), face_diff(), gmult(), lelt, ly1, lz1, n, and rtna().
subroutine ioutfld (integer, dimension(m,n,nel) a, m, n, nel, character*6 name6, ie)
Definition at line 1758 of file hmholtz.f.
References j, and n.
subroutine ioutmat4 (integer, dimension(l,m,n,nel) a, l, m, n, nel, character*6 name6, ie)
Definition at line 1738 of file hmholtz.f.
References j, and n.
subroutine outhmat (real, dimension(1) h1, real, dimension(1) h2)
Definition at line 1674 of file hmholtz.f.
References exitt(), hxdg(), j, lelt, ly1, lz1, n, outmax(), and rzero().
subroutine outmat2 (real, dimension(m,n) a, m, n, k, character*4 name)
Definition at line 1438 of file hmholtz.f.
References j, and n.
subroutine outmat4 (real, dimension(l,m,n,nel) a, l, m, n, nel, character*6 name6, ie)
Definition at line 1718 of file hmholtz.f.
References j, and n.
subroutine outmax (real, dimension(m,n) a, m, n, character*6 name6, ie)
Definition at line 1703 of file hmholtz.f.
References j, and n.
subroutine rescale_abhalf (real, dimension(n,n) a, real, dimension(n,n) b, real, dimension(n) w, n)
Definition at line 1454 of file hmholtz.f.
References ident(), j, and n.
subroutine rtna (real, dimension(nx1,ny1,nz1,nelt) au, real, dimension(nx1,ny1,nz1,nelt) ur, real, dimension(nx1,ny1,nz1,nelt) us, real, dimension(nx1,ny1,nz1,nelt) ut, real, dimension(nx1*nz1,2*ndim,lelt,2) uf)
Definition at line 2011 of file hmholtz.f.
References dsset(), and lelt.
subroutine set_eta_alpha ()
Definition at line 2078 of file hmholtz.f.
References dsset(), and gs_op.
subroutine set_fdm_prec_h1a ()
Definition at line 1374 of file hmholtz.f.
References set_fdm_prec_h1a_els(), and set_fdm_prec_h1a_gen().
subroutine set_fdm_prec_h1a_els ()
Definition at line 1133 of file hmholtz.f.
References copy(), j, lelt, ly1, and lz1.
subroutine set_fdm_prec_h1a_gen ()
Definition at line 1041 of file hmholtz.f.
References copy(), generalev(), mxm(), n, rescale_abhalf(), rzero(), transpose(), and vsqrt().
subroutine set_fdm_prec_h1b (real, dimension (nx1,ny1,nz1,1) d, real, dimension(nx1,ny1,nz1,1) h1, real, dimension(nx1,ny1,nz1,1) h2, nel)
Definition at line 1288 of file hmholtz.f.
References vlsc2(), and vlsum().
subroutine setfast (real, dimension(nx1,ny1,nz1,1) helm1, real, dimension(nx1,ny1,nz1,1) helm2, imesh)
Definition at line 279 of file hmholtz.f.
References lelt, vlamax(), vlmax(), and vlmin().
subroutine setprec (real, dimension (lx1,ly1,lz1,1) dpcm1, real, dimension(nx1,ny1,nz1,1) helm1, real, dimension(nx1,ny1,nz1,1) helm2, imsh, isd)
Definition at line 397 of file hmholtz.f.
References addcol3(), col2(), dssum(), invcol1(), j, lelt, mxm(), rzero(), and setaxdy().
subroutine sfastax ()
Definition at line 327 of file hmholtz.f.
References j, lelt, ly1, lz1, and rzero().
function vlsc32 (real, dimension(1) r, real, dimension(1) b, real, dimension(1) m, n)
Definition at line 861 of file hmholtz.f.
References n.