KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/hpf.f File Reference
hpf.f File Reference
Functions/Subroutines
subroutine make_hpf
subroutine build_hpf_mat (op_mat, f_filter, ifboyd)
subroutine build_hpf_fld (v, u, f, nx, nz)
subroutine hpf_trns_fcn (diag, kut)
subroutine spec_coeff_init (ref_xmap, ifboyd)
Function/Subroutine Documentation
build_hpf_fld()
subroutine build_hpf_fld (real, dimension(nxyz,lelv) v, real, dimension(nxyz,lelv) u, real, dimension(nx,nx) f, integer nx, integer nz)
Definition at line 165 of file hpf.f.
References copy(), ly1, lz1, mxm(), sub3(), and transpose().
build_hpf_mat()
subroutine build_hpf_mat (real, dimension(lx1,lx1) op_mat, real, dimension(lm2) f_filter, logical ifboyd)
Definition at line 116 of file hpf.f.
References copy(), gaujordf(), mxm(), and spec_coeff_init().
hpf_trns_fcn()
subroutine hpf_trns_fcn (real, dimension(lx1*lx1) diag, integer kut)
Definition at line 233 of file hpf.f.
References ident().
make_hpf()
subroutine make_hpf ()
Definition at line 15 of file hpf.f.
References addcol3(), build_hpf_fld(), build_hpf_mat(), cmult(), hpf_trns_fcn(), ly1, lz1, and opadd2col().
spec_coeff_init()
subroutine spec_coeff_init (real, dimension(lm2) ref_xmap, logical ifboyd)
Definition at line 270 of file hpf.f.
References legendre_poly(), and transpose().