KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/ic.f File Reference
ic.f File Reference
Functions/Subroutines
subroutine setics
subroutine slogic (iffort, ifrest, ifprsl, nfiles)
subroutine restart (nfiles)
subroutine sioflag (ndumps, fname, rsopts)
subroutine mapdmp (sdump, tdump, ieg, nxr, nyr, nzr, if_byte_sw)
subroutine mapab (x, y, nxr, nel)
subroutine mapab4r (x, y, nxr, nel)
function i1_from_char (s1)
integer function indx2 (s1, l1, s2, l2)
integer function indx1 (S1, S2, L2)
integer function indx_cut (S1, S2, L2)
subroutine csplit (s0, s1, s2, l0)
subroutine lshft (string, ipt)
subroutine ljust (string)
subroutine chknorm (ifzero)
subroutine prsolvt
subroutine prsolvv
subroutine nekuic
subroutine capit (lettrs, n)
logical function ifgtrl (VALUE, LINE)
logical function ifgtil (IVALUE, LINE)
subroutine perturb (tt, ifld, eps)
subroutine vcospf (x, y, n)
subroutine vbyte_swap (x, n)
logical function if_byte_swap_test (bytetest, ierr)
subroutine geom_reset (icall)
subroutine dsavg (u)
subroutine map13_all (x3, x1)
subroutine mfi_gets (u, wk, lwk, iskip)
subroutine mfi_getv (u, v, w, wk, lwk, iskip)
subroutine mfi_parse_hdr (hdr, ierr)
subroutine parse_std_hdr (hdr)
subroutine parse_std_hdr_2006 (hdr, rlcode)
subroutine mfi (fname_in, ifile)
subroutine addfid (fname, fid)
subroutine mfi_prepare (hname)
subroutine axis_interp_ic (pm1)
subroutine map_pm1_to_pr (pm1, ifile)
subroutine full_restart (fnames, n_restart)
subroutine projfld_c0 ()
Function/Subroutine Documentation
addfid()
subroutine addfid (character*1, dimension(132) fname, integer fid)
Definition at line 2512 of file ic.f.
References chcopy(), and indx1().
axis_interp_ic()
subroutine axis_interp_ic (real, dimension(lx1,ly1,lz1,lelv) pm1)
Definition at line 2663 of file ic.f.
References copy(), and mxm().
capit()
subroutine capit (character, dimension(n) lettrs, n)
Definition at line 1648 of file ic.f.
chknorm()
subroutine chknorm (logical ifzero)
Definition at line 1456 of file ic.f.
References unorm().
csplit()
subroutine csplit (character*132 s0, character*132 s1, character*132 s2, l0)
Definition at line 1402 of file ic.f.
References blank(), indx_cut(), and lshft().
dsavg()
subroutine dsavg (real, dimension(lx1,ly1,lz1,lelt) u)
Definition at line 1878 of file ic.f.
References col2(), and dssum().
full_restart()
subroutine full_restart (character *(*), dimension(*) fnames, n_restart)
Definition at line 2749 of file ic.f.
References bcast(), chcopy(), restart(), and setprop().
geom_reset()
subroutine geom_reset (icall)
Definition at line 1802 of file ic.f.
References copy(), geom1(), geom2(), map13_all(), setdef(), setinvm(), sfastax(), updmsys(), and volume().
i1_from_char()
function i1_from_char (character*1 s1)
Definition at line 1327 of file ic.f.
References indx2().
if_byte_swap_test()
logical function if_byte_swap_test (real*4 bytetest, ierr)
Definition at line 1782 of file ic.f.
References byte_reverse.
ifgtil()
logical function ifgtil (IVALUE, character*132 LINE)
Definition at line 1699 of file ic.f.
References indx1(), and ljust().
ifgtrl()
logical function ifgtrl (VALUE, character*132 LINE)
Definition at line 1662 of file ic.f.
References indx1(), and ljust().
indx1()
integer function indx1 (character*132 S1, character*132 S2, L2)
Definition at line 1357 of file ic.f.
indx2()
integer function indx2 (character*132 s1, l1, character*132 s2, l2)
Definition at line 1339 of file ic.f.
indx_cut()
integer function indx_cut (character*1, dimension(132) S1, character*1, dimension(132) S2, L2)
Definition at line 1375 of file ic.f.
References indx1().
ljust()
subroutine ljust (character*1, dimension(132) string)
Definition at line 1433 of file ic.f.
lshft()
subroutine lshft (character*1, dimension(132) string, ipt)
Definition at line 1417 of file ic.f.
map13_all()
subroutine map13_all (real, dimension(lx3,ly3,lz3,lelt) x3, real, dimension(lx1,ly1,lz1,lelt) x1)
Definition at line 1906 of file ic.f.
References map13().
map_pm1_to_pr()
subroutine map_pm1_to_pr (real, dimension(lx1*ly1*lz1,lelv) pm1, ifile)
Definition at line 2715 of file ic.f.
References copy(), and map12().
mapab()
subroutine mapab (dimension(lx1,ly1,lz1,nel) x, dimension(nxr,nxr,nxr,nel) y, nxr, nel)
Definition at line 1184 of file ic.f.
References copy(), exitt(), igllm(), mxm(), and zwgll().
mapab4r()
subroutine mapab4r (real*4, dimension(lx1,ly1,lz1,nel) x, real, dimension(nxr,nxr,nxr,nel) y, nxr, nel)
Definition at line 1253 of file ic.f.
References copy(), copy4r(), exitt(), igllm(), mxm(), and zwgll().
mapdmp()
subroutine mapdmp (real, dimension(lxyz1,lelt) sdump, real*4, dimension(lxyzr) tdump, ieg, nxr, nyr, nzr, logical if_byte_sw)
Definition at line 1109 of file ic.f.
References byte_reverse, copy4r(), crecv2(), csend(), err_chk(), exitti(), gllel(), gllnid(), and mapab4r().
mfi()
subroutine mfi (character*132 fname_in, ifile)
Definition at line 2355 of file ic.f.
References axis_interp_ic(), blank(), byte_close, byte_close_mpi(), byte_set_view(), chcopy(), dnekclock(), err_chk(), glsum(), ltrunc(), map_pm1_to_pr(), mfi_gets(), mfi_getv(), and mfi_prepare().
mfi_gets()
subroutine mfi_gets (real, dimension(lx1*ly1*lz1,1) u, real*4, dimension(2*lwk) wk, lwk, logical iskip)
Definition at line 1923 of file ic.f.
References bcast(), byte_read, byte_read_mpi(), byte_reverse, byte_reverse8, copy(), copy4r(), csend(), err_chk(), gllel(), gllnid(), iglmax(), irecv(), lim_chk(), mapab(), mapab4r(), msgwait(), nekgsync(), and rzero().
mfi_getv()
subroutine mfi_getv (real, dimension(lx1*ly1*lz1,1) u, real, dimension(lx1*ly1*lz1,1) v, real, dimension(lx1*ly1*lz1,1) w, real*4, dimension(2*lwk) wk, lwk, logical iskip)
Definition at line 2057 of file ic.f.
References bcast(), byte_read, byte_read_mpi(), byte_reverse, byte_reverse8, copy(), copy4r(), csend(), err_chk(), gllel(), gllnid(), iglmax(), irecv(), lim_chk(), mapab(), mapab4r(), msgwait(), nekgsync(), and rzero().
mfi_parse_hdr()
subroutine mfi_parse_hdr (character*132 hdr, ierr)
Definition at line 2200 of file ic.f.
References indx2(), and parse_std_hdr().
mfi_prepare()
subroutine mfi_prepare (character*132 hname)
Definition at line 2543 of file ic.f.
References addfid(), bcast(), blank(), byte_close, byte_open, byte_open_mpi(), byte_read, byte_read_mpi(), byte_reverse, byte_set_view(), chcopy(), err_chk(), exitt(), igl_running_sum(), and mfi_parse_hdr().
nekuic()
subroutine nekuic
Definition at line 1599 of file ic.f.
References nekasgn().
parse_std_hdr()
subroutine parse_std_hdr (character*132 hdr)
Definition at line 2217 of file ic.f.
References parse_std_hdr_2006().
parse_std_hdr_2006()
subroutine parse_std_hdr_2006 (character*132 hdr, character*1, dimension(20) rlcode)
Definition at line 2316 of file ic.f.
perturb()
subroutine perturb (real, dimension(1) tt, integer ifld, eps)
Definition at line 1731 of file ic.f.
References cmult(), dssum(), and vcospf().
projfld_c0()
subroutine projfld_c0
Definition at line 2770 of file ic.f.
References col2(), dsavg(), dssum(), opcolv(), opdssum(), and ortho().
prsolvt()
subroutine prsolvt
Definition at line 1488 of file ic.f.
References heat(), setprop(), and setsolv().
prsolvv()
subroutine prsolvv
Definition at line 1535 of file ic.f.
References cfill(), exitt(), fluid(), setprop(), and setsolv().
restart()
subroutine restart (nfiles)
Definition at line 416 of file ic.f.
References axis_interp_ic(), bcast(), byte_close, byte_open, byte_read, chcopy(), copy(), err_chk(), exitt(), gllnid(), i1_from_char(), if_byte_swap_test(), izero(), lbcast(), ltrunc(), map12(), map_pm1_to_pr(), mapdmp(), mfi(), and sioflag().
setics()
subroutine setics
Definition at line 3 of file ic.f.
References col2(), dssum(), exitt(), exitti(), geom_reset(), glmax(), glmin(), glsum(), lagvel(), meshv(), nekgsync(), nekuic(), opcopy(), projfld_c0(), prsolvt(), prsolvv(), ptbgeom(), restart(), rone(), rzero(), setup_convect(), and slogic().
sioflag()
subroutine sioflag (ndumps, character*132 fname, character*132 rsopts)
Definition at line 954 of file ic.f.
References blank(), capit(), chcopy(), csplit(), indx1(), indx_cut(), ljust(), and ltrunc().
slogic()
subroutine slogic (logical, dimension(ldimt1,0:lpert) iffort, logical, dimension(0:ldimt1,0:lpert) ifrest, logical, dimension(ldimt1,0:lpert) ifprsl, nfiles)
Definition at line 284 of file ic.f.
References blank(), capit(), csplit(), indx1(), indx_cut(), ljust(), ltrunc(), and sioflag().
vbyte_swap()
subroutine vbyte_swap (character*1, dimension(0:3,1) x, n)
Definition at line 1756 of file ic.f.
vcospf()
subroutine vcospf (real, dimension(1) x, real, dimension(1) y, n)
Definition at line 1748 of file ic.f.