KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/induct.f File Reference
induct.f File Reference
Functions/Subroutines
subroutine induct (igeom)
subroutine lagbfield
subroutine makebsource_mhd
subroutine makeufb
subroutine makextb
subroutine makebdfb
subroutine cresvib (resv1, resv2, resv3, h1, h2)
subroutine cresvibp (resv1, resv2, resv3, h1, h2)
subroutine incomprn (ux, uy, uz, up)
subroutine extrapp (p, plag)
subroutine opzero (ux, uy, uz)
subroutine opnorm (unorm, ux, uy, uz, type3)
subroutine lorentz_force (lf, b1, b2, b3, w1, w2)
subroutine curl (vort, u, v, w, ifavg, work1, work2)
subroutine lorentz_force2 (lf, b1, b2, b3)
subroutine lorentz_force_e (lf, b1, b2, b3, e)
subroutine spec_curl_e (cb, b1, b2, b3, rx, ry, rz, sx, sy, sz, tx, ty, tz)
subroutine specx (b, nb, a, na, ba, ab, w)
subroutine phys_to_elsasser (u1, u2, u3, b1, b2, b3, n)
subroutine elsasser_to_phys (u1, u2, u3, b1, b2, b3, n)
subroutine phys_to_elsasser2 (u1, b1, n)
subroutine elsasser_to_phys2 (u1, b1, n)
subroutine elsasserh (igeom)
subroutine compute_cfl (cfl, u, v, w, dt)
subroutine getdr (dri, zgm1, lx1)
subroutine ophinv_pr (o1, o2, o3, i1, i2, i3, h1, h2, tolh, nmxhi)
subroutine set_ifbcor
subroutine setrhsp (p, h1, h2, h2inv, pset, niprev)
subroutine gensolnp (p, h1, h2, h2inv, pset, nprev)
subroutine econjp (pset, nprev, h1, h2, h2inv, ierr)
subroutine advab_elsasser_fast
subroutine set_dealias_rx
subroutine cfl_check
Function/Subroutine Documentation
advab_elsasser_fast()
subroutine advab_elsasser_fast ()
Definition at line 1326 of file induct.f.
References add3(), grad_rst(), intp_rstd(), ly1, lz1, set_dealias_rx(), and sub3().
cfl_check()
subroutine cfl_check ()
Definition at line 1608 of file induct.f.
References compute_cfl(), ly1, lz1, opcopy(), and phys_to_elsasser().
compute_cfl()
subroutine compute_cfl (cfl, real, dimension(lx1,ly1,lz1,nelv) u, real, dimension(lx1,ly1,lz1,nelv) v, real, dimension(lx1,ly1,lz1,nelv) w, dt)
Definition at line 918 of file induct.f.
References getdr(), glmax(), ly1, and lz1.
cresvib()
subroutine cresvib (real, dimension (lx1,ly1,lz1,1) resv1, real, dimension (lx1,ly1,lz1,1) resv2, real, dimension (lx1,ly1,lz1,1) resv3, real, dimension (lx1,ly1,lz1,1) h1, real, dimension (lx1,ly1,lz1,1) h2)
Definition at line 222 of file induct.f.
References bcdirvc(), extrapp(), ly1, lz1, opadd2(), opgradt(), ophx(), and opsub2().
cresvibp()
subroutine cresvibp (real, dimension (lx1,ly1,lz1,1) resv1, real, dimension (lx1,ly1,lz1,1) resv2, real, dimension (lx1,ly1,lz1,1) resv3, real, dimension (lx1,ly1,lz1,1) h1, real, dimension (lx1,ly1,lz1,1) h2)
Definition at line 252 of file induct.f.
References bcdirvc(), bcneutr(), extrapp(), ly1, lz1, opadd2(), opgradt(), ophx(), and opsub2().
curl()
subroutine curl (real, dimension(lt,3) vort, real, dimension(1) u, real, dimension(1) v, real, dimension(1) w, logical ifavg, real, dimension(1) work1, real, dimension(1) work2)
Definition at line 486 of file induct.f.
References col2(), dssum(), dudxyz(), ly1, lz1, and sub3().
econjp()
subroutine econjp (real, dimension (lx2*ly2*lz2*lelv,mxprev) pset, nprev, real, dimension (lx1,ly1,lz1,lelv) h1, real, dimension (lx1,ly1,lz1,lelv) h2, real, dimension(lx1,ly1,lz1,lelv) h2inv, ierr)
Definition at line 1267 of file induct.f.
References add2s2(), cdabdtp(), cmult(), glsc2(), gop(), and vlsc2().
elsasser_to_phys()
subroutine elsasser_to_phys (real, dimension(1) u1, real, dimension(1) u2, real, dimension(1) u3, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, n)
Definition at line 797 of file induct.f.
elsasser_to_phys2()
subroutine elsasser_to_phys2 (real, dimension(1) u1, real, dimension(1) b1, n)
Definition at line 838 of file induct.f.
elsasserh()
subroutine elsasserh (igeom)
Definition at line 852 of file induct.f.
References cresvib(), cresvibp(), incomprn(), ly1, lz1, opadd2(), ophinv_pr(), q_filter(), and sethlm().
extrapp()
subroutine extrapp (real, dimension (lx2,ly2,lz2,1) p, real, dimension (lx2,ly2,lz2,1) plag)
Definition at line 370 of file induct.f.
References copy(), and exitt().
gensolnp()
subroutine gensolnp (real, dimension (lx2,ly2,lz2,lelv) p, real, dimension (lx1,ly1,lz1,lelv) h1, real, dimension (lx1,ly1,lz1,lelv) h2, real, dimension(lx1,ly1,lz1,lelv) h2inv, real, dimension (lx2*ly2*lz2*lelv,mxprev) pset, nprev)
Definition at line 1222 of file induct.f.
References add2(), copy(), and econjp().
getdr()
subroutine getdr (real, dimension(lx1) dri, real, dimension(lx1) zgm1, lx1)
Definition at line 1009 of file induct.f.
References invcol1().
incomprn()
subroutine incomprn (ux, uy, uz, up)
Definition at line 282 of file induct.f.
References add2(), add2col2(), chkptol(), cmult(), copy(), dnekclock(), esolver(), gensolnp(), invers2(), ly1, lz1, opadd2cm(), opbinv(), opdiv(), opgradt(), ortho(), rzero(), and setrhsp().
induct()
subroutine induct (igeom)
Definition at line 12 of file induct.f.
References elsasserh(), lagbfield(), lagvel(), ly1, lz1, makebsource_mhd(), and vol_flow().
lagbfield()
subroutine lagbfield ()
Definition at line 55 of file induct.f.
References opcopy().
lorentz_force()
subroutine lorentz_force (real, dimension(lx1*ly1*lz1*lelv,ldim) lf, real, dimension(lx1*ly1*lz1*lelv) b1, real, dimension(lx1*ly1*lz1*lelv) b2, real, dimension(lx1*ly1*lz1*lelv) b3, w1, w2)
Definition at line 447 of file induct.f.
References curl(), ly1, and lz1.
lorentz_force2()
subroutine lorentz_force2 (real, dimension(lx1*ly1*lz1*ldim,lelt) lf, real, dimension(lx1*ly1*lz1,lelt) b1, real, dimension(lx1*ly1*lz1,lelt) b2, real, dimension(lx1*ly1*lz1,lelt) b3)
Definition at line 539 of file induct.f.
References lorentz_force_e().
lorentz_force_e()
subroutine lorentz_force_e (real, dimension(lx1*ly1*lz1,3) lf, real, dimension(lx1*ly1*lz1) b1, real, dimension(lx1*ly1*lz1) b2, real, dimension(lx1*ly1*lz1) b3, integer e)
Definition at line 571 of file induct.f.
References ly1, lz1, scale(), setmap(), setproj(), spec_curl_e(), and specmp().
makebdfb()
subroutine makebdfb ()
Definition at line 179 of file induct.f.
References cmult2(), ly1, lz1, opadd2(), opadd2col(), and opcolv3c().
makebsource_mhd()
subroutine makebsource_mhd ()
Definition at line 74 of file induct.f.
References advab_elsasser_fast(), dnekclock(), exitt(), makeabf(), makebdf(), makebdfb(), makeuf(), makeufb(), makeuq(), and makextb().
makeufb()
subroutine makeufb ()
Definition at line 123 of file induct.f.
References nekuf(), and opcolv2().
makextb()
subroutine makextb ()
Definition at line 140 of file induct.f.
References add2s1(), add3s2(), copy(), ly1, and lz1.
ophinv_pr()
subroutine ophinv_pr (real, dimension (lx1,ly1,lz1,1) o1, real, dimension (lx1,ly1,lz1,1) o2, real, dimension (lx1,ly1,lz1,1) o3, real, dimension (lx1,ly1,lz1,1) i1, real, dimension (lx1,ly1,lz1,1) i2, real, dimension (lx1,ly1,lz1,1) i3, real, dimension (lx1,ly1,lz1,1) h1, real, dimension (lx1,ly1,lz1,1) h2, tolh, nmxhi)
Definition at line 1023 of file induct.f.
References hmhzsf(), hsolve(), and ophinv().
opnorm()
subroutine opnorm (unorm, real, dimension(1) ux, real, dimension(1) uy, real, dimension(1) uz, character*3 type3)
Definition at line 419 of file induct.f.
References glsum(), ly1, lz1, unorm(), and vlsc3().
opzero()
subroutine opzero (real, dimension(1) ux, real, dimension(1) uy, real, dimension(1) uz)
Definition at line 406 of file induct.f.
References ly1, lz1, and rzero().
phys_to_elsasser()
subroutine phys_to_elsasser (real, dimension(1) u1, real, dimension(1) u2, real, dimension(1) u3, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, n)
Definition at line 770 of file induct.f.
phys_to_elsasser2()
subroutine phys_to_elsasser2 (real, dimension(1) u1, real, dimension(1) b1, n)
Definition at line 824 of file induct.f.
set_dealias_rx()
subroutine set_dealias_rx ()
Definition at line 1524 of file induct.f.
References intp_rstd(), ly1, lz1, and zwgl().
set_ifbcor()
subroutine set_ifbcor ()
Definition at line 1092 of file induct.f.
References gllog().
setrhsp()
subroutine setrhsp (real, dimension (lx2,ly2,lz2,lelv) p, real, dimension (lx1,ly1,lz1,lelv) h1, real, dimension (lx1,ly1,lz1,lelv) h2, real, dimension(lx1,ly1,lz1,lelv) h2inv, real, dimension (lx2*ly2*lz2*lelv,mxprev) pset, niprev)
Definition at line 1152 of file induct.f.
References add2s2(), cdabdtp(), glsc3(), gop(), rzero(), sub2(), updrhse(), and vlsc2().
spec_curl_e()
subroutine spec_curl_e (real, dimension(lx1*ly1*lz1,3) cb, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) rx, real, dimension(1) ry, real, dimension(1) rz, real, dimension(1) sx, real, dimension(1) sy, real, dimension(1) sz, real, dimension(1) tx, real, dimension(1) ty, real, dimension(1) tz)
Definition at line 687 of file induct.f.
References local_grad3(), ly1, and lz1.
specx()
subroutine specx (real, dimension(1) b, nb, real, dimension(1) a, na, ba, ab, real, dimension(1) w)
Definition at line 755 of file induct.f.