KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/cmt/inflow_bc.f File Reference
inflow_bc.f File Reference
Functions/Subroutines
subroutine inflow (nvar, f, e, facew, wbc)
subroutine inflow_rflu (nvar, f, e, facew, wbc)
subroutine inflow_inviscid (nvar, f, e, facew, wbc)
subroutine bcondinflowperf (bcOptType, bcOptFixed, ptot, ttot, ur, vr, wr, mach, sxn, syn, szn, cpgas, mm, rl, rul, rvl, rwl, rr, rur, rvr, rwr, rer, pr, ar, tr)
Function/Subroutine Documentation
subroutine bcondinflowperf (integer bcOptType, integer bcOptFixed, real ptot, real ttot, real ur, real vr, real wr, real mach, real sxn, real syn, real szn, real cpgas, real mm, real rl, real rul, real rvl, real rwl, real rr, real rur, real rvr, real rwr, real rer, real pr, real ar, real tr)
Definition at line 284 of file inflow_bc.f.
References mixtperf_c2_grt(), mixtperf_co2_cguvw(), mixtperf_d_prt(), mixtperf_eo_dgpuvw(), mixtperf_eo_dgpvm(), mixtperf_g_cpr(), mixtperf_p_gmapo(), mixtperf_p_gpotto(), mixtperf_po_cgpuvw(), mixtperf_po_gptto(), mixtperf_r_m(), mixtperf_t_cgr(), mixtperf_t_gmato(), and mixtperf_vm_c2co2g().
subroutine inflow (integer nvar, integer f, integer e, real, dimension(nx1,nz1,2*ldim,nelt,nvar) facew, real, dimension(nx1,nz1,2*ldim,nelt,nvar) wbc)
Definition at line 3 of file inflow_bc.f.
References inflow_inviscid().
subroutine inflow_inviscid (nvar, integer f, integer e, real, dimension(nx1*nz1,2*ldim,nelt,nvar) facew, real, dimension (nx1*nz1,2*ldim,nelt,nvar) wbc)
Definition at line 99 of file inflow_bc.f.
References facind(), i0, and nekasgn().
subroutine inflow_rflu (nvar, integer f, integer e, real, dimension(nx1*nz1,2*ldim,nelt,nvar) facew, real, dimension (nx1*nz1,2*ldim,nelt,nvar) wbc)
Definition at line 20 of file inflow_bc.f.
References bcondinflowperf(), facind(), i0, and nekasgn().