KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/3rd_party/iniparser.c File Reference
iniparser.c File Reference
Parser for ini files.
#include <ctype.h>
#include "iniparser.h"
Macros
#define ASCIILINESZ (1024)
#define INI_INVALID_KEY ((char*)-1)
Typedefs
typedef enum _line_status_ line_status
Enumerations
enum _line_status_ {
LINE_UNPROCESSED, LINE_ERROR, LINE_EMPTY, LINE_COMMENT,
LINE_SECTION, LINE_VALUE
}
Functions
const char * strlwc (const char *in, char *out, unsigned len)
Convert a string to lowercase.
unsigned strstrip (char *s)
Remove blanks at the beginning and the end of a string.
int iniparser_getnsec (const dictionary *d)
Get number of sections in a dictionary.
const char * iniparser_getsecname (const dictionary *d, int n)
Get name for section n in a dictionary.
void iniparser_dump (const dictionary *d, FILE *f)
Dump a dictionary to an opened file pointer.
void iniparser_dump_ini (const dictionary *d, FILE *f)
Save a dictionary to a loadable ini file.
void iniparser_dumpsection_ini (const dictionary *d, const char *s, FILE *f)
Save a dictionary section to a loadable ini file.
int iniparser_getsecnkeys (const dictionary *d, const char *s)
Get the number of keys in a section of a dictionary.
const char ** iniparser_getseckeys (const dictionary *d, const char *s, const char **keys)
Get the number of keys in a section of a dictionary.
const char * iniparser_getstring (const dictionary *d, const char *key, const char *def)
Get the string associated to a key.
int iniparser_getint (const dictionary *d, const char *key, int notfound)
Get the string associated to a key, convert to an int.
double iniparser_getdouble (const dictionary *d, const char *key, double notfound)
Get the string associated to a key, convert to a double.
int iniparser_getboolean (const dictionary *d, const char *key, int notfound)
Get the string associated to a key, convert to a boolean.
int iniparser_find_entry (const dictionary *ini, const char *entry)
Finds out if a given entry exists in a dictionary.
int iniparser_set (dictionary *ini, const char *entry, const char *val)
Set an entry in a dictionary.
void iniparser_unset (dictionary *ini, const char *entry)
Delete an entry in a dictionary.
dictionary * iniparser_load (const char *ininame)
Parse an ini file and return an allocated dictionary object.
void iniparser_freedict (dictionary *d)
Free all memory associated to an ini dictionary.
Detailed Description
Parser for ini files.
Author
N. Devillard
Definition in file iniparser.c.
Macro Definition Documentation
ASCIILINESZ
#define ASCIILINESZ (1024)
Definition at line 14 of file iniparser.c.
INI_INVALID_KEY
#define INI_INVALID_KEY ((char*)-1)
Definition at line 15 of file iniparser.c.
Typedef Documentation
line_status
typedef enum _line_status_ line_status
This enum stores the status for each parsed line (internal use only).
Enumeration Type Documentation
_line_status_
enum _line_status_
This enum stores the status for each parsed line (internal use only).
Enumerator
LINE_UNPROCESSED
LINE_ERROR
LINE_EMPTY
LINE_COMMENT
LINE_SECTION
LINE_VALUE
Definition at line 23 of file iniparser.c.
Function Documentation
iniparser_dump()
void iniparser_dump (const dictionary * d, FILE * f)
Dump a dictionary to an opened file pointer.
Parameters
d Dictionary to dump.
f Opened file pointer to dump to.
Returns
void
This function prints out the contents of a dictionary, one element by line, onto the provided file pointer. It is OK to specify stderr or stdout as output files. This function is meant for debugging purposes mostly.
Definition at line 194 of file iniparser.c.
References _dictionary_::key, _dictionary_::size, and _dictionary_::val.
iniparser_dump_ini()
void iniparser_dump_ini (const dictionary * d, FILE * f)
Save a dictionary to a loadable ini file.
Parameters
d Dictionary to dump
f Opened file pointer to dump to
Returns
void
This function dumps a given dictionary into a loadable ini file. It is Ok to specify stderr or stdout as output files.
Definition at line 217 of file iniparser.c.
References iniparser_dumpsection_ini(), iniparser_getnsec(), iniparser_getsecname(), _dictionary_::key, _dictionary_::size, and _dictionary_::val.
iniparser_dumpsection_ini()
void iniparser_dumpsection_ini (const dictionary * d, const char * s, FILE * f)
Save a dictionary section to a loadable ini file.
Parameters
d Dictionary to dump
s Section name of dictionary to dump
f Opened file pointer to dump to
Returns
void
This function dumps a given section of a given dictionary into a loadable ini file. It is Ok to specify stderr or stdout as output files.
Definition at line 255 of file iniparser.c.
References ASCIILINESZ, iniparser_find_entry(), _dictionary_::key, _dictionary_::size, and _dictionary_::val.
iniparser_find_entry()
int iniparser_find_entry (const dictionary * ini, const char * entry)
Finds out if a given entry exists in a dictionary.
Parameters
ini Dictionary to search
entry Name of the entry to look for
Returns
integer 1 if entry exists, 0 otherwise
Finds out if a given entry exists in the dictionary. Since sections are stored as keys with NULL associated values, this is the only way of querying for the presence of sections in a dictionary.
Definition at line 503 of file iniparser.c.
References INI_INVALID_KEY, and iniparser_getstring().
iniparser_freedict()
void iniparser_freedict (dictionary * d)
Free all memory associated to an ini dictionary.
Parameters
d Dictionary to free
Returns
void
Free all memory associated to an ini dictionary. It is mandatory to call this function before the dictionary object gets out of the current context.
Definition at line 757 of file iniparser.c.
References dictionary_del().
iniparser_getboolean()
int iniparser_getboolean (const dictionary * d, const char * key, int notfound)
Get the string associated to a key, convert to a boolean.
Parameters
d Dictionary to search
key Key string to look for
notfound Value to return in case of error
Returns
integer
This function queries a dictionary for a key. A key as read from an ini file is given as "section:key". If the key cannot be found, the notfound value is returned.
A true boolean is found if one of the following is matched:
A string starting with 'y'
A string starting with 'Y'
A string starting with 't'
A string starting with 'T'
A string starting with '1'
A false boolean is found if one of the following is matched:
A string starting with 'n'
A string starting with 'N'
A string starting with 'f'
A string starting with 'F'
A string starting with '0'
The notfound value returned if no boolean is identified, does not necessarily have to be 0 or 1.
Definition at line 474 of file iniparser.c.
References INI_INVALID_KEY, and iniparser_getstring().
iniparser_getdouble()
double iniparser_getdouble (const dictionary * d, const char * key, double notfound)
Get the string associated to a key, convert to a double.
Parameters
d Dictionary to search
key Key string to look for
notfound Value to return in case of error
Returns
double
This function queries a dictionary for a key. A key as read from an ini file is given as "section:key". If the key cannot be found, the notfound value is returned.
Definition at line 433 of file iniparser.c.
References INI_INVALID_KEY, and iniparser_getstring().
iniparser_getint()
int iniparser_getint (const dictionary * d, const char * key, int notfound)
Get the string associated to a key, convert to an int.
Parameters
d Dictionary to search
key Key string to look for
notfound Value to return in case of error
Returns
integer
This function queries a dictionary for a key. A key as read from an ini file is given as "section:key". If the key cannot be found, the notfound value is returned.
Supported values for integers include the usual C notation so decimal, octal (starting with 0) and hexadecimal (starting with 0x) are supported. Examples:
"42" -> 42 "042" -> 34 (octal -> decimal) "0x42" -> 66 (hexa -> decimal)
Warning: the conversion may overflow in various ways. Conversion is totally outsourced to strtol(), see the associated man page for overflow handling.
Credits: Thanks to A. Becker for suggesting strtol()
Definition at line 411 of file iniparser.c.
References INI_INVALID_KEY, and iniparser_getstring().
iniparser_getnsec()
int iniparser_getnsec (const dictionary * d)
Get number of sections in a dictionary.
Parameters
d Dictionary to examine
Returns
int Number of sections found in dictionary
This function returns the number of sections found in a dictionary. The test to recognize sections is done on the string stored in the dictionary: a section name is given as "section" whereas a key is stored as "section:key", thus the test looks for entries that do not contain a colon.
This clearly fails in the case a section name contains a colon, but this should simply be avoided.
This function returns -1 in case of error.
Definition at line 128 of file iniparser.c.
References _dictionary_::key, and _dictionary_::size.
iniparser_getseckeys()
const char** iniparser_getseckeys (const dictionary * d, const char * s, const char ** keys)
Get the number of keys in a section of a dictionary.
Parameters
d Dictionary to examine
s Section name of dictionary to examine
keys Already allocated array to store the keys in
Returns
The pointer passed as keys argument or NULL in case of error
This function queries a dictionary and finds all keys in a given section. The keys argument should be an array of pointers which size has been determined by calling iniparser_getsecnkeys function prior to this one.
Each pointer in the returned char pointer-to-pointer is pointing to a string allocated in the dictionary; do not free or modify them.
Definition at line 330 of file iniparser.c.
References ASCIILINESZ, iniparser_find_entry(), _dictionary_::key, and _dictionary_::size.
iniparser_getsecname()
const char* iniparser_getsecname (const dictionary * d, int n)
Get name for section n in a dictionary.
Parameters
d Dictionary to examine
n Section number (from 0 to nsec-1).
Returns
Pointer to char string
This function locates the n-th section in a dictionary and returns its name as a pointer to a string statically allocated inside the dictionary. Do not free or modify the returned string!
This function returns NULL in case of error.
Definition at line 159 of file iniparser.c.
References _dictionary_::key, and _dictionary_::size.
iniparser_getsecnkeys()
int iniparser_getsecnkeys (const dictionary * d, const char * s)
Get the number of keys in a section of a dictionary.
Parameters
d Dictionary to examine
s Section name of dictionary to examine
Returns
Number of keys in section
Definition at line 289 of file iniparser.c.
References ASCIILINESZ, iniparser_find_entry(), _dictionary_::key, and _dictionary_::size.
iniparser_getstring()
const char* iniparser_getstring (const dictionary * d, const char * key, const char * def)
Get the string associated to a key.
Parameters
d Dictionary to search
key Key string to look for
def Default value to return if key not found.
Returns
pointer to statically allocated character string
This function queries a dictionary for a key. A key as read from an ini file is given as "section:key". If the key cannot be found, the pointer passed as 'def' is returned. The returned char pointer is pointing to a string allocated in the dictionary, do not free or modify it.
Definition at line 370 of file iniparser.c.
References ASCIILINESZ, dictionary_get(), and strlwc().
iniparser_load()
dictionary* iniparser_load (const char * ininame)
Parse an ini file and return an allocated dictionary object.
Parameters
ininame Name of the ini file to read.
Returns
Pointer to newly allocated dictionary
This is the parser for ini files. This function is called, providing the name of the file to be read. It returns a dictionary object that should not be accessed directly, but through accessor functions instead.
The returned dictionary must be freed using iniparser_freedict().
Definition at line 640 of file iniparser.c.
References ASCIILINESZ, dictionary_del(), and dictionary_new().
iniparser_set()
int iniparser_set (dictionary * ini, const char * entry, const char * val)
Set an entry in a dictionary.
Parameters
ini Dictionary to modify.
entry Entry to modify (entry name)
val New value to associate to the entry.
Returns
int 0 if Ok, -1 otherwise.
If the given entry can be found in the dictionary, it is modified to contain the provided value. If it cannot be found, the entry is created. It is Ok to set val to NULL.
Definition at line 525 of file iniparser.c.
References ASCIILINESZ, dictionary_set(), and strlwc().
iniparser_unset()
void iniparser_unset (dictionary * ini, const char * entry)
Delete an entry in a dictionary.
Parameters
ini Dictionary to modify
entry Entry to delete (entry name)
Returns
void
If the given entry can be found, it is deleted from the dictionary.
Definition at line 541 of file iniparser.c.
References ASCIILINESZ, dictionary_unset(), and strlwc().
strlwc()
const char* strlwc (const char * in, char * out, unsigned len)
Convert a string to lowercase.
Parameters
in String to convert.
out Output buffer.
len Size of the out buffer.
Returns
ptr to the out buffer or NULL if an error occured.
This function convert a string into lowercase. At most len - 1 elements of the input string will be converted.
Definition at line 44 of file iniparser.c.
strstrip()
unsigned strstrip (char * s)
Remove blanks at the beginning and the end of a string.
Parameters
str String to parse and alter.
Returns
unsigned New size of the string.
Definition at line 90 of file iniparser.c.