KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/int_tp/int_tp_gbox.f File Reference
int_tp_gbox.f File Reference
Functions/Subroutines
subroutine get_gen_box (xe, nelx, ye, nely, ze, nelz, lmax, name3)
subroutine getbox (x, nelx, y, nely, z, nelz, nfld, if3d)
subroutine geti1 (i, iend, io)
subroutine geti2 (i1, i2, iend, io)
subroutine geti3 (i1, i2, i3, iend, io)
subroutine getr2 (r1, r2, iend, io)
subroutine getr3 (r1, r2, r3, iend, io)
subroutine getrv (r, n, iend, io)
subroutine getiv (r, n, iend, io)
subroutine getcv0 (c, m, n, iend, io)
subroutine getcv (c, m, n, iend, io)
subroutine gets (c, n, iend, io)
subroutine get_multi_seg (nelxyz, x, y, z, m, if3d)
subroutine geometric_x (x, n, x0, x1, gain)
subroutine get_xyz_distribution (x, nelx)
subroutine scannocom (iend, infile)
function ilsum (x, n)
subroutine iint (x, n)
subroutine exitt
subroutine ifill (x, c, n)
subroutine cfill (x, c, n)
subroutine cadd (x, c, n)
integer function indx1 (S1, S2, L2)
Function/Subroutine Documentation
subroutine cadd (real, dimension(1) x, real c, n)
Definition at line 634 of file int_tp_gbox.f.
References i, and n.
subroutine cfill (real, dimension(1) x, real c, n)
Definition at line 626 of file int_tp_gbox.f.
References i, and n.
subroutine exitt ()
Definition at line 612 of file int_tp_gbox.f.
References exit().
subroutine geometric_x (real, dimension(0:n) x, n, x0, x1, gain)
Definition at line 506 of file int_tp_gbox.f.
References i, n, and scale().
subroutine get_gen_box (real, dimension(0:1) xe, nelx, real, dimension(0:1) ye, nely, real, dimension(0:1) ze, nelz, lmax, character*3 name3)
Definition at line 3 of file int_tp_gbox.f.
References blank(), exitt(), getbox(), geti1(), and gets().
subroutine get_multi_seg (integer, dimension(3) nelxyz, real, dimension(0:m) x, real, dimension(0:m) y, real, dimension(0:m) z, m, logical if3d)
Definition at line 443 of file int_tp_gbox.f.
References exit(), geometric_x(), geti1(), getiv(), getrv(), and ilsum().
subroutine get_xyz_distribution (real, dimension(0:1) x, nelx)
Definition at line 525 of file int_tp_gbox.f.
References cadd(), cmult(), i, and scale().
subroutine getbox (real, dimension(0:1) x, nelx, real, dimension(0:1) y, nely, real, dimension(0:1) z, nelz, nfld, logical if3d)
Definition at line 55 of file int_tp_gbox.f.
References exitt(), geti2(), geti3(), getr2(), getr3(), getrv(), gets(), and scale().
subroutine getcv (character*1, dimension(m,n) c, m, n, iend, io)
Definition at line 397 of file int_tp_gbox.f.
References i, j, n, and scannocom().
subroutine getcv0 (character*1, dimension(m,n) c, m, n, iend, io)
Definition at line 368 of file int_tp_gbox.f.
References i, j, n, and scannocom().
subroutine geti1 (i, iend, io)
Definition at line 248 of file int_tp_gbox.f.
References i, and scannocom().
subroutine geti2 (i1, i2, iend, io)
Definition at line 260 of file int_tp_gbox.f.
References scannocom().
subroutine geti3 (i1, i2, i3, iend, io)
Definition at line 272 of file int_tp_gbox.f.
References scannocom().
subroutine getiv (integer, dimension(n) r, n, iend, io)
Definition at line 338 of file int_tp_gbox.f.
References ifill(), j, n, and scannocom().
subroutine getr2 (r1, r2, iend, io)
Definition at line 284 of file int_tp_gbox.f.
References scannocom().
subroutine getr3 (r1, r2, r3, iend, io)
Definition at line 296 of file int_tp_gbox.f.
References scannocom().
subroutine getrv (real, dimension(n) r, n, iend, io)
Definition at line 308 of file int_tp_gbox.f.
References cfill(), j, n, and scannocom().
subroutine gets (character*1, dimension(n) c, n, iend, io)
Definition at line 429 of file int_tp_gbox.f.
References n, and scannocom().
subroutine ifill (integer, dimension(1) x, integer c, n)
Definition at line 618 of file int_tp_gbox.f.
References i, and n.
subroutine iint (integer, dimension(1) x, n)
Definition at line 604 of file int_tp_gbox.f.
References i, and n.
function ilsum (integer, dimension(1) x, n)
Definition at line 595 of file int_tp_gbox.f.
References i, ilsum(), and n.
integer function indx1 (character*80 S1, character*80 S2, L2)
Definition at line 642 of file int_tp_gbox.f.
References i, and indx1().
subroutine scannocom (iend, infile)
Definition at line 557 of file int_tp_gbox.f.
References blank(), indx1(), and ltrunc().