KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/int_tp/int_tp.f File Reference
int_tp.f File Reference
Functions/Subroutines
program int_tp
subroutine add2 (x, y, n)
subroutine copy (x, y, n)
subroutine sub2 (x, y, n)
subroutine add2sq (x, y, n)
subroutine izero (x, n)
subroutine rzero (x, n)
subroutine cmult (x, c, n)
subroutine transpose (a, lda, b, ldb)
subroutine blank (x, n)
function glmin (x, n)
function glmax (x, n)
function ltrunc (string, l)
subroutine chcopy (a, b, n)
logical function if_byte_swap_test (bytetest)
subroutine get_old_data (x, nx, ny, nz, nel, nfld, if_byte_sw, if3d, fname, iffbin, ifbyte, ierr)
subroutine get_bin_data (x, nx, ny, nz, nel, nfld, if_byte_sw, if3d)
subroutine get_bin_data2 (x, nx, ny, nz, nel, nfld, if_byte_sw, if3d)
subroutine read_bin_u (u, nx, ny, nz, nel, nfld, ndim, if_byte_sw, ifx, ifu)
subroutine get_data (x, nx, ny, nz, nel, nfld, if3d)
subroutine read_u (u, nx, ny, nz, nel, nfld)
subroutine out_data (x, n, if_byte_sw, fname, y)
subroutine stats (x, n, name)
subroutine dnorm (d2, di, x1, x2, n)
subroutine set_interpolation_ops (xe, nelx, ye, nely, ze, nelz, nx, ny, nz, xm, mx, ym, my, zm, mz, if3d)
subroutine set_interpolation_ops_1d (jx, nx, pe, xe, nelx, xm, mx, iftranspose)
subroutine get_new_geom (xm, mx, ym, my, zm, mz, nenx, neny, nenz, mmax, if3d, iuniform)
subroutine get_uni_geo (xm, mx, ym, my, zm, mz, mmax, if3d)
subroutine get_nonuni_geo (xm, mx, ym, my, zm, mz, mmax, if3d)
subroutine get_gen_box_new (xm, mx, ym, my, zm, mz, nelx, nely, nelz, mmax, if3d)
subroutine get_gen_box_new_1d (xm, mx, nx1, xe, nel, mmax, name3)
subroutine tp_interp (uout, mx, my, mz, nfld, uin, nx, ny, nz, nelx, nely, nelz, if3d)
subroutine tp_interp_3d (uout, mx, my, mz, nfld, uin, nx, ny, nz, nelx, nely, nelz)
subroutine tp_interp_2d (uout, mx, my, nfld, uin, nx, ny, nelx, nely)
subroutine get_nfld (nfld, s132, nel, if3d)
subroutine parse_hdr (nfld, hdr, nel, if3d, ifx, ifu)
subroutine xyz_chk (u, nx, ny, nz, nel, nfld, if3d)
subroutine outmat (a, m, n, name6, ie)
subroutine lex2sem_fld (v, nr, ns, nt, nelx, nely, nelz, nfld, if3d, u)
subroutine sem_out (uw, uo, nfld, nout, mx, my, mz, nelx, nely, nelz, ifile, if3d)
subroutine outfld_fm (uw, nx1, ny1, nz1, nelx, nely, nelz, nfld, if3d)
subroutine outfld_unf (uw, nx1, ny1, nz1, nelx, nely, nelz, nfld, if3d, ifile)
subroutine tp_out (uout, nfld, nout, ifile)
subroutine outu (u, nx, ny, nz, nel, nfld)
Function/Subroutine Documentation
subroutine add2 (real, dimension(1) x, real, dimension(1) y, n)
Definition at line 113 of file int_tp.f.
References i, and n.
subroutine add2sq (real, dimension(1) x, real, dimension(1) y, n)
Definition at line 137 of file int_tp.f.
References i, and n.
subroutine blank (character*1, dimension(1) x, n)
Definition at line 180 of file int_tp.f.
References i, and n.
subroutine chcopy (character*1, dimension(1) a, character*1, dimension(1) b, n)
Definition at line 227 of file int_tp.f.
References i, and n.
subroutine cmult (real, dimension(1) x, real c, n)
Definition at line 161 of file int_tp.f.
References i, and n.
subroutine copy (real, dimension(1) x, real, dimension(1) y, n)
Definition at line 121 of file int_tp.f.
References i, and n.
subroutine dnorm (d2, di, real, dimension(n) x1, real, dimension(n) x2, n)
Definition at line 556 of file int_tp.f.
References i, n, nx, and nz.
subroutine get_bin_data (real*4, dimension(1) x, nx, ny, nz, nel, nfld, logical if_byte_sw, logical if3d)
Definition at line 291 of file int_tp.f.
References blank(), byte_read, byte_reverse, exitt(), get_nfld(), n, nx, and nz.
subroutine get_bin_data2 (real*4, dimension(1) x, nx, ny, nz, nel, nfld, logical if_byte_sw, logical if3d)
Definition at line 342 of file int_tp.f.
References blank(), byte_read, exit(), nx, nz, parse_hdr(), and read_bin_u().
subroutine get_data (real, dimension(1) x, nx, ny, nz, nel, nfld, logical if3d)
Definition at line 446 of file int_tp.f.
References blank(), exitt(), get_nfld(), nx, nz, and read_u().
subroutine get_gen_box_new (real, dimension(0:mmax) xm, mx, real, dimension(0:mmax) ym, my, real, dimension(0:mmax) zm, mz, nelx, nely, nelz, mmax, logical if3d)
Definition at line 832 of file int_tp.f.
References get_gen_box(), get_gen_box_new_1d(), and nx.
subroutine get_gen_box_new_1d (real, dimension(0:mmax) xm, mx, nx1, real, dimension(0:nel) xe, nel, mmax, character*3 name3)
Definition at line 860 of file int_tp.f.
References exitt(), i, nx, nz, and zwgll().
subroutine get_new_geom (real, dimension(0:mmax) xm, mx, real, dimension(0:mmax) ym, my, real, dimension(0:mmax) zm, mz, nenx, neny, nenz, mmax, logical if3d, iuniform)
Definition at line 681 of file int_tp.f.
References get_gen_box_new(), get_nonuni_geo(), and get_uni_geo().
subroutine get_nfld (nfld, character*132 s132, nel, logical if3d)
Definition at line 1037 of file int_tp.f.
References exitt(), and i.
subroutine get_nonuni_geo (real, dimension(0:lmax) xm, mx, real, dimension(0:lmax) ym, my, real, dimension(0:lmax) zm, mz, mmax, logical if3d)
Definition at line 787 of file int_tp.f.
References exit(), exitt(), and i.
subroutine get_old_data (real, dimension(1) x, nx, ny, nz, nel, nfld, if_byte_sw, if3d, character*40 fname, logical iffbin, logical ifbyte, ierr)
Definition at line 255 of file int_tp.f.
References byte_close, byte_open, chcopy(), get_bin_data(), get_bin_data2(), get_data(), izero(), ltrunc(), nx, and nz.
subroutine get_uni_geo (real, dimension(0:mmax) xm, mx, real, dimension(0:mmax) ym, my, real, dimension(0:mmax) zm, mz, mmax, logical if3d)
Definition at line 697 of file int_tp.f.
References exit(), i, nx, and nz.
function glmax (real, dimension(1) x, n)
Definition at line 200 of file int_tp.f.
References glmax(), i, and n.
function glmin (real, dimension(1) x, n)
Definition at line 188 of file int_tp.f.
References glmin(), i, and n.
logical function if_byte_swap_test (real*4 bytetest)
Definition at line 234 of file int_tp.f.
References if_byte_swap_test().
program int_tp ()
Definition at line 2 of file int_tp.f.
References blank(), exit(), get_gen_box(), get_new_geom(), get_old_data(), n, nx, nz, sem_out(), set_interpolation_ops(), tp_interp(), tp_out(), and xyz_chk().
subroutine izero (integer, dimension(1) x, n)
Definition at line 145 of file int_tp.f.
References i, and n.
subroutine lex2sem_fld (real, dimension(0:nr,0:ns,0:nt,nfld,1) v, nr, ns, nt, nelx, nely, nelz, nfld, logical if3d, real, dimension(nr*nelx+1,ns*nely+1,nt*nelz+1,nfld) u)
Definition at line 1219 of file int_tp.f.
References i, and j.
function ltrunc (character*1, dimension(l) string, l)
Definition at line 212 of file int_tp.f.
References i, and ltrunc().
subroutine out_data (real*4, dimension(1) x, n, logical if_byte_sw, character*40 fname, real*4, dimension(1) y)
Definition at line 509 of file int_tp.f.
References byte_close, byte_open, byte_reverse, byte_write, copy(), and n.
subroutine outfld_fm (real, dimension(nx1*ny1*nz1,nfld,1) uw, nx1, ny1, nz1, nelx, nely, nelz, nfld, logical if3d)
Definition at line 1325 of file int_tp.f.
References i.
subroutine outfld_unf (real, dimension(nx1*ny1*nz1,nfld,1) uw, nx1, ny1, nz1, nelx, nely, nelz, nfld, logical if3d, ifile)
Definition at line 1367 of file int_tp.f.
References blank(), byte_close, byte_open, byte_write, chcopy(), i, and izero().
subroutine outmat (real, dimension(m,n) a, m, n, character*6 name6, ie)
Definition at line 1204 of file int_tp.f.
References i, j, and n.
subroutine outu (real*4, dimension(nx*ny*nz,nfld,nel) u, nx, ny, nz, nel, nfld)
Definition at line 1466 of file int_tp.f.
References i, j, nx, and nz.
subroutine parse_hdr (nfld, character*132 hdr, nel, logical if3d, logical ifx, logical ifu)
Definition at line 1100 of file int_tp.f.
References exitt(), i, and j.
subroutine read_bin_u (real*4, dimension(nx*ny*nz,nfld,nel) u, nx, ny, nz, nel, nfld, ndim, logical if_byte_sw, logical ifx, logical ifu)
Definition at line 396 of file int_tp.f.
References byte_read, byte_reverse, copy(), i, j, n, nx, and nz.
subroutine read_u (real*4, dimension(nx*ny*nz,nfld,nel) u, nx, ny, nz, nel, nfld)
Definition at line 490 of file int_tp.f.
References exitt(), i, nx, nz, and tmp.
subroutine rzero (real, dimension(1) x, n)
Definition at line 153 of file int_tp.f.
References i, and n.
subroutine sem_out (real, dimension(1) uw, real, dimension(nout,nfld) uo, nfld, nout, mx, my, mz, nelx, nely, nelz, ifile, logical if3d)
Definition at line 1279 of file int_tp.f.
References lex2sem_fld(), nx, nz, outfld_fm(), and outfld_unf().
subroutine set_interpolation_ops (real, dimension(0:nelx) xe, nelx, real, dimension(0:nely) ye, nely, real, dimension(0:nelz) ze, nelz, nx, ny, nz, real, dimension(0:mx) xm, mx, real, dimension(0:my) ym, my, real, dimension(0:mz) zm, mz, logical if3d)
Definition at line 572 of file int_tp.f.
References nx, nz, and set_interpolation_ops_1d().
subroutine set_interpolation_ops_1d (real, dimension(lx1*lx1,nelx) jx, nx, integer, dimension(0:nelx) pe, real, dimension(0:nelx) xe, nelx, real, dimension(0:mx) xm, mx, logical iftranspose)
Definition at line 595 of file int_tp.f.
References copy(), exit(), i, i0, igllm(), izero(), j, nx, transpose(), and zwgll().
subroutine stats (real, dimension(n,1) x, n, character*3 name)
Definition at line 537 of file int_tp.f.
References glmax(), glmin(), and n.
subroutine sub2 (real, dimension(1) x, real, dimension(1) y, n)
Definition at line 129 of file int_tp.f.
References i, and n.
subroutine tp_interp (real, dimension(0:mx,0:my,0:mz,nfld) uout, mx, my, mz, nfld, real, dimension (nx,ny,nz,nfld,nelx,nely,nelz) uin, nx, ny, nz, nelx, nely, nelz, logical if3d)
Definition at line 898 of file int_tp.f.
References nx, nz, tp_interp_2d(), and tp_interp_3d().
subroutine tp_interp_2d (real, dimension(0:mx,0:my,nfld) uout, mx, my, nfld, real, dimension (nx,ny,nfld,nelx,nely) uin, nx, ny, nelx, nely)
Definition at line 986 of file int_tp.f.
References mxm(), and nx.
subroutine tp_interp_3d (real, dimension(0:mx,0:my,0:mz,nfld) uout, mx, my, mz, nfld, real, dimension (nx,ny,nz,nfld,nelx,nely,nelz) uin, nx, ny, nz, nelx, nely, nelz)
Definition at line 915 of file int_tp.f.
References mxm(), nx, and nz.
subroutine tp_out (real, dimension(nout,nfld) uout, nfld, nout, ifile)
Definition at line 1431 of file int_tp.f.
References i.
subroutine transpose (real, dimension(lda,1) a, lda, real, dimension(ldb,1) b, ldb)
Definition at line 169 of file int_tp.f.
References i, and j.
subroutine xyz_chk (real, dimension(nx,ny,nz,nfld,nel) u, nx, ny, nz, nel, nfld, if3d)
Definition at line 1179 of file int_tp.f.
References i, n, nx, and nz.