KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/cmt/intpdiff.f File Reference
intpdiff.f File Reference
Functions/Subroutines
subroutine compute_gradients (e)
subroutine set_dealias_face
subroutine set_alias_rx (istp)
subroutine gradm11_t (grad, uxyz, csgn, e)
subroutine gradm1_t (u, ux, uy, uz)
Function/Subroutine Documentation
subroutine compute_gradients (integer e)
Definition at line 9 of file intpdiff.f.
References i, local_grad2(), and local_grad3().
subroutine gradm11_t (real, dimension(lxyz) grad, real, dimension(lxyz,ndim) uxyz, csgn, integer e)
Definition at line 192 of file intpdiff.f.
References add2(), cmult(), i, local_grad2_t(), local_grad3_t(), ly1, lz1, n, and rzero().
subroutine gradm1_t (real, dimension(lxyz,*) u, real, dimension(lxyz,*) ux, real, dimension(lxyz,*) uy, real, dimension(lxyz,*) uz)
Definition at line 246 of file intpdiff.f.
References i, local_grad2_t(), local_grad3_t(), ly1, lz1, and n.
subroutine set_alias_rx (istp)
Definition at line 116 of file intpdiff.f.
References copy(), i, and zwgll().
subroutine set_dealias_face ()
Definition at line 69 of file intpdiff.f.
References copy(), i, and zwgl().