KTH framework for Nek5000 toolboxes; testing version: Toolbox/io/io_tools/io_tools.f File Reference
io_tools.f File Reference
Framework for Nek5000 toolboxes » Toolbox » Input/output module » I/O tools
Set of I/O related tools for KTH modules.
Functions/Subroutines
subroutine io_register ()
Register io tool module.
subroutine io_file_freeid (iunit, ierr)
Get free file unit number and store max unit value.
subroutine io_file_close ()
Close all opened files up to sotred max unit numer.
subroutine io_mfo_fname (fname, bname, prefix, ierr)
Generate file name according to nek rulles without opening the file.
subroutine io_mbyte_open (hname, ierr)
Open field file.
subroutine io_mbyte_close (ierr)
Close field file.
subroutine io_mfov (offs, lvx, lvy, lvz, lnx, lny, lnz, lnel, lnelg, lndim)
Write single vector to the file.
subroutine io_mfos (offs, lvs, lnx, lny, lnz, lnel, lnelg, lndim)
Write single scalar to the file.
subroutine io_mfiv (offs, uf, vf, wf, lnx, lny, lnz, lnel, ifskip)
Read vector filed from the file.
subroutine io_mfis (offs, uf, lnx, lny, lnz, lnel, ifskip)
Read scalar filed from the file.
Detailed Description
Set of I/O related tools for KTH modules.
Author
Adam Peplinski
Date
Mar 7, 2016
Definition in file io_tools.f.
Function/Subroutine Documentation
io_mfiv()
subroutine io_mfiv (integer*8 offs, real, dimension(lnx*lny*lnz,lnel) uf, real, dimension(lnx*lny*lnz,lnel) vf, real, dimension(lnx*lny*lnz,lnel) wf, integer lnx, integer lny, integer lnz, integer lnel, logical ifskip)
Read vector filed from the file.
This is version of mfi_getv that does not perform interpolation and allows to specify element size.
Parameters
[in,out] offs offset of global vector beginning
[out] uf,vf,wf vector field compinents
[in] lnx,lny,lnz element size
[in] lnel number of elements
[in] ifskip reading flag (for non-mpi formats)
Remarks
This routine uses global scratch space VRTHOV and SCRNS
Definition at line 457 of file io_tools.f.
References bcast(), byte_read, byte_read_mpi(), byte_reverse, byte_reverse8, byte_set_view(), copy(), copy4r(), csend(), err_chk(), gllel(), gllnid(), lim_chk(), mntr_abort(), msgwait(), nekgsync(), and rzero().