KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/ivec.c File Reference
ivec.c File Reference
#include <stdio.h>
#include <math.h>
#include <float.h>
#include <limits.h>
#include "const.h"
#include "types.h"
#include "ivec.h"
#include "error.h"
#include "comm.h"
Macros
#define SORT_OPT 6
#define SORT_STACK 500
Functions
void ivec_lb_ub (register int *arg1, register int n, int *lb, int *ub)
int * ivec_copy (register int *arg1, register int *arg2, register int n)
void ivec_zero (register int *arg1, register int n)
void ivec_comp (register int *arg1, register int n)
void ivec_neg_one (register int *arg1, register int n)
void ivec_pos_one (register int *arg1, register int n)
void ivec_c_index (register int *arg1, register int n)
void ivec_fortran_index (register int *arg1, register int n)
void ivec_set (register int *arg1, register int arg2, register int n)
int ivec_cmp (register int *arg1, register int *arg2, register int n)
void ivec_max (register int *arg1, register int *arg2, register int n)
void ivec_min (register int *arg1, register int *arg2, register int n)
void ivec_mult (register int *arg1, register int *arg2, register int n)
void ivec_add (register int *arg1, register int *arg2, register int n)
void ivec_lxor (register int *arg1, register int *arg2, register int n)
void ivec_xor (register int *arg1, register int *arg2, register int n)
void ivec_or (register int *arg1, register int *arg2, register int n)
void ivec_lor (register int *arg1, register int *arg2, register int n)
void ivec_or3 (register int *arg1, register int *arg2, register int *arg3, register int n)
void ivec_and (register int *arg1, register int *arg2, register int n)
void ivec_land (register int *arg1, register int *arg2, register int n)
void ivec_and3 (register int *arg1, register int *arg2, register int *arg3, register int n)
int ivec_sum (register int *arg1, register int n)
int ivec_reduce_and (register int *arg1, register int n)
int ivec_reduce_or (register int *arg1, register int n)
int ivec_prod (register int *arg1, register int n)
int ivec_u_sum (register unsigned *arg1, register int n)
int ivec_lb (register int *arg1, register int n)
int ivec_ub (register int *arg1, register int n)
int ivec_split_buf (int *buf1, int **buf2, register int size)
void ivec_non_uniform (int *arg1, int *arg2, register int n, register int *arg3)
vfp ivec_fct_addr (register int type)
void ivec_sort (register int *ar, register int size)
void ivec_sort_companion (register int *ar, register int *ar2, register int size)
void ivec_sort_companion_hack (register int *ar, register int **ar2, register int size)
void SMI_sort (void *ar1, void *ar2, int size, int type)
int ivec_linear_search (register int item, register int *list, register int n)
int ivec_binary_search (register int item, register int *list, register int rh)
void rvec_copy (register REAL *arg1, register REAL *arg2, register int n)
void rvec_zero (register REAL *arg1, register int n)
void rvec_one (register REAL *arg1, register int n)
void rvec_neg_one (register REAL *arg1, register int n)
void rvec_set (register REAL *arg1, register REAL arg2, register int n)
void rvec_scale (register REAL *arg1, register REAL arg2, register int n)
void rvec_add (register REAL *arg1, register REAL *arg2, register int n)
REAL rvec_dot (register REAL *arg1, register REAL *arg2, register int n)
void rvec_axpy (register REAL *arg1, register REAL *arg2, register REAL scale, register int n)
void rvec_mult (register REAL *arg1, register REAL *arg2, register int n)
void rvec_max (register REAL *arg1, register REAL *arg2, register int n)
void rvec_max_abs (register REAL *arg1, register REAL *arg2, register int n)
void rvec_min (register REAL *arg1, register REAL *arg2, register int n)
void rvec_min_abs (register REAL *arg1, register REAL *arg2, register int n)
void rvec_exists (register REAL *arg1, register REAL *arg2, register int n)
vfp rvec_fct_addr (register int type)
void rvec_sort (register REAL *ar, register int Size)
void rvec_sort_companion (register REAL *ar, register int *ar2, register int Size)
int rvec_binary_search (register REAL item, register REAL *list, register int rh)
Macro Definition Documentation
#define SORT_OPT 6
Definition at line 40 of file ivec.c.
#define SORT_STACK 500
Definition at line 41 of file ivec.c.
Function Documentation
void ivec_add (register int * arg1, register int * arg2, register int n)
Definition at line 287 of file ivec.c.
void ivec_and (register int * arg1, register int * arg2, register int n)
Definition at line 384 of file ivec.c.
void ivec_and3 (register int * arg1, register int * arg2, register int * arg3, register int n)
Definition at line 416 of file ivec.c.
int ivec_binary_search (register int item, register int * list, register int rh)
Definition at line 1141 of file ivec.c.
void ivec_c_index (register int * arg1, register int n)
Definition at line 168 of file ivec.c.
References i.
int ivec_cmp (register int * arg1, register int * arg2, register int n)
Definition at line 222 of file ivec.c.
References FALSE, and TRUE.
void ivec_comp (register int * arg1, register int n)
Definition at line 120 of file ivec.c.
int* ivec_copy (register int * arg1, register int * arg2, register int n)
Definition at line 87 of file ivec.c.
vfp ivec_fct_addr (register int type)
Definition at line 647 of file ivec.c.
References ivec_add(), ivec_and(), ivec_land(), ivec_lor(), ivec_lxor(), ivec_max(), ivec_min(), ivec_mult(), ivec_non_uniform(), ivec_or(), ivec_xor(), n, ptr, and tmp.
void ivec_fortran_index (register int * arg1, register int n)
Definition at line 187 of file ivec.c.
References i.
void ivec_land (register int * arg1, register int * arg2, register int n)
Definition at line 400 of file ivec.c.
int ivec_lb (register int * arg1, register int n)
Definition at line 533 of file ivec.c.
References MIN.
void ivec_lb_ub (register int * arg1, register int n, int * lb, int * ub)
Definition at line 60 of file ivec.c.
References MAX, and MIN.
int ivec_linear_search (register int item, register int * list, register int n)
Definition at line 1122 of file ivec.c.
References tmp.
void ivec_lor (register int * arg1, register int * arg2, register int n)
Definition at line 351 of file ivec.c.
void ivec_lxor (register int * arg1, register int * arg2, register int n)
Definition at line 303 of file ivec.c.
void ivec_max (register int * arg1, register int * arg2, register int n)
Definition at line 239 of file ivec.c.
References MAX.
void ivec_min (register int * arg1, register int * arg2, register int n)
Definition at line 255 of file ivec.c.
References MIN.
void ivec_mult (register int * arg1, register int * arg2, register int n)
Definition at line 271 of file ivec.c.
void ivec_neg_one (register int * arg1, register int n)
Definition at line 136 of file ivec.c.
void ivec_non_uniform (int * arg1, int * arg2, register int n, register int * arg3)
Definition at line 592 of file ivec.c.
References error_msg_fatal(), i, ivec_add(), ivec_and(), ivec_land(), ivec_lor(), ivec_lxor(), ivec_max(), ivec_min(), ivec_mult(), ivec_or(), ivec_xor(), j, and n.
void ivec_or (register int * arg1, register int * arg2, register int n)
Definition at line 335 of file ivec.c.
void ivec_or3 (register int * arg1, register int * arg2, register int * arg3, register int n)
Definition at line 367 of file ivec.c.
void ivec_pos_one (register int * arg1, register int n)
Definition at line 152 of file ivec.c.
int ivec_prod (register int * arg1, register int n)
Definition at line 493 of file ivec.c.
References tmp.
int ivec_reduce_and (register int * arg1, register int n)
Definition at line 453 of file ivec.c.
References tmp.
int ivec_reduce_or (register int * arg1, register int n)
Definition at line 473 of file ivec.c.
References tmp.
void ivec_set (register int * arg1, register int arg2, register int n)
Definition at line 206 of file ivec.c.
void ivec_sort (register int * ar, register int size)
Definition at line 720 of file ivec.c.
References error_msg_fatal(), SORT_OPT, SORT_STACK, and SWAP.
void ivec_sort_companion (register int * ar, register int * ar2, register int size)
Definition at line 829 of file ivec.c.
References error_msg_fatal(), SORT_OPT, SORT_STACK, and SWAP.
void ivec_sort_companion_hack (register int * ar, register int ** ar2, register int size)
Definition at line 954 of file ivec.c.
References error_msg_fatal(), ptr, SORT_OPT, SORT_STACK, and SWAP.
int ivec_split_buf (int * buf1, int ** buf2, register int size)
Definition at line 575 of file ivec.c.
int ivec_sum (register int * arg1, register int n)
Definition at line 433 of file ivec.c.
References tmp.
int ivec_u_sum (register unsigned * arg1, register int n)
Definition at line 513 of file ivec.c.
References tmp.
int ivec_ub (register int * arg1, register int n)
Definition at line 553 of file ivec.c.
References MAX.
void ivec_xor (register int * arg1, register int * arg2, register int n)
Definition at line 319 of file ivec.c.
void ivec_zero (register int * arg1, register int n)
Definition at line 104 of file ivec.c.
void rvec_add (register REAL * arg1, register REAL * arg2, register int n)
Definition at line 1266 of file ivec.c.
void rvec_axpy (register REAL * arg1, register REAL * arg2, register REAL scale, register int n)
Definition at line 1302 of file ivec.c.
int rvec_binary_search (register REAL item, register REAL * list, register int rh)
Definition at line 1683 of file ivec.c.
void rvec_copy (register REAL * arg1, register REAL * arg2, register int n)
Definition at line 1170 of file ivec.c.
REAL rvec_dot (register REAL * arg1, register REAL * arg2, register int n)
Definition at line 1282 of file ivec.c.
References dot().
void rvec_exists (register REAL * arg1, register REAL * arg2, register int n)
Definition at line 1398 of file ivec.c.
vfp rvec_fct_addr (register int type)
Definition at line 1413 of file ivec.c.
References rvec_add(), rvec_exists(), rvec_max(), rvec_max_abs(), rvec_min(), rvec_min_abs(), and rvec_mult().
void rvec_max (register REAL * arg1, register REAL * arg2, register int n)
Definition at line 1334 of file ivec.c.
References MAX.
void rvec_max_abs (register REAL * arg1, register REAL * arg2, register int n)
Definition at line 1350 of file ivec.c.
void rvec_min (register REAL * arg1, register REAL * arg2, register int n)
Definition at line 1366 of file ivec.c.
References MIN.
void rvec_min_abs (register REAL * arg1, register REAL * arg2, register int n)
Definition at line 1382 of file ivec.c.
void rvec_mult (register REAL * arg1, register REAL * arg2, register int n)
Definition at line 1318 of file ivec.c.
void rvec_neg_one (register REAL * arg1, register int n)
Definition at line 1218 of file ivec.c.
void rvec_one (register REAL * arg1, register int n)
Definition at line 1202 of file ivec.c.
void rvec_scale (register REAL * arg1, register REAL arg2, register int n)
Definition at line 1250 of file ivec.c.
void rvec_set (register REAL * arg1, register REAL arg2, register int n)
Definition at line 1234 of file ivec.c.
void rvec_sort (register REAL * ar, register int Size)
Definition at line 1443 of file ivec.c.
References error_msg_fatal(), SORT_OPT, SORT_STACK, and SWAP.
void rvec_sort_companion (register REAL * ar, register int * ar2, register int Size)
Definition at line 1553 of file ivec.c.
References error_msg_fatal(), ptr, SORT_OPT, SORT_STACK, and SWAP.
void rvec_zero (register REAL * arg1, register int n)
Definition at line 1186 of file ivec.c.
void SMI_sort (void * ar1, void * ar2, int size, int type)
Definition at line 1079 of file ivec.c.
References error_msg_fatal(), ivec_sort(), ivec_sort_companion(), and ivec_sort_companion_hack().