KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/lanczos.c File Reference
lanczos.c File Reference
Functions
rvec_copy (p_k, r_k, n)
rvec_zero (Ap_k, n)
rvec_copy (v_k, r_k, n)
rvec_zero (v_k_old, n)
rvec_zero (w_k, n)
rvec_zero (tmp, n)
while ((rr >rr_limit)&&(k< iter_limit))
rvec_zero (Q[0], n)
for (i=1;i<=k;i++)
if (len_queue(ln_q))
tqli (dv, ev, k, z)
printf ("\n")
printf ("min eval[%d]=%.16e\n", j, dv[j])
rvec_zero (dv_w, n)
for (j=1;j<=k;j++)
matrix_mult (Ap_k, dv_w, n, ia, ja, vals)
for (i=0;i< n;i++)
printf ("approximate eigenvector::\n")
printf ("%d :: %d :: %d\n", n, sizeof(int *), sizeof(double *))
ivec_c_index (companion, n)
rvec_sort_companion (dv_w, companion, n)
printf ("sorted approximate eigenvector::\n")
printf (")\n")
return (color)
int * old_lanczos (int *list, int n, int *ia, int *ja, double *vals)
int * _lanczos (int *list, int n, int *ia, int *ja, double *vals)
Variables
int *int * list
int *int int n
int *int int int * ia
int *int int int int * ja
int *int int int int double * vals
double * r_k =NULL
double * p_k =NULL
double * x_k =NULL
double * Ap_k =NULL
double alpha =0.0
double beta =0.0
double rr =0.0
double rr_limit = rr*RES_LIMIT
double new_rr
double alpha_old =0.0
double beta_old =0.0
int * color = ptr = (int *) bss_malloc(n*INT_LEN)
int * ptr
int iter_limit = MIN(n,CG_LIMIT)
queue_ADT ln_q = new_queue()
struct lanczos_node * ln_ptr
double * dv = (double *) bss_malloc((k+1)*FLOAT_LEN)
double * ev = (double *) bss_malloc((k+1)*FLOAT_LEN)
double * dv_w = (double *) bss_malloc((k+1)*FLOAT_LEN)
double * ev_w = (double *) bss_malloc((k+1)*FLOAT_LEN)
double dmax
double dmin
double ** z = (double **) bss_malloc((k+1)*sizeof(double *))
double ** Q = (double **) bss_malloc((k+1)*sizeof(double *))
double * w_k = (double *) bss_malloc(n*FLOAT_LEN)
double * tmp = (double *) bss_malloc(n*FLOAT_LEN)
double * v_k = (double *) bss_malloc(n*FLOAT_LEN)
double * v_k_old = (double *) bss_malloc(n*FLOAT_LEN)
double la
double lb
int * companion = (int *) bss_malloc(n*INT_LEN)
j =-1
Function Documentation
int* _lanczos (int * list, int n, int * ia, int * ja, double * vals)
Definition at line 364 of file lanczos.c.
References alpha, alpha_old, beta, beta_old, bss_free(), bss_malloc(), color, dequeue(), dmax, dmin, dv, dv_w, enqueue(), ev, ev_w, i, iter_limit, j, la, lb, ln_ptr, ln_q, matrix_mult(), MAX, MIN, n, new_queue(), new_rr, ortho(), printf(), ptr, Q, rr, rr_limit, rvec_copy(), rvec_zero(), tmp, tqli(), v_k, v_k_old, w_k, and z.
for (i = 1; i<=k; i++)
Definition at line 160 of file lanczos.c.
References dequeue(), and i.
for (j = 1; j<=k; j++)
Definition at line 210 of file lanczos.c.
References beta, i, j, matrix_mult(), and printf().
for ()
Definition at line 217 of file lanczos.c.
References beta, bss_malloc(), i, ivec_c_index(), n, printf(), and rvec_sort_companion().
if (len_queue(ln_q))
Definition at line 172 of file lanczos.c.
References beta, bss_malloc(), error_msg_warning(), i, rvec_zero(), and tqli().
ivec_c_index (companion , n)
matrix_mult (Ap_k , dv_w , n , ia , ja , vals)
int* old_lanczos (int * list, int n, int * ia, int * ja, double * vals)
Definition at line 309 of file lanczos.c.
References bss_malloc(), color, i, n, printf(), and ptr.
printf ("\n")
printf ()
printf ("approximate eigenvector::\n")
printf ("%d :: %d :: %d\n" , n , sizeof(int *) , sizeof(double *))
printf ("sorted approximate eigenvector::\n")
printf (")
return (color)
rvec_copy (p_k , r_k , n)
rvec_copy (v_k , r_k , n)
rvec_sort_companion (dv_w , companion , n)
rvec_zero (Ap_k , n)
rvec_zero (v_k_old , n)
rvec_zero (w_k , n)
rvec_zero (tmp , n)
rvec_zero (Q [0], n)
rvec_zero (dv_w , n)
tqli (dv , ev , k , z)
while ((rr >rr_limit)&&(k< iter_limit))
Definition at line 61 of file lanczos.c.
References alpha, alpha_old, beta, beta_old, bss_malloc(), enqueue(), error_msg_warning(), matrix_mult(), MAX, n, new_rr, ortho(), printf(), rr, rvec_copy(), and rvec_zero().
Variable Documentation
double alpha =0.0
Definition at line 14 of file lanczos.c.
double alpha_old =0.0
Definition at line 15 of file lanczos.c.
Ap_k =NULL
Definition at line 13 of file lanczos.c.
beta =0.0
Definition at line 14 of file lanczos.c.
double beta_old =0.0
Definition at line 15 of file lanczos.c.
color[companion[n/2]] = ptr = (int *) bss_malloc(n*INT_LEN)
Definition at line 16 of file lanczos.c.
companion = (int *) bss_malloc(n*INT_LEN)
Definition at line 23 of file lanczos.c.
double dmax
Definition at line 20 of file lanczos.c.
double dmin
Definition at line 20 of file lanczos.c.
dv[0] = (double *) bss_malloc((k+1)*FLOAT_LEN)
Definition at line 20 of file lanczos.c.
dv_w = (double *) bss_malloc((k+1)*FLOAT_LEN)
Definition at line 20 of file lanczos.c.
ev = (double *) bss_malloc((k+1)*FLOAT_LEN)
Definition at line 20 of file lanczos.c.
ev_w = (double *) bss_malloc((k+1)*FLOAT_LEN)
Definition at line 20 of file lanczos.c.
int* int int int* ia
Definition at line 10 of file lanczos.c.
iter_limit = MIN(n,CG_LIMIT)
Definition at line 17 of file lanczos.c.
j =-1
Definition at line 193 of file lanczos.c.
int* int int int int* ja
Definition at line 10 of file lanczos.c.
double la
Definition at line 22 of file lanczos.c.
double lb
Definition at line 22 of file lanczos.c.
int* int* list
Definition at line 10 of file lanczos.c.
struct lanczos_node* ln_ptr
Definition at line 19 of file lanczos.c.
ln_q = new_queue()
Definition at line 18 of file lanczos.c.
int* int int n
Definition at line 10 of file lanczos.c.
double new_rr
Definition at line 14 of file lanczos.c.
p_k =NULL
Definition at line 13 of file lanczos.c.
int * ptr
Definition at line 16 of file lanczos.c.
Q[0] = (double **) bss_malloc((k+1)*sizeof(double *))
Definition at line 20 of file lanczos.c.
r_k =NULL
Definition at line 13 of file lanczos.c.
rr =0.0
Definition at line 14 of file lanczos.c.
rr_limit = rr*RES_LIMIT
Definition at line 14 of file lanczos.c.
tmp = (double *) bss_malloc(n*FLOAT_LEN)
Definition at line 21 of file lanczos.c.
v_k = (double *) bss_malloc(n*FLOAT_LEN)
Definition at line 21 of file lanczos.c.
v_k_old = (double *) bss_malloc(n*FLOAT_LEN)
Definition at line 21 of file lanczos.c.
int* int int int int double* vals
Initial value:
{
  int i,j,k=0
Definition at line 11 of file lanczos.c.
w_k = (double *) bss_malloc(n*FLOAT_LEN)
Definition at line 21 of file lanczos.c.
x_k =NULL
Definition at line 13 of file lanczos.c.
z = (double **) bss_malloc((k+1)*sizeof(double *))
Definition at line 20 of file lanczos.c.