KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/lb_setqvol.f File Reference
lb_setqvol.f File Reference
Functions/Subroutines
subroutine lb_setqvol (flocal, qvol, in, m, isInactive)
subroutine lb_process_items (nin, rdata, flocal, m, nmax)
Function/Subroutine Documentation
lb_process_items()
subroutine lb_process_items (nin, real, dimension(1) rdata, external flocal, m, nmax)
Definition at line 52 of file lb_setqvol.f.
References dnekclock_sync(), exitti(), i8glsum(), iglmax(), iglmin(), lelt, ly1, and lz1.
lb_setqvol()
subroutine lb_setqvol (external flocal, real, dimension(lx1,ly1,lz1,lelv,*) qvol, real, dimension(lx1,ly1,lz1,lelt,*) in, m, integer, dimension(lx1,ly1,lz1,*) isInactive)
Definition at line 3 of file lb_setqvol.f.
References lb_process_items(), lelt, ly1, and lz1.