KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/locglob.f File Reference
locglob.f File Reference
Functions/Subroutines
subroutine locglob
subroutine locglobm (jglb, nglb, mx, mel)
subroutine locglob_lexico (locglob, nglb)
subroutine settol (tol, nx, nel, x, y, z, if3d)
subroutine settol3 (tol, nx, nel, x, y, z)
subroutine settol2 (tol, nx, nel, x, y)
subroutine dssum (uin, wk)
subroutine dsavg (uin, wk)
subroutine setvert2d (glo_num, ngv, mx, nel, vertex, ifcenter, s, snum)
subroutine setvert3d (glo_num, ngv, mx, nel, vertex, skpdat, ifcenter, edge, enum, face, fnum)
subroutine outi6 (glo_num, name4, ngv)
subroutine irank_vec_tally (ind, nn, a, m, n, key, nkey, key2, aa)
subroutine irank_vecx (ind, nn, a, m, n, key, nkey, aa)
Function/Subroutine Documentation
subroutine dsavg (real, dimension(1) uin, real, dimension(1) wk)
Definition at line 335 of file locglob.f.
References i, nx, nz, and rzero().
subroutine dssum (real, dimension(1) uin, real, dimension(1) wk)
Definition at line 315 of file locglob.f.
References i, nx, nz, and rzero().
subroutine irank_vec_tally (integer, dimension(n) ind, nn, integer, dimension(m,n) a, m, n, integer, dimension(nkey) key, nkey, integer, dimension(0:3) key2, integer, dimension(m) aa)
Definition at line 940 of file locglob.f.
References i, icopy(), ituple_sort(), and n.
subroutine irank_vecx (integer, dimension(n) ind, nn, integer, dimension(m,n) a, m, n, integer, dimension(nkey) key, nkey, integer, dimension(m) aa)
Definition at line 1015 of file locglob.f.
References exitt(), i, icopy(), irank(), ituple_sort(), and n.
subroutine locglob ()
Definition at line 3 of file locglob.f.
References i, locglob_lexico(), nx, setvert2d(), and setvert3d().
subroutine locglob_lexico (integer, dimension(1) locglob, nglb)
Definition at line 122 of file locglob.f.
References i, iswap(), j, prs(), settol(), sort(), and swap().
subroutine locglobm (integer, dimension(1) jglb, nglb, mx, mel)
Definition at line 49 of file locglob.f.
References dsset(), i, locglob_lexico(), nx, nz, setvert2d(), and setvert3d().
subroutine outi6 (integer, dimension(1) glo_num, character*4 name4, ngv)
Definition at line 926 of file locglob.f.
subroutine settol (real, dimension(1) tol, nx, nel, real, dimension(1) x, real, dimension(1) y, real, dimension(1) z, logical if3d)
Definition at line 249 of file locglob.f.
References nx, settol2(), and settol3().
subroutine settol2 (real, dimension(1) tol, nx, nel, real, dimension (nx,nx,nel) x, real, dimension (nx,nx,nel) y)
Definition at line 291 of file locglob.f.
References i, j, and nx.
subroutine settol3 (real, dimension(1) tol, nx, nel, real, dimension (nx,nx,nx,nel) x, real, dimension (nx,nx,nx,nel) y, real, dimension (nx,nx,nx,nel) z)
Definition at line 262 of file locglob.f.
References i, j, and nx.
subroutine setvert2d (integer, dimension(1) glo_num, integer ngv, integer mx, nel, integer, dimension(0:1,0:1,nel) vertex, logical ifcenter, integer, dimension(3,9,nel) s, integer, dimension(9*nel) snum)
Definition at line 355 of file locglob.f.
References i, i0, iglmax(), irank_vec_tally(), izero(), and j.
subroutine setvert3d (integer, dimension(1) glo_num, integer ngv, integer mx, nel, integer, dimension(0:1,0:1,0:1,nel) vertex, integer, dimension(6,6) skpdat, logical ifcenter, integer, dimension(0:1,0:1,0:1,3,nel) edge, integer, dimension(12,nel) enum, integer, dimension(3,6,nel) face, integer, dimension(6,nel) fnum)
Definition at line 543 of file locglob.f.
References dsset(), i, i0, icopy(), iglmax(), irank(), irank_vec(), isort(), ivlmax(), j, and outi6().