KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/makeq.f File Reference
makeq.f File Reference
Functions/Subroutines
subroutine makeq
Function/Subroutine Documentation
makeq()
subroutine makeq ()
Definition at line 3 of file makeq.f.
References add2(), admesht(), convab(), convch(), lelt, ly1, lz1, makeabq(), makebdq(), makeq_aux(), sub2(), and wlaplacian().