KTH framework for Nek5000 toolboxes; testing version: Toolbox/utility/grid/map2D/map2D.f File Reference
map2D.f File Reference
3D to 2D element mapping routines
Functions/Subroutines
subroutine map2d_register ()
Register 2D mapping routines.
subroutine map2d_init ()
Initilise map2d module.
subroutine map2d_get ()
Get 3D to 2D element mapping.
subroutine map2d_get_local (ctrs, cell, ninseg, ind, ifseg, lctrs1, lctrs2, nseg, nelsort, tol)
Get local 3D=>2D mapping.
subroutine map2d_get_global (ctrs, owner, cell, ninseg, ind, ifseg, lctrs1, lctrs2, nseg, tol)
Get global 3D=>2D mapping.
subroutine map2d_init_coord
Generate 2D mesh out of 3D one.
Detailed Description
3D to 2D element mapping routines
Partially based on the old statistic code
Note
This code works for extruded meshes only
Author
Adam Peplinski
Date
May 29, 2018
Definition in file map2D.f.
Function/Subroutine Documentation
map2d_get()
subroutine map2d_get
Get 3D to 2D element mapping.
Remarks
This routine uses global scratch space SCRNS , SCRVH and SCRUZ
Definition at line 120 of file map2D.f.
References ifill(), io_file_freeid(), map2d_get_global(), map2d_get_local(), mntr_abort(), mntr_check_abort(), mntr_log(), mntr_logi(), and mntr_tmr_add().
map2d_get_global()
subroutine map2d_get_global (real, dimension(lctrs1,lctrs2) ctrs, integer, dimension(lctrs2) owner, integer, dimension(lctrs2) cell, integer, dimension(lctrs2) ninseg, integer, dimension(lctrs2) ind, logical, dimension(lctrs2) ifseg, integer lctrs1, integer lctrs2, integer nseg, real tol)
Get global 3D=>2D mapping.
Parameters
[in,out] ctrs 2D element centres
[in,out] owner global element ownership (work array)
[in,out] cell local element numberring (work array)
[in,out] ninseg elements in segmen (work array)
[in,out] ind sorting index (work array)
[in,out] ifseg segment borders (work array)
[in] lctrs1,lctrs2 array sizes
[in,out] nseg segments number
[in] tol tolerance to find segment borders
Definition at line 408 of file map2D.f.
References copy(), csend(), iswap_ip(), mntr_abort(), mntr_check_abort(), mntr_logi(), msgwait(), and tuple_sort().
map2d_get_local()
subroutine map2d_get_local (real, dimension(lctrs1,lctrs2) ctrs, integer, dimension(lctrs2) cell, integer, dimension(lctrs2) ninseg, integer, dimension(lctrs2) ind, logical, dimension(lctrs2) ifseg, integer lctrs1, integer lctrs2, integer nseg, integer nelsort, real tol)
Get local 3D=>2D mapping.
Parameters
[out] ctrs 2D element centres
[out] cell local element numberring
[out] ninseg elements in segmen (work array)
[out] ind sorting index (work array)
[out] ifseg segment borders (work array)
[in] lctrs1,lctrs2 array sizes
[out] nseg segments number
[in] nelsort number of local 3D elements to sort
[in] tol tolerance to find segment borders
Definition at line 311 of file map2D.f.
References iswap_ip(), and tuple_sort().
map2d_init()
subroutine map2d_init
Initilise map2d module.
Note
This routine should be called in frame_usr_init
Definition at line 70 of file map2D.f.
References map2d_get(), map2d_init_coord(), mntr_log(), mntr_tmr_add(), and mntr_warn().
map2d_init_coord()
subroutine map2d_init_coord
Generate 2D mesh out of 3D one.
Definition at line 702 of file map2D.f.
References copy(), ifill(), and io_file_freeid().
map2d_register()
subroutine map2d_register
Register 2D mapping routines.
Note
This routine should be called in frame_usr_register
Definition at line 13 of file map2D.f.
References mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), mntr_tmr_add(), mntr_tmr_is_name_reg(), mntr_tmr_reg(), and mntr_warn().