KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/map2.f File Reference
map2.f File Reference
Functions/Subroutines
subroutine mapelpr ()
subroutine set_proc_map ()
subroutine gfdm_elm_to_proc (gllnid, np)
subroutine gfdm_map_2d (map_st, nes, net, num_el, np)
subroutine gfdm_set_pst (ip, is, it, nelbox, nstride_box, nxp, nyp, nzp)
subroutine gfdm_build_global_el_map (gllnid, map_st, nes, net, nelbox, nstride_box, ip, is, it)
subroutine outmati (u, m, n, name6)
subroutine outmati8 (u, m, n, name6)
subroutine get_map
subroutine get_vert
subroutine get_vert_map (vertex, nlv, wk, mdw, ndw, ifgfdm)
subroutine assign_gllnid (gllnid, iunsort, nelgt, nelgv, np)
Function/Subroutine Documentation
assign_gllnid()
subroutine assign_gllnid (integer, dimension(1) gllnid, integer, dimension(1) iunsort, integer nelgt, nelgv, integer np)
Definition at line 642 of file map2.f.
References exitti(), isort(), iswapt_ip(), ivlmax(), and log2().
get_map()
subroutine get_map ()
Definition at line 392 of file map2.f.
References get_vert().
get_vert()
subroutine get_vert ()
Definition at line 399 of file map2.f.
References get_vert_map(), lelt, ly1, and lz1.
get_vert_map()
subroutine get_vert_map (integer, dimension(nlv,1) vertex, nlv, integer, dimension(mdw,ndw) wk, mdw, ndw, logical ifgfdm)
Definition at line 428 of file map2.f.
References assign_gllnid(), bcast(), blank(), byte_close, byte_open, byte_read, byte_reverse, chcopy(), csend(), err_chk(), exitt(), icopy(), iglmax(), iglsum(), irecv(), ltrunc(), msgwait(), and nekgsync().
gfdm_build_global_el_map()
subroutine gfdm_build_global_el_map (integer, dimension(1) gllnid, integer, dimension(nes,net) map_st, nes, net, integer, dimension(3) nelbox, integer, dimension(3) nstride_box, ip, is, it)
Definition at line 322 of file map2.f.
gfdm_elm_to_proc()
subroutine gfdm_elm_to_proc (integer, dimension(1) gllnid, np)
Definition at line 176 of file map2.f.
References exitt(), gfdm_build_global_el_map(), gfdm_map_2d(), and gfdm_set_pst().
gfdm_map_2d()
subroutine gfdm_map_2d (integer, dimension(nes,net) map_st, nes, net, integer, dimension(0:np) num_el, np)
Definition at line 212 of file map2.f.
gfdm_set_pst()
subroutine gfdm_set_pst (ip, is, it, integer, dimension(3) nelbox, integer, dimension(3) nstride_box, nxp, nyp, nzp)
Definition at line 263 of file map2.f.
mapelpr()
subroutine mapelpr ()
Definition at line 3 of file map2.f.
References crecv(), csend(), dnekclock(), dnekclock_sync(), exitt(), iglmax(), iglmin(), and set_proc_map().
outmati()
subroutine outmati (integer, dimension(m,n) u, m, n, character*6 name6)
Definition at line 346 of file map2.f.
References nekgsync().
outmati8()
subroutine outmati8 (integer*8, dimension(m,n) u, m, n, character*6 name6)
Definition at line 369 of file map2.f.
References nekgsync().
set_proc_map()
subroutine set_proc_map ()
Definition at line 106 of file map2.f.
References get_map(), gfdm_elm_to_proc(), igop(), izero(), and lelt.