KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/3rd_party/moab.f File Reference
moab.f File Reference
Functions/Subroutines
subroutine nekmoab_init (comm_f, imesh_instance, partn_handle, fileset_handle, ierr)
subroutine print_tag_values (tagh, nvals, is_v)
subroutine nekmoab_import
subroutine nekmoab_get_instance (imesh_instance, partn, fileset_handle)
subroutine nekmoab_create_tags
subroutine nekmoab_create_find_tag (tag_name, tag_opts, tag_size, tag_datatype, tag_handle, create_if_missing, ierr)
subroutine nekmoab_load
subroutine nekmoab_get_elems ()
subroutine nekmoab_get_gids (imeshh, nekcomm, nid_, globalIdTag, numflu, numoth, nelgv, nelgt, iestart, iecount, ieiter, lglel, gllel, gllnid)
subroutine nekmoab_get_set_infos (imeshh, fileset, nekcomm, matsetTag, numflu, numoth, numsts, iestart, iecount, ieiter, matsets, matids, nelgv, nelgt)
subroutine nekmoab_gllnid (matset, iter, count)
subroutine nekmoab_loadconn (vertex, nelgt, ncrnr)
subroutine nekmoab_loadcoord (x27, y27, z27)
subroutine nekmoab_bc ()
subroutine nekmoab_intbc (bcdata, setHandle, setId, field)
subroutine nekmoab_getelno (handle, elno)
subroutine nekmoab_getglobelno (handle, elno)
subroutine nekmoab_bcs ()
subroutine moab_geometry (xmlo, ymlo, zmlo)
subroutine xml2xc
subroutine permute_and_map (x, x27, nx, nmoab, e)
subroutine nekmoab_export_vars
subroutine nekmoab_import_tagvalues (tagname, is_v, field)
subroutine nekmoab_import_vars (tagh, is_v, field)
subroutine nekmoab_set_tag_avg (iter, tagh, size, count, vals)
subroutine nekmoab_set_tag (iter, tagh, size, count, vals)
subroutine nekmoab_set_int_tag (iter, tagh, size, count, vals)
subroutine nekmoab_set_vertex_tag (iter, tagh, count, vals, ierr)
subroutine nekmoab_get_tag_avg (iter, tagh, size, count, vals, ierr)
subroutine nekmoab_get_tag (iter, tagh, size, count, vals, ierr)
subroutine nekmoab_get_vertex_tag (iter, tagh, count, vals, ierr)
subroutine nekmoab_compute_diagnostics ()
Function/Subroutine Documentation
subroutine moab_geometry (real, dimension(nx1*ny1*nz1,1) xmlo, real, dimension(nx1*ny1*nz1,1) ymlo, real, dimension(nx1*ny1*nz1,1) zmlo)
Definition at line 1231 of file moab.f.
References lelt, nekmoab_loadcoord(), and permute_and_map().
subroutine nekmoab_bc ()
Definition at line 965 of file moab.f.
References ifill(), lelt, and nekmoab_intbc().
subroutine nekmoab_bcs ()
Definition at line 1194 of file moab.f.
References blank(), and lelt.
subroutine nekmoab_compute_diagnostics ()
Definition at line 1941 of file moab.f.
subroutine nekmoab_create_find_tag (character*(*) tag_name, character*(*) tag_opts, integer tag_size, integer tag_datatype, tag_handle, logical create_if_missing, integer ierr)
Definition at line 410 of file moab.f.
subroutine nekmoab_create_tags ()
Definition at line 278 of file moab.f.
References nekmoab_create_find_tag().
subroutine nekmoab_export_vars ()
Definition at line 1386 of file moab.f.
References exitti(), lelt, ly1, lz1, mpi_barrier(), nekmoab_set_tag(), nekmoab_set_tag_avg(), and nekmoab_set_vertex_tag().
subroutine nekmoab_get_elems ()
Definition at line 492 of file moab.f.
References lelt, nekmoab_get_gids(), and nekmoab_get_set_infos().
subroutine nekmoab_get_gids (imeshh, integer nekcomm, integer nid_, globalIdTag, integer numflu, integer numoth, integer nelgv, integer nelgt, integer, dimension(*) iestart, integer, dimension(*) iecount, ieiter, integer, dimension(*) lglel, integer, dimension(*) gllel, integer, dimension(*) gllnid)
Definition at line 536 of file moab.f.
References exitti(), igop(), izero(), lelt, mpi_scan(), nekmoab_create_find_tag(), and nekmoab_set_int_tag().
subroutine nekmoab_get_instance (imesh_instance, partn, fileset_handle)
Definition at line 262 of file moab.f.
subroutine nekmoab_get_set_infos (imeshh, fileset, integer nekcomm, matsetTag, integer numflu, integer numoth, integer numsts, integer, dimension(*) iestart, integer, dimension(*) iecount, ieiter, matsets, integer, dimension(*) matids, integer nelgv, integer nelgt)
Definition at line 711 of file moab.f.
References exitt(), and exitti().
subroutine nekmoab_get_tag (iter, tagh, integer size, integer count, real, dimension(*) vals, integer ierr)
Definition at line 1809 of file moab.f.
subroutine nekmoab_get_tag_avg (iter, tagh, integer size, integer count, real, dimension(*) vals, integer ierr)
Definition at line 1780 of file moab.f.
subroutine nekmoab_get_vertex_tag (iter, tagh, integer count, real, dimension(lx1*ly1*lz1*lelt) vals, integer ierr)
Definition at line 1833 of file moab.f.
References ly1, and lz1.
subroutine nekmoab_getelno (handle, integer elno)
Definition at line 1151 of file moab.f.
References nekmoab_getglobelno().
subroutine nekmoab_getglobelno (handle, integer elno)
Definition at line 1171 of file moab.f.
References exitt().
subroutine nekmoab_gllnid (matset, iter, integer count)
Definition at line 813 of file moab.f.
References exitti().
subroutine nekmoab_import ()
Definition at line 216 of file moab.f.
References chk_nel(), mapelpr(), moab_geometry(), nekmoab_bc(), nekmoab_create_tags(), nekmoab_get_elems(), nekmoab_init(), nekmoab_load(), and xml2xc().
subroutine nekmoab_import_tagvalues (character(*) tagname, integer is_v, real, dimension(lx1,ly1,lz1,lelt) field)
Definition at line 1552 of file moab.f.
References nekmoab_import_vars().
subroutine nekmoab_import_vars (tagh, integer is_v, real, dimension(lx1,ly1,lz1,lelt) field)
Definition at line 1569 of file moab.f.
References exitti(), nekmoab_get_tag_avg(), and nekmoab_get_vertex_tag().
subroutine nekmoab_init (integer comm_f, imesh_instance, partn_handle, fileset_handle, integer ierr)
Definition at line 76 of file moab.f.
References moab_comm_f2c, and mpi_comm_size().
subroutine nekmoab_intbc (integer, dimension(6,lelt,ldimt1) bcdata, setHandle, integer setId, integer field)
Definition at line 1027 of file moab.f.
References faces(), and nekmoab_getelno().
subroutine nekmoab_load ()
Definition at line 450 of file moab.f.
subroutine nekmoab_loadconn (integer, dimension(ncrnr, *) vertex, nelgt, ncrnr)
Definition at line 855 of file moab.f.
subroutine nekmoab_loadcoord (real, dimension(27,*) x27, real, dimension(27,*) y27, real, dimension(27,*) z27)
Definition at line 918 of file moab.f.
subroutine nekmoab_set_int_tag (iter, tagh, integer size, integer count, integer, dimension(*) vals)
Definition at line 1688 of file moab.f.
subroutine nekmoab_set_tag (iter, tagh, integer size, integer count, real, dimension(*) vals)
Definition at line 1660 of file moab.f.
subroutine nekmoab_set_tag_avg (iter, tagh, integer size, integer count, real, dimension(*) vals)
Definition at line 1630 of file moab.f.
subroutine nekmoab_set_vertex_tag (iter, tagh, integer count, real, dimension(*) vals, integer ierr)
Definition at line 1715 of file moab.f.
subroutine permute_and_map (real, dimension(1) x, real, dimension(0:1) x27, integer nx, integer nmoab, integer e)
Definition at line 1331 of file moab.f.
References gh_face_extend(), igllm(), ly1, lz1, map_to_crs(), and zwgll().
subroutine print_tag_values (tagh, integer nvals, integer is_v)
Definition at line 119 of file moab.f.
subroutine xml2xc ()
Definition at line 1267 of file moab.f.