KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/mpi_dummy.f File Reference
mpi_dummy.f File Reference
Functions/Subroutines
subroutine mpi_scan (data1, data2, n, datatype, operation, comm, ierror)
subroutine mpi_abort (comm, errorcode, ierror)
subroutine mpi_allgather (data1, nsend, sendtype, data2, nrecv, recvtype, comm, ierror)
subroutine mpi_allgatherv (data1, nsend, sendtype, data2, nrecv, ndispls, recvtype, comm, ierror)
subroutine mpi_allreduce (data1, data2, n, datatype, operation, comm, ierror)
subroutine mpi_barrier (comm, ierror)
subroutine mpi_bcast (data, n, datatype, node, comm, ierror)
subroutine mpi_bsend (data, n, datatype, iproc, itag, comm, ierror)
subroutine mpi_cart_create (comm, ldims, dims, periods, reorder, comm_cart, ierror)
subroutine mpi_cart_get (comm, ldims, dims, periods, coords, ierror)
subroutine mpi_cart_shift (comm, idir, idisp, isource, idest, ierror)
subroutine mpi_comm_dup (comm, comm_out, ierror)
subroutine mpi_comm_free (comm, ierror)
subroutine mpi_comm_rank (comm, me, ierror)
subroutine mpi_comm_size (comm, nprocs, ierror)
subroutine mpi_comm_split (comm, icolor, ikey, comm_new, ierror)
subroutine mpi_copy_double_precision (data1, data2, n, ierror)
subroutine mpi_copy_integer (data1, data2, n, ierror)
subroutine mpi_copy_real (data1, data2, n, ierror)
subroutine mpi_finalize (ierror)
subroutine mpi_get_count (istatus, datatype, icount, ierror)
subroutine mpi_init (ierror)
subroutine mpi_irecv (data, n, datatype, iproc, itag, comm, irequest, ierror)
subroutine mpi_isend (data, n, datatype, iproc, itag, comm, request, ierror)
subroutine mpi_recv (data, n, datatype, iproc, itag, comm, istatus, ierror)
subroutine mpi_reduce (data1, data2, n, datatype, operation, receiver, comm, ierror)
subroutine mpi_reduce_double_precision (data1, data2, n, operation, ierror)
subroutine mpi_reduce_integer8 (data1, data2, n, operation, ierror)
subroutine mpi_reduce_integer (data1, data2, n, operation, ierror)
subroutine mpi_reduce_real (data1, data2, n, operation, ierror)
subroutine mpi_reduce_scatter (data1, data2, n, datatype, operation, comm, ierror)
subroutine mpi_rsend (data, n, datatype, iproc, itag, comm, ierror)
subroutine mpi_send (data, n, datatype, iproc, itag, comm, ierror)
subroutine mpi_wait (irequest, istatus, ierror)
subroutine mpi_waitall (icount, irequest, istatus, ierror)
subroutine mpi_waitany (icount, array_of_requests, index, istatus, ierror)
real *8 function mpi_wtick ()
real *8 function mpi_wtime ()
subroutine mpi_initialized (mpi_is_initialized, ierr)
subroutine mpi_comm_create (icomm, igroup, icommd, ierr)
subroutine mpi_intercomm_create (ilcomm, ill, ipcomm, irl, itag, newcomm, ierr)
subroutine mpi_intercomm_merge (icomm, ihigh, icommd, ierr)
subroutine mpi_comm_group (icomm, igroup, ierr)
subroutine mpi_group_free
subroutine mpi_comm_get_attr (icomm, ikey, ival, iflag, ierr)
subroutine mpi_attr_get (icomm, ikey, ival, iflag, ierr)
subroutine mpi_type_get_extent (ikey, ib, isize, ierr)
Function/Subroutine Documentation
mpi_abort()
subroutine mpi_abort (integer comm, integer errorcode, integer ierror)
Definition at line 47 of file mpi_dummy.f.
mpi_allgather()
subroutine mpi_allgather (integer, dimension(nsend) data1, integer nsend, integer sendtype, integer, dimension(nsend) data2, integer nrecv, integer recvtype, integer comm, integer ierror)
Definition at line 73 of file mpi_dummy.f.
References mpi_copy_double_precision(), mpi_copy_integer(), and mpi_copy_real().
mpi_allgatherv()
subroutine mpi_allgatherv (integer, dimension(nsend) data1, integer nsend, integer sendtype, integer, dimension(nsend) data2, integer nrecv, integer ndispls, integer recvtype, integer comm, integer ierror)
Definition at line 108 of file mpi_dummy.f.
References mpi_copy_double_precision(), mpi_copy_integer(), and mpi_copy_real().
mpi_allreduce()
subroutine mpi_allreduce (integer, dimension(n) data1, integer, dimension(n) data2, integer n, integer datatype, integer operation, integer comm, integer ierror)
Definition at line 144 of file mpi_dummy.f.
References mpi_reduce_double_precision(), mpi_reduce_integer(), mpi_reduce_integer8(), and mpi_reduce_real().
mpi_attr_get()
subroutine mpi_attr_get (icomm, ikey, ival, logical iflag, ierr)
Definition at line 1104 of file mpi_dummy.f.
mpi_barrier()
subroutine mpi_barrier (integer comm, integer ierror)
Definition at line 194 of file mpi_dummy.f.
mpi_bcast()
subroutine mpi_bcast (integer, dimension(n) data, integer n, integer datatype, integer node, integer comm, integer ierror)
Definition at line 213 of file mpi_dummy.f.
mpi_bsend()
subroutine mpi_bsend (integer, dimension(n) data, integer n, integer datatype, integer iproc, integer itag, integer comm, integer ierror)
Definition at line 238 of file mpi_dummy.f.
mpi_cart_create()
subroutine mpi_cart_create (integer comm, integer ldims, integer, dimension(*) dims, logical, dimension(*) periods, logical reorder, integer comm_cart, integer ierror)
Definition at line 268 of file mpi_dummy.f.
mpi_cart_get()
subroutine mpi_cart_get (integer comm, integer ldims, integer, dimension(*) dims, logical, dimension(*) periods, integer, dimension(*) coords, integer ierror)
Definition at line 294 of file mpi_dummy.f.
mpi_cart_shift()
subroutine mpi_cart_shift (integer comm, integer idir, integer idisp, integer isource, integer idest, integer ierror)
Definition at line 324 of file mpi_dummy.f.
mpi_comm_create()
subroutine mpi_comm_create (icomm, igroup, icommd, ierr)
Definition at line 1058 of file mpi_dummy.f.
mpi_comm_dup()
subroutine mpi_comm_dup (integer comm, integer comm_out, integer ierror)
Definition at line 349 of file mpi_dummy.f.
mpi_comm_free()
subroutine mpi_comm_free (integer comm, integer ierror)
Definition at line 370 of file mpi_dummy.f.
mpi_comm_get_attr()
subroutine mpi_comm_get_attr (icomm, ikey, integer*8 ival, logical iflag, ierr)
Definition at line 1093 of file mpi_dummy.f.
mpi_comm_group()
subroutine mpi_comm_group (icomm, igroup, ierr)
Definition at line 1080 of file mpi_dummy.f.
mpi_comm_rank()
subroutine mpi_comm_rank (integer comm, integer me, integer ierror)
Definition at line 389 of file mpi_dummy.f.
mpi_comm_size()
subroutine mpi_comm_size (integer comm, integer nprocs, integer ierror)
Definition at line 410 of file mpi_dummy.f.
mpi_comm_split()
subroutine mpi_comm_split (integer comm, integer icolor, integer ikey, integer comm_new, integer ierror)
Definition at line 432 of file mpi_dummy.f.
mpi_copy_double_precision()
subroutine mpi_copy_double_precision (real*8, dimension(n) data1, real*8, dimension(n) data2, integer n, integer ierror)
Definition at line 454 of file mpi_dummy.f.
mpi_copy_integer()
subroutine mpi_copy_integer (integer, dimension(n) data1, integer, dimension(n) data2, integer n, integer ierror)
Definition at line 481 of file mpi_dummy.f.
mpi_copy_real()
subroutine mpi_copy_real (real, dimension(n) data1, real, dimension(n) data2, integer n, integer ierror)
Definition at line 508 of file mpi_dummy.f.
mpi_finalize()
subroutine mpi_finalize (integer ierror)
Definition at line 533 of file mpi_dummy.f.
mpi_get_count()
subroutine mpi_get_count (integer istatus, integer datatype, integer icount, integer ierror)
Definition at line 551 of file mpi_dummy.f.
mpi_group_free()
subroutine mpi_group_free
Definition at line 1088 of file mpi_dummy.f.
mpi_init()
subroutine mpi_init (integer ierror)
Definition at line 576 of file mpi_dummy.f.
mpi_initialized()
subroutine mpi_initialized (mpi_is_initialized, ierr)
Definition at line 1050 of file mpi_dummy.f.
mpi_intercomm_create()
subroutine mpi_intercomm_create (ilcomm, ill, ipcomm, irl, itag, newcomm, ierr)
Definition at line 1066 of file mpi_dummy.f.
References exitti().
mpi_intercomm_merge()
subroutine mpi_intercomm_merge (icomm, ihigh, icommd, ierr)
Definition at line 1073 of file mpi_dummy.f.
References exitti().
mpi_irecv()
subroutine mpi_irecv (integer, dimension(n) data, integer n, integer datatype, integer iproc, integer itag, integer comm, integer irequest, integer ierror)
Definition at line 596 of file mpi_dummy.f.
mpi_isend()
subroutine mpi_isend (integer, dimension(n) data, integer n, integer datatype, integer iproc, integer itag, integer comm, integer request, integer ierror)
Definition at line 627 of file mpi_dummy.f.
mpi_recv()
subroutine mpi_recv (integer, dimension(n) data, integer n, integer datatype, integer iproc, integer itag, integer comm, integer istatus, integer ierror)
Definition at line 659 of file mpi_dummy.f.
mpi_reduce()
subroutine mpi_reduce (integer, dimension(n) data1, integer data2, integer n, integer datatype, integer operation, integer receiver, integer comm, integer ierror)
Definition at line 690 of file mpi_dummy.f.
References mpi_reduce_double_precision(), mpi_reduce_integer(), and mpi_reduce_real().
mpi_reduce_double_precision()
subroutine mpi_reduce_double_precision (real*8, dimension(n) data1, real*8, dimension(n) data2, integer n, integer operation, integer ierror)
Definition at line 736 of file mpi_dummy.f.
mpi_reduce_integer()
subroutine mpi_reduce_integer (integer, dimension(n) data1, integer, dimension(n) data2, integer n, integer operation, integer ierror)
Definition at line 793 of file mpi_dummy.f.
mpi_reduce_integer8()
subroutine mpi_reduce_integer8 (integer*8, dimension(n) data1, integer*8, dimension(n) data2, integer n, integer operation, integer ierror)
Definition at line 765 of file mpi_dummy.f.
mpi_reduce_real()
subroutine mpi_reduce_real (real, dimension(n) data1, real, dimension(n) data2, integer n, integer operation, integer ierror)
Definition at line 821 of file mpi_dummy.f.
mpi_reduce_scatter()
subroutine mpi_reduce_scatter (integer, dimension(n) data1, integer, dimension(n) data2, integer n, integer datatype, integer operation, integer comm, integer ierror)
Definition at line 850 of file mpi_dummy.f.
References mpi_copy_double_precision(), mpi_copy_integer(), and mpi_copy_real().
mpi_rsend()
subroutine mpi_rsend (integer, dimension(n) data, integer n, integer datatype, integer iproc, integer itag, integer comm, integer ierror)
Definition at line 884 of file mpi_dummy.f.
mpi_scan()
subroutine mpi_scan (integer, dimension(n) data1, integer, dimension(n) data2, integer n, integer datatype, integer operation, integer comm, integer ierror)
Definition at line 4 of file mpi_dummy.f.
References copy(), i8copy(), icopy(), and rrcopy().
mpi_send()
subroutine mpi_send (integer, dimension(n) data, integer n, integer datatype, integer iproc, integer itag, integer comm, integer ierror)
Definition at line 914 of file mpi_dummy.f.
mpi_type_get_extent()
subroutine mpi_type_get_extent (ikey, integer*8 ib, integer*8 isize, ierr)
Definition at line 1113 of file mpi_dummy.f.
mpi_wait()
subroutine mpi_wait (integer irequest, integer istatus, integer ierror)
Definition at line 943 of file mpi_dummy.f.
mpi_waitall()
subroutine mpi_waitall (integer icount, integer irequest, integer istatus, integer ierror)
Definition at line 967 of file mpi_dummy.f.
mpi_waitany()
subroutine mpi_waitany (integer icount, integer, dimension(*) array_of_requests, integer index, integer istatus, integer ierror)
Definition at line 993 of file mpi_dummy.f.
mpi_wtick()
real*8 function mpi_wtick
Definition at line 1019 of file mpi_dummy.f.
mpi_wtime()
real*8 function mpi_wtime
Definition at line 1033 of file mpi_dummy.f.