KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/multimesh.f File Reference
multimesh.f File Reference
Functions/Subroutines
subroutine get_session_info (intracomm)
subroutine multimesh_create
subroutine set_intflag
subroutine userchk_set_xfer
subroutine bcopy
subroutine setintercomm (nekcommtrue, nptrue)
subroutine unsetintercomm (nekcommtrue, nptrue)
function uglmin (a, n)
function uglamax (a, n)
function uglmax (a, n)
subroutine neknekgsync ()
subroutine happy_check (ihappy)
subroutine chk_outflow_short
subroutine chk_outflow
subroutine neknekmv ()
subroutine setup_int_neknek (dxf, dyf, dzf)
subroutine exchange_points2 (dxf, dyf, dzf)
subroutine get_values2 (which_field)
subroutine field_eval (fieldout, fieldstride, fieldin)
subroutine nekneksanchk (flag)
Function/Subroutine Documentation
bcopy()
subroutine bcopy ()
Definition at line 264 of file multimesh.f.
References copy(), ly1, and lz1.
chk_outflow()
subroutine chk_outflow ()
Definition at line 432 of file multimesh.f.
References facind(), ly1, and lz1.
chk_outflow_short()
subroutine chk_outflow_short ()
Definition at line 400 of file multimesh.f.
References ly1, and lz1.
exchange_points2()
subroutine exchange_points2 (dxf, dyf, dzf)
Definition at line 551 of file multimesh.f.
References cadd(), exitt(), facind(), iglmax(), izero(), ly1, lz1, nekasgn(), neknekgsync(), and rzero().
field_eval()
subroutine field_eval (real, dimension(1) fieldout, integer fieldstride, real, dimension(1) fieldin)
Definition at line 731 of file multimesh.f.
get_session_info()
subroutine get_session_info (intracomm)
Definition at line 19 of file multimesh.f.
References bcast(), blank(), err_chk(), exitti(), iniproc(), mpi_comm_rank(), mpi_comm_size(), mpi_comm_split(), mpi_init(), and mpi_initialized().
get_values2()
subroutine get_values2 (character*3, dimension(nfld_neknek) which_field)
Definition at line 691 of file multimesh.f.
References copy(), field_eval(), lelt, ly1, lz1, and mappr().
happy_check()
subroutine happy_check (ihappy)
Definition at line 376 of file multimesh.f.
References exitt(), iglmin(), setintercomm(), and unsetintercomm().
multimesh_create()
subroutine multimesh_create ()
Definition at line 140 of file multimesh.f.
References exchange_points2(), neknekgsync(), neknekmv(), nekneksanchk(), set_intflag(), and setup_int_neknek().
neknekgsync()
subroutine neknekgsync ()
Definition at line 367 of file multimesh.f.
References happy_check(), and mpi_barrier().
neknekmv()
subroutine neknekmv ()
Definition at line 472 of file multimesh.f.
References iglmin(), neknekgsync(), setintercomm(), and unsetintercomm().
nekneksanchk()
subroutine nekneksanchk (integer flag)
Definition at line 750 of file multimesh.f.
References exitt(), exitti(), iglsum(), izero(), and neknekgsync().
set_intflag()
subroutine set_intflag ()
Definition at line 174 of file multimesh.f.
References izero().
setintercomm()
subroutine setintercomm (nekcommtrue, nptrue)
Definition at line 309 of file multimesh.f.
setup_int_neknek()
subroutine setup_int_neknek (real dxf, real dyf, real dzf)
Definition at line 493 of file multimesh.f.
References cadd(), ly1, lz1, neknekgsync(), uglmax(), and uglmin().
uglamax()
function uglamax (real, dimension(1) a, n)
Definition at line 345 of file multimesh.f.
References glamax(), happy_check(), setintercomm(), and unsetintercomm().
uglmax()
function uglmax (real, dimension(1) a, n)
Definition at line 356 of file multimesh.f.
References glmax(), happy_check(), setintercomm(), and unsetintercomm().
uglmin()
function uglmin (real, dimension(1) a, n)
Definition at line 334 of file multimesh.f.
References glmin(), happy_check(), setintercomm(), and unsetintercomm().
unsetintercomm()
subroutine unsetintercomm (nekcommtrue, nptrue)
Definition at line 323 of file multimesh.f.
userchk_set_xfer()
subroutine userchk_set_xfer ()
Definition at line 218 of file multimesh.f.
References dnekclock(), dnekclock_sync(), get_values2(), nekgsync(), and neknekgsync().