KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/mvmesh.f File Reference
mvmesh.f File Reference
Functions/Subroutines
subroutine cbcmesh
subroutine admeshv
subroutine admesht
subroutine divws (fms, sfv, phi, nel, idir)
subroutine axifms (fms, sfv, phi, nel, idir)
subroutine updcoor
subroutine mvbdry (nel)
subroutine norcmp2 (wvx, wvy, wvz, e, f)
subroutine norcmp (wt1, wt2, wt3, rnx, rny, rnz, ifc)
subroutine facemv (wt1, wt2, wt3, rnx, rny, rnz, smt, ifc)
subroutine faczqn (wt1, wt2, wt3, ifc, iel)
subroutine facsmt (smt, ifc)
subroutine cqnet (qni, ta, nel)
subroutine facemt (w1, w2, w3, rnx, rny, rnz, qni, dsa, smt, rhola, ifc)
subroutine elasolv (nel)
subroutine meshtol (ta, tolmsh, nel, imsolv)
subroutine updxyz (nel)
subroutine lagmshv (nel)
subroutine facec3 (a1, a2, a3, b1, b2, b3, ifc)
subroutine ptbgeom
subroutine ibdgeom (nel)
subroutine inigeom (ux, uy, uz, x, y, z, iside, iel)
subroutine quickmv
subroutine quickmv2d
subroutine quickmv3d
Function/Subroutine Documentation
admesht()
subroutine admesht ()
Definition at line 111 of file mvmesh.f.
References addcol3(), divws(), lelt, ly1, lz1, and rzero().
admeshv()
subroutine admeshv ()
Definition at line 82 of file mvmesh.f.
References add2(), divws(), lelt, ly1, lz1, and rzero().
axifms()
subroutine axifms (dimension(lx1,ly1,lz1,1) fms, dimension(lx1,ly1,lz1,1) sfv, dimension(lx1,ly1,lz1,1) phi, nel, idir)
Definition at line 180 of file mvmesh.f.
References addcol4(), col3(), lelt, ly1, lz1, and mxm().
cbcmesh()
subroutine cbcmesh ()
Definition at line 3 of file mvmesh.f.
cqnet()
subroutine cqnet (dimension(lx1,ly1,lz1,1) qni, dimension (lx1,ly1,lz1,1) ta, nel)
Definition at line 668 of file mvmesh.f.
References axhelm(), dssum(), lelt, ly1, lz1, sethlm(), and sub3().
divws()
subroutine divws (dimension(lx1,ly1,lz1,1) fms, dimension(lx1,ly1,lz1,1) sfv, dimension(lx1,ly1,lz1,1) phi, nel, idir)
Definition at line 132 of file mvmesh.f.
References addcol3(), axifms(), col2(), col3(), invcol2(), lelt, ly1, lz1, and urst().
elasolv()
subroutine elasolv (nel)
Definition at line 729 of file mvmesh.f.
References add2(), axhmsf(), cfill(), chsign(), dsavg(), hmhzsf(), lelt, ly1, lz1, and meshtol().
facec3()
subroutine facec3 (dimension(lx1,ly1,lz1) a1, dimension(lx1,ly1,lz1) a2, dimension(lx1,ly1,lz1) a3, dimension(lx1,ly1,lz1) b1, dimension(lx1,ly1,lz1) b2, dimension(lx1,ly1,lz1) b3, ifc)
Definition at line 939 of file mvmesh.f.
References facind2(), ly1, and lz1.
facemt()
subroutine facemt (dimension (lx1,ly1,lz1) w1, dimension (lx1,ly1,lz1) w2, dimension (lx1,ly1,lz1) w3, dimension(lx1,ly1,lz1) rnx, dimension(lx1,ly1,lz1) rny, dimension(lx1,ly1,lz1) rnz, dimension(lx1,ly1,lz1) qni, dimension(lx1,ly1,lz1) dsa, dimension(lx1,ly1,lz1) smt, rhola, ifc)
Definition at line 692 of file mvmesh.f.
References facind2(), ly1, and lz1.
facemv()
subroutine facemv (dimension(lx1,ly1,lz1) wt1, dimension(lx1,ly1,lz1) wt2, dimension(lx1,ly1,lz1) wt3, dimension(lx1,ly1,lz1) rnx, dimension(lx1,ly1,lz1) rny, dimension(lx1,ly1,lz1) rnz, dimension(lx1,ly1,lz1) smt, ifc)
Definition at line 572 of file mvmesh.f.
References copy(), facind2(), ly1, and lz1.
facsmt()
subroutine facsmt (dimension(lx1,ly1,lz1) smt, ifc)
Definition at line 653 of file mvmesh.f.
References facind2(), ly1, and lz1.
faczqn()
subroutine faczqn (dimension(lx1,ly1,lz1) wt1, dimension(lx1,ly1,lz1) wt2, dimension(lx1,ly1,lz1) wt3, ifc, iel)
Definition at line 611 of file mvmesh.f.
References copy(), facind2(), ly1, and lz1.
ibdgeom()
subroutine ibdgeom (nel)
Definition at line 1004 of file mvmesh.f.
References dsop(), facind(), inigeom(), ly1, lz1, and rzero().
inigeom()
subroutine inigeom (ux, uy, uz, x, y, z, iside, iel)
Definition at line 1059 of file mvmesh.f.
lagmshv()
subroutine lagmshv (nel)
Definition at line 911 of file mvmesh.f.
References copy(), ly1, and lz1.
meshtol()
subroutine meshtol (dimension(lx1,ly1,lz1,1) ta, tolmsh, nel, imsolv)
Definition at line 833 of file mvmesh.f.
References glmax(), ly1, lz1, and opdot().
mvbdry()
subroutine mvbdry (nel)
Definition at line 250 of file mvmesh.f.
References add2(), chknord(), cqnet(), dsavg(), dsop(), dssum(), facec3(), facemt(), facev(), facexs(), facexv(), facsmt(), faczqn(), iglmax(), lelt, ly1, lz1, norcmp2(), opcopy(), opdssum(), rmask(), rzero(), rzero3(), and unitvec().
norcmp()
subroutine norcmp (dimension(lx1,ly1,lz1) wt1, dimension(lx1,ly1,lz1) wt2, dimension(lx1,ly1,lz1) wt3, dimension(lx1,ly1,lz1) rnx, dimension(lx1,ly1,lz1) rny, dimension(lx1,ly1,lz1) rnz, ifc)
Definition at line 534 of file mvmesh.f.
References copy(), facind2(), ly1, and lz1.
norcmp2()
subroutine norcmp2 (real, dimension(lx1,ly1,lz1) wvx, real, dimension(lx1,ly1,lz1) wvy, real, dimension(lx1,ly1,lz1) wvz, integer e, integer f)
Definition at line 499 of file mvmesh.f.
References facind(), ly1, lz1, and scale().
ptbgeom()
subroutine ptbgeom ()
Definition at line 963 of file mvmesh.f.
References elasolv(), geom1(), geom2(), ibdgeom(), lagmass(), lelt, ly1, lz1, rzero(), setinvm(), updmsys(), updxyz(), and volume().
quickmv()
subroutine quickmv ()
Definition at line 1071 of file mvmesh.f.
References quickmv2d(), and quickmv3d().
quickmv2d()
subroutine quickmv2d ()
Definition at line 1084 of file mvmesh.f.
References dsavg(), glmax(), glmin(), ly1, lz1, and rzero().
quickmv3d()
subroutine quickmv3d ()
Definition at line 1151 of file mvmesh.f.
References dsavg(), glmax(), glmin(), ly1, lz1, and rzero().
updcoor()
subroutine updcoor ()
Definition at line 226 of file mvmesh.f.
References lagmshv(), and updxyz().
updxyz()
subroutine updxyz (nel)
Definition at line 865 of file mvmesh.f.
References add2(), add2s2(), cmult2(), copy(), lelt, ly1, and lz1.