KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/mxm_wrapper.f File Reference
mxm_wrapper.f File Reference
Functions/Subroutines
subroutine mxm (a, n1, b, n2, c, n3)
subroutine fgslib_mxm (a, n1, b, n2, c, n3)
Function/Subroutine Documentation
fgslib_mxm()
subroutine fgslib_mxm (real, dimension(n1,n2) a, n1, real, dimension(n2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 90 of file mxm_wrapper.f.
References mxmf2().
mxm()
subroutine mxm (real, dimension(n1,n2) a, n1, real, dimension(n2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2 of file mxm_wrapper.f.
References dgemm(), dnekclock(), mxm_bgq_10(), mxm_bgq_16(), mxm_bgq_6(), mxm_bgq_8(), and mxmf2().