KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/mxm_std.f File Reference
mxm_std.f File Reference
Functions/Subroutines
subroutine mxmf2 (A, N1, B, N2, C, N3)
subroutine mxf1 (a, n1, b, n2, c, n3)
subroutine mxf2 (a, n1, b, n2, c, n3)
subroutine mxf3 (a, n1, b, n2, c, n3)
subroutine mxf4 (a, n1, b, n2, c, n3)
subroutine mxf5 (a, n1, b, n2, c, n3)
subroutine mxf6 (a, n1, b, n2, c, n3)
subroutine mxf7 (a, n1, b, n2, c, n3)
subroutine mxf8 (a, n1, b, n2, c, n3)
subroutine mxf9 (a, n1, b, n2, c, n3)
subroutine mxf10 (a, n1, b, n2, c, n3)
subroutine mxf11 (a, n1, b, n2, c, n3)
subroutine mxf12 (a, n1, b, n2, c, n3)
subroutine mxf13 (a, n1, b, n2, c, n3)
subroutine mxf14 (a, n1, b, n2, c, n3)
subroutine mxf15 (a, n1, b, n2, c, n3)
subroutine mxf16 (a, n1, b, n2, c, n3)
subroutine mxf17 (a, n1, b, n2, c, n3)
subroutine mxf18 (a, n1, b, n2, c, n3)
subroutine mxf19 (a, n1, b, n2, c, n3)
subroutine mxf20 (a, n1, b, n2, c, n3)
subroutine mxf21 (a, n1, b, n2, c, n3)
subroutine mxf22 (a, n1, b, n2, c, n3)
subroutine mxf23 (a, n1, b, n2, c, n3)
subroutine mxf24 (a, n1, b, n2, c, n3)
subroutine mxm44_0 (a, m, b, k, c, n)
subroutine mxm44_2 (a, m, b, k, c, n)
subroutine mxm_test_all (nid, ivb)
subroutine initab (a, b, n)
subroutine mxms (a, n1, b, n2, c, n3)
subroutine mxmu4 (a, n1, b, n2, c, n3)
subroutine madd (a, n1, b, n2, c, n3)
subroutine mxmur2 (a, n1, b, n2, c, n3)
subroutine mxmur2_1 (a, n1, b, n2, c, n3)
subroutine mxmur2_2 (a, n1, b, n2, c, n3)
subroutine mxmur2_3 (a, n1, b, n2, c, n3)
subroutine mxmur2_4 (a, n1, b, n2, c, n3)
subroutine mxmur2_5 (a, n1, b, n2, c, n3)
subroutine mxmur2_6 (a, n1, b, n2, c, n3)
subroutine mxmur2_7 (a, n1, b, n2, c, n3)
subroutine mxmur2_8 (a, n1, b, n2, c, n3)
subroutine mxmur2_9 (a, n1, b, n2, c, n3)
subroutine mxmur2_10 (a, n1, b, n2, c, n3)
subroutine mxmur2_11 (a, n1, b, n2, c, n3)
subroutine mxmur2_12 (a, n1, b, n2, c, n3)
subroutine mxmur2_13 (a, n1, b, n2, c, n3)
subroutine mxmur2_14 (a, n1, b, n2, c, n3)
subroutine mxmur2_15 (a, n1, b, n2, c, n3)
subroutine mxmur2_16 (a, n1, b, n2, c, n3)
subroutine mxmur3 (a, n1, b, n2, c, n3)
subroutine mxmur3_16 (a, n1, b, n2, c, n3)
subroutine mxmur3_15 (a, n1, b, n2, c, n3)
subroutine mxmur3_14 (a, n1, b, n2, c, n3)
subroutine mxmur3_13 (a, n1, b, n2, c, n3)
subroutine mxmur3_12 (a, n1, b, n2, c, n3)
subroutine mxmur3_11 (a, n1, b, n2, c, n3)
subroutine mxmur3_10 (a, n1, b, n2, c, n3)
subroutine mxmur3_9 (a, n1, b, n2, c, n3)
subroutine mxmur3_8 (a, n1, b, n2, c, n3)
subroutine mxmur3_7 (a, n1, b, n2, c, n3)
subroutine mxmur3_6 (a, n1, b, n2, c, n3)
subroutine mxmur3_5 (a, n1, b, n2, c, n3)
subroutine mxmur3_4 (a, n1, b, n2, c, n3)
subroutine mxmur3_3 (a, n1, b, n2, c, n3)
subroutine mxmur3_2 (a, n1, b, n2, c, n3)
subroutine mxmur3_1 (a, n1, b, n2, c, n3)
subroutine mxmd (a, n1, b, n2, c, n3)
subroutine mxmfb (a, n1, b, n2, c, n3)
subroutine mxmfb_1 (a, n1, b, n2, c, n3)
subroutine mxmfb_2 (a, n1, b, n2, c, n3)
subroutine mxmfb_3 (a, n1, b, n2, c, n3)
subroutine mxmfb_4 (a, n1, b, n2, c, n3)
subroutine mxmfb_5 (a, n1, b, n2, c, n3)
subroutine mxmfb_6 (a, n1, b, n2, c, n3)
subroutine mxmfb_7 (a, n1, b, n2, c, n3)
subroutine mxmfb_8 (a, n1, b, n2, c, n3)
subroutine mxmfb_9 (a, n1, b, n2, c, n3)
subroutine mxmfb_10 (a, n1, b, n2, c, n3)
subroutine mxmfb_11 (a, n1, b, n2, c, n3)
subroutine mxmfb_12 (a, n1, b, n2, c, n3)
subroutine mxmfb_13 (a, n1, b, n2, c, n3)
subroutine mxmfb_14 (a, n1, b, n2, c, n3)
subroutine mxmfb_15 (a, n1, b, n2, c, n3)
subroutine mxmfb_16 (a, n1, b, n2, c, n3)
subroutine mxmfb_17 (a, n1, b, n2, c, n3)
subroutine mxmfb_18 (a, n1, b, n2, c, n3)
subroutine mxmfb_19 (a, n1, b, n2, c, n3)
subroutine mxmfb_20 (a, n1, b, n2, c, n3)
subroutine mxmfb_21 (a, n1, b, n2, c, n3)
subroutine mxmfb_22 (a, n1, b, n2, c, n3)
subroutine mxmfb_23 (a, n1, b, n2, c, n3)
subroutine mxmfb_24 (a, n1, b, n2, c, n3)
subroutine mxmf3 (a, n1, b, n2, c, n3)
subroutine mxmf3_1 (a, n1, b, n2, c, n3)
subroutine mxmf3_2 (a, n1, b, n2, c, n3)
subroutine mxmf3_3 (a, n1, b, n2, c, n3)
subroutine mxmf3_4 (a, n1, b, n2, c, n3)
subroutine mxmf3_5 (a, n1, b, n2, c, n3)
subroutine mxmf3_6 (a, n1, b, n2, c, n3)
subroutine mxmf3_7 (a, n1, b, n2, c, n3)
subroutine mxmf3_8 (a, n1, b, n2, c, n3)
subroutine mxmf3_9 (a, n1, b, n2, c, n3)
subroutine mxmf3_10 (a, n1, b, n2, c, n3)
subroutine mxmf3_11 (a, n1, b, n2, c, n3)
subroutine mxmf3_12 (a, n1, b, n2, c, n3)
subroutine mxmf3_13 (a, n1, b, n2, c, n3)
subroutine mxmf3_14 (a, n1, b, n2, c, n3)
subroutine mxmf3_15 (a, n1, b, n2, c, n3)
subroutine mxmf3_16 (a, n1, b, n2, c, n3)
subroutine mxmf3_17 (a, n1, b, n2, c, n3)
subroutine mxmf3_18 (a, n1, b, n2, c, n3)
subroutine mxmf3_19 (a, n1, b, n2, c, n3)
subroutine mxmf3_20 (a, n1, b, n2, c, n3)
subroutine mxmf3_21 (a, n1, b, n2, c, n3)
subroutine mxmf3_22 (a, n1, b, n2, c, n3)
subroutine mxmf3_23 (a, n1, b, n2, c, n3)
subroutine mxmf3_24 (a, n1, b, n2, c, n3)
subroutine mxm44 (a, n1, b, n2, c, n3)
subroutine mxm44_0_t (a, m, b, k, c, n)
subroutine mxm44_2_t (a, m, b, k, c, n)
subroutine mxmtest (s, nn, cn, mxmt, name, k, ivb)
subroutine mxm_analyze (s, a, nn, c, nt, ivb)
subroutine out_anal (s, a, nn, c, nt, itmax, name8, k, ivb)
subroutine mxma (a, n1, b, n2, c, n3)
subroutine mxma2 (a, n1, b, n2, c, n3)
subroutine mxa1 (a, n1, b, n2, c, n3)
subroutine mxa2 (a, n1, b, n2, c, n3)
subroutine mxa3 (a, n1, b, n2, c, n3)
subroutine mxa4 (a, n1, b, n2, c, n3)
subroutine mxa5 (a, n1, b, n2, c, n3)
subroutine mxa6 (a, n1, b, n2, c, n3)
subroutine mxa7 (a, n1, b, n2, c, n3)
subroutine mxa8 (a, n1, b, n2, c, n3)
subroutine mxa9 (a, n1, b, n2, c, n3)
subroutine mxa10 (a, n1, b, n2, c, n3)
subroutine mxa11 (a, n1, b, n2, c, n3)
subroutine mxa12 (a, n1, b, n2, c, n3)
subroutine mxa13 (a, n1, b, n2, c, n3)
subroutine mxa14 (a, n1, b, n2, c, n3)
subroutine mxa15 (a, n1, b, n2, c, n3)
subroutine mxa16 (a, n1, b, n2, c, n3)
subroutine mxa17 (a, n1, b, n2, c, n3)
subroutine mxa18 (a, n1, b, n2, c, n3)
subroutine mxa19 (a, n1, b, n2, c, n3)
subroutine mxa20 (a, n1, b, n2, c, n3)
subroutine mxa21 (a, n1, b, n2, c, n3)
subroutine mxa22 (a, n1, b, n2, c, n3)
subroutine mxa23 (a, n1, b, n2, c, n3)
subroutine mxa24 (a, n1, b, n2, c, n3)
subroutine mxm44_0a (a, m, b, k, c, n)
subroutine mxm44_2a (a, m, b, k, c, n)
Function/Subroutine Documentation
subroutine initab (real, dimension(1) a, real, dimension(1) b, n)
Definition at line 1145 of file mxm_std.f.
References n.
subroutine madd (real, dimension(n1,n2) a, n1, real, dimension(n2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1212 of file mxm_std.f.
References j.
subroutine mxa1 (real, dimension(n1,1) a, n1, real, dimension(1,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4241 of file mxm_std.f.
References j.
subroutine mxa10 (real, dimension(n1,10) a, n1, real, dimension(10,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4394 of file mxm_std.f.
References j.
subroutine mxa11 (real, dimension(n1,11) a, n1, real, dimension(11,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4416 of file mxm_std.f.
References j.
subroutine mxa12 (real, dimension(n1,12) a, n1, real, dimension(12,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4439 of file mxm_std.f.
References j.
subroutine mxa13 (real, dimension(n1,13) a, n1, real, dimension(13,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4463 of file mxm_std.f.
References j.
subroutine mxa14 (real, dimension(n1,14) a, n1, real, dimension(14,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4488 of file mxm_std.f.
References j.
subroutine mxa15 (real, dimension(n1,15) a, n1, real, dimension(15,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4514 of file mxm_std.f.
References j.
subroutine mxa16 (real, dimension(n1,16) a, n1, real, dimension(16,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4541 of file mxm_std.f.
References j.
subroutine mxa17 (real, dimension(n1,17) a, n1, real, dimension(17,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4569 of file mxm_std.f.
References j.
subroutine mxa18 (real, dimension(n1,18) a, n1, real, dimension(18,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4598 of file mxm_std.f.
References j.
subroutine mxa19 (real, dimension(n1,19) a, n1, real, dimension(19,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4628 of file mxm_std.f.
References j.
subroutine mxa2 (real, dimension(n1,2) a, n1, real, dimension(2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4254 of file mxm_std.f.
References j.
subroutine mxa20 (real, dimension(n1,20) a, n1, real, dimension(20,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4659 of file mxm_std.f.
References j.
subroutine mxa21 (real, dimension(n1,21) a, n1, real, dimension(21,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4691 of file mxm_std.f.
References j.
subroutine mxa22 (real, dimension(n1,22) a, n1, real, dimension(22,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4724 of file mxm_std.f.
References j.
subroutine mxa23 (real, dimension(n1,23) a, n1, real, dimension(23,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4758 of file mxm_std.f.
References j.
subroutine mxa24 (real, dimension(n1,24) a, n1, real, dimension(24,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4793 of file mxm_std.f.
References j.
subroutine mxa3 (real, dimension(n1,3) a, n1, real, dimension(3,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4268 of file mxm_std.f.
References j.
subroutine mxa4 (real, dimension(n1,4) a, n1, real, dimension(4,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4283 of file mxm_std.f.
References j.
subroutine mxa5 (real, dimension(n1,5) a, n1, real, dimension(5,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4299 of file mxm_std.f.
References j.
subroutine mxa6 (real, dimension(n1,6) a, n1, real, dimension(6,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4316 of file mxm_std.f.
References j.
subroutine mxa7 (real, dimension(n1,7) a, n1, real, dimension(7,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4334 of file mxm_std.f.
References j.
subroutine mxa8 (real, dimension(n1,8) a, n1, real, dimension(8,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4353 of file mxm_std.f.
References j.
subroutine mxa9 (real, dimension(n1,9) a, n1, real, dimension(9,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4373 of file mxm_std.f.
References j.
subroutine mxf1 (real, dimension(n1,1) a, n1, real, dimension(1,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 70 of file mxm_std.f.
References j.
subroutine mxf10 (real, dimension(n1,10) a, n1, real, dimension(10,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 214 of file mxm_std.f.
References j.
subroutine mxf11 (real, dimension(n1,11) a, n1, real, dimension(11,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 235 of file mxm_std.f.
References j.
subroutine mxf12 (real, dimension(n1,12) a, n1, real, dimension(12,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 257 of file mxm_std.f.
References j.
subroutine mxf13 (real, dimension(n1,13) a, n1, real, dimension(13,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 280 of file mxm_std.f.
References j.
subroutine mxf14 (real, dimension(n1,14) a, n1, real, dimension(14,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 304 of file mxm_std.f.
References j.
subroutine mxf15 (real, dimension(n1,15) a, n1, real, dimension(15,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 329 of file mxm_std.f.
References j.
subroutine mxf16 (real, dimension(n1,16) a, n1, real, dimension(16,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 355 of file mxm_std.f.
References j.
subroutine mxf17 (real, dimension(n1,17) a, n1, real, dimension(17,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 382 of file mxm_std.f.
References j.
subroutine mxf18 (real, dimension(n1,18) a, n1, real, dimension(18,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 410 of file mxm_std.f.
References j.
subroutine mxf19 (real, dimension(n1,19) a, n1, real, dimension(19,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 439 of file mxm_std.f.
References j.
subroutine mxf2 (real, dimension(n1,2) a, n1, real, dimension(2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 82 of file mxm_std.f.
References j.
subroutine mxf20 (real, dimension(n1,20) a, n1, real, dimension(20,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 469 of file mxm_std.f.
References j.
subroutine mxf21 (real, dimension(n1,21) a, n1, real, dimension(21,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 500 of file mxm_std.f.
References j.
subroutine mxf22 (real, dimension(n1,22) a, n1, real, dimension(22,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 532 of file mxm_std.f.
References j.
subroutine mxf23 (real, dimension(n1,23) a, n1, real, dimension(23,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 565 of file mxm_std.f.
References j.
subroutine mxf24 (real, dimension(n1,24) a, n1, real, dimension(24,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 599 of file mxm_std.f.
References j.
subroutine mxf3 (real, dimension(n1,3) a, n1, real, dimension(3,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 95 of file mxm_std.f.
References j.
subroutine mxf4 (real, dimension(n1,4) a, n1, real, dimension(4,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 109 of file mxm_std.f.
References j.
subroutine mxf5 (real, dimension(n1,5) a, n1, real, dimension(5,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 124 of file mxm_std.f.
References j.
subroutine mxf6 (real, dimension(n1,6) a, n1, real, dimension(6,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 140 of file mxm_std.f.
References j.
subroutine mxf7 (real, dimension(n1,7) a, n1, real, dimension(7,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 157 of file mxm_std.f.
References j.
subroutine mxf8 (real, dimension(n1,8) a, n1, real, dimension(8,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 175 of file mxm_std.f.
References j.
subroutine mxf9 (real, dimension(n1,9) a, n1, real, dimension(9,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 194 of file mxm_std.f.
References j.
subroutine mxm44 (real, dimension(n1,n2) a, n1, real, dimension(n2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3426 of file mxm_std.f.
References mxm44_0_t(), and mxm44_2_t().
subroutine mxm44_0 (real, dimension(m,k) a, m, real, dimension(k,n) b, k, real, dimension(m,n) c, n)
Definition at line 634 of file mxm_std.f.
References j, and n.
subroutine mxm44_0_t (real, dimension(m,k) a, m, real, dimension(k,n) b, k, real, dimension(m,n) c, n)
Definition at line 3454 of file mxm_std.f.
References j, and n.
subroutine mxm44_0a (real, dimension(m,k) a, m, real, dimension(k,n) b, k, real, dimension(m,n) c, n)
Definition at line 4829 of file mxm_std.f.
References j, and n.
subroutine mxm44_2 (real, dimension(m,2) a, m, real, dimension(2,n) b, k, real, dimension(m,n) c, n)
Definition at line 1063 of file mxm_std.f.
References j, and n.
subroutine mxm44_2_t (real, dimension(m,2) a, m, real, dimension(2,n) b, k, real, dimension(m,n) c, n)
Definition at line 3885 of file mxm_std.f.
References j, and n.
subroutine mxm44_2a (real, dimension(m,2) a, m, real, dimension(2,n) b, k, real, dimension(m,n) c, n)
Definition at line 5266 of file mxm_std.f.
References j, and n.
subroutine mxm_analyze (real, dimension(nn,2,nt,3) s, real, dimension(nn,2,nt,3) a, nn, character*5, dimension(3,nt) c, nt, ivb)
Definition at line 4032 of file mxm_std.f.
References n, and out_anal().
subroutine mxm_test_all (nid, ivb)
Definition at line 1109 of file mxm_std.f.
References madd(), mxm(), mxm44(), mxm_analyze(), mxmd(), mxmf3(), mxmfb(), mxms(), mxmtest(), mxmu4(), mxmur2(), mxmur3(), and nekgsync().
subroutine mxma (real, dimension(n1,n2) a, n1, real, dimension(n2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4126 of file mxm_std.f.
References mxma2().
subroutine mxma2 (real, dimension(n1,n2) a, n1, real, dimension(n2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 4159 of file mxm_std.f.
References mxa1(), mxa10(), mxa11(), mxa12(), mxa13(), mxa14(), mxa15(), mxa16(), mxa17(), mxa18(), mxa19(), mxa2(), mxa20(), mxa21(), mxa22(), mxa23(), mxa24(), mxa3(), mxa4(), mxa5(), mxa6(), mxa7(), mxa8(), mxa9(), and mxm44_0a().
subroutine mxmd (real, dimension(n1,n2) a, n1, real, dimension(n2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2090 of file mxm_std.f.
References dgemm().
subroutine mxmf2 (real, dimension(n1,n2) A, N1, real, dimension(n2,n3) B, N2, real, dimension(n1,n3) C, N3)
Definition at line 3 of file mxm_std.f.
References mxf1(), mxf10(), mxf11(), mxf12(), mxf13(), mxf14(), mxf15(), mxf16(), mxf17(), mxf18(), mxf19(), mxf2(), mxf20(), mxf21(), mxf22(), mxf23(), mxf24(), mxf3(), mxf4(), mxf5(), mxf6(), mxf7(), mxf8(), mxf9(), and mxm44_0().
subroutine mxmf3 (real, dimension(n1,n2) a, n1, real, dimension(n2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2761 of file mxm_std.f.
References dgemm(), mxmf3_1(), mxmf3_10(), mxmf3_11(), mxmf3_12(), mxmf3_13(), mxmf3_14(), mxmf3_15(), mxmf3_16(), mxmf3_17(), mxmf3_18(), mxmf3_19(), mxmf3_2(), mxmf3_20(), mxmf3_21(), mxmf3_22(), mxmf3_23(), mxmf3_24(), mxmf3_3(), mxmf3_4(), mxmf3_5(), mxmf3_6(), mxmf3_7(), mxmf3_8(), mxmf3_9(), and sgemm().
subroutine mxmf3_1 (real, dimension(n1,1) a, n1, real, dimension(1,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2862 of file mxm_std.f.
References j.
subroutine mxmf3_10 (real, dimension(n1,10) a, n1, real, dimension(10,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3006 of file mxm_std.f.
References j.
subroutine mxmf3_11 (real, dimension(n1,11) a, n1, real, dimension(11,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3027 of file mxm_std.f.
References j.
subroutine mxmf3_12 (real, dimension(n1,12) a, n1, real, dimension(12,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3049 of file mxm_std.f.
References j.
subroutine mxmf3_13 (real, dimension(n1,13) a, n1, real, dimension(13,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3072 of file mxm_std.f.
References j.
subroutine mxmf3_14 (real, dimension(n1,14) a, n1, real, dimension(14,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3096 of file mxm_std.f.
References j.
subroutine mxmf3_15 (real, dimension(n1,15) a, n1, real, dimension(15,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3121 of file mxm_std.f.
References j.
subroutine mxmf3_16 (real, dimension(n1,16) a, n1, real, dimension(16,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3147 of file mxm_std.f.
References j.
subroutine mxmf3_17 (real, dimension(n1,17) a, n1, real, dimension(17,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3174 of file mxm_std.f.
References j.
subroutine mxmf3_18 (real, dimension(n1,18) a, n1, real, dimension(18,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3202 of file mxm_std.f.
References j.
subroutine mxmf3_19 (real, dimension(n1,19) a, n1, real, dimension(19,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3231 of file mxm_std.f.
References j.
subroutine mxmf3_2 (real, dimension(n1,2) a, n1, real, dimension(2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2874 of file mxm_std.f.
References j.
subroutine mxmf3_20 (real, dimension(n1,20) a, n1, real, dimension(20,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3261 of file mxm_std.f.
References j.
subroutine mxmf3_21 (real, dimension(n1,21) a, n1, real, dimension(21,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3292 of file mxm_std.f.
References j.
subroutine mxmf3_22 (real, dimension(n1,22) a, n1, real, dimension(22,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3324 of file mxm_std.f.
References j.
subroutine mxmf3_23 (real, dimension(n1,23) a, n1, real, dimension(23,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3357 of file mxm_std.f.
References j.
subroutine mxmf3_24 (real, dimension(n1,24) a, n1, real, dimension(24,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3391 of file mxm_std.f.
References j.
subroutine mxmf3_3 (real, dimension(n1,3) a, n1, real, dimension(3,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2887 of file mxm_std.f.
References j.
subroutine mxmf3_4 (real, dimension(n1,4) a, n1, real, dimension(4,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2901 of file mxm_std.f.
References j.
subroutine mxmf3_5 (real, dimension(n1,5) a, n1, real, dimension(5,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2916 of file mxm_std.f.
References j.
subroutine mxmf3_6 (real, dimension(n1,6) a, n1, real, dimension(6,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2932 of file mxm_std.f.
References j.
subroutine mxmf3_7 (real, dimension(n1,7) a, n1, real, dimension(7,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2949 of file mxm_std.f.
References j.
subroutine mxmf3_8 (real, dimension(n1,8) a, n1, real, dimension(8,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2967 of file mxm_std.f.
References j.
subroutine mxmf3_9 (real, dimension(n1,9) a, n1, real, dimension(9,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2986 of file mxm_std.f.
References j.
subroutine mxmfb (real, dimension(n1,n2) a, n1, real, dimension(n2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2107 of file mxm_std.f.
References dgemm(), mxmfb_1(), mxmfb_10(), mxmfb_11(), mxmfb_12(), mxmfb_13(), mxmfb_14(), mxmfb_15(), mxmfb_16(), mxmfb_17(), mxmfb_18(), mxmfb_19(), mxmfb_2(), mxmfb_20(), mxmfb_21(), mxmfb_22(), mxmfb_23(), mxmfb_24(), mxmfb_3(), mxmfb_4(), mxmfb_5(), mxmfb_6(), mxmfb_7(), mxmfb_8(), mxmfb_9(), and sgemm().
subroutine mxmfb_1 (real, dimension(n1,1) a, n1, real, dimension(1,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2197 of file mxm_std.f.
References j.
subroutine mxmfb_10 (real, dimension(n1,10) a, n1, real, dimension(10,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2341 of file mxm_std.f.
References j.
subroutine mxmfb_11 (real, dimension(n1,11) a, n1, real, dimension(11,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2362 of file mxm_std.f.
References j.
subroutine mxmfb_12 (real, dimension(n1,12) a, n1, real, dimension(12,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2384 of file mxm_std.f.
References j.
subroutine mxmfb_13 (real, dimension(n1,13) a, n1, real, dimension(13,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2407 of file mxm_std.f.
References j.
subroutine mxmfb_14 (real, dimension(n1,14) a, n1, real, dimension(14,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2431 of file mxm_std.f.
References j.
subroutine mxmfb_15 (real, dimension(n1,15) a, n1, real, dimension(15,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2456 of file mxm_std.f.
References j.
subroutine mxmfb_16 (real, dimension(n1,16) a, n1, real, dimension(16,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2482 of file mxm_std.f.
References j.
subroutine mxmfb_17 (real, dimension(n1,17) a, n1, real, dimension(17,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2509 of file mxm_std.f.
References j.
subroutine mxmfb_18 (real, dimension(n1,18) a, n1, real, dimension(18,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2537 of file mxm_std.f.
References j.
subroutine mxmfb_19 (real, dimension(n1,19) a, n1, real, dimension(19,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2566 of file mxm_std.f.
References j.
subroutine mxmfb_2 (real, dimension(n1,2) a, n1, real, dimension(2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2209 of file mxm_std.f.
References j.
subroutine mxmfb_20 (real, dimension(n1,20) a, n1, real, dimension(20,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2596 of file mxm_std.f.
References j.
subroutine mxmfb_21 (real, dimension(n1,21) a, n1, real, dimension(21,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2627 of file mxm_std.f.
References j.
subroutine mxmfb_22 (real, dimension(n1,22) a, n1, real, dimension(22,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2659 of file mxm_std.f.
References j.
subroutine mxmfb_23 (real, dimension(n1,23) a, n1, real, dimension(23,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2692 of file mxm_std.f.
References j.
subroutine mxmfb_24 (real, dimension(n1,24) a, n1, real, dimension(24,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2726 of file mxm_std.f.
References j.
subroutine mxmfb_3 (real, dimension(n1,3) a, n1, real, dimension(3,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2222 of file mxm_std.f.
References j.
subroutine mxmfb_4 (real, dimension(n1,4) a, n1, real, dimension(4,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2236 of file mxm_std.f.
References j.
subroutine mxmfb_5 (real, dimension(n1,5) a, n1, real, dimension(5,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2251 of file mxm_std.f.
References j.
subroutine mxmfb_6 (real, dimension(n1,6) a, n1, real, dimension(6,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2267 of file mxm_std.f.
References j.
subroutine mxmfb_7 (real, dimension(n1,7) a, n1, real, dimension(7,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2284 of file mxm_std.f.
References j.
subroutine mxmfb_8 (real, dimension(n1,8) a, n1, real, dimension(8,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2302 of file mxm_std.f.
References j.
subroutine mxmfb_9 (real, dimension(n1,9) a, n1, real, dimension(9,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 2321 of file mxm_std.f.
References j.
subroutine mxms (real, dimension(n1,n2) a, n1, real, dimension(n2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1160 of file mxm_std.f.
References j.
subroutine mxmtest (real, dimension(nn,2) s, nn, character*5 cn, external mxmt, character*5 name, k, ivb)
Definition at line 3931 of file mxm_std.f.
References dnekclock(), initab(), lelt, ly1, lz1, and n.
subroutine mxmu4 (real, dimension(n1,n2) a, n1, real, dimension(n2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1182 of file mxm_std.f.
References j.
subroutine mxmur2 (real, dimension(n1,n2) a, n1, real, dimension(n2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1225 of file mxm_std.f.
References j, mxmur2_1(), mxmur2_10(), mxmur2_11(), mxmur2_12(), mxmur2_13(), mxmur2_14(), mxmur2_15(), mxmur2_16(), mxmur2_2(), mxmur2_3(), mxmur2_4(), mxmur2_5(), mxmur2_6(), mxmur2_7(), mxmur2_8(), and mxmur2_9().
subroutine mxmur2_1 (real, dimension(n1,1) a, n1, real, dimension(1,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1285 of file mxm_std.f.
References j.
subroutine mxmur2_10 (real, dimension(n1,10) a, n1, real, dimension(10,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1420 of file mxm_std.f.
References j.
subroutine mxmur2_11 (real, dimension(n1,11) a, n1, real, dimension(11,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1440 of file mxm_std.f.
References j.
subroutine mxmur2_12 (real, dimension(n1,12) a, n1, real, dimension(12,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1461 of file mxm_std.f.
References j.
subroutine mxmur2_13 (real, dimension(n1,13) a, n1, real, dimension(13,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1483 of file mxm_std.f.
References j.
subroutine mxmur2_14 (real, dimension(n1,14) a, n1, real, dimension(14,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1506 of file mxm_std.f.
References j.
subroutine mxmur2_15 (real, dimension(n1,15) a, n1, real, dimension(15,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1530 of file mxm_std.f.
References j.
subroutine mxmur2_16 (real, dimension(n1,16) a, n1, real, dimension(16,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1555 of file mxm_std.f.
References j.
subroutine mxmur2_2 (real, dimension(n1,2) a, n1, real, dimension(2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1296 of file mxm_std.f.
References j.
subroutine mxmur2_3 (real, dimension(n1,3) a, n1, real, dimension(3,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1308 of file mxm_std.f.
References j.
subroutine mxmur2_4 (real, dimension(n1,4) a, n1, real, dimension(4,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1321 of file mxm_std.f.
References j.
subroutine mxmur2_5 (real, dimension(n1,5) a, n1, real, dimension(5,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1335 of file mxm_std.f.
References j.
subroutine mxmur2_6 (real, dimension(n1,6) a, n1, real, dimension(6,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1350 of file mxm_std.f.
References j.
subroutine mxmur2_7 (real, dimension(n1,7) a, n1, real, dimension(7,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1366 of file mxm_std.f.
References j.
subroutine mxmur2_8 (real, dimension(n1,8) a, n1, real, dimension(8,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1383 of file mxm_std.f.
References j.
subroutine mxmur2_9 (real, dimension(n1,9) a, n1, real, dimension(9,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1401 of file mxm_std.f.
References j.
subroutine mxmur3 (real, dimension(n1,n2) a, n1, real, dimension(n2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 1582 of file mxm_std.f.
References j, mxmur3_1(), mxmur3_10(), mxmur3_11(), mxmur3_12(), mxmur3_13(), mxmur3_14(), mxmur3_15(), mxmur3_16(), mxmur3_2(), mxmur3_3(), mxmur3_4(), mxmur3_5(), mxmur3_6(), mxmur3_7(), mxmur3_8(), and mxmur3_9().
subroutine mxmur3_1 (real, dimension(n1,n2) a, n1, real, dimension(n2,1) b, n2, real, dimension(n1,1) c, n3)
Definition at line 2077 of file mxm_std.f.
subroutine mxmur3_10 (real, dimension(n1,n2) a, n1, real, dimension(n2,10) b, n2, real, dimension(n1,10) c, n3)
Definition at line 1870 of file mxm_std.f.
subroutine mxmur3_11 (real, dimension(n1,n2) a, n1, real, dimension(n2,11) b, n2, real, dimension(n1,11) c, n3)
Definition at line 1837 of file mxm_std.f.
subroutine mxmur3_12 (real, dimension(n1,n2) a, n1, real, dimension(n2,12) b, n2, real, dimension(n1,12) c, n3)
Definition at line 1802 of file mxm_std.f.
subroutine mxmur3_13 (real, dimension(n1,n2) a, n1, real, dimension(n2,13) b, n2, real, dimension(n1,13) c, n3)
Definition at line 1765 of file mxm_std.f.
subroutine mxmur3_14 (real, dimension(n1,n2) a, n1, real, dimension(n2,14) b, n2, real, dimension(n1,14) c, n3)
Definition at line 1726 of file mxm_std.f.
subroutine mxmur3_15 (real, dimension(n1,n2) a, n1, real, dimension(n2,15) b, n2, real, dimension(n1,15) c, n3)
Definition at line 1685 of file mxm_std.f.
subroutine mxmur3_16 (real, dimension(n1,n2) a, n1, real, dimension(n2,16) b, n2, real, dimension(n1,16) c, n3)
Definition at line 1642 of file mxm_std.f.
subroutine mxmur3_2 (real, dimension(n1,n2) a, n1, real, dimension(n2,2) b, n2, real, dimension(n1,2) c, n3)
Definition at line 2062 of file mxm_std.f.
subroutine mxmur3_3 (real, dimension(n1,n2) a, n1, real, dimension(n2,3) b, n2, real, dimension(n1,3) c, n3)
Definition at line 2045 of file mxm_std.f.
subroutine mxmur3_4 (real, dimension(n1,n2) a, n1, real, dimension(n2,4) b, n2, real, dimension(n1,4) c, n3)
Definition at line 2026 of file mxm_std.f.
subroutine mxmur3_5 (real, dimension(n1,n2) a, n1, real, dimension(n2,5) b, n2, real, dimension(n1,5) c, n3)
Definition at line 2005 of file mxm_std.f.
subroutine mxmur3_6 (real, dimension(n1,n2) a, n1, real, dimension(n2,6) b, n2, real, dimension(n1,6) c, n3)
Definition at line 1982 of file mxm_std.f.
subroutine mxmur3_7 (real, dimension(n1,n2) a, n1, real, dimension(n2,7) b, n2, real, dimension(n1,7) c, n3)
Definition at line 1957 of file mxm_std.f.
subroutine mxmur3_8 (real, dimension(n1,n2) a, n1, real, dimension(n2,8) b, n2, real, dimension(n1,8) c, n3)
Definition at line 1930 of file mxm_std.f.
subroutine mxmur3_9 (real, dimension(n1,n2) a, n1, real, dimension(n2,9) b, n2, real, dimension(n1,9) c, n3)
Definition at line 1901 of file mxm_std.f.
subroutine out_anal (real, dimension(nn,2,nt,3) s, real, dimension(nn,2,nt,3) a, nn, character*5, dimension(3,nt) c, nt, integer, dimension(200) itmax, character*8 name8, k, ivb)
Definition at line 4098 of file mxm_std.f.
References n.