KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/n2to3/n2to3.f File Reference
n2to3.f File Reference
Functions/Subroutines
program trans
subroutine rea23 (dzi, zmin, neln, itype)
subroutine rea2re2 (dzi, zmin, cb5, cb6, ifflow, ifheat, ifper, ifmhd)
subroutine re2_bc (nbc, cb5, cb6, ifflow, ifheat, ifper)
subroutine re2_curve (ifcirc)
subroutine re2_xyz (x, y, dzi, zmin, nel, nlev, ifcirc)
subroutine bufchk (buf, n)
subroutine blank (s, n)
function ltrunc (s, n)
integer function indx1 (s1, s2, l2)
subroutine readwrite (sout, key, nk)
function glmax (a, n)
function glmin (a, n)
subroutine addc (x, c, n)
subroutine cmult (x, c, n)
subroutine copy (a, b, n)
subroutine icopy (a, b, n)
subroutine chcopy (x, y, n)
subroutine rzero (x, n)
subroutine izero (x, n)
subroutine rzero8 (x, n)
subroutine rdcurve
subroutine out_curve (itype)
function mod1 (i, n)
subroutine sweep_circ (xc, yc, zc, x, y, n, theta)
subroutine out_e_hdr (e, ilev, a, igroup, io)
subroutine newcurve (itype)
subroutine outcurve (r1, r2, r3, r4, r5, cc, edge, e, nel, ipass, itype)
subroutine get_midside (xm, ym, edge, e)
subroutine capit (lettrs, n)
subroutine exitt
subroutine exitrr (stringi, r1, r2)
subroutine rdparam (ifflow, ifheat, ifmhd)
Function/Subroutine Documentation
subroutine addc (real, dimension(1) x, c, n)
Definition at line 1041 of file n2to3.f.
References i, and n.
subroutine blank (character*1, dimension(1) s, n)
Definition at line 950 of file n2to3.f.
References i, and n.
subroutine bufchk (real*8, dimension(n) buf, n)
Definition at line 941 of file n2to3.f.
References n.
subroutine capit (character, dimension(n) lettrs, n)
Definition at line 1512 of file n2to3.f.
References i, and n.
subroutine chcopy (character*1, dimension(1) x, character*1, dimension(1) y, n)
Definition at line 1073 of file n2to3.f.
References i, and n.
subroutine cmult (real, dimension(1) x, c, n)
Definition at line 1049 of file n2to3.f.
References i, and n.
subroutine copy (real, dimension(1) a, real, dimension(1) b, n)
Definition at line 1057 of file n2to3.f.
References i, and n.
subroutine exitrr (character*1, dimension(132) stringi, r1, r2)
Definition at line 1532 of file n2to3.f.
References blank(), chcopy(), exitt(), and indx1().
subroutine exitt ()
Definition at line 1525 of file n2to3.f.
References exit().
subroutine get_midside (xm, ym, integer edge, integer e)
Definition at line 1461 of file n2to3.f.
References i0, and mod1().
function glmax (real, dimension(1) a, n)
Definition at line 1021 of file n2to3.f.
References glmax(), i, and n.
function glmin (real, dimension(1) a, n)
Definition at line 1031 of file n2to3.f.
References glmin(), i, and n.
subroutine icopy (integer, dimension(1) a, integer, dimension(1) b, n)
Definition at line 1065 of file n2to3.f.
References i, and n.
integer function indx1 (character*80 s1, character*80 s2, l2)
Definition at line 970 of file n2to3.f.
References i, and indx1().
subroutine izero (integer, dimension(1) x, n)
Definition at line 1089 of file n2to3.f.
References i, and n.
function ltrunc (character*1, dimension(1) s, n)
Definition at line 958 of file n2to3.f.
References j, ltrunc(), and n.
function mod1 (i, n)
Definition at line 1284 of file n2to3.f.
References i, mod1(), and n.
subroutine newcurve (itype)
Definition at line 1341 of file n2to3.f.
References get_midside(), i, outcurve(), and sweep_circ().
subroutine out_curve (itype)
Definition at line 1152 of file n2to3.f.
References byte_write, chcopy(), and exit().
subroutine out_e_hdr (integer e, ilev, character*1 a, igroup, io)
Definition at line 1324 of file n2to3.f.
subroutine outcurve (r1, r2, r3, r4, r5, character*1 cc, integer edge, integer e, nel, ipass, itype)
Definition at line 1399 of file n2to3.f.
References byte_write, and chcopy().
subroutine rdcurve ()
Definition at line 1105 of file n2to3.f.
References blank(), exit(), and rzero().
subroutine rdparam (logical ifflow, logical ifheat, logical ifmhd)
Definition at line 1553 of file n2to3.f.
References blank(), i, indx1(), ltrunc(), and readwrite().
subroutine re2_bc (nbc, character*3, dimension(2) cb5, character*3, dimension(2) cb6, logical ifflow, logical ifheat, logical ifper)
Definition at line 623 of file n2to3.f.
References blank(), byte_write, chcopy(), izero(), j, rzero(), and rzero8().
subroutine re2_curve (logical ifcirc)
Definition at line 824 of file n2to3.f.
References newcurve(), out_curve(), and rdcurve().
subroutine re2_xyz (real, dimension(4,1) x, real, dimension(4,1) y, real, dimension(1) dzi, zmin, nel, nlev, logical ifcirc)
Definition at line 839 of file n2to3.f.
References byte_write, and sweep_circ().
subroutine rea23 (real, dimension(1) dzi, zmin, neln, itype)
Definition at line 162 of file n2to3.f.
References blank(), byte_write, exit(), izero(), j, ltrunc(), mod1(), newcurve(), out_curve(), out_e_hdr(), rdcurve(), rdparam(), rea2re2(), readwrite(), rzero(), rzero8(), and sweep_circ().
subroutine rea2re2 (real, dimension(1) dzi, zmin, character*3, dimension(2) cb5, character*3, dimension(2) cb6, logical ifflow, logical ifheat, logical ifper, logical ifmhd)
Definition at line 582 of file n2to3.f.
References re2_bc(), re2_curve(), re2_xyz(), and readwrite().
subroutine readwrite (character*80 sout, character*80 key, nk)
Definition at line 988 of file n2to3.f.
References blank(), capit(), chcopy(), i, indx1(), and ltrunc().
subroutine rzero (real, dimension(1) x, n)
Definition at line 1081 of file n2to3.f.
References i, and n.
subroutine rzero8 (real*8, dimension(1) x, n)
Definition at line 1097 of file n2to3.f.
References i, and n.
subroutine sweep_circ (real, dimension(n) xc, real, dimension(n) yc, real, dimension(n) zc, real, dimension(n) x, real, dimension(n) y, n, theta)
Definition at line 1302 of file n2to3.f.
References i, and n.
program trans ()
Definition at line 2 of file n2to3.f.
References blank(), byte_close, byte_open, chcopy(), exitrr(), i, ltrunc(), and rea23().