KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/navier6.f File Reference
navier6.f File Reference
Functions/Subroutines
subroutine set_overlap
subroutine overflow_ck (n_req, n_avail, signal)
subroutine iunswap (b, ind, n, temp)
subroutine set_fem_data_l2 (nep, nd, no, x, y, z, p)
subroutine map_face12 (x2, x1, w1, w2)
subroutine map_one_face12 (x2, x1, iface, i12, i12t, w1, w2)
subroutine dface_add1sa (x)
subroutine faces (a, s, ie, iface, nx, ny, nz)
Function/Subroutine Documentation
dface_add1sa()
subroutine dface_add1sa (real, dimension(lx1,ly1,lz1,1) x)
Definition at line 336 of file navier6.f.
References ly1, and lz1.
faces()
subroutine faces (dimension(nx,ny,nz,lelt) a, s, ie, iface, nx, ny, nz)
Definition at line 386 of file navier6.f.
References facind(), and lelt.
iunswap()
subroutine iunswap (integer, dimension(1) b, integer, dimension(1) ind, n, integer, dimension(1) temp)
Definition at line 135 of file navier6.f.
map_face12()
subroutine map_face12 (real, dimension(lx1*ly1*lz1,1) x2, real, dimension(lx1*ly1*lz1,1) x1, real, dimension(1) w1, real, dimension(1) w2)
Definition at line 246 of file navier6.f.
References map_one_face12().
map_one_face12()
subroutine map_one_face12 (real, dimension(lx1,ly1,lz1) x2, real, dimension(lx1,ly1,lz1) x1, iface, real, dimension(1) i12, real, dimension(1) i12t, real, dimension(1) w1, real, dimension(1) w2)
Definition at line 278 of file navier6.f.
References copy(), facind(), ly1, lz1, and mxm().
overflow_ck()
subroutine overflow_ck (n_req, n_avail, character*11 signal)
Definition at line 116 of file navier6.f.
References exitt(), and mynode().
set_fem_data_l2()
subroutine set_fem_data_l2 (nep, nd, no, real, dimension(lx1,ly1,lz1,1) x, real, dimension(lx1,ly1,lz1,1) y, real, dimension(lx1,ly1,lz1,1) z, real, dimension(lx1,ly1,lz1,1) p)
Definition at line 150 of file navier6.f.
References dface_add1sa(), faces(), ly1, lz1, map_face12(), rzero(), and scale().
set_overlap()
subroutine set_overlap ()
Definition at line 31 of file navier6.f.
References gen_fast(), gen_fast_spacing(), h1mg_setup(), hsmg_setup(), init_weight_op(), lelt, ly1, lz1, set_fem_data_l2(), set_up_h1_crs(), and swap_lengths().