KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/navier4.f File Reference
navier4.f File Reference
Functions/Subroutines
subroutine setrhs (p, h1, h2, h2inv)
subroutine gensoln (p, h1, h2, h2inv)
subroutine updtset (p, h1, h2, h2inv, IERR)
subroutine econj (kprev, h1, h2, h2inv, ierr)
subroutine chkptol
function vlsc3 (X, Y, B, N)
subroutine updrhse (p, h1, h2, h2inv, ierr)
subroutine echeck (kprev, h1, h2, h2inv, intetype)
subroutine projh (r, h1, h2, bi, vml, vmk, approx, napprox, wl, ws, name4)
subroutine gensh (v1, h1, h2, vml, vmk, approx, napprox, wl, ws, name4)
subroutine hconj (approx, k, h1, h2, vml, vmk, ws, name4, ierr)
subroutine updrhsh (approx, napprox, h1, h2, vml, vmk, ws, name4)
subroutine hmhzpf (name, u, r, h1, h2, mask, mult, imesh, tli, maxit, isd, bi)
subroutine hsolve (name, u, r, h1, h2, vmk, vml, imsh, tol, maxit, isd, approx, napprox, bi)
subroutine project1 (b, n, rvar, ivar, h1, h2, msk, w, ifwt, ifvec, name6)
subroutine project1_a (xbar, bbar, b, xx, bb, n, m, w, ifwt, ifvec)
function iproj_chk (h1old, h2old, h1, h2, n)
subroutine proj_matvec (b, x, n, h1, h2, msk, name6)
subroutine proj_ortho (xx, bb, n, m, w, ifwt, ifvec, name6)
subroutine project2 (x, n, rvar, ivar, h1, h2, msk, w, ifwt, ifvec, name6)
subroutine project2_a (x, xbar, xx, bb, n, m, mmx, h1, h2, msk, w, ifwt, ifvec, name6)
subroutine proj_get_ivar (m, mmx, ixb, ibb, ix, ib, ih1, ih2, ivar, n, ifvec, name6)
subroutine laplacep (name, u, mask, mult, ifld, tol, maxi, approx, napprox)
Function/Subroutine Documentation
subroutine chkptol ()
Definition at line 267 of file navier4.f.
References col3(), glsc2(), and opdiv().
subroutine echeck (kprev, real, dimension (lx1,ly1,lz1,lelv) h1, real, dimension (lx1,ly1,lz1,lelv) h2, real, dimension(lx1,ly1,lz1,lelv) h2inv, intetype)
Definition at line 431 of file navier4.f.
References cdabdtp().
subroutine econj (kprev, real, dimension (lx1,ly1,lz1,lelv) h1, real, dimension (lx1,ly1,lz1,lelv) h2, real, dimension(lx1,ly1,lz1,lelv) h2inv, ierr)
Definition at line 200 of file navier4.f.
References add2s2(), cdabdtp(), cmult(), glsc2(), gop(), and vlsc2().
subroutine gensh (real, dimension(1) v1, real, dimension(1) h1, real, dimension(1) h2, real, dimension(1) vml, real, dimension(1) vmk, real, dimension(lt,0:1) approx, integer, dimension(2) napprox, real, dimension(1) wl, real, dimension(1) ws, character*4 name4)
Definition at line 554 of file navier4.f.
References add2(), copy(), hconj(), lelt, ly1, and lz1.
subroutine gensoln (real, dimension (lx2,ly2,lz2,lelv) p, real, dimension (lx1,ly1,lz1,lelv) h1, real, dimension (lx1,ly1,lz1,lelv) h2, real, dimension(lx1,ly1,lz1,lelv) h2inv)
Definition at line 111 of file navier4.f.
References add2(), copy(), and updtset().
subroutine hconj (real, dimension(lt,0:1) approx, k, real, dimension(1) h1, real, dimension(1) h2, real, dimension(1) vml, real, dimension(1) vmk, real, dimension(1) ws, character*4 name4, ierr)
Definition at line 611 of file navier4.f.
References add2s2(), axhelm(), cmult(), col2(), glsc2(), gop(), lelt, ly1, lz1, and vlsc2().
subroutine hmhzpf (character*4 name, real, dimension (lx1,ly1,lz1,1) u, real, dimension (lx1,ly1,lz1,1) r, real, dimension (lx1,ly1,lz1,1) h1, real, dimension (lx1,ly1,lz1,1) h2, real, dimension (lx1,ly1,lz1,1) mask, real, dimension (lx1,ly1,lz1,1) mult, imesh, tli, maxit, isd, real, dimension (lx1,ly1,lz1,1) bi)
Definition at line 755 of file navier4.f.
References cggo(), cggo_dg(), chktcg1(), dnekclock(), lelt, ly1, and lz1.
subroutine hsolve (character*4 name, real, dimension (lx1,ly1,lz1,1) u, real, dimension (lx1,ly1,lz1,1) r, real, dimension (lx1,ly1,lz1,1) h1, real, dimension (lx1,ly1,lz1,1) h2, real, dimension (lx1,ly1,lz1,1) vmk, real, dimension (lx1,ly1,lz1,1) vml, imsh, tol, maxit, isd, real, dimension (1) approx, integer, dimension(1) napprox, real, dimension (lx1,ly1,lz1,1) bi)
Definition at line 805 of file navier4.f.
References blank(), capit(), chcopy(), col2(), dssum(), hmholtz(), hmhzpf(), lelt, ly1, lz1, n, project1(), and project2().
function iproj_chk (real, dimension(n) h1old, real, dimension(n) h2old, real, dimension(n) h1, real, dimension(n) h2, n)
Definition at line 1013 of file navier4.f.
References copy(), glmax(), and n.
subroutine laplacep (character*4 name, real, dimension(1) u, real, dimension(1) mask, real, dimension(1) mult, ifld, tol, maxi, real, dimension (1) approx, integer, dimension(1) napprox)
Definition at line 1240 of file navier4.f.
References add2(), axhelm(), blank(), capit(), chcopy(), copy(), dsavg(), dssum(), hmhzpf(), lelt, ly1, lz1, n, project1(), project2(), rone(), and rzero().
subroutine proj_get_ivar (m, mmx, ixb, ibb, ix, ib, ih1, ih2, integer, dimension(10) ivar, n, logical ifvec, character*6 name6)
Definition at line 1208 of file navier4.f.
References n.
subroutine proj_matvec (real, dimension(n) b, real, dimension(n) x, n, real, dimension(n) h1, real, dimension(n) h2, real, dimension(n) msk, character*6 name6)
Definition at line 1049 of file navier4.f.
References axhelm(), col2(), dssum(), and n.
subroutine proj_ortho (real, dimension(n,1) xx, real, dimension(n,1) bb, n, m, real, dimension(n) w, logical ifwt, logical ifvec, character*6 name6)
Definition at line 1070 of file navier4.f.
References add2s2(), cmult(), copy(), glsc2(), glsc3(), glsum(), n, scale(), vlsc2(), and vlsc3().
subroutine project1 (real, dimension(n) b, n, real, dimension(n,1) rvar, integer, dimension(1) ivar, real, dimension(n) h1, real, dimension(n) h2, real, dimension(n) msk, real, dimension(n) w, logical ifwt, logical ifvec, character*6 name6)
Definition at line 871 of file navier4.f.
References dnekclock(), glsc3(), iproj_chk(), n, proj_get_ivar(), proj_matvec(), proj_ortho(), and project1_a().
subroutine project1_a (real, dimension(n) xbar, real, dimension(n) bbar, real, dimension(n) b, real, dimension(n,m) xx, real, dimension(n,m) bb, n, m, real, dimension(n) w, logical ifwt, logical ifvec)
Definition at line 975 of file navier4.f.
References add2s2(), cmult2(), gop(), n, sub2(), vlsc2(), and vlsc3().
subroutine project2 (real, dimension(n) x, n, real, dimension(n,1) rvar, integer, dimension(1) ivar, real, dimension(n) h1, real, dimension(n) h2, real, dimension(n) msk, real, dimension(n) w, logical ifwt, logical ifvec, character*6 name6)
Definition at line 1153 of file navier4.f.
References dnekclock(), n, proj_get_ivar(), and project2_a().
subroutine project2_a (real, dimension(n) x, real, dimension(n) xbar, real, dimension(n,1) xx, real, dimension(n,1) bb, n, m, mmx, real, dimension(n) h1, real, dimension(n) h2, real, dimension(n) msk, real, dimension(n) w, logical ifwt, logical ifvec, character*6 name6)
Definition at line 1181 of file navier4.f.
References add2(), copy(), n, proj_matvec(), and proj_ortho().
subroutine projh (real, dimension(1) r, real, dimension(1) h1, real, dimension(1) h2, real, dimension(1) bi, real, dimension(1) vml, real, dimension(1) vmk, real, dimension(lt,0:1) approx, integer, dimension(2) napprox, real, dimension(1) wl, real, dimension(1) ws, character*4 name4)
Definition at line 475 of file navier4.f.
References add2s2(), axhelm(), cmult2(), col2(), dssum(), glsc23(), gop(), lelt, ly1, lz1, sub2(), updrhsh(), and vlsc3().
subroutine setrhs (real, dimension (lx2,ly2,lz2,lelv) p, real, dimension (lx1,ly1,lz1,lelv) h1, real, dimension (lx1,ly1,lz1,lelv) h2, real, dimension(lx1,ly1,lz1,lelv) h2inv)
Definition at line 10 of file navier4.f.
References add2s2(), cdabdtp(), glsc3(), gop(), rzero(), sub2(), updrhse(), and vlsc2().
subroutine updrhse (real, dimension (lx2,ly2,lz2,lelv) p, real, dimension (lx1,ly1,lz1,lelv) h1, real, dimension (lx1,ly1,lz1,lelv) h2, real, dimension(lx1,ly1,lz1,lelv) h2inv, ierr)
Definition at line 355 of file navier4.f.
References econj(), and invers2().
subroutine updrhsh (real, dimension(lt,0:1) approx, integer, dimension(2) napprox, real, dimension(1) h1, real, dimension(1) h2, real, dimension(1) vml, real, dimension(1) vmk, real, dimension(1) ws, character*4 name4)
Definition at line 691 of file navier4.f.
References copy(), hconj(), lelt, ly1, and lz1.
subroutine updtset (real, dimension (lx2,ly2,lz2,lelv) p, real, dimension (lx1,ly1,lz1,lelv) h1, real, dimension (lx1,ly1,lz1,lelv) h2, real, dimension(lx1,ly1,lz1,lelv) h2inv, IERR)
Definition at line 148 of file navier4.f.
References copy(), and econj().
function vlsc3 (dimension(1) X, dimension(1) Y, dimension(1) B, N)
Definition at line 322 of file navier4.f.
References n.