KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/navier5.f File Reference
navier5.f File Reference
Functions/Subroutines
subroutine q_filter (wght)
subroutine filterq (v, f, nx, nz, w1, w2, ft, if3d, dmax)
subroutine outmatx (a, m, n, io, name)
subroutine drag_calc (scale)
subroutine mappr (pm1, pm2, pa, pb)
function facint_a (a, area, f, e)
function facint_v (a, area, f, e)
function facint (a, b, area, ifc, ie)
function facint2 (a, b, c, area, ifc, ie)
subroutine out_csrmats (acsr, ia, ja, n, name9)
subroutine local_grad3 (ur, us, ut, u, N, e, D, Dt)
subroutine local_grad2 (ur, us, u, N, e, D, Dt)
subroutine gradm1 (ux, uy, uz, u)
subroutine comp_vort3 (vort, work1, work2, u, v, w)
subroutine surface_int (sint, sarea, a, e, f)
subroutine surface_flux (dq, qx, qy, qz, e, f, w)
subroutine gaujordf (a, m, n, indr, indc, ipiv, ierr, rmult)
subroutine legendre_poly (L, x, N)
subroutine build_new_filter (intv, zpts, nx, kut, wght, nio)
subroutine avg_all
subroutine avg1 (avg, f, alpha, beta, n, name, ifverbose)
subroutine avg2 (avg, f, alpha, beta, n, name, ifverbose)
subroutine avg3 (avg, f, g, alpha, beta, n, name, ifverbose)
subroutine build_legend_transform (Lj, Ljt, zpts, nx)
subroutine local_err_est (err, u, nx, Lj, Ljt, uh, w, if3d)
subroutine get_exyz (ex, ey, ez, eg, nelx, nely, nelz)
subroutine dump_header2d (excode, nx, ny, nlx, nly, ierr)
subroutine outfld2d_p (u, v, w, nx, ny, nlx, nly, name, ifld, jid, npido, ir)
subroutine outfld2d (u, v, w, nx, ny, nlx, nly, name, ifld)
subroutine planar_average_z (ua, u, w1, w2)
subroutine drgtrq (dgtq, xm0, ym0, zm0, sij, pm1, visc, f, e)
subroutine torque_calc (scale, x0, ifdout, iftout)
subroutine comp_sij (sij, nij, u, v, w, ur, us, ut, vr, vs, vt, wr, ws, wt)
subroutine auto_averager (fname127)
subroutine x_average (ua, u, w1, w2)
subroutine x_average_transpose (u, ua)
subroutine x_distribute (u)
subroutine x_distribute2 (ua, u)
subroutine y_slice (ua, u, w1, w2)
subroutine z_slice_g (uz, u, w1, kz, ezi, nx, ny, nz, nlxy)
subroutine z_slice (ua, u, w1, w2)
subroutine y_average (ua, u, w1, w2)
subroutine y_avg_buff (ux, uy, uz, c2, name, icount)
subroutine z_avg_buff (ux, uy, uz, c2, name, icount)
subroutine y_ins_buff (ux, uy, uz, c2, name, icount)
subroutine z_ins_buff (ux, uy, uz, c2, name, icount)
subroutine buff_2d_out (u, v, w, nx, ny, nex, ney, c2, name, ifld)
subroutine y2d (u, v, w, p, c1, icount)
subroutine z2d (u, v, w, p, c1, icount)
subroutine anal_2d
subroutine chkit (u, name4, n)
subroutine outmesh
subroutine out_el (xt, e)
subroutine get_el (xt, x, y, z)
subroutine shear_calc_max (strsmx, scale, x0, ifdout, iftout)
subroutine get_strsmax (strsmax, xm0, ym0, zm0, sij, pm1, visc, f, e)
subroutine fix_geom
subroutine gh_face_extend (x, zg, n, gh_type, e, v)
subroutine gh_face_extend_2d (x, zg, n, gh_type, e, v)
subroutine gh_face_extend_3d (x, zg, n, gh_type, e, v)
real function ran1 (idum)
subroutine rand_fld_h1 (x)
subroutine rescale_x (x, x0, x1)
subroutine z_distribute (u)
subroutine z_average (ua, u, w1, w2)
subroutine z_average_transpose (u, ua)
subroutine no_z_profile (u)
subroutine z_profile (ua, u, w1, w2)
subroutine z_profile_transpose (u, ua)
subroutine no_y_profile (u)
subroutine y_profile (ua, u, w1, w2)
subroutine y_profile_transpose (u, ua)
subroutine build_filter (f, diag, nx)
subroutine g_filter (u, diag, ifld)
subroutine cut_off_filter (u, mx, ifld)
subroutine filter_d2 (v, nx, nz, wgt, ifd4)
function dist3d (a, b, c, x, y, z)
function dist2d (a, b, x, y)
subroutine domain_size (xmin, xmax, ymin, ymax, zmin, zmax)
subroutine cheap_dist (d, ifld, b)
subroutine distf (d, ifld, b, dmin, emin, xn, yn, zn)
subroutine turb_outflow (d, m1, rq, uin)
subroutine add_temp (f2tbc, nbc, npass)
subroutine add_temp_1 (f2tbc, nbc)
Function/Subroutine Documentation
add_temp()
subroutine add_temp (character*3, dimension(2,nbc) f2tbc, nbc, npass)
Definition at line 4611 of file navier5.f.
References add_temp_1(), and setup_topo().
add_temp_1()
subroutine add_temp_1 (character*3, dimension(2,nbc) f2tbc, nbc)
Definition at line 4630 of file navier5.f.
References chcopy(), copy(), and icopy().
anal_2d()
subroutine anal_2d ()
Definition at line 2951 of file navier5.f.
References y2d(), and z2d().
auto_averager()
subroutine auto_averager (character*127 fname127)
Definition at line 2307 of file navier5.f.
References add2(), bcast(), blank(), chcopy(), cmult2(), exitti(), iglmax(), indx1(), lelt, ly1, lz1, opadd2(), restart(), rzero(), and scale().
avg1()
subroutine avg1 (real, dimension(n) avg, real, dimension(n) f, alpha, beta, n, character*4 name, logical ifverbose)
Definition at line 1292 of file navier5.f.
References glmax(), and glmin().
avg2()
subroutine avg2 (real, dimension(n) avg, real, dimension(n) f, alpha, beta, n, character*4 name, logical ifverbose)
Definition at line 1315 of file navier5.f.
References glmax(), and glmin().
avg3()
subroutine avg3 (real, dimension(n) avg, real, dimension(n) f, real, dimension(n) g, alpha, beta, n, character*4 name, logical ifverbose)
Definition at line 1338 of file navier5.f.
References glmax(), and glmin().
avg_all()
subroutine avg_all ()
Definition at line 1159 of file navier5.f.
References avg1(), avg2(), avg3(), exitt(), ly1, lz1, outpost(), outpost2(), and rzero().
buff_2d_out()
subroutine buff_2d_out (real, dimension(1) u, real, dimension(1) v, real, dimension(1) w, nx, ny, nex, ney, character*2 c2, character*2 name, ifld)
Definition at line 2806 of file navier5.f.
References copy(), err_chk(), lz1, and outfld2d_p().
build_filter()
subroutine build_filter (real, dimension(nx,nx) f, real, dimension(nx) diag, nx)
Definition at line 4001 of file navier5.f.
References copy(), exitti(), gaujordf(), legendre_poly(), mxm(), transpose(), and zwgll().
build_legend_transform()
subroutine build_legend_transform (real, dimension(nx*nx) Lj, real, dimension(nx*nx) Ljt, real, dimension(nx) zpts, nx)
Definition at line 1361 of file navier5.f.
References exitt(), gaujordf(), legendre_poly(), transpose(), and transpose1().
build_new_filter()
subroutine build_new_filter (real, dimension(nx,nx) intv, real, dimension(nx) zpts, nx, kut, wght, nio)
Definition at line 1077 of file navier5.f.
References copy(), exitt(), gaujordf(), ident(), legendre_poly(), mxm(), and transpose().
cheap_dist()
subroutine cheap_dist (real, dimension(lx1,ly1,lz1,lelt) d, ifld, character*3 b)
Definition at line 4251 of file navier5.f.
References cfill(), dist2d(), dist3d(), domain_size(), facev(), glmax(), iglsum(), ly1, and lz1.
chkit()
subroutine chkit (real, dimension(1) u, character*4 name4, n)
Definition at line 2990 of file navier5.f.
References vlmax(), vlmin(), and vlsc2().
comp_sij()
subroutine comp_sij (real, dimension(lx1*ly1*lz1,nij,lelv) sij, nij, real, dimension (lx1*ly1*lz1,lelv) u, real, dimension (lx1*ly1*lz1,lelv) v, real, dimension (lx1*ly1*lz1,lelv) w, real, dimension (1) ur, real, dimension (1) us, real, dimension (1) ut, real, dimension (1) vr, real, dimension (1) vs, real, dimension (1) vt, real, dimension (1) wr, real, dimension (1) ws, real, dimension (1) wt)
Definition at line 2172 of file navier5.f.
References local_grad2(), local_grad3(), ly1, lz1, and setaxdy().
comp_vort3()
subroutine comp_vort3 (real, dimension(lt,3) vort, real, dimension(1) work1, real, dimension(1) work2, real, dimension(1) u, real, dimension(1) v, real, dimension(1) w)
Definition at line 789 of file navier5.f.
References col2(), dssum(), local_grad2(), local_grad3(), ly1, and lz1.
cut_off_filter()
subroutine cut_off_filter (real, dimension(1) u, mx, ifld)
Definition at line 4082 of file navier5.f.
References build_filter(), filterq(), ly1, lz1, and rone().
dist2d()
function dist2d (a, b, x, y)
Definition at line 4219 of file navier5.f.
dist3d()
function dist3d (a, b, c, x, y, z)
Definition at line 4209 of file navier5.f.
distf()
subroutine distf (real, dimension(lx1,ly1,lz1,lelt) d, ifld, character*3 b, real, dimension(lx1,ly1,lz1,lelt) dmin, real, dimension(lx1,ly1,lz1,lelt) emin, real, dimension(lx1,ly1,lz1,lelt) xn, real, dimension(lx1,ly1,lz1,lelt) yn, real, dimension(lx1,ly1,lz1,lelt) zn)
Definition at line 4348 of file navier5.f.
References cfill(), copy(), domain_size(), facev(), glmax(), iglsum(), ly1, lz1, and opcopy().
domain_size()
subroutine domain_size (xmin, xmax, ymin, ymax, zmin, zmax)
Definition at line 4229 of file navier5.f.
References glmax(), glmin(), ly1, and lz1.
drag_calc()
subroutine drag_calc (scale)
Definition at line 250 of file navier5.f.
References add2s2(), cfill(), col2(), dudxyz(), facint(), facint2(), gop(), ly1, lz1, mappr(), rone(), and scale().
drgtrq()
subroutine drgtrq (real, dimension(3,4) dgtq, real, dimension (lx1,ly1,lz1,lelt) xm0, real, dimension (lx1,ly1,lz1,lelt) ym0, real, dimension (lx1,ly1,lz1,lelt) zm0, real, dimension (lx1,ly1,lz1,3*ldim-3,lelv) sij, real, dimension (lx1,ly1,lz1,lelv) pm1, real, dimension(lx1,ly1,lz1,lelv) visc, integer f, integer e)
Definition at line 1807 of file navier5.f.
References dsset(), ly1, lz1, and rzero().
dump_header2d()
subroutine dump_header2d (character*2, dimension(15) excode, nx, ny, nlx, nly, ierr)
Definition at line 1538 of file navier5.f.
References byte_write.
facint()
function facint (dimension (lx1,ly1,lz1,lelv) a, dimension (lx1,lz1,6,lelv) b, dimension (lx1,lz1,6,lelv) area, ifc, ie)
Definition at line 606 of file navier5.f.
References dsset(), ly1, and lz1.
facint2()
function facint2 (dimension (lx1,ly1,lz1,lelv) a, dimension (lx1,lz1,6,lelv) b, dimension (lx1,lz1,6,lelv) c, dimension (lx1,lz1,6,lelv) area, ifc, ie)
Definition at line 646 of file navier5.f.
References dsset(), ly1, and lz1.
facint_a()
function facint_a (real, dimension(lx1,lz1,6,lelt) a, real, dimension(lx1,lz1,6,lelt) area, integer f, integer e)
Definition at line 550 of file navier5.f.
References lz1.
facint_v()
function facint_v (real, dimension(lx1,ly1,lz1,lelt) a, real, dimension(lx1,lz1,6,lelt) area, integer f, integer e)
Definition at line 571 of file navier5.f.
References dsset(), ly1, and lz1.
filter_d2()
subroutine filter_d2 (real, dimension(lt,nelt) v, nx, nz, wgt, logical ifd4)
Definition at line 4110 of file navier5.f.
References dsavg(), glamax(), lelt, local_grad2(), local_grad2_t(), local_grad3(), local_grad3_t(), ly1, and lz1.
filterq()
subroutine filterq (real, dimension(nx*nx*nz,nelt) v, real, dimension(nx,nx) f, nx, nz, real, dimension(1) w1, real, dimension(1) w2, real, dimension(nx,nx) ft, logical if3d, dmax)
Definition at line 179 of file navier5.f.
References copy(), mxm(), sub3(), transpose(), and vlamax().
fix_geom()
subroutine fix_geom ()
Definition at line 3301 of file navier5.f.
References add2(), copy(), dsop(), dssum(), facev(), geom_reset(), gh_face_extend(), glamax(), glmax(), lelt, ly1, lz1, and rone().
g_filter()
subroutine g_filter (real, dimension(1) u, real, dimension(1) diag, ifld)
Definition at line 4059 of file navier5.f.
References build_filter(), filterq(), ly1, and lz1.
gaujordf()
subroutine gaujordf (real, dimension(m,n) a, m, n, integer, dimension(m) indr, integer, dimension(n) indc, integer, dimension(n) ipiv, ierr, real, dimension(m) rmult)
Definition at line 944 of file navier5.f.
References exitt(), and izero().
get_el()
subroutine get_el (real, dimension(2**ldim,ldim) xt, real, dimension(lx1,ly1,lz1) x, real, dimension(lx1,ly1,lz1) y, real, dimension(lx1,ly1,lz1) z)
Definition at line 3073 of file navier5.f.
References ly1, and lz1.
get_exyz()
subroutine get_exyz (integer ex, integer ey, integer ez, integer eg, nelx, nely, nelz)
Definition at line 1525 of file navier5.f.
References mod1().
get_strsmax()
subroutine get_strsmax (strsmax, real, dimension (lx1,ly1,lz1,lelt) xm0, real, dimension (lx1,ly1,lz1,lelt) ym0, real, dimension (lx1,ly1,lz1,lelt) zm0, real, dimension (lx1,ly1,lz1,3*ldim-3,lelv) sij, real, dimension (lx1,ly1,lz1,lelv) pm1, real, dimension(lx1,ly1,lz1,lelv) visc, integer f, integer e)
Definition at line 3207 of file navier5.f.
References dsset(), ly1, and lz1.
gh_face_extend()
subroutine gh_face_extend (real, dimension(1) x, real, dimension(1) zg, n, integer gh_type, real, dimension(1) e, real, dimension(1) v)
Definition at line 3402 of file navier5.f.
References gh_face_extend_2d(), and gh_face_extend_3d().
gh_face_extend_2d()
subroutine gh_face_extend_2d (real, dimension(n,n) x, real, dimension(n) zg, n, integer gh_type, real, dimension(n,n) e, real, dimension(n,n) v)
Definition at line 3417 of file navier5.f.
References add3(), copy(), and rzero().
gh_face_extend_3d()
subroutine gh_face_extend_3d (real, dimension(n,n,n) x, real, dimension(n) zg, n, integer gh_type, real, dimension(n,n,n) e, real, dimension(n,n,n) v)
Definition at line 3482 of file navier5.f.
References add2(), copy(), and rzero().
gradm1()
subroutine gradm1 (real, dimension(lxyz,1) ux, real, dimension(lxyz,1) uy, real, dimension(lxyz,1) uz, real, dimension(lxyz,1) u)
Definition at line 739 of file navier5.f.
References local_grad2(), local_grad3(), ly1, lz1, and setaxdy().
legendre_poly()
subroutine legendre_poly (real, dimension(0:n) L, x, N)
Definition at line 1061 of file navier5.f.
local_err_est()
subroutine local_err_est (real, dimension(5,2) err, real, dimension(1) u, nx, real, dimension(1) Lj, real, dimension(1) Ljt, real, dimension(nx,nx,nx) uh, real, dimension(1) w, logical if3d)
Definition at line 1390 of file navier5.f.
References rzero(), tensr3(), and vlsc2().
local_grad2()
subroutine local_grad2 (real, dimension(0:n,0:n) ur, real, dimension(0:n,0:n) us, real, dimension (0:n,0:n,1) u, N, integer e, real, dimension (0:n,0:n) D, real, dimension(0:n,0:n) Dt)
Definition at line 724 of file navier5.f.
References mxm().
local_grad3()
subroutine local_grad3 (real, dimension(0:n,0:n,0:n) ur, real, dimension(0:n,0:n,0:n) us, real, dimension(0:n,0:n,0:n) ut, real, dimension (0:n,0:n,0:n,1) u, N, integer e, real, dimension (0:n,0:n) D, real, dimension(0:n,0:n) Dt)
Definition at line 705 of file navier5.f.
References mxm().
mappr()
subroutine mappr (real, dimension(lx1,ly1,lz1,lelv) pm1, real, dimension(lx2,ly2,lz2,lelv) pm2, real, dimension (lx1,ly2,lz2) pa, real, dimension (lx1,ly1,lz2) pb)
Definition at line 513 of file navier5.f.
References col2(), copy(), dssum(), ly1, lz1, and mxm().
no_y_profile()
subroutine no_y_profile (real, dimension(1) u)
Definition at line 3901 of file navier5.f.
References lelt, ly1, lz1, sub2(), y_profile(), and y_profile_transpose().
no_z_profile()
subroutine no_z_profile (real, dimension(1) u)
Definition at line 3805 of file navier5.f.
References lelt, ly1, lz1, sub2(), z_profile(), and z_profile_transpose().
out_csrmats()
subroutine out_csrmats (real, dimension(1) acsr, integer, dimension(1) ia, integer, dimension(1) ja, n, character*9 name9)
Definition at line 674 of file navier5.f.
References blank().
out_el()
subroutine out_el (real, dimension(2**ldim,ldim) xt, integer e)
Definition at line 3052 of file navier5.f.
outfld2d()
subroutine outfld2d (real, dimension(nx*ny*nlx*nly) u, real, dimension(nx*ny*nlx*nly) v, real, dimension(nx*ny*nlx*nly) w, nx, ny, nlx, nly, character*3 name, ifld)
Definition at line 1695 of file navier5.f.
References blank(), dump_header2d(), and err_chk().
outfld2d_p()
subroutine outfld2d_p (real, dimension(nx*ny*nlx*nly) u, real, dimension(nx*ny*nlx*nly) v, real, dimension(nx*ny*nlx*nly) w, nx, ny, nlx, nly, character*4 name, ifld, jid, npido, ir)
Definition at line 1614 of file navier5.f.
References blank(), and dump_header2d().
outmatx()
subroutine outmatx (real, dimension(m*n) a, m, n, io, character*4 name)
Definition at line 236 of file navier5.f.
outmesh()
subroutine outmesh ()
Definition at line 3016 of file navier5.f.
References crecv2(), csend(), exitt(), get_el(), nekgsync(), and out_el().
planar_average_z()
subroutine planar_average_z (real, dimension(lz1,nelz) ua, real, dimension(lx1*ly1,lz1,nelv) u, real, dimension(lz1,nelz) w1, real, dimension(lz1,nelz) w2)
Definition at line 1763 of file navier5.f.
References gop(), ly1, lz1, and rzero().
q_filter()
subroutine q_filter (wght)
Definition at line 3 of file navier5.f.
References add2sxy(), build_new_filter(), exitti(), filterq(), glmax(), ident(), igllm(), iglm(), iglmax(), ly1, lz1, mxm(), zwgl(), and zwgll().
ran1()
real function ran1 (integer idum)
Definition at line 3630 of file navier5.f.
rand_fld_h1()
subroutine rand_fld_h1 (real, dimension(1) x)
Definition at line 3667 of file navier5.f.
References dsavg(), ly1, lz1, and ran1().
rescale_x()
subroutine rescale_x (real, dimension(1) x, x0, x1)
Definition at line 3682 of file navier5.f.
References glmax(), glmin(), ly1, lz1, and scale().
shear_calc_max()
subroutine shear_calc_max (real, dimension(maxobj) strsmx, scale, real, dimension(3) x0, logical ifdout, logical iftout)
Definition at line 3095 of file navier5.f.
References add2s2(), cadd2(), cfill(), cmult(), comp_sij(), get_strsmax(), glmax(), glmin(), gop(), lelt, ly1, lz1, mappr(), rzero(), and scale().
surface_flux()
subroutine surface_flux (dq, real, dimension(l,1) qx, real, dimension(l,1) qy, real, dimension(l,1) qz, integer e, integer f, real, dimension(lx1,ly1,lz1) w)
Definition at line 908 of file navier5.f.
References dsset(), faccl3(), faddcl3(), ly1, and lz1.
surface_int()
subroutine surface_int (sint, sarea, real, dimension(lx1,ly1,lz1,1) a, integer e, integer f)
Definition at line 874 of file navier5.f.
References dsset(), ly1, and lz1.
torque_calc()
subroutine torque_calc (scale, real, dimension(3) x0, logical ifdout, logical iftout)
Definition at line 1941 of file navier5.f.
References add2s2(), cadd2(), cfill(), cmult(), comp_sij(), drgtrq(), glmax(), glmin(), gop(), iglmax(), lelt, ly1, lz1, mappr(), and scale().
turb_outflow()
subroutine turb_outflow (real, dimension(lx2,ly2,lz2,lelt) d, real, dimension(lx1*ly1*lz1,lelt) m1, rq, uin)
Definition at line 4493 of file navier5.f.
References cheap_dist(), copy(), glamax(), glsc2(), glsc3(), iglsum(), ly1, lz1, maph1_to_l2(), rone(), rzero(), and vlmax().
x_average()
subroutine x_average (real, dimension(ly1,lz1,nely,nelz) ua, real, dimension (lx1,ly1,lz1,nelv) u, real, dimension(ly1,lz1,nely,nelz) w1, real, dimension(ly1,lz1,nely,nelz) w2)
Definition at line 2403 of file navier5.f.
References exitti(), get_exyz(), gop(), ly1, lz1, and rzero().
x_average_transpose()
subroutine x_average_transpose (real, dimension(lx1,ly1,lz1,nelv) u, real, dimension(ly1,lz1,nely,nelz) ua)
Definition at line 2452 of file navier5.f.
References get_exyz(), ly1, and lz1.
x_distribute()
subroutine x_distribute (real, dimension(1) u)
Definition at line 2482 of file navier5.f.
References ly1, lz1, x_average(), and x_average_transpose().
x_distribute2()
subroutine x_distribute2 (real, dimension(1) ua, real, dimension(1) u)
Definition at line 2507 of file navier5.f.
References ly1, lz1, x_average(), and x_average_transpose().
y2d()
subroutine y2d (real, dimension(1) u, real, dimension(1) v, real, dimension(1) w, real, dimension(1) p, character*1 c1, icount)
Definition at line 2858 of file navier5.f.
References ly1, lz1, y_avg_buff(), and y_ins_buff().
y_average()
subroutine y_average (real, dimension(lx1,lz1,nelx,nelz) ua, real, dimension (lx1,ly1,lz1,nelv) u, real, dimension(lx1,lz1,nelx,nelz) w1, real, dimension(lx1,lz1,nelx,nelz) w2)
Definition at line 2652 of file navier5.f.
References get_exyz(), gop(), ly1, lz1, and rzero().
y_avg_buff()
subroutine y_avg_buff (real, dimension(1) ux, real, dimension(1) uy, real, dimension(1) uz, character*2 c2, character*2 name, icount)
Definition at line 2698 of file navier5.f.
References buff_2d_out(), lz1, and y_average().
y_ins_buff()
subroutine y_ins_buff (real, dimension(1) ux, real, dimension(1) uy, real, dimension(1) uz, character*2 c2, character*2 name, icount)
Definition at line 2752 of file navier5.f.
References buff_2d_out(), lz1, and y_slice().
y_profile()
subroutine y_profile (real, dimension(lz1,lelz) ua, real, dimension (lx1,ly1,lz1,nelv) u, real, dimension(lz1,lelz) w1, real, dimension(lz1,lelz) w2)
Definition at line 3930 of file navier5.f.
References get_exyz(), gop(), ly1, lz1, and rzero().
y_profile_transpose()
subroutine y_profile_transpose (real, dimension(lx1,ly1,lz1,nelv) u, real, dimension(lz1,lelz) ua)
Definition at line 3974 of file navier5.f.
References get_exyz(), ly1, and lz1.
y_slice()
subroutine y_slice (real, dimension(lx1,lz1,nelx,nelz) ua, real, dimension (lx1,ly1,lz1,nelv) u, real, dimension(lx1,lz1,nelx,nelz) w1, real, dimension(lx1,lz1,nelx,nelz) w2)
Definition at line 2531 of file navier5.f.
References get_exyz(), gop(), lz1, and rzero().
z2d()
subroutine z2d (real, dimension(1) u, real, dimension(1) v, real, dimension(1) w, real, dimension(1) p, character*1 c1, icount)
Definition at line 2907 of file navier5.f.
References ly1, lz1, z_avg_buff(), and z_ins_buff().
z_average()
subroutine z_average (real, dimension(lx1,ly1,nelx,nely) ua, real, dimension (lx1,ly1,lz1,nelv) u, real, dimension(lx1,ly1,nelx,nely) w1, real, dimension(lx1,ly1,nelx,nely) w2)
Definition at line 3726 of file navier5.f.
References exitti(), get_exyz(), gop(), ly1, lz1, and rzero().
z_average_transpose()
subroutine z_average_transpose (real, dimension(lx1,ly1,lz1,nelv) u, real, dimension(lx1,ly1,nelx,nely) ua)
Definition at line 3775 of file navier5.f.
References get_exyz(), ly1, and lz1.
z_avg_buff()
subroutine z_avg_buff (real, dimension(1) ux, real, dimension(1) uy, real, dimension(1) uz, character*2 c2, character*2 name, icount)
Definition at line 2725 of file navier5.f.
References buff_2d_out(), ly1, and z_average().
z_distribute()
subroutine z_distribute (u)
Definition at line 3700 of file navier5.f.
References ly1, z_average(), and z_average_transpose().
z_ins_buff()
subroutine z_ins_buff (real, dimension(1) ux, real, dimension(1) uy, real, dimension(1) uz, character*2 c2, character*2 name, icount)
Definition at line 2779 of file navier5.f.
References buff_2d_out(), ly1, and z_slice().
z_profile()
subroutine z_profile (real, dimension(lz1,lelz) ua, real, dimension (lx1,ly1,lz1,nelv) u, real, dimension(lz1,lelz) w1, real, dimension(lz1,lelz) w2)
Definition at line 3834 of file navier5.f.
References get_exyz(), gop(), ly1, lz1, and rzero().
z_profile_transpose()
subroutine z_profile_transpose (real, dimension(lx1,ly1,lz1,nelv) u, real, dimension(lz1,lelz) ua)
Definition at line 3876 of file navier5.f.
References get_exyz(), ly1, and lz1.
z_slice()
subroutine z_slice (real, dimension(lx1,ly1,nelx,nely) ua, real, dimension (lx1,ly1,lz1,nelv) u, real, dimension(lx1,ly1,nelx,nely) w1, real, dimension(lx1,ly1,nelx,nely) w2)
Definition at line 2614 of file navier5.f.
References get_exyz(), gop(), ly1, and rzero().
z_slice_g()
subroutine z_slice_g (real, dimension(nx,ny,nlxy) uz, real, dimension (nx,ny,nz,nelv) u, real, dimension(nx,ny,nlxy) w1, kz, integer ezi, nx, ny, nz, nlxy)
Definition at line 2569 of file navier5.f.
References copy(), get_exyz(), gop(), and rzero().