KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/navier1.f File Reference
navier1.f File Reference
Functions/Subroutines
subroutine plan1 (igeom)
subroutine crespuz (respr, g1, g2, g3, h1, h2, h2inv, intype)
subroutine cresvuz (resv1, resv2, resv3)
subroutine makeg (out1, out2, out3, h1, h2, intype)
subroutine ctolspl (tolspl, respr)
subroutine ortho (respr)
subroutine cdabdtp (ap, wp, h1, h2, h2inv, intype)
subroutine opgrad (out1, out2, out3, inp)
subroutine cdtp (dtx, x, rm2, sm2, tm2, isd)
subroutine multd (dx, x, rm2, sm2, tm2, isd, iflg)
subroutine ophinv (out1, out2, out3, inp1, inp2, inp3, h1, h2, tolh, nmxi)
subroutine ophx (out1, out2, out3, inp1, inp2, inp3, h1, h2)
subroutine opbinv (out1, out2, out3, inp1, inp2, inp3, h2inv)
subroutine opbinv1 (out1, out2, out3, inp1, inp2, inp3, SCALE)
subroutine uzprec (rpcg, rcg, h1m1, h2m1, intype, wp)
subroutine eprec (z2, r2)
subroutine convprn (iconv, rbnorm, rrpt, res, z, tol)
subroutine convpr (res, tol, iconv, rbnorm)
subroutine chktcg2 (tol, res, iconv)
subroutine dudxyz (du, u, rm1, sm1, tm1, jm1, imsh, isd)
subroutine convopo (conv, fi)
subroutine conv2 (dtfi, fi)
subroutine cmask (cmask1, cmask2)
subroutine makef
subroutine makeuf
subroutine nekuf (f1, f2, f3)
subroutine advab
subroutine makebdf
subroutine makeabf
subroutine setab3 (ab0, ab1, ab2)
subroutine setabbd (ab, dtlag, nab, nbd)
subroutine setbd (bd, dtbd, nbd)
subroutine bdsys (a, b, dt, nbd, ldim)
subroutine tauinit (tau, ilag)
subroutine velinit (vel1, vel2, vel3, ilag)
subroutine velconv (vxn, vyn, vzn, tau)
subroutine frkconv (y, x, mask)
subroutine velchar (vel, vn, vlag, nbd, tau, dtbd)
subroutine lagvel
subroutine hypmsk3 (hv1msk, hv2msk, hv3msk)
subroutine setordbd
subroutine normsc (h1, semi, l2, linf, x, imesh)
subroutine normvc (h1, semi, l2, linf, x1, x2, x3)
subroutine genwp (wp, wm2, p)
subroutine convuz (ifstuz)
subroutine convsp (ifstsp)
subroutine antimsk (y, x, xmask, n)
subroutine opamask (vbdry1, vbdry2, vbdry3)
subroutine opmask (res1, res2, res3)
subroutine opadd2 (a1, a2, a3, b1, b2, b3)
subroutine opsub2 (a1, a2, a3, b1, b2, b3)
subroutine opsub3 (a1, a2, a3, b1, b2, b3, c1, c2, c3)
subroutine opcolv3 (a1, a2, a3, b1, b2, b3, c)
subroutine opcolv (a1, a2, a3, c)
subroutine opcol2 (a1, a2, a3, b1, b2, b3)
subroutine opchsgn (a, b, c)
subroutine opcopy (a1, a2, a3, b1, b2, b3)
subroutine rotate_cyc (r1, r2, r3, idir)
subroutine opdssum (a, b, c)
subroutine opdsop (a, b, c, op)
subroutine opicol2 (a1, a2, a3, b1, b2, b3)
subroutine oprzero (a, b, c)
subroutine oprone (a, b, c)
subroutine opcmult (a, b, c, const)
subroutine opcolv2c (a1, a2, a3, b1, b2, c)
subroutine opcolv2 (a1, a2, a3, b1, b2)
subroutine opadd2col (a1, a2, a3, b1, b2, b3, c)
subroutine opcolv3c (a1, a2, a3, b1, b2, b3, c, d)
subroutine uzawa (rcg, h1, h2, h2inv, intype, iter)
subroutine mapw (md, nd, m1, n1, mflg)
subroutine mapwp (md, nd, m1, n1, mflg)
subroutine specmp (b, nb, a, na, ba, ab, w)
subroutine setmap (n1, nd)
subroutine set_pnd (P, LkD, LkNt, N, D)
subroutine convop (conv, fi)
subroutine conv1d (dfi, fi)
subroutine conv1 (du, u)
subroutine conv1no (du, u)
subroutine conv1rk (du, dv, dw, u, v, w)
subroutine velconvv (vxn, vyn, vzn, tau)
subroutine frkconvv (du, dv, dw, u, v, w, mu)
subroutine conv1rk2 (du, dv, dw, u, v, w, cu, cv, cw, beta, wk)
subroutine frkconvv2 (du, dv, dw, u, v, w, cu, cv, cw, beta, mu, wk)
subroutine hypmsk3v (msk, mask)
subroutine ophyprk (vel1, vel2, vel3, ilag)
subroutine opdiv (outfld, inpx, inpy, inpz)
subroutine opgradt (outx, outy, outz, inpfld)
subroutine setproj (n1, nd)
subroutine set_pndoi (Pt, P, LkNt, N, D)
subroutine wgradm1 (ux, uy, uz, u, nel)
subroutine makevis
subroutine comp_siej (U1, U2, U3)
subroutine wlaplacian (out, a, diff, ifld)
subroutine explstrs
subroutine expl_strs (w1, w2, w3, u1, u2, u3)
subroutine expl_strs_e (w1, w2, w3, u1, u2, u3, e)
subroutine expl_strs_e_3d (w1, w2, w3, u1, u2, u3, e)
subroutine expl_strs_e_2d (w1, w2, u1, u2, e)
subroutine gradl_rst_t (u, ur, us, ut, md, if3d)
subroutine gradl_rst (ur, us, ut, u, md, if3d)
subroutine local_grad3_t (u, ur, us, ut, N, e, D, Dt, w)
subroutine local_grad2_t (u, ur, us, N, e, D, Dt, w)
subroutine get_dgll_ptr (ip, mx, md)
subroutine gen_dgll (dgl, dgt, mp, np, w)
Function/Subroutine Documentation
advab()
subroutine advab ()
Definition at line 1584 of file navier1.f.
References convop(), ly1, lz1, rzero(), and subcol3().
antimsk()
subroutine antimsk (real, dimension(1) y, real, dimension(1) x, real, dimension(1) xmask, n)
Definition at line 2315 of file navier1.f.
bdsys()
subroutine bdsys (real, dimension(ldim,9) a, real, dimension(9) b, real, dimension(9) dt, nbd, ldim)
Definition at line 1844 of file navier1.f.
References rzero().
cdabdtp()
subroutine cdabdtp (real, dimension (lx2,ly2,lz2,1) ap, real, dimension (lx2,ly2,lz2,1) wp, real, dimension (lx1,ly1,lz1,1) h1, real, dimension (lx1,ly1,lz1,1) h2, real, dimension (lx1,ly1,lz1,1) h2inv, intype)
Definition at line 264 of file navier1.f.
References ly1, lz1, opbinv(), opbinv1(), opdiv(), opgradt(), and ophinv().
cdtp()
subroutine cdtp (real, dimension (lx1*ly1*lz1,lelv) dtx, real, dimension (lx2*ly2*lz2,lelv) x, real, dimension (lx2*ly2*lz2,lelv) rm2, real, dimension (lx2*ly2*lz2,lelv) sm2, real, dimension (lx2*ly2*lz2,lelv) tm2, isd)
Definition at line 336 of file navier1.f.
References add2(), col2(), col3(), copy(), dnekclock(), invcol2(), lelt, ly1, lz1, mxm(), and rzero().
chktcg2()
subroutine chktcg2 (tol, real, dimension (lx2,ly2,lz2,lelv) res, iconv)
Definition at line 1160 of file navier1.f.
References col2(), col3(), and glsum().
cmask()
subroutine cmask (real, dimension (lx1,ly1,lz1,lelv) cmask1, real, dimension (lx1,ly1,lz1,lelv) cmask2)
Definition at line 1461 of file navier1.f.
References cfill(), facev(), ly1, and lz1.
comp_siej()
subroutine comp_siej (dimension(lx1,ly1,lz1,1) U1, dimension(lx1,ly1,lz1,1) U2, dimension(lx1,ly1,lz1,1) U3)
Definition at line 4376 of file navier1.f.
References axiezz(), cmult(), col2(), lelt, ly1, lz1, rzero3(), and uxyz().
conv1()
subroutine conv1 (real, dimension (lx1*ly1*lz1,1) du, real, dimension (lx1,ly1,lz1,1) u)
Definition at line 3336 of file navier1.f.
References lelt, ly1, lz1, and mxm().
conv1d()
subroutine conv1d (real, dimension (lx1,ly1,lz1,1) dfi, real, dimension (lx1,ly1,lz1,1) fi)
Definition at line 3281 of file navier1.f.
References addcol3(), col3(), dudxyz(), ly1, lz1, mapw(), and mapwp().
conv1no()
subroutine conv1no (real, dimension (lx1*ly1*lz1,1) du, real, dimension (lx1,ly1,lz1,1) u)
Definition at line 3413 of file navier1.f.
References lelt, ly1, lz1, and mxm().
conv1rk()
subroutine conv1rk (real, dimension(lx1*ly1*lz1,1) du, real, dimension(lx1*ly1*lz1,1) dv, real, dimension(lx1*ly1*lz1,1) dw, real, dimension (lx1,ly1,lz1,1) u, real, dimension (lx1,ly1,lz1,1) v, real, dimension (lx1,ly1,lz1,1) w)
Definition at line 3491 of file navier1.f.
References lelt, ly1, lz1, and mxm().
conv1rk2()
subroutine conv1rk2 (real, dimension(lx1*ly1*lz1,1) du, real, dimension(lx1*ly1*lz1,1) dv, real, dimension(lx1*ly1*lz1,1) dw, real, dimension (lx1,ly1,lz1,1) u, real, dimension (lx1,ly1,lz1,1) v, real, dimension (lx1,ly1,lz1,1) w, real, dimension(lx1,ly1,lz1,1) cu, real, dimension(lx1,ly1,lz1,1) cv, real, dimension(lx1,ly1,lz1,1) cw, beta, real, dimension(lx1,ly1,lz1,3) wk)
Definition at line 3727 of file navier1.f.
References ly1, lz1, and mxm().
conv2()
subroutine conv2 (real, dimension (lx1,ly1,lz1,1) dtfi, real, dimension (lx1,ly1,lz1,1) fi)
Definition at line 1369 of file navier1.f.
References add2(), col2(), col4(), copy(), invcol2(), ly1, lz1, mxm(), and rzero().
convop()
subroutine convop (real, dimension (lx1,ly1,lz1,1) conv, real, dimension (lx1,ly1,lz1,1) fi)
Definition at line 3198 of file navier1.f.
References conv1(), conv1d(), convect_cons(), convect_dg(), convect_new(), convopo(), dnekclock(), invcol2(), ly1, lz1, mfi(), and rzero().
convopo()
subroutine convopo (real, dimension (lx1,ly1,lz1,1) conv, real, dimension (lx1,ly1,lz1,1) fi)
Definition at line 1292 of file navier1.f.
References add2(), add2s2(), cmask(), col3(), conv1(), conv2(), ly1, lz1, mfi(), and rzero().
convpr()
subroutine convpr (real, dimension (lx2,ly2,lz2,lelv) res, tol, iconv, rbnorm)
Definition at line 1137 of file navier1.f.
References col3(), and glsc2().
convprn()
subroutine convprn (iconv, rbnorm, rrpt, real, dimension (1) res, real, dimension (1) z, tol)
Definition at line 1109 of file navier1.f.
References gop(), vlsc2(), and vlsc21().
convsp()
subroutine convsp (logical ifstsp)
Definition at line 2309 of file navier1.f.
convuz()
subroutine convuz (logical ifstuz)
Definition at line 2248 of file navier1.f.
References col3(), glsc2(), glsc3(), ly1, lz1, opadd2(), opcolv3(), opcopy(), opdiv(), opdssum(), opgradt(), ophx(), opmask(), opsub2(), and sethlm().
crespuz()
subroutine crespuz (real, dimension (lx2,ly2,lz2,lelv) respr, real, dimension (lx1,ly1,lz1,lelv) g1, real, dimension (lx1,ly1,lz1,lelv) g2, real, dimension (lx1,ly1,lz1,lelv) g3, real, dimension (lx1,ly1,lz1,lelv) h1, real, dimension (lx1,ly1,lz1,lelv) h2, real, dimension (lx1,ly1,lz1,lelv) h2inv, intype)
Definition at line 85 of file navier1.f.
References ly1, lz1, opamask(), opbinv(), opdiv(), ophinv(), opsub2(), and ortho().
cresvuz()
subroutine cresvuz (real, dimension (lx1,ly1,lz1,1) resv1, real, dimension (lx1,ly1,lz1,1) resv2, real, dimension (lx1,ly1,lz1,1) resv3)
Definition at line 118 of file navier1.f.
References ly1, lz1, opadd2(), opgradt(), ophx(), oprzero(), opsub2(), and sethlm().
ctolspl()
subroutine ctolspl (tolspl, real, dimension (lx2,ly2,lz2,lelv) respr)
Definition at line 199 of file navier1.f.
References col2(), glsum(), invcol3(), ly1, and lz1.
dudxyz()
subroutine dudxyz (real, dimension (lx1,ly1,lz1,1) du, real, dimension (lx1,ly1,lz1,1) u, real, dimension (lx1,ly1,lz1,1) rm1, real, dimension (lx1,ly1,lz1,1) sm1, real, dimension (lx1,ly1,lz1,1) tm1, real, dimension (lx1,ly1,lz1,1) jm1, imsh, isd)
Definition at line 1227 of file navier1.f.
References addcol3(), col2(), lelt, ly1, lz1, mxm(), and setaxdy().
eprec()
subroutine eprec (real, dimension (lx2,ly2,lz2,lelv) z2, real, dimension (lx2,ly2,lz2,lelv) r2)
Definition at line 1032 of file navier1.f.
References add2s2(), col3(), glsc2(), glsum(), hmholtz(), ly1, lz1, map12(), map21e(), rone(), and rzero().
expl_strs()
subroutine expl_strs (real, dimension(1) w1, real, dimension(1) w2, real, dimension(1) w3, real, dimension(1) u1, real, dimension(1) u2, real, dimension(1) u3)
Definition at line 4486 of file navier1.f.
References expl_strs_e(), ly1, and lz1.
expl_strs_e()
subroutine expl_strs_e (real, dimension(1) w1, real, dimension(1) w2, real, dimension(1) w3, real, dimension(1) u1, real, dimension(1) u2, real, dimension(1) u3, integer e)
Definition at line 4506 of file navier1.f.
References expl_strs_e_2d(), and expl_strs_e_3d().
expl_strs_e_2d()
subroutine expl_strs_e_2d (real, dimension(1) w1, real, dimension(1) w2, real, dimension(1) u1, real, dimension(1) u2, integer e)
Definition at line 4609 of file navier1.f.
References gradl_rst(), gradl_rst_t(), ly1, and lz1.
expl_strs_e_3d()
subroutine expl_strs_e_3d (real, dimension(1) w1, real, dimension(1) w2, real, dimension(1) w3, real, dimension(1) u1, real, dimension(1) u2, real, dimension(1) u3, integer e)
Definition at line 4530 of file navier1.f.
References gradl_rst(), gradl_rst_t(), ly1, and lz1.
explstrs()
subroutine explstrs ()
Definition at line 4459 of file navier1.f.
References expl_strs_e(), ly1, and lz1.
frkconv()
subroutine frkconv (real, dimension (lx1,ly1,lz1,1) y, real, dimension (lx1,ly1,lz1,1) x, real, dimension (lx1,ly1,lz1,1) mask)
Definition at line 1931 of file navier1.f.
References col2(), convop(), dssum(), ly1, and lz1.
frkconvv()
subroutine frkconvv (real, dimension(1) du, real, dimension(1) dv, real, dimension(1) dw, real, dimension (1) u, real, dimension (1) v, real, dimension (1) w, integer, dimension(0:1) mu)
Definition at line 3652 of file navier1.f.
References conv1rk(), ly1, lz1, and opdssum().
frkconvv2()
subroutine frkconvv2 (real, dimension(1) du, real, dimension(1) dv, real, dimension(1) dw, real, dimension (1) u, real, dimension (1) v, real, dimension (1) w, real, dimension(1) cu, real, dimension(1) cv, real, dimension(1) cw, beta, integer, dimension(0:1) mu, real, dimension(lx1*ly1*lz1,3) wk)
Definition at line 3849 of file navier1.f.
References conv1rk2(), ly1, lz1, and opdssum().
gen_dgll()
subroutine gen_dgll (real, dimension(mp,np) dgl, real, dimension(np*mp) dgt, mp, np, real, dimension(1) w)
Definition at line 4815 of file navier1.f.
References fd_weights_full(), lim_chk(), transpose(), and zwgll().
genwp()
subroutine genwp (real, dimension (lx2,ly2,lz2,lelv) wp, real, dimension (lx2,ly2,lz2) wm2, real, dimension (lx2,ly2,lz2,lelv) p)
Definition at line 2228 of file navier1.f.
References col3().
get_dgll_ptr()
subroutine get_dgll_ptr (ip, mx, md)
Definition at line 4771 of file navier1.f.
References gen_dgll(), and lim_chk().
gradl_rst()
subroutine gradl_rst (real, dimension(1) ur, real, dimension(1) us, real, dimension(1) ut, real, dimension(1) u, md, logical if3d)
Definition at line 4702 of file navier1.f.
References get_dgll_ptr(), local_grad2(), and local_grad3().
gradl_rst_t()
subroutine gradl_rst_t (real, dimension(1) u, real, dimension(1) ur, real, dimension(1) us, real, dimension(1) ut, md, logical if3d)
Definition at line 4673 of file navier1.f.
References get_dgll_ptr(), local_grad2_t(), and local_grad3_t().
hypmsk3()
subroutine hypmsk3 (real, dimension (lx1,ly1,lz1,1) hv1msk, real, dimension (lx1,ly1,lz1,1) hv2msk, real, dimension (lx1,ly1,lz1,1) hv3msk)
Definition at line 2024 of file navier1.f.
References copy(), faccl3(), facev(), faddcl3(), fcaver(), lelt, ly1, lz1, rone(), and rzero().
hypmsk3v()
subroutine hypmsk3v (integer, dimension(0:1) msk, real, dimension(lxyz1,lelt) mask)
Definition at line 3927 of file navier1.f.
References faccl3(), facev(), faddcl3(), fcaver(), lelt, ly1, lz1, rone(), and rzero().
lagvel()
subroutine lagvel ()
Definition at line 1998 of file navier1.f.
References copy(), ly1, lz1, and opcopy().
local_grad2_t()
subroutine local_grad2_t (real, dimension (0:n,0:n,1) u, real, dimension(0:n,0:n) ur, real, dimension(0:n,0:n) us, N, integer e, real, dimension (0:n,0:n) D, real, dimension(0:n,0:n) Dt, real, dimension (0:n,0:n) w)
Definition at line 4753 of file navier1.f.
References add2(), and mxm().
local_grad3_t()
subroutine local_grad3_t (real, dimension (0:n,0:n,0:n,1) u, real, dimension(0:n,0:n,0:n) ur, real, dimension(0:n,0:n,0:n) us, real, dimension(0:n,0:n,0:n) ut, N, integer e, real, dimension (0:n,0:n) D, real, dimension(0:n,0:n) Dt, real, dimension (0:n,0:n,0:n) w)
Definition at line 4728 of file navier1.f.
References add2(), and mxm().
makeabf()
subroutine makeabf ()
Definition at line 1665 of file navier1.f.
References add2s1(), add3s2(), col2(), copy(), ly1, and lz1.
makebdf()
subroutine makebdf ()
Definition at line 1616 of file navier1.f.
References cfill(), cmult2(), ly1, lz1, opadd2(), opadd2col(), and opcolv3c().
makef()
subroutine makef ()
Definition at line 1496 of file navier1.f.
References admeshv(), advab(), advchar(), make_hpf(), makeabf(), makebdf(), makeuf(), and makevis().
makeg()
subroutine makeg (real, dimension (lx1,ly1,lz1,lelv) out1, real, dimension (lx1,ly1,lz1,lelv) out2, real, dimension (lx1,ly1,lz1,lelv) out3, real, dimension (lx1,ly1,lz1,lelv) h1, real, dimension (lx1,ly1,lz1,lelv) h2, intype)
Definition at line 145 of file navier1.f.
References ly1, lz1, opadd2(), opamask(), opchsgn(), opgradt(), ophx(), opsub2(), and rzero().
makeuf()
subroutine makeuf ()
Definition at line 1531 of file navier1.f.
References nekuf(), and opcolv().
makevis()
subroutine makevis ()
Definition at line 4285 of file navier1.f.
References add2(), cmult(), col2(), comp_siej(), copy(), lelt, ly1, lz1, opcolv(), opdiv(), opdssum(), and rone().
mapw()
subroutine mapw (real, dimension(lxd,lyd,lzd,lelv) md, nd, real, dimension(lx1,ly1,lz1,lelv) m1, n1, mflg)
Definition at line 3021 of file navier1.f.
References setmap(), and specmp().
mapwp()
subroutine mapwp (real, dimension(lxd,lyd,lzd,lelv) md, nd, real, dimension(lx1,ly1,lz1,lelv) m1, n1, mflg)
Definition at line 3053 of file navier1.f.
References setproj(), and specmp().
multd()
subroutine multd (real, dimension (lx2*ly2*lz2,lelv) dx, real, dimension (lx1*ly1*lz1,lelv) x, real, dimension (lx2*ly2*lz2,lelv) rm2, real, dimension (lx2*ly2*lz2,lelv) sm2, real, dimension (lx2*ly2*lz2,lelv) tm2, isd, iflg)
Definition at line 544 of file navier1.f.
References add2(), addcol3(), col2(), col3(), copy(), dnekclock(), invcol2(), lelt, ly1, lz1, mxm(), and rzero().
nekuf()
subroutine nekuf (real, dimension (lx1,ly1,lz1,lelv) f1, real, dimension (lx1,ly1,lz1,lelv) f2, real, dimension (lx1,ly1,lz1,lelv) f3)
Definition at line 1550 of file navier1.f.
References dnekclock(), dnekclock_sync(), ly1, lz1, nekasgn(), and oprzero().
normsc()
subroutine normsc (real h1, real semi, real l2, real linf, real, dimension (lx1,ly1,lz1,1) x, imesh)
Definition at line 2094 of file navier1.f.
References axhelm(), col2(), col3(), glamax(), glsum(), lelt, ly1, lz1, rone(), and rzero().
normvc()
subroutine normvc (real h1, real semi, real l2, real linf, real, dimension (lx1,ly1,lz1,1) x1, real, dimension (lx1,ly1,lz1,1) x2, real, dimension (lx1,ly1,lz1,1) x3)
Definition at line 2151 of file navier1.f.
References add2(), col2(), col3(), glamax(), glsum(), lelt, ly1, lz1, ophx(), rone(), and rzero().
opadd2()
subroutine opadd2 (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3)
Definition at line 2418 of file navier1.f.
References add2(), ly1, and lz1.
opadd2col()
subroutine opadd2col (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) c)
Definition at line 2810 of file navier1.f.
References ly1, and lz1.
opamask()
subroutine opamask (real, dimension (lx1,ly1,lz1,1) vbdry1, real, dimension (lx1,ly1,lz1,1) vbdry2, real, dimension (lx1,ly1,lz1,1) vbdry3)
Definition at line 2343 of file navier1.f.
References amask(), antimsk(), ly1, and lz1.
opbinv()
subroutine opbinv (real, dimension (1) out1, real, dimension (1) out2, real, dimension (1) out3, real, dimension (1) inp1, real, dimension (1) inp2, real, dimension (1) inp3, real, dimension (1) h2inv)
Definition at line 840 of file navier1.f.
References dssum(), invcol3(), ly1, lz1, opdssum(), and opmask().
opbinv1()
subroutine opbinv1 (real, dimension (1) out1, real, dimension (1) out2, real, dimension (1) out3, real, dimension (1) inp1, real, dimension (1) inp2, real, dimension (1) inp3, SCALE)
Definition at line 903 of file navier1.f.
References ly1, lz1, opdssum(), opmask(), and scale().
opchsgn()
subroutine opchsgn (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c)
Definition at line 2532 of file navier1.f.
References chsign(), ly1, and lz1.
opcmult()
subroutine opcmult (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, const)
Definition at line 2722 of file navier1.f.
References cmult(), ly1, and lz1.
opcol2()
subroutine opcol2 (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3)
Definition at line 2522 of file navier1.f.
References col2(), ly1, and lz1.
opcolv()
subroutine opcolv (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) c)
Definition at line 2486 of file navier1.f.
References ly1, and lz1.
opcolv2()
subroutine opcolv2 (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) b1, real, dimension(1) b2)
Definition at line 2771 of file navier1.f.
References ly1, and lz1.
opcolv2c()
subroutine opcolv2c (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) b1, real, dimension(1) b2, c)
Definition at line 2732 of file navier1.f.
References ly1, and lz1.
opcolv3()
subroutine opcolv3 (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension (1) c)
Definition at line 2448 of file navier1.f.
References ly1, and lz1.
opcolv3c()
subroutine opcolv3c (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension (1) c, d)
Definition at line 2847 of file navier1.f.
References ly1, and lz1.
opcopy()
subroutine opcopy (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3)
Definition at line 2542 of file navier1.f.
References copy(), ly1, and lz1.
opdiv()
subroutine opdiv (real, dimension (lx2,ly2,lz2,1) outfld, real, dimension (lx1,ly1,lz1,1) inpx, real, dimension (lx1,ly1,lz1,1) inpy, real, dimension (lx1,ly1,lz1,1) inpz)
Definition at line 4124 of file navier1.f.
References add2(), copy(), and multd().
opdsop()
subroutine opdsop (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c, character*3 op)
Definition at line 2662 of file navier1.f.
References ly1, lz1, rotate_cyc(), and vec_dsop().
opdssum()
subroutine opdssum (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c)
Definition at line 2641 of file navier1.f.
References ly1, lz1, rotate_cyc(), and vec_dssum().
opgrad()
subroutine opgrad (real, dimension (lx2,ly2,lz2,1) out1, real, dimension (lx2,ly2,lz2,1) out2, real, dimension (lx2,ly2,lz2,1) out3, real, dimension (lx1,ly1,lz1,1) inp)
Definition at line 303 of file navier1.f.
References multd(), and wgradm1().
opgradt()
subroutine opgradt (real, dimension (lx1,ly1,lz1,1) outx, real, dimension (lx1,ly1,lz1,1) outy, real, dimension (lx1,ly1,lz1,1) outz, real, dimension (lx2,ly2,lz2,1) inpfld)
Definition at line 4155 of file navier1.f.
References cdtp().
ophinv()
subroutine ophinv (real, dimension(1) out1, real, dimension(1) out2, real, dimension(1) out3, real, dimension(1) inp1, real, dimension(1) inp2, real, dimension(1) inp3, real, dimension(1) h1, real, dimension(1) h2, tolh, nmxi)
Definition at line 748 of file navier1.f.
References hmholtz(), and hmhzsf().
ophx()
subroutine ophx (real, dimension (lx1,ly1,lz1,1) out1, real, dimension (lx1,ly1,lz1,1) out2, real, dimension (lx1,ly1,lz1,1) out3, real, dimension (lx1,ly1,lz1,1) inp1, real, dimension (lx1,ly1,lz1,1) inp2, real, dimension (lx1,ly1,lz1,1) inp3, real, dimension (lx1,ly1,lz1,1) h1, real, dimension (lx1,ly1,lz1,1) h2)
Definition at line 807 of file navier1.f.
References axhelm(), and axhmsf().
ophyprk()
subroutine ophyprk (real, dimension (lx1,ly1,lz1,1) vel1, real, dimension (lx1,ly1,lz1,1) vel2, real, dimension (lx1,ly1,lz1,1) vel3, ilag)
Definition at line 3980 of file navier1.f.
References add2s2(), copy(), frkconv(), hypmsk3(), ly1, lz1, opcopy(), tauinit(), velconv(), and velinit().
opicol2()
subroutine opicol2 (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3)
Definition at line 2692 of file navier1.f.
References invcol2(), ly1, and lz1.
opmask()
subroutine opmask (real, dimension(1) res1, real, dimension(1) res2, real, dimension(1) res3)
Definition at line 2382 of file navier1.f.
References col2(), ly1, lz1, and rmask().
oprone()
subroutine oprone (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c)
Definition at line 2712 of file navier1.f.
References ly1, lz1, and rone().
oprzero()
subroutine oprzero (real, dimension(1) a, real, dimension(1) b, real, dimension(1) c)
Definition at line 2702 of file navier1.f.
References ly1, lz1, and rzero().
opsub2()
subroutine opsub2 (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3)
Definition at line 2428 of file navier1.f.
References ly1, lz1, and sub2().
opsub3()
subroutine opsub3 (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) c1, real, dimension(1) c2, real, dimension(1) c3)
Definition at line 2438 of file navier1.f.
References ly1, lz1, and sub3().
ortho()
subroutine ortho (real, dimension (lx2,ly2,lz2,lelv) respr)
Definition at line 229 of file navier1.f.
References cadd(), exitti(), and glsum().
plan1()
subroutine plan1 (igeom)
Definition at line 2 of file navier1.f.
References add2(), bcdirvc(), bcneutr(), convuz(), copy(), crespuz(), cresvuz(), gfdm_pres_solv(), invers2(), lagvel(), ly1, lz1, makef(), makeg(), opadd2(), ophinv(), sethlm(), and uzawa().
rotate_cyc()
subroutine rotate_cyc (real, dimension(lx1,ly1,lz1,1) r1, real, dimension(lx1,ly1,lz1,1) r2, real, dimension(lx1,ly1,lz1,1) r3, idir)
Definition at line 2553 of file navier1.f.
References facind2(), ly1, and lz1.
set_pnd()
subroutine set_pnd (real, dimension(n,d) P, real, dimension(0:n-1,d) LkD, real, dimension(n,0:n-1) LkNt, integer N, integer D)
Definition at line 3131 of file navier1.f.
References mxm(), pnleg(), and zwgll().
set_pndoi()
subroutine set_pndoi (real, dimension(n,d) Pt, real, dimension(d,n) P, real, dimension(n,0:n-1) LkNt, integer N, integer D)
Definition at line 4201 of file navier1.f.
References igllm(), and zwgll().
setab3()
subroutine setab3 (ab0, ab1, ab2)
Definition at line 1707 of file navier1.f.
setabbd()
subroutine setabbd (real, dimension(nab) ab, real, dimension(nab) dtlag, nab, nbd)
Definition at line 1730 of file navier1.f.
setbd()
subroutine setbd (real, dimension(1) bd, real, dimension(1) dtbd, nbd)
Definition at line 1803 of file navier1.f.
References bdsys(), lu(), rzero(), and solve().
setmap()
subroutine setmap (n1, nd)
Definition at line 3110 of file navier1.f.
References exitt(), igllm(), and zwgll().
setordbd()
subroutine setordbd ()
Definition at line 2071 of file navier1.f.
setproj()
subroutine setproj (n1, nd)
Definition at line 4176 of file navier1.f.
References exitt(), set_pnd(), set_pndoi(), and transpose().
specmp()
subroutine specmp (real, dimension(nb,nb,nb) b, nb, real, dimension(na,na,na) a, na, ba, ab, real, dimension(1) w)
Definition at line 3079 of file navier1.f.
References mxm().
tauinit()
subroutine tauinit (tau, ilag)
Definition at line 1876 of file navier1.f.
uzawa()
subroutine uzawa (real, dimension (lx2,ly2,lz2,lelv) rcg, real, dimension (lx1,ly1,lz1,lelv) h1, real, dimension (lx1,ly1,lz1,lelv) h2, real, dimension(lx1,ly1,lz1,lelv) h2inv, intype, iter)
Definition at line 2886 of file navier1.f.
References add2s1(), add2s2(), cdabdtp(), chktcg2(), convprn(), copy(), exitt(), glamax(), glsc2(), ly1, lz1, ortho(), rzero(), and uzprec().
uzprec()
subroutine uzprec (real, dimension (lx2,ly2,lz2,lelv) rpcg, real, dimension (lx2,ly2,lz2,lelv) rcg, real, dimension (lx1,ly1,lz1,lelv) h1m1, real, dimension (lx1,ly1,lz1,lelv) h2m1, intype, real, dimension (lx2,ly2,lz2,lelv) wp)
Definition at line 963 of file navier1.f.
References add2(), cmult(), col2(), col3(), copy(), eprec(), eprec2(), gfdm_pres_solv(), map12(), and ortho().
velchar()
subroutine velchar (real, dimension (lx1,ly1,lz1,lelv) vel, real, dimension (lx1,ly1,lz1,lelv) vn, real, dimension (lx1,ly1,lz1,lelv,9) vlag, nbd, tau, real, dimension (nbd) dtbd)
Definition at line 1958 of file navier1.f.
References add2s2(), add3s2(), copy(), exitt(), ly1, and lz1.
velconv()
subroutine velconv (real, dimension (lx1,ly1,lz1,lelv) vxn, real, dimension (lx1,ly1,lz1,lelv) vyn, real, dimension (lx1,ly1,lz1,lelv) vzn, tau)
Definition at line 1912 of file navier1.f.
References velchar().
velconvv()
subroutine velconvv (real, dimension(1) vxn, real, dimension(1) vyn, real, dimension(1) vzn, tau)
Definition at line 3576 of file navier1.f.
References ly1, lz1, and velchar().
velinit()
subroutine velinit (real, dimension (lx1,ly1,lz1,lelv) vel1, real, dimension (lx1,ly1,lz1,lelv) vel2, real, dimension (lx1,ly1,lz1,lelv) vel3, ilag)
Definition at line 1891 of file navier1.f.
References opcopy().
wgradm1()
subroutine wgradm1 (real, dimension(lxyz,1) ux, real, dimension(lxyz,1) uy, real, dimension(lxyz,1) uz, real, dimension(lxyz,1) u, nel)
Definition at line 4230 of file navier1.f.
References local_grad2(), local_grad3(), ly1, lz1, setaxdy(), and setaxw1().
wlaplacian()
subroutine wlaplacian (real, dimension(1) out, real, dimension(1) a, real, dimension(1) diff, ifld)
Definition at line 4429 of file navier1.f.
References axhelm(), bcneusc(), ly1, lz1, rzero(), and sub2().