KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/navier3.f File Reference
navier3.f File Reference
Functions/Subroutines
subroutine eprec2 (Z2, R2)
subroutine dd_solver (u, v)
subroutine rar2_out (x, name13)
subroutine rarr_out2 (x, name13)
Function/Subroutine Documentation
dd_solver()
subroutine dd_solver (real, dimension(1) u, real, dimension(1) v)
Definition at line 53 of file navier3.f.
References add2s2(), crs_solve_l2(), dnekclock(), lelt, local_solves_fdm(), ly1, lz1, and rzero().
eprec2()
subroutine eprec2 (real, dimension (lx2,ly2,lz2,lelv) Z2, real, dimension (lx2,ly2,lz2,lelv) R2)
Definition at line 2 of file navier3.f.
References dd_solver(), ly1, lz1, and rzero().
rar2_out()
subroutine rar2_out (real, dimension(lx2,ly2,lz2,lelt) x, character*13 name13)
Definition at line 93 of file navier3.f.
rarr_out2()
subroutine rarr_out2 (real, dimension(lx2,ly2,lz2,lelt) x, character*13 name13)
Definition at line 120 of file navier3.f.
References ly1, and lz1.