KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/navier0.f File Reference
navier0.f File Reference
Functions/Subroutines
subroutine esolver (RES, H1, H2, H2INV, INTYPE)
subroutine estrat
subroutine einit
subroutine dmp_map (imap)
subroutine p_outvec_ir (ia, a, lda, name9)
Function/Subroutine Documentation
dmp_map()
subroutine dmp_map (integer, dimension(nelgt) imap)
Definition at line 101 of file navier0.f.
References lelt, ly1, lz1, and p_outvec_ir().
einit()
subroutine einit ()
Definition at line 84 of file navier0.f.
References estrat(), ly1, and lz1.
esolver()
subroutine esolver (real, dimension (lx2,ly2,lz2,lelv) RES, real, dimension (lx1,ly1,lz1,lelv) H1, real, dimension (lx1,ly1,lz1,lelv) H2, real, dimension (lx1,ly1,lz1,lelv) H2INV, INTYPE)
Definition at line 2 of file navier0.f.
References copy(), dnekclock(), exitt(), gfdm_pres_solv(), ortho(), uzawa(), and uzawa_gmres().
estrat()
subroutine estrat ()
Definition at line 55 of file navier0.f.
p_outvec_ir()
subroutine p_outvec_ir (integer, dimension(1) ia, real, dimension(lda,1) a, lda, character*9 name9)
Definition at line 131 of file navier0.f.
References copy(), crecv2(), csend(), icopy(), and nekgsync().