KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/navier8.f File Reference
navier8.f File Reference
Functions/Subroutines
subroutine set_vert (glo_num, ngv, nx, nel, vertex, ifcenter)
subroutine crs_solve_l2 (uf, vf)
subroutine set_up_h1_crs
subroutine set_jl_crs_mask (n, mask, se_to_gcrs)
subroutine set_mat_ij (ia, ja, n, ne)
subroutine irank_vec (ind, nn, a, m, n, key, nkey, aa)
subroutine ituple_sort (a, lda, n, key, nkey, ind, aa)
subroutine tuple_sort (a, lda, n, key, nkey, ind, aa)
logical function iftuple_ialtb (a, b, key, nkey)
logical function iftuple_altb (a, b, key, nkey)
logical function iftuple_ianeb (a, b, key, nkey)
subroutine get_local_crs (a, lda, nxc, h1, h2, w, ldw)
subroutine a_crs_enriched (a, h1, h2, x1, y1, z1, nxc, if3d, ie)
subroutine a_crs_3d (a, h1, h2, xc, yc, zc, ie)
subroutine bindec (bin_in)
subroutine get_local_a_tet (a, x, y, z, kt, ie)
subroutine a_crs_2d (a, h1, h2, x, y, ie)
subroutine map_m_to_n (a, na, b, nb, if3d, w, ldw)
subroutine specmpn (b, nb, a, na, ba, ab, if3d, w, ldw)
subroutine irank (A, IND, N)
subroutine iranku (r, input, n, w, ind)
subroutine ifacev_redef (a, ie, iface, val, nx, ny, nz)
subroutine map_c_to_f_l2_bilin (uf, uc, w)
subroutine map_f_to_c_l2_bilin (uc, uf, w)
subroutine maph1_to_l2 (a, na, b, nb, if3d, w, ldw)
subroutine maph1_to_l2t (b, nb, a, na, if3d, w, ldw)
subroutine irank_vec_tally (ind, nn, a, m, n, key, nkey, key2, aa)
subroutine out_se1 (se2crs, nx, name)
subroutine out_se0 (se2crs, nx, nel, name)
subroutine crs_solve_h1 (uf, vf)
subroutine set_h1_basis_bilin
subroutine map_c_to_f_h1_bilin (uf, uc)
subroutine map_f_to_c_h1_bilin (uc, uf)
subroutine get_local_crs_galerkin (a, ncl, nxc, h1, h2, w1, w2)
subroutine gen_crs_basis (b, j)
subroutine gen_crs_basis2 (b, j)
subroutine get_vertex
subroutine assign_gllnid (gllnid, iunsort, nelgt, nelgv, np)
subroutine get_vert
subroutine get_vert_map (vertex, nlv, nel, suffix, ifgfdm)
subroutine irank_vecn (ind, nn, a, m, n, key, nkey, aa)
subroutine gbtuple_rank (tuple, m, n, nmax, cr_h, nid, np, ind)
subroutine setvert3d (glo_num, ngv, nx, nel, vertex, ifcenter)
subroutine setvert2d (glo_num, ngv, nx, nel, vertex, ifcenter)
subroutine map_to_crs (a, na, b, nb, if3d, w, ldw)
subroutine check_p_bc (glo_num, nx, ny, nz, nel)
Function/Subroutine Documentation
subroutine a_crs_2d (real, dimension(4,4) a, real, dimension(1) h1, real, dimension(1) h2, real, dimension(1) x, real, dimension(1) y, ie)
Definition at line 811 of file navier8.f.
References rzero().
subroutine a_crs_3d (real, dimension(0:7,0:7) a, real, dimension(0:7) h1, real, dimension(0:7) h2, real, dimension(0:7) xc, real, dimension(0:7) yc, real, dimension(0:7) zc, ie)
Definition at line 634 of file navier8.f.
References bindec(), get_local_a_tet(), j, and rzero().
subroutine a_crs_enriched (real, dimension(1) a, real, dimension(1) h1, real, dimension(1) h2, real, dimension(nxc,nxc,1) x1, real, dimension(nxc,nxc,1) y1, real, dimension(nxc,nxc,1) z1, nxc, logical if3d, ie)
Definition at line 543 of file navier8.f.
References a_crs_2d(), a_crs_3d(), ia, j, ja, nz, and rzero().
subroutine assign_gllnid (integer, dimension(1) gllnid, integer, dimension(1) iunsort, integer nelgt, nelgv, integer np)
Definition at line 1636 of file navier8.f.
References exitti(), isort(), iswapt_ip(), ivlmax(), and log2().
subroutine bindec (integer bin_in)
Definition at line 695 of file navier8.f.
subroutine check_p_bc (integer*8, dimension(nx,ny,nz,nel) glo_num, nx, ny, nz, nel)
Definition at line 2571 of file navier8.f.
References j, nx, and nz.
subroutine crs_solve_h1 (real, dimension(1) uf, real, dimension(1) vf)
Definition at line 1324 of file navier8.f.
References col3(), crs_solve, dnekclock(), lelt, map_c_to_f_h1_bilin(), and map_f_to_c_h1_bilin().
subroutine crs_solve_l2 (real, dimension(1) uf, real, dimension(1) vf)
Definition at line 36 of file navier8.f.
References crs_solve, lelt, ly1, lz1, map_c_to_f_l2_bilin(), and map_f_to_c_l2_bilin().
subroutine gbtuple_rank (integer, dimension(m,nmax) tuple, m, n, nmax, integer cr_h, nid, np, integer, dimension(nmax) ind)
Definition at line 1940 of file navier8.f.
References exitt(), igl_running_sum(), iglmax(), irank_vecn(), ituple_sort(), and n.
subroutine gen_crs_basis (real, dimension(nx1,ny1,nz1) b, j)
Definition at line 1523 of file navier8.f.
References copy(), j, and zwgll().
subroutine gen_crs_basis2 (real, dimension(nx1,ny1,nz1) b, j)
Definition at line 1567 of file navier8.f.
References copy(), j, and zwgll().
subroutine get_local_a_tet (real, dimension(4,4) a, real, dimension(4) x, real, dimension(4) y, real, dimension(4) z, kt, ie)
Definition at line 714 of file navier8.f.
References j.
subroutine get_local_crs (real, dimension(1) a, lda, nxc, real, dimension(1) h1, real, dimension(1) h2, real, dimension(ldw) w, ldw)
Definition at line 493 of file navier8.f.
References a_crs_enriched(), exitt(), and map_m_to_n().
subroutine get_local_crs_galerkin (real, dimension(ncl,ncl,1) a, ncl, nxc, real, dimension(1) h1, real, dimension(1) h2, real, dimension(nx1*ny1*nz1,nelv) w1, real, dimension(nx1*ny1*nz1,nelv) w2)
Definition at line 1482 of file navier8.f.
References axhelm(), copy(), gen_crs_basis(), j, and vlsc2().
subroutine get_vert ()
Definition at line 1721 of file navier8.f.
References get_vert_map(), lelt, and nekmoab_loadconn().
subroutine get_vert_map (integer, dimension(nlv,1) vertex, nlv, nel, character*4 suffix, logical ifgfdm)
Definition at line 1750 of file navier8.f.
References assign_gllnid(), bcast(), blank(), chcopy(), csend(), exitt(), exitt0(), icopy(), iglmax(), irecv(), ltrunc(), ly1, lz1, msgwait(), and nekgsync().
subroutine get_vertex ()
Definition at line 1612 of file navier8.f.
References gen_gtp_vertex(), get_vert(), and lelt.
subroutine ifacev_redef (integer, dimension(nx,ny,nz,lelt) a, ie, iface, integer val, nx, ny, nz)
Definition at line 1046 of file navier8.f.
References facind(), nx, and nz.
logical function iftuple_altb (real, dimension(1) a, real, dimension(1) b, integer, dimension(nkey) key, nkey)
Definition at line 456 of file navier8.f.
logical function iftuple_ialtb (integer, dimension(1) a, integer, dimension(1) b, integer, dimension(nkey) key, nkey)
Definition at line 436 of file navier8.f.
logical function iftuple_ianeb (integer, dimension(1) a, integer, dimension(1) b, integer, dimension(nkey) key, nkey)
Definition at line 476 of file navier8.f.
subroutine irank (integer, dimension(1) A, integer, dimension(1) IND, N)
Definition at line 967 of file navier8.f.
References j, and n.
subroutine irank_vec (integer, dimension(n) ind, nn, integer, dimension(m,n) a, m, n, integer, dimension(nkey) key, nkey, integer, dimension(m) aa)
Definition at line 246 of file navier8.f.
References icopy(), irank(), ituple_sort(), and n.
subroutine irank_vec_tally (integer, dimension(n) ind, nn, integer, dimension(m,n) a, m, n, integer, dimension(nkey) key, nkey, integer, dimension(0:3) key2, integer, dimension(m) aa)
Definition at line 1187 of file navier8.f.
References icopy(), ituple_sort(), and n.
subroutine irank_vecn (integer, dimension(n) ind, nn, integer, dimension(m,n) a, m, n, integer, dimension(nkey) key, nkey, integer, dimension(m) aa)
Definition at line 1898 of file navier8.f.
References icopy(), ituple_sort(), and n.
subroutine iranku (integer, dimension(1) r, integer, dimension(1) input, n, integer, dimension(1) w, integer, dimension(1) ind)
Definition at line 1016 of file navier8.f.
References icopy(), isort(), iunswap(), and n.
subroutine ituple_sort (integer, dimension(lda,n) a, lda, n, integer, dimension(nkey) key, nkey, integer, dimension(1) ind, integer, dimension(lda) aa)
Definition at line 310 of file navier8.f.
References icopy(), j, and n.
subroutine map_c_to_f_h1_bilin (real, dimension(lxyz,lelt) uf, real, dimension(2,2,ldim-1,lelt) uc)
Definition at line 1390 of file navier8.f.
References lelt, ly1, lz1, mxm(), and set_h1_basis_bilin().
subroutine map_c_to_f_l2_bilin (real, dimension(lxyz,lelt) uf, real, dimension(nxyz_c,lelt) uc, real, dimension(1) w)
Definition at line 1063 of file navier8.f.
References maph1_to_l2().
subroutine map_f_to_c_h1_bilin (real, dimension(lcr,lelt) uc, real, dimension(lx1,ly1,lz1,lelt) uf)
Definition at line 1439 of file navier8.f.
References lelt, ly1, lz1, mxm(), and set_h1_basis_bilin().
subroutine map_f_to_c_l2_bilin (real, dimension(nxyz_c,lelt) uc, real, dimension(lxyz,lelt) uf, real, dimension(1) w)
Definition at line 1086 of file navier8.f.
References maph1_to_l2t().
subroutine map_m_to_n (real, dimension(1) a, na, real, dimension(1) b, nb, logical if3d, real, dimension(1) w, ldw)
Definition at line 886 of file navier8.f.
References exitt(), igllm(), specmpn(), and zwgll().
subroutine map_to_crs (real, dimension(1) a, na, real, dimension(1) b, nb, logical if3d, real, dimension(1) w, ldw)
Definition at line 2535 of file navier8.f.
References exitt(), igllm(), specmpn(), and zwgll().
subroutine maph1_to_l2 (real, dimension(1) a, na, real, dimension(1) b, nb, logical if3d, real, dimension(1) w, ldw)
Definition at line 1110 of file navier8.f.
References exitt(), igllm(), specmpn(), zwgl(), and zwgll().
subroutine maph1_to_l2t (real, dimension(1) b, nb, real, dimension(1) a, na, logical if3d, real, dimension(1) w, ldw)
Definition at line 1149 of file navier8.f.
References exitt(), igllm(), specmpn(), zwgl(), and zwgll().
subroutine out_se0 (integer, dimension(nx,nx,1) se2crs, nx, nel, character*4 name)
Definition at line 1294 of file navier8.f.
References j, and nx.
subroutine out_se1 (integer, dimension(nx,nx,1) se2crs, nx, character*4 name)
Definition at line 1264 of file navier8.f.
References j, and nx.
subroutine set_h1_basis_bilin ()
Definition at line 1373 of file navier8.f.
References transpose().
subroutine set_jl_crs_mask (n, real, dimension(1) mask, integer*8, dimension(1) se_to_gcrs)
Definition at line 221 of file navier8.f.
References n.
subroutine set_mat_ij (integer, dimension(n,n,ne) ia, integer, dimension(n,n,ne) ja, integer n, integer ne)
Definition at line 230 of file navier8.f.
subroutine set_up_h1_crs ()
Definition at line 84 of file navier8.f.
References crs_setup, dnekclock(), facev(), get_local_crs_galerkin(), get_vertex(), gs_free, gs_op, gs_setup, ia, invcol1(), ja, lelt, ly1, lz1, n, nz, rone(), rzero(), set_jl_crs_mask(), set_mat_ij(), and set_vert().
subroutine set_vert (integer*8, dimension(1) glo_num, integer*8 ngv, integer nx, nel, integer, dimension(1) vertex, logical ifcenter)
Definition at line 4 of file navier8.f.
References check_p_bc(), nz, setvert2d(), and setvert3d().
subroutine setvert2d (integer*8, dimension(1) glo_num, integer*8 ngv, integer nx, nel, integer, dimension(0:1,0:1,1) vertex, logical ifcenter)
Definition at line 2359 of file navier8.f.
References gbtuple_rank(), i0, iglmax(), j, lelt, n, and nz.
subroutine setvert3d (integer*8, dimension(1) glo_num, integer*8 ngv, integer nx, nel, integer, dimension(0:1,0:1,0:1,1) vertex, logical ifcenter)
Definition at line 2000 of file navier8.f.
References dsset(), gbtuple_rank(), i0, icopy(), iglmax(), irank(), isort(), j, lelt, n, and nz.
subroutine specmpn (real, dimension(nb,nb,nb) b, nb, real, dimension(na,na,na) a, na, ba, ab, logical if3d, real, dimension(ldw) w, ldw)
Definition at line 924 of file navier8.f.
References exitt(), and mxm().
subroutine tuple_sort (real, dimension(lda,n) a, lda, n, integer, dimension(nkey) key, nkey, integer, dimension(1) ind, real, dimension(lda) aa)
Definition at line 372 of file navier8.f.
References copy(), j, and n.