KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/nekmerge/tsort.f File Reference
tsort.f File Reference
Functions/Subroutines
subroutine ituple_sort (a, lda, n, key, nkey, ind, aa)
subroutine tuple_sort (a, lda, n, key, nkey, ind, aa)
logical function iftuple_ialtb (a, b, key, nkey)
logical function iftuple_altb (a, b, key, nkey)
logical function iftuple_ianeb (a, b, key, nkey)
logical function iftuple_iaeqb (a, b, key, nkey)
subroutine tuple_swapt_ip (x, m, n, p, t1, t2)
subroutine isort (a, ind, n)
subroutine iswap_ip (x, p, n)
subroutine iswapt_ip (x, p, n)
Function/Subroutine Documentation
logical function iftuple_altb (real, dimension(1) a, real, dimension(1) b, integer, dimension(nkey) key, nkey)
Definition at line 143 of file tsort.f.
References i, and iftuple_altb().
logical function iftuple_iaeqb (integer, dimension(1) a, integer, dimension(1) b, integer, dimension(nkey) key, nkey)
Definition at line 176 of file tsort.f.
References i, and iftuple_iaeqb().
logical function iftuple_ialtb (integer, dimension(1) a, integer, dimension(1) b, integer, dimension(nkey) key, nkey)
Definition at line 125 of file tsort.f.
References i, and iftuple_ialtb().
logical function iftuple_ianeb (integer, dimension(1) a, integer, dimension(1) b, integer, dimension(nkey) key, nkey)
Definition at line 161 of file tsort.f.
References i, and iftuple_ianeb().
subroutine isort (integer, dimension(1) a, integer, dimension(1) ind, n)
Definition at line 230 of file tsort.f.
References i, j, and n.
subroutine iswap_ip (integer, dimension(1) x, integer, dimension(1) p, n)
Definition at line 283 of file tsort.f.
References exitt(), j, and n.
subroutine iswapt_ip (integer, dimension(1) x, integer, dimension(1) p, n)
Definition at line 319 of file tsort.f.
References exitt(), j, and n.
subroutine ituple_sort (integer, dimension(lda,n) a, lda, n, integer, dimension(nkey) key, nkey, integer, dimension(1) ind, integer, dimension(lda) aa)
Definition at line 3 of file tsort.f.
References i, icopy(), j, and n.
subroutine tuple_sort (real, dimension(lda,n) a, lda, n, integer, dimension(nkey) key, nkey, integer, dimension(1) ind, real, dimension(lda) aa)
Definition at line 63 of file tsort.f.
References copy(), i, j, and n.
subroutine tuple_swapt_ip (real, dimension(m,n) x, m, n, integer, dimension(1) p, real, dimension(m) t1, real, dimension(m) t2)
Definition at line 191 of file tsort.f.
References copy(), exitt(), j, and n.