KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/nekmerge/nekmerge.f File Reference
nekmerge.f File Reference
Functions/Subroutines
program nekmerge
subroutine load_rea_files (ans)
subroutine open_file_in (ifile, iend)
subroutine open_file_out (ifile, ans)
subroutine set_ee_bcs
subroutine global_fnbr (face, dx, ndim, nel, ind, ninseg, ifseg)
subroutine get_side (dx, x, y, z, nel, ndim)
subroutine f_pairing (cbc, face, ndim, nel, nfld, lelt, work)
subroutine exitt
subroutine output_mesh (ans)
subroutine output_mesh_bin
subroutine output_mesh_ascii
subroutine out_xyz_ascii
subroutine out_curve_ascii
subroutine out_bdry_ascii
Function/Subroutine Documentation
subroutine exitt ()
Definition at line 392 of file nekmerge.f.
subroutine f_pairing (character*3, dimension(6,lelt,ndim) cbc, integer, dimension(2*ndim,nel) face, ndim, nel, nfld, lelt, integer, dimension(1) work)
Definition at line 350 of file nekmerge.f.
References exitt(), i, izero(), and n.
subroutine get_side (real, dimension(0:ndim,2*ndim,nel) dx, real, dimension(8,nel) x, real, dimension(8,nel) y, real, dimension(8,nel) z, nel, ndim)
Definition at line 282 of file nekmerge.f.
References i, j, rzero(), and scale().
subroutine global_fnbr (integer, dimension(1) face, real, dimension(0:ndim,1) dx, ndim, nel, integer, dimension(1) ind, integer, dimension(1) ninseg, logical, dimension(1) ifseg)
Definition at line 204 of file nekmerge.f.
References i, icopy(), iswap_ip(), j, n, tuple_sort(), and tuple_swapt_ip().
subroutine load_rea_files (character*1 ans)
Definition at line 39 of file nekmerge.f.
References blank(), exitt(), lelt, open_file_in(), open_file_out(), rd_bdry(), rd_curve(), rd_xyz(), and rw_param().
program nekmerge ()
Definition at line 2 of file nekmerge.f.
References exitt(), load_rea_files(), output_mesh(), and set_ee_bcs().
subroutine open_file_in (ifile, iend)
Definition at line 106 of file nekmerge.f.
References blank(), chcopy(), indx1(), and ltrunc().
subroutine open_file_out (ifile, character*1 ans)
Definition at line 143 of file nekmerge.f.
References blank(), byte_open, chcopy(), indx1(), and ltrunc().
subroutine out_bdry_ascii ()
Definition at line 631 of file nekmerge.f.
References j.
subroutine out_curve_ascii ()
Definition at line 590 of file nekmerge.f.
References cleanr(), and j.
subroutine out_xyz_ascii ()
Definition at line 552 of file nekmerge.f.
References blank(), and ltrunc().
subroutine output_mesh (character*1 ans)
Definition at line 397 of file nekmerge.f.
References output_mesh_ascii(), and output_mesh_bin().
subroutine output_mesh_ascii ()
Definition at line 528 of file nekmerge.f.
References lineout(), out_bdry_ascii(), out_curve_ascii(), out_xyz_ascii(), and scanout().
subroutine output_mesh_bin ()
Definition at line 409 of file nekmerge.f.
References blank(), byte_close, byte_write, chcopy(), copy(), icopy(), lineout(), and scanout().
subroutine set_ee_bcs ()
Definition at line 186 of file nekmerge.f.
References f_pairing(), get_side(), global_fnbr(), and lelt.