KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/nekmerge/strings.f File Reference
strings.f File Reference
Functions/Subroutines
subroutine scanout (string, input, len, infile, outfile)
subroutine scanoutafter (string, input, len, infile, outfile)
subroutine copy (a, b, n)
subroutine icopy (a, b, n)
subroutine chcopy (a, b, n)
subroutine blank (s, n)
function ltrunc (s, n)
integer function indx1 (S1, S2, L2)
subroutine cleanr (x, n)
subroutine rzero (x, n)
subroutine izero (x, n)
subroutine out_data (y, n, fname)
subroutine lineout (io, s, n)
subroutine fbyte_write (s, n)
subroutine strg_write (s, n)
subroutine int_write (s, n)
subroutine real_write (s, n)
subroutine bdry_write (s, n)
Function/Subroutine Documentation
subroutine bdry_write (real, dimension(n) s, n)
Definition at line 225 of file strings.f.
References int_write(), real_write(), and strg_write().
subroutine blank (character*1, dimension(1) s, n)
Definition at line 80 of file strings.f.
References i, and n.
subroutine chcopy (character*1, dimension(1) a, character*1, dimension(1) b, n)
Definition at line 73 of file strings.f.
References i, and n.
subroutine cleanr (real, dimension(1) x, n)
Definition at line 120 of file strings.f.
References i, and n.
subroutine copy (real, dimension(1) a, real, dimension(1) b, n)
Definition at line 59 of file strings.f.
References i, and n.
subroutine fbyte_write (character*4, dimension(n) s, n)
Definition at line 183 of file strings.f.
References byte_write, lineout(), and n.
subroutine icopy (integer, dimension(1) a, integer, dimension(1) b, n)
Definition at line 66 of file strings.f.
References i, and n.
integer function indx1 (character*80 S1, character*80 S2, L2)
Definition at line 102 of file strings.f.
References i, and indx1().
subroutine int_write (integer, dimension(n) s, n)
Definition at line 207 of file strings.f.
References n.
subroutine izero (integer, dimension(1) x, n)
Definition at line 140 of file strings.f.
References i, and n.
subroutine lineout (io, character*1, dimension(n) s, n)
Definition at line 175 of file strings.f.
References ltrunc(), and n.
function ltrunc (character*1, dimension(1) s, n)
Definition at line 89 of file strings.f.
References j, ltrunc(), and n.
subroutine out_data (real*4, dimension(1) y, n, character*40 fname)
Definition at line 148 of file strings.f.
References byte_close, byte_open, byte_write, and n.
subroutine real_write (real, dimension(n) s, n)
Definition at line 216 of file strings.f.
References n.
subroutine rzero (real, dimension(1) x, n)
Definition at line 132 of file strings.f.
References i, and n.
subroutine scanout (character*80 string, character*1, dimension(1) input, len, integer infile, integer outfile)
Definition at line 3 of file strings.f.
References blank(), chcopy(), indx1(), j, and ltrunc().
subroutine scanoutafter (character*80 string, character*1, dimension(1) input, len, integer infile, integer outfile)
Definition at line 32 of file strings.f.
References blank(), chcopy(), indx1(), j, and ltrunc().
subroutine strg_write (character*4, dimension(n) s, n)
Definition at line 198 of file strings.f.
References n.