KTH framework for Nek5000 toolboxes; testing version: Nek5000/jl/obbox_test.c File Reference
obbox_test.c File Reference
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include <float.h>
#include <string.h>
#include "c99.h"
#include "types.h"
#include "name.h"
#include "fail.h"
#include "mem.h"
#include "poly.h"
#include "lob_bnd.h"
#include "obbox.h"
#include "rand_elt_test.h"
Macros
#define REPEAT 20
#define N 100
#define NR 7
#define MR (4*NR)
#define NS 8
#define MS (4*NS)
#define NT 9
#define MT (4*NT)
#define TOL 0.00001
Functions
int main ()
Macro Definition Documentation
#define MR (4*NR)
Definition at line 20 of file obbox_test.c.
#define MS (4*NS)
Definition at line 22 of file obbox_test.c.
#define MT (4*NT)
Definition at line 24 of file obbox_test.c.
#define N 100
Definition at line 18 of file obbox_test.c.
#define NR 7
Definition at line 19 of file obbox_test.c.
#define NS 8
Definition at line 21 of file obbox_test.c.
#define NT 9
Definition at line 23 of file obbox_test.c.
#define REPEAT 20
Definition at line 16 of file obbox_test.c.
#define TOL 0.00001
Definition at line 26 of file obbox_test.c.
Function Documentation
int main ()
Definition at line 46 of file obbox_test.c.
References obbox_2::A, obbox_3::A, bubble_elt(), obbox_2::c0, obbox_3::c0, i, j, lob_bnd_2, lob_bnd_3, lob_bnd_setup, lobatto_nodes, dbl_range::max, dbl_range::min, MR, MS, MT, N, n, NR, NS, NT, obbox_calc_2, obbox_calc_3, printf(), rand_elt_2(), rand_elt_3(), REPEAT, tmalloc, TOL, x, obbox_2::x, obbox_3::x, y(), and z.