KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/nekmerge/openfile.f File Reference
openfile.f File Reference
Functions/Subroutines
subroutine open_file_in (ifile)
subroutine open_file_out (ifile)
Function/Subroutine Documentation
subroutine open_file_in (ifile)
Definition at line 3 of file openfile.f.
References blank(), chcopy(), and ltrunc().
subroutine open_file_out (ifile)
Definition at line 26 of file openfile.f.
References blank(), byte_open, chcopy(), and ltrunc().