KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/cmt/outflow_bc.f File Reference
outflow_bc.f File Reference
Dirichlet states for outflow boundary conditions.
Functions/Subroutines
subroutine outflow (nvar, f, e, facew, wbc, flux)
subroutine outflow_rflu (nvar, f, e, facew, wbc)
subroutine bcondoutflowperf (bcOpt, pout, sxn, syn, szn, cpgas, mol, rho, rhou, rhov, rhow, rhoe, press, rhob, rhoub, rhovb, rhowb, rhoeb)
Detailed Description
Dirichlet states for outflow boundary conditions.
Definition in file outflow_bc.f.
Function/Subroutine Documentation
subroutine bcondoutflowperf (integer bcOpt, real pout, real sxn, real syn, real szn, real cpgas, real mol, real rho, real rhou, real rhov, real rhow, real rhoe, real press, real rhob, real rhoub, real rhovb, real rhowb, real rhoeb)
Definition at line 132 of file outflow_bc.f.
References mixtperf_p_deogvm2().
subroutine outflow (integer nvar, integer f, integer e, real, dimension(nx1,nz1,2*ldim,nelt,nvar) facew, real, dimension(nx1,nz1,2*ldim,nelt,nvar) wbc, real, dimension(nx1*nz1,2*ldim,nelt,*) flux)
Definition at line 3 of file outflow_bc.f.
References outflow_rflu().
subroutine outflow_rflu (nvar, integer f, integer e, real, dimension(nx1*nz1,2*ldim,nelt,nvar) facew, real, dimension(nx1*nz1,2*ldim,nelt,nvar) wbc)
Definition at line 19 of file outflow_bc.f.
References bcondoutflowperf(), facind(), i0, and nekasgn().