KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/pertsupport.f File Reference
pertsupport.f File Reference
Functions/Subroutines
subroutine flushbuffer (k)
real function opnormold (v1, v2, v3, weight)
function opnorm2 (v1, v2, v3)
function tnorm (temp)
real function dmnorm (v1, v2, v3, temp)
subroutine opscale (v1, v2, v3, temp, alpha)
subroutine opscalev (v1, v2, v3, alpha)
subroutine computelyap
subroutine computelyap1 (vxq, vyq, vzq, tq, jpp)
subroutine rescalepert (pertnorm, pertinvnorm, jpp)
subroutine writehist (v1, v2, v3, temp, jpp)
subroutine initialize
subroutine initialize1 (jpp)
subroutine get_useric
subroutine out_pert
subroutine pert_add2s2 (i, j, scale)
function pert_inner_prod (i, j)
subroutine pert_ortho_norm
subroutine pert_ortho_norm1 (k)
Function/Subroutine Documentation
subroutine computelyap ()
Definition at line 138 of file pertsupport.f.
References computelyap1().
subroutine computelyap1 (real, dimension(1) vxq, real, dimension(1) vyq, real, dimension(1) vzq, real, dimension(1) tq, jpp)
Definition at line 151 of file pertsupport.f.
References dmnorm(), flushbuffer(), pert_ortho_norm(), and rescalepert().
real function dmnorm (real, dimension(1) v1, real, dimension(1) v2, real, dimension(1) v3, real, dimension(1) temp)
Definition at line 70 of file pertsupport.f.
References glsc3().
subroutine flushbuffer (integer k)
Definition at line 4 of file pertsupport.f.
subroutine get_useric ()
Definition at line 499 of file pertsupport.f.
subroutine initialize ()
Definition at line 344 of file pertsupport.f.
References initialize1().
subroutine initialize1 (jpp)
Definition at line 355 of file pertsupport.f.
References bcast(), blank(), chcopy(), exitt(), get_useric(), ltrunc(), ly1, lz1, opnorm2(), opzero(), rescalepert(), rzero(), and tnorm().
function opnorm2 (real, dimension(1) v1, real, dimension(1) v2, real, dimension(1) v3)
Definition at line 36 of file pertsupport.f.
References glsc3().
real function opnormold (real, dimension(1) v1, real, dimension(1) v2, real, dimension(1) v3, real, dimension(1) weight)
Definition at line 14 of file pertsupport.f.
References glsc3().
subroutine opscale (real, dimension(1) v1, real, dimension(1) v2, real, dimension(1) v3, real, dimension(1) temp, real alpha)
Definition at line 100 of file pertsupport.f.
References cmult(), lelt, ly1, and lz1.
subroutine opscalev (real, dimension(*) v1, real, dimension(*) v2, real, dimension(*) v3, real alpha)
Definition at line 120 of file pertsupport.f.
References cmult().
subroutine out_pert ()
Definition at line 531 of file pertsupport.f.
References outpost2(), and writehist().
subroutine pert_add2s2 (i, j, scale)
Definition at line 552 of file pertsupport.f.
References add2s2(), and scale().
function pert_inner_prod (i, j)
Definition at line 596 of file pertsupport.f.
References glsc3().
subroutine pert_ortho_norm ()
Definition at line 618 of file pertsupport.f.
References pert_ortho_norm1().
subroutine pert_ortho_norm1 (k)
Definition at line 629 of file pertsupport.f.
References pert_add2s2(), pert_inner_prod(), rescalepert(), and scale().
subroutine rescalepert (pertnorm, pertinvnorm, jpp)
Definition at line 236 of file pertsupport.f.
References cmult(), ly1, lz1, and opscale().
function tnorm (real, dimension(*) temp)
Definition at line 58 of file pertsupport.f.
References glsc3().
subroutine writehist (real, dimension(nx1,ny1,nz1,nelv) v1, real, dimension(nx1,ny1,nz1,nelv) v2, real, dimension(nx1,ny1,nz1,nelv) v3, real, dimension(nx1,ny1,nz1,nelv) temp, jpp)
Definition at line 268 of file pertsupport.f.
References crecv(), csend(), and flushbuffer().