KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/perturb.f File Reference
perturb.f File Reference
Functions/Subroutines
subroutine fluidp (igeom)
subroutine perturbv (igeom)
subroutine lagfieldp
subroutine makefp
subroutine makeufp
subroutine advabp
subroutine advabp_adjoint
subroutine convop_adj (bdux, bduy, bduz, udx, udy, udz, cx, cy, cz)
subroutine makextp
subroutine makebdfp
subroutine cresvipp (resv1, resv2, resv3, h1, h2)
subroutine heatp (igeom)
subroutine cdscalp (igeom)
subroutine makeqp
subroutine makeuqp
subroutine convabp
subroutine makeabqp
subroutine makebdqp
subroutine lagscalp
subroutine incomprp (ux, uy, uz, up)
subroutine extrapprp (prextr)
subroutine lagpresp
subroutine lyap_scale
subroutine out_pert
subroutine pert_add2s2 (i, j, scale)
function pert_inner_prod (i, j)
subroutine pert_ortho_norm
subroutine pert_ortho_norm1 (k)
function opnorm2 (v1, v2, v3)
function tnorm (temp)
function dmnorm1 (v1, v2, v3, temp)
subroutine opscale (v1, v2, v3, temp, alpha)
subroutine opscalev (v1, v2, v3, alpha)
subroutine computelyap
subroutine computelyap1 (vxq, vyq, vzq, tq, jpp)
subroutine rescalepert (pertnorm, pertinvnorm, jpp)
Function/Subroutine Documentation
advabp()
subroutine advabp ()
Definition at line 132 of file perturb.f.
References convop(), ly1, lz1, and opcopy().
advabp_adjoint()
subroutine advabp_adjoint ()
Definition at line 207 of file perturb.f.
References convop(), convop_adj(), ly1, lz1, opcolv3(), and opcopy().
cdscalp()
subroutine cdscalp (igeom)
Definition at line 578 of file perturb.f.
References add2(), axhelm(), bcdirsc(), bcneusc(), hmholtz(), lagscalp(), lelt, ly1, lz1, makeqp(), sethlm(), and sub3().
computelyap()
subroutine computelyap ()
Definition at line 1239 of file perturb.f.
References computelyap1().
computelyap1()
subroutine computelyap1 (real, dimension(1) vxq, real, dimension(1) vyq, real, dimension(1) vzq, real, dimension(1) tq, jpp)
Definition at line 1251 of file perturb.f.
References dmnorm1(), pert_ortho_norm(), and rescalepert().
convabp()
subroutine convabp ()
Definition at line 709 of file perturb.f.
References add2(), cmult(), col2(), convop(), copy(), lelt, ly1, lz1, opcopy(), and subcol3().
convop_adj()
subroutine convop_adj (real, dimension(1) bdux, real, dimension(1) bduy, real, dimension(1) bduz, real, dimension(1) udx, real, dimension(1) udy, real, dimension(1) udz, real, dimension(1) cx, real, dimension(1) cy, real, dimension(1) cz)
Definition at line 317 of file perturb.f.
References grad_rst(), intp_rstd(), invcol2(), ly1, lz1, and set_dealias_rx().
cresvipp()
subroutine cresvipp (real, dimension (lx1,ly1,lz1,1) resv1, real, dimension (lx1,ly1,lz1,1) resv2, real, dimension (lx1,ly1,lz1,1) resv3, real, dimension (lx1,ly1,lz1,1) h1, real, dimension (lx1,ly1,lz1,1) h2)
Definition at line 510 of file perturb.f.
References bcdirvc(), extrapprp(), ly1, lz1, opadd2(), opgradt(), ophx(), and opsub2().
dmnorm1()
function dmnorm1 (real, dimension(1) v1, real, dimension(1) v2, real, dimension(1) v3, real, dimension(1) temp)
Definition at line 1171 of file perturb.f.
References glsc3(), ly1, and lz1.
extrapprp()
subroutine extrapprp (real, dimension (lx2,ly2,lz2,lelv) prextr)
Definition at line 931 of file perturb.f.
References add3(), cmult(), copy(), exitt(), and sub3().
fluidp()
subroutine fluidp (igeom)
Definition at line 3 of file perturb.f.
References perturbv().
heatp()
subroutine heatp (igeom)
Definition at line 543 of file perturb.f.
References cdscalp(), settolt(), and unorm().
incomprp()
subroutine incomprp (ux, uy, uz, up)
Definition at line 850 of file perturb.f.
References add3(), chsign(), cmult2(), esolver(), extrapprp(), invers2(), lagpresp(), ly1, lz1, opadd2(), opbinv(), opdiv(), opgradt(), ortho(), and rzero().
lagfieldp()
subroutine lagfieldp ()
Definition at line 74 of file perturb.f.
References opcopy().
lagpresp()
subroutine lagpresp ()
Definition at line 957 of file perturb.f.
References copy().
lagscalp()
subroutine lagscalp ()
Definition at line 827 of file perturb.f.
References copy(), ly1, and lz1.
lyap_scale()
subroutine lyap_scale ()
Definition at line 972 of file perturb.f.
References cmult(), ly1, lz1, normvc(), opcmult(), and scale().
makeabqp()
subroutine makeabqp ()
Definition at line 755 of file perturb.f.
References add2s1(), add3s2(), copy(), lelt, ly1, and lz1.
makebdfp()
subroutine makebdfp ()
Definition at line 466 of file perturb.f.
References cmult2(), ly1, lz1, opadd2(), opadd2col(), and opcolv3c().
makebdqp()
subroutine makebdqp ()
Definition at line 784 of file perturb.f.
References add2(), add2s2(), cmult(), col2(), col3(), copy(), lelt, ly1, and lz1.
makefp()
subroutine makefp ()
Definition at line 94 of file perturb.f.
References advabp(), advabp_adjoint(), makebdfp(), makeufp(), and makextp().
makeqp()
subroutine makeqp ()
Definition at line 659 of file perturb.f.
References convabp(), exitt(), makeabqp(), makebdqp(), and makeuqp().
makeufp()
subroutine makeufp ()
Definition at line 114 of file perturb.f.
References nekuf(), and opcolv2().
makeuqp()
subroutine makeuqp ()
Definition at line 684 of file perturb.f.
References col2(), ly1, lz1, rzero(), and setqvol().
makextp()
subroutine makextp ()
Definition at line 427 of file perturb.f.
References add2s1(), add3s2(), copy(), ly1, and lz1.
opnorm2()
function opnorm2 (real, dimension(1) v1, real, dimension(1) v2, real, dimension(1) v3)
Definition at line 1137 of file perturb.f.
References glsc3(), ly1, lz1, and opnorm2().
opscale()
subroutine opscale (real, dimension(1) v1, real, dimension(1) v2, real, dimension(1) v3, real, dimension(1) temp, real alpha)
Definition at line 1201 of file perturb.f.
References cmult(), lelt, ly1, and lz1.
opscalev()
subroutine opscalev (real, dimension(*) v1, real, dimension(*) v2, real, dimension(*) v3, real alpha)
Definition at line 1221 of file perturb.f.
References cmult(), ly1, and lz1.
out_pert()
subroutine out_pert ()
Definition at line 1024 of file perturb.f.
References outpost2().
pert_add2s2()
subroutine pert_add2s2 (i, j, scale)
Definition at line 1044 of file perturb.f.
References add2s2(), ly1, lz1, and scale().
pert_inner_prod()
function pert_inner_prod (i, j)
Definition at line 1089 of file perturb.f.
References glsc3(), ly1, lz1, and pert_inner_prod().
pert_ortho_norm()
subroutine pert_ortho_norm ()
Definition at line 1111 of file perturb.f.
References pert_ortho_norm1().
pert_ortho_norm1()
subroutine pert_ortho_norm1 (k)
Definition at line 1122 of file perturb.f.
References pert_add2s2(), pert_inner_prod(), rescalepert(), and scale().
perturbv()
subroutine perturbv (igeom)
Definition at line 26 of file perturb.f.
References cresvipp(), incomprp(), lagfieldp(), ly1, lz1, makefp(), opadd2(), ophinv(), and sethlm().
rescalepert()
subroutine rescalepert (pertnorm, pertinvnorm, jpp)
Definition at line 1336 of file perturb.f.
References cmult(), ly1, lz1, and opscale().
tnorm()
function tnorm (real, dimension(*) temp)
Definition at line 1159 of file perturb.f.
References glsc3(), ly1, lz1, and tnorm().