KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/plan5.f File Reference
plan5.f File Reference
Functions/Subroutines
subroutine plan5 (igeom)
subroutine midstep (ux, uy, uz, pu, iresv, dtl)
subroutine adv_geom (dtl)
Function/Subroutine Documentation
adv_geom()
subroutine adv_geom (dtl)
Definition at line 150 of file plan5.f.
References gengeom().
midstep()
subroutine midstep (real, dimension(1) ux, real, dimension(1) uy, real, dimension(1) uz, real, dimension(1) pu, iresv, dtl)
Definition at line 70 of file plan5.f.
References admeshv(), adv_geom(), bcdirvc(), cmult2(), convop(), copy(), exitti(), incomprn(), lelt, ly1, lz1, makeuf(), opadd2(), opcopy(), ophinv_pr(), ophx(), and rzero().
plan5()
subroutine plan5 (igeom)
Definition at line 3 of file plan5.f.
References geom_reset(), ly1, lz1, midstep(), opcopy(), ortho(), setprop(), and setup_convect().