KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/planx.f File Reference
planx.f File Reference
Functions/Subroutines
subroutine plan3 (IGEOM)
subroutine lagpres
subroutine cresvif (resv1, resv2, resv3, h1, h2)
subroutine extrapp_old (PREXTR)
subroutine ophinvpr (ot1, ot2, ot3, in1, in2, in3, h1, h2, tolh, nmxi)
subroutine hmzpf2 (nm, u, rhs, h1, h2, mask, mult, imsh, tol, mxit, isd)
subroutine projh2 (v1, h1, h2, vml, vmask, isd, imsh)
subroutine gensh2 (v1, h1, h2, vml, vmask, isd, imsh)
subroutine updtseth2 (v1, h1, h2, vml, vmask, isd, imsh)
subroutine hconj2 (kprev, h1, h2, vml, vmask, isd, imsh)
subroutine updrhsh2 (h1, h2, vml, vmask, isd, imsh)
Function/Subroutine Documentation
subroutine cresvif (real, dimension (lx1,ly1,lz1,1) resv1, real, dimension (lx1,ly1,lz1,1) resv2, real, dimension (lx1,ly1,lz1,1) resv3, real, dimension (lx1,ly1,lz1,1) h1, real, dimension (lx1,ly1,lz1,1) h2)
Definition at line 81 of file planx.f.
References bcdirvc(), bcneutr(), extrapp(), lagvel(), ly1, lz1, opadd2(), opgradt(), ophx(), and opsub2().
subroutine extrapp_old (real, dimension (lx2,ly2,lz2,lelv) PREXTR)
Definition at line 115 of file planx.f.
References add3(), cmult(), copy(), exitt(), and sub3().
subroutine gensh2 (real, dimension(1) v1, real, dimension(1) h1, real, dimension(1) h2, real, dimension(1) vml, real, dimension(1) vmask, isd, imsh)
Definition at line 342 of file planx.f.
References add2(), copy(), and updtseth2().
subroutine hconj2 (kprev, real, dimension(1) h1, real, dimension(1) h2, real, dimension(1) vml, real, dimension(1) vmask, isd, imsh)
Definition at line 407 of file planx.f.
References add2s2(), axhelm(), cmult(), col2(), dssum(), glsc2(), gop(), and vlsc2().
subroutine hmzpf2 (character*4 nm, real, dimension (lx1,ly1,lz1,1) u, real, dimension (lx1,ly1,lz1,1) rhs, real, dimension (lx1,ly1,lz1,1) h1, real, dimension (lx1,ly1,lz1,1) h2, real, dimension (lx1,ly1,lz1,1) mask, real, dimension (lx1,ly1,lz1,1) mult, imsh, tol, mxit, isd)
Definition at line 203 of file planx.f.
References col2(), dssum(), gensh2(), hmhzpf(), and projh2().
subroutine lagpres ()
Definition at line 62 of file planx.f.
References copy().
subroutine ophinvpr (real, dimension (lx1,ly1,lz1,1) ot1, real, dimension (lx1,ly1,lz1,1) ot2, real, dimension (lx1,ly1,lz1,1) ot3, real, dimension (lx1,ly1,lz1,1) in1, real, dimension (lx1,ly1,lz1,1) in2, real, dimension (lx1,ly1,lz1,1) in3, real, dimension (lx1,ly1,lz1,1) h1, real, dimension (lx1,ly1,lz1,1) h2, tolh, nmxi)
Definition at line 146 of file planx.f.
References hmhzsf(), hmzpf2(), and ophinv().
subroutine plan3 (IGEOM)
Definition at line 2 of file planx.f.
References cresvif(), incomprn(), ly1, lz1, makef(), opadd2(), ophinv(), ophinv_pr(), and sethlm().
subroutine projh2 (real, dimension(1) v1, real, dimension(1) h1, real, dimension(1) h2, real, dimension(1) vml, real, dimension(1) vmask, isd, imsh)
Definition at line 233 of file planx.f.
References add2s2(), axhelm(), cmult2(), col2(), dssum(), glsc23(), gop(), izero(), rzero(), sub2(), updrhsh2(), and vlsc3().
subroutine updrhsh2 (real, dimension(1) h1, real, dimension(1) h2, real, dimension(1) vml, real, dimension(1) vmask, isd, imsh)
Definition at line 487 of file planx.f.
References hconj2(), and izero().
subroutine updtseth2 (real, dimension(1) v1, real, dimension(1) h1, real, dimension(1) h2, real, dimension(1) vml, real, dimension(1) vmask, isd, imsh)
Definition at line 365 of file planx.f.
References copy(), and hconj2().