KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/postpro.f File Reference
postpro.f File Reference
Functions/Subroutines
subroutine load_fld (string)
subroutine lambda2 (l2)
subroutine find_lam3 (lam, aa, w, ndim, ierr)
subroutine quadratic (x1, x2, a, b, c, ierr)
subroutine cubic (xo, ai1, ai2, ai3, ierr)
subroutine comp_gije (gije, u, v, w, e)
subroutine filter_s1 (scalar, tf, nx, nel)
subroutine filter_s0 (scalar, wght, ncut, name5)
subroutine intpts_setup (tolin, ih)
subroutine intpts (fieldin, nfld, pts, n, fieldout, ifot, ifpts, ih)
subroutine intpts_done (ih)
subroutine tens3d1 (v, u, f, ft, nv, nu)
subroutine build_1d_filt (fh, fht, trnsfr, nx, nio)
subroutine mag_tensor_e (mag, aije)
subroutine comp_sije (gije)
subroutine map2reg (ur, n, u, nel)
subroutine map2reg_2di_e (uf, n, uc, m)
subroutine map2reg_3di_e (uf, n, uc, m)
subroutine gen_int_gz (j, jt, g, n, z, m)
subroutine zuni (z, np)
subroutine gen_re2 (imid)
subroutine gen_re2_xyz
subroutine gen_re2_curve (imid)
subroutine gen_re2_bc (ifld)
subroutine gen_rea (imid)
subroutine gen_rea_xyz
subroutine gen_rea_curve (imid)
subroutine gen_rea_bc (ifld)
subroutine gen_rea_midside_e (e)
subroutine g2gi (outfld, infld, geofld)
subroutine g2gi_buf2v (v, buf, ndim, nel, nxyz)
subroutine g2gi_v2buf (buf, v, ndim, nel, nxyz)
subroutine hpts
subroutine buffer_in (buffer, npp, npoints, nbuf)
subroutine hpts_in (pts, npts, npoints)
subroutine hpts_out (fieldout, nflds, nfldm, npoints, nbuff)
Function/Subroutine Documentation
subroutine buffer_in (real, dimension(ldim,nbuf) buffer, npp, npoints, nbuf)
Definition at line 2041 of file postpro.f.
References bcast(), csend(), exitt(), iglsum(), irecv(), j, msgwait(), and nekgsync().
subroutine build_1d_filt (real, dimension(nx,nx) fh, real, dimension(nx,nx) fht, real, dimension(nx) trnsfr, nx, nio)
Definition at line 567 of file postpro.f.
References copy(), exitt(), gaujordf(), j, legendre_poly(), mxm(), n, nx, rzero(), transpose(), and zwgll().
subroutine comp_gije (real, dimension(lx1*ly1*lz1,ldim,ldim) gije, real, dimension (lx1*ly1*lz1) u, real, dimension (lx1*ly1*lz1) v, real, dimension (lx1*ly1*lz1) w, integer e)
Definition at line 258 of file postpro.f.
References exitt(), local_grad2(), local_grad3(), and n.
subroutine comp_sije (real, dimension(lx1*ly1*lz1,ldim,ldim) gije)
Definition at line 659 of file postpro.f.
References j.
subroutine cubic (real, dimension(3) xo, real ai1, real ai2, real ai3, ierr)
Definition at line 199 of file postpro.f.
References rzero().
subroutine filter_s0 (real, dimension(1) scalar, wght, ncut, character*5 name5)
Definition at line 348 of file postpro.f.
References build_new_filter(), filterq(), glmax(), and iglmax().
subroutine filter_s1 (real, dimension(lxyz,1) scalar, real, dimension(nx) tf, nx, nel)
Definition at line 326 of file postpro.f.
References build_1d_filt(), copy(), ly1, lz1, nx, and tens3d1().
subroutine find_lam3 (real, dimension(ndim) lam, real, dimension(ndim,ndim) aa, real, dimension(ndim,ndim) w, ndim, ierr)
Definition at line 84 of file postpro.f.
References cubic(), quadratic(), and sort().
subroutine g2gi (character*132 outfld, character*132 infld, character*132 geofld)
Definition at line 1649 of file postpro.f.
References bcast(), byte_close, byte_open_mpi(), byte_read_mpi(), byte_set_view(), byte_sync_mpi(), byte_write_mpi(), chcopy(), copy(), copyx4(), dnekclock_sync(), err_chk(), exitt(), g2gi_buf2v(), g2gi_v2buf(), igl_running_sum(), iglmax(), indx2(), intpts(), intpts_setup(), lelt, load_fld(), ly1, lz1, mfi_parse_hdr(), npts, and rzero().
subroutine g2gi_buf2v (real, dimension(nel*nxyz,1) v, real*4, dimension(1) buf, ndim, nel, nxyz)
Definition at line 1885 of file postpro.f.
References copy4r(), and j.
subroutine g2gi_v2buf (real*4, dimension(1) buf, real, dimension(nel*nxyz,1) v, ndim, nel, nxyz)
Definition at line 1902 of file postpro.f.
References copyx4(), and j.
subroutine gen_int_gz (real, dimension(n,m) j, real, dimension(m,n) jt, real, dimension(n) g, n, real, dimension(m) z, m)
Definition at line 775 of file postpro.f.
References fd_weights_full(), n, and transpose().
subroutine gen_re2 (imid)
Definition at line 812 of file postpro.f.
References blank(), byte_close, byte_open, byte_write, err_chk(), gen_re2_bc(), gen_re2_curve(), and gen_re2_xyz().
subroutine gen_re2_bc (ifld)
Definition at line 1160 of file postpro.f.
References blank(), byte_write, chcopy(), copy(), copyx4(), err_chk(), gop(), icopy(), igop(), izero(), and rzero().
subroutine gen_re2_curve (imid)
Definition at line 1039 of file postpro.f.
References blank(), byte_write, chcopy(), copy(), copyx4(), err_chk(), gen_rea_midside_e(), gop(), icopy(), iglsum(), igop(), izero(), lelt, and rzero().
subroutine gen_re2_xyz ()
Definition at line 859 of file postpro.f.
References byte_write, err_chk(), gop(), igop(), izero(), j, and rzero().
subroutine gen_rea (imid)
Definition at line 1279 of file postpro.f.
References gen_rea_bc(), gen_rea_curve(), and gen_rea_xyz().
subroutine gen_rea_bc (ifld)
Definition at line 1502 of file postpro.f.
References chcopy(), copy(), gop(), igop(), izero(), and rzero().
subroutine gen_rea_curve (imid)
Definition at line 1400 of file postpro.f.
References blank(), copy(), gen_rea_midside_e(), gop(), iglsum(), igop(), izero(), lelt, and rzero().
subroutine gen_rea_midside_e (integer e)
Definition at line 1591 of file postpro.f.
References chcopy(), copy(), j, and map2reg().
subroutine gen_rea_xyz ()
Definition at line 1304 of file postpro.f.
References gop(), igop(), izero(), j, and rzero().
subroutine hpts ()
Definition at line 1919 of file postpro.f.
References copy(), findpts, findpts_eval, hpts_in(), hpts_out(), intpts_setup(), lelt, ly1, lz1, and prepost_map().
subroutine hpts_in (real, dimension(ldim,npts) pts, npts, npoints)
Definition at line 2105 of file postpro.f.
References buffer_in(), copy(), exitt(), lelt, ly1, lz1, mod1(), and npts.
subroutine hpts_out (real, dimension(nfldm,nbuff) fieldout, nflds, nfldm, npoints, nbuff)
Definition at line 2168 of file postpro.f.
References crecv(), csend(), and nekgsync().
subroutine intpts (real, dimension(1) fieldin, nfld, real, dimension(1) pts, n, real, dimension(1) fieldout, logical ifot, logical ifpts, ih)
Definition at line 424 of file postpro.f.
References exitt(), findpts, findpts_eval, iglsum(), lelt, ly1, lz1, and n.
subroutine intpts_done (ih)
Definition at line 523 of file postpro.f.
References findpts_free.
subroutine intpts_setup (tolin, ih)
Definition at line 394 of file postpro.f.
References findpts_setup, lelt, ly1, lz1, and n.
subroutine lambda2 (real, dimension(lx1,ly1,lz1,1) l2)
Definition at line 28 of file postpro.f.
References comp_gije(), filter_s0(), find_lam3(), j, ly1, lz1, n, and rzero().
subroutine load_fld (character*1, dimension(1) string)
Definition at line 2 of file postpro.f.
References blank(), chcopy(), and setics().
subroutine mag_tensor_e (real, dimension (lx1*ly1*lz1) mag, real, dimension(lx1*ly1*lz1,ldim,ldim) aije)
Definition at line 634 of file postpro.f.
References j, rzero(), and vsqrt().
subroutine map2reg (real, dimension(1) ur, n, real, dimension(lx1*ly1*lz1,1) u, nel)
Definition at line 685 of file postpro.f.
References map2reg_2di_e(), map2reg_3di_e(), and n.
subroutine map2reg_2di_e (real, dimension(n,n) uf, n, real, dimension(m,m) uc, m)
Definition at line 706 of file postpro.f.
References exitti(), gen_int_gz(), j, mxm(), n, zuni(), and zwgll().
subroutine map2reg_3di_e (real, dimension(n,n,n) uf, n, real, dimension(m,m,m) uc, m)
Definition at line 735 of file postpro.f.
References exitti(), gen_int_gz(), j, mxm(), n, zuni(), and zwgll().
subroutine quadratic (x1, x2, a, b, c, ierr)
Definition at line 151 of file postpro.f.
subroutine tens3d1 (real, dimension(nv,nv,nv) v, real, dimension(nu,nu,nu) u, real, dimension(1) f, real, dimension(1) ft, nv, nu)
Definition at line 530 of file postpro.f.
References exitt(), lz1, and mxm().
subroutine zuni (real, dimension(1) z, np)
Definition at line 796 of file postpro.f.