KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/postnek5.f File Reference
postnek5.f File Reference
Functions/Subroutines
subroutine heatc (tpp, xpp, ypp, zpp, ifcrv, ktr)
subroutine contour (val, wrk, ifcrv, ncol, jrow1, jrow2, ktr)
subroutine advcell (RC, SC, IFEDGB, IFCRN, IEDGC, VAL, WRK, NCOL, ICEL, JCEL, JCEL0)
subroutine ctrscan (ifok, wrk, r, rxvr, nxvr, n)
subroutine pltcntr (xpp, ypp, zpp, val, ktr)
subroutine evalsc2 (x0, scal, rrl)
subroutine fndrr (rc, r0, r1, v0, v1, v)
logical function ifin (VAL)
subroutine beginpp
subroutine minmax (xmn, xmx, x, n)
subroutine lfalse (ifa, n)
subroutine heatf (tpp, xpp, ypp, zpp, ifcrv, inrm)
subroutine setrstp (ivec)
subroutine setrstp_act (ivec, XPT1, YPT1, ZPT1, XNRM1, YNRM1, ZNRM1)
subroutine aarrow (xpp, ypp, zpp, xvec, yvec, zvec, nxx)
subroutine arow3p (x, y, z, dxbar, dybar, dzbar, vecp, sarrow)
subroutine border (xpp, ypp, zpp, ifcrv, nxx_IN, ifnx)
subroutine mapgl1 (xf, xgl, mxx, mx)
subroutine mapglr (xmap, ymap, intrp, mxx, mx, wrk)
subroutine setix (intrp, mxx, mx, wrk)
subroutine mapglr2 (xmap, ymap, intrp, mxx, mx, r1, r2, s1, s2, wrk)
subroutine setix2 (intrp, mxx, mx, r1, r2, s1, s2, wrk)
subroutine drwmsh
subroutine drwmsh2
subroutine nekplanar
subroutine setrstp_set (ivec, XPT1, YPT1, ZPT1)
subroutine mapglg (xmap, ymap, intrp, mxx, mx, wrk)
subroutine setixg (intrp, mxx, mx, wrk)
subroutine drwmsh3
subroutine draw_circu (x3, y3, z3, r, u, sc, l)
subroutine arow3np (x, y, z, dxbar, dybar, dzbar, sarrow)
subroutine draw_circ1 (x3, y3, z3, r)
subroutine map_gll_2_gl (ugl, mx, ugll, nx, if3d)
subroutine findl_new (txy, level, tmin, tmax)
Function/Subroutine Documentation
subroutine aarrow (dimension (nxx,nxx) xpp, dimension (nxx,nxx) ypp, dimension (nxx,nxx) zpp, dimension(nxx,nxx) xvec, dimension(nxx,nxx) yvec, dimension(nxx,nxx) zvec, nxx)
Definition at line 1343 of file postnek5.f.
References alpha, arow3p(), cmult(), cross(), dotprod(), i, j, norm3d(), and sub2().
subroutine advcell (RC, SC, logical IFEDGB, logical IFCRN, IEDGC, VAL, dimension(ncol,ncol) WRK, NCOL, ICEL, JCEL, JCEL0)
Definition at line 507 of file postnek5.f.
References fndrr(), i, i0, j, and mod1().
subroutine arow3np (x, y, z, dxbar, dybar, dzbar, sarrow)
Definition at line 2335 of file postnek5.f.
References cmult(), color, cross(), draw3(), i, move3(), norm3d(), penw(), and scale().
subroutine arow3p (x, y, z, dxbar, dybar, dzbar, dimension(3) vecp, sarrow)
Definition at line 1399 of file postnek5.f.
References cmult(), color, cross(), draw3(), i, move3(), norm3d(), penw(), and scale().
subroutine beginpp ()
Definition at line 835 of file postnek5.f.
References ifill().
subroutine border (dimension(1) xpp, dimension(1) ypp, dimension(1) zpp, logical, dimension(4) ifcrv, nxx_IN, logical ifnx)
Definition at line 1489 of file postnek5.f.
References color, draw3(), i, j, mapgl1(), move3(), and rzero().
subroutine contour (val, dimension(ncol,ncol) wrk, logical, dimension(4) ifcrv, ncol, jrow1, jrow2, ktr)
Definition at line 281 of file postnek5.f.
References advcell(), fndrr(), izero(), and lfalse().
subroutine ctrscan (logical ifok, dimension(n) wrk, dimension(n) r, dimension(n) rxvr, nxvr, n)
Definition at line 655 of file postnek5.f.
References i, and n.
subroutine draw_circ1 (x3, y3, z3, r)
Definition at line 2426 of file postnek5.f.
References drawc(), i, movec(), n, xiso(), xscr(), yiso(), and yscr().
subroutine draw_circu (x3, y3, z3, r, u, sc, l)
Definition at line 2246 of file postnek5.f.
References blank(), drawc(), gwrite(), i, movec(), n, xiso(), and yiso().
subroutine drwmsh ()
Definition at line 1718 of file postnek5.f.
References color, draw3(), i, j, mapgl1(), move3(), nx, nz, and rzero().
subroutine drwmsh2 ()
Definition at line 1787 of file postnek5.f.
References color, draw_circ1(), gencen(), i, j, map_gll_2_gl(), nx, nz, prs(), rad_circ(), and rer().
subroutine drwmsh3 ()
Definition at line 2178 of file postnek5.f.
References color, draw_circu(), gencen(), i, j, nx, nz, prs(), and rer().
subroutine evalsc2 (x0, dimension(1) scal, dimension(3) rrl)
Definition at line 753 of file postnek5.f.
References hlegn(), i, j, and nx.
subroutine findl_new (txy, level, tmin, tmax)
Definition at line 2537 of file postnek5.f.
subroutine fndrr (rc, r0, r1, v0, v1, v)
Definition at line 803 of file postnek5.f.
subroutine heatc (dimension(nx,ny) tpp, dimension(nx,ny) xpp, dimension(nx,ny) ypp, dimension(nx,ny) zpp, logical, dimension(4) ifcrv, ktr)
Definition at line 31 of file postnek5.f.
References color, contour(), ctrscan(), draw3(), i, izero(), mapglr(), move3(), nx, pltcntr(), prs(), rzero(), setix(), sort(), and swap().
subroutine heatf (dimension(nx,ny) tpp, dimension(nx,ny) xpp, dimension(nx,ny) ypp, dimension(nx,ny) zpp, logical, dimension(4) ifcrv, inrm)
Definition at line 864 of file postnek5.f.
References color, cross(), draw3(), findl(), findl_new(), i, j, mapglg(), mapglr(), move3(), norm3d(), nx, prs(), setix(), shift(), and sub3().
logical function ifin (VAL)
Definition at line 815 of file postnek5.f.
subroutine lfalse (logical, dimension(1) ifa, n)
Definition at line 856 of file postnek5.f.
References i, and n.
subroutine map_gll_2_gl (ugl, mx, ugll, nx, if3d)
Definition at line 2494 of file postnek5.f.
References copy(), fd_weights_full(), map_tnsr(), nx, transpose(), zwgl(), and zwgll().
subroutine mapgl1 (dimension(1) xf, dimension(1) xgl, mxx, mx)
Definition at line 1576 of file postnek5.f.
References mxm(), prs(), and setix().
subroutine mapglg (dimension(mxx,mxx) xmap, dimension(mx,mx) ymap, real, dimension(mxx,mx,2) intrp, mxx, mx, dimension(1) wrk)
Definition at line 2136 of file postnek5.f.
References mxm(), and setixg().
subroutine mapglr (dimension(mxx,mxx) xmap, dimension(mx,mx) ymap, real, dimension(mxx,mx,2) intrp, mxx, mx, dimension(1) wrk)
Definition at line 1613 of file postnek5.f.
References mxm(), and setix().
subroutine mapglr2 (dimension(mxx,mxx) xmap, dimension(mx,mx) ymap, real, dimension(mxx,mx,2) intrp, mxx, mx, r1, r2, s1, s2, dimension(1) wrk)
Definition at line 1658 of file postnek5.f.
References mxm(), and setix2().
subroutine minmax (xmn, xmx, dimension(1) x, n)
Definition at line 845 of file postnek5.f.
References i, and n.
subroutine nekplanar ()
Definition at line 1848 of file postnek5.f.
References getfld(), glmax(), glmin(), nx, nz, prs(), and reiii().
subroutine pltcntr (dimension(nx,ny) xpp, dimension(nx,ny) ypp, dimension(nx,ny) zpp, val, ktr)
Definition at line 695 of file postnek5.f.
References beginpp(), color, endp(), evalsc2(), fillp(), icolor1(), move(), nx, vdraw3(), xiso(), and yiso().
subroutine setix (real, dimension(mxx,mx,2) intrp, mxx, mx, real, dimension(mxx) wrk)
Definition at line 1641 of file postnek5.f.
References i, and igllm().
subroutine setix2 (real, dimension(mxx,mx,2) intrp, mxx, mx, r1, r2, s1, s2, real, dimension(mxx) wrk)
Definition at line 1693 of file postnek5.f.
References i, igllmt(), and transpose().
subroutine setixg (real, dimension(mxx,mx,2) intrp, mxx, mx, real, dimension(mxx) wrk)
Definition at line 2164 of file postnek5.f.
References igllm(), and zwgll().
subroutine setrstp (ivec)
Definition at line 1061 of file postnek5.f.
References blank(), prs(), rerrr(), res(), and setrstp_act().
subroutine setrstp_act (ivec, XPT1, YPT1, ZPT1, XNRM1, YNRM1, ZNRM1)
Definition at line 1103 of file postnek5.f.
References cross(), decod(), dmin, dotprod(), i, j, list, mod1(), norm3d(), nx, nz, prs(), rerrr(), rzero(), and sub3().
subroutine setrstp_set (ivec, XPT1, YPT1, ZPT1)
Definition at line 1952 of file postnek5.f.
References cross(), decod(), dmin, dotprod(), i, j, list, mod1(), norm3d(), nx, nz, prs(), rerrr(), res(), rzero(), and sub3().