KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/postnek2a.f File Reference
postnek2a.f File Reference
Functions/Subroutines
subroutine particle_paths
subroutine out_xpos (xpos, i)
subroutine rk4pp (wnew, w, t, dt, n)
subroutine compute_fp (vel, xpos, t_str)
subroutine get_coef (coef, t, t0, t1, t2, t3)
subroutine get_part (isel)
Function/Subroutine Documentation
subroutine compute_fp (real, dimension(3) vel, real, dimension(3) xpos, t_str)
Definition at line 127 of file postnek2a.f.
References evalsc(), findre(), get_coef(), i, j, nx, and nz.
subroutine get_coef (real, dimension(0:3) coef, t, t0, t1, t2, t3)
Definition at line 212 of file postnek2a.f.
References i, and j.
subroutine get_part (isel)
Definition at line 233 of file postnek2a.f.
References i, j, and prs().
subroutine out_xpos (real, dimension(3) xpos, i)
Definition at line 80 of file postnek2a.f.
References drawc(), i, movec(), xisom(), and yisom().
subroutine particle_paths ()
Definition at line 2 of file postnek2a.f.
References color, copy(), get_part(), getfld(), nx, nz, out_xpos(), prs(), reiii(), and rk4pp().
subroutine rk4pp (real, dimension(1) wnew, real, dimension(1) w, real t, real dt, n)
Definition at line 94 of file postnek2a.f.
References add2s2(), add3s2(), compute_fp(), copy(), and n.