KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/subs.f File Reference
subs.f File Reference
Functions/Subroutines
subroutine sort (A, IND, N)
subroutine swap (A, W, IND, N)
subroutine iswap (A, W, IND, N)
subroutine chswap (A, W, L, IND, N)
subroutine ljust (STRING)
subroutine capit (LETTRS, N)
subroutine parse (LINES, ARGS, IA)
subroutine blank (STRING, N)
subroutine cadd2 (A, B, C, N)
subroutine cadd (A, B, N)
subroutine cmult (A, B, N)
subroutine chcopy (A, B, N)
function ltrunc (STRING, L)
subroutine roots (XVAL, NROOTS, FTARGT, F, N)
subroutine vsqrt (A, N)
subroutine vcnvert (A, N)
subroutine convert (T)
subroutine deltmp
function ilmin (A, N)
function ilmax (A, N)
function vlmax (A, N)
function vlamax (A, N)
function iglsum (A, N)
function iglmin (A, N)
function iglmax (A, N)
function ivlmax (A, N)
function glmax (A, N)
function vlmin (A, N)
function glmin (A, N)
function mod1 (I, N)
integer function indx1 (S1, S2, L2)
integer function nindx1 (S1, S2, L2)
subroutine isort (a, ind, n)
subroutine sortit (a, ind, n)
subroutine add3s12 (x, y, cy, z, cz, n)
subroutine add3s2 (x, y, z, c, n)
subroutine cmult2 (x, y, c, n)
subroutine add2s1 (x, y, c, n)
subroutine add2s2 (x, y, c, n)
function glsc2 (x, y, n)
function vlsum (x, n)
function glsc1 (x, n)
subroutine irank (A, IND, N)
subroutine rank (A, IND, N)
subroutine col3 (A, B, C, N)
subroutine subcol3 (A, B, C, N)
subroutine addcol3 (A, B, C, N)
subroutine addcol4 (A, B, C, D, N)
subroutine subcol4 (A, B, C, D, N)
subroutine izero (IA, N)
subroutine rzero (A, N)
subroutine vdot (DOT, U1, U2, U3, V1, V2, V3, N)
subroutine invcol2 (A, B, N)
subroutine copy (A, B, N)
subroutine icopy (A, B, N)
subroutine sub2 (A, B, N)
subroutine sub3 (C, A, B, N)
subroutine add3 (C, A, B, N)
subroutine add2 (A, B, N)
function almin (A, N)
function almax (A, N)
subroutine iint (in, n)
subroutine irank_vec (ind, nn, a, m, n, key, nkey, aa)
subroutine cfill (a, b, n)
subroutine ifill (a, b, n)
subroutine semhat (a, b, c, d, dp, jp, z, n, w)
subroutine generalev (a, b, lam, n, w)
Function/Subroutine Documentation
subroutine add2 (real, dimension(n) A, real, dimension(n) B, N)
Definition at line 950 of file subs.f.
References i, and n.
subroutine add2s1 (real, dimension(1) x, real, dimension(1) y, real c, n)
Definition at line 695 of file subs.f.
References i, and n.
subroutine add2s2 (real, dimension(1) x, real, dimension(1) y, real c, n)
Definition at line 704 of file subs.f.
References i, and n.
subroutine add3 (real, dimension(1) C, real, dimension(1) A, real, dimension(1) B, N)
Definition at line 943 of file subs.f.
References i, and n.
subroutine add3s12 (real, dimension(1) x, real, dimension(1) y, real cy, real, dimension(1) z, real cz, n)
Definition at line 668 of file subs.f.
References i, and n.
subroutine add3s2 (real, dimension(1) x, real, dimension(1) y, real, dimension(1) z, real c, n)
Definition at line 677 of file subs.f.
References i, and n.
subroutine addcol3 (real, dimension(n) A, real, dimension(n) B, real, dimension(n) C, N)
Definition at line 862 of file subs.f.
References i, and n.
subroutine addcol4 (real, dimension(n) A, real, dimension(n) B, real, dimension(n) C, real, dimension(n) D, N)
Definition at line 869 of file subs.f.
References i, and n.
function almax (real, dimension(n) A, N)
Definition at line 972 of file subs.f.
References i, and n.
function almin (real, dimension(n) A, N)
Definition at line 957 of file subs.f.
References i, and n.
subroutine blank (character*1, dimension(n) STRING, N)
Definition at line 206 of file subs.f.
References i, and n.
subroutine cadd (dimension(1) A, B, N)
Definition at line 224 of file subs.f.
References i, and n.
subroutine cadd2 (dimension(1) A, dimension(1) B, C, N)
Definition at line 217 of file subs.f.
References i, and n.
subroutine capit (character, dimension(n) LETTRS, N)
Definition at line 144 of file subs.f.
References i, and n.
subroutine cfill (real, dimension(1) a, real b, n)
Definition at line 1060 of file subs.f.
References i, and n.
subroutine chcopy (character*1, dimension(1) A, character*1, dimension(1) B, N)
Definition at line 238 of file subs.f.
References i, and n.
subroutine chswap (character*1, dimension(l,1) A, character*1, dimension(l,1) W, L, integer, dimension(1) IND, N)
Definition at line 100 of file subs.f.
References j, and n.
subroutine cmult (dimension(1) A, B, N)
Definition at line 231 of file subs.f.
References i, and n.
subroutine cmult2 (real, dimension(1) x, real, dimension(1) y, real c, n)
Definition at line 686 of file subs.f.
References i, and n.
subroutine col3 (real, dimension(n) A, real, dimension(n) B, real, dimension(n) C, N)
Definition at line 848 of file subs.f.
References i, and n.
subroutine convert (T)
Definition at line 310 of file subs.f.
References ione().
subroutine copy (real, dimension(n) A, real, dimension(n) B, N)
Definition at line 915 of file subs.f.
References i, and n.
subroutine deltmp ()
Definition at line 378 of file subs.f.
References blank().
subroutine generalev (real, dimension(n,n) a, real, dimension(n,n) b, real, dimension(n) lam, n, real, dimension(n,n) w)
Definition at line 1128 of file subs.f.
References exitt(), n, outmat(), and ssygv().
function glmax (dimension(n) A, N)
Definition at line 476 of file subs.f.
References glmax(), i, and n.
function glmin (dimension(n) A, N)
Definition at line 496 of file subs.f.
References glmin(), i, and n.
function glsc1 (real, dimension(1) x, n)
Definition at line 739 of file subs.f.
References i, and n.
function glsc2 (real, dimension(1) x, real, dimension(1) y, n)
Definition at line 713 of file subs.f.
References glsc2(), i, and n.
subroutine icopy (integer, dimension(1) A, integer, dimension(1) B, N)
Definition at line 922 of file subs.f.
References i, and n.
subroutine ifill (integer, dimension(1) a, integer b, n)
Definition at line 1067 of file subs.f.
References i, and n.
function iglmax (integer, dimension(n) A, N)
Definition at line 456 of file subs.f.
References i, iglmax(), and n.
function iglmin (integer, dimension(n) A, N)
Definition at line 446 of file subs.f.
References i, iglmin(), and n.
function iglsum (integer, dimension(n) A, N)
Definition at line 436 of file subs.f.
References i, iglsum(), and n.
subroutine iint (integer, dimension(1) in, n)
Definition at line 988 of file subs.f.
References i, and n.
function ilmax (integer, dimension(n) A, N)
Definition at line 406 of file subs.f.
References i, and n.
function ilmin (integer, dimension(n) A, N)
Definition at line 396 of file subs.f.
References i, and n.
integer function indx1 (character*80 S1, character*80 S2, L2)
Definition at line 521 of file subs.f.
References i, and indx1().
subroutine invcol2 (real, dimension(1) A, real, dimension(1) B, N)
Definition at line 908 of file subs.f.
References i, and n.
subroutine irank (integer, dimension(1) A, integer, dimension(1) IND, N)
Definition at line 751 of file subs.f.
References i, j, and n.
subroutine irank_vec (integer, dimension(n) ind, nn, integer, dimension(m,n) a, m, n, integer, dimension(nkey) key, nkey, integer, dimension(m) aa)
Definition at line 996 of file subs.f.
References i, icopy(), irank(), ituple_sort(), and n.
subroutine isort (integer, dimension(1) a, integer, dimension(1) ind, n)
Definition at line 560 of file subs.f.
References i, j, and n.
subroutine iswap (integer, dimension(1) A, integer, dimension(1) W, integer, dimension(1) IND, N)
Definition at line 83 of file subs.f.
References j, and n.
function ivlmax (integer, dimension(n) A, N)
Definition at line 466 of file subs.f.
References i, ivlmax(), and n.
subroutine izero (dimension(1) IA, N)
Definition at line 883 of file subs.f.
References i, ia, and n.
subroutine ljust (character*1, dimension(80) STRING)
Definition at line 121 of file subs.f.
References i, and j.
function ltrunc (character*1, dimension(l) STRING, L)
Definition at line 246 of file subs.f.
References i, and ltrunc().
function mod1 (I, N)
Definition at line 506 of file subs.f.
References i, mod1(), n, and prs().
integer function nindx1 (character*80 S1, character*80 S2, L2)
Definition at line 539 of file subs.f.
References i.
subroutine parse (character, dimension(70) LINES, character, dimension(10,5) ARGS, IA)
Definition at line 158 of file subs.f.
References capit(), i, ia, and j.
subroutine rank (dimension(1) A, dimension(1) IND, N)
Definition at line 800 of file subs.f.
References i, j, and n.
subroutine roots (dimension(2,n) XVAL, NROOTS, FTARGT, dimension(0:n) F, N)
Definition at line 265 of file subs.f.
References i, and n.
subroutine rzero (dimension(1) A, N)
Definition at line 889 of file subs.f.
References i, and n.
subroutine semhat (real, dimension(0:n,0:n) a, real, dimension(0:n) b, real, dimension(0:n,0:n) c, real, dimension(0:n,0:n) d, real, dimension(0:n,1:n-1) dp, real, dimension(0:n,1:n-1) jp, real, dimension(0:n) z, n, real, dimension(0:1) w)
Definition at line 1074 of file subs.f.
References fd_weights_full(), i, j, n, rzero(), and zwgll().
subroutine sort (dimension(1) A, dimension(1) IND, N)
Definition at line 18 of file subs.f.
References i, j, and n.
subroutine sortit (real, dimension(1) a, integer, dimension(1) ind, n)
Definition at line 614 of file subs.f.
References i, j, and n.
subroutine sub2 (real, dimension(1) A, real, dimension(1) B, N)
Definition at line 929 of file subs.f.
References i, and n.
subroutine sub3 (real, dimension(1) C, real, dimension(1) A, real, dimension(1) B, N)
Definition at line 936 of file subs.f.
References i, and n.
subroutine subcol3 (real, dimension(n) A, real, dimension(n) B, real, dimension(n) C, N)
Definition at line 855 of file subs.f.
References i, and n.
subroutine subcol4 (real, dimension(n) A, real, dimension(n) B, real, dimension(n) C, real, dimension(n) D, N)
Definition at line 876 of file subs.f.
References i, and n.
subroutine swap (dimension(1) A, dimension(1) W, dimension(1) IND, N)
Definition at line 66 of file subs.f.
References j, and n.
subroutine vcnvert (real*4, dimension(1) A, N)
Definition at line 302 of file subs.f.
References convert(), i, and n.
subroutine vdot (dimension(n) DOT, dimension(n) U1, dimension(n) U2, dimension(n) U3, dimension(n) V1, dimension(n) V2, dimension(n) V3, N)
Definition at line 895 of file subs.f.
References dot(), i, and n.
function vlamax (dimension(n) A, N)
Definition at line 426 of file subs.f.
References i, n, and vlamax().
function vlmax (dimension(n) A, N)
Definition at line 416 of file subs.f.
References i, n, and vlmax().
function vlmin (dimension(n) A, N)
Definition at line 486 of file subs.f.
References i, n, and vlmin().
function vlsum (real, dimension(1) x, n)
Definition at line 729 of file subs.f.
References i, n, and vlsum().
subroutine vsqrt (dimension(1) A, N)
Definition at line 294 of file subs.f.
References i, and n.