KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/postnek9.f File Reference
postnek9.f File Reference
Functions/Subroutines
subroutine mltiplt2
subroutine mltiplt
subroutine setstate (is, ifdrm, ir, ic, il, ii, name)
subroutine savstate (is, ns, ir, ic, il, ii, name)
subroutine genstrv
subroutine vcross (x1, x2, x3, y1, y2, y3, z1, z2, z3, n)
subroutine vnorms (x1, x2, x3, alpha, n)
subroutine dudrst (dudr, duds, dudt, U)
subroutine mltiplt3
subroutine grab_window_pix (iname, l, iframe)
subroutine auto_size_pixel_window
subroutine quick_get_box (xmse1, ymse1, xmse2, ymse2)
subroutine mltiplt4
subroutine particle_paths
subroutine out_xpos (xpos, i)
subroutine rk4pp (wnew, w, t, dt, n)
subroutine compute_fp (vel, xpos, t_str)
subroutine get_coef (coef, t, t0, t1, t2, t3)
subroutine get_part (isel)
subroutine mltiplt_all
subroutine scrn_out
subroutine userchk
Function/Subroutine Documentation
subroutine auto_size_pixel_window ()
Definition at line 1004 of file postnek9.f.
References i, j, quick_get_box(), scoordx(), scoordy(), xscr(), and yscr().
subroutine compute_fp (real, dimension(3) vel, real, dimension(3) xpos, t_str)
Definition at line 1400 of file postnek9.f.
References evalsc(), findre(), get_coef(), i, j, nx, and nz.
subroutine dudrst (dimension(nx,ny,nz) dudr, dimension(nx,ny,nz) duds, dimension(nx,ny,nz) dudt, dimension(nx,ny,nz) U)
Definition at line 786 of file postnek9.f.
References mxm(), nx, and nz.
subroutine genstrv ()
Definition at line 572 of file postnek9.f.
References alpha, decod(), dudrst(), i, j, list, mxm(), n, nx, nz, sortl(), vcross(), and vnorms().
subroutine get_coef (real, dimension(0:3) coef, t, t0, t1, t2, t3)
Definition at line 1507 of file postnek9.f.
References i, and j.
subroutine get_part (isel)
Definition at line 1528 of file postnek9.f.
References i, j, and prs().
subroutine grab_window_pix (character*1, dimension(1) iname, l, iframe)
Definition at line 902 of file postnek9.f.
References blank(), chcopy(), and terminate_string().
subroutine mltiplt ()
Definition at line 188 of file postnek9.f.
References clear(), drmesh(), getfld(), grab_window_pix(), i, mouse(), plotit(), prs(), setstate(), and setwrk().
subroutine mltiplt2 ()
Definition at line 18 of file postnek9.f.
References auto_size_pixel_window(), blank(), clear(), drfram(), drmesh(), getfld(), grab_window_pix(), gswrit(), hard(), heject(), i, mouse(), nohard(), nx, plotit(), prs(), rei(), reiii(), savstate(), setstate(), setwrk(), and userchk().
subroutine mltiplt3 ()
Definition at line 802 of file postnek9.f.
References blank(), getfld(), grab_window_pix(), mouse(), prs(), rei(), reii(), setwrk(), and vtk_out_xyz_sc().
subroutine mltiplt4 ()
Definition at line 1093 of file postnek9.f.
References blank(), getfld(), grab_window_pix(), mouse(), prs(), rei(), reii(), setwrk(), and vtk_out_xyz_sc().
subroutine mltiplt_all ()
Definition at line 1567 of file postnek9.f.
References blank(), getfld(), grab_window_pix(), mouse(), prs(), rei(), reii(), setwrk(), and vtk_out_all().
subroutine out_xpos (real, dimension(3) xpos, i)
Definition at line 1342 of file postnek9.f.
References drawc(), i, movec(), xisom(), and yisom().
subroutine particle_paths ()
Definition at line 1208 of file postnek9.f.
References color, copy(), get_part(), getfld(), glmax(), glmin(), nx, nz, out_xpos(), prs(), prsii(), reiii(), and rk4pp().
subroutine quick_get_box (xmse1, ymse1, xmse2, ymse2)
Definition at line 1047 of file postnek9.f.
References drawc(), movec(), prs(), and quickscan_xy().
subroutine rk4pp (real, dimension(1) wnew, real, dimension(1) w, real t, real dt, n)
Definition at line 1356 of file postnek9.f.
References add2s2(), add3s2(), compute_fp(), copy(), and n.
subroutine savstate (is, ns, ir, ic, il, ii, character*4 name)
Definition at line 398 of file postnek9.f.
References copy(), icopy(), list, prs(), and rei().
subroutine scrn_out ()
Definition at line 1672 of file postnek9.f.
References auto_size_pixel_window(), clear(), drmesh(), grab_window_pix(), hard(), mltiplt(), nohard(), plotit(), post_reset_window(), prs(), and res().
subroutine setstate (is, logical ifdrm, ir, ic, il, ii, character*4 name)
Definition at line 229 of file postnek9.f.
References copy(), icopy(), list, and setgraph().
subroutine userchk ()
Definition at line 1729 of file postnek9.f.
References nx, and nz.
subroutine vcross (dimension(1) x1, dimension(1) x2, dimension(1) x3, dimension(1) y1, dimension(1) y2, dimension(1) y3, dimension(1) z1, dimension(1) z2, dimension(1) z3, n)
Definition at line 760 of file postnek9.f.
References i, and n.
subroutine vnorms (dimension(1) x1, dimension(1) x2, dimension(1) x3, alpha, n)
Definition at line 773 of file postnek9.f.
References alpha, i, and n.