KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/postnek3.f File Reference
postnek3.f File Reference
Functions/Subroutines
subroutine pfiles
subroutine setwrk (ifdoin)
subroutine plotph (io)
subroutine drawel (iel)
subroutine pfiles2
subroutine gtlines
subroutine arrow4s (x, y, z, dx, dy, dz)
subroutine draw3s (x3, y3, z3)
subroutine move3s (x3, y3, z3)
subroutine redraw
subroutine resetdw
subroutine modwrk
subroutine vloga (x, n)
subroutine coef2
subroutine find_lam2 (lam2, lam, aa, w, miter, ndim, ierr)
subroutine muller (x2, x2i, x1i, x0i, tol, tolf, kiter, ierr)
subroutine muller2 (x2, x2i, x1i, x0i, tol, tolf, kiter, l, ierr)
function ff (x)
subroutine lin_combo
subroutine new_vortex
subroutine vel_grad_tens (vel, i, ie)
subroutine quadratic (x1, x2, a, b, c, ierr)
subroutine vol_int (sum, vol, g)
subroutine vol_int2 (sum, vol, g, h)
function zbrent (X1, X2, TOL, TOLF, iter)
subroutine find_lam3 (lam2, lam, aa, w, ndim, ierr)
subroutine cubic (xo, ai1, ai2, ai3, ierr)
subroutine vfiles
subroutine vfiles2
subroutine plotphv
subroutine rms_avg
subroutine rms_uvw
subroutine filter_fld
subroutine filterqdif (v, f, nx, nz, nel, w1, w2, ft, if3d, dmax)
subroutine legendre_poly (L, x, N)
subroutine build_new_filter (filt, zpts, nx, kut, wght, nid)
subroutine ident (a, n)
subroutine ctr_intp3 (u)
subroutine ctr_intp5 (u)
subroutine get_prof_vars
subroutine get_profile (xo, yo, zo, dxabc, dyabc, dzabc, dabc)
subroutine comp_vorticity
subroutine magnitude (wk, v1, v2, v3)
subroutine gtlines_box_x
subroutine gtlines_box_z
subroutine filterqstd (v, f, nx, nz, nel, w1, w2, ft, if3d, dmax)
subroutine filterq (v, f, nx, nz, nel, w1, w2, ft, if3d, dmax)
Function/Subroutine Documentation
subroutine arrow4s (x, y, z, dx, dy, dz)
Definition at line 989 of file postnek3.f.
References color, draw3s(), move3s(), penw(), and scale().
subroutine build_new_filter (real, dimension(nx,nx) filt, real, dimension(nx) zpts, nx, kut, wght, nid)
Definition at line 2708 of file postnek3.f.
References copy(), exitt(), gaujordf(), ident(), j, legendre_poly(), mxm(), n, nx, and transpose().
subroutine coef2 ()
Definition at line 1194 of file postnek3.f.
References geom1().
subroutine comp_vorticity ()
Definition at line 3110 of file postnek3.f.
References copy(), dsavg(), dudxyz(), nx, nz, and sub3().
subroutine ctr_intp3 (real, dimension(0:1) u)
Definition at line 2803 of file postnek3.f.
subroutine ctr_intp5 (real, dimension(0:1) u)
Definition at line 2812 of file postnek3.f.
subroutine cubic (real, dimension(3) xo, real ai1, real ai2, real ai3, ierr)
Definition at line 2213 of file postnek3.f.
References rzero().
subroutine draw3s (x3, y3, z3)
Definition at line 1015 of file postnek3.f.
References drawc(), xiso(), and yiso().
subroutine drawel (iel)
Definition at line 737 of file postnek3.f.
References beginb(), color, drawc(), endp(), fillp(), getpts(), gwrite(), i, iabs, j, movec(), and rzero().
function ff (x)
Definition at line 1518 of file postnek3.f.
References ax().
subroutine filter_fld ()
Definition at line 2574 of file postnek3.f.
References alpha, build_new_filter(), filterq(), glmax(), nx, and nz.
subroutine filterq (real, dimension(nx*nx*nz,nel) v, real, dimension(nx,nx) f, nx, nz, nel, real, dimension(1) w1, real, dimension(1) w2, real, dimension(nx,nx) ft, logical if3d, dmax)
Definition at line 3445 of file postnek3.f.
References dmax, filterqdif(), filterqstd(), nx, and nz.
subroutine filterqdif (real, dimension(nx*nx*nz,nel) v, real, dimension(nx,nx) f, nx, nz, nel, real, dimension(1) w1, real, dimension(1) w2, real, dimension(nx,nx) ft, logical if3d, dmax)
Definition at line 2642 of file postnek3.f.
References copy(), dmax, i, j, mxm(), nx, nz, sub2(), transpose(), and vlamax().
subroutine filterqstd (real, dimension(nx*nx*nz,nel) v, real, dimension(nx,nx) f, nx, nz, nel, real, dimension(1) w1, real, dimension(1) w2, real, dimension(nx,nx) ft, logical if3d, dmax)
Definition at line 3395 of file postnek3.f.
References copy(), dmax, i, j, mxm(), nx, nz, sub3(), transpose(), and vlamax().
subroutine find_lam2 (real lam2, real, dimension(3) lam, real, dimension(3,3) aa, real, dimension(3,3) w, miter, ndim, ierr)
Definition at line 1215 of file postnek3.f.
References i, muller2(), quadratic(), and zbrent().
subroutine find_lam3 (real lam2, real, dimension(3) lam, real, dimension(3,3) aa, real, dimension(3,3) w, ndim, ierr)
Definition at line 2141 of file postnek3.f.
References cubic(), quadratic(), and sortit().
subroutine get_prof_vars ()
Definition at line 2824 of file postnek3.f.
References blank(), chcopy(), i, and menu().
subroutine get_profile (xo, yo, zo, dxabc, dyabc, dzabc, dabc)
Definition at line 2963 of file postnek3.f.
References ctr_intp3(), ctr_intp5(), i, izero(), and rzero().
subroutine gtlines ()
Definition at line 913 of file postnek3.f.
References blank(), prs(), and res().
subroutine gtlines_box_x ()
Definition at line 3185 of file postnek3.f.
References glmax(), glmin(), nx, nz, prs(), rei(), and res().
subroutine gtlines_box_z ()
Definition at line 3279 of file postnek3.f.
References glmax(), glmin(), nx, nz, prs(), rei(), and res().
subroutine ident (real, dimension(n,n) a, n)
Definition at line 2790 of file postnek3.f.
References i, and n.
subroutine legendre_poly (real, dimension(0:n) L, x, N)
Definition at line 2692 of file postnek3.f.
References j, and n.
subroutine lin_combo ()
Definition at line 1546 of file postnek3.f.
References add2s1(), cmult2(), getfld(), glmax(), glmin(), nx, nz, prs(), prsi(), rei(), and rerr().
subroutine magnitude (real, dimension(1) wk, real, dimension(1) v1, real, dimension(1) v2, real, dimension(1) v3)
Definition at line 3162 of file postnek3.f.
References i, nx, and nz.
subroutine modwrk ()
Definition at line 1117 of file postnek3.f.
References glmax(), glmin(), nx, nz, prs(), and vloga().
subroutine move3s (x3, y3, z3)
Definition at line 1036 of file postnek3.f.
References movec(), xiso(), and yiso().
subroutine muller (x2, x2i, x1i, x0i, tol, tolf, kiter, ierr)
Definition at line 1342 of file postnek3.f.
References ff(), and i.
subroutine muller2 (x2, x2i, x1i, x0i, tol, tolf, kiter, l, ierr)
Definition at line 1442 of file postnek3.f.
References ff(), and quadratic().
subroutine new_vortex ()
Definition at line 1649 of file postnek3.f.
References alpha, build_new_filter(), copy(), dsavg(), filterq(), find_lam2(), find_lam3(), i, j, nx, nz, prsi(), rzero(), ssyev(), and vel_grad_tens().
subroutine pfiles ()
Definition at line 19 of file postnek3.f.
References get_prof_vars(), getpt(), gtlines(), gtlines_box_z(), pfiles2(), plotph(), prs(), rei(), and setwrk().
subroutine pfiles2 ()
Definition at line 846 of file postnek3.f.
References plotph(), resetdw(), and setwrk().
subroutine plotph (io)
Definition at line 454 of file postnek3.f.
References arrow4s(), color, dotprod(), draw3s(), drawc(), get_profile(), i, move3s(), movec(), norm3d(), and prs().
subroutine plotphv ()
Definition at line 2390 of file postnek3.f.
References arow3np(), color, draw3s(), move3s(), and norm3d().
subroutine quadratic (x1, x2, a, b, c, ierr)
Definition at line 1869 of file postnek3.f.
subroutine redraw ()
Definition at line 1057 of file postnek3.f.
References color, drawc(), i, movec(), scrudmp(), xiso(), and yiso().
subroutine resetdw ()
Definition at line 1107 of file postnek3.f.
subroutine rms_avg ()
Definition at line 2476 of file postnek3.f.
References add2s2(), col3(), getfld(), nx, nz, prs(), prsi(), rei(), and vsqrt().
subroutine rms_uvw ()
Definition at line 2528 of file postnek3.f.
References add2s2(), col3(), getfld(), nx, nz, prs(), prsi(), and rei().
subroutine setwrk (logical ifdoin)
Definition at line 125 of file postnek3.f.
References add2(), addcol3(), col3(), comp_vorticity(), copy(), dsavg(), dudxyz(), filter_fld(), genstrv(), i, magnitude(), new_vortex(), nx, nz, procmap(), prs(), rzero(), setwrks(), strfct(), userf(), and vol_int().
subroutine vel_grad_tens (real, dimension(1) vel, i, ie)
Definition at line 1792 of file postnek3.f.
References addcol3(), col3(), i, invcol2(), mxm(), nx, and nz.
subroutine vfiles ()
Definition at line 2272 of file postnek3.f.
References getpt(), gtlines(), plotphv(), prs(), rei(), setwrk(), and vfiles2().
subroutine vfiles2 ()
Definition at line 2334 of file postnek3.f.
References plotphv(), resetdw(), and setwrk().
subroutine vloga (dimension(1) x, n)
Definition at line 1171 of file postnek3.f.
References i, and n.
subroutine vol_int (sum, vol, real, dimension(1) g)
Definition at line 1922 of file postnek3.f.
References nx, nz, and prsr().
subroutine vol_int2 (sum, vol, real, dimension(1) g, real, dimension(1) h)
Definition at line 1974 of file postnek3.f.
References nx, nz, and prsr().
function zbrent (X1, X2, TOL, TOLF, iter)
Definition at line 2029 of file postnek3.f.
References ff(), and zbrent().