KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/postnek5a.f File Reference
postnek5a.f File Reference
Functions/Subroutines
subroutine cutting_plane
subroutine getplane (nsect, stepval)
subroutine new_contour (nsect, stepval, is)
subroutine compute_contour_variable (w, ldw, n)
subroutine map_interp (w_interp, ldwi, w_gll, ldwg, n_gll, nxx)
subroutine find_contour (wpp, ldw, w_gll, ldw_gll, n_gll, KTR, nxx)
subroutine dumpfile
subroutine contour_setup
subroutine outmat (a, m, n, ch3)
subroutine out_mat (a, m, n, ch3)
subroutine pltcntr2 (wpp, ldw, n_gll, val, ktr)
subroutine out_contour (nsect, stepval, is)
subroutine set_progress_variable (is)
subroutine prog_theta (is)
subroutine sort_prog
function dot_prod (x1, y1, z1, x2, y2, z2)
subroutine setcvol
subroutine cvolume
subroutine setrstv (XPT1, YPT1, ZPT1, IVEC, IFSAME)
subroutine strplt (ifnewplt)
subroutine genfem
Function/Subroutine Documentation
subroutine compute_contour_variable (real, dimension(ldw,0:15) w, ldw, n)
Definition at line 254 of file postnek5a.f.
References i, and n.
subroutine contour_setup ()
Definition at line 372 of file postnek5a.f.
References i, and prs().
subroutine cutting_plane ()
Definition at line 3 of file postnek5a.f.
References contour_setup(), getplane(), i, j, menu(), new_contour(), out_contour(), prs(), and vdraw3().
subroutine cvolume ()
Definition at line 802 of file postnek5a.f.
References i, setcvol(), setrstv(), and tem().
function dot_prod (x1, y1, z1, x2, y2, z2)
Definition at line 749 of file postnek5a.f.
subroutine dumpfile ()
Definition at line 357 of file postnek5a.f.
subroutine find_contour (real, dimension (ldw ,0:n_gll) wpp, ldw, real, dimension(ldw_gll,0:n_gll) w_gll, ldw_gll, n_gll, KTR, nxx)
Definition at line 299 of file postnek5a.f.
References contour(), glmax(), glmin(), and pltcntr2().
subroutine genfem ()
Definition at line 1093 of file postnek5a.f.
References copy(), i, icopy(), irank(), iswap(), j, locglob(), nx, nz, prs(), and swap().
subroutine getplane (nsect, stepval)
Definition at line 64 of file postnek5a.f.
References arrow4(), prs(), rei(), rer(), rerrr(), and res().
subroutine map_interp (real, dimension(ldwi,0:n_gll) w_interp, ldwi, real, dimension (ldwg,0:n_gll) w_gll, ldwg, n_gll, nxx)
Definition at line 271 of file postnek5a.f.
References i, mapglr(), nx, and setix().
subroutine new_contour (nsect, stepval, is)
Definition at line 126 of file postnek5a.f.
References compute_contour_variable(), decod(), find_contour(), glmax(), glmin(), hard(), i, map_interp(), nohard(), nx, nz, and sortl().
subroutine out_contour (nsect, stepval, is)
Definition at line 510 of file postnek5a.f.
References i, j, and set_progress_variable().
subroutine out_mat (real, dimension(m,n) a, m, n, character*3 ch3)
Definition at line 441 of file postnek5a.f.
References i, j, and n.
subroutine outmat (real, dimension(m,n) a, m, n, character*3 ch3)
Definition at line 420 of file postnek5a.f.
References i, j, and n.
subroutine pltcntr2 (dimension(ldw,0:15) wpp, ldw, n_gll, val, ktr)
Definition at line 454 of file postnek5a.f.
References beginpp(), evalsc2(), and vdraw3().
subroutine prog_theta (is)
Definition at line 595 of file postnek5a.f.
References arrow4(), dot_prod(), draw_circ1(), i, menu(), and prs().
subroutine set_progress_variable (is)
Definition at line 548 of file postnek5a.f.
References i, prog_theta(), prs(), res(), and sort_prog().
subroutine setcvol ()
Definition at line 759 of file postnek5a.f.
References menu(), prs(), rei(), rerr(), and rerrr().
subroutine setrstv (XPT1, YPT1, ZPT1, IVEC, logical IFSAME)
Definition at line 849 of file postnek5a.f.
References cross(), decod(), dmin, dotprod(), i, j, list, mod1(), norm3d(), nx, nz, prs(), rerrr(), rzero(), and sub3().
subroutine sort_prog ()
Definition at line 712 of file postnek5a.f.
References i, and j.
subroutine strplt (logical ifnewplt)
Definition at line 1039 of file postnek5a.f.
References blank(), draw3(), i, ltrunc(), move3(), prs(), and res().