KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/iolib.f File Reference
iolib.f File Reference
Functions/Subroutines
subroutine prs (S)
subroutine pri (I)
subroutine prr (R)
subroutine prii (I1, I2)
subroutine priii (I1, I2, I3)
subroutine prrrr (R1, R2, R3)
subroutine prrr (R1, R2)
subroutine prsi (S, I)
subroutine pris (I, S)
subroutine prsrrr (S, r1, r2, r3)
subroutine prsrr (S, r1, r2)
subroutine prsr (S, R)
subroutine prsii (S, I, J)
subroutine prsiii (s, i1, i2, i3)
subroutine prsiv (s, i1, i2, i3, i4)
subroutine prsir (S, I, R)
subroutine prsis (S1, I, S2)
subroutine prsrs (S1, R, S2)
subroutine res (S1, N)
subroutine reiii (i, j, k)
subroutine reii (I, j)
subroutine rei (I)
subroutine rer (R1)
subroutine rerr (R1, R2)
subroutine rerrr (R1, R2, R3)
subroutine rerrrr (R1, R2, R3, R4)
subroutine putsold (S, NCHARS)
subroutine getsold (S)
subroutine setgraph (ifgraf)
Function/Subroutine Documentation
subroutine getsold (character S)
Definition at line 580 of file iolib.f.
subroutine pri (I)
Definition at line 83 of file iolib.f.
References i, and prs().
subroutine prii (I1, I2)
Definition at line 103 of file iolib.f.
References prs().
subroutine priii (I1, I2, I3)
Definition at line 112 of file iolib.f.
References prs().
subroutine pris (I, character, dimension(*) S)
Definition at line 164 of file iolib.f.
References i, j, and prs().
subroutine prr (R)
Definition at line 93 of file iolib.f.
References prs().
subroutine prrr (R1, R2)
Definition at line 131 of file iolib.f.
References prs().
subroutine prrrr (R1, R2, R3)
Definition at line 121 of file iolib.f.
References prs().
subroutine prs (character, dimension(*) S)
Definition at line 55 of file iolib.f.
References chcopy(), i, and j.
subroutine prsi (character, dimension(*) S, I)
Definition at line 141 of file iolib.f.
References i, j, and prs().
subroutine prsii (character, dimension(*) S, I, J)
Definition at line 253 of file iolib.f.
References i, j, and prs().
subroutine prsiii (character, dimension(*) s, i1, i2, i3)
Definition at line 275 of file iolib.f.
References prs().
subroutine prsir (character, dimension(*) S, I, R)
Definition at line 326 of file iolib.f.
References i, and prs().
subroutine prsis (character, dimension(*) S1, I, character, dimension(*) S2)
Definition at line 348 of file iolib.f.
References i, j, and prs().
subroutine prsiv (character, dimension(*) s, i1, i2, i3, i4)
Definition at line 301 of file iolib.f.
References prs().
subroutine prsr (character, dimension(*) S, R)
Definition at line 231 of file iolib.f.
References i, and prs().
subroutine prsrr (character, dimension(*) S, r1, r2)
Definition at line 209 of file iolib.f.
References i, and prs().
subroutine prsrrr (character, dimension(*) S, r1, r2, r3)
Definition at line 187 of file iolib.f.
References i, and prs().
subroutine prsrs (character, dimension(*) S1, R, character, dimension(*) S2)
Definition at line 388 of file iolib.f.
References i, and prs().
subroutine putsold (character, dimension(*) S, NCHARS)
Definition at line 571 of file iolib.f.
References i.
subroutine rei (I)
Definition at line 491 of file iolib.f.
References i, prs(), and res().
subroutine reii (I, j)
Definition at line 475 of file iolib.f.
References i, j, prs(), and res().
subroutine reiii (i, j, k)
Definition at line 459 of file iolib.f.
References i, j, prs(), and res().
subroutine rer (R1)
Definition at line 507 of file iolib.f.
References prs(), and res().
subroutine rerr (R1, R2)
Definition at line 523 of file iolib.f.
References prs(), and res().
subroutine rerrr (R1, R2, R3)
Definition at line 539 of file iolib.f.
References prs(), and res().
subroutine rerrrr (R1, R2, R3, R4)
Definition at line 555 of file iolib.f.
References prs(), and res().
subroutine res (character, dimension(*) S1, N)
Definition at line 434 of file iolib.f.
References gets(), i, and n.
subroutine setgraph (logical ifgraf)
Definition at line 592 of file iolib.f.