KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/xinterface.f File Reference
xinterface.f File Reference
Functions/Subroutines
program mainf
subroutine reader (VALUE, IERR)
subroutine openf (IUNIT, FILE, STATUS, ITYPE, IERR)
subroutine findfl (SESION, OLDVER)
subroutine mouse (XMOUSE, YMOUSE, BUTTON)
subroutine move (X, Y)
subroutine draw (X, Y)
subroutine movesc (X, Y)
subroutine drawsc (X, Y)
subroutine beginp (X1, Y1)
subroutine beginb (X1, Y1)
subroutine gnable
subroutine gindis
subroutine sgvis (iseg, ivisibility)
subroutine heject
subroutine clsseg
subroutine opnseg (ISEG)
subroutine delseg (ISEG)
subroutine penw (IWIDTH)
subroutine scroll (ILINES)
subroutine rubber
subroutine offrub
subroutine gwrite (X, Y, SIZE, STRING)
subroutine gswrit (X, Y, SIZE, STRING)
subroutine devini (DEVICE)
subroutine devex
subroutine endp
subroutine fillp (ICOLOR)
subroutine clear
subroutine cleara
subroutine color (Incolor)
subroutine clrmap (TYPE)
function scoordx (worldx)
function scoordy (worldy)
function scoordx_inv (pix)
function scoordy_inv (pix)
Function/Subroutine Documentation
subroutine beginb (X1, Y1)
Definition at line 239 of file xinterface.f.
References ifill(), move(), and movec().
subroutine beginp (X1, Y1)
Definition at line 218 of file xinterface.f.
References ifill(), move(), and movec().
subroutine clear ()
Definition at line 457 of file xinterface.f.
subroutine cleara ()
Definition at line 471 of file xinterface.f.
subroutine clrmap (character*4 TYPE)
Definition at line 550 of file xinterface.f.
References color, and i.
subroutine clsseg ()
Definition at line 319 of file xinterface.f.
subroutine color (Incolor)
Definition at line 477 of file xinterface.f.
References i.
subroutine delseg (ISEG)
Definition at line 327 of file xinterface.f.
subroutine devex ()
Definition at line 424 of file xinterface.f.
subroutine devini (DEVICE)
Definition at line 399 of file xinterface.f.
subroutine draw (X, Y)
Definition at line 161 of file xinterface.f.
References drawsc(), xscr(), and yscr().
subroutine drawsc (X, Y)
Definition at line 192 of file xinterface.f.
References ifill(), scoordx(), and scoordy().
subroutine endp ()
Definition at line 434 of file xinterface.f.
References ifill().
subroutine fillp (ICOLOR)
Definition at line 449 of file xinterface.f.
References iabs.
subroutine findfl (SESION, OLDVER)
Definition at line 67 of file xinterface.f.
subroutine gindis ()
Definition at line 262 of file xinterface.f.
subroutine gnable ()
Definition at line 258 of file xinterface.f.
subroutine gswrit (X, Y, SIZE, character, dimension(100) STRING)
Definition at line 372 of file xinterface.f.
References i, movesc(), prs(), scoordx(), and scoordy().
subroutine gwrite (X, Y, SIZE, character, dimension(100) STRING)
Definition at line 362 of file xinterface.f.
References gswrit(), xscr(), and yscr().
subroutine heject ()
Definition at line 270 of file xinterface.f.
References chcopy(), initps(), openf(), and penw().
program mainf ()
Definition at line 1 of file xinterface.f.
subroutine mouse (XMOUSE, YMOUSE, BUTTON)
Definition at line 71 of file xinterface.f.
References filter(), prs(), prsr(), res(), xphy(), and yphy().
subroutine move (X, Y)
Definition at line 156 of file xinterface.f.
References movesc(), xscr(), and yscr().
subroutine movesc (X, Y)
Definition at line 166 of file xinterface.f.
References ifill(), scoordx(), and scoordy().
subroutine offrub ()
Definition at line 358 of file xinterface.f.
subroutine openf (IUNIT, character*(*) FILE, character*(*) STATUS, ITYPE, IERR)
Definition at line 35 of file xinterface.f.
References i.
subroutine opnseg (ISEG)
Definition at line 323 of file xinterface.f.
subroutine penw (IWIDTH)
Definition at line 331 of file xinterface.f.
subroutine reader (VALUE, IERR)
Definition at line 18 of file xinterface.f.
subroutine rubber ()
Definition at line 354 of file xinterface.f.
function scoordx (worldx)
Definition at line 664 of file xinterface.f.
function scoordx_inv (pix)
Definition at line 676 of file xinterface.f.
function scoordy (worldy)
Definition at line 670 of file xinterface.f.
function scoordy_inv (pix)
Definition at line 684 of file xinterface.f.
subroutine scroll (ILINES)
Definition at line 350 of file xinterface.f.
subroutine sgvis (iseg, ivisibility)
Definition at line 266 of file xinterface.f.