KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/postnek2.f File Reference
postnek2.f File Reference
Functions/Subroutines
subroutine interp (val, xex, yex, zex, ieo, tt, ierr)
subroutine evalsc (x0, scal, rrl, inew)
subroutine findl (txy, level, tmin, tmax)
subroutine histry
subroutine setann
subroutine ezxy (x, y, n, icode)
subroutine value
subroutine values_std
subroutine nekprofil
subroutine ezxyp (dum, pingrl, icode)
subroutine drbox (iel, k)
subroutine stream
subroutine lagrnge (dtl, il, intdir, dtprim, dcirc, KS)
subroutine setlgr
subroutine updatel (xxl, rrl, dt0, il, ie, intdir, dtprim, dcirc, KS)
subroutine diamda (xx, yy)
subroutine intcrc (totdt, nstcnt, x00, y00, z00, stptol, strtol)
subroutine project (v0, v1, v2, iset)
subroutine cross (v1, v2, v3)
subroutine norm3d (v1)
subroutine calcerr (tt, iferr)
subroutine extrap (est, e, nx, ny, nz, ie)
subroutine strfct (psi)
subroutine strem2 (psi, ie)
subroutine spint (p, s, wght, n)
logical function ifcond (xyzlg)
subroutine factor_solve (x, a, lda, b, n)
subroutine sgefa (a, lda, n, ipvt, info)
subroutine sgesl (a, lda, n, ipvt, b, job)
subroutine blas_saxpy (n, sa, sx, incx, sy, incy)
subroutine streamline_draw (w, iostep, dti, intdir, nstep, iclr, n)
subroutine set_dt (dt_sti, w0, w1, kstep, m, n, eps, dti)
subroutine compute_f (f, xpos, t_str)
subroutine out_w (xpos, t_str, dt_str, dto, i, nstep, iclr)
subroutine rk4 (wnew, w, t, dt, n)
function some_norm (e, u, v, n)
subroutine u_fld_values_in (x_in, y_in, z_in, ie, ierr)
subroutine set_u_fld_values_out
subroutine u_fld_values
function user_flow (xi, yi, zi)
function user_temp (x, y, z)
function blasius (Y, DELTA, U)
subroutine dump_xyz_fld
subroutine terminate_string (s, n)
subroutine streamline_draw_2d_close (w, iostep, dti, intdir, nstep, iclr, n, iflast)
subroutine close_w (wc, w1, dt1, wo, to, k, nsteps, n)
logical function if_close (w, w0, t, dt, i, nsteps, iflast)
subroutine find_y_flag (iemin)
subroutine find_vertex (ix, iy, iz, e, xx, x, y, z, nel, nx, ny, nz, if3d)
subroutine find_vertexa (ix, iy, iz, ie, xx, x, y, z, nel, nx, ny, nz, if3d)
subroutine set_curve (ifcurv)
subroutine findr_new (rrl, xxl, ie, iguess, ierr)
subroutine pf_read (v, n)
subroutine pf_write (v, n)
subroutine findre (ie_min, rl, xl, rminmax, ierr)
subroutine findr (rrl, xxl, ie, iguess, ierr)
subroutine values
Function/Subroutine Documentation
subroutine blas_saxpy (integer n, real sa, real, dimension(1) sx, integer incx, real, dimension(1) sy, integer incy)
Definition at line 2364 of file postnek2.f.
function blasius (Y, DELTA, U)
Definition at line 3164 of file postnek2.f.
References i, spline(), splint(), and vel().
subroutine calcerr (tt, iferr)
Definition at line 1830 of file postnek2.f.
subroutine close_w (real, dimension(4) wc, real, dimension(4) w1, dt1, real, dimension(4) wo, to, k, nsteps, n)
Definition at line 3450 of file postnek2.f.
References n, and rk4().
subroutine compute_f (real, dimension(3) f, real, dimension(3) xpos, t_str)
Definition at line 2619 of file postnek2.f.
References evalsc(), findre(), nx, and nz.
subroutine cross (dimension(3) v1, dimension(3) v2, dimension(3) v3)
Definition at line 1799 of file postnek2.f.
subroutine diamda (xx, yy)
Definition at line 1581 of file postnek2.f.
References drawc(), and movec().
subroutine drbox (iel, k)
Definition at line 899 of file postnek2.f.
References color, draw3(), i, j, move3(), nx, and nz.
subroutine dump_xyz_fld ()
Definition at line 3204 of file postnek2.f.
References blank(), byte_close, byte_open, byte_write, i, nx, nz, prs(), and terminate_string().
subroutine evalsc (x0, dimension(1) scal, dimension(3) rrl, inew)
Definition at line 119 of file postnek2.f.
References copy(), hlegn(), i, j, nx, and nz.
subroutine extrap (est, dimension(1) e, nx, ny, nz, ie)
Definition at line 1838 of file postnek2.f.
subroutine ezxy (real, dimension(n) x, real, dimension(n) y, n, icode)
Definition at line 421 of file postnek2.f.
References drawsc(), gswrit(), hard(), i, movesc(), n, nohard(), openf(), prr(), prs(), and res().
subroutine ezxyp (real, dimension(nx,ny,nz,nel) dum, pingrl, icode)
Definition at line 873 of file postnek2.f.
subroutine factor_solve (real, dimension(n) x, real, dimension(lda,n) a, lda, real, dimension(n) b, n)
Definition at line 2126 of file postnek2.f.
References copy(), n, sgefa(), and sgesl().
subroutine find_vertex (ix, iy, iz, integer e, real, dimension(3) xx, real, dimension(nx,ny,nz,nel) x, real, dimension(nx,ny,nz,nel) y, real, dimension(nx,ny,nz,nel) z, nel, nx, ny, nz, logical if3d)
Definition at line 3537 of file postnek2.f.
References dmin, i, j, nx, and nz.
subroutine find_vertexa (ix, iy, iz, ie, real, dimension(3) xx, real, dimension(nx,ny,nz,nel) x, real, dimension(nx,ny,nz,nel) y, real, dimension(nx,ny,nz,nel) z, nel, nx, ny, nz, logical if3d)
Definition at line 3581 of file postnek2.f.
References dmin, i, j, nx, and nz.
subroutine find_y_flag (iemin)
Definition at line 3510 of file postnek2.f.
References glmax(), n, nx, nz, and vlmin().
subroutine findl (txy, level, tmin, tmax)
Definition at line 182 of file postnek2.f.
subroutine findr (dimension(3) rrl, dimension(3) xxl, ie, iguess, ierr)
Definition at line 3818 of file postnek2.f.
References copy(), dist2(), evalsc(), factor_solve(), mod1(), nx, and nz.
subroutine findr_new (dimension(3) rrl, dimension(3) xxl, ie, iguess, ierr)
Definition at line 3665 of file postnek2.f.
References set_curve().
subroutine findre (ie_min, real, dimension(3) rl, real, dimension(3) xl, rminmax, ierr)
Definition at line 3712 of file postnek2.f.
References findr(), rmax(), and vlamax().
subroutine histry ()
Definition at line 203 of file postnek2.f.
References clear(), drfram(), drmesh(), ezxy(), gwrite(), hard(), heject(), i, j, mouse(), nohard(), nx, nz, prs(), prsi(), prsis(), res(), xphy(), and yphy().
logical function if_close (real, dimension(4) w, real, dimension(4) w0, real t, real dt, i, nsteps, logical iflast)
Definition at line 3480 of file postnek2.f.
References i.
logical function ifcond (dimension(3) xyzlg)
Definition at line 2113 of file postnek2.f.
subroutine intcrc (totdt, nstcnt, x00, y00, z00, stptol, strtol)
Definition at line 1592 of file postnek2.f.
References evalsc(), lagrnge(), nx, nz, prs(), rr, vlmax(), and vlmin().
subroutine interp (val, xex, yex, zex, ieo, real, dimension(1) tt, ierr)
Definition at line 3 of file postnek2.f.
References coef(), diamd3(), evalsc(), findr(), findre(), locglob(), nx, nz, and prs().
subroutine lagrnge (dtl, il, intdir, dtprim, dcirc, KS)
Definition at line 1393 of file postnek2.f.
References findre(), rr, and updatel().
subroutine nekprofil ()
Definition at line 824 of file postnek2.f.
References draw3(), drawc(), ezxyp(), hard(), move3(), movec(), nohard(), prs(), and setwrk().
subroutine norm3d (dimension(3) v1)
Definition at line 1812 of file postnek2.f.
References dotprod().
subroutine out_w (real, dimension(3) xpos, t_str, dt_str, dto, i, nstep, iclr)
Definition at line 2647 of file postnek2.f.
References color, drawc(), evalsc(), findre(), i, icolor1(), movec(), nx, nz, tmp, xisom(), and yisom().
subroutine pf_read (real, dimension(1) v, n)
Definition at line 3696 of file postnek2.f.
References n.
subroutine pf_write (real, dimension(1) v, n)
Definition at line 3704 of file postnek2.f.
References n.
subroutine project (dimension(3) v0, dimension(3) v1, dimension(3) v2, iset)
Definition at line 1728 of file postnek2.f.
References add2(), copy(), cross(), dotprod(), j, norm3d(), prs(), xiso(), and yiso().
subroutine rk4 (real, dimension(1) wnew, real, dimension(1) w, real t, real dt, n)
Definition at line 2680 of file postnek2.f.
References add2s2(), add3s2(), compute_f(), copy(), and n.
subroutine set_curve (logical, dimension(nelm) ifcurv)
Definition at line 3631 of file postnek2.f.
References i.
subroutine set_dt (dt_sti, real, dimension(1) w0, real, dimension(1) w1, kstep, m, n, eps, dti)
Definition at line 2551 of file postnek2.f.
References glmax(), glmin(), glsc1(), n, nx, nz, some_norm(), and sub3().
subroutine set_u_fld_values_out ()
Definition at line 2902 of file postnek2.f.
References blank(), byte_open, byte_write, i, prs(), and terminate_string().
subroutine setann ()
Definition at line 403 of file postnek2.f.
References gwrite(), hard(), i, mouse(), nohard(), prs(), and res().
subroutine setlgr ()
Definition at line 1426 of file postnek2.f.
subroutine sgefa (real, dimension(lda,1) a, integer lda, integer n, integer, dimension(1) ipvt, integer info)
Definition at line 2142 of file postnek2.f.
References saxpy(), and sscal().
subroutine sgesl (real, dimension(lda,1) a, integer lda, integer n, integer, dimension(1) ipvt, real, dimension(1) b, integer job)
Definition at line 2246 of file postnek2.f.
References saxpy().
function some_norm (real, dimension(1) e, real, dimension(1) u, real, dimension(1) v, n)
Definition at line 2713 of file postnek2.f.
References j, and n.
subroutine spint (dimension(n,n) p, dimension(n) s, dimension(n) wght, n)
Definition at line 2084 of file postnek2.f.
References hleg(), i, j, n, and rzero().
subroutine stream ()
Definition at line 931 of file postnek2.f.
References coef(), color, cross(), drawc(), findre(), iabs, j, lagrnge(), locglob(), mouse(), movec(), norm3d(), nx, nz, openf(), project(), prs(), prsis(), rei(), res(), rr, setlgr(), setwrk(), streamline_draw(), streamline_draw_2d_close(), xisom(), and yisom().
subroutine streamline_draw (real, dimension(3) w, iostep, dti, intdir, nstep, iclr, n)
Definition at line 2412 of file postnek2.f.
References add3s12(), copy(), findre(), n, out_w(), prsrrr(), rk4(), and set_dt().
subroutine streamline_draw_2d_close (real, dimension(3) w, iostep, dti, intdir, nstep, iclr, n, logical iflast)
Definition at line 3282 of file postnek2.f.
References add3s12(), copy(), findre(), n, out_w(), prsrrr(), rk4(), and set_dt().
subroutine strem2 (real, dimension(1) psi, ie)
Definition at line 1984 of file postnek2.f.
References i, j, mxm(), nx, nz, and rzero().
subroutine strfct (real, dimension(1) psi)
Definition at line 1845 of file postnek2.f.
References cadd(), find_y_flag(), glmax(), glmin(), i, j, nx, nz, rzero(), spint(), and strem2().
subroutine terminate_string (character*1, dimension(n) s, n)
Definition at line 3264 of file postnek2.f.
References chcopy(), ltrunc(), and n.
subroutine u_fld_values ()
Definition at line 2951 of file postnek2.f.
References byte_close, byte_write, i, i0, mod1(), nx, nz, pf_read(), pf_write(), prs(), prsii(), rer(), set_u_fld_values_out(), u_fld_values_in(), user_flow(), and user_temp().
subroutine u_fld_values_in (real, dimension(1) x_in, real, dimension(1) y_in, real, dimension(1) z_in, ie, ierr)
Definition at line 2740 of file postnek2.f.
References blank(), byte_close, byte_open, byte_read, byte_reverse, chcopy(), glmax(), glmin(), i, ltrunc(), nx, nz, prs(), res(), and terminate_string().
subroutine updatel (dimension(3) xxl, dimension(3) rrl, dt0, il, ie, intdir, dtprim, dcirc, KS)
Definition at line 1442 of file postnek2.f.
References evalsc(), nx, nz, and project().
function user_flow (xi, yi, zi)
Definition at line 3139 of file postnek2.f.
function user_temp (x, y, z)
Definition at line 3157 of file postnek2.f.
subroutine value ()
Definition at line 492 of file postnek2.f.
References prs(), prsr(), and prsrs().
subroutine values ()
Definition at line 4133 of file postnek2.f.
References color, find_vertex(), find_vertexa(), i, j, mouse(), nx, nz, openf(), prs(), prsi(), prsii(), prsiii(), prsrr(), prsrrr(), rei(), rerr(), rerrr(), res(), u_fld_values(), value(), and xdot().
subroutine values_std ()
Definition at line 535 of file postnek2.f.
References color, diamd3(), find_vertex(), find_vertexa(), g3writ(), glmax(), glmin(), hard(), i, j, mouse(), nx, nz, openf(), prs(), prsi(), prsii(), prsiii(), prsrr(), prsrrr(), rei(), rerr(), rerrr(), res(), u_fld_values(), value(), and xdot().