KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/legend.f File Reference
legend.f File Reference
Functions/Subroutines
subroutine legend (zpts, wght, n)
subroutine dudxyz (DU, U, RM1, SM1, TM1, JM1, IEL)
subroutine igllmt (IT12, Z1, Z2, NZ1, NZ2, ND1, ND2)
real function hleg (I, ZZ, ZLEG, NZZ)
subroutine hlegn (H, ZH, ZLEG, NZZ)
subroutine dermat (D, DT, PN, Z, NZ, NZD)
real function pnz (Z, NZ)
real function pnd (Z, NZ)
subroutine genpn1 (PN, Z, NZ)
Function/Subroutine Documentation
subroutine dermat (real, dimension(nzd,nzd) D, real, dimension(nzd,nzd) DT, real, dimension(nzd) PN, real, dimension(nzd) Z, NZ, NZD)
Definition at line 155 of file legend.f.
References i, j, n, and nz.
subroutine dudxyz (real, dimension (nx,ny,nz) DU, real, dimension (nx,ny,nz,1) U, real, dimension (nx,ny,nz,1) RM1, real, dimension (nx,ny,nz,1) SM1, real, dimension (nx,ny,nz,1) TM1, real, dimension (nx,ny,nz,1) JM1, IEL)
Definition at line 13 of file legend.f.
References addcol3(), col3(), invcol2(), mxm(), nx, and nz.
subroutine genpn1 (real, dimension(1) PN, real, dimension(1) Z, NZ)
Definition at line 207 of file legend.f.
References i, n, and nz.
real function hleg (I, ZZ, real, dimension(nzz) ZLEG, NZZ)
Definition at line 89 of file legend.f.
References i, pnd(), and pnz().
subroutine hlegn (real, dimension(1) H, ZH, real, dimension(1) ZLEG, NZZ)
Definition at line 117 of file legend.f.
References i, pnd(), and pnz().
subroutine igllmt (real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, NZ1, NZ2, ND1, ND2)
Definition at line 67 of file legend.f.
References hlegn(), and i.
subroutine legend (zpts, wght, n)
Definition at line 3 of file legend.f.
References n, and zwgll().
real function pnd (Z, NZ)
Definition at line 189 of file legend.f.
References n, and nz.
real function pnz (Z, NZ)
Definition at line 177 of file legend.f.
References n, and nz.