KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/mxm44f2.f File Reference
mxm44f2.f File Reference
Functions/Subroutines
subroutine mxm (a, n1, b, n2, c, n3)
subroutine fmxm (a, n1, b, n2, c, n3)
subroutine mxmf2 (A, N1, B, N2, C, N3)
subroutine mxf1 (a, n1, b, n2, c, n3)
subroutine mxf2 (a, n1, b, n2, c, n3)
subroutine mxf3 (a, n1, b, n2, c, n3)
subroutine mxf4 (a, n1, b, n2, c, n3)
subroutine mxf5 (a, n1, b, n2, c, n3)
subroutine mxf6 (a, n1, b, n2, c, n3)
subroutine mxf7 (a, n1, b, n2, c, n3)
subroutine mxf8 (a, n1, b, n2, c, n3)
subroutine mxf9 (a, n1, b, n2, c, n3)
subroutine mxf10 (a, n1, b, n2, c, n3)
subroutine mxf11 (a, n1, b, n2, c, n3)
subroutine mxf12 (a, n1, b, n2, c, n3)
subroutine mxf13 (a, n1, b, n2, c, n3)
subroutine mxf14 (a, n1, b, n2, c, n3)
subroutine mxf15 (a, n1, b, n2, c, n3)
subroutine mxf16 (a, n1, b, n2, c, n3)
subroutine mxf17 (a, n1, b, n2, c, n3)
subroutine mxf18 (a, n1, b, n2, c, n3)
subroutine mxf19 (a, n1, b, n2, c, n3)
subroutine mxf20 (a, n1, b, n2, c, n3)
subroutine mxf21 (a, n1, b, n2, c, n3)
subroutine mxf22 (a, n1, b, n2, c, n3)
subroutine mxf23 (a, n1, b, n2, c, n3)
subroutine mxf24 (a, n1, b, n2, c, n3)
subroutine mxm44_0 (a, m, b, k, c, n)
subroutine mxm44_2 (a, m, b, k, c, n)
Function/Subroutine Documentation
subroutine fmxm (real, dimension(n1,n2) a, n1, real, dimension(n2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 34 of file mxm44f2.f.
References mxmf2().
subroutine mxf1 (real, dimension(n1,1) a, n1, real, dimension(1,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 145 of file mxm44f2.f.
References i, and j.
subroutine mxf10 (real, dimension(n1,10) a, n1, real, dimension(10,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 289 of file mxm44f2.f.
References i, and j.
subroutine mxf11 (real, dimension(n1,11) a, n1, real, dimension(11,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 310 of file mxm44f2.f.
References i, and j.
subroutine mxf12 (real, dimension(n1,12) a, n1, real, dimension(12,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 332 of file mxm44f2.f.
References i, and j.
subroutine mxf13 (real, dimension(n1,13) a, n1, real, dimension(13,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 355 of file mxm44f2.f.
References i, and j.
subroutine mxf14 (real, dimension(n1,14) a, n1, real, dimension(14,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 379 of file mxm44f2.f.
References i, and j.
subroutine mxf15 (real, dimension(n1,15) a, n1, real, dimension(15,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 404 of file mxm44f2.f.
References i, and j.
subroutine mxf16 (real, dimension(n1,16) a, n1, real, dimension(16,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 430 of file mxm44f2.f.
References i, and j.
subroutine mxf17 (real, dimension(n1,17) a, n1, real, dimension(17,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 457 of file mxm44f2.f.
References i, and j.
subroutine mxf18 (real, dimension(n1,18) a, n1, real, dimension(18,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 485 of file mxm44f2.f.
References i, and j.
subroutine mxf19 (real, dimension(n1,19) a, n1, real, dimension(19,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 514 of file mxm44f2.f.
References i, and j.
subroutine mxf2 (real, dimension(n1,2) a, n1, real, dimension(2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 157 of file mxm44f2.f.
References i, and j.
subroutine mxf20 (real, dimension(n1,20) a, n1, real, dimension(20,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 544 of file mxm44f2.f.
References i, and j.
subroutine mxf21 (real, dimension(n1,21) a, n1, real, dimension(21,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 575 of file mxm44f2.f.
References i, and j.
subroutine mxf22 (real, dimension(n1,22) a, n1, real, dimension(22,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 607 of file mxm44f2.f.
References i, and j.
subroutine mxf23 (real, dimension(n1,23) a, n1, real, dimension(23,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 640 of file mxm44f2.f.
References i, and j.
subroutine mxf24 (real, dimension(n1,24) a, n1, real, dimension(24,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 674 of file mxm44f2.f.
References i, and j.
subroutine mxf3 (real, dimension(n1,3) a, n1, real, dimension(3,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 170 of file mxm44f2.f.
References i, and j.
subroutine mxf4 (real, dimension(n1,4) a, n1, real, dimension(4,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 184 of file mxm44f2.f.
References i, and j.
subroutine mxf5 (real, dimension(n1,5) a, n1, real, dimension(5,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 199 of file mxm44f2.f.
References i, and j.
subroutine mxf6 (real, dimension(n1,6) a, n1, real, dimension(6,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 215 of file mxm44f2.f.
References i, and j.
subroutine mxf7 (real, dimension(n1,7) a, n1, real, dimension(7,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 232 of file mxm44f2.f.
References i, and j.
subroutine mxf8 (real, dimension(n1,8) a, n1, real, dimension(8,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 250 of file mxm44f2.f.
References i, and j.
subroutine mxf9 (real, dimension(n1,9) a, n1, real, dimension(9,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 269 of file mxm44f2.f.
References i, and j.
subroutine mxm (real, dimension(n1,n2) a, n1, real, dimension(n2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 3 of file mxm44f2.f.
References mxmf2().
subroutine mxm44_0 (real, dimension(m,k) a, m, real, dimension(k,n) b, k, real, dimension(m,n) c, n)
Definition at line 709 of file mxm44f2.f.
References i, j, and n.
subroutine mxm44_2 (real, dimension(m,2) a, m, real, dimension(2,n) b, k, real, dimension(m,n) c, n)
Definition at line 1144 of file mxm44f2.f.
References i, j, and n.
subroutine mxmf2 (real, dimension(n1,n2) A, N1, real, dimension(n2,n3) B, N2, real, dimension(n1,n3) C, N3)
Definition at line 65 of file mxm44f2.f.
References mxf1(), mxf10(), mxf11(), mxf12(), mxf13(), mxf14(), mxf15(), mxf16(), mxf17(), mxf18(), mxf19(), mxf2(), mxf20(), mxf21(), mxf22(), mxf23(), mxf24(), mxf3(), mxf4(), mxf5(), mxf6(), mxf7(), mxf8(), mxf9(), and mxm44_0().