KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/postnek7.f File Reference
postnek7.f File Reference
Functions/Subroutines
subroutine srfplot
subroutine temsrf
subroutine srflabl (IERR)
subroutine extpln2 (XX, XPLOT, NOUT, IPLN, Idum)
subroutine setwrks
subroutine dblank (STRING, N)
subroutine sorts (NLSTK)
subroutine getsrf (IERR, mOPEN)
subroutine srfile (IERR, FILE1, JNID, IUNIT, mOPEN)
function realchr (S, L)
function intchr (S, L)
subroutine getnam (FILENM, BASE, mOPEN, JNID)
Function/Subroutine Documentation
subroutine dblank (character*1, dimension(1) STRING, N)
Definition at line 461 of file postnek7.f.
References i, j, and n.
subroutine extpln2 (dimension(1) XX, dimension(nout,1) XPLOT, NOUT, IPLN, Idum)
Definition at line 277 of file postnek7.f.
References nx.
subroutine getnam (character*80 FILENM, character*14 BASE, mOPEN, JNID)
Definition at line 887 of file postnek7.f.
References blank(), chcopy(), indx1(), ione(), j, and ltrunc().
subroutine getsrf (integer IERR, mOPEN)
Definition at line 551 of file postnek7.f.
References blank(), chcopy(), extpln2(), i, indx1(), intchr(), list, nx, nz, prs(), realchr(), rzero(), srfile(), and vrnvert().
function intchr (character*1, dimension(1) S, L)
Definition at line 871 of file postnek7.f.
References j, and prs().
function realchr (character*1, dimension(1) S, L)
Definition at line 855 of file postnek7.f.
References j, and prs().
subroutine setwrks ()
Definition at line 293 of file postnek7.f.
References copy(), dudxyz(), glmax(), glmin(), i, nx, nz, prs(), and rzero().
subroutine sorts (NLSTK)
Definition at line 494 of file postnek7.f.
References blank(), chcopy(), chswap(), decod(), i, icopy(), iswap(), j, list, nx, nz, sort(), and ziso().
subroutine srfile (IERR, character*80 FILE1, JNID, IUNIT, mOPEN)
Definition at line 819 of file postnek7.f.
References getnam(), and prs().
subroutine srflabl (IERR)
Definition at line 142 of file postnek7.f.
References beginb(), drbar(), drcovr(), endp(), fillp(), gwrite(), movesc(), prsrs(), sgvis(), xphy(), and yphy().
subroutine srfplot ()
Definition at line 2 of file postnek7.f.
References clear(), drmesh(), getsrf(), gwrite(), hard(), heject(), nohard(), nx, setwrks(), temsrf(), xphy(), and yphy().
subroutine temsrf ()
Definition at line 44 of file postnek7.f.
References decod(), heatc(), heatf(), i, j, list, nx, nz, penw(), sorts(), and srflabl().