KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/revert.f File Reference
revert.f File Reference
Functions/Subroutines
real *4 function revert (T)
Function/Subroutine Documentation
real*4 function revert (character*4 T)
Definition at line 2 of file revert.f.
References blank(), i, ione(), and irank().