KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/postnek8.f File Reference
postnek8.f File Reference
Functions/Subroutines
subroutine arow3nc (x, y, z, dxbar, dybar, dzbar, sarrowi, jclr)
subroutine selite (nelpf, se_to_face, nfcs, jclr)
subroutine hilitef (iface, ie, icolr)
subroutine hilitev (iface, ie, icolr)
subroutine outline (input, leni, io)
subroutine scanout (string, input, len, infile, outfile)
subroutine out_rea
subroutine get_vert (vertex, nlv)
subroutine face_id (se_to_face, nfctot, vertex, nlv, wrk, tmp_face, nfcs)
subroutine surface_id (nelpf, nfctot, se_to_face, nfcs, vertex, nlv, srfef, srfvt, srfvx, nfc, vtxpt)
subroutine vec_vtx_min (vs, v, vt, m, n, nm, work, nd)
subroutine vec_vtx_sum (vs, v, vt, m, n, nm, work, nd)
subroutine gen_srf_nrm (vn, vx, nd, m)
subroutine surfchk
subroutine remap_xyz (nelpf, nfctot, se_to_face, nfcs, vertex, nlv, srfef, srfvt, srfvx, nfc, vtxpt)
subroutine remap_xyz1
subroutine defect_id (phib, jk, n, srfef, srfvt, srfvx, srfvn, nfc, nd, nvrt, srfnb, phil, phihat, work)
subroutine defect_crct1 (srfef, srfvt, srfvx, srfvn, nfc, nd, nvrt, srfnb, vtxpt, phil, phihat, phib, jk, wrk, n, nelpf, se_to_face, nfcs)
subroutine defect_crct3 (srfef, srfvt, srfvx, srfvn, nfc, nd, nvrt, srfnb, vtxpt, phil, phihat, phib, jk, wrk, n, nelpf, se_to_face, nfcs)
subroutine defect_crct2 (srfef, srfvt, srfvx, srfvn, nfc, nd, nvrt, srfnb, vtxpt, phil, phihat, phib, jk, wrk, n, nelpf, se_to_face, nfcs)
subroutine mesh_smooth
subroutine find_bc_crv (b, nv, cell, nvc, ncell)
subroutine build_adj (ja, ia, n, cell, nvc, ncell, edge, ne, w, wk, ind)
subroutine get_gxyz (nv, cell, nvc, ncell, ww, ind, ierr)
subroutine find_sm_box (b, nv, x0, x1, y0, y1, z0, z1)
subroutine qb (b, n, x, x0, x1)
subroutine find_bd_jac (b, nv, cell, nvc, nel, iebad, nebad)
subroutine chk_jacob (vol, ratio, nebad, iebad, b, xp, yp, zp, cell, nvc)
subroutine chkjac (ierr, JAC, N)
function gs_smooth (x, y, z, b, c, a, ja, ia, n, g, gg, s, eps, icall)
subroutine smoother (cell, nvc, ia, ja, ww, b, g, x0, x1, y0, y1, z0, z1, ss, eps, idpth)
subroutine dilate_el (dxyz, xyz, eps, vol, volo, volm)
function vec_length (v, n)
subroutine angle_fix (dxyz, xyz)
subroutine angle_smooth_el (dxyz, xyz, eps)
subroutine show_plot
subroutine set_mesh (xyz)
subroutine reset_mesh (xyz)
subroutine angle_smoother (cell, nvc, ia, ja, ww, b, g, x0, x1, y0, y1, z0, z1, ein)
subroutine boundary_graph (g, b, ja, ia, n)
subroutine remap_xyz2 (cell, nvc, b)
subroutine build_graph (cell, nvc, ia, ja, ww, b, g, x0, x1, y0, y1, z0, z1)
subroutine build_surface_pointers (cell, ncrnr)
subroutine mean_normal (srfnb, srfvn, srfef, srfvt, srfvx, nfc, nd, nvrt, work)
subroutine set_surf_layer (x0, x1, y0, y1, z0, z1)
subroutine update_surface_layer (ia, ja, b, delta, alpha)
function gs_smooth2 (x, y, z, b, c, xyzn, ja, ia, n, g, gg, s, lam, icall)
Function/Subroutine Documentation
subroutine angle_fix (real, dimension(3,0:3) dxyz, real, dimension(3,0:3) xyz)
Definition at line 2274 of file postnek8.f.
References add2(), cmult(), cross(), norm3d(), rzero(), sub2(), sub3(), and vec_length().
subroutine angle_smooth_el (real, dimension(3,8) dxyz, real, dimension(3,8) xyz, eps)
Definition at line 2331 of file postnek8.f.
References add2(), angle_fix(), cmult(), copy(), i, j, and rzero().
subroutine angle_smoother (integer, dimension(nvc,1) cell, nvc, integer, dimension(1) ia, integer, dimension(1) ja, real, dimension(0:1) ww, integer, dimension(1) b, integer, dimension(1) g, x0, x1, y0, y1, z0, z1, ein)
Definition at line 2435 of file postnek8.f.
References angle_smooth_el(), boundary_graph(), build_adj(), chk_jacob(), dilate_el(), dmax, find_bc_crv(), find_bd_jac(), find_sm_box(), get_gxyz(), glmax(), glmin(), i, izero(), n, and vlamax().
subroutine arow3nc (x, y, z, dxbar, dybar, dzbar, sarrowi, jclr)
Definition at line 3 of file postnek8.f.
References cmult(), color, cross(), draw3(), i, move3(), norm3d(), penw(), and scale().
subroutine boundary_graph (integer, dimension(1) g, integer, dimension(1) b, integer, dimension(1) ja, integer, dimension(1) ia, n)
Definition at line 2561 of file postnek8.f.
References i, ilmax(), j, n, and prsii().
subroutine build_adj (integer, dimension(9) ja, integer, dimension(9) ia, n, integer, dimension(nvc,ncell) cell, nvc, ncell, integer, dimension(2,ne) edge, ne, integer, dimension(2,1) w, integer, dimension(1) wk, integer, dimension(1) ind)
Definition at line 1648 of file postnek8.f.
References i, ituple_s_merge(), and n.
subroutine build_graph (integer, dimension(nvc,1) cell, nvc, integer, dimension(1) ia, integer, dimension(1) ja, real, dimension(0:1) ww, integer, dimension(1) b, integer, dimension(1) g, x0, x1, y0, y1, z0, z1)
Definition at line 2619 of file postnek8.f.
References build_adj(), find_bc_crv(), find_sm_box(), get_gxyz(), izero(), and n.
subroutine build_surface_pointers (integer, dimension(ncrnr,1) cell, ncrnr)
Definition at line 2663 of file postnek8.f.
References face_id(), get_vert(), ilmax(), mean_normal(), and surface_id().
subroutine chk_jacob (real, dimension(1) vol, real, dimension(1) ratio, nebad, integer, dimension(1) iebad, integer, dimension(1) b, real, dimension(1) xp, real, dimension(1) yp, real, dimension(1) zp, integer, dimension(nvc,1) cell, nvc)
Definition at line 1839 of file postnek8.f.
References addcol3(), addcol4(), chkjac(), dgll(), draw3(), hilight2(), i, j, legend(), move3(), mxm(), rmin(), rzero(), subcol3(), subcol4(), vlmax(), vlmin(), and vlsum().
subroutine chkjac (ierr, real, dimension(n) JAC, N)
Definition at line 2003 of file postnek8.f.
References i, and n.
subroutine defect_crct1 (integer, dimension(2,0:1) srfef, integer, dimension(nfc,1) srfvt, real, dimension(nd,nfc,1) srfvx, real, dimension(nd,nfc,1) srfvn, nfc, nd, nvrt, real, dimension(nd,nfc,1) srfnb, real, dimension(nd,nvrt) vtxpt, real, dimension(nfc,1) phil, real, dimension(nfc,1) phihat, real, dimension(1000) phib, integer, dimension (1000) jk, real, dimension (nd,nvrt) wrk, n, nelpf, se_to_face, nfcs)
Definition at line 1020 of file postnek8.f.
References arow3nc(), i, j, mod1(), n, prsi(), refresh2(), res(), rone(), selite(), and vec_vtx_sum().
subroutine defect_crct2 (integer, dimension(2,0:1) srfef, integer, dimension(nfc,1) srfvt, real, dimension(nd,nfc,1) srfvx, real, dimension(nd,nfc,1) srfvn, nfc, nd, nvrt, real, dimension(nd,nfc,1) srfnb, real, dimension(nd,nvrt) vtxpt, real, dimension(nfc,1) phil, real, dimension(nfc,1) phihat, real, dimension(1000) phib, integer, dimension (1000) jk, real, dimension (nd,nvrt) wrk, n, nelpf, se_to_face, nfcs)
Definition at line 1307 of file postnek8.f.
References add2s2(), arow3nc(), copy(), dot(), hilitev(), i, j, mod1(), n, prsi(), prsr(), refresh2(), res(), rone(), selite(), and vec_vtx_sum().
subroutine defect_crct3 (integer, dimension(2,0:1) srfef, integer, dimension(nfc,1) srfvt, real, dimension(nd,nfc,1) srfvx, real, dimension(nd,nfc,1) srfvn, nfc, nd, nvrt, real, dimension(nd,nfc,1) srfnb, real, dimension(nd,nvrt) vtxpt, real, dimension(nfc,1) phil, real, dimension(nfc,1) phihat, real, dimension(1000) phib, integer, dimension (1000) jk, real, dimension (nd,nvrt) wrk, n, nelpf, se_to_face, nfcs)
Definition at line 1111 of file postnek8.f.
References hilitev(), i, j, mod1(), n, prsi(), res(), rone(), and vec_vtx_sum().
subroutine defect_id (real, dimension(1000) phib, integer, dimension (1000) jk, n, integer, dimension(2,0:1) srfef, integer, dimension(nfc,1) srfvt, real, dimension(nd,nfc,1) srfvx, real, dimension(nd,nfc,1) srfvn, nfc, nd, nvrt, real, dimension(nd,nfc,1) srfnb, real, dimension(nfc,1) phil, real, dimension(nfc,1) phihat, real, dimension(nd,nvrt) work)
Definition at line 872 of file postnek8.f.
References arow3nc(), dot(), gen_srf_nrm(), i, invcol2(), iswap(), j, mod1(), n, norm3d(), rone(), sortit(), vec_vtx_min(), and vec_vtx_sum().
subroutine dilate_el (real, dimension(3,8) dxyz, real, dimension(3,8) xyz, eps, vol, volo, volm)
Definition at line 2226 of file postnek8.f.
References i, j, rzero(), and scale().
subroutine face_id (integer, dimension(nfcs,1) se_to_face, nfctot, integer, dimension(nlv,1) vertex, nlv, integer, dimension(1) wrk, integer, dimension(ndim,nfcs,1) tmp_face, nfcs)
Definition at line 488 of file postnek8.f.
References icopy(), irank_vec(), and isort().
subroutine find_bc_crv (integer, dimension(nv) b, nv, integer, dimension(nvc,ncell) cell, nvc, ncell)
Definition at line 1590 of file postnek8.f.
References izero().
subroutine find_bd_jac (integer, dimension(nv) b, nv, integer, dimension(nvc,nel) cell, nvc, nel, integer, dimension(nebad) iebad, nebad)
Definition at line 1824 of file postnek8.f.
References i, and j.
subroutine find_sm_box (integer, dimension(1) b, nv, x0, x1, y0, y1, z0, z1)
Definition at line 1795 of file postnek8.f.
References qb().
subroutine gen_srf_nrm (real, dimension(nd,0:1,0:1) vn, real, dimension(nd,0:1,0:1) vx, nd, m)
Definition at line 662 of file postnek8.f.
References cross(), i, and norm3d().
subroutine get_gxyz (nv, integer, dimension(nvc,1) cell, nvc, ncell, integer, dimension(0:1) ww, integer, dimension(1) ind, ierr)
Definition at line 1723 of file postnek8.f.
References blank(), chcopy(), get_vert(), icopy(), indx1(), and j.
subroutine get_vert (integer, dimension(nlv,nel) vertex, nlv)
Definition at line 440 of file postnek8.f.
References blank(), chcopy(), ilmax(), ilmin(), and indx1().
function gs_smooth (real, dimension(1) x, real, dimension(1) y, real, dimension(1) z, integer, dimension(1) b, real, dimension(1) c, real, dimension(1) a, integer, dimension(1) ja, integer, dimension(1) ia, n, integer, dimension(1) g, gg, s, eps, icall)
Definition at line 2017 of file postnek8.f.
References i, j, n, and scale().
function gs_smooth2 (real, dimension(1) x, real, dimension(1) y, real, dimension(1) z, integer, dimension(1) b, real, dimension(1) c, real, dimension(3,1) xyzn, integer, dimension(1) ja, integer, dimension(1) ia, n, integer, dimension(1) g, gg, s, real lam, icall)
Definition at line 2887 of file postnek8.f.
References i, j, and n.
subroutine hilitef (iface, ie, icolr)
Definition at line 120 of file postnek8.f.
References color, evline(), hlegn(), nx, nz, penw(), and vdraw3a().
subroutine hilitev (iface, ie, icolr)
Definition at line 250 of file postnek8.f.
References hilitef(), and prsiii().
subroutine mean_normal (real, dimension(nd,nfc,1) srfnb, real, dimension(nd,nfc,1) srfvn, integer, dimension(2,0:1) srfef, integer, dimension(nfc,1) srfvt, real, dimension(nd,nfc,1) srfvx, nfc, nd, nvrt, real, dimension(nd,nvrt) work)
Definition at line 2719 of file postnek8.f.
References gen_srf_nrm(), j, norm3d(), and vec_vtx_sum().
subroutine mesh_smooth ()
Definition at line 1456 of file postnek8.f.
References angle_smoother(), i, menu(), nx, nz, prs(), prsrr(), refresh2(), reii(), remap_xyz1(), rerr(), reset_mesh(), set_mesh(), set_surf_layer(), show_plot(), smoother(), vlmax(), and vlmin().
subroutine out_rea ()
Definition at line 294 of file postnek8.f.
References blank(), chcopy(), indx1(), j, outline(), prs(), scanout(), vlmax(), and vlmin().
subroutine outline (character*1, dimension(1) input, leni, io)
Definition at line 256 of file postnek8.f.
References i, and ltrunc().
subroutine qb (integer, dimension(1) b, n, real, dimension(1) x, x0, x1)
Definition at line 1809 of file postnek8.f.
References i, and n.
subroutine remap_xyz (integer, dimension(nfctot) nelpf, nfctot, integer, dimension(nfcs,1) se_to_face, nfcs, integer, dimension(nlv,1) vertex, nlv, integer, dimension(2,0:1) srfef, integer, dimension(nfc,1) srfvt, real, dimension(ndim,nfc,1) srfvx, nfc, real, dimension(ndim,1) vtxpt)
Definition at line 791 of file postnek8.f.
References coef(), gencen(), hilitef(), and mespos().
subroutine remap_xyz1 ()
Definition at line 849 of file postnek8.f.
References coef(), gencen(), and mespos().
subroutine remap_xyz2 (integer, dimension(nvc,1) cell, nvc, integer, dimension(1) b)
Definition at line 2594 of file postnek8.f.
References coef(), gencen(), i, and mespos().
subroutine reset_mesh (real, dimension(3,8,1) xyz)
Definition at line 2418 of file postnek8.f.
References i, ia, and ja.
subroutine scanout (character*80 string, character*1, dimension(1) input, len, integer infile, integer outfile)
Definition at line 268 of file postnek8.f.
References blank(), chcopy(), indx1(), j, and ltrunc().
subroutine selite (integer, dimension(1) nelpf, integer, dimension(nfcs,1) se_to_face, nfcs, jclr)
Definition at line 95 of file postnek8.f.
References coef(), gencen(), hilitef(), mespos(), prsi(), and res().
subroutine set_mesh (real, dimension(3,8,1) xyz)
Definition at line 2402 of file postnek8.f.
References i.
subroutine set_surf_layer (x0, x1, y0, y1, z0, z1)
Definition at line 2752 of file postnek8.f.
References alpha, build_graph(), build_surface_pointers(), out_rea(), prs(), remap_xyz2(), rer(), show_plot(), and update_surface_layer().
subroutine show_plot ()
Definition at line 2387 of file postnek8.f.
References copy(), nx, nz, and plotit().
subroutine smoother (integer, dimension(nvc,1) cell, nvc, integer, dimension(1) ia, integer, dimension(1) ja, real, dimension(0:1) ww, integer, dimension(1) b, integer, dimension(1) g, x0, x1, y0, y1, z0, z1, ss, eps, idpth)
Definition at line 2124 of file postnek8.f.
References boundary_graph(), build_adj(), chk_jacob(), find_bc_crv(), find_bd_jac(), find_sm_box(), get_gxyz(), gs_smooth(), i, izero(), n, prs(), and rerrr().
subroutine surface_id (integer, dimension(nfctot) nelpf, nfctot, integer, dimension(nfcs,1) se_to_face, nfcs, integer, dimension(nlv,1) vertex, nlv, integer, dimension(2,0:1) srfef, integer, dimension(nfc,1) srfvt, real, dimension(ndim,nfc,1) srfvx, nfc, real, dimension(ndim,1) vtxpt)
Definition at line 533 of file postnek8.f.
References hilitef(), izero(), and n.
subroutine surfchk ()
Definition at line 698 of file postnek8.f.
References defect_crct1(), defect_crct2(), defect_crct3(), defect_id(), face_id(), get_vert(), ilmax(), out_rea(), prs(), rei(), remap_xyz(), res(), selite(), and surface_id().
subroutine update_surface_layer (integer, dimension(1) ia, integer, dimension(1) ja, integer, dimension(1) b, delta, alpha)
Definition at line 2801 of file postnek8.f.
References alpha, i, and j.
function vec_length (real, dimension(1) v, n)
Definition at line 2261 of file postnek8.f.
References i, and n.
subroutine vec_vtx_min (real, dimension(nd,m,n) vs, real, dimension(nd,m,n) v, integer, dimension(m,n) vt, m, n, nm, real, dimension(nd,nm) work, nd)
Definition at line 609 of file postnek8.f.
References cfill(), i, j, and n.
subroutine vec_vtx_sum (real, dimension(nd,m,n) vs, real, dimension(nd,m,n) v, integer, dimension(m,n) vt, m, n, nm, real, dimension(nd,nm) work, nd)
Definition at line 636 of file postnek8.f.
References i, j, n, and rzero().