KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/plot.f File Reference
plot.f File Reference
Functions/Subroutines
subroutine data
function xscr (XPHYS)
function yscr (YPHYS)
function xphy (XSCREN)
function yphy (YSCREN)
subroutine gingrd (x1)
subroutine drwbox (X1, Y1, X2, Y2, IC)
subroutine xdot (XX, YY)
subroutine ddummy (IEDGE, IEL)
subroutine dashsc (X1, Y1, X2, Y2, N)
subroutine xdiamd (XX, YY)
subroutine sdiamd (XX, YY)
subroutine rdiamd (XX, YY)
subroutine arrow (X, Y, DXBAR, DYBAR, SARROW)
subroutine arrow4 (X, Y, Z, DX, DY, DZ)
subroutine draw3 (X3, Y3, Z3)
subroutine move3 (X3, Y3, Z3)
subroutine setrot (x3d, x3, y3, z3)
function xiso (X3, Y3, Z3)
function yiso (X3, Y3, Z3)
function ziso (X3, Y3, Z3)
function xisom (x3, y3i, z3)
function yisom (X3, Y3i, Z3)
function zisom (X3, Y3i, Z3)
subroutine uniso (X3D, Y3D, Z3D, XI, YI, ZI)
subroutine uniso2 (X3D, Y3D, Z3D, XI, YI, ZI)
subroutine uniso3 (X3D, Y3D, Z3D, XI, YI, ZI)
function dotprod (X, Y)
subroutine g3writ (X, Y, Z, SIZE, STRING)
subroutine drelev (IDRAW, IFADE, FLAG)
subroutine sortz
subroutine setvue
subroutine menu (XMOUSE, YMOUSE, BUTTON, MTITLE)
subroutine drmenu (mtitle)
subroutine drcovr (ICOVER)
subroutine drbar (TX, NTX)
subroutine rdmenu (XMOUSE, YMOUSE)
subroutine keypadm (TEMP, button, xmouse, ymouse)
subroutine keypad (TEMP)
subroutine rdkey (XMOUSE, YMOUSE, NCHAR, TEMP, IERR)
subroutine drkey
subroutine hard
subroutine nohard
subroutine getpts (NPOINT, CSPACE, IELS, ISID, XCRVED, YCRVED)
subroutine drawed (IEL, IEDGE, IFLIP)
subroutine setenv
subroutine initqms
subroutine initps
subroutine vdraw (XXIS, YYIS, N)
subroutine trngl1 (XY1, XY2, XY3)
subroutine trngl2 (XY1, XY2, XY3, IC)
function icolor1 (VAL)
function bcolor (VAL1, VAL2)
subroutine savebox (XY1, XY2, XY3, XY4, IC)
subroutine flshbox
subroutine box1 (XY1, XY2, XY3, XY4, IC)
logical function ifmenu (XMOUSE, YMOUSE)
subroutine vdraw3 (XYZ, N)
subroutine vdraw3a (X, Y, Z, N)
subroutine arrow3 (X, Y, Z, DXBAR, DYBAR, DZBAR, PLANE, SARROW)
subroutine keypad_def (TEMP, default)
subroutine rdkey_nice (XMOUSE, YMOUSE, NCHAR, TEMP, IERR)
subroutine draw_circ (x3, y3, z3, r)
subroutine adjvue (ifadjust)
subroutine diamd3 (xd, yd, zd, iclr)
Function/Subroutine Documentation
subroutine adjvue (logical ifadjust)
Definition at line 2265 of file plot.f.
References blank(), prs(), res(), and rescal().
subroutine arrow (X, Y, DXBAR, DYBAR, SARROW)
Definition at line 401 of file plot.f.
References drawc(), movec(), and scale().
subroutine arrow3 (X, Y, Z, DXBAR, DYBAR, DZBAR, character PLANE, SARROW)
Definition at line 2004 of file plot.f.
References cmult(), color, cross(), draw3(), i, move3(), norm3d(), and penw().
subroutine arrow4 (X, Y, Z, DX, DY, DZ)
Definition at line 414 of file plot.f.
References color, draw3(), move3(), penw(), and scale().
function bcolor (VAL1, VAL2)
Definition at line 1812 of file plot.f.
References i.
subroutine box1 (dimension(3) XY1, dimension(3) XY2, dimension(3) XY3, dimension(3) XY4, IC)
Definition at line 1923 of file plot.f.
References beginp(), color, drawc(), endp(), fillp(), xiso(), and yiso().
subroutine dashsc (X1, Y1, X2, Y2, N)
Definition at line 343 of file plot.f.
References drawsc(), i, movesc(), and n.
subroutine data ()
Definition at line 20 of file plot.f.
References blank(), i, if(), n, prs(), setgraph(), xphy(), and yphy().
subroutine ddummy (IEDGE, IEL)
Definition at line 338 of file plot.f.
subroutine diamd3 (xd, yd, zd, iclr)
Definition at line 2322 of file plot.f.
References color, diamda(), xisom(), and yisom().
function dotprod (dimension(3) X, dimension(3) Y)
Definition at line 612 of file plot.f.
References i.
subroutine draw3 (X3, Y3, Z3)
Definition at line 440 of file plot.f.
References drawc(), xiso(), and yiso().
subroutine draw_circ (x3, y3, z3, r)
Definition at line 2220 of file plot.f.
References drawc(), i, movec(), n, xiso(), and yiso().
subroutine drawed (IEL, IEDGE, IFLIP)
Definition at line 1452 of file plot.f.
References drawc(), getpts(), i, iflip(), movec(), xiso(), and yiso().
subroutine drbar (real, dimension(16) TX, NTX)
Definition at line 1040 of file plot.f.
References beginb(), clsseg(), delseg(), endp(), fillp(), gwrite(), move(), opnseg(), xphy(), and yphy().
subroutine drcovr (ICOVER)
Definition at line 991 of file plot.f.
References beginp(), clsseg(), color, endp(), fillp(), movesc(), opnseg(), xphy(), and yphy().
subroutine drelev (IDRAW, IFADE, character*5 FLAG)
Definition at line 627 of file plot.f.
References color, drawsc(), i, and movesc().
subroutine drkey ()
Definition at line 1211 of file plot.f.
References beginb(), clsseg(), color, draw(), endp(), fillp(), gwrite(), i, j, move(), opnseg(), xphy(), yphy(), and yscr().
subroutine drmenu (character*(*) mtitle)
Definition at line 893 of file plot.f.
References beginb(), beginp(), clsseg(), color, delseg(), drawsc(), endp(), fillp(), gswrit(), movesc(), opnseg(), sgvis(), xphy(), and yphy().
subroutine drwbox (X1, Y1, X2, Y2, IC)
Definition at line 317 of file plot.f.
References color, drawc(), and movec().
subroutine flshbox ()
Definition at line 1893 of file plot.f.
References beginp(), color, drawc(), endp(), fillp(), i, xiso(), and yiso().
subroutine g3writ (X, Y, Z, SIZE, character, dimension(100) STRING)
Definition at line 621 of file plot.f.
References gwrite(), xiso(), and yiso().
subroutine getpts (NPOINT, real, dimension(npoint) CSPACE, IELS, ISID, real, dimension(npoint) XCRVED, real, dimension(npoint) YCRVED)
Definition at line 1317 of file plot.f.
References dist2(), i, j, keypad(), latchob(), and prs().
subroutine gingrd (x1)
Definition at line 305 of file plot.f.
References prs().
subroutine hard ()
Definition at line 1305 of file plot.f.
function icolor1 (VAL)
Definition at line 1788 of file plot.f.
logical function ifmenu (XMOUSE, YMOUSE)
Definition at line 1961 of file plot.f.
References i, j, xscr(), yphy(), and yscr().
subroutine initps ()
Definition at line 1586 of file plot.f.
References chcopy(), and ltrunc().
subroutine initqms ()
Definition at line 1579 of file plot.f.
subroutine keypad (TEMP)
Definition at line 1120 of file plot.f.
References drkey(), mouse(), prs(), rdkey(), and sgvis().
subroutine keypad_def (TEMP, default)
Definition at line 2115 of file plot.f.
References drkey(), mouse(), prs(), rdkey_nice(), and sgvis().
subroutine keypadm (TEMP, button, xmouse, ymouse)
Definition at line 1100 of file plot.f.
References drkey(), mouse(), prs(), rdkey(), and sgvis().
subroutine menu (XMOUSE, YMOUSE, BUTTON, character, dimension(*) MTITLE)
Definition at line 764 of file plot.f.
References blank(), chcopy(), drcovr(), drmenu(), i, ltrunc(), mouse(), prs(), rei(), sgvis(), xscr(), and yscr().
subroutine move3 (X3, Y3, Z3)
Definition at line 448 of file plot.f.
References movec(), xiso(), and yiso().
subroutine nohard ()
Definition at line 1311 of file plot.f.
subroutine rdiamd (XX, YY)
Definition at line 388 of file plot.f.
References drawsc(), and movesc().
subroutine rdkey (XMOUSE, YMOUSE, NCHAR, TEMP, IERR)
Definition at line 1142 of file plot.f.
References blank(), i, j, prs(), reader(), sgvis(), xscr(), yphy(), and yscr().
subroutine rdkey_nice (XMOUSE, YMOUSE, NCHAR, TEMP, IERR)
Definition at line 2147 of file plot.f.
References blank(), i, j, prs(), reader(), sgvis(), xscr(), yphy(), and yscr().
subroutine rdmenu (XMOUSE, YMOUSE)
Definition at line 1081 of file plot.f.
References prs(), xphy(), and yphy().
subroutine savebox (dimension(3) XY1, dimension(3) XY2, dimension(3) XY3, dimension(3) XY4, IC)
Definition at line 1847 of file plot.f.
References copy(), and flshbox().
subroutine sdiamd (XX, YY)
Definition at line 377 of file plot.f.
References drawsc(), and movesc().
subroutine setenv ()
Definition at line 1517 of file plot.f.
References blank(), i, ia, openf(), parse(), and prs().
subroutine setrot (real, dimension(3) x3d, x3, y3, z3)
Definition at line 455 of file plot.f.
subroutine setvue ()
Definition at line 714 of file plot.f.
References prs(), prsrs(), reader(), res(), and rescal().
subroutine sortz ()
Definition at line 669 of file plot.f.
References iswap(), sort(), and ziso().
subroutine trngl1 (dimension(4) XY1, dimension(4) XY2, dimension(4) XY3)
Definition at line 1682 of file plot.f.
References bcolor(), copy(), icolor1(), and trngl2().
subroutine trngl2 (dimension(3) XY1, dimension(3) XY2, dimension(3) XY3, IC)
Definition at line 1753 of file plot.f.
References beginp(), color, drawc(), endp(), fillp(), xiso(), and yiso().
subroutine uniso (X3D, Y3D, Z3D, XI, YI, ZI)
Definition at line 576 of file plot.f.
subroutine uniso2 (X3D, Y3D, Z3D, XI, YI, ZI)
Definition at line 588 of file plot.f.
subroutine uniso3 (X3D, Y3D, Z3D, XI, YI, ZI)
Definition at line 600 of file plot.f.
subroutine vdraw (dimension(n) XXIS, dimension(n) YYIS, N)
Definition at line 1672 of file plot.f.
References drawc(), i, movec(), and n.
subroutine vdraw3 (dimension(4,n) XYZ, N)
Definition at line 1981 of file plot.f.
References color, draw3(), i, icolor1(), move3(), and n.
subroutine vdraw3a (dimension(n) X, dimension(n) Y, dimension(n) Z, N)
Definition at line 1994 of file plot.f.
References draw3(), i, move3(), and n.
subroutine xdiamd (XX, YY)
Definition at line 366 of file plot.f.
References drawc(), and movec().
subroutine xdot (XX, YY)
Definition at line 328 of file plot.f.
References drawc(), and movec().
function xiso (X3, Y3, Z3)
Definition at line 500 of file plot.f.
References dotprod(), and setrot().
function xisom (x3, y3i, z3)
Definition at line 532 of file plot.f.
References dotprod(), and setrot().
function xphy (XSCREN)
Definition at line 293 of file plot.f.
function xscr (XPHYS)
Definition at line 281 of file plot.f.
function yiso (X3, Y3, Z3)
Definition at line 511 of file plot.f.
References dotprod(), and setrot().
function yisom (X3, Y3i, Z3)
Definition at line 547 of file plot.f.
References dotprod(), and setrot().
function yphy (YSCREN)
Definition at line 299 of file plot.f.
function yscr (YPHYS)
Definition at line 287 of file plot.f.
function ziso (X3, Y3, Z3)
Definition at line 522 of file plot.f.
References dotprod(), and setrot().
function zisom (X3, Y3i, Z3)
Definition at line 561 of file plot.f.
References dotprod(), and setrot().