KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/screen.f File Reference
screen.f File Reference
Functions/Subroutines
subroutine setscr
subroutine setgrd
subroutine drgrid
subroutine refresh
subroutine movec (X1, Y1)
subroutine drawc (X1, Y1)
subroutine filter (XMOUSE, YMOUSE, XSCREEN, YSCREEN)
subroutine drwobj (IOBJ)
subroutine latchob (X0, Y0, Z0, DIST2, IOBJ)
subroutine setobj
subroutine setzoom
subroutine setrans
subroutine rescal
subroutine ellgen (x, y, n, a, b)
subroutine genpair (ynew, x0, y0, x1, y1, a, b)
subroutine refresh2
Function/Subroutine Documentation
subroutine drawc (X1, Y1)
Definition at line 602 of file screen.f.
References dot(), draw(), and move().
subroutine drgrid ()
Definition at line 415 of file screen.f.
References color, draw(), drawc(), drawsc(), drwobj(), gingrd(), gswrit(), gwrite(), i, move(), movec(), movesc(), xphy(), xscr(), yphy(), and yscr().
subroutine drwobj (IOBJ)
Definition at line 817 of file screen.f.
References color, i, npts, and vdraw().
subroutine ellgen (real, dimension(0:1) x, real, dimension(0:1) y, n, a, b)
Definition at line 1284 of file screen.f.
References copy(), genpair(), i, j, n, prs(), and rerr().
subroutine filter (XMOUSE, YMOUSE, XSCREEN, YSCREEN)
Definition at line 733 of file screen.f.
References dist2(), i, latchob(), xphy(), and yphy().
subroutine genpair (real, dimension(0:1) ynew, x0, y0, x1, y1, a, b)
Definition at line 1374 of file screen.f.
subroutine latchob (X0, Y0, Z0, DIST2, IOBJ)
Definition at line 830 of file screen.f.
References dist2(), i, and npts.
subroutine movec (X1, Y1)
Definition at line 584 of file screen.f.
subroutine refresh ()
Definition at line 551 of file screen.f.
References beginb(), clear(), clsseg(), color, drawsc(), drkey(), endp(), fillp(), nohard(), opnseg(), sgvis(), xphy(), and yphy().
subroutine refresh2 ()
Definition at line 1411 of file screen.f.
References clear(), drfram(), drmesh(), hard(), heject(), and nohard().
subroutine rescal ()
Definition at line 1195 of file screen.f.
References xiso(), xphy(), yiso(), and yphy().
subroutine setgrd ()
Definition at line 266 of file screen.f.
References drawel(), drgrid(), i, keypad(), menu(), prs(), and refresh().
subroutine setobj ()
Definition at line 857 of file screen.f.
References drwobj(), ellgen(), i, n, npts, and rzero().
subroutine setrans ()
Definition at line 1128 of file screen.f.
References color, drawsc(), drgrid(), mouse(), movesc(), prs(), xphy(), xscr(), yphy(), and yscr().
subroutine setscr ()
Definition at line 18 of file screen.f.
References adjvue(), clear(), draxis(), drfram(), drmesh(), dspobj(), hard(), heject(), menu(), mouse(), nohard(), post_reset_window(), prs(), reii(), relite(), rescal(), setquad(), setrans(), setvue(), setzoom(), and strplt().
subroutine setzoom ()
Definition at line 888 of file screen.f.
References color, drawc(), drawsc(), mouse(), movec(), movesc(), prs(), rerrrr(), rescal(), scale(), xphy(), xscr(), yphy(), and yscr().