KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/tsort.f File Reference
tsort.f File Reference
Functions/Subroutines
subroutine ituple_sort (a, lda, n, key, nkey, ind, aa)
subroutine tuple_sort (a, lda, n, key, nkey, ind, aa)
logical function iftuple_ialtb (a, b, key, nkey)
logical function iftuple_altb (a, b, key, nkey)
logical function iftuple_ianeb (a, b, key, nkey)
subroutine ipsort (ID, N, D, INFO)
subroutine iusort (ID, N, list, INFO)
subroutine ituple_s_merge (na, a, lda, n, key, nkey, ind, aa)
Function/Subroutine Documentation
logical function iftuple_altb (real, dimension(1) a, real, dimension(1) b, integer, dimension(nkey) key, nkey)
Definition at line 145 of file tsort.f.
References i, and iftuple_altb().
logical function iftuple_ialtb (integer, dimension(1) a, integer, dimension(1) b, integer, dimension(nkey) key, nkey)
Definition at line 127 of file tsort.f.
References i, and iftuple_ialtb().
logical function iftuple_ianeb (integer, dimension(1) a, integer, dimension(1) b, integer, dimension(nkey) key, nkey)
Definition at line 163 of file tsort.f.
References i, and iftuple_ianeb().
subroutine ipsort (character ID, integer N, integer, dimension(1) D, integer INFO)
Definition at line 178 of file tsort.f.
References i, j, tmp, and xerbla().
subroutine ituple_s_merge (na, integer, dimension(lda,n) a, lda, n, integer, dimension(nkey) key, nkey, integer, dimension(1) ind, integer, dimension(lda) aa)
Definition at line 445 of file tsort.f.
References ituple_sort(), j, and n.
subroutine ituple_sort (integer, dimension(lda,n) a, lda, n, integer, dimension(nkey) key, nkey, integer, dimension(1) ind, integer, dimension(lda) aa)
Definition at line 3 of file tsort.f.
References i, icopy(), j, and n.
subroutine iusort (character*1 ID, N, integer, dimension(1) list, INFO)
Definition at line 421 of file tsort.f.
References i, ipsort(), and n.
subroutine tuple_sort (real, dimension(lda,n) a, lda, n, integer, dimension(nkey) key, nkey, integer, dimension(1) ind, real, dimension(lda) aa)
Definition at line 65 of file tsort.f.
References copy(), i, j, and n.