KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/xdriver.c File Reference
xdriver.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <errno.h>
#include <math.h>
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/cursorfont.h>
#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Xos.h>
#include <X11/Xatom.h>
#include <X11/Xresource.h>
#include "icon"
#include <assert.h>
#include "errmem.h"
Data Structures
struct mse_event_rec
Macros
#define NUM_COLOR_CELLS 15
#define MAX_WINDOWH 8960 /* 800 896 1412 1694 */
#define MAX_WINDOWW 9520 /* 850 952 1500 1800 */
#define SAFTY 0
#define MAX(x, y) ((x)>(y)) ? (x) : (y)
#define MIN(x, y) ((x)<(y)) ? (x) : (y)
#define FALSE 0
#define TRUE 1
#define check_width 16
#define check_height 16
#define MOUSE 0
#define LINE 1
Functions
void hmt_refresh_ (void)
void hpm_t_ (void)
void htw_t_ (void)
void hpm_f_ (void)
void htw_f_ (void)
void grab_window_raw_ (float *x1, float *y1, float *x2, float *y2, char *filename)
void grab_window_xwd_ (char *filename)
void grab_window_ (char *filename, int *index)
void getwin_ (float *width, float *height)
void xplanes_ (int *nplanes)
void xwaitm_ (int *button, float *xmouse, float *ymouse)
void beep_ ()
void gets_ (char *line)
void xdrawto_ (float *x, float *y)
void xmove_ (float *x, float *y)
void xcmap_ (red, green, blue, int *num)
void hmt_xcmap_ (red, green, blue, int *num)
void hmt_xsetfill_ (int *icolor)
void xsetfill_ (int *icolor)
void xsetpen_ (int *icolor)
void xpoly_ (float *xfill, float *yfill, int *nvertices, int *boundary)
void xclear_ (int *i)
void xcleara_ ()
void xputxt_ (float *x, float *y, float *fontsize, char *string, int *strlength)
void puts_ (char *message, int *nchars)
void closew_ ()
void mainc_ (void)
void set_ww_wh_ (int *ww, int *wh)
Macro Definition Documentation
#define check_height 16
Definition at line 32 of file xdriver.c.
#define check_width 16
Definition at line 31 of file xdriver.c.
#define FALSE 0
Definition at line 27 of file xdriver.c.
#define LINE 1
Definition at line 38 of file xdriver.c.
#define MAX (x, y) ((x)>(y)) ? (x) : (y)
Definition at line 25 of file xdriver.c.
#define MAX_WINDOWH 8960 /* 800 896 1412 1694 */
Definition at line 20 of file xdriver.c.
#define MAX_WINDOWW 9520 /* 850 952 1500 1800 */
Definition at line 21 of file xdriver.c.
#define MIN (x, y) ((x)<(y)) ? (x) : (y)
Definition at line 26 of file xdriver.c.
#define MOUSE 0
Definition at line 37 of file xdriver.c.
#define NUM_COLOR_CELLS 15
Definition at line 19 of file xdriver.c.
#define SAFTY 0
Definition at line 22 of file xdriver.c.
#define TRUE 1
Definition at line 28 of file xdriver.c.
Function Documentation
void beep_ ()
Definition at line 621 of file xdriver.c.
References dpy.
void closew_ ()
Definition at line 1231 of file xdriver.c.
References Quit().
void gets_ (char * line)
Definition at line 649 of file xdriver.c.
References i, LINE, x, xmainloop(), and y().
void getwin_ (float * width, float* height)
Definition at line 539 of file xdriver.c.
References windowh, and windoww.
void grab_window_ (char * filename, int * index)
Definition at line 505 of file xdriver.c.
References printf().
void grab_window_raw_ (float * x1, float * y1, float * x2, float * y2, char * filename)
Definition at line 202 of file xdriver.c.
References border(), dpy, error(), exit(), i, if(), j, malloc(), MAX, MIN, n, NUM_COLOR_CELLS, printf(), shift(), tcalloc, tmalloc, windowh, windoww, x, and y().
void grab_window_xwd_ (char * filename)
Definition at line 479 of file xdriver.c.
References printf().
void hmt_refresh_ (void)
Definition at line 136 of file xdriver.c.
References dpy, windowh, and windoww.
void hmt_xcmap_ (red , green , blue , int * num)
Definition at line 791 of file xdriver.c.
References dpy, i, NUM_COLOR_CELLS, printf(), Random_Integer(), and Random_Seed().
void hmt_xsetfill_ (int * icolor)
Definition at line 862 of file xdriver.c.
References dpy, and NUM_COLOR_CELLS.
void hpm_f_ (void)
Definition at line 178 of file xdriver.c.
References FALSE.
void hpm_t_ (void)
Definition at line 153 of file xdriver.c.
References TRUE.
void htw_f_ (void)
Definition at line 184 of file xdriver.c.
References FALSE.
void htw_t_ (void)
Definition at line 159 of file xdriver.c.
References TRUE.
void mainc_ (void)
Definition at line 1254 of file xdriver.c.
References Quit(), and SetUpEnv().
void puts_ (char * message, int * nchars)
Definition at line 1169 of file xdriver.c.
References active_line, advanceLine(), dpy, i, and Line.
void set_ww_wh_ (int * ww, int * wh)
Definition at line 1284 of file xdriver.c.
References active_line, advanceLine(), backSpace(), mse_event_rec::buttonNumber, char_spacing, check_height, check_width, dpy, error(), exit(), i, if(), j, lb, left_margin, LINE, Line, line_spacing, list, MAX_WINDOWH, MAX_WINDOWW, MOUSE, n, num_lines, printf(), Quit(), Random_Integer(), Random_Seed(), resetXPRINT(), seed, SetUpEnv(), showChar(), text_screenh, tmp, top_line, TypeChar(), vfx, vfy, windowh, windoww, mse_event_rec::xclicked, xmainloop(), and mse_event_rec::yclicked.
void xclear_ (int * i)
Definition at line 1005 of file xdriver.c.
References dpy, line_spacing, text_screenh, windowh, windoww, and xsetfill_().
void xcleara_ ()
Definition at line 1054 of file xdriver.c.
References dpy, i, line_spacing, text_screenh, windowh, windoww, x, xsetfill_(), and y().
void xcmap_ (red , green , blue , int * num)
Definition at line 748 of file xdriver.c.
References dpy, and i.
void xdrawto_ (float * x, float* y)
Definition at line 684 of file xdriver.c.
References dpy.
void xmove_ (float * x, float* y)
Definition at line 723 of file xdriver.c.
References dpy.
void xplanes_ (int * nplanes)
Definition at line 563 of file xdriver.c.
References dpy.
void xpoly_ (float * xfill, float * yfill, int * nvertices, int * boundary)
Definition at line 939 of file xdriver.c.
References dpy, and i.
void xputxt_ (float * x, float* y, float* fontsize, char * string, int * strlength)
Definition at line 1111 of file xdriver.c.
References dpy.
void xsetfill_ (int * icolor)
Definition at line 889 of file xdriver.c.
References dpy.
void xsetpen_ (int * icolor)
Definition at line 914 of file xdriver.c.
References dpy.
void xwaitm_ (int * button, float * xmouse, float* ymouse)
Definition at line 586 of file xdriver.c.
References mse_event_rec::buttonNumber, dpy, MOUSE, text_screenh, windowh, mse_event_rec::xclicked, xmainloop(), and mse_event_rec::yclicked.