KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/iolib_no_graph.f File Reference
iolib_no_graph.f File Reference
Functions/Subroutines
subroutine prs (S)
subroutine pri (I)
subroutine prr (R)
subroutine prii (I1, I2)
subroutine prrrr (R1, R2, R3)
subroutine prrr (R1, R2)
subroutine prsi (S, I)
subroutine pris (I, S)
subroutine prsrrr (S, r1, r2, r3)
subroutine prsrr (S, r1, r2)
subroutine prsr (S, R)
subroutine prsii (S, I, J)
subroutine prsir (S, I, R)
subroutine prsis (S1, I, S2)
subroutine prsrs (S1, R, S2)
subroutine res (S1, N)
subroutine reiii (i, j, k)
subroutine reii (I, j)
subroutine rei (I)
subroutine rer (R1)
subroutine rerr (R1, R2)
subroutine rerrr (R1, R2, R3)
subroutine rerrrr (R1, R2, R3, R4)
subroutine putsold (S, NCHARS)
subroutine getsold (S)
subroutine prsiii (S, I1, i2, i3)
subroutine prsiv (s, i1, i2, i3, i4)
subroutine priii (I1, I2, I3)
subroutine setgraph (ifgraf)
Function/Subroutine Documentation
subroutine getsold (character S)
Definition at line 520 of file iolib_no_graph.f.
subroutine pri (I)
Definition at line 84 of file iolib_no_graph.f.
References i, and prs().
subroutine prii (I1, I2)
Definition at line 105 of file iolib_no_graph.f.
References prs().
subroutine priii (I1, I2, I3)
Definition at line 579 of file iolib_no_graph.f.
References prs().
subroutine pris (I, character, dimension(*) S)
Definition at line 158 of file iolib_no_graph.f.
References blank(), i, j, prs(), and putsold().
subroutine prr (R)
Definition at line 94 of file iolib_no_graph.f.
References prs().
subroutine prrr (R1, R2)
Definition at line 125 of file iolib_no_graph.f.
References prs().
subroutine prrrr (R1, R2, R3)
Definition at line 115 of file iolib_no_graph.f.
References prs().
subroutine prs (character, dimension(*) S)
Definition at line 55 of file iolib_no_graph.f.
References chcopy(), i, and j.
subroutine prsi (character, dimension(*) S, I)
Definition at line 135 of file iolib_no_graph.f.
References i, j, prs(), and putsold().
subroutine prsii (character, dimension(*) S, I, J)
Definition at line 248 of file iolib_no_graph.f.
References i, j, prs(), and putsold().
subroutine prsiii (character, dimension(*) S, I1, i2, i3)
Definition at line 532 of file iolib_no_graph.f.
References prs().
subroutine prsir (character, dimension(*) S, I, R)
Definition at line 270 of file iolib_no_graph.f.
References i, prs(), and putsold().
subroutine prsis (character, dimension(*) S1, I, character, dimension(*) S2)
Definition at line 292 of file iolib_no_graph.f.
References i, j, prs(), and putsold().
subroutine prsiv (character, dimension(*) s, i1, i2, i3, i4)
Definition at line 554 of file iolib_no_graph.f.
References prs().
subroutine prsr (character, dimension(*) S, R)
Definition at line 226 of file iolib_no_graph.f.
References i, prs(), and putsold().
subroutine prsrr (character, dimension(*) S, r1, r2)
Definition at line 204 of file iolib_no_graph.f.
References i, prs(), and putsold().
subroutine prsrrr (character, dimension(*) S, r1, r2, r3)
Definition at line 182 of file iolib_no_graph.f.
References i, prs(), and putsold().
subroutine prsrs (character, dimension(*) S1, R, character, dimension(*) S2)
Definition at line 332 of file iolib_no_graph.f.
References i, prs(), and putsold().
subroutine putsold (character, dimension(*) S, NCHARS)
Definition at line 511 of file iolib_no_graph.f.
References i.
subroutine rei (I)
Definition at line 431 of file iolib_no_graph.f.
References i, prs(), and res().
subroutine reii (I, j)
Definition at line 415 of file iolib_no_graph.f.
References i, j, prs(), and res().
subroutine reiii (i, j, k)
Definition at line 399 of file iolib_no_graph.f.
References i, j, prs(), and res().
subroutine rer (R1)
Definition at line 447 of file iolib_no_graph.f.
References prs(), and res().
subroutine rerr (R1, R2)
Definition at line 463 of file iolib_no_graph.f.
References prs(), and res().
subroutine rerrr (R1, R2, R3)
Definition at line 479 of file iolib_no_graph.f.
References prs(), and res().
subroutine rerrrr (R1, R2, R3, R4)
Definition at line 495 of file iolib_no_graph.f.
References prs(), and res().
subroutine res (character, dimension(*) S1, N)
Definition at line 378 of file iolib_no_graph.f.
References getsold(), i, and n.
subroutine setgraph (logical ifgraf)
Definition at line 588 of file iolib_no_graph.f.