KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/postnek.f File Reference
postnek.f File Reference
Functions/Subroutines
subroutine fprep
subroutine plotit (iprompt)
subroutine readln (LOCATN)
subroutine drmesh
subroutine readhs
subroutine comand (ARG, IA)
subroutine setatt
subroutine setres
subroutine setloc
subroutine getpt (POINT1, POINT2, POINT3, FLAG)
subroutine draxis
subroutine show (ARG, IA)
subroutine init
subroutine tem
subroutine fill_tx
subroutine colrbar
subroutine drfram
subroutine driso
subroutine plerr
subroutine drerr (IEL, ICOLOR)
subroutine mespos
subroutine vel
subroutine dspobj
subroutine findnam (CHOICES, NCC)
subroutine relite
subroutine initstate
subroutine dmpstate
subroutine outstate (name)
subroutine init0
subroutine post_reset_window
subroutine setloc_bdry (if_add_loc)
subroutine noncon_chk (ifnc)
subroutine temvel
subroutine exitt
subroutine get_subset_list
subroutine copy4b (a, b, n, iel, nel)
subroutine copy8b (a, b, n, iel, nel)
subroutine copyi (a, b, n)
subroutine quickfill (pp)
Function/Subroutine Documentation
subroutine colrbar ()
Definition at line 2984 of file postnek.f.
References beginb(), drbar(), drcovr(), endp(), fill_tx(), fillp(), gwrite(), movesc(), prsrs(), sgvis(), xphy(), and yphy().
subroutine comand (ARG, IA)
Definition at line 831 of file postnek.f.
References i, and prs().
subroutine copy4b (real, dimension(nel,1) a, real*4, dimension(1) b, n, iel, nel)
Definition at line 4705 of file postnek.f.
References i, and n.
subroutine copy8b (real, dimension(nel,1) a, real*8, dimension(1) b, n, iel, nel)
Definition at line 4714 of file postnek.f.
References i, and n.
subroutine copyi (integer, dimension(1) a, real*8, dimension(1) b, n)
Definition at line 4723 of file postnek.f.
References i, and n.
subroutine dmpstate ()
Definition at line 4048 of file postnek.f.
References outstate(), prs(), and res().
subroutine draxis ()
Definition at line 1586 of file postnek.f.
References arrow3(), color, and g3writ().
subroutine drerr (IEL, ICOLOR)
Definition at line 3512 of file postnek.f.
References beginp(), color, draw3(), drawc(), drawed(), endp(), fillp(), hard(), i, j, movec(), nohard(), nx, nz, xiso(), and yiso().
subroutine drfram ()
Definition at line 3128 of file postnek.f.
References color, drawsc(), draxis(), gwrite(), i, movesc(), xphy(), and yphy().
subroutine driso ()
Definition at line 3183 of file postnek.f.
References beginb(), color, drawc(), endp(), fillp(), getpts(), i, iflip(), movec(), penw(), rescal(), sortz(), xiso(), xisom(), yiso(), and yisom().
subroutine drmesh ()
Definition at line 731 of file postnek.f.
References diamd3(), driso(), drisog(), g3writ(), hard(), i, j, nx, nz, and rzero().
subroutine dspobj ()
Definition at line 3932 of file postnek.f.
References color, drawc(), i, movec(), xiso(), and yiso().
subroutine exitt ()
Definition at line 4661 of file postnek.f.
subroutine fill_tx ()
Definition at line 2960 of file postnek.f.
References i.
subroutine findnam (character*26, dimension(1) CHOICES, NCC)
Definition at line 3975 of file postnek.f.
References i.
subroutine fprep ()
Definition at line 18 of file postnek.f.
References clear(), compute_miles(), compute_stresses(), cutting_plane(), data(), deltmp(), devex(), dmpstate(), drfram(), drmesh(), exitt(), fileout(), getfld(), gindis(), gnable(), hard(), heject(), hilight(), i, ia, init(), init0(), initstate(), lin_combo(), menu(), mesh_smooth(), mltiplt(), mltiplt2(), mouse(), nohard(), nx, periodic_check(), plotit(), prs(), prsi(), redraw(), rei(), rms_avg(), rms_uvw(), savstate(), set_surf_layer(), setatt(), setcvol(), setloc(), setscr(), setwrk(), show(), surfchk(), xphy(), and yphy().
subroutine get_subset_list ()
Definition at line 4682 of file postnek.f.
References izero(), prsi(), and reiii().
subroutine getpt (POINT1, POINT2, POINT3, character*26 FLAG)
Definition at line 1501 of file postnek.f.
References mouse(), prs(), rer(), rerrr(), rmin(), xiso(), xscr(), and ziso().
subroutine init ()
Definition at line 1613 of file postnek.f.
References blank(), byte_close, byte_open, byte_read, byte_reverse, byte_reverse8, capit(), chcopy(), clear(), clrmap(), copy4b(), copy4r(), copy8b(), copy8r(), copyi(), ddummy(), dermat(), devex(), devini(), exitt(), genpn1(), get_subset_list(), getfld(), i, indx1(), initps(), initqms(), izero(), j, legend(), ltrunc(), mespos(), n, nx, nz, openf(), prrr(), prs(), prsi(), prsii(), prsis(), readhs(), res(), rescal(), rr, rzero(), setenv(), setgraph(), setquad(), setsrfp(), and setwrk().
subroutine init0 ()
Definition at line 4107 of file postnek.f.
subroutine initstate ()
Definition at line 4006 of file postnek.f.
References outstate(), and setstate().
subroutine mespos ()
Definition at line 3598 of file postnek.f.
References genxyz(), getpts(), i, j, legend(), nx, and nz.
subroutine noncon_chk (logical ifnc)
Definition at line 4329 of file postnek.f.
subroutine outstate (character*8 name)
Definition at line 4069 of file postnek.f.
References savstate().
subroutine plerr ()
Definition at line 3399 of file postnek.f.
References beginb(), calcerr(), drbar(), drerr(), endp(), fillp(), gwrite(), mouse(), movesc(), penw(), prs(), prsrs(), sgvis(), xphy(), and yphy().
subroutine plotit (iprompt)
Definition at line 515 of file postnek.f.
References animate(), beginb(), color, cvolume(), drwmsh(), drwmsh2(), drwmsh3(), endp(), fillp(), grab_window_pix(), gwrite(), heject(), histry(), mouse(), movesc(), nekplanar(), nekprofil(), particle_paths(), pfiles(), plerr(), prs(), srfplot(), stream(), strplt(), tem(), temvel(), value(), values(), vel(), vfiles(), xphy(), and yphy().
subroutine post_reset_window ()
Definition at line 4127 of file postnek.f.
References clear(), devini(), and drmesh().
subroutine quickfill (real, dimension(nx,ny,nz) pp)
Definition at line 4732 of file postnek.f.
References i, j, nx, and nz.
subroutine readhs ()
Definition at line 827 of file postnek.f.
subroutine readln (LOCATN)
Definition at line 691 of file postnek.f.
References capit(), openf(), prs(), and res().
subroutine relite ()
Definition at line 3997 of file postnek.f.
References hilight().
subroutine setatt ()
Definition at line 865 of file postnek.f.
References avg_uvwpt_regular(), drbar(), genfem(), getfld(), mapz(), menu(), prs(), reader(), rei(), rerr(), res(), setann(), setres(), shiftcg(), and shiftmom().
subroutine setloc ()
Definition at line 1214 of file postnek.f.
References blank(), clip_plane(), color, cutting_plane(), diamda(), draw(), draw3(), drawsc(), draxis(), drmesh(), findnam(), getpt(), i, j, list, menu(), mouse(), move(), move3(), movesc(), nx, nz, pris(), prs(), prsi(), rei(), rmin(), setloc_bdry(), setrstp(), setsrfp(), and signpl().
subroutine setloc_bdry (logical if_add_loc)
Definition at line 4139 of file postnek.f.
References menu(), noncon_chk(), pris(), prs(), res(), and setsrfp().
subroutine setres ()
Definition at line 1069 of file postnek.f.
References blank(), menu(), pris(), prs(), prsi(), prsis(), prsrs(), reader(), res(), and sortit().
subroutine show (ARG, IA)
Definition at line 1606 of file postnek.f.
subroutine tem ()
Definition at line 2702 of file postnek.f.
References colrbar(), decod(), heatc(), heatf(), i, j, lfalse(), nx, nz, penw(), prs(), sortl(), and vmirror().
subroutine temvel ()
Definition at line 4371 of file postnek.f.
References aarrow(), arrow(), color, colrbar(), decod(), heatc(), heatf(), i, j, lfalse(), nx, nz, penw(), prs(), sortl(), vmirror(), xphy(), and yphy().
subroutine vel ()
Definition at line 3757 of file postnek.f.
References aarrow(), arrow(), arrow3(), border(), color, decod(), i, j, lfalse(), nx, nz, prs(), sortl(), xphy(), and yphy().