KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/postnek6.f File Reference
postnek6.f File Reference
Functions/Subroutines
subroutine setquad
subroutine drquad
subroutine xdiam3 (xyz)
subroutine mapxc (xyz, ie)
subroutine decod (ix, iy, iz, ie, Jxyz, nx, ny, nz)
subroutine setsrfp (srfqal, nqual, ifld)
subroutine sortl
subroutine signpl (lplane)
subroutine gencen
subroutine clip_plane
subroutine mirror (xm, ym, zm, xi, yi, zi, m)
subroutine vmirror (tm, xm, ym, zm, n, m)
subroutine outvtx (ie, ifce, io)
subroutine assign_bc
subroutine gaujordf (a, m, n, indr, indc, ipiv, ierr)
subroutine shiftcg
subroutine shiftmom
subroutine mapz (f, regdir)
subroutine setsrfp_periodic (e, f, e1, f1, ifld)
subroutine periodic_check
Function/Subroutine Documentation
subroutine assign_bc ()
Definition at line 697 of file postnek6.f.
subroutine clip_plane ()
Definition at line 562 of file postnek6.f.
References capit(), decod(), i, j, list, nx, nz, prs(), rer(), and res().
subroutine decod (ix, iy, iz, ie, Jxyz, nx, ny, nz)
Definition at line 302 of file postnek6.f.
References nx, and nz.
subroutine drquad ()
Definition at line 246 of file postnek6.f.
References color, and xdiam3().
subroutine gaujordf (real, dimension(m,n) a, m, n, integer, dimension(m) indr, integer, dimension(n) indc, integer, dimension(n) ipiv, ierr)
Definition at line 707 of file postnek6.f.
References i, izero(), j, n, and tmp.
subroutine gencen ()
Definition at line 518 of file postnek6.f.
References j, rzero(), and vsqrt().
subroutine mapxc (dimension(3,8) xyz, ie)
Definition at line 278 of file postnek6.f.
References i.
subroutine mapz (real, dimension(nxm*nym*nzm*nelm) f, character*1 regdir)
Definition at line 1026 of file postnek6.f.
References copy(), fd_weights_full(), legend(), mxm(), nx, nz, prs(), and transpose().
subroutine mirror (xm, ym, zm, xi, yi, zi, m)
Definition at line 636 of file postnek6.f.
subroutine outvtx (ie, ifce, io)
Definition at line 667 of file postnek6.f.
subroutine periodic_check ()
Definition at line 1118 of file postnek6.f.
References prs(), prsiv(), res(), setsrfp_periodic(), and tem().
subroutine setquad ()
Definition at line 3 of file postnek6.f.
References gencen(), mapxc(), mod1(), and rzero().
subroutine setsrfp (character*1, dimension(1) srfqal, nqual, ifld)
Definition at line 324 of file postnek6.f.
References list, nx, and signpl().
subroutine setsrfp_periodic (integer e, integer f, integer e1, integer f1, ifld)
Definition at line 1078 of file postnek6.f.
References list, nx, prsiii(), prsiv(), and signpl().
subroutine shiftcg ()
Definition at line 801 of file postnek6.f.
References blank(), cadd(), coef(), gencen(), nx, nz, prs(), prsrr(), prsrrr(), rerr(), res(), and vol_int().
subroutine shiftmom ()
Definition at line 873 of file postnek6.f.
References blank(), cadd2(), coef(), gaujordf(), gencen(), i, j, mxm(), norm3d(), nx, nz, outmat(), prs(), prsi(), prsrrr(), res(), ssyev(), vol_int(), and vol_int2().
subroutine signpl (lplane)
Definition at line 454 of file postnek6.f.
References cross(), decod(), i, j, norm3d(), nx, nz, and sub3().
subroutine sortl ()
Definition at line 406 of file postnek6.f.
References decod(), i, icopy(), iswap(), list, mirror(), nx, nz, sort(), and ziso().
subroutine vmirror (real, dimension(n,n) tm, real, dimension(n,n) xm, real, dimension(n,n) ym, real, dimension(n,n) zm, n, m)
Definition at line 650 of file postnek6.f.
References i, and n.
subroutine xdiam3 (dimension(3) xyz)
Definition at line 263 of file postnek6.f.
References drawc(), movec(), xiso(), and yiso().