KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/legend.f File Reference
legend.f File Reference
Functions/Subroutines
subroutine legend (ZPTS, WGHT, N)
subroutine zwgl (Z, W, NP)
subroutine zwgll (Z, W, NP)
subroutine zwgj (Z, W, NP, ALPHA, BETA)
subroutine zwgjd (Z, W, NP, ALPHA, BETA)
subroutine zwglj (Z, W, NP, ALPHA, BETA)
subroutine zwgljd (Z, W, NP, ALPHA, BETA)
real *8 function endw1 (N, ALPHA, BETA)
real *8 function endw2 (N, ALPHA, BETA)
real *8 function gammaf (X)
real *8 function pnormj (N, ALPHA, BETA)
subroutine jacg (XJAC, NP, ALPHA, BETA)
subroutine jacobf (POLY, PDER, POLYM1, PDERM1, POLYM2, PDERM2, N, ALP, BET, X)
real function hgj (II, Z, ZGJ, NP, ALPHA, BETA)
real *8 function hgjd (II, Z, ZGJ, NP, ALPHA, BETA)
real function hglj (II, Z, ZGLJ, NP, ALPHA, BETA)
real *8 function hgljd (I, Z, ZGLJ, NP, ALPHA, BETA)
subroutine dgj (D, DT, Z, NZ, NZD, ALPHA, BETA)
subroutine dgjd (D, DT, Z, NZ, NZD, ALPHA, BETA)
subroutine dglj (D, DT, Z, NZ, NZD, ALPHA, BETA)
subroutine dgljd (D, DT, Z, NZ, NZD, ALPHA, BETA)
subroutine dgll (D, DT, Z, NZ, NZD)
real function hgll (I, Z, ZGLL, NZ)
real function hgl (I, Z, ZGL, NZ)
real function pnleg (Z, N)
real function pndleg (Z, N)
subroutine dgllgl (D, DT, ZM1, ZM2, IM12, NZM1, NZM2, ND1, ND2)
subroutine dgljgj (D, DT, ZGL, ZG, IGLG, NPGL, NPG, ND1, ND2, ALPHA, BETA)
subroutine dgljgjd (D, DT, ZGL, ZG, IGLG, NPGL, NPG, ND1, ND2, ALPHA, BETA)
subroutine iglm (I12, IT12, Z1, Z2, NZ1, NZ2, ND1, ND2)
subroutine igllm (I12, IT12, Z1, Z2, NZ1, NZ2, ND1, ND2)
subroutine igjm (I12, IT12, Z1, Z2, NZ1, NZ2, ND1, ND2, ALPHA, BETA)
subroutine igljm (I12, IT12, Z1, Z2, NZ1, NZ2, ND1, ND2, ALPHA, BETA)
subroutine invcol2 (A, B, N)
subroutine copy8 (A, B, N)
subroutine copy (A, B, N)
subroutine icopy (A, B, N)
real function hleg (I, ZZ, ZLEG, NZZ)
subroutine hlegn (H, ZH, ZLEG, NZZ)
subroutine sub2 (A, B, N)
subroutine add3 (C, A, B, N)
subroutine sub3 (C, A, B, N)
subroutine add2 (A, B, N)
function almin (A, N)
function almax (A, N)
subroutine igllmt (IT12, Z1, Z2, NZ1, NZ2, ND1, ND2)
subroutine trnsps2 (B, A, N1, N2)
subroutine col3 (A, B, C, N)
subroutine addcol3 (A, B, C, N)
subroutine subcol3 (A, B, C, N)
subroutine addcol4 (A, B, C, D, N)
subroutine subcol4 (A, B, C, D, N)
subroutine izero (IA, N)
subroutine rzero (A, N)
subroutine vdot (DOT, U1, U2, U3, V1, V2, V3, N)
real function pnz (Z, NZ)
real function pnd (Z, NZ)
Function/Subroutine Documentation
subroutine add2 (real, dimension(n) A, real, dimension(n) B, N)
Definition at line 1332 of file legend.f.
References i, and n.
subroutine add3 (real, dimension(1) C, real, dimension(1) A, real, dimension(1) B, N)
Definition at line 1316 of file legend.f.
References i, and n.
subroutine addcol3 (real, dimension(n) A, real, dimension(n) B, real, dimension(n) C, N)
Definition at line 1416 of file legend.f.
References i, and n.
subroutine addcol4 (real, dimension(n) A, real, dimension(n) B, real, dimension(n) C, real, dimension(n) D, N)
Definition at line 1432 of file legend.f.
References i, and n.
function almax (real, dimension(n) A, N)
Definition at line 1356 of file legend.f.
References almax(), i, and n.
function almin (real, dimension(n) A, N)
Definition at line 1340 of file legend.f.
References almin(), i, and n.
subroutine col3 (real, dimension(n) A, real, dimension(n) B, real, dimension(n) C, N)
Definition at line 1408 of file legend.f.
References i, and n.
subroutine copy (real, dimension(n) A, real, dimension(n) B, N)
Definition at line 1226 of file legend.f.
References i, and n.
subroutine copy8 (real*8, dimension(n) A, real*8, dimension(n) B, N)
Definition at line 1218 of file legend.f.
References i, and n.
subroutine dgj (real, dimension(nzd,nzd) D, real, dimension(nzd,nzd) DT, real, dimension(1) Z, NZ, NZD, real ALPHA, real BETA)
Definition at line 660 of file legend.f.
References dgjd(), exitt(), i, j, and nz.
subroutine dgjd (real*8, dimension(nzd,nzd) D, real*8, dimension(nzd,nzd) DT, real*8, dimension(1) Z, NZ, NZD, real*8 ALPHA, real*8 BETA)
Definition at line 704 of file legend.f.
References exitt(), i, j, jacobf(), n, and nz.
subroutine dglj (real, dimension(nzd,nzd) D, real, dimension(nzd,nzd) DT, real, dimension(1) Z, NZ, NZD, real ALPHA, real BETA)
Definition at line 742 of file legend.f.
References dgljd(), exitt(), i, j, and nz.
subroutine dgljd (real*8, dimension(nzd,nzd) D, real*8, dimension(nzd,nzd) DT, real*8, dimension(1) Z, NZ, NZD, real*8 ALPHA, real*8 BETA)
Definition at line 786 of file legend.f.
References exitt(), i, j, jacobf(), n, and nz.
subroutine dgljgj (real, dimension(nd2,nd1) D, real, dimension(nd1,nd2) DT, real, dimension(nd1) ZGL, real, dimension(nd2) ZG, real, dimension(nd2,nd1) IGLG, NPGL, NPG, ND1, ND2, ALPHA, BETA)
Definition at line 1001 of file legend.f.
References alpha, beta, dgljgjd(), exitt(), i, and j.
subroutine dgljgjd (real*8, dimension(nd2,nd1) D, real*8, dimension(nd1,nd2) DT, real*8, dimension(nd1) ZGL, real*8, dimension(nd2) ZG, real*8, dimension(nd2,nd1) IGLG, NPGL, NPG, ND1, ND2, real*8 ALPHA, real*8 BETA)
Definition at line 1055 of file legend.f.
References exitt(), i, j, and jacobf().
subroutine dgll (real, dimension(nzd,nzd) D, real, dimension(nzd,nzd) DT, real, dimension(1) Z, NZ, NZD)
Definition at line 832 of file legend.f.
References i, j, n, nz, and pnleg().
subroutine dgllgl (real, dimension(nd2,nd1) D, real, dimension(nd1,nd2) DT, real, dimension(nd1) ZM1, real, dimension(nd2) ZM2, real, dimension(nd2,nd1) IM12, NZM1, NZM2, ND1, ND2)
Definition at line 966 of file legend.f.
References pnleg().
real*8 function endw1 (N, real*8 ALPHA, real*8 BETA)
Definition at line 311 of file legend.f.
References alpha, beta, gammaf(), i, and n.
real*8 function endw2 (N, real*8 ALPHA, real*8 BETA)
Definition at line 355 of file legend.f.
References alpha, beta, gammaf(), i, and n.
real*8 function gammaf (real*8 X)
Definition at line 399 of file legend.f.
References gammaf().
real function hgj (II, real Z, real, dimension(1) ZGJ, NP, real ALPHA, real BETA)
Definition at line 548 of file legend.f.
References exitt(), hgj(), hgjd(), and i.
real*8 function hgjd (II, real*8 Z, real*8, dimension(1) ZGJ, NP, real*8 ALPHA, real*8 BETA)
Definition at line 578 of file legend.f.
References hgjd(), and jacobf().
real function hgl (I, Z, real, dimension(1) ZGL, NZ)
Definition at line 888 of file legend.f.
References hgl(), i, n, nz, pndleg(), and pnleg().
real function hglj (II, real Z, real, dimension(1) ZGLJ, NP, real ALPHA, real BETA)
Definition at line 602 of file legend.f.
References exitt(), hglj(), hgljd(), and i.
real*8 function hgljd (I, real*8 Z, real*8, dimension(1) ZGLJ, NP, real*8 ALPHA, real*8 BETA)
Definition at line 632 of file legend.f.
References hgljd(), i, jacobf(), and n.
real function hgll (I, Z, real, dimension(1) ZGLL, NZ)
Definition at line 867 of file legend.f.
References hgll(), i, n, nz, pndleg(), and pnleg().
real function hleg (I, ZZ, real, dimension(nzz) ZLEG, NZZ)
Definition at line 1242 of file legend.f.
References hleg(), i, pnd(), and pnz().
subroutine hlegn (real, dimension(1) H, ZH, real, dimension(1) ZLEG, NZZ)
Definition at line 1270 of file legend.f.
References i, pnd(), and pnz().
subroutine icopy (integer, dimension(1) A, integer, dimension(1) B, N)
Definition at line 1234 of file legend.f.
References i, and n.
subroutine igjm (real, dimension(nd2,nd1) I12, real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, NZ1, NZ2, ND1, ND2, ALPHA, BETA)
Definition at line 1158 of file legend.f.
References alpha, beta, hgj(), i, and j.
subroutine igljm (real, dimension(nd2,nd1) I12, real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, NZ1, NZ2, ND1, ND2, ALPHA, BETA)
Definition at line 1184 of file legend.f.
References alpha, beta, hglj(), i, and j.
subroutine igllm (real, dimension(nd2,nd1) I12, real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, NZ1, NZ2, ND1, ND2)
Definition at line 1133 of file legend.f.
References hgll(), i, and j.
subroutine igllmt (real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, NZ1, NZ2, ND1, ND2)
Definition at line 1372 of file legend.f.
References hlegn(), and i.
subroutine iglm (real, dimension(nd2,nd1) I12, real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, NZ1, NZ2, ND1, ND2)
Definition at line 1108 of file legend.f.
References hgl(), i, and j.
subroutine invcol2 (real, dimension(1) A, real, dimension(1) B, N)
Definition at line 1210 of file legend.f.
References i, and n.
subroutine izero (dimension(1) IA, N)
Definition at line 1448 of file legend.f.
References i, ia, and n.
subroutine jacg (real*8, dimension(1) XJAC, NP, ALPHA, BETA)
Definition at line 449 of file legend.f.
References alpha, beta, exitt(), i, j, jacobf(), n, and swap().
subroutine jacobf (POLY, PDER, POLYM1, PDERM1, POLYM2, PDERM2, N, ALP, BET, X)
Definition at line 508 of file legend.f.
References n.
subroutine legend (ZPTS, WGHT, N)
Definition at line 18 of file legend.f.
References n, and zwgll().
real function pnd (Z, NZ)
Definition at line 1488 of file legend.f.
References n, nz, and pnd().
real function pndleg (Z, N)
Definition at line 939 of file legend.f.
References n, and pndleg().
real function pnleg (Z, N)
Definition at line 907 of file legend.f.
References n, and pnleg().
real*8 function pnormj (N, real*8 ALPHA, real*8 BETA)
Definition at line 423 of file legend.f.
References gammaf(), i, n, and pnormj().
real function pnz (Z, NZ)
Definition at line 1476 of file legend.f.
References n, nz, and pnz().
subroutine rzero (dimension(1) A, N)
Definition at line 1455 of file legend.f.
References i, and n.
subroutine sub2 (real, dimension(1) A, real, dimension(1) B, N)
Definition at line 1308 of file legend.f.
References i, and n.
subroutine sub3 (real, dimension(1) C, real, dimension(1) A, real, dimension(1) B, N)
Definition at line 1324 of file legend.f.
References i, and n.
subroutine subcol3 (real, dimension(n) A, real, dimension(n) B, real, dimension(n) C, N)
Definition at line 1424 of file legend.f.
References i, and n.
subroutine subcol4 (real, dimension(n) A, real, dimension(n) B, real, dimension(n) C, real, dimension(n) D, N)
Definition at line 1440 of file legend.f.
References i, and n.
subroutine trnsps2 (dimension(n2,n1) B, dimension(n1,n2) A, N1, N2)
Definition at line 1394 of file legend.f.
References i, and j.
subroutine vdot (dimension(n) DOT, dimension(n) U1, dimension(n) U2, dimension(n) U3, dimension(n) V1, dimension(n) V2, dimension(n) V3, N)
Definition at line 1462 of file legend.f.
References dot(), i, and n.
subroutine zwgj (real, dimension(1) Z, real, dimension(1) W, NP, real ALPHA, real BETA)
Definition at line 150 of file legend.f.
References i, and zwgjd().
subroutine zwgjd (real*8, dimension(1) Z, real*8, dimension(1) W, NP, real*8 ALPHA, real*8 BETA)
Definition at line 182 of file legend.f.
References exitt(), gammaf(), i, jacg(), jacobf(), n, and pnormj().
subroutine zwgl (real, dimension(1) Z, real, dimension(1) W, NP)
Definition at line 116 of file legend.f.
References alpha, beta, and zwgj().
subroutine zwglj (real, dimension(1) Z, real, dimension(1) W, NP, real ALPHA, real BETA)
Definition at line 234 of file legend.f.
References exitt(), i, and zwgljd().
subroutine zwgljd (real*8, dimension(np) Z, real*8, dimension(np) W, NP, real*8 ALPHA, real*8 BETA)
Definition at line 266 of file legend.f.
References endw1(), endw2(), exitt(), i, jacobf(), n, and zwgjd().
subroutine zwgll (real, dimension(1) Z, real, dimension(1) W, NP)
Definition at line 133 of file legend.f.
References alpha, beta, and zwglj().