KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/subs.f File Reference
subs.f File Reference
Functions/Subroutines
subroutine sort (a, ind, n)
subroutine swap (a, w, ind, n)
subroutine isort (a, ind, n)
subroutine swap8 (a, w, ind, n)
subroutine iswap (a, w, ind, n)
subroutine chswap (a, w, l, ind, n)
subroutine ljust (string)
subroutine capit (lettrs, n)
subroutine parse (lines, args, ia)
subroutine blank (string, n)
subroutine chfill (string, s, n)
function vlsum (a, n)
function vlsc2 (a, b, n)
subroutine cmult (a, b, n)
subroutine chcopy (a, b, n)
function ltrunc (string, l)
subroutine roots (xval, nroots, ftargt, f, n)
subroutine vsqrt (a, n)
subroutine vcnvert (a, n)
subroutine convert (t)
subroutine deltmp
function iglmin (a, n)
function iglmax (a, n)
function glsc2 (a, b, n)
function glamax (a, n)
function vlmax (a, n)
function vlmin (a, n)
function glmax (a, n)
function glmin (a, n)
function mod1 (i, n)
integer function indx1 (s1, s2, l2)
integer function nindx1 (s1, s2, l2)
subroutine jfill (x, i, n)
function glsum (a, n)
subroutine add2s1 (x, y, c, n)
subroutine add2s2 (x, y, c, n)
subroutine cmult2 (x, y, c, n)
subroutine cadd (x, c, n)
subroutine normalize (x, s, n)
subroutine orthogonalize (y, x, n)
subroutine rank (A, IND, N)
subroutine irank (a, ind, n)
subroutine iswap_ip (x, p, n)
Function/Subroutine Documentation
subroutine add2s1 (real, dimension(1) x, real, dimension(1) y, real c, n)
Definition at line 607 of file subs.f.
References i, and n.
subroutine add2s2 (real, dimension(1) x, real, dimension(1) y, real c, n)
Definition at line 615 of file subs.f.
References i, and n.
subroutine blank (character*1, dimension(n) string, n)
Definition at line 267 of file subs.f.
References i, and n.
subroutine cadd (real, dimension(1) x, real c, n)
Definition at line 631 of file subs.f.
References i, and n.
subroutine capit (character, dimension(n) lettrs, n)
Definition at line 206 of file subs.f.
References i, and n.
subroutine chcopy (character*1, dimension(1) a, character*1, dimension(1) b, n)
Definition at line 313 of file subs.f.
References i, and n.
subroutine chfill (character*1, dimension(n) string, character*1 s, n)
Definition at line 278 of file subs.f.
References i, and n.
subroutine chswap (character*1, dimension(l,1) a, character*1, dimension(l,1) w, l, integer, dimension(1) ind, n)
Definition at line 164 of file subs.f.
References j, and n.
subroutine cmult (dimension(1) a, b, n)
Definition at line 307 of file subs.f.
References i, and n.
subroutine cmult2 (real, dimension(1) x, real, dimension(1) y, real c, n)
Definition at line 623 of file subs.f.
References i, and n.
subroutine convert (t)
Definition at line 374 of file subs.f.
References ione().
subroutine deltmp ()
Definition at line 441 of file subs.f.
References blank().
function glamax (dimension(n) a, n)
Definition at line 487 of file subs.f.
References glamax(), i, and n.
function glmax (dimension(n) a, n)
Definition at line 517 of file subs.f.
References glmax(), i, and n.
function glmin (dimension(n) a, n)
Definition at line 527 of file subs.f.
References glmin(), i, and n.
function glsc2 (real, dimension(n) a, real, dimension(n) b, n)
Definition at line 477 of file subs.f.
References glsc2(), i, and n.
function glsum (real, dimension(1) a, n)
Definition at line 597 of file subs.f.
References glsum(), i, and n.
function iglmax (integer, dimension(1) a, n)
Definition at line 468 of file subs.f.
References i, iglmax(), and n.
function iglmin (integer, dimension(1) a, n)
Definition at line 459 of file subs.f.
References i, iglmin(), and n.
integer function indx1 (character*80 s1, character*80 s2, l2)
Definition at line 551 of file subs.f.
References i, and indx1().
subroutine irank (integer, dimension(1) a, integer, dimension(1) ind, n)
Definition at line 728 of file subs.f.
References i, j, and n.
subroutine isort (integer, dimension(1) a, integer, dimension(1) ind, n)
Definition at line 82 of file subs.f.
References i, j, and n.
subroutine iswap (integer, dimension(1) a, integer, dimension(1) w, integer, dimension(1) ind, n)
Definition at line 148 of file subs.f.
References j, and n.
subroutine iswap_ip (integer, dimension(1) x, integer, dimension(1) p, n)
Definition at line 778 of file subs.f.
References exit(), j, and n.
subroutine jfill (integer, dimension(1) x, i, n)
Definition at line 589 of file subs.f.
References i, j, and n.
subroutine ljust (character*1, dimension(80) string)
Definition at line 184 of file subs.f.
References i, and j.
function ltrunc (character*1, dimension(l) string, l)
Definition at line 320 of file subs.f.
References i, and ltrunc().
function mod1 (i, n)
Definition at line 537 of file subs.f.
References i, mod1(), n, and prs().
integer function nindx1 (character*80 s1, character*80 s2, l2)
Definition at line 568 of file subs.f.
References i, and nindx1().
subroutine normalize (real, dimension(1) x, s, n)
Definition at line 639 of file subs.f.
References i, and n.
subroutine orthogonalize (real, dimension(1) y, real, dimension(1) x, n)
Definition at line 654 of file subs.f.
References glsc2(), i, and n.
subroutine parse (character, dimension(70) lines, character, dimension(10,5) args, ia)
Definition at line 219 of file subs.f.
References capit(), i, ia, and j.
subroutine rank (real, dimension(1) A, integer, dimension(1) IND, N)
Definition at line 676 of file subs.f.
References i, j, and n.
subroutine roots (dimension(2,n) xval, nroots, ftargt, dimension(0:n) f, n)
Definition at line 333 of file subs.f.
References i, and n.
subroutine sort (dimension(1) a, dimension(1) ind, n)
Definition at line 18 of file subs.f.
References i, j, and n.
subroutine swap (dimension(1) a, dimension(1) w, dimension(1) ind, n)
Definition at line 66 of file subs.f.
References j, and n.
subroutine swap8 (real*8, dimension(1) a, real*8, dimension(1) w, integer, dimension(1) ind, n)
Definition at line 131 of file subs.f.
References j, and n.
subroutine vcnvert (real*4, dimension(1) a, n)
Definition at line 367 of file subs.f.
References convert(), i, and n.
function vlmax (dimension(n) a, n)
Definition at line 497 of file subs.f.
References i, n, and vlmax().
function vlmin (dimension(n) a, n)
Definition at line 507 of file subs.f.
References i, n, and vlmin().
function vlsc2 (real, dimension(1) a, real, dimension(1) b, n)
Definition at line 297 of file subs.f.
References i, n, and vlsc2().
function vlsum (real, dimension(1) a, n)
Definition at line 287 of file subs.f.
References i, n, and vlsum().
subroutine vsqrt (dimension(1) a, n)
Definition at line 361 of file subs.f.
References i, and n.