KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/xdriver.c File Reference
xdriver.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/cursorfont.h>
#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <X11/Xos.h>
#include <X11/Xatom.h>
#include <X11/Xresource.h>
#include "icon"
Data Structures
struct mse_event_rec
Macros
#define NUM_COLOR_CELLS (64+16)
#define check_width 16
#define check_height 16
#define MOUSE 0
#define LINE 1
Functions
void xmainloop ()
int Quit ()
void error ()
void Random_Seed (unsigned seed)
int Random_Integer (int lb, int ub)
int x_num_colors (void)
void resetXPRINT ()
void SetUpEnv ()
void getwin_ (float *width, float *height)
void xplanes_ (int *nplanes)
void xwaitm_ (int *button, float *xmouse, float *ymouse)
void beep_ ()
void gets_ (char *line)
void xdrawto_ (float *x, float *y)
void xmove_ (float *x, float *y)
void xcmap_ (red, green, blue, int *num)
void hmt_xcmap_ (red, green, blue, int *num)
void hmt_xsetfill_ (int *icolor)
void xsetfill_ (int *icolor)
void xsetpen_ (int *icolor)
void xpoly_ (float *xfill, float *yfill, int *nvertices, int *boundary)
void xclear_ ()
void xcleara_ ()
void xputxt_ (float *x, float *y, float *fontsize, char *string, int *strlength)
void advanceLine ()
void puts_ (char *message, int *nchars)
void showChar (char c)
void backSpace ()
void TypeChar (char c)
void xmainloop (int code)
void closew_ ()
void error (char *mesg)
void mainc_ ()
Variables
Display * dpy = NULL
int windowh = 950
int windoww =1022
int vfx = 0
int vfy = 0
int char_spacing = 6
int line_spacing = 15
int text_screenh = 150
int left_margin = 000
char Line [10][90]
int active_line = 0
int top_line = 0
int num_lines = 10
Macro Definition Documentation
#define check_height 16
Definition at line 77 of file xdriver.c.
#define check_width 16
Definition at line 76 of file xdriver.c.
#define LINE 1
Definition at line 84 of file xdriver.c.
#define MOUSE 0
Definition at line 83 of file xdriver.c.
#define NUM_COLOR_CELLS (64+16)
Definition at line 16 of file xdriver.c.
Function Documentation
void advanceLine ()
Definition at line 635 of file xdriver.c.
References active_line, dpy, i, left_margin, Line, line_spacing, num_lines, text_screenh, top_line, and windowh.
void backSpace ()
Definition at line 718 of file xdriver.c.
References char_spacing, and dpy.
void beep_ ()
Definition at line 312 of file xdriver.c.
References dpy.
void closew_ ()
Definition at line 845 of file xdriver.c.
References Quit().
void error ()
void error (char * mesg)
Definition at line 851 of file xdriver.c.
References exit().
void gets_ (char * line)
Definition at line 327 of file xdriver.c.
References i, LINE, x, xmainloop(), and y().
void getwin_ (float * width, float* height)
Definition at line 269 of file xdriver.c.
References windowh, and windoww.
void hmt_xcmap_ (red , green , blue , int * num)
Definition at line 398 of file xdriver.c.
References dpy, i, NUM_COLOR_CELLS, printf(), Random_Integer(), and Random_Seed().
void hmt_xsetfill_ (int * icolor)
Definition at line 484 of file xdriver.c.
References dpy, and NUM_COLOR_CELLS.
void mainc_ (void)
Definition at line 865 of file xdriver.c.
References Quit(), and SetUpEnv().
void puts_ (char * message, int * nchars)
Definition at line 680 of file xdriver.c.
References active_line, advanceLine(), dpy, i, and Line.
int Quit ()
Definition at line 835 of file xdriver.c.
References dpy, and exit().
int Random_Integer (int lb, int ub)
Definition at line 466 of file xdriver.c.
void Random_Seed (unsigned seed)
Definition at line 457 of file xdriver.c.
void resetXPRINT ()
Definition at line 99 of file xdriver.c.
References dpy, left_margin, text_screenh, and windowh.
void SetUpEnv (void)
Definition at line 108 of file xdriver.c.
References check_height, check_width, dpy, error(), i, j, Line, printf(), resetXPRINT(), vfx, vfy, windowh, and windoww.
void showChar (char c)
Definition at line 706 of file xdriver.c.
References char_spacing, and dpy.
void TypeChar (char c)
Definition at line 735 of file xdriver.c.
References active_line, advanceLine(), backSpace(), dpy, i, Line, Quit(), and showChar().
int x_num_colors (void)
Definition at line 92 of file xdriver.c.
References NUM_COLOR_CELLS.
void xclear_ ()
Definition at line 557 of file xdriver.c.
References dpy, i, line_spacing, text_screenh, windowh, windoww, and xsetfill_().
void xcleara_ ()
Definition at line 583 of file xdriver.c.
References dpy, i, line_spacing, text_screenh, windowh, windoww, x, xsetfill_(), and y().
void xcmap_ (red , green , blue , int * num)
Definition at line 376 of file xdriver.c.
References dpy, and i.
void xdrawto_ (float * x, float* y)
Definition at line 349 of file xdriver.c.
References dpy.
void xmainloop ()
void xmainloop (int code)
Definition at line 772 of file xdriver.c.
References mse_event_rec::buttonNumber, dpy, exit(), i, if(), LINE, MOUSE, printf(), TypeChar(), mse_event_rec::xclicked, and mse_event_rec::yclicked.
void xmove_ (float * x, float* y)
Definition at line 364 of file xdriver.c.
References dpy.
void xplanes_ (int * nplanes)
Definition at line 280 of file xdriver.c.
References dpy.
void xpoly_ (float * xfill, float * yfill, int * nvertices, int * boundary)
Definition at line 527 of file xdriver.c.
References dpy, and i.
void xputxt_ (float * x, float* y, float* fontsize, char * string, int * strlength)
Definition at line 618 of file xdriver.c.
References dpy.
void xsetfill_ (int * icolor)
Definition at line 502 of file xdriver.c.
References dpy.
void xsetpen_ (int * icolor)
Definition at line 514 of file xdriver.c.
References dpy, and NUM_COLOR_CELLS.
void xwaitm_ (int * button, float * xmouse, float* ymouse)
Definition at line 290 of file xdriver.c.
References mse_event_rec::buttonNumber, dpy, MOUSE, text_screenh, windowh, mse_event_rec::xclicked, xmainloop(), and mse_event_rec::yclicked.
Variable Documentation
int active_line = 0
Definition at line 54 of file xdriver.c.
int char_spacing = 6
Definition at line 49 of file xdriver.c.
Display* dpy = NULL
Definition at line 25 of file xdriver.c.
int left_margin = 000
Definition at line 52 of file xdriver.c.
char Line[10][90]
Definition at line 53 of file xdriver.c.
int line_spacing = 15
Definition at line 50 of file xdriver.c.
int num_lines = 10
Definition at line 56 of file xdriver.c.
int text_screenh = 150
Definition at line 51 of file xdriver.c.
int top_line = 0
Definition at line 55 of file xdriver.c.
int vfx = 0
Definition at line 44 of file xdriver.c.
int vfy = 0
Definition at line 44 of file xdriver.c.
int windowh = 950
Definition at line 42 of file xdriver.c.
int windoww =1022
Definition at line 42 of file xdriver.c.