KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/prenek.f File Reference
prenek.f File Reference
Functions/Subroutines
subroutine fprep
subroutine read_params
subroutine build_options
subroutine after_build
subroutine reauni
function rmaxx (r, nelm, nel, nc)
function rminx (r, nelm, nel, nc)
function rbarx (r, nelm, nel, nc)
function rmax (r, n)
function rmin (r, n)
function rbar (r, n)
subroutine wrtpar (cflag)
subroutine seteqt
subroutine chkeqt (ierr)
subroutine setreq
subroutine setpar
subroutine ckpar (mode, ierr)
subroutine readln (locate)
subroutine prexit
subroutine session_exit
subroutine erexit
subroutine init
subroutine output
subroutine histry
subroutine integq
subroutine objec
subroutine delobj (isobjt)
subroutine getfac (iface, iel, cflag, isobjt)
subroutine drivef
subroutine drivfc (ipscal)
subroutine intcnd
subroutine initfun
subroutine initpre
subroutine initres
subroutine helper (routine, ientry)
subroutine initdef
subroutine exitt
subroutine exit
subroutine init_param
subroutine init_cparam
subroutine init_vparam
Function/Subroutine Documentation
subroutine after_build ()
Definition at line 303 of file prenek.f.
References drawel(), drgrid(), drivef(), drmenu(), histry(), i, intcnd(), integq(), menu(), objec(), output(), prexit(), prs(), prsis(), refresh(), session_exit(), and setzoom().
subroutine build_options ()
Definition at line 183 of file prenek.f.
References ckpar(), i, ltrunc(), menu(), n, openf(), prs(), prsrs(), reauni(), res(), seteqt(), and setpar().
subroutine chkeqt (ierr)
Definition at line 979 of file prenek.f.
References prs().
subroutine ckpar (character*5 mode, ierr)
Definition at line 1291 of file prenek.f.
References i, prs(), and setreq().
subroutine delobj (isobjt)
Definition at line 2429 of file prenek.f.
References gwrite().
subroutine drivef ()
Definition at line 2533 of file prenek.f.
References capit(), drivfc(), prs(), and readln().
subroutine drivfc (ipscal)
Definition at line 2560 of file prenek.f.
References prs(), prsi(), and res().
subroutine erexit ()
Definition at line 1697 of file prenek.f.
References devex(), exitt(), and prs().
subroutine exit ()
Definition at line 3032 of file prenek.f.
subroutine exitt ()
Definition at line 3021 of file prenek.f.
References nx, and nz.
subroutine fprep ()
Definition at line 17 of file prenek.f.
References after_build(), blank(), build(), build_options(), chcopy(), data(), gnable(), indx1(), init(), ltrunc(), menu(), openf(), prs(), read_params(), res(), seteqt(), and setpar().
subroutine getfac (iface, iel, character*6 cflag, isobjt)
Definition at line 2465 of file prenek.f.
References color, drawed(), gwrite(), i, mouse(), move(), penw(), prs(), rerr(), rmin(), xscr(), and yscr().
subroutine helper (character, dimension(*) routine, ientry)
Definition at line 2933 of file prenek.f.
References prs().
subroutine histry ()
Definition at line 1993 of file prenek.f.
References color, drawel(), drelev(), i, j, menu(), mouse(), nx, nz, penw(), prs(), rer(), rerr(), rmin(), xdot(), xscr(), and yscr().
subroutine init ()
Definition at line 1707 of file prenek.f.
References beginb(), blank(), chcopy(), clear(), clrmap(), clsseg(), color, devini(), drawsc(), endp(), fillp(), findfl(), gindis(), gwrite(), hard(), i, init_param(), initps(), initqms(), n, nohard(), openf(), opnseg(), prs(), res(), setenv(), sgvis(), xphy(), and yphy().
subroutine init_cparam ()
Definition at line 3046 of file prenek.f.
References blank(), and i.
subroutine init_param ()
Definition at line 3037 of file prenek.f.
References init_cparam(), and init_vparam().
subroutine init_vparam ()
Definition at line 3155 of file prenek.f.
References rzero().
subroutine initdef ()
Definition at line 2999 of file prenek.f.
References blank(), capit(), i, ljust(), prs(), and res().
subroutine initfun ()
Definition at line 2665 of file prenek.f.
References blank(), pris(), prs(), and res().
subroutine initpre ()
Definition at line 2738 of file prenek.f.
References blank(), capit(), chcopy(), helper(), i, ljust(), ltrunc(), prs(), and res().
subroutine initres ()
Definition at line 2817 of file prenek.f.
References blank(), capit(), chcopy(), helper(), i, indx1(), ljust(), ltrunc(), prs(), rei(), and res().
subroutine intcnd ()
Definition at line 2637 of file prenek.f.
References chcopy(), initdef(), initfun(), initpre(), initres(), and menu().
subroutine integq ()
Definition at line 2239 of file prenek.f.
References i, menu(), and prs().
subroutine objec ()
Definition at line 2286 of file prenek.f.
References delobj(), drawel(), drelev(), getfac(), gwrite(), i, menu(), prs(), prsi(), and res().
subroutine output ()
Definition at line 1871 of file prenek.f.
References i, menu(), prs(), prsis(), and res().
subroutine prexit ()
Definition at line 1376 of file prenek.f.
References cleara(), curcnt(), erexit(), i, if(), n, session_exit(), and wrtpar().
function rbar (real, dimension(n) r, n)
Definition at line 576 of file prenek.f.
References i, and n.
function rbarx (real, dimension(8,nelm) r, nelm, nel, nc)
Definition at line 545 of file prenek.f.
References i, and j.
subroutine read_params ()
Definition at line 100 of file prenek.f.
References blank(), chcopy(), ckpar(), i, nindx1(), and prs().
subroutine readln (locate)
Definition at line 1348 of file prenek.f.
References capit(), erexit(), prs(), and res().
subroutine reauni ()
Definition at line 423 of file prenek.f.
References i, pris(), prs(), prsis(), rbarx(), rmaxx(), and rminx().
function rmax (real, dimension(n) r, n)
Definition at line 556 of file prenek.f.
References i, and n.
function rmaxx (real, dimension(8,nelm) r, nelm, nel, nc)
Definition at line 523 of file prenek.f.
References i, and j.
function rmin (real, dimension(n) r, n)
Definition at line 566 of file prenek.f.
References i, and n.
function rminx (real, dimension(8,nelm) r, nelm, nel, nc)
Definition at line 534 of file prenek.f.
References i, and j.
subroutine session_exit ()
Definition at line 1682 of file prenek.f.
References deltmp(), devex(), exitt(), and prs().
subroutine seteqt ()
Definition at line 656 of file prenek.f.
References chkeqt(), drcovr(), i, menu(), prs(), and prsis().
subroutine setpar ()
Definition at line 1076 of file prenek.f.
References beginb(), clsseg(), color, delseg(), drawsc(), drcovr(), drmenu(), endp(), fillp(), gindis(), gnable(), gswrit(), i, movesc(), nx, opnseg(), prs(), prsi(), prsir(), reader(), rer(), res(), setreq(), xphy(), and yphy().
subroutine setreq ()
Definition at line 1000 of file prenek.f.
References i.
subroutine wrtpar (character cflag)
Definition at line 586 of file prenek.f.
References chcopy(), i, j, ltrunc(), n, openf(), and prs().