KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/mxm.f File Reference
mxm.f File Reference
Functions/Subroutines
subroutine mxm (A, N1, B, N2, C, N3)
subroutine mxm1 (a, n1, b, n2, c, n3)
subroutine mxm2 (a, n1, b, n2, c, n3)
subroutine mxm3 (a, n1, b, n2, c, n3)
subroutine mxm4 (a, n1, b, n2, c, n3)
subroutine mxm5 (a, n1, b, n2, c, n3)
subroutine mxm6 (a, n1, b, n2, c, n3)
subroutine mxm7 (a, n1, b, n2, c, n3)
subroutine mxm8 (a, n1, b, n2, c, n3)
subroutine mxm9 (a, n1, b, n2, c, n3)
subroutine mxm10 (a, n1, b, n2, c, n3)
subroutine mxm11 (a, n1, b, n2, c, n3)
subroutine mxm12 (a, n1, b, n2, c, n3)
subroutine mxm13 (a, n1, b, n2, c, n3)
subroutine mxm14 (a, n1, b, n2, c, n3)
subroutine mxm15 (a, n1, b, n2, c, n3)
subroutine mxm16 (a, n1, b, n2, c, n3)
Function/Subroutine Documentation
subroutine mxm (real, dimension(n1,n2) A, N1, real, dimension(n2,n3) B, N2, real, dimension(n1,n3) C, N3)
Definition at line 2 of file mxm.f.
References i, j, mxm1(), mxm10(), mxm11(), mxm12(), mxm13(), mxm14(), mxm15(), mxm16(), mxm2(), mxm3(), mxm4(), mxm5(), mxm6(), mxm7(), mxm8(), and mxm9().
subroutine mxm1 (real, dimension(n1,1) a, n1, real, dimension(1,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 62 of file mxm.f.
References i, and j.
subroutine mxm10 (real, dimension(n1,10) a, n1, real, dimension(10,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 197 of file mxm.f.
References i, and j.
subroutine mxm11 (real, dimension(n1,11) a, n1, real, dimension(11,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 217 of file mxm.f.
References i, and j.
subroutine mxm12 (real, dimension(n1,12) a, n1, real, dimension(12,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 238 of file mxm.f.
References i, and j.
subroutine mxm13 (real, dimension(n1,13) a, n1, real, dimension(13,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 260 of file mxm.f.
References i, and j.
subroutine mxm14 (real, dimension(n1,14) a, n1, real, dimension(14,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 283 of file mxm.f.
References i, and j.
subroutine mxm15 (real, dimension(n1,15) a, n1, real, dimension(15,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 307 of file mxm.f.
References i, and j.
subroutine mxm16 (real, dimension(n1,16) a, n1, real, dimension(16,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 332 of file mxm.f.
References i, and j.
subroutine mxm2 (real, dimension(n1,2) a, n1, real, dimension(2,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 73 of file mxm.f.
References i, and j.
subroutine mxm3 (real, dimension(n1,3) a, n1, real, dimension(3,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 85 of file mxm.f.
References i, and j.
subroutine mxm4 (real, dimension(n1,4) a, n1, real, dimension(4,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 98 of file mxm.f.
References i, and j.
subroutine mxm5 (real, dimension(n1,5) a, n1, real, dimension(5,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 112 of file mxm.f.
References i, and j.
subroutine mxm6 (real, dimension(n1,6) a, n1, real, dimension(6,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 127 of file mxm.f.
References i, and j.
subroutine mxm7 (real, dimension(n1,7) a, n1, real, dimension(7,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 143 of file mxm.f.
References i, and j.
subroutine mxm8 (real, dimension(n1,8) a, n1, real, dimension(8,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 160 of file mxm.f.
References i, and j.
subroutine mxm9 (real, dimension(n1,9) a, n1, real, dimension(9,n3) b, n2, real, dimension(n1,n3) c, n3)
Definition at line 178 of file mxm.f.
References i, and j.