KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/xinterface.f File Reference
xinterface.f File Reference
Functions/Subroutines
program mainf
subroutine reader (VALUE, IERR)
subroutine openf (IUNIT, FILE, STATUS, ITYPE, IERR)
subroutine findfl (SESION, OLDVER)
subroutine mouse (XMOUSE, YMOUSE, BUTTON)
subroutine move (X, Y)
subroutine draw (X, Y)
subroutine movesc (X, Y)
subroutine drawsc (X, Y)
subroutine beginp (X1, Y1)
subroutine beginb (X1, Y1)
subroutine gnable
subroutine gindis
subroutine sgvis (iseg, ivisibility)
subroutine heject
subroutine clsseg
subroutine opnseg (ISEG)
subroutine delseg (ISEG)
subroutine penw (IWIDTH)
subroutine scroll (ILINES)
subroutine rubber
subroutine offrub
subroutine gwrite (X, Y, SIZE, STRING)
subroutine gswrit (X, Y, SIZE, STRING)
subroutine devini (DEVICE)
subroutine devex
subroutine endp
subroutine fillp (ICOLOR)
subroutine hmt_fillp (ICOLOR)
subroutine clear
subroutine cleara
subroutine color (ICOLOR)
subroutine hmt_color (ICOLOR)
subroutine clrmap (TYPE)
function scoordx (WORLDX)
function scoordy (WORLDY)
subroutine openfld (IUNIT, FILE, suffix, STATUS, IFFMAT, IERR)
subroutine mouse2 (xmouse, ymouse, button, ifout)
Function/Subroutine Documentation
subroutine beginb (X1, Y1)
Definition at line 232 of file xinterface.f.
References ifill(), move(), and movec().
subroutine beginp (X1, Y1)
Definition at line 211 of file xinterface.f.
References ifill(), move(), and movec().
subroutine clear ()
Definition at line 410 of file xinterface.f.
subroutine cleara ()
Definition at line 416 of file xinterface.f.
subroutine clrmap (character*4 TYPE)
Definition at line 526 of file xinterface.f.
References color, and i.
subroutine clsseg ()
Definition at line 274 of file xinterface.f.
subroutine color (ICOLOR)
Definition at line 424 of file xinterface.f.
References i.
subroutine delseg (ISEG)
Definition at line 282 of file xinterface.f.
subroutine devex ()
Definition at line 369 of file xinterface.f.
subroutine devini (DEVICE)
Definition at line 353 of file xinterface.f.
subroutine draw (X, Y)
Definition at line 155 of file xinterface.f.
References drawsc(), xscr(), and yscr().
subroutine drawsc (X, Y)
Definition at line 185 of file xinterface.f.
References ifill(), scoordx(), and scoordy().
subroutine endp ()
Definition at line 378 of file xinterface.f.
References ifill().
subroutine fillp (ICOLOR)
Definition at line 393 of file xinterface.f.
References iabs.
subroutine findfl (SESION, OLDVER)
Definition at line 60 of file xinterface.f.
subroutine gindis ()
Definition at line 255 of file xinterface.f.
subroutine gnable ()
Definition at line 251 of file xinterface.f.
subroutine gswrit (X, Y, SIZE, character, dimension(100) STRING)
Definition at line 326 of file xinterface.f.
References i, movesc(), prs(), scoordx(), and scoordy().
subroutine gwrite (X, Y, SIZE, character, dimension(100) STRING)
Definition at line 317 of file xinterface.f.
References gswrit(), xscr(), and yscr().
subroutine heject ()
Definition at line 263 of file xinterface.f.
References penw().
subroutine hmt_color (ICOLOR)
Definition at line 473 of file xinterface.f.
References i.
subroutine hmt_fillp (ICOLOR)
Definition at line 402 of file xinterface.f.
References iabs.
program mainf ()
Definition at line 1 of file xinterface.f.
subroutine mouse (XMOUSE, YMOUSE, BUTTON)
Definition at line 64 of file xinterface.f.
References filter(), prs(), prsr(), xphy(), and yphy().
subroutine mouse2 (xmouse, ymouse, button, logical ifout)
Definition at line 725 of file xinterface.f.
References filter(), i, prs(), prsr(), prsrr(), rmin(), xphy(), and yphy().
subroutine move (X, Y)
Definition at line 150 of file xinterface.f.
References movesc(), xscr(), and yscr().
subroutine movesc (X, Y)
Definition at line 160 of file xinterface.f.
References ifill(), scoordx(), and scoordy().
subroutine offrub ()
Definition at line 313 of file xinterface.f.
subroutine openf (IUNIT, character*(*) FILE, character*(*) STATUS, ITYPE, IERR)
Definition at line 23 of file xinterface.f.
References i.
subroutine openfld (IUNIT, character*(*) FILE, integer suffix, character*(*) STATUS, logical IFFMAT, IERR)
Definition at line 652 of file xinterface.f.
References blank(), chcopy(), i, and indx1().
subroutine opnseg (ISEG)
Definition at line 278 of file xinterface.f.
subroutine penw (IWIDTH)
Definition at line 286 of file xinterface.f.
subroutine reader (VALUE, IERR)
Definition at line 6 of file xinterface.f.
subroutine rubber ()
Definition at line 309 of file xinterface.f.
function scoordx (WORLDX)
Definition at line 640 of file xinterface.f.
References scoordx().
function scoordy (WORLDY)
Definition at line 647 of file xinterface.f.
References scoordy().
subroutine scroll (ILINES)
Definition at line 305 of file xinterface.f.
subroutine sgvis (iseg, ivisibility)
Definition at line 259 of file xinterface.f.