KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/postnek6.f File Reference
postnek6.f File Reference
Functions/Subroutines
subroutine setquad
subroutine drquad
subroutine xdiam3 (XYZ)
subroutine mapxc (XYZ, IE)
subroutine decod (IX, IY, IZ, IE, IXYZ, NX, NY, NZ)
subroutine setsrfp (SRFQAL, NQUAL, IFLD)
subroutine sortl
subroutine signpl (Lplane)
subroutine gencen
subroutine gen_neigh
subroutine out27 (x, y, z, e, name4)
Function/Subroutine Documentation
subroutine decod (IX, IY, IZ, IE, IXYZ, NX, NY, NZ)
Definition at line 286 of file postnek6.f.
References nx, and nz.
subroutine drquad ()
Definition at line 233 of file postnek6.f.
References color, and xdiam3().
subroutine gen_neigh ()
Definition at line 540 of file postnek6.f.
References gencen(), izero(), and mkside().
subroutine gencen ()
Definition at line 460 of file postnek6.f.
References genxyz_e(), i, j, prexit(), rzero(), and vsqrt().
subroutine mapxc (dimension(3,8) XYZ, IE)
Definition at line 263 of file postnek6.f.
References i.
subroutine out27 (real, dimension(3,3,3) x, real, dimension(3,3,3) y, real, dimension(3,3,3) z, integer e, character*4 name4)
Definition at line 580 of file postnek6.f.
References i, and j.
subroutine setquad ()
Definition at line 2 of file postnek6.f.
References gencen(), mapxc(), mod1(), and rzero().
subroutine setsrfp (character*1, dimension(1) SRFQAL, NQUAL, IFLD)
Definition at line 306 of file postnek6.f.
References list, nx, and signpl().
subroutine signpl (Lplane)
Definition at line 397 of file postnek6.f.
References cross(), decod(), i, j, norm3d(), nx, nz, and sub3().
subroutine sortl ()
Definition at line 368 of file postnek6.f.
References decod(), i, iswap(), list, nx, nz, sort(), and ziso().
subroutine xdiam3 (dimension(3) XYZ)
Definition at line 249 of file postnek6.f.
References drawc(), movec(), xiso(), and yiso().