KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/iolib_no_graph.f File Reference
iolib_no_graph.f File Reference
Functions/Subroutines
subroutine prs (s)
subroutine pri (i)
subroutine prr (r)
subroutine prii (i1, i2)
subroutine prrrr (r1, r2, r3)
subroutine prrr (r1, r2)
subroutine prsi (s, i)
subroutine pris (i, s)
subroutine pris4 (i, s)
subroutine pris8 (i, s)
subroutine prsrrr (s, R1, R2, R3)
subroutine prsrr (s, R1, R2)
subroutine prsr (s, r)
subroutine prsii (s, i, j)
subroutine prsir (s, i, r)
subroutine prsis (s1, i, s2)
subroutine prsisi (s1, i1, s2, i2)
subroutine prsrs (s1, r, s2)
subroutine res (s1, n)
subroutine reiii (I, J, K)
subroutine reii (i, J)
subroutine rei (i)
subroutine rer (r1)
subroutine rerr (r1, r2)
subroutine rerrr (r1, r2, r3)
subroutine rerrrr (r1, r2, r3, r4)
subroutine putsold (s, nchars)
subroutine getsold (s)
subroutine prsiii (s, i1, I2, I3)
subroutine priii (i1, i2, i3)
subroutine setgraph (ifgraf)
Function/Subroutine Documentation
subroutine getsold (character s)
Definition at line 712 of file iolib_no_graph.f.
subroutine pri (i)
Definition at line 119 of file iolib_no_graph.f.
References i, and prs().
subroutine prii (i1, i2)
Definition at line 142 of file iolib_no_graph.f.
References prs().
subroutine priii (i1, i2, i3)
Definition at line 746 of file iolib_no_graph.f.
References prs().
subroutine pris (i, character, dimension(*) s)
Definition at line 199 of file iolib_no_graph.f.
References blank(), i, j, prs(), and putsold().
subroutine pris4 (i, character, dimension(*) s)
Definition at line 222 of file iolib_no_graph.f.
References blank(), i, j, prs(), and putsold().
subroutine pris8 (i, character, dimension(*) s)
Definition at line 245 of file iolib_no_graph.f.
References blank(), i, j, prs(), and putsold().
subroutine prr (r)
Definition at line 130 of file iolib_no_graph.f.
References prs().
subroutine prrr (r1, r2)
Definition at line 164 of file iolib_no_graph.f.
References prs().
subroutine prrrr (r1, r2, r3)
Definition at line 153 of file iolib_no_graph.f.
References prs().
subroutine prs (character, dimension(*) s)
Definition at line 57 of file iolib_no_graph.f.
References chcopy(), exitt(), i, j, and putsold().
subroutine prsi (character, dimension(*) s, i)
Definition at line 175 of file iolib_no_graph.f.
References i, j, prs(), and putsold().
subroutine prsii (character, dimension(*) s, i, j)
Definition at line 334 of file iolib_no_graph.f.
References i, j, prs(), and putsold().
subroutine prsiii (character, dimension(*) s, i1, I2, I3)
Definition at line 724 of file iolib_no_graph.f.
References prs().
subroutine prsir (character, dimension(*) s, i, r)
Definition at line 357 of file iolib_no_graph.f.
References i, prs(), and putsold().
subroutine prsis (character, dimension(*) s1, i, character, dimension(*) s2)
Definition at line 379 of file iolib_no_graph.f.
References i, j, prs(), and putsold().
subroutine prsisi (character, dimension(*) s1, i1, character, dimension(*) s2, i2)
Definition at line 419 of file iolib_no_graph.f.
References j, prs(), and putsold().
subroutine prsr (character, dimension(*) s, r)
Definition at line 312 of file iolib_no_graph.f.
References i, prs(), and putsold().
subroutine prsrr (character, dimension(*) s, R1, R2)
Definition at line 290 of file iolib_no_graph.f.
References i, prs(), and putsold().
subroutine prsrrr (character, dimension(*) s, R1, R2, R3)
Definition at line 268 of file iolib_no_graph.f.
References i, prs(), and putsold().
subroutine prsrs (character, dimension(*) s1, r, character, dimension(*) s2)
Definition at line 462 of file iolib_no_graph.f.
References i, prs(), and putsold().
subroutine putsold (character, dimension(*) s, nchars)
Definition at line 703 of file iolib_no_graph.f.
References i.
subroutine rei (i)
Definition at line 579 of file iolib_no_graph.f.
References i, prs(), and res().
subroutine reii (i, J)
Definition at line 555 of file iolib_no_graph.f.
References i, j, prs(), and res().
subroutine reiii (I, J, K)
Definition at line 531 of file iolib_no_graph.f.
References i, j, prs(), and res().
subroutine rer (r1)
Definition at line 604 of file iolib_no_graph.f.
References i, prs(), and res().
subroutine rerr (r1, r2)
Definition at line 629 of file iolib_no_graph.f.
References i, prs(), and res().
subroutine rerrr (r1, r2, r3)
Definition at line 654 of file iolib_no_graph.f.
References i, prs(), and res().
subroutine rerrrr (r1, r2, r3, r4)
Definition at line 679 of file iolib_no_graph.f.
References i, prs(), and res().
subroutine res (character, dimension(*) s1, n)
Definition at line 509 of file iolib_no_graph.f.
References getsold(), i, and n.
subroutine setgraph (logical ifgraf)
Definition at line 755 of file iolib_no_graph.f.