KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/screen.f File Reference
screen.f File Reference
Functions/Subroutines
subroutine setgrd
subroutine drgrid
subroutine refresh
subroutine movec (x1, y1)
subroutine drawc (x1, y1)
subroutine filter (xmouse, ymouse, xscreen, yscreen)
subroutine getobjs
subroutine drwobjs
subroutine drwobj_dash (iobj)
subroutine drwobj (iobj)
subroutine latchob (x1, y1, x0, y0, z0, dist2, k, i, iobj)
subroutine setzoom
subroutine setrans
subroutine rescal
subroutine ellgen (x, y, n, a, b)
subroutine genpair (ynew, x0, y0, x1, y1, a, b)
subroutine redraw_mesh
subroutine redraw_mesh_small
subroutine setobj
subroutine color_test
subroutine bezier
subroutine mouse_diam (xmouse, ymouse, button, iclr)
subroutine dr_bezier (j0, j1)
Function/Subroutine Documentation
subroutine bezier ()
Definition at line 1485 of file screen.f.
References dr_bezier(), i, i0, j, mouse_diam(), prs(), prsii(), and xphy().
subroutine color_test ()
Definition at line 1453 of file screen.f.
References mouse_diam().
subroutine dr_bezier (j0, j1)
Definition at line 1549 of file screen.f.
References color, diam2(), i, i0, and vdraw().
subroutine drawc (x1, y1)
Definition at line 434 of file screen.f.
References dot(), draw(), and move().
subroutine drgrid ()
Definition at line 191 of file screen.f.
References cadd(), cmult2(), color, draw(), drawc(), drawsc(), drwobjs(), gingrd(), gswrit(), gwrite(), i, j, move(), movec(), movesc(), rzero(), vdraw(), xphy(), xscr(), yphy(), and yscr().
subroutine drwobj (iobj)
Definition at line 813 of file screen.f.
References color, diam2(), i, mod1(), npts, and vdraw().
subroutine drwobj_dash (iobj)
Definition at line 779 of file screen.f.
References color, i, mod1(), npts, and vdraw().
subroutine drwobjs ()
Definition at line 763 of file screen.f.
References drwobj(), drwobj_dash(), and i.
subroutine ellgen (real, dimension(0:1) x, real, dimension(0:1) y, n, a, b)
Definition at line 1253 of file screen.f.
References copy(), genpair(), i, j, n, prs(), and rerr().
subroutine filter (xmouse, ymouse, xscreen, yscreen)
Definition at line 565 of file screen.f.
References dist2(), i, j, latchob(), rzero(), xphy(), and yphy().
subroutine genpair (real, dimension(0:1) ynew, x0, y0, x1, y1, a, b)
Definition at line 1343 of file screen.f.
subroutine getobjs ()
Definition at line 726 of file screen.f.
References n, npts, prsii(), prsis(), and redraw_mesh().
subroutine latchob (x1, y1, x0, y0, z0, dist2, k, i, iobj)
Definition at line 834 of file screen.f.
References dist2(), i, and npts.
subroutine mouse_diam (xmouse, ymouse, button, iclr)
Definition at line 1540 of file screen.f.
References diam2(), mouse(), and xphy().
subroutine movec (x1, y1)
Definition at line 416 of file screen.f.
References move().
subroutine redraw_mesh ()
Definition at line 1380 of file screen.f.
References drawel(), drawis(), drgrid(), drmenu(), drwobjs(), i, refresh(), and sortel().
subroutine redraw_mesh_small ()
Definition at line 1405 of file screen.f.
References drawel(), drawis(), drgrid(), drmenu(), drwobjs(), i, refresh(), and sortel().
subroutine refresh ()
Definition at line 383 of file screen.f.
References beginb(), clear(), clsseg(), color, drawsc(), endp(), fillp(), nohard(), opnseg(), sgvis(), xphy(), and yphy().
subroutine rescal ()
Definition at line 1165 of file screen.f.
References xiso(), xphy(), yiso(), and yphy().
subroutine setgrd ()
Definition at line 19 of file screen.f.
References drawel(), drgrid(), i, menu(), prs(), refresh(), rei(), and rer().
subroutine setobj ()
Definition at line 1429 of file screen.f.
References bezier(), getobjs(), menu(), and redraw_mesh().
subroutine setrans ()
Definition at line 1098 of file screen.f.
References color, drawsc(), drgrid(), mouse(), movesc(), prs(), xphy(), xscr(), yphy(), and yscr().
subroutine setzoom ()
Definition at line 862 of file screen.f.
References color, drawc(), drawsc(), mouse(), movec(), movesc(), prs(), rerrrr(), rescal(), scale(), xphy(), xscr(), yphy(), and yscr().