KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/plot.f File Reference
plot.f File Reference
Functions/Subroutines
subroutine data
function xscr (XPHYS)
function yscr (YPHYS)
function xphy (XSCREN)
function yphy (YSCREN)
subroutine gingrd (X1)
subroutine drwbox (X1, Y1, X2, Y2, IC)
subroutine xdot (XX, YY)
subroutine ddummy (IEDGE, IEL)
subroutine dashsc (X1, Y1, X2, Y2, N)
subroutine arrow (X, Y, DXBAR, DYBAR, SARROW)
subroutine arrow4 (X, Y, Z, DX, DY, DZ)
subroutine draw3 (X3, Y3, Z3)
subroutine move3 (X3, Y3, Z3)
function xiso (X3, Y3, Z3)
function yiso (X3, Y3, Z3)
function ziso (X3, Y3, Z3)
subroutine uniso (X3D, Y3D, Z3D, XI, YI, ZI)
subroutine uniso2 (X3D, Y3D, Z3D, XI, YI, ZI)
subroutine uniso3 (X3D, Y3D, Z3D, XI, YI, ZI)
function dotprod (X, Y)
subroutine g3writ (X, Y, Z, SIZE, STRING)
subroutine drelev (IDRAW, IFADE, FLAG)
subroutine sortz
subroutine setvue
subroutine menu (XMOUSE, YMOUSE, BUTTON, MTITLE)
subroutine drmenu (mtitle)
subroutine drcovr (ICOVER)
subroutine drbar (TX, NTX)
subroutine rdmenu (XMOUSE, YMOUSE)
subroutine keypad (TEMP)
subroutine hard
subroutine nohard
subroutine getpts (npoint, cspace, iels, isid, xcrved, ycrved)
subroutine drawed (IEL, IEDGE, IFLIP)
subroutine setenv
subroutine initqms
subroutine initps
subroutine vdraw (XXIS, YYIS, N)
subroutine trngl1 (XY1, XY2, XY3)
subroutine trngl2 (XY1, XY2, XY3, IC)
function icolor1 (VAL)
function bcolor (VAL1, VAL2)
subroutine savebox (XY1, XY2, XY3, XY4, IC)
subroutine flshbox
subroutine box1 (XY1, XY2, XY3, XY4, IC)
logical function ifmenu (XMOUSE, YMOUSE)
subroutine vdraw3 (XYZ, N)
subroutine vdraw3a (X, Y, Z, N)
subroutine arrow3 (X, Y, Z, DXBAR, DYBAR, DZBAR, PLANE, SARROW)
subroutine draw_circ (x3, y3, z3, r)
subroutine adjvue (ifadjust)
subroutine xdiamd (XX, YY)
subroutine sdiamd (XX, YY)
subroutine rdiamd (XX, YY)
subroutine diam2 (xmouse, ymouse, iclr)
subroutine xdiam2 (xmouse, ymouse, iclr)
Function/Subroutine Documentation
subroutine adjvue (logical ifadjust)
Definition at line 1811 of file plot.f.
References blank(), prs(), res(), and rescal().
subroutine arrow (X, Y, DXBAR, DYBAR, SARROW)
Definition at line 365 of file plot.f.
References drawc(), movec(), and scale().
subroutine arrow3 (X, Y, Z, DXBAR, DYBAR, DZBAR, character PLANE, SARROW)
Definition at line 1727 of file plot.f.
References color, draw3(), move3(), penw(), and scale().
subroutine arrow4 (X, Y, Z, DX, DY, DZ)
Definition at line 378 of file plot.f.
References color, draw3(), move3(), penw(), and scale().
function bcolor (VAL1, VAL2)
Definition at line 1535 of file plot.f.
References bcolor(), and i.
subroutine box1 (dimension(3) XY1, dimension(3) XY2, dimension(3) XY3, dimension(3) XY4, IC)
Definition at line 1646 of file plot.f.
References beginp(), color, drawc(), endp(), fillp(), xiso(), and yiso().
subroutine dashsc (X1, Y1, X2, Y2, N)
Definition at line 342 of file plot.f.
References drawsc(), i, movesc(), and n.
subroutine data ()
Definition at line 20 of file plot.f.
References blank(), i, if(), n, prs(), setgraph(), xphy(), and yphy().
subroutine ddummy (IEDGE, IEL)
Definition at line 337 of file plot.f.
subroutine diam2 (xmouse, ymouse, iclr)
Definition at line 1903 of file plot.f.
References color, drawsc(), movesc(), xscr(), and yscr().
function dotprod (dimension(3) X, dimension(3) Y)
Definition at line 504 of file plot.f.
References dotprod(), and i.
subroutine draw3 (X3, Y3, Z3)
Definition at line 404 of file plot.f.
References drawc(), xiso(), and yiso().
subroutine draw_circ (x3, y3, z3, r)
Definition at line 1766 of file plot.f.
References drawc(), i, movec(), n, xiso(), and yiso().
subroutine drawed (IEL, IEDGE, IFLIP)
Definition at line 1208 of file plot.f.
References drawc(), getpts(), i, iflip(), movec(), xiso(), and yiso().
subroutine drbar (real, dimension(16) TX, NTX)
Definition at line 946 of file plot.f.
References beginb(), clsseg(), delseg(), endp(), fillp(), gwrite(), move(), opnseg(), xphy(), and yphy().
subroutine drcovr (ICOVER)
Definition at line 897 of file plot.f.
References beginp(), clsseg(), color, endp(), fillp(), movesc(), opnseg(), xphy(), and yphy().
subroutine drelev (IDRAW, IFADE, character*5 FLAG)
Definition at line 519 of file plot.f.
References color, drawsc(), i, and movesc().
subroutine drmenu (character*(*) mtitle)
Definition at line 792 of file plot.f.
References beginb(), beginp(), clsseg(), color, delseg(), drawsc(), endp(), fillp(), gswrit(), movesc(), opnseg(), sgvis(), xphy(), and yphy().
subroutine drwbox (X1, Y1, X2, Y2, IC)
Definition at line 316 of file plot.f.
References color, drawc(), and movec().
subroutine flshbox ()
Definition at line 1616 of file plot.f.
References beginp(), color, drawc(), endp(), fillp(), i, xiso(), and yiso().
subroutine g3writ (X, Y, Z, SIZE, character, dimension(100) STRING)
Definition at line 513 of file plot.f.
References gwrite(), xiso(), and yiso().
subroutine getpts (npoint, real, dimension(npoint) cspace, iels, isid, real, dimension(npoint) xcrved, real, dimension(npoint) ycrved)
Definition at line 1024 of file plot.f.
References dist2(), gen_int_gz(), i, j, latchob(), mxm(), prs(), and rer().
subroutine gingrd (X1)
Definition at line 304 of file plot.f.
References prs().
subroutine hard ()
Definition at line 1012 of file plot.f.
function icolor1 (VAL)
Definition at line 1511 of file plot.f.
References icolor1().
logical function ifmenu (XMOUSE, YMOUSE)
Definition at line 1684 of file plot.f.
References i, ifmenu(), j, xscr(), yphy(), and yscr().
subroutine initps ()
Definition at line 1334 of file plot.f.
subroutine initqms ()
Definition at line 1327 of file plot.f.
subroutine keypad (TEMP)
Definition at line 1004 of file plot.f.
References rer().
subroutine menu (XMOUSE, YMOUSE, BUTTON, character, dimension(*) MTITLE)
Definition at line 656 of file plot.f.
References drcovr(), drmenu(), i, mouse(), pris4(), prs(), rei(), sgvis(), xscr(), and yscr().
subroutine move3 (X3, Y3, Z3)
Definition at line 412 of file plot.f.
References movec(), xiso(), and yiso().
subroutine nohard ()
Definition at line 1018 of file plot.f.
subroutine rdiamd (XX, YY)
Definition at line 1890 of file plot.f.
References drawsc(), and movesc().
subroutine rdmenu (XMOUSE, YMOUSE)
Definition at line 985 of file plot.f.
References prs(), xphy(), and yphy().
subroutine savebox (dimension(3) XY1, dimension(3) XY2, dimension(3) XY3, dimension(3) XY4, IC)
Definition at line 1570 of file plot.f.
References copy(), and flshbox().
subroutine sdiamd (XX, YY)
Definition at line 1879 of file plot.f.
References drawsc(), and movesc().
subroutine setenv ()
Definition at line 1274 of file plot.f.
References i, ia, openf(), parse(), and prs().
subroutine setvue ()
Definition at line 606 of file plot.f.
References prs(), prsrs(), reader(), res(), and rescal().
subroutine sortz ()
Definition at line 561 of file plot.f.
References iswap(), sort(), and ziso().
subroutine trngl1 (dimension(4) XY1, dimension(4) XY2, dimension(4) XY3)
Definition at line 1405 of file plot.f.
References bcolor(), copy(), icolor1(), and trngl2().
subroutine trngl2 (dimension(3) XY1, dimension(3) XY2, dimension(3) XY3, IC)
Definition at line 1476 of file plot.f.
References beginp(), color, drawc(), endp(), fillp(), xiso(), and yiso().
subroutine uniso (X3D, Y3D, Z3D, XI, YI, ZI)
Definition at line 468 of file plot.f.
subroutine uniso2 (X3D, Y3D, Z3D, XI, YI, ZI)
Definition at line 480 of file plot.f.
subroutine uniso3 (X3D, Y3D, Z3D, XI, YI, ZI)
Definition at line 492 of file plot.f.
subroutine vdraw (dimension(n) XXIS, dimension(n) YYIS, N)
Definition at line 1394 of file plot.f.
References drawc(), i, movec(), and n.
subroutine vdraw3 (dimension(4,n) XYZ, N)
Definition at line 1704 of file plot.f.
References color, draw3(), i, icolor1(), move3(), and n.
subroutine vdraw3a (dimension(n) X, dimension(n) Y, dimension(n) Z, N)
Definition at line 1717 of file plot.f.
References draw3(), i, move3(), and n.
subroutine xdiam2 (xmouse, ymouse, iclr)
Definition at line 1915 of file plot.f.
References color, drawsc(), movesc(), xscr(), and yscr().
subroutine xdiamd (XX, YY)
Definition at line 1868 of file plot.f.
References drawc(), and movec().
subroutine xdot (XX, YY)
Definition at line 327 of file plot.f.
References drawc(), and movec().
function xiso (X3, Y3, Z3)
Definition at line 419 of file plot.f.
References dotprod(), and xiso().
function xphy (XSCREN)
Definition at line 293 of file plot.f.
References xphy().
function xscr (XPHYS)
Definition at line 281 of file plot.f.
References xscr().
function yiso (X3, Y3, Z3)
Definition at line 436 of file plot.f.
References dotprod(), and yiso().
function yphy (YSCREN)
Definition at line 299 of file plot.f.
References yphy().
function yscr (YPHYS)
Definition at line 287 of file plot.f.
References yscr().
function ziso (X3, Y3, Z3)
Definition at line 452 of file plot.f.
References dotprod(), and ziso().