KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/prepost.f File Reference
prepost.f File Reference
Functions/Subroutines
subroutine prepost (ifdoin, prefin)
subroutine prepost_map (isave)
subroutine outfld (prefix)
subroutine outhis (ifhis)
subroutine intglq
subroutine bdforce
subroutine bdheat
subroutine setsmu (smult)
function sumfc (FF, SM, IFC)
subroutine file2 (nopen, PREFIX)
subroutine rzero4 (a, n)
subroutine copyx4 (a, b, n)
subroutine copy4r (a, b, n)
function i_find_prefix (prefix, imax)
subroutine dump_header (excodein, p66, ierr)
subroutine fill_tmp (tdump, id, ie)
subroutine get_id (id)
subroutine close_fld (p66, ierr)
subroutine out_tmp (id, p66, ierr)
subroutine mfo_outfld (prefix)
subroutine io_init
subroutine mfo_open_files (prefix, ierr)
subroutine restart_nfld (nfld, prefix)
subroutine full_restart_save (iosave)
subroutine restart_save (iosave, save_size, nfldi)
subroutine outpost (v1, v2, v3, vp, vt, name3)
subroutine outpost2 (v1, v2, v3, vp, vt, nfldt, name3)
subroutine mfo_mdatav (u, v, w, nel)
subroutine mfo_mdatas (u, nel)
subroutine mfo_outs (u, nel, mx, my, mz)
subroutine mfo_outv (u, v, w, nel, mx, my, mz)
subroutine mfo_write_hdr
Function/Subroutine Documentation
subroutine bdforce ()
Definition at line 801 of file prepost.f.
References add2(), axhmsf(), bcneutr(), cmult(), ly1, lz1, opchsgn(), opdssum(), opgradt(), rzero(), sethlm(), sub2(), and twallsh().
subroutine bdheat ()
Definition at line 865 of file prepost.f.
References axhelm(), bcneusc(), cmult(), dssum(), lelt, ly1, lz1, sethlm(), and sub2().
subroutine close_fld (p66, ierr)
Definition at line 1323 of file prepost.f.
References byte_close.
subroutine copy4r (real, dimension(1) a, real*4, dimension(1) b, n)
Definition at line 1109 of file prepost.f.
References n.
subroutine copyx4 (real*4, dimension(1) a, real, dimension(1) b, n)
Definition at line 1101 of file prepost.f.
References n.
subroutine dump_header (character*30 excodein, p66, ierr)
Definition at line 1155 of file prepost.f.
References blank(), and byte_write.
subroutine file2 (nopen, character*1, dimension(3) PREFIX)
Definition at line 986 of file prepost.f.
References blank(), chcopy(), ione(), and ltrunc().
subroutine fill_tmp (real*4, dimension(lxyz,lpsc9) tdump, id, ie)
Definition at line 1232 of file prepost.f.
References copyx4(), ly1, lz1, and rzero4().
subroutine full_restart_save (integer iosave)
Definition at line 1824 of file prepost.f.
References restart_save().
subroutine get_id (id)
Definition at line 1304 of file prepost.f.
function i_find_prefix (character*3 prefix, imax)
Definition at line 1118 of file prepost.f.
References exitt().
subroutine intglq ()
Definition at line 662 of file prepost.f.
References bdforce(), bdheat(), copy(), dssum(), glsum(), lelt, ly1, lz1, rzero(), setsmu(), and sumfc().
subroutine io_init ()
Definition at line 1562 of file prepost.f.
References exitt(), glmin(), igl_running_sum(), and nek_comm_io().
subroutine mfo_mdatas (real, dimension(lx1*ly1*lz1,1) u, nel)
Definition at line 2103 of file prepost.f.
References byte_write, byte_write_mpi(), crecv(), csend(), err_chk(), j, lelt, n, nekgsync(), vlmax(), and vlmin().
subroutine mfo_mdatav (real, dimension(lx1*ly1*lz1,1) u, real, dimension(lx1*ly1*lz1,1) v, real, dimension(lx1*ly1*lz1,1) w, nel)
Definition at line 2014 of file prepost.f.
References byte_write, byte_write_mpi(), crecv(), csend(), err_chk(), j, lelt, n, nekgsync(), vlmax(), and vlmin().
subroutine mfo_open_files (character*1, dimension(3) prefix, ierr)
Definition at line 1624 of file prepost.f.
References blank(), chcopy(), i_find_prefix(), ltrunc(), mbyte_open(), mod1(), ndigit, and restart_nfld().
subroutine mfo_outfld (character*3 prefix)
Definition at line 1379 of file prepost.f.
References bcast(), byte_close, byte_close_mpi(), byte_set_view(), dnekclock_sync(), err_chk(), glsum(), lelt, ly1, lz1, map2reg(), mfo_mdatas(), mfo_mdatav(), mfo_open_files(), mfo_outs(), mfo_outv(), and mfo_write_hdr().
subroutine mfo_outs (real, dimension(mx,my,mz,1) u, nel, mx, my, mz)
Definition at line 2177 of file prepost.f.
References byte_write, byte_write_mpi(), copy(), copyx4(), crecv(), csend(), err_chk(), exitt(), lelt, and nekgsync().
subroutine mfo_outv (real, dimension(mx*my*mz,1) u, real, dimension(mx*my*mz,1) v, real, dimension(mx*my*mz,1) w, nel, mx, my, mz)
Definition at line 2265 of file prepost.f.
References byte_write, byte_write_mpi(), copy(), copyx4(), crecv(), csend(), err_chk(), exitt(), j, lelt, and nekgsync().
subroutine mfo_write_hdr ()
Definition at line 2385 of file prepost.f.
References blank(), byte_set_view(), byte_write, byte_write_mpi(), crecv(), csend(), err_chk(), get_bytesw_write, icopy(), j, lelt, nekgsync(), and set_bytesw_write.
subroutine out_tmp (id, p66, ierr)
Definition at line 1339 of file prepost.f.
References blank(), byte_write, ly1, and lz1.
subroutine outfld (character*3 prefix)
Definition at line 269 of file prepost.f.
References bcast(), blank(), byte_open, chcopy(), close_fld(), crecv2(), csend(), dump_header(), err_chk(), file2(), fill_tmp(), get_id(), i_find_prefix(), izero(), ltrunc(), ly1, lz1, mfo_outfld(), mod1(), nekgsync(), and out_tmp().
subroutine outhis (logical ifhis)
Definition at line 473 of file prepost.f.
References crecv(), csend(), glmax(), intglq(), j, ly1, lz1, and rmin().
subroutine outpost (real, dimension(1) v1, real, dimension(1) v2, real, dimension(1) v3, real, dimension(1) vp, real, dimension(1) vt, character*3 name3)
Definition at line 1927 of file prepost.f.
References outpost2().
subroutine outpost2 (real, dimension(1) v1, real, dimension(1) v2, real, dimension(1) v3, real, dimension(1) vp, real, dimension(ltot1,1) vt, nfldt, character*3 name3)
Definition at line 1943 of file prepost.f.
References copy(), exitt(), lelt, ly1, lz1, and prepost().
subroutine prepost (logical ifdoin, character*3 prefin)
Definition at line 3 of file prepost.f.
References dnekclock(), err_chk(), gop(), ly1, lz1, outfld(), outhis(), and prepost_map().
subroutine prepost_map (isave)
Definition at line 153 of file prepost.f.
References copy(), lelt, ly1, lz1, mxm(), and rzero().
subroutine restart_nfld (nfld, character*3 prefix)
Definition at line 1719 of file prepost.f.
References indx1(), and mod1().
subroutine restart_save (integer iosave, integer save_size, integer nfldi)
Definition at line 1843 of file prepost.f.
References outpost2().
subroutine rzero4 (real*4, dimension(1) a, n)
Definition at line 1094 of file prepost.f.
References n.
subroutine setsmu (dimension (lx1,ly1,lz1,1) smult)
Definition at line 941 of file prepost.f.
References facind(), ly1, lz1, and rzero().
function sumfc (real, dimension(lx1,ly1,lz1) FF, real, dimension(lx1,ly1,lz1) SM, IFC)
Definition at line 973 of file prepost.f.
References facind().