KTH framework for Nek5000 toolboxes; testing version: Toolbox/postprocessing/pstat2d/pstat.f File Reference
pstat.f File Reference
Post processing for statistics module.
Functions/Subroutines
subroutine pstat_register ()
Register post processing statistics module.
subroutine pstat_init ()
Initilise pstat module.
logical function pstat_is_initialised ()
Check if module was initialised.
subroutine pstat_main
Main interface of pstat module.
subroutine pstat_mesh_manipulate
Manipulate mesh to find proper element ordering (in case of AMR refine)
subroutine pstat_transfer ()
Reshuffle elements between sts and current ordering.
subroutine pstat_sts_avg
Read in fields and average them.
subroutine pstat_deriv
Calculate derivatives.
subroutine pstat_interp
Interpolate int the set of points.
Detailed Description
Post processing for statistics module.
Post processing I/O routines for statistics module.
Author
Adam Peplinski
Date
Mar 13, 2019
Definition in file pstat.f.
Function/Subroutine Documentation
pstat_deriv()
subroutine pstat_deriv
Calculate derivatives.
Definition at line 826 of file pstat.f.
References copy(), geom_reset(), gradm1(), outpost2(), and rzero().
pstat_init()
subroutine pstat_init
Initilise pstat module.
Note
This routine should be called in frame_usr_init
Definition at line 100 of file pstat.f.
References mntr_tmr_add(), mntr_warn(), and rprm_rp_get().
pstat_interp()
subroutine pstat_interp
Interpolate int the set of points.
Definition at line 1105 of file pstat.f.
References io_file_freeid(), mntr_abort(), pstat_mfi_interp(), and pstat_mfo_interp().
pstat_is_initialised()
logical function pstat_is_initialised
Check if module was initialised.
Returns
pstat_is_initialised
Definition at line 167 of file pstat.f.
pstat_main()
subroutine pstat_main
Main interface of pstat module.
Definition at line 180 of file pstat.f.
References mntr_log(), mntr_tmr_add(), pstat_deriv(), pstat_interp(), pstat_mesh_manipulate(), pstat_mfi_crd2d(), and pstat_sts_avg().
pstat_mesh_manipulate()
subroutine pstat_mesh_manipulate
Manipulate mesh to find proper element ordering (in case of AMR refine)
Definition at line 233 of file pstat.f.
References gllel(), gllnid(), io_file_freeid(), ituple_sort(), mntr_abort(), mntr_check_abort(), and mntr_logi().
pstat_register()
subroutine pstat_register
Register post processing statistics module.
Note
This routine should be called in frame_usr_register
Definition at line 11 of file pstat.f.
References mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), mntr_tmr_add(), mntr_tmr_is_name_reg(), mntr_tmr_reg(), mntr_warn(), rprm_rp_reg(), rprm_sec_reg(), and rprm_sec_set_act().
pstat_sts_avg()
subroutine pstat_sts_avg
Read in fields and average them.
Definition at line 693 of file pstat.f.
References add2s2(), addfid(), cmult(), copy(), io_init(), io_mfo_fname(), mfi(), mntr_abort(), outpost2(), pstat_transfer(), and rzero().
pstat_transfer()
subroutine pstat_transfer
Reshuffle elements between sts and current ordering.
Definition at line 590 of file pstat.f.
References gllel(), gllnid(), and mntr_abort().