KTH framework for Nek5000 toolboxes; testing version: Toolbox/postprocessing/pstat3d/pstat_IO.f File Reference
pstat_IO.f File Reference
Functions/Subroutines
subroutine pstat_mfo
Write field data data to the file.
subroutine pstat_mfi_interp
Read interpolation points position and redistribute them.
subroutine pstat_mfo_interp
Geather data and write it down.
subroutine pstat_field_out (int_field, fldim, ierr)
Geather single field data and write it down.
Function/Subroutine Documentation
pstat_field_out()
subroutine pstat_field_out (real, dimension(fldim*lhis) int_field, integer fldim, integer ierr)
Geather single field data and write it down.
Parameters
[in] int_field interpolated field
[in] fldim field dimension
[out] ierr error flag
Definition at line 583 of file pstat_IO.f.
References byte_write, copy(), copyx4(), crecv2(), and csend().
pstat_mfi_interp()
subroutine pstat_mfi_interp
Read interpolation points position and redistribute them.
Definition at line 83 of file pstat_IO.f.
References bcast(), blank(), byte_close, byte_open, byte_read, byte_reverse, byte_reverse8, copy(), copy4r(), crecv2(), csend(), io_file_freeid(), mntr_check_abort(), and mntr_logi().
pstat_mfo()
subroutine pstat_mfo
Write field data data to the file.
Definition at line 10 of file pstat_IO.f.
References outpost().
pstat_mfo_interp()
subroutine pstat_mfo_interp
Geather data and write it down.
Definition at line 276 of file pstat_IO.f.
References byte_close, byte_open, byte_write, mntr_check_abort(), and pstat_field_out().