KTH framework for Nek5000 toolboxes; testing version: Toolbox/postprocessing/pstat3d/pstat.f File Reference
pstat.f File Reference
Post processing for statistics module.
Functions/Subroutines
subroutine pstat_register ()
Register post processing statistics module.
subroutine pstat_init ()
Initilise pstat module.
logical function pstat_is_initialised ()
Check if module was initialised.
subroutine pstat_main
Main interface of pstat module.
subroutine pstat_sts_avg
Read in fields and average them.
subroutine pstat_nfield
Calculate new fileds.
subroutine pstat_interp
Interpolate int the set of points.
Detailed Description
Post processing for statistics module.
Post processing I/O routines for statistics module.
Author
Adam Peplinski
Date
Mar 13, 2019
Definition in file pstat.f.
Function/Subroutine Documentation
pstat_init()
subroutine pstat_init
Initilise pstat module.
Note
This routine should be called in frame_usr_init
Definition at line 96 of file pstat.f.
References icopy(), mntr_tmr_add(), mntr_warn(), and rprm_rp_get().
pstat_interp()
subroutine pstat_interp
Interpolate int the set of points.
Definition at line 769 of file pstat.f.
References io_file_freeid(), mntr_abort(), pstat_mfi_interp(), and pstat_mfo_interp().
pstat_is_initialised()
logical function pstat_is_initialised
Check if module was initialised.
Returns
pstat_is_initialised
Definition at line 161 of file pstat.f.
References pstat_is_initialised().
pstat_main()
subroutine pstat_main
Main interface of pstat module.
Definition at line 174 of file pstat.f.
References mntr_log(), mntr_tmr_add(), pstat_interp(), pstat_nfield(), and pstat_sts_avg().
pstat_nfield()
subroutine pstat_nfield
Calculate new fileds.
Definition at line 336 of file pstat.f.
References add2(), add3(), add4(), admcol3(), chsign(), cmult(), col3(), copy(), gradm1(), pstat_mfo(), rzero(), sub2(), sub3(), subcol3(), subcol4(), and vdot3().
pstat_register()
subroutine pstat_register
Register post processing statistics module.
Note
This routine should be called in frame_usr_register
Definition at line 11 of file pstat.f.
References mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), mntr_tmr_add(), mntr_tmr_is_name_reg(), mntr_tmr_reg(), mntr_warn(), rprm_rp_reg(), rprm_sec_reg(), and rprm_sec_set_act().
pstat_sts_avg()
subroutine pstat_sts_avg
Read in fields and average them.
Definition at line 216 of file pstat.f.
References add2s2(), addfid(), cmult(), io_init(), io_mfo_fname(), mfi(), and rzero().