KTH framework for Nek5000 toolboxes; testing version: Toolbox/postprocessing/pstat2d/pstat_IO.f File Reference
pstat_IO.f File Reference
Functions/Subroutines
subroutine pstat_mfi_crd2d
Read nonconforming data from the file.
subroutine pstat_mfi_interp
Read interpolation points position and redistribute them.
subroutine pstat_mfo_interp
Geather data and write it down.
Function/Subroutine Documentation
pstat_mfi_crd2d()
subroutine pstat_mfi_crd2d
Read nonconforming data from the file.
Definition at line 10 of file pstat_IO.f.
References addfid(), bcast(), blank(), byte_close, byte_close_mpi(), byte_open, byte_open_mpi(), byte_read, byte_read_mpi(), byte_reverse, byte_set_view(), copy(), copy4r(), io_file_freeid(), io_init(), io_mfo_fname(), mntr_abort(), and mntr_check_abort().
pstat_mfi_interp()
subroutine pstat_mfi_interp
Read interpolation points position and redistribute them.
Definition at line 195 of file pstat_IO.f.
References bcast(), blank(), byte_close, byte_open, byte_read, byte_reverse, byte_reverse8, copy(), copy4r(), crecv2(), csend(), io_file_freeid(), mntr_check_abort(), and mntr_logi().
pstat_mfo_interp()
subroutine pstat_mfo_interp
Geather data and write it down.
Definition at line 388 of file pstat_IO.f.
References byte_close, byte_open, byte_write, copy(), copyx4(), crecv2(), csend(), and mntr_check_abort().