KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/ptools.c File Reference
ptools.c File Reference
#include <stdio.h>
#include <math.h>
#include <float.h>
#include <limits.h>
#include "const.h"
#include "types.h"
#include "ptools.h"
#include "ivec.h"
#include "error.h"
#include "comm.h"
Macros
#define SORT_STACK 50
Functions
void p_rank_mtuple_ (int *r, void *tl_in, int *n, int *m, int *k, int *if_sort, char *type)
void p_rank_mtuple (int *r, void *tl_in, int n, int m, int k, int sort, int type)
Macro Definition Documentation
#define SORT_STACK 50
Definition at line 50 of file ptools.c.
Function Documentation
void p_rank_mtuple (int * r, void * tl_in, int n, int m, int k, int sort, int type)
Definition at line 125 of file ptools.c.
References bss_free(), bss_malloc(), error_msg_fatal(), error_msg_warning(), exit(), FALSE, giop(), i, ivec_c_index(), ivec_copy(), ivec_lb_ub(), ivec_sort(), j, lb, MIN, my_id, n, printf(), rank(), sort(), SORT_STACK, SWAP, tmp, TRUE, and vals.
void p_rank_mtuple_ (int * r, void * tl_in, int * n, int * m, int * k, int * if_sort, char * type)
Definition at line 93 of file ptools.c.
References error_msg_fatal(), p_rank_mtuple(), and printf().