KTH framework for Nek5000 toolboxes; testing version: Toolbox/tools/tsrs/pts_redistribute.f File Reference
pts_redistribute.f File Reference
Functions/Subroutines
subroutine pts_rdst (nptimb)
subroutine pts_transfer (rbuf, lrbuf, ibuf, libuf, lpts, npts)
subroutine pts_map_all (mid, lpts, npts, npoints, nptimb)
subroutine pts_map_set (mid, lpts, istatus, indasg, npts_plist, lplist, npts, nplist)
subroutine ivgl_running_sum (out, in, n)
subroutine ibcastn (buf, len, sid)
Function/Subroutine Documentation
ibcastn()
subroutine ibcastn (integer, dimension(len) buf, integer len, integer sid)
Definition at line 856 of file pts_redistribute.f.
References mpi_bcast().
ivgl_running_sum()
subroutine ivgl_running_sum (integer, dimension(n) out, integer, dimension(n) in, integer n)
Definition at line 843 of file pts_redistribute.f.
References mpi_scan().
pts_map_all()
subroutine pts_map_all (integer, dimension(lpts) mid, integer lpts, integer npts, integer npoints, integer nptimb)
Definition at line 188 of file pts_redistribute.f.
References exitt(), nekgsync(), and pts_map_set().
pts_map_set()
subroutine pts_map_set (integer, dimension(lpts) mid, integer lpts, integer istatus, integer indasg, integer, dimension(lplist) npts_plist, integer lplist, integer npts, integer nplist)
Definition at line 402 of file pts_redistribute.f.
References exitt(), ibcastn(), icopy(), ivgl_running_sum(), and izero().
pts_rdst()
subroutine pts_rdst (integer nptimb)
Definition at line 17 of file pts_redistribute.f.
References exitt(), pts_map_all(), and pts_transfer().
pts_transfer()
subroutine pts_transfer (real, dimension(lrbuf,lpts) rbuf, integer lrbuf, integer, dimension(libuf,lpts) ibuf, integer libuf, integer lpts, integer npts)
Definition at line 130 of file pts_redistribute.f.