KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/queue.c File Reference
queue.c File Reference
#include <stdio.h>
#include "queue.h"
#include "error.h"
#include "bss_malloc.h"
Data Structures
struct node
struct queue_CDT
Functions
queue_ADT new_queue (void)
void free_queue (queue_ADT q)
void enqueue (queue_ADT q, void *obj)
void * dequeue (queue_ADT q)
int len_queue (queue_ADT q)
Function Documentation
void* dequeue (queue_ADT q)
Definition at line 148 of file queue.c.
References bss_free(), error_msg_fatal(), and node::obj.
void enqueue (queue_ADT q, void * obj)
Definition at line 125 of file queue.c.
References bss_malloc(), and node::obj.
void free_queue (queue_ADT q)
Definition at line 79 of file queue.c.
References bss_free(), error_msg_fatal(), error_msg_warning(), and node::next.
int len_queue (queue_ADT q)
Definition at line 183 of file queue.c.
queue_ADT new_queue (void)
Definition at line 56 of file queue.c.
References bss_malloc().