KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/reatore2/re2torea.f File Reference
re2torea.f File Reference
Functions/Subroutines
program re2torea
subroutine exitt
Function/Subroutine Documentation
subroutine exitt ()
Definition at line 227 of file re2torea.f.
program re2torea ()
Definition at line 2 of file re2torea.f.
References blank(), byte_close, byte_open, byte_read, chcopy(), j, ltrunc(), and scanout().