KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/reader_rea.f File Reference
reader_rea.f File Reference
Functions/Subroutines
subroutine rdparam
subroutine rdmesh
subroutine rdcurve
subroutine rdbdry
subroutine rdicdf
subroutine rdmatp
subroutine rdhist
subroutine rdout
subroutine rdobj
Function/Subroutine Documentation
rdbdry()
subroutine rdbdry ()
Definition at line 695 of file reader_rea.f.
References blank(), capit(), exitt(), indx1(), lelt, and rzero().
rdcurve()
subroutine rdcurve ()
Definition at line 602 of file reader_rea.f.
References blank(), exitt(), lelt, and rzero().
rdhist()
subroutine rdhist ()
Definition at line 990 of file reader_rea.f.
References bcast(), blank(), err_chk(), exitt(), izero(), ly1, and lz1.
rdicdf()
subroutine rdicdf ()
Definition at line 874 of file reader_rea.f.
References bcast(), blank(), capit(), exitti(), iglmax(), and indx1().
rdmatp()
subroutine rdmatp ()
Definition at line 941 of file reader_rea.f.
References bcast(), exitt(), izero(), and rzero().
rdmesh()
subroutine rdmesh ()
Definition at line 512 of file reader_rea.f.
References exitt(), and rzero().
rdobj()
subroutine rdobj ()
Definition at line 1148 of file reader_rea.f.
References bcast(), and err_chk().
rdout()
subroutine rdout ()
Definition at line 1064 of file reader_rea.f.
References bcast(), exitt(), exitti(), iglmax(), and lfalse().
rdparam()
subroutine rdparam ()
Definition at line 3 of file reader_rea.f.
References bcast(), capit(), exitt(), exitti(), indx1(), ly1, and lz1.