KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/reader_par.f File Reference
reader_par.f File Reference
Functions/Subroutines
subroutine readat_par
subroutine setdefaultparam
subroutine par_read (ierr)
subroutine bcastparam
subroutine chkparam
subroutine par_verify (ierr)
Function/Subroutine Documentation
bcastparam()
subroutine bcastparam ()
Definition at line 783 of file reader_par.f.
References bcast().
chkparam()
subroutine chkparam ()
Definition at line 917 of file reader_par.f.
References exitt(), exitti(), iglmax(), lelt, ly1, and lz1.
par_read()
subroutine par_read (ierr)
Definition at line 194 of file reader_par.f.
References blank(), capit(), finiparser_dump, finiparser_find, finiparser_load, and par_verify().
par_verify()
subroutine par_verify (ierr)
Definition at line 1122 of file reader_par.f.
References capit(), and chcopy().
readat_par()
subroutine readat_par ()
Definition at line 3 of file reader_par.f.
References bcast(), bcastparam(), chkparam(), exitt(), mapelpr(), nekgsync(), par_read(), read_re2_data(), read_re2_hdr(), and setdefaultparam().
setdefaultparam()
subroutine setdefaultparam ()
Definition at line 36 of file reader_par.f.
References blank(), izero(), and rzero().