KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/readat_new.f File Reference
readat_new.f File Reference
Functions/Subroutines
subroutine readat_new
subroutine setdefaultparam
subroutine par_read (ierr)
subroutine bcastparam
subroutine chkparam
subroutine par_verify (ierr)
Function/Subroutine Documentation
subroutine bcastparam ()
Definition at line 527 of file readat_new.f.
References bcast().
subroutine chkparam ()
Definition at line 653 of file readat_new.f.
References exitt(), exitti(), iglmax(), lelt, ly1, and lz1.
subroutine par_read (ierr)
Definition at line 155 of file readat_new.f.
References blank(), capit(), finiparser_dump, finiparser_find, finiparser_load, j, and par_verify().
subroutine par_verify (ierr)
Definition at line 853 of file readat_new.f.
References capit(), chcopy(), j, and n.
subroutine readat_new ()
Definition at line 3 of file readat_new.f.
References bcast(), bcastparam(), bin_rd1(), chkparam(), exitt(), mapelpr(), nekgsync(), open_bin_file(), par_read(), and setdefaultparam().
subroutine setdefaultparam ()
Definition at line 35 of file readat_new.f.
References blank(), izero(), and rzero().