KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/nekmerge/reader.f File Reference
reader.f File Reference
Functions/Subroutines
subroutine rw_param (nelt, nelv, ndim, nelt_all, nelv_all, nfld, ifile)
subroutine rd_xyz (x, y, z, nel, ndim)
subroutine rd_curve (ncurve, ccurve, curve, nel, ndim)
subroutine rd_bdry (cbc, bc, ibc, string, nel, nelo, ndim, nfld, lelt)
Function/Subroutine Documentation
subroutine rd_bdry (character*3, dimension (6,lelt,nfld) cbc, real, dimension(5,6,lelt,nfld) bc, integer, dimension (6,lelt,nfld) ibc, character*80 string, nel, nelo, ndim, nfld, lelt)
Definition at line 118 of file reader.f.
References blank(), cleanr(), indx1(), and j.
subroutine rd_curve (ncurve, character*1, dimension (12,1) ccurve, real, dimension(6,12,1) curve, nel, ndim)
Definition at line 81 of file reader.f.
References blank(), cleanr(), copy(), and rzero().
subroutine rd_xyz (real, dimension(8,nel) x, real, dimension(8,nel) y, real, dimension(8,nel) z, nel, ndim)
Definition at line 53 of file reader.f.
subroutine rw_param (nelt, nelv, ndim, nelt_all, nelv_all, nfld, ifile)
Definition at line 3 of file reader.f.
References blank(), i, indx1(), lineout(), and scanout().