KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/reatore2/reatore2.f File Reference
reatore2.f File Reference
Functions/Subroutines
program trans
subroutine exitt
Function/Subroutine Documentation
subroutine exitt ()
Definition at line 226 of file reatore2.f.
References close_files(), dnekclock(), exit(), exit_(), flush_io(), happy_check(), mpi_finalize(), nek_flops(), nekgsync(), and print_stack.
program trans ()
Definition at line 2 of file reatore2.f.
References blank(), byte_close, byte_open, byte_write, chcopy(), copy48(), indx1(), lelt, lineout(), ltrunc(), and scanout().