KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/reatore2/strings.f File Reference
strings.f File Reference
Functions/Subroutines
subroutine scanout (string, input, len, infile, outfile)
subroutine scanoutafter (string, input, len, infile, outfile)
subroutine copy48 (a, b, n)
subroutine copy (a, b, n)
subroutine icopy (a, b, n)
subroutine chcopy (a, b, n)
subroutine blank (s, n)
function ltrunc (s, n)
integer function indx1 (S1, S2, L2)
subroutine rzero (x, n)
subroutine izero (x, n)
subroutine lineout (io, s, n)
subroutine fbyte_write (s, n)
Function/Subroutine Documentation
subroutine blank (character*1, dimension(1) s, n)
Definition at line 87 of file strings.f.
References i, and n.
subroutine chcopy (character*1, dimension(1) a, character*1, dimension(1) b, n)
Definition at line 80 of file strings.f.
References i, and n.
subroutine copy (real, dimension(1) a, real, dimension(1) b, n)
Definition at line 66 of file strings.f.
References i, and n.
subroutine copy48 (real*8, dimension(1) a, real*4, dimension(1) b, n)
Definition at line 58 of file strings.f.
References i, and n.
subroutine fbyte_write (character*4, dimension(n) s, n)
Definition at line 152 of file strings.f.
References byte_write, lineout(), and n.
subroutine icopy (integer, dimension(1) a, integer, dimension(1) b, n)
Definition at line 73 of file strings.f.
References i, and n.
integer function indx1 (character*80 S1, character*80 S2, L2)
Definition at line 109 of file strings.f.
References i, and indx1().
subroutine izero (integer, dimension(1) x, n)
Definition at line 136 of file strings.f.
References i, and n.
subroutine lineout (io, character*1, dimension(n) s, n)
Definition at line 144 of file strings.f.
References ltrunc(), and n.
function ltrunc (character*1, dimension(1) s, n)
Definition at line 96 of file strings.f.
References j, ltrunc(), and n.
subroutine rzero (real, dimension(1) x, n)
Definition at line 128 of file strings.f.
References i, and n.
subroutine scanout (character*80 string, character*1, dimension(1) input, len, integer infile, integer outfile)
Definition at line 3 of file strings.f.
References blank(), chcopy(), indx1(), j, and ltrunc().
subroutine scanoutafter (character*80 string, character*1, dimension(1) input, len, integer infile, integer outfile)
Definition at line 31 of file strings.f.
References blank(), chcopy(), indx1(), j, and ltrunc().