KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/scrdmp.f File Reference
scrdmp.f File Reference
Functions/Subroutines
subroutine scrdmp
subroutine scrudmp
Function/Subroutine Documentation
subroutine scrdmp ()
Definition at line 2 of file scrdmp.f.
References blank().
subroutine scrudmp ()
Definition at line 25 of file scrdmp.f.
References prsi(), and rei().