KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/singlmesh.f File Reference
singlmesh.f File Reference
Functions/Subroutines
subroutine get_session_info (intracomm)
subroutine userchk_set_xfer
subroutine setintercomm (nekcommtrue, nptrue)
subroutine unsetintercomm (nekcommtrue, nptrue)
subroutine uglmin (a, n)
subroutine happy_check (iflag)
subroutine bcopy
subroutine chk_outflow
subroutine multimesh_create
Function/Subroutine Documentation
bcopy()
subroutine bcopy ()
Definition at line 85 of file singlmesh.f.
chk_outflow()
subroutine chk_outflow ()
Definition at line 92 of file singlmesh.f.
get_session_info()
subroutine get_session_info (intracomm)
Definition at line 3 of file singlmesh.f.
References bcast(), blank(), err_chk(), iniproc(), mpi_comm_dup(), mpi_init(), and mpi_initialized().
happy_check()
subroutine happy_check (iflag)
Definition at line 78 of file singlmesh.f.
multimesh_create()
subroutine multimesh_create ()
Definition at line 99 of file singlmesh.f.
setintercomm()
subroutine setintercomm (nekcommtrue, nptrue)
Definition at line 56 of file singlmesh.f.
uglmin()
subroutine uglmin (a, n)
Definition at line 71 of file singlmesh.f.
unsetintercomm()
subroutine unsetintercomm (nekcommtrue, nptrue)
Definition at line 64 of file singlmesh.f.
userchk_set_xfer()
subroutine userchk_set_xfer ()
Definition at line 48 of file singlmesh.f.