KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/speclib.f File Reference
speclib.f File Reference
Functions/Subroutines
subroutine zwgl (Z, W, NP)
subroutine zwgll (Z, W, NP)
subroutine zwgj (Z, W, NP, ALPHA, BETA)
subroutine zwgjd (Z, W, NP, ALPHA, BETA)
subroutine zwglj (Z, W, NP, ALPHA, BETA)
subroutine zwgljd (Z, W, NP, ALPHA, BETA)
real *8 function endw1 (N, ALPHA, BETA)
real *8 function endw2 (N, ALPHA, BETA)
real *8 function gammaf (X)
real *8 function pnormj (N, ALPHA, BETA)
subroutine jacg (XJAC, NP, ALPHA, BETA)
subroutine jacobf (POLY, PDER, POLYM1, PDERM1, POLYM2, PDERM2, N, ALP, BET, X)
real function hgj (II, Z, ZGJ, NP, ALPHA, BETA)
real *8 function hgjd (II, Z, ZGJ, NP, ALPHA, BETA)
real function hglj (II, Z, ZGLJ, NP, ALPHA, BETA)
real *8 function hgljd (I, Z, ZGLJ, NP, ALPHA, BETA)
subroutine dgj (D, DT, Z, NZ, lzd, ALPHA, BETA)
subroutine dgjd (D, DT, Z, NZ, lzd, ALPHA, BETA)
subroutine dglj (D, DT, Z, NZ, lzd, ALPHA, BETA)
subroutine dgljd (D, DT, Z, NZ, lzd, ALPHA, BETA)
subroutine dgll (D, DT, Z, NZ, lzd)
real function hgll (I, Z, ZGLL, NZ)
real function hgl (I, Z, ZGL, NZ)
real function pnleg (Z, N)
real function pndleg (Z, N)
subroutine dgllgl (D, DT, ZM1, ZM2, IM12, NZM1, NZM2, ND1, ND2)
subroutine dgljgj (D, DT, ZGL, ZG, IGLG, NPGL, NPG, ND1, ND2, ALPHA, BETA)
subroutine dgljgjd (D, DT, ZGL, ZG, IGLG, NPGL, NPG, ND1, ND2, ALPHA, BETA)
subroutine iglm (I12, IT12, Z1, Z2, lz1, lz2, ND1, ND2)
subroutine igllm (I12, IT12, Z1, Z2, lz1, lz2, ND1, ND2)
subroutine igjm (I12, IT12, Z1, Z2, lz1, lz2, ND1, ND2, ALPHA, BETA)
subroutine igljm (I12, IT12, Z1, Z2, lz1, lz2, ND1, ND2, ALPHA, BETA)
Function/Subroutine Documentation
dgj()
subroutine dgj (real, dimension(lzd,lzd) D, real, dimension(lzd,lzd) DT, real, dimension(1) Z, NZ, lzd, real ALPHA, real BETA)
Definition at line 631 of file speclib.f.
References dgjd(), and exitt().
dgjd()
subroutine dgjd (real*8, dimension(lzd,lzd) D, real*8, dimension(lzd,lzd) DT, real*8, dimension(1) Z, NZ, lzd, real*8 ALPHA, real*8 BETA)
Definition at line 674 of file speclib.f.
References exitt(), and jacobf().
dglj()
subroutine dglj (real, dimension(lzd,lzd) D, real, dimension(lzd,lzd) DT, real, dimension(1) Z, NZ, lzd, real ALPHA, real BETA)
Definition at line 712 of file speclib.f.
References dgljd(), and exitt().
dgljd()
subroutine dgljd (real*8, dimension(lzd,lzd) D, real*8, dimension(lzd,lzd) DT, real*8, dimension(1) Z, NZ, lzd, real*8 ALPHA, real*8 BETA)
Definition at line 755 of file speclib.f.
References exitt(), and jacobf().
dgljgj()
subroutine dgljgj (real, dimension(nd2,nd1) D, real, dimension(nd1,nd2) DT, real, dimension(nd1) ZGL, real, dimension(nd2) ZG, real, dimension(nd2,nd1) IGLG, NPGL, NPG, ND1, ND2, ALPHA, BETA)
Definition at line 970 of file speclib.f.
References dgljgjd(), and exitt().
dgljgjd()
subroutine dgljgjd (real*8, dimension(nd2,nd1) D, real*8, dimension(nd1,nd2) DT, real*8, dimension(nd1) ZGL, real*8, dimension(nd2) ZG, real*8, dimension(nd2,nd1) IGLG, NPGL, NPG, ND1, ND2, real*8 ALPHA, real*8 BETA)
Definition at line 1024 of file speclib.f.
References exitt(), and jacobf().
dgll()
subroutine dgll (real, dimension(lzd,lzd) D, real, dimension(lzd,lzd) DT, real, dimension(1) Z, NZ, lzd)
Definition at line 801 of file speclib.f.
References pnleg().
dgllgl()
subroutine dgllgl (real, dimension(nd2,nd1) D, real, dimension(nd1,nd2) DT, real, dimension(nd1) ZM1, real, dimension(nd2) ZM2, real, dimension(nd2,nd1) IM12, NZM1, NZM2, ND1, ND2)
Definition at line 935 of file speclib.f.
References pnleg().
endw1()
real*8 function endw1 (N, real*8 ALPHA, real*8 BETA)
Definition at line 284 of file speclib.f.
References gammaf().
endw2()
real*8 function endw2 (N, real*8 ALPHA, real*8 BETA)
Definition at line 328 of file speclib.f.
References gammaf().
gammaf()
real*8 function gammaf (real*8 X)
Definition at line 372 of file speclib.f.
hgj()
real function hgj (II, real Z, real, dimension(1) ZGJ, NP, real ALPHA, real BETA)
Definition at line 521 of file speclib.f.
References exitt().
hgjd()
real*8 function hgjd (II, real*8 Z, real*8, dimension(1) ZGJ, NP, real*8 ALPHA, real*8 BETA)
Definition at line 550 of file speclib.f.
References jacobf().
hgl()
real function hgl (I, Z, real, dimension(1) ZGL, NZ)
Definition at line 857 of file speclib.f.
References pndleg(), and pnleg().
hglj()
real function hglj (II, real Z, real, dimension(1) ZGLJ, NP, real ALPHA, real BETA)
Definition at line 574 of file speclib.f.
References exitt().
hgljd()
real*8 function hgljd (I, real*8 Z, real*8, dimension(1) ZGLJ, NP, real*8 ALPHA, real*8 BETA)
Definition at line 603 of file speclib.f.
References jacobf().
hgll()
real function hgll (I, Z, real, dimension(1) ZGLL, NZ)
Definition at line 836 of file speclib.f.
References pndleg(), and pnleg().
igjm()
subroutine igjm (real, dimension(nd2,nd1) I12, real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, lz1, lz2, ND1, ND2, ALPHA, BETA)
Definition at line 1127 of file speclib.f.
References hgj(), and lz1.
igljm()
subroutine igljm (real, dimension(nd2,nd1) I12, real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, lz1, lz2, ND1, ND2, ALPHA, BETA)
Definition at line 1153 of file speclib.f.
References hglj(), and lz1.
igllm()
subroutine igllm (real, dimension(nd2,nd1) I12, real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, lz1, lz2, ND1, ND2)
Definition at line 1102 of file speclib.f.
References hgll(), and lz1.
iglm()
subroutine iglm (real, dimension(nd2,nd1) I12, real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, lz1, lz2, ND1, ND2)
Definition at line 1077 of file speclib.f.
References hgl(), and lz1.
jacg()
subroutine jacg (real*8, dimension(1) XJAC, NP, ALPHA, BETA)
Definition at line 422 of file speclib.f.
References jacobf(), and swap().
jacobf()
subroutine jacobf (POLY, PDER, POLYM1, PDERM1, POLYM2, PDERM2, N, ALP, BET, X)
Definition at line 481 of file speclib.f.
pndleg()
real function pndleg (Z, N)
Definition at line 908 of file speclib.f.
pnleg()
real function pnleg (Z, N)
Definition at line 876 of file speclib.f.
pnormj()
real*8 function pnormj (N, real*8 ALPHA, real*8 BETA)
Definition at line 396 of file speclib.f.
References gammaf().
zwgj()
subroutine zwgj (real, dimension(1) Z, real, dimension(1) W, NP, real ALPHA, real BETA)
Definition at line 125 of file speclib.f.
References exitt(), and zwgjd().
zwgjd()
subroutine zwgjd (real*8, dimension(1) Z, real*8, dimension(1) W, NP, real*8 ALPHA, real*8 BETA)
Definition at line 156 of file speclib.f.
References exitt(), gammaf(), jacg(), jacobf(), and pnormj().
zwgl()
subroutine zwgl (real, dimension(1) Z, real, dimension(1) W, NP)
Definition at line 91 of file speclib.f.
References zwgj().
zwglj()
subroutine zwglj (real, dimension(1) Z, real, dimension(1) W, NP, real ALPHA, real BETA)
Definition at line 208 of file speclib.f.
References exitt(), and zwgljd().
zwgljd()
subroutine zwgljd (real*8, dimension(np) Z, real*8, dimension(np) W, NP, real*8 ALPHA, real*8 BETA)
Definition at line 239 of file speclib.f.
References endw1(), endw2(), exitt(), jacobf(), and zwgjd().
zwgll()
subroutine zwgll (real, dimension(1) Z, real, dimension(1) W, NP)
Definition at line 108 of file speclib.f.
References zwglj().