KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/ssolv.f File Reference
ssolv.f File Reference
Functions/Subroutines
subroutine sstest (ISSS)
subroutine ssinit (KMAX)
subroutine chkext (IFACCX, Z, S)
subroutine filllag
subroutine gonstep (N, ITEST)
subroutine go1step (X, Y, NVEC)
subroutine gostep
subroutine modprop
subroutine mkvec (X)
subroutine mkarr (X)
subroutine ssparam (KMAX, L)
subroutine chkssvt
subroutine chkssv
subroutine chksst
subroutine ssnormd (DV1, DV2, DV3)
subroutine ssnormp (DV1, DV2, DV3)
subroutine settolv
subroutine settolt
subroutine chktolp (TOLMIN)
subroutine setchar
subroutine project
Function/Subroutine Documentation
chkext()
subroutine chkext (logical IFACCX, real*8, dimension(1) Z, real*8, dimension(1) S)
Definition at line 81 of file ssolv.f.
References filllag(), mkarr(), mkvec(), rzero(), and unorm().
chksst()
subroutine chksst ()
Definition at line 570 of file ssolv.f.
References axhelm(), col2(), col3(), dssum(), exitt(), glsum(), lelt, ly1, lz1, normsc(), sethlm(), settolt(), and sub3().
chkssv()
subroutine chkssv ()
Definition at line 480 of file ssolv.f.
References col3(), exitt(), glsc2(), glsum(), ly1, lz1, normvc(), opcol2(), opcolv3(), opdiv(), opdssum(), ophx(), opmask(), opsub3(), sethlm(), and settolv().
chkssvt()
subroutine chkssvt ()
Definition at line 447 of file ssolv.f.
References chksst(), and chkssv().
chktolp()
subroutine chktolp (TOLMIN)
Definition at line 724 of file ssolv.f.
References col2(), col3(), glsum(), opdiv(), and settolv().
filllag()
subroutine filllag ()
Definition at line 158 of file ssolv.f.
References lagscal(), and lagvel().
go1step()
subroutine go1step (real*8, dimension(1) X, real*8, dimension(1) Y, NVEC)
Definition at line 198 of file ssolv.f.
References chkssvt(), comment(), fluid(), geneig(), gengeom(), heat(), meshv(), mkarr(), mkvec(), modprop(), prepost(), setprop(), setsolv(), and settime().
gonstep()
subroutine gonstep (N, ITEST)
Definition at line 177 of file ssolv.f.
References gostep().
gostep()
subroutine gostep ()
Definition at line 240 of file ssolv.f.
References chkssvt(), comment(), fluid(), geneig(), gengeom(), heat(), meshv(), modprop(), prepost(), setprop(), setsolv(), and settime().
mkarr()
subroutine mkarr (real*8, dimension(1) X)
Definition at line 348 of file ssolv.f.
References ly1, and lz1.
mkvec()
subroutine mkvec (real*8, dimension(1) X)
Definition at line 305 of file ssolv.f.
References ly1, and lz1.
modprop()
subroutine modprop ()
Definition at line 279 of file ssolv.f.
References cmult(), ly1, and lz1.
project()
subroutine project ()
Definition at line 779 of file ssolv.f.
References chsign(), ly1, lz1, opadd2(), opbinv(), opdiv(), opgradt(), ortho(), rone(), rzero(), and uzawa().
setchar()
subroutine setchar ()
Definition at line 744 of file ssolv.f.
settolt()
subroutine settolt ()
Definition at line 693 of file ssolv.f.
References glmin(), ly1, lz1, and tnorm().
settolv()
subroutine settolv ()
Definition at line 648 of file ssolv.f.
References glmax(), glmin(), ly1, and lz1.
ssinit()
subroutine ssinit (KMAX)
Definition at line 27 of file ssolv.f.
References setchar(), and setprop().
ssnormd()
subroutine ssnormd (real, dimension(1) DV1, real, dimension(1) DV2, real, dimension(1) DV3)
Definition at line 629 of file ssolv.f.
References normvc().
ssnormp()
subroutine ssnormp (real, dimension(1) DV1, real, dimension(1) DV2, real, dimension(1) DV3)
Definition at line 639 of file ssolv.f.
References normvc().
ssparam()
subroutine ssparam (KMAX, L)
Definition at line 391 of file ssolv.f.
References setchar(), and ssinit().
sstest()
subroutine sstest (ISSS)
Definition at line 2 of file ssolv.f.
References exitt().