KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/ssyev.f File Reference
ssyev.f File Reference
Functions/Subroutines
subroutine slae2 (A, B, C, RT1, RT2)
subroutine slaev2 (A, B, C, RT1, RT2, CS1, SN1)
real function slanst (NORM, N, D, E)
real function slansy (NORM, UPLO, N, A, LDA, WORK)
real function slapy2 (X, Y)
subroutine slarf (SIDE, M, N, V, INCV, TAU, C, LDC, WORK)
subroutine slarfb (SIDE, TRANS, DIRECT, STOREV, M, N, K, V, LDV, T, LDT, C, LDC, WORK, LDWORK)
subroutine slarfg (N, ALPHA, X, INCX, TAU)
subroutine slarft (DIRECT, STOREV, N, K, V, LDV, TAU, T, LDT)
subroutine slartg (F, G, CS, SN, R)
subroutine slascl (TYPE, KL, KU, CFROM, CTO, M, N, A, LDA, INFO)
subroutine slaset (UPLO, M, N, ALPHA, BETA, A, LDA)
subroutine slasr (SIDE, PIVOT, DIRECT, M, N, C, S, A, LDA)
subroutine slasrt (ID, N, D, INFO)
subroutine slassq (N, X, INCX, SCALE, SUMSQ)
subroutine slatrd (UPLO, N, NB, A, LDA, E, TAU, W, LDW)
subroutine sorg2l (M, N, K, A, LDA, TAU, WORK, INFO)
subroutine sorg2r (M, N, K, A, LDA, TAU, WORK, INFO)
subroutine sorgql (M, N, K, A, LDA, TAU, WORK, LWORK, INFO)
subroutine sorgqr (M, N, K, A, LDA, TAU, WORK, LWORK, INFO)
subroutine sorgtr (UPLO, N, A, LDA, TAU, WORK, LWORK, INFO)
subroutine spotf2 (UPLO, N, A, LDA, INFO)
subroutine spotrf (UPLO, N, A, LDA, INFO)
subroutine ssteqr (COMPZ, N, D, E, Z, LDZ, WORK, INFO)
subroutine ssterf (N, D, E, INFO)
subroutine ssyev (JOBZ, UPLO, N, A, LDA, W, WORK, LWORK, INFO)
subroutine ssygs2 (ITYPE, UPLO, N, A, LDA, B, LDB, INFO)
subroutine ssygst (ITYPE, UPLO, N, A, LDA, B, LDB, INFO)
subroutine ssygv (ITYPE, JOBZ, UPLO, N, A, LDA, B, LDB, W, WORK, LWORK, INFO)
subroutine ssytd2 (UPLO, N, A, LDA, D, E, TAU, INFO)
subroutine ssytrd (UPLO, N, A, LDA, D, E, TAU, WORK, LWORK, INFO)
real function slamch (CMACH)
subroutine slamc1 (BETA, T, RND, IEEE1)
subroutine slamc2 (BETA, T, RND, EPS, EMIN, RMIN, EMAX, RMAX)
real function slamc3 (A, B)
subroutine slamc4 (EMIN, START, BASE)
subroutine slamc5 (BETA, P, EMIN, IEEE, EMAX, RMAX)
integer function ilaenv (ISPEC, NAME, OPTS, N1, N2, N3, N4)
Function/Subroutine Documentation
integer function ilaenv (integer ISPEC, character*(*) NAME, character*(*) OPTS, integer N1, integer N2, integer N3, integer N4)
Definition at line 7472 of file ssyev.f.
References ilaenv().
subroutine slae2 (real A, real B, real C, real RT1, real RT2)
Definition at line 2 of file ssyev.f.
subroutine slaev2 (real A, real B, real C, real RT1, real RT2, real CS1, real SN1)
Definition at line 126 of file ssyev.f.
subroutine slamc1 (integer BETA, integer T, logical RND, logical IEEE1)
Definition at line 6744 of file ssyev.f.
subroutine slamc2 (integer BETA, integer T, logical RND, real EPS, integer EMIN, real RMIN, integer EMAX, real RMAX)
Definition at line 6931 of file ssyev.f.
References slamc1(), slamc4(), and slamc5().
real function slamc3 (real A, real B)
Definition at line 7190 of file ssyev.f.
References slamc3().
subroutine slamc4 (integer EMIN, real START, integer BASE)
Definition at line 7228 of file ssyev.f.
subroutine slamc5 (integer BETA, integer P, integer EMIN, logical IEEE, integer EMAX, real RMAX)
Definition at line 7312 of file ssyev.f.
real function slamch (character CMACH)
Definition at line 6614 of file ssyev.f.
References slamc2(), and slamch().
real function slanst (character NORM, integer N, real, dimension(*) D, real, dimension(*) E)
Definition at line 296 of file ssyev.f.
References slanst(), and slassq().
real function slansy (character NORM, character UPLO, integer N, real, dimension(lda, *) A, integer LDA, real, dimension(*) WORK)
Definition at line 421 of file ssyev.f.
References slansy(), and slassq().
real function slapy2 (real X, real Y)
Definition at line 595 of file ssyev.f.
References slapy2().
subroutine slarf (character SIDE, integer M, integer N, real, dimension(*) V, integer INCV, real TAU, real, dimension(ldc, *) C, integer LDC, real, dimension(*) WORK)
Definition at line 649 of file ssyev.f.
References sgemv(), and sger().
subroutine slarfb (character SIDE, character TRANS, character DIRECT, character STOREV, integer M, integer N, integer K, real, dimension(ldv, *) V, integer LDV, real, dimension(ldt, *) T, integer LDT, real, dimension(ldc, *) C, integer LDC, real, dimension(ldwork, *) WORK, integer LDWORK)
Definition at line 766 of file ssyev.f.
References scopy(), sgemm(), and strmm().
subroutine slarfg (integer N, real ALPHA, real, dimension(*) X, integer INCX, real TAU)
Definition at line 1353 of file ssyev.f.
References sscal().
subroutine slarft (character DIRECT, character STOREV, integer N, integer K, real, dimension(ldv, *) V, integer LDV, real, dimension(*) TAU, real, dimension(ldt, *) T, integer LDT)
Definition at line 1491 of file ssyev.f.
References sgemv(), and strmv().
subroutine slartg (real F, real G, real CS, real SN, real R)
Definition at line 1709 of file ssyev.f.
subroutine slascl (character TYPE, integer KL, integer KU, real CFROM, real CTO, integer M, integer N, real, dimension(lda, *) A, integer LDA, integer INFO)
Definition at line 1852 of file ssyev.f.
References xerbla().
subroutine slaset (character UPLO, integer M, integer N, real ALPHA, real BETA, real, dimension(lda, *) A, integer LDA)
Definition at line 2120 of file ssyev.f.
subroutine slasr (character SIDE, character PIVOT, character DIRECT, integer M, integer N, real, dimension(*) C, real, dimension(*) S, real, dimension(lda, *) A, integer LDA)
Definition at line 2235 of file ssyev.f.
References xerbla().
subroutine slasrt (character ID, integer N, real, dimension(*) D, integer INFO)
Definition at line 2560 of file ssyev.f.
References i, j, tmp, and xerbla().
subroutine slassq (integer N, real, dimension(*) X, integer INCX, real SCALE, real SUMSQ)
Definition at line 2804 of file ssyev.f.
subroutine slatrd (character UPLO, integer N, integer NB, real, dimension(lda, *) A, integer LDA, real, dimension(*) E, real, dimension(*) TAU, real, dimension(ldw, *) W, integer LDW)
Definition at line 2893 of file ssyev.f.
References saxpy(), sgemv(), slarfg(), sscal(), and ssymv().
subroutine sorg2l (integer M, integer N, integer K, real, dimension(lda, *) A, integer LDA, real, dimension(*) TAU, real, dimension(*) WORK, integer INFO)
Definition at line 3152 of file ssyev.f.
References slarf(), sscal(), and xerbla().
subroutine sorg2r (integer M, integer N, integer K, real, dimension(lda, *) A, integer LDA, real, dimension(*) TAU, real, dimension(*) WORK, integer INFO)
Definition at line 3280 of file ssyev.f.
References slarf(), sscal(), and xerbla().
subroutine sorgql (integer M, integer N, integer K, real, dimension(lda, *) A, integer LDA, real, dimension(*) TAU, real, dimension(lwork) WORK, integer LWORK, integer INFO)
Definition at line 3410 of file ssyev.f.
References nx, slarfb(), slarft(), sorg2l(), and xerbla().
subroutine sorgqr (integer M, integer N, integer K, real, dimension(lda, *) A, integer LDA, real, dimension(*) TAU, real, dimension(lwork) WORK, integer LWORK, integer INFO)
Definition at line 3615 of file ssyev.f.
References nx, slarfb(), slarft(), sorg2r(), and xerbla().
subroutine sorgtr (character UPLO, integer N, real, dimension(lda, *) A, integer LDA, real, dimension(*) TAU, real, dimension(lwork) WORK, integer LWORK, integer INFO)
Definition at line 3823 of file ssyev.f.
References sorgql(), sorgqr(), and xerbla().
subroutine spotf2 (character UPLO, integer N, real, dimension(lda, *) A, integer LDA, integer INFO)
Definition at line 3986 of file ssyev.f.
References sgemv(), sscal(), and xerbla().
subroutine spotrf (character UPLO, integer N, real, dimension(lda, *) A, integer LDA, integer INFO)
Definition at line 4154 of file ssyev.f.
References sgemm(), spotf2(), ssyrk(), strsm(), and xerbla().
subroutine ssteqr (character COMPZ, integer N, real, dimension(*) D, real, dimension(*) E, real, dimension(ldz, *) Z, integer LDZ, real, dimension(*) WORK, integer INFO)
Definition at line 4338 of file ssyev.f.
References slae2(), slaev2(), slartg(), slascl(), slaset(), slasr(), slasrt(), sswap(), tst(), and xerbla().
subroutine ssterf (integer N, real, dimension(*) D, real, dimension(*) E, integer INFO)
Definition at line 4839 of file ssyev.f.
References slae2(), slascl(), slasrt(), tst(), and xerbla().
subroutine ssyev (character JOBZ, character UPLO, integer N, real, dimension(lda, *) A, integer LDA, real, dimension(*) W, real, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 5218 of file ssyev.f.
References slascl(), sorgtr(), sscal(), ssteqr(), ssterf(), ssytrd(), and xerbla().
subroutine ssygs2 (integer ITYPE, character UPLO, integer N, real, dimension(lda, *) A, integer LDA, real, dimension(ldb, *) B, integer LDB, integer INFO)
Definition at line 5416 of file ssyev.f.
References saxpy(), sscal(), ssyr2(), strmv(), strsv(), and xerbla().
subroutine ssygst (integer ITYPE, character UPLO, integer N, real, dimension(lda, *) A, integer LDA, real, dimension(ldb, *) B, integer LDB, integer INFO)
Definition at line 5628 of file ssyev.f.
References ssygs2(), ssymm(), ssyr2k(), strmm(), strsm(), and xerbla().
subroutine ssygv (integer ITYPE, character JOBZ, character UPLO, integer N, real, dimension(lda, *) A, integer LDA, real, dimension(ldb, *) B, integer LDB, real, dimension(*) W, real, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 5879 of file ssyev.f.
References spotrf(), ssyev(), ssygst(), strmm(), strsm(), and xerbla().
subroutine ssytd2 (character UPLO, integer N, real, dimension(lda, *) A, integer LDA, real, dimension(*) D, real, dimension(*) E, real, dimension(*) TAU, integer INFO)
Definition at line 6087 of file ssyev.f.
References saxpy(), slarfg(), ssymv(), ssyr2(), and xerbla().
subroutine ssytrd (character UPLO, integer N, real, dimension(lda, *) A, integer LDA, real, dimension(*) D, real, dimension(*) E, real, dimension(*) TAU, real, dimension(*) WORK, integer LWORK, integer INFO)
Definition at line 6335 of file ssyev.f.
References slatrd(), ssyr2k(), ssytd2(), and xerbla().