KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/stack.c File Reference
stack.c File Reference
#include <stdio.h>
#include "stack.h"
#include "error.h"
#include "bss_malloc.h"
Data Structures
struct node
struct stack_CDT
Functions
stack_ADT new_stack (void)
void free_stack (stack_ADT s)
void push (stack_ADT s, void *obj)
void * pop (stack_ADT s)
int len_stack (stack_ADT s)
Function Documentation
void free_stack (stack_ADT s)
Definition at line 60 of file stack.c.
References bss_free(), error_msg_fatal(), error_msg_warning(), and node::next.
int len_stack (stack_ADT s)
Definition at line 161 of file stack.c.
stack_ADT new_stack (void)
Definition at line 38 of file stack.c.
References bss_malloc().
void* pop (stack_ADT s)
Definition at line 129 of file stack.c.
References bss_free(), error_msg_fatal(), node::next, and node::obj.
void push (stack_ADT s, void * obj)
Definition at line 105 of file stack.c.
References bss_malloc(), node::next, and node::obj.