KTH framework for Nek5000 toolboxes; testing version: Toolbox/tools/stat/stat_IO.f File Reference
stat_IO.f File Reference
IO routines for 2D/3D statistics module.
Functions/Subroutines
subroutine stat_mfo ()
Main interface for saving statistics.
subroutine stat_mfo_outfld3d ()
Statistics muti-file output of 3D data.
subroutine stat_mfo_outfld2d ()
Statistics muti-file output of 2D data.
subroutine stat_mfo_write_hdr2d
Write hdr, byte key, global ordering of 2D data.
subroutine stat_mfo_write_stat2d
Write additional data at the end of the file.
subroutine stat_mfo_crd2d
Write element centres to the file (in case of AMR level as well)
Detailed Description
IO routines for 2D/3D statistics module.
This is a set of routines to write 2D statistics to the file. They are modiffication of the existing nek5000 routines
Note
This code works for extruded meshes only
Author
Prabal Negi, Adam Peplinski
Date
Aug 15, 2018
Definition in file stat_IO.f.
Function/Subroutine Documentation
stat_mfo()
subroutine stat_mfo
Main interface for saving statistics.
Definition at line 13 of file stat_IO.f.
References stat_mfo_outfld2d(), and stat_mfo_outfld3d().
stat_mfo_crd2d()
subroutine stat_mfo_crd2d
Write element centres to the file (in case of AMR level as well)
Definition at line 482 of file stat_IO.f.
References blank(), byte_close, byte_close_mpi(), byte_set_view(), byte_write, byte_write_mpi(), crecv(), csend(), igllm(), mfo_open_files(), mntr_check_abort(), mxm(), and zwgll().
stat_mfo_outfld2d()
subroutine stat_mfo_outfld2d
Statistics muti-file output of 2D data.
This routine is just modification of mfo_outfld
Remarks
This routine uses global scratch space SCRUZ
Definition at line 100 of file stat_IO.f.
References byte_close, byte_close_mpi(), byte_set_view(), copy(), mfo_open_files(), mfo_outs(), mntr_check_abort(), stat_mfo_crd2d(), stat_mfo_write_hdr2d(), and stat_mfo_write_stat2d().
stat_mfo_outfld3d()
subroutine stat_mfo_outfld3d
Statistics muti-file output of 3D data.
Definition at line 30 of file stat_IO.f.
References outpost().
stat_mfo_write_hdr2d()
subroutine stat_mfo_write_hdr2d
Write hdr, byte key, global ordering of 2D data.
This routine is just modification of mfo_write_hdr
Remarks
This routine uses global scratch space CTMP0
Definition at line 316 of file stat_IO.f.
References blank(), byte_set_view(), byte_write, byte_write_mpi(), crecv(), csend(), and mntr_check_abort().
stat_mfo_write_stat2d()
subroutine stat_mfo_write_stat2d
Write additional data at the end of the file.
Definition at line 463 of file stat_IO.f.