KTH framework for Nek5000 toolboxes; testing version: Toolbox/tools/stat/stat.f File Reference
stat.f File Reference
2D and 3D statistics module
Functions/Subroutines
subroutine stat_register ()
Register 2D and 3D statistics module.
subroutine stat_init ()
Initilise statistics module.
logical function stat_is_initialised ()
Check if module was initialised.
subroutine stat_avg
Main interface of statistics module.
subroutine stat_init_int1d ()
Get local integration coefficients.
subroutine stat_reshufflev (rvar, var, nl)
Array reshuffle.
subroutine stat_compute_1dav1 (lvar, npos, alpha, beta)
Perform local 1D integration on 1 variable.
subroutine stat_compute_1dav2 (lvar1, lvar2, npos, alpha, beta)
Perform local 1D integration on multiplication of 2 variables.
subroutine stat_gs_sum
Global statistics summation.
subroutine stat_compute ()
Compute statistics.
Detailed Description
2D and 3D statistics module
Note
This code works for extruded meshes only
Author
Prabal Negi, Adam Peplinski
Date
Aug 15, 2018
Definition in file stat.f.
Function/Subroutine Documentation
stat_avg()
subroutine stat_avg
Main interface of statistics module.
This routine performs time averaging and file writing.
Note
This routine should be called in userchk during every step
Definition at line 190 of file stat.f.
References mntr_log(), mntr_tmr_add(), rzero(), stat_compute(), stat_gs_sum(), and stat_mfo().
stat_compute()
subroutine stat_compute
Compute statistics.
Remarks
This routine uses global scratch space SCRMG, SCRUZ, SCRNS, SCRSF
Definition at line 726 of file stat.f.
References add2(), col3(), copy(), mappr(), mntr_log(), stat_compute_1dav1(), stat_compute_1dav2(), and stat_reshufflev().
stat_compute_1dav1()
subroutine stat_compute_1dav1 (real, dimension(lx1,ly1,lz1,lelt) lvar, integer npos, real alpha, real beta)
Perform local 1D integration on 1 variable.
Parameters
[in] lvar integrated variable
[in] npos position in stat_ruavg
[in] alpha,beta time averaging parameters
Remarks
This routine uses global scratch space CTMP0
Definition at line 529 of file stat.f.
References add2sxy(), mntr_abort(), and rzero().
stat_compute_1dav2()
subroutine stat_compute_1dav2 (real, dimension(lx1,ly1,lz1,lelt) lvar1, real, dimension(lx1,ly1,lz1,lelt) lvar2, integer npos, real alpha, real beta)
Perform local 1D integration on multiplication of 2 variables.
Parameters
[in] lvar1,lvar2 integrated variable
[in] npos position in stat_ruavg
[in] alpha,beta time averaging parameters
Remarks
This routine uses global scratch space CTMP0
Definition at line 586 of file stat.f.
References add2sxy(), col3(), mntr_abort(), and rzero().
stat_gs_sum()
subroutine stat_gs_sum
Global statistics summation.
Definition at line 642 of file stat.f.
References copy(), invcol2(), mntr_log(), and rzero().
stat_init()
subroutine stat_init
Initilise statistics module.
Note
This routine should be called in frame_usr_init
Definition at line 108 of file stat.f.
References map2d_init(), mntr_log(), mntr_tmr_add(), mntr_warn(), rprm_rp_get(), rzero(), and stat_init_int1d().
stat_init_int1d()
subroutine stat_init_int1d
Get local integration coefficients.
This version does 1D integration over one of the directions R,S,T. It supports curved coordinate systems, however axisymmetric 2.5D cases are not supported
Remarks
This routine uses global scratch space SCRSF
Definition at line 273 of file stat.f.
References add2(), copy(), mntr_abort(), mxm(), rzero(), stat_reshufflev(), vsq(), and vsqrt().
stat_is_initialised()
logical function stat_is_initialised
Check if module was initialised.
Returns
stat_is_initialised
Definition at line 175 of file stat.f.
stat_register()
subroutine stat_register
Register 2D and 3D statistics module.
Note
This routine should be called in frame_usr_register
Definition at line 13 of file stat.f.
References map2d_register(), mntr_abort(), mntr_mod_is_name_reg(), mntr_mod_reg(), mntr_tmr_add(), mntr_tmr_is_name_reg(), mntr_tmr_reg(), mntr_warn(), rprm_rp_reg(), rprm_sec_reg(), and rprm_sec_set_act().
stat_reshufflev()
subroutine stat_reshufflev (real, dimension(lx1,ly1,lz1,lelt) rvar, real, dimension(lx1,ly1,lz1,lelt) var, integer nl)
Array reshuffle.
Reorder directions in such a way that the uniform direction corresponds to the the first index
Parameters
[out] rvar reshuffled array
[in] var input array
[in] nl element number to reshuffle
Definition at line 460 of file stat.f.
References copy().