KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/cmt/step.f File Reference
step.f File Reference
time stepping and mesh spacing routines
Functions/Subroutines
subroutine setdtcmt
subroutine mindr (mdr, diffno)
real function dist2 (x1, y1, x2, y2)
subroutine compute_grid_h (h, x, y, z)
subroutine glinvcol2max (col2m, a, b, n, s)
subroutine glsqinvcolmin (col2m, a, b, n, s)
subroutine compute_mesh_h (h, x, y, z)
Detailed Description
time stepping and mesh spacing routines
Definition in file step.f.
Function/Subroutine Documentation
subroutine compute_grid_h (real, dimension(nx1,ny1,nz1,nelt) h, real, dimension(nx1,ny1,nz1,nelt) x, real, dimension(nx1,ny1,nz1,nelt) y, real, dimension(nx1,ny1,nz1,nelt) z)
Definition at line 159 of file step.f.
References cross(), and dot().
subroutine compute_mesh_h (real, dimension(nelt) h, real, dimension(nx1,ny1,nz1,nelt) x, real, dimension(nx1,ny1,nz1,nelt) y, real, dimension(nx1,ny1,nz1,nelt) z)
Definition at line 286 of file step.f.
References rzero().
real function dist2 (real x1, real y1, real x2, real y2)
Definition at line 147 of file step.f.
subroutine glinvcol2max (real col2m, real, dimension(*) a, real, dimension(*) b, n, real s)
Definition at line 258 of file step.f.
References glamax(), i, and n.
subroutine glsqinvcolmin (real col2m, real, dimension(*) a, real, dimension(*) b, n, real s)
Definition at line 272 of file step.f.
References glamin(), i, and n.
subroutine mindr (real mdr, diffno)
Definition at line 89 of file step.f.
References dist2(), exitt(), glmax(), and glmin().
subroutine setdtcmt ()
Definition at line 3 of file step.f.
References compute_cfl(), exitt(), glinvcol2max(), glsqinvcolmin(), i, lelt, ly1, and lz1.