KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/subs2.f File Reference
subs2.f File Reference
Functions/Subroutines
subroutine setaxw1 (IFAXWG)
subroutine setaxw2 (IFAXWG)
subroutine stnrinv
subroutine opdot (DP, A1, A2, A3, B1, B2, B3, N)
subroutine opadds (A1, A2, A3, B1, B2, B3, CONST, N, ISC)
subroutine facexs (A, B, IFACE1, IOP)
subroutine facexv (A1, A2, A3, B1, B2, B3, IFACE1, IOP)
subroutine facsub2 (A1, A2, A3, B1, B2, B3, IFACE1)
subroutine gammasf (H1, H2)
subroutine cmult2 (A, B, CONST, N)
subroutine add3s (A, B, C, CONST, N)
subroutine emerxit
subroutine faccvs (A1, A2, A3, B, IFACE1)
subroutine stx1sf
subroutine solvel
subroutine vsoln (UX, UY, UZ, X, Y, Z, PI)
subroutine solpres
subroutine prsoln (P, X, Y, Z, PI)
subroutine printel (TA, A, IEL)
subroutine printv (TA, A, NEL)
subroutine outf1 (X, TXT, IEL, IFC)
subroutine outm1 (X, TXT, NP, IEL, IP)
subroutine outm2 (X, TXT, NP, IEL, IP)
subroutine stsmask (C1MASK, C2MASK, C3MASK)
subroutine updmsys (IFLD)
subroutine sethmsk (HVMASK, HFMASK, IFLD, NEL)
subroutine skipcnr (NEL)
subroutine setmask (C1MASK, C2MASK, C3MASK, HVMASK, NEL)
subroutine setmlog (HVMASK, HFMASK, IFLD, NEL)
subroutine setcsys (HVMASK, HFMASK, NEL)
subroutine comavn2 (HVMASK, HFMASK, NEL)
subroutine comavn3 (HVMASK, HFMASK, NEL)
subroutine fixwmsk (W2MASK, W3MASK, HVMASK, HFMASK, NEL)
subroutine fxwms2 (W2MASK, HVMASK, HFMASK, NEL)
subroutine fxwms3 (W2MASK, W3MASK, HVMASK, HFMASK, NEL)
subroutine setcdat
subroutine edgindf (LF1, LF2, LFSKIP, ISD, IFCN)
subroutine edgindv (LV1, LV2, LVSKIP, ISD)
subroutine setcdof
subroutine amask (VB1, VB2, VB3, V1, V2, V3, NEL)
subroutine rmask (R1, R2, R3, NEL)
subroutine qmask (R1, R2, R3, R1MASK, R2MASK, R3MASK, NEL)
subroutine fcmsk2 (R1, R2, S1, S2, R1MASK, R2MASK, NEL)
subroutine fcmsk3 (R1, R2, R3, S1, S2, S3, R1MASK, R2MASK, R3MASK, NEL)
subroutine egmask (R1, R2, R3, S1, S2, S3, R1MASK, R2MASK, R3MASK, NEL)
subroutine crmsk2 (R1, R2, S1, S2, R1MASK, R2MASK, NEL)
subroutine crmsk3 (R1, R2, R3, S1, S2, S3, R1MASK, R2MASK, R3MASK, NEL)
subroutine getsnormal (sn, ix, iy, iz, iside, e)
subroutine fixmska (c1mask, c2mask, c3mask)
subroutine icol2 (a, b, n)
subroutine iface_e (a, iface, val, nx, ny, nz)
function op_vlsc2_wt (b1, b2, b3, x1, x2, x3, wt)
function op_glsc2_wt (b1, b2, b3, x1, x2, x3, wt)
Function/Subroutine Documentation
add3s()
subroutine add3s (dimension(1) A, dimension(1) B, dimension(1) C, CONST, N)
Definition at line 340 of file subs2.f.
amask()
subroutine amask (dimension(lx1,ly1,lz1,1) VB1, dimension(lx1,ly1,lz1,1) VB2, dimension(lx1,ly1,lz1,1) VB3, dimension(lx1,ly1,lz1,1) V1, dimension(lx1,ly1,lz1,1) V2, dimension(lx1,ly1,lz1,1) V3, NEL)
Definition at line 1719 of file subs2.f.
References copy(), lelt, ly1, lz1, qmask(), rone(), and sub3().
cmult2()
subroutine cmult2 (dimension(1) A, dimension(1) B, CONST, N)
Definition at line 333 of file subs2.f.
comavn2()
subroutine comavn2 (dimension(lx1,ly1,lz1,1) HVMASK, dimension(lx1,lz1,6,1) HFMASK, NEL)
Definition at line 1011 of file subs2.f.
References chsign(), copy(), dssum(), ly1, lz1, rzero(), and unitvec().
comavn3()
subroutine comavn3 (dimension(lx1,ly1,lz1,1) HVMASK, dimension(lx1,lz1,6,1) HFMASK, NEL)
Definition at line 1075 of file subs2.f.
References dssum(), edgindf(), edgindv(), facind2(), lelt, ly1, lz1, unitvec(), vcross(), and vdot3().
crmsk2()
subroutine crmsk2 (dimension(lx1,ly1,lz1,1) R1, dimension(lx1,ly1,lz1,1) R2, dimension(lx1,ly1,lz1,1) S1, dimension(lx1,ly1,lz1,1) S2, dimension(lx1,ly1,lz1,1) R1MASK, dimension(lx1,ly1,lz1,1) R2MASK, NEL)
Definition at line 1984 of file subs2.f.
References ly1, and lz1.
crmsk3()
subroutine crmsk3 (dimension(lx1,ly1,lz1,1) R1, dimension(lx1,ly1,lz1,1) R2, dimension(lx1,ly1,lz1,1) R3, dimension(lx1,ly1,lz1,1) S1, dimension(lx1,ly1,lz1,1) S2, dimension(lx1,ly1,lz1,1) S3, dimension(lx1,ly1,lz1,1) R1MASK, dimension(lx1,ly1,lz1,1) R2MASK, dimension(lx1,ly1,lz1,1) R3MASK, NEL)
Definition at line 2029 of file subs2.f.
References ly1, and lz1.
edgindf()
subroutine edgindf (LF1, LF2, LFSKIP, ISD, IFCN)
Definition at line 1646 of file subs2.f.
edgindv()
subroutine edgindv (LV1, LV2, LVSKIP, ISD)
Definition at line 1671 of file subs2.f.
egmask()
subroutine egmask (dimension(lx1,ly1,lz1,1) R1, dimension(lx1,ly1,lz1,1) R2, dimension(lx1,ly1,lz1,1) R3, dimension(lx1,ly1,lz1,1) S1, dimension(lx1,ly1,lz1,1) S2, dimension(lx1,ly1,lz1,1) S3, dimension(lx1,ly1,lz1,1) R1MASK, dimension(lx1,ly1,lz1,1) R2MASK, dimension(lx1,ly1,lz1,1) R3MASK, NEL)
Definition at line 1936 of file subs2.f.
References edgindv(), ly1, and lz1.
emerxit()
subroutine emerxit ()
Definition at line 347 of file subs2.f.
References exitt(), prepost(), and runstat().
faccvs()
subroutine faccvs (dimension(lx1,ly1,lz1) A1, dimension(lx1,ly1,lz1) A2, dimension(lx1,ly1,lz1) A3, dimension(lx1,ly1) B, IFACE1)
Definition at line 381 of file subs2.f.
References dsset(), ly1, and lz1.
facexs()
subroutine facexs (dimension(lx1,ly1) A, dimension(lx1,ly1,lz1) B, IFACE1, IOP)
Definition at line 121 of file subs2.f.
References dsset(), ly1, and lz1.
facexv()
subroutine facexv (dimension(lx1,ly1) A1, dimension(lx1,ly1) A2, dimension(lx1,ly1) A3, dimension(lx1,ly1,lz1) B1, dimension(lx1,ly1,lz1) B2, dimension(lx1,ly1,lz1) B3, IFACE1, IOP)
Definition at line 165 of file subs2.f.
References dsset(), ly1, and lz1.
facsub2()
subroutine facsub2 (dimension(lx1,ly1,lz1) A1, dimension(lx1,ly1,lz1) A2, dimension(lx1,ly1,lz1) A3, dimension(lx1,ly1) B1, dimension(lx1,ly1) B2, dimension(lx1,ly1) B3, IFACE1)
Definition at line 214 of file subs2.f.
References dsset(), ly1, and lz1.
fcmsk2()
subroutine fcmsk2 (dimension(lx1,ly1,lz1,1) R1, dimension(lx1,ly1,lz1,1) R2, dimension(lx1,ly1,lz1,1) S1, dimension(lx1,ly1,lz1,1) S2, dimension(lx1,ly1,lz1,1) R1MASK, dimension(lx1,ly1,lz1,1) R2MASK, NEL)
Definition at line 1852 of file subs2.f.
References facind2(), ly1, and lz1.
fcmsk3()
subroutine fcmsk3 (dimension(lx1,ly1,lz1,1) R1, dimension(lx1,ly1,lz1,1) R2, dimension(lx1,ly1,lz1,1) R3, dimension(lx1,ly1,lz1,1) S1, dimension(lx1,ly1,lz1,1) S2, dimension(lx1,ly1,lz1,1) S3, dimension(lx1,ly1,lz1,1) R1MASK, dimension(lx1,ly1,lz1,1) R2MASK, dimension(lx1,ly1,lz1,1) R3MASK, NEL)
Definition at line 1887 of file subs2.f.
References facind2(), ly1, and lz1.
fixmska()
subroutine fixmska (real, dimension(lx1,ly1,lz1,1) c1mask, real, dimension(lx1,ly1,lz1,1) c2mask, real, dimension(lx1,ly1,lz1,1) c3mask)
Definition at line 2119 of file subs2.f.
References icol2(), iface_e(), izero(), ly1, and lz1.
fixwmsk()
subroutine fixwmsk (dimension(lx1,ly1,lz1,1) W2MASK, dimension(lx1,ly1,lz1,1) W3MASK, dimension(lx1,ly1,lz1,1) HVMASK, dimension(lx1,lz1,6,1) HFMASK, NEL)
Definition at line 1219 of file subs2.f.
References dsop(), fxwms2(), fxwms3(), ly1, and lz1.
fxwms2()
subroutine fxwms2 (dimension(lx1,ly1,lz1,1) W2MASK, dimension(lx1,ly1,lz1,1) HVMASK, dimension(lx1,lz1,6,1) HFMASK, NEL)
Definition at line 1239 of file subs2.f.
References dot(), ly1, and lz1.
fxwms3()
subroutine fxwms3 (dimension(lx1,ly1,lz1,1) W2MASK, dimension(lx1,ly1,lz1,1) W3MASK, dimension(lx1,ly1,lz1,1) HVMASK, dimension(lx1,lz1,6,1) HFMASK, NEL)
Definition at line 1286 of file subs2.f.
References dot(), edgindf(), edgindv(), ly1, and lz1.
gammasf()
subroutine gammasf (dimension(lx1,ly1,lz1,1) H1, dimension(lx1,ly1,lz1,1) H2)
Definition at line 249 of file subs2.f.
References axhmsf(), cmult(), col3(), copy(), emerxit(), exitt(), glsc3(), ly1, lz1, opdssum(), rmask(), and stx1sf().
getsnormal()
subroutine getsnormal (real, dimension(3) sn, ix, iy, iz, iside, integer e)
Definition at line 2089 of file subs2.f.
icol2()
subroutine icol2 (integer, dimension(1) a, integer, dimension(1) b, n)
Definition at line 2163 of file subs2.f.
iface_e()
subroutine iface_e (integer, dimension(nx,ny,nz) a, iface, integer val, nx, ny, nz)
Definition at line 2173 of file subs2.f.
References facind().
op_glsc2_wt()
function op_glsc2_wt (real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) x1, real, dimension(1) x2, real, dimension(1) x3, real, dimension(1) wt)
Definition at line 2213 of file subs2.f.
References glsum(), ly1, and lz1.
op_vlsc2_wt()
function op_vlsc2_wt (real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) x1, real, dimension(1) x2, real, dimension(1) x3, real, dimension(1) wt)
Definition at line 2189 of file subs2.f.
References ly1, and lz1.
opadds()
subroutine opadds (dimension(lx1,ly1,lz1,1) A1, dimension(lx1,ly1,lz1,1) A2, dimension(lx1,ly1,lz1,1) A3, dimension(lx1,ly1,lz1,1) B1, dimension(lx1,ly1,lz1,1) B2, dimension(lx1,ly1,lz1,1) B3, CONST, N, ISC)
Definition at line 98 of file subs2.f.
References add2s1(), add2s2(), ly1, and lz1.
opdot()
subroutine opdot (dimension(lx1,ly1,lz1,1) DP, dimension(lx1,ly1,lz1,1) A1, dimension(lx1,ly1,lz1,1) A2, dimension(lx1,ly1,lz1,1) A3, dimension(lx1,ly1,lz1,1) B1, dimension(lx1,ly1,lz1,1) B2, dimension(lx1,ly1,lz1,1) B3, N)
Definition at line 78 of file subs2.f.
References ly1, lz1, vdot2(), and vdot3().
outf1()
subroutine outf1 (dimension(lx1,lz1,6,lelt) X, character*10 TXT, IEL, IFC)
Definition at line 575 of file subs2.f.
References lelt, and lz1.
outm1()
subroutine outm1 (dimension(lx1,ly1,lz1,lelt) X, character*10 TXT, NP, IEL, IP)
Definition at line 602 of file subs2.f.
References lelt, ly1, and lz1.
outm2()
subroutine outm2 (dimension(lx2,ly2,lz2,lelv) X, character*10 TXT, NP, IEL, IP)
Definition at line 629 of file subs2.f.
printel()
subroutine printel (dimension(lx1,ly1,lz1,lelt) TA, character A, IEL)
Definition at line 535 of file subs2.f.
References lelt, ly1, lz1, and outm1().
printv()
subroutine printv (dimension(lx1,ly1,lz1,lelt) TA, character A, NEL)
Definition at line 552 of file subs2.f.
References lelt, ly1, lz1, and outm1().
prsoln()
subroutine prsoln (P, X, Y, Z, PI)
Definition at line 523 of file subs2.f.
qmask()
subroutine qmask (dimension(lx1,ly1,lz1,1) R1, dimension(lx1,ly1,lz1,1) R2, dimension(lx1,ly1,lz1,1) R3, dimension(lx1,ly1,lz1,1) R1MASK, dimension(lx1,ly1,lz1,1) R2MASK, dimension(lx1,ly1,lz1,1) R3MASK, NEL)
Definition at line 1796 of file subs2.f.
References col2(), copy(), crmsk2(), crmsk3(), egmask(), fcmsk2(), fcmsk3(), lelt, ly1, and lz1.
rmask()
subroutine rmask (dimension (lx1,ly1,lz1,1) R1, dimension (lx1,ly1,lz1,1) R2, dimension (lx1,ly1,lz1,1) R3, NEL)
Definition at line 1762 of file subs2.f.
References ly1, lz1, and qmask().
setaxw1()
subroutine setaxw1 (logical IFAXWG)
Definition at line 2 of file subs2.f.
References copy(), and ly1.
setaxw2()
subroutine setaxw2 (logical IFAXWG)
Definition at line 17 of file subs2.f.
References copy().
setcdat()
subroutine setcdat ()
Definition at line 1368 of file subs2.f.
setcdof()
subroutine setcdof ()
Definition at line 1705 of file subs2.f.
setcsys()
subroutine setcsys (dimension(lx1,ly1,lz1,1) HVMASK, dimension(lx1,lz1,6,1) HFMASK, NEL)
Definition at line 980 of file subs2.f.
References comavn2(), comavn3(), facexv(), ly1, lz1, and rzero3().
sethmsk()
subroutine sethmsk (dimension(lx1,ly1,lz1,1) HVMASK, dimension(lx1,lz1,6,1) HFMASK, IFLD, NEL)
Definition at line 706 of file subs2.f.
References cfill(), dsop(), facev(), ly1, and lz1.
setmask()
subroutine setmask (dimension(lx1,ly1,lz1,1) C1MASK, dimension(lx1,ly1,lz1,1) C2MASK, dimension(lx1,ly1,lz1,1) C3MASK, dimension (lx1,ly1,lz1,1) HVMASK, NEL)
Definition at line 852 of file subs2.f.
References copy(), ly1, lz1, and rzero3().
setmlog()
subroutine setmlog (dimension(lx1,ly1,lz1,1) HVMASK, dimension(lx1,lz1,6,1) HFMASK, IFLD, NEL)
Definition at line 881 of file subs2.f.
References gllog(), lfalse(), ly1, and lz1.
skipcnr()
subroutine skipcnr (NEL)
Definition at line 805 of file subs2.f.
References lfalse().
solpres()
subroutine solpres ()
Definition at line 506 of file subs2.f.
References prsoln().
solvel()
subroutine solvel ()
Definition at line 472 of file subs2.f.
References ly1, lz1, and vsoln().
stnrinv()
subroutine stnrinv ()
Definition at line 32 of file subs2.f.
References add2s2(), addcol3(), col3(), col4(), lelt, ly1, lz1, rzero(), stnrate(), subcol3(), and subcol4().
stsmask()
subroutine stsmask (dimension(lx1,ly1,lz1,1) C1MASK, dimension(lx1,ly1,lz1,1) C2MASK, dimension(lx1,ly1,lz1,1) C3MASK)
Definition at line 655 of file subs2.f.
References fixmska(), fixwmsk(), lelt, ly1, lz1, setcdat(), setcsys(), sethmsk(), setmask(), setmlog(), and skipcnr().
stx1sf()
subroutine stx1sf ()
Definition at line 427 of file subs2.f.
References cmult(), col3(), copy(), glsc3(), ly1, lz1, opdssum(), rmask(), and rzero3().
updmsys()
subroutine updmsys (IFLD)
Definition at line 690 of file subs2.f.
References lelt, ly1, lz1, setcsys(), and sethmsk().
vsoln()
subroutine vsoln (UX, UY, UZ, X, Y, Z, PI)
Definition at line 489 of file subs2.f.