KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/subs1.f File Reference
subs1.f File Reference
Functions/Subroutines
subroutine cggosf (u1, u2, u3, r1, r2, r3, h1, h2, rmult, binv, vol, tin, maxit, matmod)
subroutine setdt
subroutine cvgnlps (ifconv)
subroutine unorm
subroutine chktmg (tol, res, w1, w2, mult, mask, imesh)
subroutine setdtc
subroutine cumax (v1, v2, v3, umax)
subroutine setdtfs (dtfs)
subroutine cdxmin2 (dtst, rhosig, iel, ifc, ifaxis)
subroutine cdxmin3 (dtst, rhosig, iel, ifc)
function facdot (A, B, IFACE1)
subroutine fcaver (xaver, a, iel, iface1)
subroutine faccl2 (a, b, iface1)
subroutine faccl3 (a, b, c, iface1)
subroutine faddcl3 (a, b, c, iface1)
subroutine sethlm (h1, h2, intloc)
subroutine nekuvp (iel)
subroutine diagnos
subroutine setsolv
subroutine hmhzsf (name, u1, u2, u3, r1, r2, r3, h1, h2, rmask1, rmask2, rmask3, rmult, tol, maxit, matmod)
subroutine chktcgs (r1, r2, r3, rmask1, rmask2, rmask3, rmult, binv, vol, tol, nel)
subroutine axhmsf (au1, au2, au3, u1, u2, u3, h1, h2, matmod)
subroutine stnrate (u1, u2, u3, nel, matmod)
subroutine stress (h1, h2, nel, matmod, ifaxis)
subroutine aijuj (au1, au2, au3, nel, ifaxis)
subroutine uxyz (u, ex, ey, ez, nel)
subroutine urst (u, ur, us, ut, nel)
subroutine ddrst (u, ur, us, ut)
subroutine axiezz (u2, eyy, ezz, nel)
subroutine flush_io
subroutine fcsum2 (xsum, asum, x, e, f)
function surf_mean (u, ifld, bc_in, ierr)
subroutine fdm_h1a (z, r, d, nel, kt, rr)
subroutine set_vert_strs (glo_num, ngv, nx, nel, vertex, ifcenter)
subroutine get_strs_mask (mask, nxc, nzc, nel)
subroutine axstrs (a1, a2, a3, p1, p2, p3, h1, h2, matmod, nel)
subroutine axstrs_nds (a1, a2, a3, p1, p2, p3, h1, h2, matmod, nel)
subroutine get_local_crs_galerkin_strs (a, ncl, nxc, h1, h2, matmod)
subroutine crs_strs (u1, u2, u3, v1, v2, v3)
subroutine set_up_h1_crs_strs (h1, h2, ifld, matmod)
subroutine axsf_e_3d (au, av, aw, u, v, w, h1, h2, ur, e)
subroutine axsf_e_2d (au, av, u, v, h1, h2, ur, e)
subroutine axsf_fast (au, av, aw, u, v, w, h1, h2, ifld)
subroutine ttxyz (ff, tx, ty, tz, nel)
subroutine ttrst (ff, fr, fs, ft, ta)
subroutine axitzz (vfy, tzz, nel)
subroutine setaxdy (ifaxdy)
function opnorm2w (v1, v2, v3, w)
subroutine strs_project_a (b1, b2, b3, h1, h2, wt, ifld, ierr, matmod)
subroutine strs_project_b (x1, x2, x3, h1, h2, wt, ifld, ierr)
subroutine strs_orthok (x, b, n, k, h1, h2, wt, ifld, w, ierr, matmod)
subroutine strs_ortho_one (x, b, n, k, h1, h2, wt, ifld, w, ierr, matmod)
subroutine strs_ortho_all (x, b, n, k, h1, h2, wt, ifld, w, ierr, matmod)
subroutine setprop
Function/Subroutine Documentation
aijuj()
subroutine aijuj (dimension(lx1,ly1,lz1,1) au1, dimension(lx1,ly1,lz1,1) au2, dimension(lx1,ly1,lz1,1) au3, nel, logical ifaxis)
Definition at line 1564 of file subs1.f.
References axitzz(), lelt, ly1, lz1, and ttxyz().
axhmsf()
subroutine axhmsf (dimension(lx1,ly1,lz1,1) au1, dimension(lx1,ly1,lz1,1) au2, dimension(lx1,ly1,lz1,1) au3, dimension (lx1*ly1*lz1*1) u1, dimension (lx1*ly1*lz1*1) u2, dimension (lx1*ly1*lz1*1) u3, dimension (lx1,ly1,lz1,1) h1, dimension (lx1,ly1,lz1,1) h2, matmod)
Definition at line 1370 of file subs1.f.
References addcol4(), aijuj(), axhelm(), axsf_fast(), dnekclock(), exitti(), lelt, ly1, lz1, setfast(), stnrate(), and stress().
axiezz()
subroutine axiezz (dimension (lx1,ly1,lz1,1) u2, dimension(lx1,ly1,lz1,1) eyy, dimension(lx1,ly1,lz1,1) ezz, nel)
Definition at line 1663 of file subs1.f.
References invcol3(), ly1, and lz1.
axitzz()
subroutine axitzz (dimension(lx1,ly1,lz1,1) vfy, dimension(lx1,ly1,lz1,1) tzz, nel)
Definition at line 2443 of file subs1.f.
References add2(), col4(), ly1, lz1, and setaxw1().
axsf_e_2d()
subroutine axsf_e_2d (real, dimension(1) au, real, dimension(1) av, real, dimension(1) u, real, dimension(1) v, real, dimension(1) h1, real, dimension(1) h2, real, dimension(l,ldim,ldim) ur, integer e)
Definition at line 2254 of file subs1.f.
References local_grad2(), local_grad2_t(), ly1, and lz1.
axsf_e_3d()
subroutine axsf_e_3d (real, dimension(1) au, real, dimension(1) av, real, dimension(1) aw, real, dimension(1) u, real, dimension(1) v, real, dimension(1) w, real, dimension(1) h1, real, dimension(1) h2, real, dimension(l,ldim,ldim) ur, integer e)
Definition at line 2165 of file subs1.f.
References local_grad3(), local_grad3_t(), ly1, and lz1.
axsf_fast()
subroutine axsf_fast (real, dimension(l,1) au, real, dimension(l,1) av, real, dimension(l,1) aw, real, dimension(l,1) u, real, dimension(l,1) v, real, dimension(l,1) w, real, dimension(l,1) h1, real, dimension(l,1) h2, ifld)
Definition at line 2311 of file subs1.f.
References axsf_e_2d(), axsf_e_3d(), ly1, and lz1.
axstrs()
subroutine axstrs (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) p1, real, dimension(1) p2, real, dimension(1) p3, h1, h2, matmod, nel)
Definition at line 1926 of file subs1.f.
References axhmsf(), opdssum(), and rmask().
axstrs_nds()
subroutine axstrs_nds (real, dimension(1) a1, real, dimension(1) a2, real, dimension(1) a3, real, dimension(1) p1, real, dimension(1) p2, real, dimension(1) p3, h1, h2, matmod, nel)
Definition at line 1936 of file subs1.f.
References axhmsf(), and rmask().
cdxmin2()
subroutine cdxmin2 (dimension(lx1,1) dtst, rhosig, iel, ifc, logical ifaxis)
Definition at line 864 of file subs1.f.
References facec2(), ly1, mxm(), and setaxdy().
cdxmin3()
subroutine cdxmin3 (dimension(lx1,ly1) dtst, rhosig, iel, ifc)
Definition at line 910 of file subs1.f.
References facexv(), ly1, mxm(), and setdrs().
cggosf()
subroutine cggosf (real, dimension(1) u1, real, dimension(1) u2, real, dimension(1) u3, real, dimension(1) r1, real, dimension(1) r2, real, dimension(1) r3, real, dimension(1) h1, real, dimension(1) h2, real, dimension(1) rmult, real, dimension(1) binv, vol, tin, maxit, matmod)
Definition at line 4 of file subs1.f.
References add2(), axhmsf(), col3(), crs_strs(), fdm_h1a(), glsc2(), glsc3(), lelt, ly1, lz1, op_glsc2_wt(), opadd2(), opadds(), opdot(), opdssum(), opzero(), rmask(), set_fdm_prec_h1a(), set_fdm_prec_h1b(), set_up_h1_crs_strs(), setfast(), and setprec().
chktcgs()
subroutine chktcgs (dimension (lx1,ly1,lz1,1) r1, dimension (lx1,ly1,lz1,1) r2, dimension (lx1,ly1,lz1,1) r3, dimension(lx1,ly1,lz1,1) rmask1, dimension(lx1,ly1,lz1,1) rmask2, dimension(lx1,ly1,lz1,1) rmask3, dimension (lx1,ly1,lz1,1) rmult, dimension (lx1,ly1,lz1,1) binv, vol, tol, nel)
Definition at line 1289 of file subs1.f.
References add3(), add4(), glsc2(), glsc3(), glsum(), lelt, ly1, lz1, and opdot().
chktmg()
subroutine chktmg (tol, real, dimension (lx1,ly1,lz1,1) res, real, dimension (lx1,ly1,lz1,1) w1, real, dimension (lx1,ly1,lz1,1) w2, real, dimension (lx1,ly1,lz1,1) mult, real, dimension (lx1,ly1,lz1,1) mask, imesh)
Definition at line 391 of file subs1.f.
References col3(), copy(), dssum(), glsc3(), glsum(), ly1, lz1, and rone().
crs_strs()
subroutine crs_strs (real, dimension(1) u1, real, dimension(1) u2, real, dimension(1) u3, real, dimension(1) v1, real, dimension(1) v2, real, dimension(1) v3)
Definition at line 2005 of file subs1.f.
References dnekclock(), lelt, ly1, lz1, map_c_to_f_h1_bilin(), and map_f_to_c_h1_bilin().
cumax()
subroutine cumax (dimension(lx1,ly1,lz1,1) v1, dimension(lx1,ly1,lz1,1) v2, dimension(lx1,ly1,lz1,1) v3, umax)
Definition at line 677 of file subs1.f.
References col2(), glmax(), invcol2(), ly1, lz1, rzero3(), vdot2(), vdot3(), vlmax(), vsqrt(), and xyzrst().
cvgnlps()
subroutine cvgnlps (logical ifconv)
Definition at line 321 of file subs1.f.
References unorm().
ddrst()
subroutine ddrst (dimension (lx1,ly1,lz1) u, dimension(lx1,ly1,lz1) ur, dimension(lx1,ly1,lz1) us, dimension(lx1,ly1,lz1) ut)
Definition at line 1638 of file subs1.f.
References ly1, lz1, and mxm().
diagnos()
subroutine diagnos ()
Definition at line 1207 of file subs1.f.
faccl2()
subroutine faccl2 (dimension(lx1,ly1,lz1) a, dimension(lx1,ly1) b, iface1)
Definition at line 1022 of file subs1.f.
References dsset(), ly1, and lz1.
faccl3()
subroutine faccl3 (dimension(lx1,ly1,lz1) a, dimension(lx1,ly1,lz1) b, dimension(lx1,ly1) c, iface1)
Definition at line 1057 of file subs1.f.
References dsset(), ly1, and lz1.
facdot()
function facdot (dimension(lx1,ly1,lz1) A, dimension(lx1,ly1) B, IFACE1)
Definition at line 947 of file subs1.f.
References dsset(), ly1, and lz1.
faddcl3()
subroutine faddcl3 (dimension(lx1,ly1,lz1) a, dimension(lx1,ly1,lz1) b, dimension(lx1,ly1) c, iface1)
Definition at line 1091 of file subs1.f.
References dsset(), ly1, and lz1.
fcaver()
subroutine fcaver (xaver, real, dimension(lx1,ly1,lz1,1) a, iel, iface1)
Definition at line 983 of file subs1.f.
References dsset(), ly1, and lz1.
fcsum2()
subroutine fcsum2 (xsum, asum, real, dimension(lx1,ly1,lz1,1) x, integer e, integer f)
Definition at line 1694 of file subs1.f.
References dsset(), ly1, and lz1.
fdm_h1a()
subroutine fdm_h1a (real, dimension(lx1,ly1,lz1,1) z, real, dimension(lx1,ly1,lz1,1) r, real, dimension(lx1,ly1,lz1,1) d, nel, integer, dimension(lelt,3) kt, real, dimension(lx1,ly1,lz1,1) rr)
Definition at line 1772 of file subs1.f.
References col2(), col3(), copy(), dssum(), ly1, lz1, and mxm().
flush_io()
subroutine flush_io ()
Definition at line 1690 of file subs1.f.
get_local_crs_galerkin_strs()
subroutine get_local_crs_galerkin_strs (real, dimension(ldim,ncl,ldim,ncl,1) a, ncl, nxc, real, dimension(1) h1, real, dimension(1) h2, matmod)
Definition at line 1947 of file subs1.f.
References axstrs_nds(), copy(), gen_crs_basis(), lelt, ly1, lz1, opzero(), and vlsc2().
get_strs_mask()
subroutine get_strs_mask (real, dimension(ldim,nxc,nxc,nzc,nel) mask, nxc, nzc, nel)
Definition at line 1886 of file subs1.f.
hmhzsf()
subroutine hmhzsf (character name, real, dimension(1) u1, real, dimension(1) u2, real, dimension(1) u3, real, dimension(1) r1, real, dimension(1) r2, real, dimension(1) r3, real, dimension(1) h1, real, dimension(1) h2, real, dimension(1) rmask1, real, dimension(1) rmask2, real, dimension(1) rmask3, real, dimension(1) rmult, tol, maxit, matmod)
Definition at line 1225 of file subs1.f.
References cggosf(), chktcgs(), dnekclock(), ly1, lz1, opdssum(), rmask(), rzero3(), strs_project_a(), and strs_project_b().
nekuvp()
subroutine nekuvp (iel)
Definition at line 1182 of file subs1.f.
References ly1, lz1, and nekasgn().
opnorm2w()
function opnorm2w (real, dimension(1) v1, real, dimension(1) v2, real, dimension(1) v3, real, dimension(1) w)
Definition at line 2493 of file subs1.f.
References glsum(), ly1, lz1, and vlsc3().
set_up_h1_crs_strs()
subroutine set_up_h1_crs_strs (h1, h2, ifld, matmod)
Definition at line 2082 of file subs1.f.
References dnekclock(), exitti(), get_local_crs_galerkin_strs(), get_strs_mask(), get_vertex(), lelt, set_jl_crs_mask(), set_mat_ij(), and set_vert_strs().
set_vert_strs()
subroutine set_vert_strs (integer*8, dimension(1) glo_num, integer*8 ngv, integer nx, nel, integer, dimension(1) vertex, logical ifcenter)
Definition at line 1851 of file subs1.f.
References lelt, ly1, lz1, and set_vert().
setaxdy()
subroutine setaxdy (logical ifaxdy)
Definition at line 2475 of file subs1.f.
References copy(), and ly1.
setdt()
subroutine setdt ()
Definition at line 179 of file subs1.f.
References compute_cfl(), emerxit(), lelt, ly1, lz1, opsub3(), setdtc(), setdtfs(), and uglmin().
setdtc()
subroutine setdtc ()
Definition at line 460 of file subs1.f.
References bcdirvc(), cumax(), glmax(), glmin(), ly1, lz1, makeuf(), opcolv(), opdssum(), opsub3(), rzero(), and setprop().
setdtfs()
subroutine setdtfs (dtfs)
Definition at line 793 of file subs1.f.
References cdxmin2(), cdxmin3(), cfill(), faceis(), facexs(), glmin(), ly1, lz1, setprop(), vlmax(), and vlmin().
sethlm()
subroutine sethlm (real, dimension(1) h1, real, dimension(1) h2, intloc)
Definition at line 1127 of file subs1.f.
References cmult2(), copy(), ly1, lz1, and rzero().
setprop()
subroutine setprop ()
Definition at line 2751 of file subs1.f.
References dnekclock(), lelt, ly1, lz1, and vprops().
setsolv()
subroutine setsolv ()
Definition at line 1212 of file subs1.f.
References lelt.
stnrate()
subroutine stnrate (dimension(lx1,ly1,lz1,1) u1, dimension(lx1,ly1,lz1,1) u2, dimension(lx1,ly1,lz1,1) u3, nel, matmod)
Definition at line 1448 of file subs1.f.
References axiezz(), invcol2(), lelt, ly1, lz1, rzero3(), and uxyz().
stress()
subroutine stress (dimension(lx1,ly1,lz1,1) h1, dimension(lx1,ly1,lz1,1) h2, nel, matmod, logical ifaxis)
Definition at line 1494 of file subs1.f.
References add3s(), addcol3(), cmult2(), col2(), col3(), copy(), lelt, ly1, and lz1.
strs_ortho_all()
subroutine strs_ortho_all (real, dimension(n,ldim,k) x, real, dimension(n,ldim,k) b, n, k, real, dimension(n) h1, real, dimension(n) h2, real, dimension(n) wt, ifld, real, dimension(n,ldim) w, ierr, matmod)
Definition at line 2731 of file subs1.f.
References copy(), and strs_orthok().
strs_ortho_one()
subroutine strs_ortho_one (real, dimension(n,ldim,k) x, real, dimension(n,ldim,k) b, n, k, real, dimension(n) h1, real, dimension(n) h2, real, dimension(n) wt, ifld, real, dimension(n,ldim) w, ierr, matmod)
Definition at line 2711 of file subs1.f.
References copy(), and strs_orthok().
strs_orthok()
subroutine strs_orthok (real, dimension(n,ldim,k) x, real, dimension(n,ldim,k) b, n, k, real, dimension(n) h1, real, dimension(n) h2, real, dimension(n) wt, ifld, real, dimension(n,ldim) w, ierr, matmod)
Definition at line 2646 of file subs1.f.
References add2s2(), axhmsf(), cmult(), glsum(), op_glsc2_wt(), op_vlsc2_wt(), opdssum(), rmask(), and scale().
strs_project_a()
subroutine strs_project_a (real, dimension(1) b1, real, dimension(1) b2, real, dimension(1) b3, real, dimension(1) h1, real, dimension(1) h2, real, dimension(1) wt, ifld, ierr, matmod)
Definition at line 2510 of file subs1.f.
References col3(), copy(), difmax(), dnekclock(), lelt, ly1, lz1, op_glsc2_wt(), opadds(), opcopy(), opnorm2w(), opzero(), strs_ortho_all(), and strs_ortho_one().
strs_project_b()
subroutine strs_project_b (real, dimension(1) x1, real, dimension(1) x2, real, dimension(1) x3, real, dimension(1) h1, real, dimension(1) h2, real, dimension(1) wt, ifld, ierr)
Definition at line 2588 of file subs1.f.
References dnekclock(), lelt, ly1, lz1, opadd2(), and opcopy().
surf_mean()
function surf_mean (real, dimension(1) u, ifld, character*3 bc_in, ierr)
Definition at line 1736 of file subs1.f.
References fcsum2(), and glsum().
ttrst()
subroutine ttrst (dimension(lx1,ly1,lz1) ff, dimension(lx1,ly1,lz1) fr, dimension(lx1,ly1,lz1) fs, dimension(lx1,ly1,lz1) ft, dimension(lx1,ly1,lz1) ta)
Definition at line 2411 of file subs1.f.
References add2(), ly1, lz1, and mxm().
ttxyz()
subroutine ttxyz (dimension(lx1*ly1*lz1,1) ff, dimension(lx1,ly1,lz1,1) tx, dimension(lx1,ly1,lz1,1) ty, dimension(lx1,ly1,lz1,1) tz, nel)
Definition at line 2339 of file subs1.f.
References addcol3(), col2(), col3(), lelt, ly1, lz1, mxm(), setaxdy(), and ttrst().
unorm()
subroutine unorm ()
Definition at line 349 of file subs1.f.
References normsc(), and normvc().
urst()
subroutine urst (dimension (lx1,ly1,lz1,1) u, dimension(lx1,ly1,lz1,1) ur, dimension(lx1,ly1,lz1,1) us, dimension(lx1,ly1,lz1,1) ut, nel)
Definition at line 1619 of file subs1.f.
References ddrst(), ly1, lz1, and setaxdy().
uxyz()
subroutine uxyz (dimension (lx1,ly1,lz1,1) u, dimension(lx1,ly1,lz1,1) ex, dimension(lx1,ly1,lz1,1) ey, dimension(lx1,ly1,lz1,1) ez, nel)
Definition at line 1587 of file subs1.f.
References addcol3(), lelt, ly1, lz1, and urst().