KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/cmt/surface_fluxes.f File Reference
surface_fluxes.f File Reference
Routines for surface terms on RHS.
Functions/Subroutines
subroutine faceu (ivar, yourface)
subroutine fillq (ivar, field, wminus, yourface)
subroutine face_state_commo (mine, yours, nf, nstate, handle)
subroutine face_flux_commo (flux1, flux2, nf, neq, handle)
subroutine inviscidflux (wminus, wplus, flux, nstate, nflux)
subroutine surface_integral_full (vol, flux)
subroutine diffh2graduf (e, eq, graduf)
subroutine igu_cmt (flxscr, gdudxk, wminus)
subroutine igu_dirichlet (flux, agradu)
subroutine fluxes_full_field
Restrict and copy face data and compute inviscid numerical flux on face points.
Detailed Description
Routines for surface terms on RHS.
Definition in file surface_fluxes.f.
Function/Subroutine Documentation
subroutine diffh2graduf (integer e, integer eq, real, dimension(nx1*nz1*2*ndim,nelt,toteq) graduf)
Definition at line 366 of file surface_fluxes.f.
References addcol3(), col2(), copy(), full2face_cmt(), ly1, lz1, and rzero().
subroutine face_flux_commo (real, dimension(*) flux1, real, dimension(*) flux2, nf, neq, integer handle)
Definition at line 147 of file surface_fluxes.f.
subroutine face_state_commo (real, dimension(*) mine, real, dimension(*) yours, integer nf, integer nstate, integer handle)
Definition at line 120 of file surface_fluxes.f.
References copy(), and sub2().
subroutine faceu (ivar, real, dimension(nx1,nz1,2*ldim,nelt) yourface)
Definition at line 77 of file surface_fluxes.f.
References full2face_cmt().
subroutine fillq (integer ivar, real, dimension(nx1,ny1,nz1,nelt) field, real, dimension(nx1*nz1*2*ndim*nelt,*) wminus, real, dimension(nx1,nz1,2*ndim,*) yourface)
Definition at line 95 of file surface_fluxes.f.
References full2face_cmt(), and i.
subroutine igu_cmt (real, dimension(nx1*nz1*2*ndim*nelt,toteq) flxscr, real, dimension(nx1*nz1*2*ndim,nelt,toteq) gdudxk, real, dimension(nx1*nz1,2*ndim,nelt,nqq) wminus)
Definition at line 402 of file surface_fluxes.f.
References bcflux(), chsign(), cmult(), copy(), igu_dirichlet(), and sub2().
subroutine igu_dirichlet (real, dimension(nx1*nz1,2*ndim,nelt,toteq) flux, real, dimension(nx1*nz1,2*ndim,nelt,toteq) agradu)
Definition at line 444 of file surface_fluxes.f.
References cmult(), and copy().
subroutine inviscidflux (real, dimension(nx1*nz1,2*ndim,nelt,nstate) wminus, real, dimension(nx1*nz1,2*ndim,nelt,nstate) wplus, real, dimension(nx1*nz1,2*ndim,nelt,nflux) flux, integer nstate, integer nflux)
Definition at line 160 of file surface_fluxes.f.
References ausm_fluxfunction(), col2(), copy(), invcol3(), lz1, map_faced(), nx, nz, and rzero().
subroutine surface_integral_full (real, dimension(nx1*ny1*nz1*nelt) vol, real, dimension(*) flux)
Definition at line 344 of file surface_fluxes.f.
References add_face2full_cmt().