KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/genbox/genbox.f File Reference
genbox.f File Reference
Functions/Subroutines
program genbox
# #========================================================
comments
#
This is the set of box data for full spherical configuration
# #======================================================== # ps3.rea 3 NDIM 3 NFLDS box_1 (Any string with 1st character .ne. "c" or "C") -4 4 -4 (nelx,nely,nelz for Box) 0 1. (if nelx<0, length to be equally divided) 0 .25 .5 .75 1.0 (if nely>0, nely+1 y-values for start/stop of els) 0 1. P ,P ,P ,P ,P ,P (fluid bc's) P ,P ,P ,P ,P ,P (temp bc's) P ,P ,P ,P ,P ,P (passive scalar bc's) box_2 (Any string with 1st character .ne. "c" or "C") -4 4 -4 (nelx,nely,nelz for Box) 1 2. (if nelx<0, length to be equally divided) 0 .25 .5 .75 1.0 (if nely>0, nely+1 y-values for start/stop of els) 0 1. P ,P ,P ,P ,P ,P (fluid bc's) P ,P ,P ,P ,P ,P (temp bc's) P ,P ,P ,P ,P ,P (passive scalar bc's)
subroutine scanout (string, input, len, infile, outfile)
subroutine nekscan (string, input, len, infile)
subroutine blank (A, N)
function ltrunc (STRING, L)
integer function indx1 (S1, S2, L2)
subroutine ccopy (A, B, N)
subroutine rzero8 (A, N)
subroutine rzero (A, N)
function mod1 (I, N)
subroutine scannocom (iend, infile)
subroutine geti1 (i, iend, io)
subroutine geti2 (i1, i2, iend, io)
subroutine geti3 (i1, i2, i3, iend, io)
subroutine getr3 (r1, r2, r3, iend, io)
subroutine getr2 (r1, r2, iend, io)
subroutine getr1 (r1, iend, io)
subroutine getrv (r, n, iend, io)
subroutine getcv0 (c, m, n, iend, io)
subroutine getcv (c, m, n, iend, io)
subroutine gets (c, n, iend, io)
subroutine cfill (a, b, n)
subroutine icopy (a, b, n)
subroutine chcopy (a, b, n)
subroutine copy (a, b, n)
subroutine copy48 (a, b, n)
subroutine exitt
subroutine getiv (r, n, iend, io)
subroutine get_multi_seg (nelxyz, x, y, z, m, if3d)
subroutine geometric_x (x, n, x0, x1, gain)
subroutine overflow_chk (n_req, n_avail, var, sub)
subroutine cmult (x, a, n)
subroutine cadd (x, a, n)
subroutine get_xyz_distribution (x, nelx)
subroutine outmat6 (a, m, n, name6, ilabel)
subroutine cyl (if3d, ifflow, nfld, string, string1)
subroutine cyl_box (x, y, z, nels, cob, rad, tht, cbc, curve, ccurve, maxx, if3d, nfld)
subroutine get_cyl_box (xy0, nels, cob, rad, tht, z, cbc, maxx, if3d, nfld)
subroutine out_xy_box (x, y, z, nels, maxx, if3d)
subroutine out_curves (curve, ccurve, nel, if3d)
subroutine out_xy_curves (curve, ccurve, nels, if3d)
subroutine out_tens_bcs (cbc, nlx, nly, nlz, nbox, nfld, if3d, ifflow)
subroutine ifill (x, ic, n)
function ilsum (x, n)
subroutine set_logical (ifflow, ifheat, inf, outf, nlogic)
subroutine scanparam (str, str1, nparam, nfd, ifflw, ifht, ifmhd, infil, outfil)
Function/Subroutine Documentation
subroutine blank (character*1, dimension(1) A, N)
Definition at line 1519 of file genbox.f.
References n.
subroutine cadd (real, dimension(n) x, real a, n)
Definition at line 2013 of file genbox.f.
References n.
subroutine ccopy (character*1, dimension(1) A, character*1, dimension(1) B, N)
Definition at line 1562 of file genbox.f.
References n.
subroutine cfill (dimension(1) a, b, n)
Definition at line 1829 of file genbox.f.
References n.
subroutine chcopy (character*1, dimension(1) a, character*1, dimension(1) b, n)
Definition at line 1846 of file genbox.f.
References n.
subroutine cmult (real, dimension(n) x, real a, n)
Definition at line 2005 of file genbox.f.
References n.
subroutine copy (real, dimension(1) a, real, dimension(1) b, n)
Definition at line 1853 of file genbox.f.
References n.
subroutine copy48 (real*4, dimension(1) a, real*8, dimension(1) b, n)
Definition at line 1860 of file genbox.f.
References n.
subroutine cyl (logical if3d, logical ifflow, nfld, character*132 string, character*1, dimension(132) string1)
Definition at line 2070 of file genbox.f.
References cyl_box(), j, ltrunc(), nekscan(), out_tens_bcs(), out_xy_box(), out_xy_curves(), and scanout().
subroutine cyl_box (real, dimension(4,maxx*maxx) x, real, dimension(4,maxx*maxx) y, real, dimension(0:maxx) z, integer, dimension(3) nels, character*1, dimension(0:maxx) cob, real, dimension(0:maxx) rad, real, dimension(0:maxx) tht, character*3, dimension(6,nfld) cbc, real, dimension(5,8,maxx) curve, character*1, dimension(8,maxx) ccurve, maxx, logical if3d, nfld)
Definition at line 2122 of file genbox.f.
References blank(), cadd(), exitt(), get_cyl_box(), get_xyz_distribution(), j, n, and rzero().
subroutine exitt ()
Definition at line 1869 of file genbox.f.
References exit().
program genbox ()
# #========================================================
comments
#
This is the set of box data for full spherical configuration
# #======================================================== # ps3.rea 3 NDIM 3 NFLDS box_1 (Any string with 1st character .ne. "c" or "C") -4 4 -4 (nelx,nely,nelz for Box) 0 1. (if nelx<0, length to be equally divided) 0 .25 .5 .75 1.0 (if nely>0, nely+1 y-values for start/stop of els) 0 1. P ,P ,P ,P ,P ,P (fluid bc's) P ,P ,P ,P ,P ,P (temp bc's) P ,P ,P ,P ,P ,P (passive scalar bc's) box_2 (Any string with 1st character .ne. "c" or "C") -4 4 -4 (nelx,nely,nelz for Box) 1 2. (if nelx<0, length to be equally divided) 0 .25 .5 .75 1.0 (if nely>0, nely+1 y-values for start/stop of els) 0 1. P ,P ,P ,P ,P ,P (fluid bc's) P ,P ,P ,P ,P ,P (temp bc's) P ,P ,P ,P ,P ,P (passive scalar bc's)
Definition at line 67 of file genbox.f.
References blank(), byte_close, byte_open, byte_write, chcopy(), copy(), copy48(), cyl(), exitt(), get_multi_seg(), getcv(), geti1(), geti2(), geti3(), getr1(), getr2(), getr3(), getrv(), gets(), ia, icopy(), j, ltrunc(), mod1(), nekscan(), rzero(), rzero8(), scale(), scanout(), scanparam(), and set_logical().
subroutine geometric_x (real, dimension(0:n) x, n, x0, x1, gain)
Definition at line 1969 of file genbox.f.
References n, and scale().
subroutine get_cyl_box (real, dimension(2) xy0, integer, dimension(3) nels, character*1, dimension(0:maxx) cob, real, dimension(0:maxx) rad, real, dimension(0:maxx) tht, real, dimension(0:maxx) z, character*3, dimension(6,nfld) cbc, maxx, logical if3d, nfld)
Definition at line 2305 of file genbox.f.
References getcv(), getcv0(), geti2(), geti3(), getr2(), getrv(), and overflow_chk().
subroutine get_multi_seg (integer, dimension(3) nelxyz, real, dimension(0:m) x, real, dimension(0:m) y, real, dimension(0:m) z, m, logical if3d)
Definition at line 1906 of file genbox.f.
References exitt(), geometric_x(), geti1(), getiv(), getrv(), and ilsum().
subroutine get_xyz_distribution (real, dimension(0:2) x, nelx)
Definition at line 2021 of file genbox.f.
References cadd(), cmult(), exitt(), and scale().
subroutine getcv (character*1, dimension(m,n) c, m, n, iend, io)
Definition at line 1782 of file genbox.f.
References exitt(), n, and scannocom().
subroutine getcv0 (character*1, dimension(m,n) c, m, n, iend, io)
Definition at line 1753 of file genbox.f.
References j, n, and scannocom().
subroutine geti1 (i, iend, io)
Definition at line 1639 of file genbox.f.
References scannocom().
subroutine geti2 (i1, i2, iend, io)
Definition at line 1651 of file genbox.f.
References scannocom().
subroutine geti3 (i1, i2, i3, iend, io)
Definition at line 1663 of file genbox.f.
References scannocom().
subroutine getiv (integer, dimension(n) r, n, iend, io)
Definition at line 1876 of file genbox.f.
References ifill(), j, n, and scannocom().
subroutine getr1 (r1, iend, io)
Definition at line 1699 of file genbox.f.
References scannocom().
subroutine getr2 (r1, r2, iend, io)
Definition at line 1687 of file genbox.f.
References scannocom().
subroutine getr3 (r1, r2, r3, iend, io)
Definition at line 1675 of file genbox.f.
References scannocom().
subroutine getrv (real, dimension(n) r, n, iend, io)
Definition at line 1711 of file genbox.f.
References cfill(), n, and scannocom().
subroutine gets (character*1, dimension(n) c, n, iend, io)
Definition at line 1815 of file genbox.f.
References n, and scannocom().
subroutine icopy (integer, dimension(1) a, integer, dimension(1) b, n)
Definition at line 1839 of file genbox.f.
References n.
subroutine ifill (integer, dimension(1) x, ic, n)
Definition at line 2853 of file genbox.f.
References n.
function ilsum (integer, dimension(1) x, n)
Definition at line 2861 of file genbox.f.
References ilsum(), and n.
integer function indx1 (character*132 S1, character*132 S2, L2)
Definition at line 1544 of file genbox.f.
References indx1().
function ltrunc (character*1, dimension(l) STRING, L)
Definition at line 1530 of file genbox.f.
References ltrunc().
function mod1 (I, N)
Definition at line 1583 of file genbox.f.
References mod1(), and n.
subroutine nekscan (character*132 string, character*1, dimension(1) input, len, integer infile)
Definition at line 1500 of file genbox.f.
References blank(), and indx1().
subroutine out_curves (real, dimension(5,8,nel) curve, character*1, dimension(8,nel) ccurve, nel, logical if3d)
Definition at line 2458 of file genbox.f.
subroutine out_tens_bcs (character*3, dimension(6,nbox,nfld) cbc, integer, dimension(nbox) nlx, integer, dimension(nbox) nly, integer, dimension(nbox) nlz, nbox, nfld, logical if3d, logical ifflow)
Definition at line 2556 of file genbox.f.
References j, mod1(), rzero(), and rzero8().
subroutine out_xy_box (real, dimension(4,1) x, real, dimension(4,1) y, real, dimension(0:maxx) z, integer, dimension(3) nels, maxx, logical if3d)
Definition at line 2373 of file genbox.f.
References ia, and mod1().
subroutine out_xy_curves (real, dimension(5,8,1) curve, character*1, dimension(8,1) ccurve, integer, dimension(3) nels, logical if3d)
Definition at line 2501 of file genbox.f.
subroutine outmat6 (real, dimension(m,n) a, m, n, character*6 name6, ilabel)
Definition at line 2057 of file genbox.f.
References j, and n.
subroutine overflow_chk (n_req, n_avail, character*3 var, character*6 sub)
Definition at line 1988 of file genbox.f.
References exit().
subroutine rzero (dimension(1) A, N)
Definition at line 1576 of file genbox.f.
References n.
subroutine rzero8 (real*8, dimension(1) A, N)
Definition at line 1569 of file genbox.f.
References n.
subroutine scannocom (iend, infile)
Definition at line 1599 of file genbox.f.
References blank(), indx1(), and ltrunc().
subroutine scanout (character*132 string, character*1, dimension(1) input, integer len, integer infile, integer outfile)
Definition at line 1474 of file genbox.f.
References blank(), ccopy(), indx1(), j, and ltrunc().
subroutine scanparam (character*132 str, character*1, dimension(132) str1, nparam, nfd, logical ifflw, logical ifht, logical ifmhd, integer infil, integer outfil)
Definition at line 2938 of file genbox.f.
References blank(), ccopy(), j, and ltrunc().
subroutine set_logical (logical ifflow, logical ifheat, integer inf, integer outf, nlogic)
Definition at line 2870 of file genbox.f.
References blank(), ccopy(), indx1(), j, and ltrunc().