KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/nekmerge/byte.c File Reference
byte.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <float.h>
#include <math.h>
#include <time.h>
Macros
#define READ 1
#define WRITE 2
#define MAX_NAME 80
#define SWAP(a, b) temp=(a); (a)=(b); (b)=temp;
Functions
void byte_open_ (char *n)
void byte_close_ ()
void byte_rewind_ ()
void byte_write_ (float *buf, int *n)
void byte_read_ (float *buf, int *n)
void byte_reverse_ (float *buf, int *nn)
Macro Definition Documentation
#define MAX_NAME 80
Definition at line 55 of file byte.c.
#define READ 1
Definition at line 53 of file byte.c.
#define SWAP (a, b) temp=(a); (a)=(b); (b)=temp;
Definition at line 58 of file byte.c.
#define WRITE 2
Definition at line 54 of file byte.c.
Function Documentation
void byte_close_ ()
Definition at line 117 of file byte.c.
References byte_rewind(), and printf().
void byte_open_ (char * n)
Definition at line 84 of file byte.c.
References byte_close(), MAX_NAME, and printf().
void byte_read_ (float * buf, int * n)
Definition at line 239 of file byte.c.
References byte_reverse(), error_msg_fatal(), printf(), and READ.
void byte_reverse_ (float * buf, int * nn)
Definition at line 295 of file byte.c.
References exit(), FALSE, i, j, main(), n, printf(), ptr, SWAP, and TRUE.
void byte_rewind_ ()
Definition at line 154 of file byte.c.
References byte_write().
void byte_write_ (float * buf, int * n)
Definition at line 183 of file byte.c.
References byte_read(), error_msg_fatal(), printf(), and WRITE.