KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/coef.f File Reference
coef.f File Reference
Functions/Subroutines
subroutine coef
subroutine geom1 (ie)
subroutine setarea (ie)
subroutine area3 (area, unx, uny, unz, a, b, c, dot)
subroutine area2 (area, unx, uny, xrm1, xsm1, yrm1, ysm1, ie)
subroutine setwgtr (WGTR1, WGTR2, WGTR3, WGTR4, ie)
subroutine unitvec (X, Y, Z, N)
subroutine vdot3 (DOT, U1, U2, U3, V1, V2, V3, N)
Function/Subroutine Documentation
subroutine area2 (real, dimension(nx,4) area, real, dimension(ny,4) unx, real, dimension(ny,4) uny, real, dimension(nx,ny) xrm1, real, dimension(nx,ny) xsm1, real, dimension(ny,ny) yrm1, real, dimension(nx,ny) ysm1, ie)
Definition at line 315 of file coef.f.
References nx.
subroutine area3 (real, dimension(nx,ny,6) area, real, dimension (nx,ny,6) unx, real, dimension (nx,ny,6) uny, real, dimension (nx,ny,6) unz, real, dimension (nx,ny,nz) a, real, dimension (nx,ny,nz) b, real, dimension (nx,ny,nz) c, real, dimension(nx,ny,nz) dot)
Definition at line 230 of file coef.f.
References nx, nz, unitvec(), vcross(), and vdot3().
subroutine coef ()
Definition at line 3 of file coef.f.
References almax(), almin(), dermat(), dssum(), fcnnct(), genpn1(), geom1(), i, legend(), nx, and nz.
subroutine geom1 (ie)
Definition at line 90 of file coef.f.
References addcol4(), i, mxm(), nx, nz, rzero(), setarea(), and subcol4().
subroutine setarea (ie)
Definition at line 197 of file coef.f.
References area2(), area3(), dot(), nx, and nz.
subroutine setwgtr (real, dimension(nx) WGTR1, real, dimension(ny) WGTR2, real, dimension(nx) WGTR3, real, dimension(ny) WGTR4, ie)
Definition at line 380 of file coef.f.
References copy(), and nx.
subroutine unitvec (real, dimension(1) X, real, dimension(1) Y, real, dimension(1) Z, N)
Definition at line 419 of file coef.f.
References i, and n.
subroutine vdot3 (real, dimension(1) DOT, real, dimension(1) U1, real, dimension(1) U2, real, dimension(1) U3, real, dimension(1) V1, real, dimension(1) V2, real, dimension(1) V3, N)
Definition at line 432 of file coef.f.
References i, and n.