KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/blas.f File Reference
blas.f File Reference
Functions/Subroutines
real function sasum (n, sx, incx)
subroutine sscal (n, sa, sx, incx)
subroutine saxpy (n, sa, sx, incx, sy, incy)
real function sdot (n, sx, incx, sy, incy)
subroutine scopy (n, sx, incx, sy, incy)
integer function isamax (n, sx, incx)
subroutine sswap (n, sx, incx, sy, incy)
subroutine srot (n, sx, incx, sy, incy, c, s)
subroutine srotg (sa, sb, c, s)
real function snrm2 (n, sx, incx)
subroutine sgemv (trans, m, n, alpha, a, lda, x, incx, beta, y, incy)
subroutine xerbla (srname, info)
logical function lsame (CA, CB)
subroutine strsv (uplo, trans, diag, n, a, lda, x, incx)
real *8 function dasum (n, sx, incx)
subroutine dscal (n, sa, sx, incx)
subroutine daxpy (n, sa, sx, incx, sy, incy)
real *8 function ddot (n, sx, incx, sy, incy)
subroutine dcopy (n, sx, incx, sy, incy)
integer function idamax (n, sx, incx)
subroutine dswap (n, sx, incx, sy, incy)
subroutine drot (n, sx, incx, sy, incy, c, s)
subroutine drotg (sa, sb, c, s)
real *8 function dnrm2 (n, sx, incx)
subroutine dgemv (trans, m, n, alpha, a, lda, x, incx, beta, y, incy)
subroutine dtrsv (uplo, trans, diag, n, a, lda, x, incx)
Function/Subroutine Documentation
real*8 function dasum (integer n, real*8, dimension(1) sx, integer incx)
Definition at line 1209 of file blas.f.
References dasum().
subroutine daxpy (integer n, real*8 sa, real*8, dimension(1) sx, integer incx, real*8, dimension(1) sy, integer incy)
Definition at line 1294 of file blas.f.
subroutine dcopy (integer n, real*8, dimension(1) sx, integer incx, real*8, dimension(1) sy, integer incy)
Definition at line 1391 of file blas.f.
real*8 function ddot (integer n, real*8, dimension(1) sx, integer incx, real*8, dimension(1) sy, integer incy)
Definition at line 1342 of file blas.f.
References ddot().
subroutine dgemv (character*1 trans, integer m, integer n, real*8 alpha, real, dimension(lda, *) a, integer lda, real, dimension(*) x, integer incx, real*8 beta, real, dimension(*) y, integer incy)
Definition at line 1734 of file blas.f.
References xerbla().
real*8 function dnrm2 (integer n, real*8, dimension(1) sx, integer incx)
Definition at line 1604 of file blas.f.
References beta, and dnrm2().
subroutine drot (integer n, real*8, dimension(1) sx, integer incx, real*8, dimension(1) sy, integer incy, real*8 c, real*8 s)
Definition at line 1538 of file blas.f.
subroutine drotg (real*8 sa, real*8 sb, real*8 c, real*8 s)
Definition at line 1575 of file blas.f.
subroutine dscal (integer n, real*8 sa, real*8, dimension(1) sx, integer incx)
Definition at line 1252 of file blas.f.
subroutine dswap (integer n, real*8, dimension(1) sx, integer incx, real*8, dimension(1) sy, integer incy)
Definition at line 1476 of file blas.f.
References tmp.
subroutine dtrsv (character*1 uplo, character*1 trans, character*1 diag, integer n, real*8, dimension(lda, *) a, integer lda, real*8, dimension(*) x, integer incx)
Definition at line 1995 of file blas.f.
References xerbla().
integer function idamax (integer n, real*8, dimension(1) sx, integer incx)
Definition at line 1438 of file blas.f.
References idamax().
integer function isamax (integer n, real, dimension(1) sx, integer incx)
Definition at line 232 of file blas.f.
References isamax().
logical function lsame (character CA, character CB)
Definition at line 833 of file blas.f.
References lsame().
real function sasum (integer n, real, dimension(1) sx, integer incx)
Definition at line 3 of file blas.f.
References sasum().
subroutine saxpy (integer n, real sa, real, dimension(1) sx, integer incx, real, dimension(1) sy, integer incy)
Definition at line 88 of file blas.f.
subroutine scopy (integer n, real, dimension(1) sx, integer incx, real, dimension(1) sy, integer incy)
Definition at line 185 of file blas.f.
real function sdot (integer n, real, dimension(1) sx, integer incx, real, dimension(1) sy, integer incy)
Definition at line 136 of file blas.f.
References sdot().
subroutine sgemv (character*1 trans, integer m, integer n, real alpha, real, dimension(lda, *) a, integer lda, real, dimension(*) x, integer incx, real beta, real, dimension(*) y, integer incy)
Definition at line 526 of file blas.f.
References xerbla().
real function snrm2 (integer n, real, dimension(1) sx, integer incx)
Definition at line 396 of file blas.f.
References beta, and snrm2().
subroutine srot (integer n, real, dimension(1) sx, integer incx, real, dimension(1) sy, integer incy, real c, real s)
Definition at line 332 of file blas.f.
subroutine srotg (real sa, real sb, real c, real s)
Definition at line 369 of file blas.f.
subroutine sscal (integer n, real sa, real, dimension(1) sx, integer incx)
Definition at line 46 of file blas.f.
subroutine sswap (integer n, real, dimension(1) sx, integer incx, real, dimension(1) sy, integer incy)
Definition at line 270 of file blas.f.
References tmp.
subroutine strsv (character*1 uplo, character*1 trans, character*1 diag, integer n, real, dimension(lda, *) a, integer lda, real, dimension(*) x, integer incx)
Definition at line 919 of file blas.f.
References xerbla().
subroutine xerbla (character*6 srname, integer info)
Definition at line 787 of file blas.f.