KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/gs.c File Reference
gs.c File Reference
#include <stdio.h>
#include <strings.h>
#include <math.h>
#include <float.h>
#include <limits.h>
#include "const.h"
#include "types.h"
#include "comm.h"
#include "ivec.h"
#include "bss_malloc.h"
#include "bit_mask.h"
#include "error.h"
#include "queue.h"
#include "gs.h"
Data Structures
struct gather_scatter_id
Macros
#define TREE_BUF_SZ 2048;
#define GS_VEC_SZ 1
Typedefs
typedef struct gather_scatter_id gs_id
Functions
void flush_io_ (void)
void gs_init_vec_sz_ (int *size)
void gs_init_vec_sz (int size)
void gs_init_msg_buf_sz_ (int *buf_size)
void gs_init_msg_buf_sz (int buf_size)
int gs_init_ (int *elms, int *nel, int *level)
void gs_gop_ (int *gs, REAL *vals, char *op)
void gs_gop_vec_ (int *gs, REAL *vals, char *op, int *step)
void gs_free_ (int *gs)
gs_id * gs_init (register int *elms, int nel, int level)
void gs_gop_binary (gs_ADT gs, REAL *vals, rbfp fct)
void gs_gop (register gs_id *gs, register REAL *vals, register char *op)
void gs_free (register gs_id *gs)
void gs_gop_vec (register gs_id *gs, register REAL *vals, register char *op, register int step)
void gs_gop_hc_ (int *gs, REAL *vals, char *op, int *dim)
void gs_gop_hc (register gs_id *gs, register REAL *vals, register char *op, register int dim)
Macro Definition Documentation
#define GS_VEC_SZ 1
Definition at line 51 of file gs.c.
#define TREE_BUF_SZ 2048;
Definition at line 50 of file gs.c.
Typedef Documentation
typedef struct gather_scatter_id gs_id
Function Documentation
void flush_io_ (void)
Definition at line 276 of file gs.c.
void gs_free (register gs_id * gs)
Definition at line 4669 of file gs.c.
References bss_free(), gather_scatter_id::companion, gather_scatter_id::elms, error_msg_warning(), gather_scatter_id::gop_local_reduce, i, gather_scatter_id::in, gather_scatter_id::local_elms, gather_scatter_id::max_left_over, gather_scatter_id::msg_ids_in, gather_scatter_id::msg_ids_out, gather_scatter_id::msg_sizes, gather_scatter_id::ngh_buf, gather_scatter_id::nghs, gather_scatter_id::node_list, gather_scatter_id::num_gop_local_reduce, gather_scatter_id::num_local_total, gather_scatter_id::num_pairs, gather_scatter_id::out, gather_scatter_id::pair_list, perm_free(), gather_scatter_id::pw_elm_list, gather_scatter_id::pw_nghs, gather_scatter_id::pw_vals, gather_scatter_id::tree_buf, gather_scatter_id::tree_elms, gather_scatter_id::tree_map_in, gather_scatter_id::tree_map_out, gather_scatter_id::tree_work, and gather_scatter_id::vals.
void gs_free_ (int * gs)
Definition at line 458 of file gs.c.
References gs_free().
void gs_gop (register gs_id * gs, register REAL * vals, register char * op)
Definition at line 1973 of file gs.c.
References gather_scatter_id::avg_node_pairs, dcopy(), error_msg_fatal(), error_msg_warning(), gather_scatter_id::gl_bss_min, gather_scatter_id::gl_max, gather_scatter_id::gl_min, gather_scatter_id::gl_perm_min, gather_scatter_id::gop_local_reduce, grop(), gather_scatter_id::id, gather_scatter_id::in, irecv(), isend(), j, gather_scatter_id::len_pw_list, gather_scatter_id::level, list, gather_scatter_id::loc_node_pairs, gather_scatter_id::local_reduce, MAX, gather_scatter_id::max_left_over, gather_scatter_id::max_nghs, gather_scatter_id::max_node_pairs, gather_scatter_id::max_pairs, MIN, gather_scatter_id::min_node_pairs, gather_scatter_id::msg_ids_in, gather_scatter_id::msg_ids_out, gather_scatter_id::msg_sizes, msgwait(), my_id, gather_scatter_id::negl, gather_scatter_id::nel, gather_scatter_id::nel_max, gather_scatter_id::nel_min, gather_scatter_id::nel_sum, gather_scatter_id::node_list, gather_scatter_id::num_gop_local_reduce, gather_scatter_id::num_local, gather_scatter_id::num_local_gop, gather_scatter_id::num_local_reduce, gather_scatter_id::num_nghs, num_nodes, gather_scatter_id::num_pairs, gather_scatter_id::ordered, gather_scatter_id::out, gather_scatter_id::pair_list, gather_scatter_id::positive, printf(), gather_scatter_id::pw_elm_list, gather_scatter_id::pw_vals, gather_scatter_id::repeats, rvec_one(), rvec_set(), rvec_zero(), scopy(), tmp, gather_scatter_id::tree_buf, gather_scatter_id::tree_map_in, gather_scatter_id::tree_map_out, gather_scatter_id::tree_nel, and gather_scatter_id::tree_work.
void gs_gop_ (int * gs, REAL * vals, char * op)
Definition at line 402 of file gs.c.
References gs_gop().
void gs_gop_binary (gs_ADT gs, REAL * vals, rbfp fct)
Definition at line 1632 of file gs.c.
References error_msg_fatal(), error_msg_warning(), gop(), gather_scatter_id::gop_local_reduce, gather_scatter_id::in, irecv(), isend(), list, gather_scatter_id::local_reduce, gather_scatter_id::max_left_over, gather_scatter_id::msg_ids_in, gather_scatter_id::msg_ids_out, gather_scatter_id::msg_sizes, msgwait(), my_id, gather_scatter_id::node_list, gather_scatter_id::num_gop_local_reduce, gather_scatter_id::num_local_reduce, gather_scatter_id::out, gather_scatter_id::pair_list, gather_scatter_id::pw_elm_list, gather_scatter_id::pw_vals, tmp, gather_scatter_id::tree_buf, gather_scatter_id::tree_map_in, gather_scatter_id::tree_map_out, gather_scatter_id::tree_nel, and gather_scatter_id::tree_work.
void gs_gop_hc (register gs_id * gs, register REAL * vals, register char * op, register int dim)
Definition at line 5415 of file gs.c.
References dcopy(), error_msg_fatal(), error_msg_warning(), grop_hc(), i, i_log2_num_nodes, gather_scatter_id::in, irecv(), isend(), list, gather_scatter_id::max_left_over, MIN, gather_scatter_id::msg_ids_in, gather_scatter_id::msg_ids_out, gather_scatter_id::msg_sizes, msgwait(), my_id, gather_scatter_id::node_list, gather_scatter_id::num_local, gather_scatter_id::num_local_gop, gather_scatter_id::num_pairs, gather_scatter_id::out, gather_scatter_id::pair_list, gather_scatter_id::pw_elm_list, gather_scatter_id::pw_vals, rvec_zero(), scopy(), gather_scatter_id::tree_buf, gather_scatter_id::tree_map_in, gather_scatter_id::tree_map_out, gather_scatter_id::tree_nel, and gather_scatter_id::tree_work.
void gs_gop_hc_ (int * gs, REAL * vals, char * op, int * dim)
Definition at line 5394 of file gs.c.
References gs_gop_hc().
void gs_gop_vec (register gs_id * gs, register REAL * vals, register char * op, register int step)
Definition at line 4782 of file gs.c.
References daxpy(), dcopy(), error_msg_fatal(), error_msg_warning(), gather_scatter_id::gop_local_reduce, grop(), i, gather_scatter_id::in, irecv(), isend(), list, gather_scatter_id::local_reduce, gather_scatter_id::max_left_over, gather_scatter_id::msg_ids_in, gather_scatter_id::msg_ids_out, gather_scatter_id::msg_sizes, msgwait(), my_id, gather_scatter_id::node_list, gather_scatter_id::num_gop_local_reduce, gather_scatter_id::num_local, gather_scatter_id::num_local_gop, gather_scatter_id::num_local_reduce, gather_scatter_id::num_pairs, gather_scatter_id::out, gather_scatter_id::pair_list, gather_scatter_id::pw_elm_list, gather_scatter_id::pw_vals, rvec_add(), rvec_copy(), rvec_zero(), saxpy(), scopy(), gather_scatter_id::tree_buf, gather_scatter_id::tree_map_in, gather_scatter_id::tree_map_out, gather_scatter_id::tree_nel, and gather_scatter_id::tree_work.
void gs_gop_vec_ (int * gs, REAL * vals, char * op, int * step)
Definition at line 430 of file gs.c.
References gs_gop_vec().
gs_id* gs_init (register int * elms, int nel, int level)
Definition at line 483 of file gs.c.
References gather_scatter_id::avg_node_pairs, bm_to_proc(), bss_free(), bss_init(), bss_malloc(), bss_stats(), comm_init(), gather_scatter_id::companion, ct_bits(), gather_scatter_id::elms, error_msg_fatal(), error_msg_warning(), floor_num_nodes, giop(), gather_scatter_id::gl_max, gather_scatter_id::gl_min, gather_scatter_id::gop_local_reduce, gs(), i, i_log2_num_nodes, gather_scatter_id::id, gather_scatter_id::in, ivec_and3(), ivec_binary_search(), ivec_copy(), ivec_or(), ivec_reduce_and(), ivec_reduce_or(), ivec_sum(), ivec_xor(), ivec_zero(), j, len_bit_mask(), gather_scatter_id::len_pw_list, gather_scatter_id::level, gather_scatter_id::loc_node_pairs, gather_scatter_id::local_elms, gather_scatter_id::local_reduce, gather_scatter_id::local_strength, gather_scatter_id::mask_sz, MAX, gather_scatter_id::max_left_over, gather_scatter_id::max_nghs, gather_scatter_id::max_node_pairs, gather_scatter_id::max_pairs, MIN, gather_scatter_id::min_node_pairs, gather_scatter_id::msg_ids_in, gather_scatter_id::msg_ids_out, gather_scatter_id::msg_sizes, gather_scatter_id::msg_total, my_id, n, gather_scatter_id::negl, nekgsync(), gather_scatter_id::nel, gather_scatter_id::nel_max, gather_scatter_id::nel_min, gather_scatter_id::nel_sum, gather_scatter_id::nel_total, gather_scatter_id::ngh_buf, gather_scatter_id::ngh_buf_sz, gather_scatter_id::nghs, gather_scatter_id::node_list, gather_scatter_id::num_gop_local_reduce, gather_scatter_id::num_loads, gather_scatter_id::num_local, gather_scatter_id::num_local_gop, gather_scatter_id::num_local_reduce, gather_scatter_id::num_local_total, gather_scatter_id::num_nghs, num_nodes, gather_scatter_id::num_pairs, gather_scatter_id::num_pw_nghs, gather_scatter_id::ordered, gather_scatter_id::out, gather_scatter_id::pair_list, perm_init(), perm_malloc(), perm_stats(), gather_scatter_id::positive, printf(), gather_scatter_id::pw_elm_list, gather_scatter_id::pw_nghs, gather_scatter_id::pw_vals, gather_scatter_id::repeats, rvec_zero(), set_bit_mask(), SMI_sort(), tmp, gather_scatter_id::tree_buf, TREE_BUF_SZ, gather_scatter_id::tree_elms, gather_scatter_id::tree_map_in, gather_scatter_id::tree_map_out, gather_scatter_id::tree_map_sz, gather_scatter_id::tree_nel, gather_scatter_id::tree_work, and TRUE.
int gs_init_ (int * elms, int * nel, int * level)
Definition at line 371 of file gs.c.
References error_msg_fatal(), gs(), gs_init(), gather_scatter_id::id, and gather_scatter_id::vals.
void gs_init_msg_buf_sz (int buf_size)
Definition at line 349 of file gs.c.
References gather_scatter_id::elms, gather_scatter_id::level, gather_scatter_id::nel, and TRUE.
void gs_init_msg_buf_sz_ (int * buf_size)
Definition at line 335 of file gs.c.
References gs_init_msg_buf_sz().
void gs_init_vec_sz (int size)
Definition at line 315 of file gs.c.
References TRUE.
void gs_init_vec_sz_ (int * size)
Definition at line 299 of file gs.c.
References gs_init_vec_sz().