KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/reatore2/byte.c File Reference
byte.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <float.h>
#include <math.h>
#include <time.h>
#include <sys/stat.h>
#include <sys/types.h>
Macros
#define FNAME_H
#define FORTRAN_NAME(low, up) low
#define byte_reverse FORTRAN_NAME(byte_reverse, BYTE_REVERSE)
#define byte_open FORTRAN_NAME(byte_open, BYTE_OPEN)
#define byte_close FORTRAN_NAME(byte_close, BYTE_CLOSE)
#define byte_rewind FORTRAN_NAME(byte_rewind, BYTE_REWIND)
#define byte_read FORTRAN_NAME(byte_read, BYTE_READ)
#define byte_write FORTRAN_NAME(byte_write, BYTE_WRITE)
#define set_bytesw_write FORTRAN_NAME(set_bytesw_write,SET_BYTESW_WRITE)
#define set_bytesw_read FORTRAN_NAME(set_bytesw_read ,SET_BYTESW_READ)
#define get_bytesw_write FORTRAN_NAME(get_bytesw_write,GET_BYTESW_WRITE)
#define get_bytesw_read FORTRAN_NAME(get_bytesw_read ,GET_BYTESW_READ)
#define READ 1
#define WRITE 2
#define MAX_NAME 132
#define SWAP(a, b) temp=(a); (a)=(b); (b)=temp;
Functions
void exitt ()
void cexitt ()
void byte_reverse (float *buf, int *nn)
void byte_open (char *n)
void byte_close ()
void byte_rewind ()
void byte_write (float *buf, int *n)
void byte_read (float *buf, int *n)
void set_bytesw_write (int *pa)
void set_bytesw_read (int *pa)
void get_bytesw_write (int *pa)
void get_bytesw_read (int *pa)
Variables
int bytesw_write =0
int bytesw_read =0
Macro Definition Documentation
#define byte_close FORTRAN_NAME(byte_close, BYTE_CLOSE)
Definition at line 35 of file byte.c.
#define byte_open FORTRAN_NAME(byte_open, BYTE_OPEN)
Definition at line 34 of file byte.c.
#define byte_read FORTRAN_NAME(byte_read, BYTE_READ)
Definition at line 37 of file byte.c.
#define byte_reverse FORTRAN_NAME(byte_reverse, BYTE_REVERSE)
Definition at line 33 of file byte.c.
#define byte_rewind FORTRAN_NAME(byte_rewind, BYTE_REWIND)
Definition at line 36 of file byte.c.
#define byte_write FORTRAN_NAME(byte_write, BYTE_WRITE)
Definition at line 38 of file byte.c.
#define FNAME_H
Definition at line 12 of file byte.c.
#define FORTRAN_NAME (low, up) low
Definition at line 27 of file byte.c.
#define get_bytesw_read FORTRAN_NAME(get_bytesw_read ,GET_BYTESW_READ)
Definition at line 42 of file byte.c.
#define get_bytesw_write FORTRAN_NAME(get_bytesw_write,GET_BYTESW_WRITE)
Definition at line 41 of file byte.c.
#define MAX_NAME 132
Definition at line 46 of file byte.c.
#define READ 1
Definition at line 44 of file byte.c.
#define set_bytesw_read FORTRAN_NAME(set_bytesw_read ,SET_BYTESW_READ)
Definition at line 40 of file byte.c.
#define set_bytesw_write FORTRAN_NAME(set_bytesw_write,SET_BYTESW_WRITE)
Definition at line 39 of file byte.c.
#define SWAP (a, b) temp=(a); (a)=(b); (b)=temp;
Definition at line 48 of file byte.c.
#define WRITE 2
Definition at line 45 of file byte.c.
Function Documentation
void byte_close ()
Definition at line 127 of file byte.c.
References cexitt(), and printf().
void byte_open (char * n)
Definition at line 93 of file byte.c.
References cexitt(), i, MAX_NAME, and printf().
void byte_read (float * buf, int * n)
Definition at line 183 of file byte.c.
References byte_reverse, bytesw_read, cexitt(), printf(), and READ.
void byte_reverse (float * buf, int * nn)
Definition at line 74 of file byte.c.
References cexitt(), n, printf(), ptr, and SWAP.
void byte_rewind ()
Definition at line 140 of file byte.c.
void byte_write (float * buf, int * n)
Definition at line 148 of file byte.c.
References byte_reverse, bytesw_write, cexitt(), printf(), and WRITE.
void cexitt ()
Definition at line 65 of file byte.c.
References exitt().
void exitt ()
Definition at line 521 of file comm_mpi.f.
References close_files(), dnekclock(), exit(), exit_(), flush_io(), happy_check(), mpi_finalize(), nek_flops(), nekgsync(), nx, nz, and print_stack.
void get_bytesw_read (int * pa)
Definition at line 246 of file byte.c.
References bytesw_read.
void get_bytesw_write (int * pa)
Definition at line 241 of file byte.c.
References bytesw_write.
void set_bytesw_read (int * pa)
Definition at line 233 of file byte.c.
References bytesw_read.
void set_bytesw_write (int * pa)
Definition at line 225 of file byte.c.
References bytesw_write.
Variable Documentation
int bytesw_read =0
Definition at line 55 of file byte.c.
int bytesw_write =0
Definition at line 54 of file byte.c.