KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/speclib.f File Reference
speclib.f File Reference
Functions/Subroutines
subroutine zwgl (Z, W, NP)
subroutine zwgll (Z, W, NP)
subroutine zwgj (Z, W, NP, ALPHA, BETA)
subroutine zwgjd (Z, W, NP, ALPHA, BETA)
subroutine zwglj (Z, W, NP, ALPHA, BETA)
subroutine zwgljd (Z, W, NP, ALPHA, BETA)
real *8 function endw1 (N, ALPHA, BETA)
real *8 function endw2 (N, ALPHA, BETA)
real *8 function gammaf (X)
real *8 function pnormj (N, ALPHA, BETA)
subroutine jacg (XJAC, NP, ALPHA, BETA)
subroutine jacobf (POLY, PDER, POLYM1, PDERM1, POLYM2, PDERM2, N, ALP, BET, X)
real function hgj (II, Z, ZGJ, NP, ALPHA, BETA)
real *8 function hgjd (II, Z, ZGJ, NP, ALPHA, BETA)
real function hglj (II, Z, ZGLJ, NP, ALPHA, BETA)
real *8 function hgljd (I, Z, ZGLJ, NP, ALPHA, BETA)
subroutine dgj (D, DT, Z, NZ, NZD, ALPHA, BETA)
subroutine dgjd (D, DT, Z, NZ, NZD, ALPHA, BETA)
subroutine dglj (D, DT, Z, NZ, NZD, ALPHA, BETA)
subroutine dgljd (D, DT, Z, NZ, NZD, ALPHA, BETA)
subroutine dgll (D, DT, Z, NZ, NZD)
real function hgll (I, Z, ZGLL, NZ)
real function hgl (I, Z, ZGL, NZ)
real function pnleg (Z, N)
real function pndleg (Z, N)
subroutine dgllgl (D, DT, ZM1, ZM2, IM12, NZM1, NZM2, ND1, ND2)
subroutine dgljgj (D, DT, ZGL, ZG, IGLG, NPGL, NPG, ND1, ND2, ALPHA, BETA)
subroutine dgljgjd (D, DT, ZGL, ZG, IGLG, NPGL, NPG, ND1, ND2, ALPHA, BETA)
subroutine iglm (I12, IT12, Z1, Z2, NZ1, NZ2, ND1, ND2)
subroutine igllm (I12, IT12, Z1, Z2, NZ1, NZ2, ND1, ND2)
subroutine igjm (I12, IT12, Z1, Z2, NZ1, NZ2, ND1, ND2, ALPHA, BETA)
subroutine igljm (I12, IT12, Z1, Z2, NZ1, NZ2, ND1, ND2, ALPHA, BETA)
Function/Subroutine Documentation
subroutine dgj (real, dimension(nzd,nzd) D, real, dimension(nzd,nzd) DT, real, dimension(1) Z, NZ, NZD, real ALPHA, real BETA)
Definition at line 635 of file speclib.f.
References dgjd(), i, j, and nz.
subroutine dgjd (real*8, dimension(nzd,nzd) D, real*8, dimension(nzd,nzd) DT, real*8, dimension(1) Z, NZ, NZD, real*8 ALPHA, real*8 BETA)
Definition at line 679 of file speclib.f.
References i, j, jacobf(), n, and nz.
subroutine dglj (real, dimension(nzd,nzd) D, real, dimension(nzd,nzd) DT, real, dimension(1) Z, NZ, NZD, real ALPHA, real BETA)
Definition at line 717 of file speclib.f.
References dgljd(), i, j, and nz.
subroutine dgljd (real*8, dimension(nzd,nzd) D, real*8, dimension(nzd,nzd) DT, real*8, dimension(1) Z, NZ, NZD, real*8 ALPHA, real*8 BETA)
Definition at line 761 of file speclib.f.
References i, j, jacobf(), n, and nz.
subroutine dgljgj (real, dimension(nd2,nd1) D, real, dimension(nd1,nd2) DT, real, dimension(nd1) ZGL, real, dimension(nd2) ZG, real, dimension(nd2,nd1) IGLG, NPGL, NPG, ND1, ND2, ALPHA, BETA)
Definition at line 976 of file speclib.f.
References alpha, beta, dgljgjd(), i, and j.
subroutine dgljgjd (real*8, dimension(nd2,nd1) D, real*8, dimension(nd1,nd2) DT, real*8, dimension(nd1) ZGL, real*8, dimension(nd2) ZG, real*8, dimension(nd2,nd1) IGLG, NPGL, NPG, ND1, ND2, real*8 ALPHA, real*8 BETA)
Definition at line 1030 of file speclib.f.
References i, j, and jacobf().
subroutine dgll (real, dimension(nzd,nzd) D, real, dimension(nzd,nzd) DT, real, dimension(1) Z, NZ, NZD)
Definition at line 807 of file speclib.f.
References i, j, n, nz, and pnleg().
subroutine dgllgl (real, dimension(nd2,nd1) D, real, dimension(nd1,nd2) DT, real, dimension(nd1) ZM1, real, dimension(nd2) ZM2, real, dimension(nd2,nd1) IM12, NZM1, NZM2, ND1, ND2)
Definition at line 941 of file speclib.f.
References pnleg().
real*8 function endw1 (N, real*8 ALPHA, real*8 BETA)
Definition at line 286 of file speclib.f.
References alpha, beta, gammaf(), i, and n.
real*8 function endw2 (N, real*8 ALPHA, real*8 BETA)
Definition at line 330 of file speclib.f.
References alpha, beta, gammaf(), i, and n.
real*8 function gammaf (real*8 X)
Definition at line 374 of file speclib.f.
References gammaf().
real function hgj (II, real Z, real, dimension(1) ZGJ, NP, real ALPHA, real BETA)
Definition at line 523 of file speclib.f.
References hgj(), hgjd(), and i.
real*8 function hgjd (II, real*8 Z, real*8, dimension(1) ZGJ, NP, real*8 ALPHA, real*8 BETA)
Definition at line 553 of file speclib.f.
References hgjd(), and jacobf().
real function hgl (I, Z, real, dimension(1) ZGL, NZ)
Definition at line 863 of file speclib.f.
References hgl(), i, n, nz, pndleg(), and pnleg().
real function hglj (II, real Z, real, dimension(1) ZGLJ, NP, real ALPHA, real BETA)
Definition at line 577 of file speclib.f.
References hglj(), hgljd(), and i.
real*8 function hgljd (I, real*8 Z, real*8, dimension(1) ZGLJ, NP, real*8 ALPHA, real*8 BETA)
Definition at line 607 of file speclib.f.
References hgljd(), i, jacobf(), and n.
real function hgll (I, Z, real, dimension(1) ZGLL, NZ)
Definition at line 842 of file speclib.f.
References hgll(), i, n, nz, pndleg(), and pnleg().
subroutine igjm (real, dimension(nd2,nd1) I12, real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, NZ1, NZ2, ND1, ND2, ALPHA, BETA)
Definition at line 1133 of file speclib.f.
References alpha, beta, hgj(), i, and j.
subroutine igljm (real, dimension(nd2,nd1) I12, real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, NZ1, NZ2, ND1, ND2, ALPHA, BETA)
Definition at line 1159 of file speclib.f.
References alpha, beta, hglj(), i, and j.
subroutine igllm (real, dimension(nd2,nd1) I12, real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, NZ1, NZ2, ND1, ND2)
Definition at line 1108 of file speclib.f.
References hgll(), i, and j.
subroutine iglm (real, dimension(nd2,nd1) I12, real, dimension(nd1,nd2) IT12, real, dimension(nd1) Z1, real, dimension(nd2) Z2, NZ1, NZ2, ND1, ND2)
Definition at line 1083 of file speclib.f.
References hgl(), i, and j.
subroutine jacg (real*8, dimension(1) XJAC, NP, ALPHA, BETA)
Definition at line 424 of file speclib.f.
References alpha, beta, i, j, jacobf(), n, and swap().
subroutine jacobf (POLY, PDER, POLYM1, PDERM1, POLYM2, PDERM2, N, ALP, BET, X)
Definition at line 483 of file speclib.f.
References n.
real function pndleg (Z, N)
Definition at line 914 of file speclib.f.
References n, and pndleg().
real function pnleg (Z, N)
Definition at line 882 of file speclib.f.
References n, and pnleg().
real*8 function pnormj (N, real*8 ALPHA, real*8 BETA)
Definition at line 398 of file speclib.f.
References gammaf(), i, n, and pnormj().
subroutine zwgj (real, dimension(1) Z, real, dimension(1) W, NP, real ALPHA, real BETA)
Definition at line 126 of file speclib.f.
References i, and zwgjd().
subroutine zwgjd (real*8, dimension(1) Z, real*8, dimension(1) W, NP, real*8 ALPHA, real*8 BETA)
Definition at line 158 of file speclib.f.
References gammaf(), i, jacg(), jacobf(), n, and pnormj().
subroutine zwgl (real, dimension(1) Z, real, dimension(1) W, NP)
Definition at line 92 of file speclib.f.
References alpha, beta, and zwgj().
subroutine zwglj (real, dimension(1) Z, real, dimension(1) W, NP, real ALPHA, real BETA)
Definition at line 210 of file speclib.f.
References i, and zwgljd().
subroutine zwgljd (real*8, dimension(np) Z, real*8, dimension(np) W, NP, real*8 ALPHA, real*8 BETA)
Definition at line 242 of file speclib.f.
References endw1(), endw2(), i, jacobf(), n, and zwgjd().
subroutine zwgll (real, dimension(1) Z, real, dimension(1) W, NP)
Definition at line 109 of file speclib.f.
References alpha, beta, and zwglj().