KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/vprops.f File Reference
vprops.f File Reference
Functions/Subroutines
subroutine vprops
Function/Subroutine Documentation
subroutine vprops ()
Definition at line 18 of file vprops.f.
References copyel(), drawel(), drelev(), drgrid(), drmenu(), i, if(), menu(), mouse(), prs(), prsi(), prsis(), prsr(), refresh(), rer(), res(), rmin(), and setzoom().