KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/coef.f File Reference
coef.f File Reference
Functions/Subroutines
subroutine jacobian
Function/Subroutine Documentation
subroutine jacobian ()
Definition at line 2 of file coef.f.
References addcol3(), addcol4(), chkjac(), copy(), dgll(), mxm(), rzero(), subcol3(), subcol4(), and zwgll().