KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/genxyz.f File Reference
genxyz.f File Reference
Functions/Subroutines
subroutine genxyz (xml, yml, zml, ie, nxl, nyl, nzl)
subroutine sphsrf (xml, yml, zml, ifce, ie, mx, my, mz, xysrf)
subroutine edg3d (xysrf, x1, x2, i1, i2, j1, j2, mx, my)
real function dot (V1, V2, N)
subroutine crn3d (xcv, xc, yc, zc, curve, iface, IE)
subroutine dsset (mx, my, mz)
subroutine rone (x, n)
subroutine gensrf (XML, YML, ZML, IFCE, IE, MX, MY, MZ, zgml)
subroutine prjects (x0, dxc, c, cc)
subroutine srfind (x1, x0, c, cc)
function ressrf (x, c, cc)
subroutine arcsrf (xml, yml, zml, nxl, nyl, nzl, ie, isid)
subroutine addtnsr (s, h1, h2, h3, nx, ny, nz)
Function/Subroutine Documentation
subroutine addtnsr (dimension(nx,ny,nz) s, dimension(1) h1, dimension(1) h2, dimension(1) h3, nx, ny, nz)
Definition at line 814 of file genxyz.f.
References nx, and nz.
subroutine arcsrf (dimension(nxl,nyl,nzl,1) xml, dimension(nxl,nyl,nzl,1) yml, dimension(nxl,nyl,nzl,1) zml, nxl, nyl, nzl, ie, isid)
Definition at line 710 of file genxyz.f.
References addtnsr(), exitt(), ly1, lz1, and mod1().
subroutine crn3d (dimension(3,2,2) xcv, dimension(8) xc, dimension(8) yc, dimension(8) zc, dimension(4) curve, iface, IE)
Definition at line 367 of file genxyz.f.
References j, and test().
real function dot (dimension(n) V1, dimension(n) V2, N)
Definition at line 353 of file genxyz.f.
References dot(), and n.
subroutine dsset (mx, my, mz)
Definition at line 422 of file genxyz.f.
subroutine edg3d (dimension(3,mx,my) xysrf, dimension(3) x1, dimension(3) x2, i1, i2, j1, j2, mx, my)
Definition at line 310 of file genxyz.f.
References copy(), cross(), dot(), j, ly1, lz1, and norm3d().
subroutine gensrf (dimension(mx,my,mz,1) XML, dimension(mx,my,mz,1) YML, dimension(mx,my,mz,1) ZML, IFCE, IE, MX, MY, MZ, dimension(lx1,3) zgml)
Definition at line 505 of file genxyz.f.
References dsset(), j, ly1, lz1, prjects(), and rmin().
subroutine genxyz (dimension(nxl,nyl,nzl,1) xml, dimension(nxl,nyl,nzl,1) yml, dimension(nxl,nyl,nzl,1) zml, ie, nxl, nyl, nzl)
Definition at line 3 of file genxyz.f.
References arcsrf(), gensrf(), legend(), ly1, lz1, nx, rone(), rzero(), and sphsrf().
subroutine prjects (real, dimension(3) x0, dxc, real, dimension(5) c, character*1 cc)
Definition at line 594 of file genxyz.f.
References alpha, copy(), ressrf(), and srfind().
function ressrf (real, dimension(3) x, real, dimension(5) c, character*1 cc)
Definition at line 694 of file genxyz.f.
References ressrf().
subroutine rone (dimension(1) x, n)
Definition at line 497 of file genxyz.f.
References n.
subroutine sphsrf (dimension(mx,my,mz,1) xml, dimension(mx,my,mz,1) yml, dimension(mx,my,mz,1) zml, ifce, ie, mx, my, mz, dimension(3,mx,mz) xysrf)
Definition at line 116 of file genxyz.f.
References cmult(), crn3d(), cross(), dot(), dsset(), edg3d(), j, ly1, lz1, mxm1(), norm3d(), rone(), and tmp.
subroutine srfind (real, dimension(3) x1, real, dimension(3) x0, real, dimension(5) c, character*1 cc)
Definition at line 658 of file genxyz.f.
References ressrf().