KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/comm.c File Reference
comm.c File Reference
#include <stdio.h>
#include "const.h"
#include "types.h"
#include "error.h"
#include "ivec.h"
#include "bss_malloc.h"
#include "comm.h"
Functions
void comm_init_ (void)
void comm_init (void)
void comm_terminate (void)
void giop_ (int *vals, int *work, int *n, int *oprs)
void giop (int *vals, int *work, int n, int *oprs)
void grop_ (REAL *vals, REAL *work, int *n, int *oprs)
void grop (REAL *vals, REAL *work, int n, int *oprs)
void grop_hc_ (REAL *vals, REAL *work, int *n, int *oprs, int *dim)
void grop_hc (REAL *vals, REAL *work, int n, int *oprs, int dim)
void grop_hc_vvl_ (REAL *vals, REAL *work, int *len_vec, int *oprs, int *dim)
void gop (void *vals, void *work, int n, vbfp fp, DATA_TYPE dt, int comm_type)
void ssgl_radd (register REAL *vals, register REAL *work, register int level, register int *segs)
void grop_hc_vvl (REAL *vals, REAL *work, int *segs, int *oprs, int dim)
int hmt_xor_ (register int *i1, register int *i2)
void staged_gs_ (register REAL *vals, register REAL *work, register int *level, register int *segs)
void staged_iadd_ (int *gl_num, int *level)
void staged_radd_ (double *gl_num, int *level)
void hmt_concat_ (REAL *vals, REAL *work, int *size)
void new_ssgl_radd (register REAL *vals, register REAL *work, register int level, register int *segs)
Variables
int my_id = 0
int num_nodes = 1
int floor_num_nodes
int i_log2_num_nodes
Function Documentation
void comm_init (void)
Definition at line 132 of file comm.c.
References error_msg_fatal(), error_msg_warning(), floor_num_nodes, i, i_log2_num_nodes, ivec_zero(), my_id, mynode(), num_nodes, numnodes(), and tmp.
void comm_init_ (void)
Definition at line 115 of file comm.c.
References comm_init().
void comm_terminate (void)
Definition at line 234 of file comm.c.
References exit(), n, and vals.
void giop (int * vals, int * work, int n, int * oprs)
Definition at line 282 of file comm.c.
References comm_init(), crecv(), csend(), error_msg_fatal(), error_msg_warning(), floor_num_nodes, i_log2_num_nodes, ivec_fct_addr(), my_id, n, num_nodes, and vals.
void giop_ (int * vals, int * work, int * n, int * oprs)
Definition at line 265 of file comm.c.
References giop().
void gop (void * vals, void * work, int n, vbfp fp, DATA_TYPE dt, int comm_type)
Definition at line 822 of file comm.c.
References comm_init(), crecv(), csend(), error_msg_fatal(), floor_num_nodes, i_log2_num_nodes, my_id, n, num_nodes, TRUE, and vals.
void grop (REAL * vals, REAL * work, int n, int * oprs)
Definition at line 476 of file comm.c.
References comm_init(), crecv(), csend(), error_msg_fatal(), error_msg_warning(), floor_num_nodes, i_log2_num_nodes, my_id, n, num_nodes, rvec_fct_addr(), and vals.
void grop_ (REAL * vals, REAL * work, int * n, int * oprs)
Definition at line 459 of file comm.c.
References grop().
void grop_hc (REAL * vals, REAL * work, int n, int * oprs, int dim)
Definition at line 669 of file comm.c.
References comm_init(), crecv(), csend(), error_msg_fatal(), error_msg_warning(), i_log2_num_nodes, MIN, my_id, n, num_nodes, rvec_fct_addr(), and vals.
void grop_hc_ (REAL * vals, REAL * work, int * n, int * oprs, int * dim)
Definition at line 649 of file comm.c.
References grop_hc().
void grop_hc_vvl (REAL * vals, REAL * work, int * segs, int * oprs, int dim)
Definition at line 1129 of file comm.c.
References comm_init(), crecv(), csend(), error_msg_fatal(), error_msg_warning(), floor_num_nodes, i_log2_num_nodes, MIN, my_id, n, num_nodes, rvec_fct_addr(), and vals.
void grop_hc_vvl_ (REAL * vals, REAL * work, int * len_vec, int * oprs, int * dim)
Definition at line 805 of file comm.c.
References grop_hc_vvl().
void hmt_concat_ (REAL * vals, REAL * work, int * size)
Definition at line 1844 of file comm.c.
References comm_init(), i_log2_num_nodes, irecv(), isend(), msgwait(), my_id, num_nodes, printf(), and rvec_copy().
int hmt_xor_ (register int * i1, register int * i2)
Definition at line 1433 of file comm.c.
void new_ssgl_radd (register REAL * vals, register REAL * work, register int level, register int * segs)
Definition at line 2077 of file comm.c.
References comm_init(), crecv(), csend(), error_msg_fatal(), i_log2_num_nodes, my_id, num_nodes, and rvec_add().
void ssgl_radd (register REAL * vals, register REAL * work, register int level, register int * segs)
Definition at line 999 of file comm.c.
References comm_init(), crecv(), csend(), error_msg_fatal(), i_log2_num_nodes, my_id, num_nodes, and rvec_add().
void staged_gs_ (register REAL * vals, register REAL * work, register int * level, register int * segs)
Definition at line 1451 of file comm.c.
References ssgl_radd().
void staged_iadd_ (int * gl_num, int * level)
Definition at line 1466 of file comm.c.
References comm_init(), error_msg_fatal(), floor_num_nodes, i_log2_num_nodes, irecv(), isend(), msgwait(), my_id, num_nodes, and tmp.
void staged_radd_ (double * gl_num, int * level)
Definition at line 1653 of file comm.c.
References comm_init(), error_msg_fatal(), floor_num_nodes, i_log2_num_nodes, irecv(), isend(), msgwait(), my_id, num_nodes, and tmp.
Variable Documentation
int floor_num_nodes
Definition at line 46 of file comm.c.
int i_log2_num_nodes
Definition at line 47 of file comm.c.
int my_id = 0
Definition at line 44 of file comm.c.
int num_nodes = 1
Definition at line 45 of file comm.c.