KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/trap.f File Reference
trap.f File Reference
Functions/Subroutines
subroutine gradient (a, b, c, b1, b2)
subroutine procmap
subroutine fcnnct
subroutine swap2 (w, a, IND, N)
function interval (X, XI, N1)
subroutine putunit (n)
subroutine putx (ii, j, n, x)
subroutine putch (ii, j, n, x)
function trap (PRO, YPT, DS, NPTPR)
subroutine fileout
subroutine transpose (a, lda, b, ldb)
subroutine grab_window_xwd0
subroutine grab_window_raw0
subroutine get_box (xmse1, ymse1, xmse2, ymse2)
subroutine pix_map_out
subroutine vtk_out_xyz_sc (mx, ifout)
subroutine compress (ngpt, x, loc, ind, n, wk)
subroutine vtk_out_hex (icell, mx, my, mz, nel, ifout)
subroutine vtk_out_sca (ww, n, ifout, ivtk_dump)
subroutine fd_weights_full (xx, x, n, m, c)
subroutine map_tnsr (u2, n2, u1, n1, i, it, w1, w2, if3d)
subroutine mapreg3d (w_map, mx, ldmap, w_in, nx, ne, ifclip, ifxin, w)
subroutine vtk_out_head (name, lname, ifout, io)
subroutine vtk_out_xyz (x, y, z, n, ifout)
subroutine vtk_out_sc (ifout)
subroutine vtk_srf_cnt (vtkcut, vtkw, ngpt)
subroutine countour_tet (w, ws, vs, iffill)
subroutine draw_poly_fill (xyz, n, iffill)
subroutine find_xin (nc, ifclip, ifxin, xp, nx3, nel, xcmn, xcmx)
subroutine settol3n (tol, nx, nel, x, y, z)
subroutine settol3v (tol, ldt, nx, nel, x, y, z)
subroutine vtk_out_surf1 (cbi, mx, ifout)
subroutine out_face1 (nfout, ifce, ie, io, xf, yf, zf)
subroutine vtk_out_head_obj (name, lname, ifout, io)
subroutine mapreg3d1 (w_map, mx, w_in, nx, w)
subroutine vtk_out_surf (cbi, mx, ifout)
subroutine out_face (mx, nfout, ifce, ie, xf, yf, zf, io, wf, iw, ww)
subroutine quickscan_xy (x1, y1, x2, y2)
subroutine s3to2_regular
subroutine slab_sum (ua, va, pa, ta, uin, vin, pin, tin, nxy, nelxy, zlen)
subroutine avg_uvwpt_regular
subroutine avg_u_regular (uin)
subroutine avg_u_regular_old (uin)
subroutine slab_sum1 (ua, uin, nxy, nelxy, zlen)
subroutine get_tprd (tprd, xrc, yrc, zrc)
subroutine avg_uvwpt_radial
subroutine vtk_out_all (mx, ifout)
subroutine vtk_out_vec (uu, vv, ww, n, ifout, ivtk_dump)
subroutine vtk_out_surf0 (cbi, mx, ifout)
subroutine clrc (str11)
subroutine set_cluster (cluster, ncl, nelzz, tprd)
subroutine avg_u_radial (uin)
subroutine avg_u_radial2 (uin, wk, rmin, rmax, dr, cluster, ncl, nelzz)
subroutine avg_u_cylinder (ur, uin, mlx)
subroutine get_jac1di (jac1di, rad1d, melx, mely, melz)
subroutine avg_cylinder
subroutine out_glob (jglob, mx, my, mz, nel)
subroutine outfld (mx, my, mz, mel, mdim, uu, vv, ww, pp, tt)
Function/Subroutine Documentation
subroutine avg_cylinder ()
Definition at line 3185 of file trap.f.
References avg_u_cylinder(), i, nx, and prsii().
subroutine avg_u_cylinder (real, dimension(1) ur, real, dimension(1) uin, mlx)
Definition at line 3103 of file trap.f.
References get_jac1di(), i, j, nx, nz, and prsii().
subroutine avg_u_radial (real, dimension(1) uin)
Definition at line 2999 of file trap.f.
References avg_u_radial2(), get_tprd(), and set_cluster().
subroutine avg_u_radial2 (real, dimension(nx,ny,nz,nel) uin, real, dimension(nx,ny,nel) wk, rmin, rmax, real, dimension(nel) dr, integer, dimension(1) cluster, ncl, nelzz)
Definition at line 3040 of file trap.f.
References i, nx, nz, prsrr(), rmax(), rmin(), and rzero().
subroutine avg_u_regular (real, dimension(1) uin)
Definition at line 2286 of file trap.f.
References copy(), i, nx, nz, prs(), and rei().
subroutine avg_u_regular_old (real, dimension(1) uin)
Definition at line 2362 of file trap.f.
References copy(), glmax(), glmin(), nx, nz, prs(), rei(), rzero(), slab_sum1(), vlmax(), and vlmin().
subroutine avg_uvwpt_radial ()
Definition at line 2534 of file trap.f.
References avg_u_radial().
subroutine avg_uvwpt_regular ()
Definition at line 2256 of file trap.f.
References avg_u_regular(), and setwrk().
subroutine clrc (character*11 str11)
Definition at line 2899 of file trap.f.
References clear(), drfram(), drmesh(), hard(), heject(), nohard(), prs(), and res().
subroutine compress (ngpt, real, dimension(n) x, integer, dimension(n) loc, integer, dimension(n) ind, n, real, dimension(n) wk)
Definition at line 884 of file trap.f.
References i, n, and swap().
subroutine countour_tet (real w, real, dimension(4) ws, real, dimension(3,4) vs, logical iffill)
Definition at line 1536 of file trap.f.
References beta, draw_poly_fill(), i, ifill(), and j.
subroutine draw_poly_fill (real, dimension(3,n) xyz, n, logical iffill)
Definition at line 1610 of file trap.f.
References beginpp(), drawc(), endp(), i, movec(), n, xiso(), and yiso().
subroutine fcnnct ()
Definition at line 28 of file trap.f.
References dmax, gencen(), i, i0, interval(), j, putch(), putunit(), sort(), and swap2().
subroutine fd_weights_full (xx, real, dimension(0:n) x, n, m, real, dimension(0:n,0:m) c)
Definition at line 1126 of file trap.f.
References i, j, and n.
subroutine fileout ()
Definition at line 316 of file trap.f.
References blank(), chcopy(), dump_xyz_fld(), get_box(), i, izero(), j, menu(), mltiplt3(), mltiplt4(), mltiplt_all(), prsis(), reader(), res(), scoordx(), scoordy(), vtk_out_all(), vtk_out_sc(), vtk_out_surf(), vtk_out_xyz_sc(), xscr(), and yscr().
subroutine find_xin (nc, logical ifclip, logical, dimension(1) ifxin, real, dimension(nx3,nel) xp, nx3, nel, xcmn, xcmx)
Definition at line 1632 of file trap.f.
References glmax(), and glmin().
subroutine get_box (xmse1, ymse1, xmse2, ymse2)
Definition at line 506 of file trap.f.
References color, drawc(), drawsc(), mouse(), movec(), movesc(), prs(), prsii(), prsrr(), quickscan_xy(), reii(), scoordx(), scoordx_inv(), scoordy(), scoordy_inv(), xphy(), xscr(), yphy(), and yscr().
subroutine get_jac1di (real, dimension(nx,melx) jac1di, real, dimension(nx,melx) rad1d, melx, mely, melz)
Definition at line 3158 of file trap.f.
References i, i0, mxm(), nx, and nz.
subroutine get_tprd (real, dimension(6,nel) tprd, real, dimension(nx,ny,nz,nel) xrc, real, dimension(nx,ny,nz,nel) yrc, real, dimension(nx,ny,nz,nel) zrc)
Definition at line 2439 of file trap.f.
References nx, nz, rmax(), and rmin().
subroutine grab_window_raw0 ()
Definition at line 502 of file trap.f.
subroutine grab_window_xwd0 ()
Definition at line 498 of file trap.f.
subroutine gradient (a, b, c, b1, b2)
Definition at line 3 of file trap.f.
References prs(), rei(), and rerr().
function interval (X, dimension(0:n1) XI, N1)
Definition at line 214 of file trap.f.
References n.
subroutine map_tnsr (real, dimension(n2,n2,n2) u2, n2, real, dimension(n1,n1,n1) u1, n1, real, dimension(n2,n1) i, real, dimension(n1,n2) it, real, dimension (n2,n1,n1) w1, real, dimension (n2,n2,n1) w2, logical if3d)
Definition at line 1189 of file trap.f.
References mxm().
subroutine mapreg3d (real, dimension(mx*mx*mx,ldmap) w_map, mx, ldmap, real, dimension (nx*nx*nx,ne) w_in, nx, ne, logical ifclip, logical, dimension(1) ifxin, real, dimension(0:1) w)
Definition at line 1213 of file trap.f.
References copy(), fd_weights_full(), legend(), map_tnsr(), nx, prsii(), and transpose().
subroutine mapreg3d1 (real, dimension(mx*mx*mx) w_map, mx, real, dimension (nx*nx*nx) w_in, nx, real, dimension(0:1) w)
Definition at line 1953 of file trap.f.
References copy(), fd_weights_full(), legend(), map_tnsr(), nx, and transpose().
subroutine out_face (mx, nfout, ifce, ie, real, dimension(nx,ny,nz,1) xf, real, dimension(nx,ny,nz,1) yf, real, dimension(nx,ny,nz,1) zf, io, real, dimension(nx,ny,nz,1) wf, iw, real, dimension(mx,mx,mx,5) ww)
Definition at line 2110 of file trap.f.
References dsset(), mapreg3d1(), nx, and nz.
subroutine out_face1 (nfout, ifce, ie, io, real, dimension(nx,ny,nz,1) xf, real, dimension(nx,ny,nz,1) yf, real, dimension(nx,ny,nz,1) zf)
Definition at line 1850 of file trap.f.
References dsset(), nx, and nz.
subroutine out_glob (integer, dimension(mx,my,mz,nel) jglob, mx, my, mz, nel)
Definition at line 3214 of file trap.f.
References i, j, and n.
subroutine outfld (mx, my, mz, mel, mdim, uu, vv, ww, pp, tt)
Definition at line 3234 of file trap.f.
References blank(), byte_close, byte_open, byte_write, i, prs(), and terminate_string().
subroutine pix_map_out ()
Definition at line 711 of file trap.f.
References blank(), izero(), and prs().
subroutine procmap ()
Definition at line 20 of file trap.f.
subroutine putch (ii, j, n, x)
Definition at line 283 of file trap.f.
References i, j, and n.
subroutine putunit (n)
Definition at line 260 of file trap.f.
References n.
subroutine putx (ii, j, n, character*1 x)
Definition at line 274 of file trap.f.
References i, j, and n.
subroutine quickscan_xy (x1, y1, x2, y2)
Definition at line 2153 of file trap.f.
References xiso(), and yiso().
subroutine s3to2_regular ()
Definition at line 2180 of file trap.f.
References glmax(), glmin(), nx, nz, outfld(), prs(), rei(), rzero(), slab_sum(), vlmax(), and vlmin().
subroutine set_cluster (integer, dimension (nelm) cluster, integer ncl, nelzz, real, dimension(6,nelm) tprd)
Definition at line 2917 of file trap.f.
References get_tprd(), i, iint(), iswap(), and tuple_sort().
subroutine settol3n (real, dimension(nx,nx,nx,nel) tol, nx, nel, real, dimension (nx,nx,nx,nel) x, real, dimension (nx,nx,nx,nel) y, real, dimension (nx,nx,nx,nel) z)
Definition at line 1663 of file trap.f.
References i, i0, j, nx, prs(), prsr(), res(), and scale().
subroutine settol3v (real, dimension(ldt,3) tol, ldt, nx, nel, real, dimension (ldt) x, real, dimension (ldt) y, real, dimension (ldt) z)
Definition at line 1734 of file trap.f.
References i.
subroutine slab_sum (real, dimension(nxy,1) ua, real, dimension(nxy,1) va, real, dimension(nxy,1) pa, real, dimension(nxy,1) ta, real, dimension(nxy,nz,1) uin, real, dimension(nxy,nz,1) vin, real, dimension(nxy,nz,1) pin, real, dimension(nxy,nz,1) tin, nxy, nelxy, real zlen)
Definition at line 2230 of file trap.f.
References i, nz, and scale().
subroutine slab_sum1 (real, dimension(nxy,1) ua, real, dimension(nxy,nz,1) uin, nxy, nelxy, real zlen)
Definition at line 2416 of file trap.f.
References i, nz, and scale().
subroutine swap2 (dimension(1) w, dimension(1) a, dimension(1) IND, N)
Definition at line 203 of file trap.f.
References j, and n.
subroutine transpose (real, dimension(lda,1) a, lda, real, dimension(ldb,1) b, ldb)
Definition at line 487 of file trap.f.
References i, and j.
function trap (real, dimension(0:500) PRO, real, dimension(0:500) YPT, DS, NPTPR)
Definition at line 292 of file trap.f.
subroutine vtk_out_all (mx, logical ifout)
Definition at line 2558 of file trap.f.
References compress(), find_xin(), i, icopy(), isort(), locglobm(), mapreg3d(), nx, nz, prs(), prsii(), prsrr(), rerr(), setwrk(), vtk_out_head(), vtk_out_hex(), vtk_out_sca(), and vtk_out_xyz().
subroutine vtk_out_head (character*1, dimension(lname) name, lname, logical ifout, io)
Definition at line 1273 of file trap.f.
References i, and ltrunc().
subroutine vtk_out_head_obj (character*1, dimension(lname) name, lname, logical ifout, io)
Definition at line 1881 of file trap.f.
References i, and ltrunc().
subroutine vtk_out_hex (integer, dimension(mx,my,mz,nel) icell, mx, my, mz, nel, logical ifout)
Definition at line 908 of file trap.f.
References i, i0, j, and prsii().
subroutine vtk_out_sc (logical ifout)
Definition at line 1392 of file trap.f.
References compress(), glmax(), glmin(), ifill(), mapreg3d(), nx, prs(), prsrr(), rei(), rer(), and vtk_srf_cnt().
subroutine vtk_out_sca (real, dimension(1) ww, n, logical ifout, ivtk_dump)
Definition at line 1074 of file trap.f.
References blank(), glmax(), glmin(), i, n, and prs().
subroutine vtk_out_surf (character*3 cbi, mx, logical ifout)
Definition at line 2005 of file trap.f.
References i, j, out_face(), and vtk_out_head_obj().
subroutine vtk_out_surf0 (character*3 cbi, mx, logical ifout)
Definition at line 2794 of file trap.f.
References decod(), i, j, list, nx, out_face(), and vtk_out_head_obj().
subroutine vtk_out_surf1 (character*3 cbi, mx, logical ifout)
Definition at line 1765 of file trap.f.
References i, j, nx, nz, out_face1(), and vtk_out_head_obj().
subroutine vtk_out_vec (real, dimension(1) uu, real, dimension(1) vv, real, dimension(1) ww, n, logical ifout, ivtk_dump)
Definition at line 2746 of file trap.f.
References blank(), glmax(), glmin(), i, n, and prs().
subroutine vtk_out_xyz (real, dimension(1) x, real, dimension(1) y, real, dimension(1) z, n, logical ifout)
Definition at line 1351 of file trap.f.
References blank(), i, ltrunc(), and n.
subroutine vtk_out_xyz_sc (mx, logical ifout)
Definition at line 740 of file trap.f.
References coef2(), compress(), find_xin(), i, icopy(), isort(), locglobm(), mapreg3d(), nx, nz, prs(), prsii(), prsrr(), rerr(), setwrk(), vtk_out_head(), vtk_out_hex(), vtk_out_sca(), and vtk_out_xyz().
subroutine vtk_srf_cnt (vtkcut, real, dimension(1) vtkw, ngpt)
Definition at line 1450 of file trap.f.
References color, countour_tet(), fillp(), and prsii().