KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/trap2.f File Reference
trap2.f File Reference
Functions/Subroutines
subroutine tec_cell_gen (kcell, ncells, icell, mx, my, mz, nel)
subroutine mltiplt_tec
subroutine tec_out_xyz_sc (mx, v1, v2, iframe)
program complextest
Function/Subroutine Documentation
program complextest ()
Definition at line 326 of file trap2.f.
References color, i, j, and npts.
subroutine mltiplt_tec ()
Definition at line 64 of file trap2.f.
References getfld(), grab_window_pix(), mouse(), prs(), rei(), reiii(), and tec_out_xyz_sc().
subroutine tec_cell_gen (integer, dimension(8,1) kcell, ncells, integer, dimension(mx,my,mz,nel) icell, mx, my, mz, nel)
Definition at line 3 of file trap2.f.
References i, i0, j, and prsii().
subroutine tec_out_xyz_sc (mx, real, dimension(1) v1, real, dimension(1) v2, iframe)
Definition at line 120 of file trap2.f.
References coef2(), compress(), find_xin(), icopy(), isort(), locglobm(), mapreg3d(), nx, nz, prs(), prsii(), prsrr(), rerr(), setwrk(), tec_cell_gen(), and vtk_out_hex().