KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/trap3.f File Reference
trap3.f File Reference
Functions/Subroutines
subroutine n2tec_field_open
subroutine n2tec_fezone_hdr (ncell, npts)
subroutine n2tec_xyz_out (npts, xm, ym, zm)
subroutine n2tec_scalar_out (npts, scalar)
subroutine n2tec_cell_out (cell)
subroutine n2tec_fclose (cell)
Function/Subroutine Documentation
subroutine n2tec_cell_out (integer, dimension(1) cell)
Definition at line 170 of file trap3.f.
References i.
subroutine n2tec_fclose (cell)
Definition at line 181 of file trap3.f.
References i.
subroutine n2tec_fezone_hdr (ncell, npts)
Definition at line 42 of file trap3.f.
References i, and npts.
subroutine n2tec_field_open ()
Definition at line 3 of file trap3.f.
References blank(), chcopy(), i, and ltrunc().
subroutine n2tec_scalar_out (npts, real, dimension(npts) scalar)
Definition at line 148 of file trap3.f.
References i, and npts.
subroutine n2tec_xyz_out (npts, real, dimension(npts) xm, real, dimension(npts) ym, real, dimension(npts) zm)
Definition at line 124 of file trap3.f.
References i, and npts.