KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/turb.f File Reference
turb.f File Reference
Functions/Subroutines
subroutine setturb
subroutine pretmic
subroutine postmic
subroutine cbcturb
subroutine whatfld (IFTURB)
subroutine turbfld (IFKFLD, IFEFLD)
subroutine tviscos
subroutine tviscke
subroutine tvisca
subroutine tpropk
subroutine tprope
subroutine maketq
subroutine setqk
subroutine setqe
subroutine turbqk
subroutine turbqe
subroutine turbwbc (TMP, TMA, SMU)
subroutine facewsk (S, IEL, IFC)
subroutine facewse (S, IEL, IFC)
subroutine settmc
subroutine comphi (PHI)
subroutine iniphi (PHI)
subroutine twalluz (IGEOM)
subroutine twallsh
subroutine facews (TRX, TRY, TRZ, IEL, IFC)
subroutine comwuz (XWLL, YWLL, ZWLL, V1, V2, V3, VISKIN, VISMIN, IEL, IFC)
subroutine norind (JS3, JF3, JSKIP3, IWX, IWY, IFC, ISCH)
subroutine cwref (XWLL, YWLL, ZWLL, UTW, ZNW, VTAN1, VTAN2, VTAN3, IEL, IFC, JWX, JWY, JS3, JSKIP3)
subroutine comtdir (VTAN1, VTAN2, VTAN3, JWX, JWY, IWZ, IEL, IFC)
subroutine subgrid (UTW, ZNW, UW, ZW, ZL, ZU, UL, UU, AKVIS, UST1, IEL, IFC, JWX, JWY, JWZ)
subroutine comufr (UST, U, Z, AKVIS, UST1, IEL, IFC, JWX, JWY)
subroutine comlsq
subroutine lscale
subroutine tlmask (SMASK)
subroutine bcdirtl (TLS, SMS, TMP)
subroutine facewl (S, IEL, IFC)
subroutine getvar (V, VP, RP)
subroutine invchk2 (A, B, N)
subroutine facind2 (JS1, JF1, JSKIP1, JS2, JF2, JSKIP2, IFC)
Function/Subroutine Documentation
subroutine bcdirtl (dimension(lx1,ly1,lz1,lelv) TLS, dimension(lx1,ly1,lz1,lelv) SMS, dimension(lx1,ly1,lz1,lelv) TMP)
Definition at line 1121 of file turb.f.
References add2(), col2(), dsop(), facev(), facewl(), ly1, lz1, and rzero().
subroutine cbcturb ()
Definition at line 64 of file turb.f.
subroutine comlsq ()
Definition at line 1029 of file turb.f.
References cfill(), cmult(), glmax(), and lscale().
subroutine comphi (dimension(lx1,ly1,lz1,1) PHI)
Definition at line 494 of file turb.f.
References addcol3(), cmult(), lelt, ly1, lz1, rzero(), and stnrate().
subroutine comtdir (VTAN1, VTAN2, VTAN3, JWX, JWY, IWZ, IEL, IFC)
Definition at line 876 of file turb.f.
subroutine comufr (UST, U, Z, AKVIS, UST1, IEL, IFC, JWX, JWY)
Definition at line 970 of file turb.f.
References emerxit(), and exitt().
subroutine comwuz (dimension(lx1,lz1) XWLL, dimension(lx1,lz1) YWLL, dimension(lx1,lz1) ZWLL, dimension(lx1,ly1,lz1) V1, dimension(lx1,ly1,lz1) V2, dimension(lx1,ly1,lz1) V3, dimension(lx1,ly1,lz1) VISKIN, VISMIN, IEL, IFC)
Definition at line 677 of file turb.f.
References comtdir(), comufr(), cwref(), facind2(), ly1, lz1, norind(), and subgrid().
subroutine cwref (dimension(lx1,lz1) XWLL, dimension(lx1,lz1) YWLL, dimension(lx1,lz1) ZWLL, dimension(lx1) UTW, dimension(lx1) ZNW, VTAN1, VTAN2, VTAN3, IEL, IFC, JWX, JWY, JS3, JSKIP3)
Definition at line 835 of file turb.f.
References lz1.
subroutine facewl (dimension(lx1,ly1,lz1) S, IEL, IFC)
Definition at line 1158 of file turb.f.
References facind2(), i, ly1, and lz1.
subroutine facews (dimension(lx1,ly1,lz1) TRX, dimension(lx1,ly1,lz1) TRY, dimension(lx1,ly1,lz1) TRZ, IEL, IFC)
Definition at line 644 of file turb.f.
References facind2(), i, ly1, and lz1.
subroutine facewse (dimension(lx1,ly1,lz1) S, IEL, IFC)
Definition at line 435 of file turb.f.
References facind2(), i, ly1, and lz1.
subroutine facewsk (dimension(lx1,ly1,lz1) S, IEL, IFC)
Definition at line 415 of file turb.f.
References facind2(), i, ly1, and lz1.
subroutine facind2 (JS1, JF1, JSKIP1, JS2, JF2, JSKIP2, IFC)
Definition at line 1207 of file turb.f.
References dsset().
subroutine getvar (dimension(lx1) V, VP, RP)
Definition at line 1181 of file turb.f.
References hgll(), and i.
subroutine iniphi (dimension(lx1,ly1,lz1,1) PHI)
Definition at line 527 of file turb.f.
References bcdirvc(), cfill(), glmax(), glmin(), ly1, lz1, nekuf(), and opdot().
subroutine invchk2 (dimension(1) A, dimension(1) B, N)
Definition at line 1196 of file turb.f.
References i, and n.
subroutine lscale ()
Definition at line 1054 of file turb.f.
References add2(), axhelm(), bcdirtl(), cfill(), cmult(), col2(), hmholtz(), ly1, lz1, rone(), rzero(), sub2(), and tlmask().
subroutine maketq ()
Definition at line 285 of file turb.f.
References setqe(), setqk(), and turbfld().
subroutine norind (JS3, JF3, JSKIP3, IWX, IWY, IFC, ISCH)
Definition at line 816 of file turb.f.
subroutine postmic ()
Definition at line 54 of file turb.f.
References comlsq().
subroutine pretmic ()
Definition at line 26 of file turb.f.
References cfill(), and rzero().
subroutine setqe ()
Definition at line 313 of file turb.f.
References rzero(), and turbqe().
subroutine setqk ()
Definition at line 299 of file turb.f.
References rzero(), and turbqk().
subroutine settmc ()
Definition at line 459 of file turb.f.
subroutine setturb ()
Definition at line 2 of file turb.f.
subroutine subgrid (dimension(lx1) UTW, dimension(lx1) ZNW, UW, ZW, ZL, ZU, UL, UU, AKVIS, UST1, IEL, IFC, JWX, JWY, JWZ)
Definition at line 908 of file turb.f.
References comufr(), emerxit(), exitt(), and getvar().
subroutine tlmask (dimension(lx1,ly1,lz1,lelv) SMASK)
Definition at line 1096 of file turb.f.
References dsop(), facev(), ly1, lz1, and rone().
subroutine tprope ()
Definition at line 262 of file turb.f.
References add3(), cfill(), cmult2(), ly1, lz1, and rone().
subroutine tpropk ()
Definition at line 239 of file turb.f.
References add3(), cfill(), cmult2(), ly1, lz1, and rone().
subroutine turbfld (logical IFKFLD, logical IFEFLD)
Definition at line 136 of file turb.f.
subroutine turbqe ()
Definition at line 344 of file turb.f.
References addcol3(), cmult(), cmult2(), col2(), comphi(), invchk2(), ly1, lz1, and sub2().
subroutine turbqk ()
Definition at line 327 of file turb.f.
References addcol3(), col2(), comphi(), ly1, lz1, and sub2().
subroutine turbwbc (dimension(lx1,ly1,lz1,1) TMP, dimension(lx1,ly1,lz1,1) TMA, dimension(lx1,ly1,lz1,1) SMU)
Definition at line 366 of file turb.f.
References dssum(), facewse(), facewsk(), facind(), invchk2(), ly1, lz1, and rzero().
subroutine tvisca ()
Definition at line 194 of file turb.f.
References addcol3(), cmult2(), col2(), col3(), comlsq(), comphi(), dssum(), iniphi(), ly1, lz1, and vsqrt().
subroutine tviscke ()
Definition at line 174 of file turb.f.
References addcol3(), cmult2(), col2(), and invchk2().
subroutine tviscos ()
Definition at line 155 of file turb.f.
References tvisca(), and tviscke().
subroutine twallsh ()
Definition at line 610 of file turb.f.
References add2(), faccvs(), facews(), ly1, lz1, and rzero3().
subroutine twalluz (IGEOM)
Definition at line 568 of file turb.f.
References bctwall(), comwuz(), copy(), facexv(), glmin(), invcol2(), ly1, lz1, rzero3(), and sub2().
subroutine whatfld (logical IFTURB)
Definition at line 118 of file turb.f.
References turbfld().