KTH framework for Nek5000 toolboxes; testing version: Toolbox/driver/runparam/uparam/uparam.f File Reference
uparam.f File Reference
Framework for Nek5000 toolboxes » Toolbox » Driver modules for KTH nek5000 platform » Runtime parameters » User parameters
Set of subroutines to read/write user runtime parameters.
Functions/Subroutines
subroutine user_param_in (iunit)
subroutine user_param_out (iunit)
Detailed Description
Set of subroutines to read/write user runtime parameters.
Author
Adam Peplinski
Date
Mar 7, 2016
Definition in file uparam.f.
Function/Subroutine Documentation
subroutine user_param_in (integer iunit)
Definition at line 19 of file uparam.f.
References bcast(), and err_chk().
subroutine user_param_out (integer iunit)
Definition at line 69 of file uparam.f.
References err_chk().