KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/userf.f File Reference
userf.f File Reference
Functions/Subroutines
subroutine userf
subroutine rad_vel
subroutine gkl_userf
subroutine vortex_tracking
subroutine id_cores
subroutine cluster_cores (icalld)
subroutine defjcc (jcc, nccolor, ccolor, nc)
subroutine core_position
subroutine vrticity
subroutine core_enstrophy
subroutine compute_stresses
subroutine get_hemi_forces (vdrag, pdrag, sarea)
subroutine fc_strs (s1, s2, s3, p1, p2, p3, sa, unx, uny, unz, area, v1, v2, v3, p, mu, pavg, ifc, ie, xp)
subroutine user_line_obj_gkl (pavg)
subroutine find_hemi
subroutine interp_all (uvw, xi, yi, zi, ierr)
subroutine line_avg (uvwavg, x0, x1)
subroutine time_trace
subroutine integrate_uut (q1i, q2i, q3i, x0, x1, q1, q2, q3)
subroutine get_component
subroutine add_const
subroutine compute_miles
subroutine compute_miles2
subroutine compute_miles3
subroutine azi_avg
subroutine trapzdu (s, m, a, b, n, sum, f, it)
subroutine qtrapu (uint, m, a, b, s, olds, w, f, ierr)
subroutine azi_int (uaz, vaz, waz, paz, taz, xstart, zstart, ierr)
subroutine func_eval (ss, m, tht, ierr)
subroutine get_file (npt, ii, io, ierr)
subroutine set_anil
subroutine interp_new (val, xex, yex, zex, idum, tt, IERR, rrl, ieo)
subroutine strfct_spec (psi)
subroutine strem2_spec (psi, ie)
subroutine find_x_flag (iemin)
subroutine integrate_uut6 (wint, x0, x1, q1, q2, q3, q4, q5, q6)
subroutine integrate_uut2 (wint, x0, x1, q1, q2)
subroutine integrate_uut9 (wint, x0, x1, q1, q2, q3, q4, q5, q6, q7, q8, q9)
subroutine compute_miles4
subroutine compute_miles5_old
subroutine compute_miles5
subroutine shift_comp
subroutine scale_comp
subroutine facind (kx1, kx2, ky1, ky2, kz1, kz2, nx1, ny1, nz1, iface)
subroutine facev (a, ie, iface, val, nx, ny, nz)
subroutine getnormals (unx, uny, unz, ie, is, x, y, z, ld, ndim)
subroutine vcross_normal (u, v, w)
subroutine mkside1 (xs, ys, zs, iside, ie)
subroutine set_element_cluster_param (par_cluster, nbface)
subroutine init_cluster_means (cls_means, npar, ncluster, par_cluster, ldp, nbface)
real function ran1 (idum)
subroutine cluster_bc
subroutine wave_space_z
subroutine ztransform (u, st, wk, nx, ny, nz, nel)
subroutine read_fld
subroutine get_fname80_open_old (io, ierr)
subroutine get_fname80 (fname)
subroutine big_image
subroutine enstrophy_out
subroutine sem2lex (ul, us, nelx, nely, nelz)
subroutine outlex (ul, nelx, nely, nelz, idim, name5)
subroutine const_per_elem
subroutine get_map (pmap, nel, depth, cell, nv, nrnk, npts, noutflow, io)
subroutine view_map
subroutine xy_average
subroutine xy_avg1 (ua, u, area, nx, nelxy, nelz)
subroutine xy_avgo (za, ua, va, wa, nx, nelz)
subroutine xz_average
subroutine xz_avg1 (ua, u, area, nx, nelx, nely, nelz)
subroutine xz6_average
subroutine xz_avg6 (u, nx, nelx, nely, nelz)
subroutine mapleg1 (uh, u, nx, ndim, w)
subroutine build_legend_transform (Lj, Ljt, zpts, nx)
subroutine tensr3 (v, nv, u, nu, A, Bt, Ct, w, ndim)
subroutine transpose1 (a, n)
subroutine error_dist
subroutine out_dist3 (u, nx, e)
Function/Subroutine Documentation
subroutine add_const ()
Definition at line 1500 of file userf.f.
References cadd(), copy(), glmax(), glmin(), nx, nz, prs(), rer(), and shift().
subroutine azi_avg ()
Definition at line 2274 of file userf.f.
References azi_int(), get_file(), and i.
subroutine azi_int (uaz, vaz, waz, paz, taz, xstart, zstart, ierr)
Definition at line 2430 of file userf.f.
References i, nx, nz, and qtrapu().
subroutine big_image ()
Definition at line 4903 of file userf.f.
References auto_size_pixel_window(), blank(), clear(), drfram(), drmesh(), grab_window_pix(), gswrit(), hard(), heject(), i, mouse(), nohard(), nx, plotit(), post_reset_window(), prs(), rei(), rer(), savstate(), setstate(), and setwrk().
subroutine build_legend_transform (real, dimension(nx*nx) Lj, real, dimension(nx*nx) Ljt, real, dimension(nx) zpts, nx)
Definition at line 5501 of file userf.f.
References cmult(), exitt(), gaujordf(), i, j, legendre_poly(), n, nx, transpose(), and transpose1().
subroutine cluster_bc ()
Definition at line 4634 of file userf.f.
References copy(), dmin, dot(), facev(), glmax(), glmin(), i, init_cluster_means(), izero(), j, nx, nz, plotit(), prs(), ran1(), res(), rone(), rzero(), and set_element_cluster_param().
subroutine cluster_cores (icalld)
Definition at line 444 of file userf.f.
References color, defjcc(), glmin(), hilight2(), i, ilmin(), irank(), iswap(), izero(), j, nx, nz, and rank().
subroutine compute_miles ()
Definition at line 1526 of file userf.f.
References getfld(), glmax(), glmin(), i, i0, integrate_uut(), interp_all(), j, n, nx, nz, pris(), prs(), rei(), rzero(), and setwrk().
subroutine compute_miles2 ()
Definition at line 1810 of file userf.f.
References getfld(), glmax(), glmin(), i, interp_all(), j, n, nx, nz, pris(), prs(), rei(), rzero(), and setwrk().
subroutine compute_miles3 ()
Definition at line 1990 of file userf.f.
References col3(), getfld(), glmax(), glmin(), i, i0, integrate_uut(), interp_all(), j, n, nx, nz, pris(), prs(), rei(), res(), rzero(), setwrk(), and time_trace().
subroutine compute_miles4 ()
Definition at line 3145 of file userf.f.
References copy(), dudxyz(), getfld(), glmax(), glmin(), i, i0, integrate_uut9(), interp_all(), j, n, nx, nz, pris(), prs(), rei(), rer(), rzero(), and setwrk().
subroutine compute_miles5 ()
Definition at line 3964 of file userf.f.
References copy(), getfld(), glmax(), glmin(), i, integrate_uut2(), interp_all(), j, n, nx, nz, pris(), prs(), rei(), rer(), rzero(), and setwrk().
subroutine compute_miles5_old ()
Definition at line 3549 of file userf.f.
References copy(), dudxyz(), getfld(), glmax(), glmin(), i, i0, integrate_uut9(), interp_all(), j, n, nx, nz, pris(), prs(), rei(), rer(), rzero(), and setwrk().
subroutine compute_stresses ()
Definition at line 839 of file userf.f.
References find_hemi(), get_hemi_forces(), getfld(), pris(), prs(), reiii(), rer(), and setwrk().
subroutine const_per_elem ()
Definition at line 5148 of file userf.f.
References cfill(), i, nx, nz, and prs().
subroutine core_enstrophy ()
Definition at line 798 of file userf.f.
References nx, nz, and prs().
subroutine core_position ()
Definition at line 717 of file userf.f.
References nx, and nz.
subroutine defjcc (integer, dimension(1) jcc, nccolor, integer, dimension(1) ccolor, nc)
Definition at line 675 of file userf.f.
subroutine enstrophy_out ()
Definition at line 5031 of file userf.f.
References comp_vorticity(), i, n, nx, nz, outlex(), prs(), reiii(), and sem2lex().
subroutine error_dist ()
Definition at line 5582 of file userf.f.
References i, mapleg1(), nx, and out_dist3().
subroutine facev (real, dimension(nx,ny,nz,1) a, ie, iface, val, nx, ny, nz)
Definition at line 4353 of file userf.f.
References facind(), nx, and nz.
subroutine facind (kx1, kx2, ky1, ky2, kz1, kz2, nx1, ny1, nz1, iface)
Definition at line 4337 of file userf.f.
subroutine fc_strs (real s1, real s2, real s3, p1, p2, p3, sa, real, dimension(nx,nz,6) unx, real, dimension(nx,nz,6) uny, real, dimension(nx,nz,6) unz, real, dimension(nx,nz,6) area, real, dimension(nx,ny,nz) v1, real, dimension(nx,ny,nz) v2, real, dimension(nx,ny,nz) v3, real, dimension(nx,ny,nz) p, real mu, real pavg, ifc, ie, real, dimension(nx,ny,nz,1) xp)
Definition at line 971 of file userf.f.
References dsset(), i, nx, and nz.
subroutine find_hemi ()
Definition at line 1195 of file userf.f.
References decod(), i, list, nx, prs(), rerrr(), and setrstp_set().
subroutine find_x_flag (iemin)
Definition at line 2918 of file userf.f.
References glmax(), n, nx, nz, and vlmin().
subroutine func_eval (real, dimension(m) ss, m, tht, ierr)
Definition at line 2509 of file userf.f.
References color, draw_circ1(), evalsc(), glmax(), glmin(), interp_new(), nx, nz, and rzero().
subroutine get_component ()
Definition at line 1465 of file userf.f.
References copy(), i, menu(), nx, nz, and prs().
subroutine get_file (npt, ii, io, ierr)
Definition at line 2577 of file userf.f.
References prs(), and res().
subroutine get_fname80 (character*80 fname)
Definition at line 4892 of file userf.f.
References blank(), prs(), and res().
subroutine get_fname80_open_old (io, ierr)
Definition at line 4871 of file userf.f.
References get_fname80(), ltrunc(), and prs().
subroutine get_hemi_forces (real, dimension(3) vdrag, real, dimension(3) pdrag, real sarea)
Definition at line 902 of file userf.f.
References fc_strs(), j, mod1(), nx, nz, and prs().
subroutine get_map (integer, dimension(nel) pmap, nel, integer depth, integer, dimension(nv,nel) cell, nv, nrnk, npts, noutflow, io)
Definition at line 5169 of file userf.f.
References iglmax(), iglmin(), npts, and prsi().
subroutine getnormals (unx, uny, unz, ie, is, real, dimension(ld,8) x, real, dimension(ld,8) y, real, dimension(ld,8) z, ld, ndim)
Definition at line 4368 of file userf.f.
References vcross_normal().
subroutine gkl_userf ()
Definition at line 222 of file userf.f.
References vortex_tracking().
subroutine id_cores ()
Definition at line 365 of file userf.f.
References glmin(), nx, and nz.
subroutine init_cluster_means (real, dimension (npar,ncluster) cls_means, npar, ncluster, real, dimension (ldp ,nbface) par_cluster, ldp, nbface)
Definition at line 4570 of file userf.f.
References copy(), i, and j.
subroutine integrate_uut (q1i, q2i, q3i, real, dimension(3) x0, real, dimension(3) x1, real, dimension(1) q1, real, dimension(1) q2, real, dimension(1) q3)
Definition at line 1411 of file userf.f.
References i, and n.
subroutine integrate_uut2 (real, dimension(9) wint, real, dimension(3) x0, real, dimension(3) x1, real, dimension(1) q1, real, dimension(1) q2)
Definition at line 3009 of file userf.f.
References add2s2(), copy(), i, n, and rzero().
subroutine integrate_uut6 (real, dimension(6) wint, real, dimension(3) x0, real, dimension(3) x1, real, dimension(1) q1, real, dimension(1) q2, real, dimension(1) q3, real, dimension(1) q4, real, dimension(1) q5, real, dimension(1) q6)
Definition at line 2945 of file userf.f.
References add2s2(), copy(), i, n, and rzero().
subroutine integrate_uut9 (real, dimension(9) wint, real, dimension(3) x0, real, dimension(3) x1, real, dimension(1) q1, real, dimension(1) q2, real, dimension(1) q3, real, dimension(1) q4, real, dimension(1) q5, real, dimension(1) q6, real, dimension(1) q7, real, dimension(1) q8, real, dimension(1) q9)
Definition at line 3073 of file userf.f.
References add2s2(), copy(), i, n, and rzero().
subroutine interp_all (real, dimension(13) uvw, xi, yi, zi, ierr)
Definition at line 1228 of file userf.f.
References prrrr(), prs(), and rzero().
subroutine interp_new (val, xex, yex, zex, idum, real, dimension(1) tt, IERR, real, dimension(3) rrl, ieo)
Definition at line 2644 of file userf.f.
References coef(), evalsc(), findr(), findre(), locglob(), nx, nz, and prs().
subroutine line_avg (real, dimension(9,1) uvwavg, real, dimension(3) x0, real, dimension(3) x1)
Definition at line 1266 of file userf.f.
References add2s2(), cmult(), i, i0, interp_all(), j, prrrr(), prsi(), and rzero().
subroutine mapleg1 (real, dimension(nx**ndim) uh, real, dimension(nx**ndim) u, nx, ndim, real, dimension(nx**ndim,2) w)
Definition at line 5474 of file userf.f.
References build_legend_transform(), nx, tensr3(), and zwgll().
subroutine mkside1 (xs, ys, zs, iside, ie)
Definition at line 4456 of file userf.f.
subroutine out_dist3 (real, dimension(nx,nx,nx) u, nx, integer e)
Definition at line 5612 of file userf.f.
References i, i0, j, nx, and rzero().
subroutine outlex (real, dimension(nx,nelx,ny,nely,nz,nelz) ul, nelx, nely, nelz, idim, character*5 name5)
Definition at line 5111 of file userf.f.
References nx, and nz.
subroutine qtrapu (real, dimension(m) uint, m, a, b, real, dimension(m) s, real, dimension(m) olds, real, dimension(m) w, real, dimension(m) f, ierr)
Definition at line 2379 of file userf.f.
References cfill(), copy(), i, rzero(), and trapzdu().
subroutine rad_vel ()
Definition at line 161 of file userf.f.
References get_component(), i, nx, and nz.
real function ran1 (integer idum)
Definition at line 4598 of file userf.f.
subroutine read_fld ()
Definition at line 4850 of file userf.f.
References get_fname80_open_old(), i, nx, and nz.
subroutine scale_comp ()
Definition at line 4313 of file userf.f.
References blank(), cmult(), nx, nz, prs(), rer(), res(), and scale().
subroutine sem2lex (real, dimension(nx,nelx,ny,nely,nz,nelz) ul, real, dimension(nx,ny,nz,nel) us, nelx, nely, nelz)
Definition at line 5083 of file userf.f.
References nx, and nz.
subroutine set_anil ()
Definition at line 2615 of file userf.f.
References avg_uvwpt_radial(), azi_avg(), menu(), prs(), and strfct_spec().
subroutine set_element_cluster_param (real, dimension (9,nelm) par_cluster, nbface)
Definition at line 4493 of file userf.f.
References getnormals(), glmax(), glmin(), mkside1(), nx, and nz.
subroutine shift_comp ()
Definition at line 4289 of file userf.f.
References blank(), cadd(), nx, nz, prs(), rer(), res(), and shift().
subroutine strem2_spec (real, dimension(1) psi, ie)
Definition at line 2847 of file userf.f.
References i, j, mxm(), nx, nz, and rzero().
subroutine strfct_spec (real, dimension(1) psi)
Definition at line 2747 of file userf.f.
References find_x_flag(), i, j, nx, nz, rzero(), spint(), and strem2_spec().
subroutine tensr3 (real, dimension(nv,nv,nv) v, nv, real, dimension(nu,nu,nu) u, nu, real, dimension(1) A, Bt, Ct, real, dimension(1) w, ndim)
Definition at line 5537 of file userf.f.
References mxm().
subroutine time_trace ()
Definition at line 1347 of file userf.f.
References getfld(), glmax(), glmin(), interp_all(), nx, nz, pris(), prs(), prsrrr(), and reiii().
subroutine transpose1 (real, dimension(n,n) a, n)
Definition at line 5569 of file userf.f.
References i, j, and n.
subroutine trapzdu (real, dimension(m) s, m, real a, real b, integer n, real, dimension(m) sum, real, dimension(m) f, integer it)
Definition at line 2309 of file userf.f.
References add2(), cmult(), func_eval(), i, and rzero().
subroutine user_line_obj_gkl (pavg)
Definition at line 1100 of file userf.f.
References i, i0, j, prrrr(), prsi(), and prsr().
subroutine userf ()
Definition at line 3 of file userf.f.
References add_const(), big_image(), cluster_bc(), compute_miles(), compute_miles2(), compute_miles3(), compute_miles4(), compute_miles5(), const_per_elem(), copy(), enstrophy_out(), error_dist(), gkl_userf(), menu(), nx, nz, rad_vel(), read_fld(), scale_comp(), set_anil(), shift_comp(), view_map(), vsqrt(), wave_space_z(), xz6_average(), and xz_average().
subroutine vcross_normal (real, dimension(3) u, real, dimension(3) v, real, dimension(3) w)
Definition at line 4433 of file userf.f.
subroutine view_map ()
Definition at line 5196 of file userf.f.
References blank(), clear(), color, drfram(), drmesh(), g3writ(), get_map(), i, j, npts, nx, prs(), and res().
subroutine vortex_tracking ()
Definition at line 264 of file userf.f.
References cluster_cores(), copy(), core_enstrophy(), core_position(), id_cores(), new_vortex(), nx, nz, and vrticity().
subroutine vrticity ()
Definition at line 742 of file userf.f.
References dsavg(), dudxyz(), nx, nz, prs(), and sub3().
subroutine wave_space_z ()
Definition at line 4788 of file userf.f.
References cmult(), copy(), generalev(), i, mapz(), nx, nz, rzero(), semhat(), transpose(), and ztransform().
subroutine xy_average ()
Definition at line 5255 of file userf.f.
References nx, prs(), rei(), xy_avg1(), and xy_avgo().
subroutine xy_avg1 (real, dimension(nx,nelz) ua, real, dimension(nx,nx,nx,nelxy,nelz) u, real, dimension(nx,nx,6,nelxy,nelz) area, nx, nelxy, nelz)
Definition at line 5285 of file userf.f.
References nx.
subroutine xy_avgo (real, dimension(nx,nelz) za, real, dimension(nx,nelz) ua, real, dimension(nx,nelz) va, real, dimension(nx,nelz) wa, nx, nelz)
Definition at line 5312 of file userf.f.
References nx.
subroutine xz6_average ()
Definition at line 5388 of file userf.f.
References nx, prs(), reiii(), and xz_avg6().
subroutine xz_average ()
Definition at line 5332 of file userf.f.
References nx, prs(), reiii(), xy_avgo(), and xz_avg1().
subroutine xz_avg1 (real, dimension(nx,nely) ua, real, dimension(nx,nx,nx,nelx,nely,nelz) u, real, dimension(nx,nx,6,nelx,nely,nelz) area, nx, nelx, nely, nelz)
Definition at line 5359 of file userf.f.
References nx.
subroutine xz_avg6 (real, dimension(nx*nx*nx,nelx,nely,nelz) u, nx, nelx, nely, nelz)
Definition at line 5416 of file userf.f.
References i, mod1(), and nx.
subroutine ztransform (real, dimension(nx*ny*nz,nel) u, real, dimension(nz,nz) st, real, dimension(nx*ny*nz) wk, nx, ny, nz, nel)
Definition at line 4833 of file userf.f.
References copy(), mxm(), nx, and nz.