KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/postnek/vtk_interface.c File Reference
vtk_interface.c File Reference
#include <stdio.h>
#include <math.h>
#include <float.h>
#include <limits.h>
#include "const.h"
#include "types.h"
#include "bss_malloc.h"
#include "error.h"
#include "vtk_interface.h"
Functions
main ()
void clear_vtk_all_ (void)
void get_srfs (void)
void make_vtk_srf_ (int *flag)
void set_vtk_file_tag_ (int *n)
void set_vtk_file_name_ (char *fn)
void set_vtk_pts_ (float *x, float *y, float *z, int *n, int *reflect)
void set_vtk_cells_ (int *cells, int *n, int *reflect)
void set_vtk_cscalar_ (float *vals, int *n, int *reflect)
void set_vtk_pscalar_ (float *vals, int *n, int *reflect)
Variables
char * file_header
int tag
int npts
float * pt_coords
int nhexes
int * hex_cells
float * contour_scalar
float * passive_scalar
int nsrfs
float * srf_thresholds
Function Documentation
void clear_vtk_all_ (void)
Definition at line 53 of file vtk_interface.c.
References bss_free(), contour_scalar, file_header, hex_cells, nhexes, npts, nsrfs, passive_scalar, pt_coords, srf_thresholds, and tag.
void get_srfs (void)
Definition at line 74 of file vtk_interface.c.
References bss_malloc(), error_msg_warning(), i, nsrfs, and srf_thresholds.
main ()
Definition at line 46 of file vtk_interface.c.
void make_vtk_srf_ (int * flag)
Definition at line 103 of file vtk_interface.c.
References contour_scalar, error(), error_msg_fatal(), file_header, get_srfs(), hex_cells, nhexes, npts, nsrfs, passive_scalar, printf(), pt_coords, srf_thresholds, and tag.
void set_vtk_cells_ (int * cells, int * n, int * reflect)
Definition at line 194 of file vtk_interface.c.
References bss_free(), bss_malloc(), hex_cells, i, n, nhexes, ptr, and TRUE.
void set_vtk_cscalar_ (float * vals, int * n, int * reflect)
Definition at line 223 of file vtk_interface.c.
References bss_malloc(), contour_scalar, error_msg_fatal(), i, n, npts, ptr, TRUE, and vals.
void set_vtk_file_name_ (char * fn)
Definition at line 143 of file vtk_interface.c.
References bss_init(), bss_malloc(), comm_init(), file_header, i, and perm_init().
void set_vtk_file_tag_ (int * n)
Definition at line 136 of file vtk_interface.c.
References n, and tag.
void set_vtk_pscalar_ (float * vals, int * n, int * reflect)
Definition at line 260 of file vtk_interface.c.
References bss_malloc(), error_msg_fatal(), i, n, npts, passive_scalar, ptr, TRUE, and vals.
void set_vtk_pts_ (float * x, float * y, float * z, int * n, int * reflect)
Definition at line 165 of file vtk_interface.c.
References bss_free(), bss_malloc(), i, n, npts, pt_coords, ptr, TRUE, x, y(), and z.
Variable Documentation
float* contour_scalar
Definition at line 41 of file vtk_interface.c.
char* file_header
Definition at line 35 of file vtk_interface.c.
int* hex_cells
Definition at line 40 of file vtk_interface.c.
int nhexes
Definition at line 39 of file vtk_interface.c.
int npts
Definition at line 37 of file vtk_interface.c.
int nsrfs
Definition at line 43 of file vtk_interface.c.
float* passive_scalar
Definition at line 42 of file vtk_interface.c.
float* pt_coords
Definition at line 38 of file vtk_interface.c.
float* srf_thresholds
Definition at line 44 of file vtk_interface.c.
int tag
Definition at line 36 of file vtk_interface.c.