KTH framework for Nek5000 toolboxes; testing version: Nek5000/core/cmt/wall_bc.f File Reference
wall_bc.f File Reference
Dirichlet states for wall boundary conditions.
Functions/Subroutines
subroutine wallbc2 (nstate, f, e, facew, wbc)
subroutine wallbc_inviscid (nstate, f, e, facew, wbc)
subroutine reflect_rind (nvar, f, e, facew, wbc)
subroutine slipwall_rflu (nvar, f, e, facew, wbc, fluxw)
subroutine rflu_setrindstateslipwallperf (cpGas, mmGas, nx, ny, nz, rl, ul, vl, wl, fs, pl)
Detailed Description
Dirichlet states for wall boundary conditions.
Definition in file wall_bc.f.
Function/Subroutine Documentation
subroutine reflect_rind (nvar, integer f, integer e, real, dimension(nx1*nz1,2*ndim,nelt,nvar) facew, real, dimension(nx1*nz1,2*ndim,nelt,nvar) wbc)
Definition at line 107 of file wall_bc.f.
References facind(), i0, and lz1.
subroutine rflu_setrindstateslipwallperf (real cpGas, real mmGas, real nx, real ny, real nz, real rl, real ul, real vl, real wl, real fs, real pl)
Definition at line 345 of file wall_bc.f.
subroutine slipwall_rflu (nvar, integer f, integer e, real, dimension(nx1*nz1,2*ndim,nelt,nvar) facew, real, dimension(nx1*nz1,2*ndim,nelt,nvar) wbc, real, dimension(nx1*nz1,2*ndim,nelt,*) fluxw)
Definition at line 179 of file wall_bc.f.
References centralinviscid_fluxfunction(), col2(), copy(), facind(), i0, invcol3(), lz1, map_faced(), nekasgn(), rflu_setrindstateslipwallperf(), and rzero().
subroutine wallbc2 (integer nstate, integer f, integer e, real, dimension(nx1*nz1,2*ndim,nelt,nstate) facew, real, dimension(nx1*nz1,2*ndim,nelt,nstate) wbc)
Definition at line 5 of file wall_bc.f.
References cmtasgn(), facind(), i0, and nekasgn().
subroutine wallbc_inviscid (integer nstate, integer f, integer e, real, dimension(nx1*nz1,2*ndim,nelt,nstate) facew, real, dimension(nx1*nz1,2*ndim,nelt,nstate) wbc)
Definition at line 91 of file wall_bc.f.
References reflect_rind().