KTH framework for Nek5000 toolboxes; testing version: Nek5000/jl/xxt_test.c File Reference
xxt_test.c File Reference
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include "name.h"
#include "fail.h"
#include "types.h"
#include "comm.h"
#include "crs.h"
Functions
int main (int narg, char *arg[])
Variables
const uint nx [3] = {8,4,4}
const ulong x_id [3][8]
double bv [3][8][8]
const uint nz [3] = {32,16,16}
const uint Ai [3][32]
const uint Aj [3][32]
const double Ar [3][32]
Function Documentation
int main (int narg, char * arg[])
Definition at line 95 of file xxt_test.c.
References Ai, Aj, Ar, bv, comm_init(), crs_free, crs_setup, crs_solve, crs_stats, exit(), i, comm::id, j, nx, nz, printf(), uint, and x_id.
Variable Documentation
const uint Ai[3][32]
Initial value:
= { {0,0,0,0, 1,1,1,1, 2,2,2,2, 3,3,3,3,
                    4,4,4,4, 5,5,5,5, 6,6,6,6, 7,7,7,7},
                   {0,0,0,0, 1,1,1,1, 2,2,2,2, 3,3,3,3},
                   {0,0,0,0, 1,1,1,1, 2,2,2,2, 3,3,3,3} }
Definition at line 80 of file xxt_test.c.
const uint Aj[3][32]
Initial value:
= { {0,1,2,3, 0,1,2,3, 0,1,2,3, 0,1,2,3,
                    4,5,6,7, 4,5,6,7, 4,5,6,7, 4,5,6,7},
                   {0,1,2,3, 0,1,2,3, 0,1,2,3, 0,1,2,3},
                   {0,1,2,3, 0,1,2,3, 0,1,2,3, 0,1,2,3} }
Definition at line 85 of file xxt_test.c.
const double Ar[3][32]
Initial value:
= { { 4,-1,-1,-2, -1,4,-2,-1, -1,-2,4,-1, -2,-1,-1,4,
                     4,-1,-1,-2, -1,4,-2,-1, -1,-2,4,-1, -2,-1,-1,4 },
                   { 4,-1,-1,-2, -1,4,-2,-1, -1,-2,4,-1, -2,-1,-1,4 },
                   { 4,-1,-1,-2, -1,4,-2,-1, -1,-2,4,-1, -2,-1,-1,4 } }
Definition at line 90 of file xxt_test.c.
double bv[3][8][8]
Initial value:
= { { {0,1/2.,0,0,0,0,0,0},
                             {0,0,0,0,0,0,0,0},
                             {0,0,1/2.,0,1/2.,0,0,0},
                             {0,0,0,1/4.,0,1/4.,0,0},
                             {0,0,0,0,0,0,0,0},
                             {0,0,0,0,0,0,1,0},
                             {0,0,0,0,0,0,0,1/2.},
                             {0,0,0,0,0,0,0,0} },
                           { {1/2.,0,0,0},
                             {0,1,0,0},
                             {0,0,0,0},
                             {0,0,1/4.,0},
                             {0,0,0,1/2.},
                             {0,0,0,0},
                             {0,0,0,0},
                             {0,0,0,0} },
                           { {0,0,0,0},
                             {0,0,0,0},
                             {0,0,0,0},
                             {1/4.,0,0,0},
                             {0,1/2.,0,0},
                             {0,0,0,0},
                             {0,0,1/2.,0},
                             {0,0,0,1} } }
Definition at line 51 of file xxt_test.c.
const uint nx[3] = {8,4,4}
Definition at line 41 of file xxt_test.c.
const uint nz[3] = {32,16,16}
Definition at line 78 of file xxt_test.c.
const ulong x_id[3][8]
Initial value:
= { {0,2,4,5, 4,5,7,8},
                           {2,3,5,6},
                           {5,6,8,9} }
Definition at line 47 of file xxt_test.c.