KTH framework for Nek5000 toolboxes; testing version: Nek5000/tools/prenek/zipper2.f File Reference
zipper2.f File Reference
Functions/Subroutines
subroutine octspl
subroutine wind3d
subroutine zip2
subroutine swapel (ind, n, nelm1)
subroutine gh_face_extend_2d (x, zg, n, gh_type, e, v)
subroutine gh_face_extend (x, zg, n, gh_type, e, v)
subroutine sphsrf_e (xml, yml, zml, ifce, e, mx, my, mz, xysrf)
subroutine edg3d (xysrf, x1, x2, i1, i2, j1, j2, mx, my)
real function dot (v1, v2, n)
subroutine crn3d (xcv, xc, yc, zc, curve, iface, ie)
subroutine dsset2 (js1, jf1, jskip1, js2, jf2, jskip2, iface, mx, my, mz)
subroutine dsset (mx, my, mz)
subroutine rone (x, n)
subroutine arcsrf_e (xml, yml, zml, nxl, nyl, nzl, e, isid)
subroutine addtnsr (s, h1, h2, h3, nx, ny, nz)
subroutine setrst2 (xpt, vec)
subroutine finde (ie, xpt1, ypt1, zpt1)
subroutine evalsc (x0, scal, rrl, inew)
subroutine chsign (x, n)
subroutine cross (v1, v2, v3)
subroutine norm3d (v1)
subroutine renum
subroutine getpt3 (xpt, ie, text)
subroutine fndpln (ijkpln, iplan, vec3, vec, xpt, ie)
subroutine win3d (je, ie, ilist, frac)
subroutine rotelm (je, irot, crot)
subroutine rotelm1 (je, irot, crot)
subroutine rotel (ie, crot)
subroutine hilite (ie, xp, yp, zp, iclr)
subroutine evline (uv, uvp, hik, n1, n1d, npt, nskip)
subroutine setebc (ifld)
subroutine psphsrf_e (xml, yml, zml, ifce, e, mx, my, mz, xysrf)
subroutine hilites (ie, iside)
subroutine shift
subroutine shifter (Shift, Sep, dir, pts, coord)
subroutine curcnt
subroutine splite (je, ie, ilist, ipln, frac)
subroutine qsplite (ie, liste)
subroutine shift2
subroutine shifter2a (pmin, pmax, gain, Shift, Sep, dir, pts, coord)
subroutine shifter2b (Shift, Sep, dir, pts, coord)
subroutine shifter2c (Shift, Sep, dir, pts, coord, gain, qmax, qmin)
subroutine shifter2 (Shift, Sep, dir, pts, coord)
subroutine hsplite (ie, liste)
subroutine zsplite (ie, liste)
function ie_click (prompt)
subroutine msplit
subroutine get_ratios (rrz, nzspi, razi)
function get_ratio (i, n, ratio)
subroutine fix_curve (e, i, j, k, nxsp, nysp, nzsp, rrx, rry, rrz, xl, yl, zl)
subroutine fix_c_curve (e, ii, jj, kk, nxsp, nysp, nzsp, rrx, rry, rrz)
subroutine fix_s_curve (e, ii, jj, kk, nxsp, nysp, nzsp, rrx, rry, rrz)
subroutine arcsph_e (xml, yml, zml, nxl, nyl, nzl, e, isid)
subroutine el_swap_ip (p, n, nmax)
subroutine el_bc_swap_ip (p, n)
subroutine renum_special
function dist_solid (e)
function dist_special (x, y, z)
function dcircle (x, y, xc, yc, r)
subroutine map_m_to_n (a, na, b, nb, if3d, w, ldw)
subroutine specmpn (b, nb, a, na, ba, ab, if3d, w, ldw)
subroutine tensr3 (v, n1, n2, n3, u, m1, m2, m3, A, Bt, Ct, w, ldw, if3d)
subroutine gen_int_gz (j, jt, g, n, z, m)
subroutine fd_weights_full (xx, x, n, m, c)
subroutine transpose_r (a, lda, b, ldb)
subroutine set_zgml (nxi)
subroutine msplite (ie, nxspi, nyspi, nzspi, raxi, rayi, razi)
subroutine linquad (xl, yl, zl, nxl, nyl, nzl, e)
subroutine xyzlin (xl, yl, zl, nxl, nyl, nzl, e)
subroutine xyzquad (xl, yl, zl, nxl, nyl, nzl, e)
subroutine genxyz_e (xl, yl, zl, e, nxl, nyl, nzl)
subroutine set_hlin (h, mx)
subroutine q_to_neklin (x, ldx, xq, if3d)
subroutine plane_project_mesh (x0, p1, p2, p3, e0, e1, tol)
subroutine draw3v (x3, y3, z3)
subroutine move3v (x3, y3, z3)
subroutine drawqel (xl, yl, nxl, nyl, e, ic)
subroutine octsplite (ie, liste)
subroutine octsplitn (ie, liste)
Function/Subroutine Documentation
subroutine addtnsr (dimension(nx,ny,nz) s, dimension(1) h1, dimension(1) h2, dimension(1) h3, nx, ny, nz)
Definition at line 1166 of file zipper2.f.
References nx, and nz.
subroutine arcsph_e (real, dimension(nxl,nyl,nzl) xml, real, dimension(nxl,nyl,nzl) yml, real, dimension(nxl,nyl,nzl) zml, nxl, nyl, nzl, integer e, isid)
Definition at line 3960 of file zipper2.f.
References cmult(), edg3d(), i, j, ly1, lz1, and sub3().
subroutine arcsrf_e (real, dimension(nxl,nyl,nzl) xml, real, dimension(nxl,nyl,nzl) yml, real, dimension(nxl,nyl,nzl) zml, nxl, nyl, nzl, integer e, isid)
Definition at line 1044 of file zipper2.f.
References addtnsr(), ly1, lz1, mod1(), and set_hlin().
subroutine chsign (real, dimension(n) x, n)
Definition at line 1403 of file zipper2.f.
References i, and n.
subroutine crn3d (dimension(3,2,2) xcv, dimension(8) xc, dimension(8) yc, dimension(8) zc, dimension(4) curve, iface, ie)
Definition at line 873 of file zipper2.f.
References exitt(), i, j, and test().
subroutine cross (real, dimension(3) v1, real, dimension(3) v2, real, dimension(3) v3)
Definition at line 1414 of file zipper2.f.
subroutine curcnt ()
Definition at line 2638 of file zipper2.f.
function dcircle (x, y, xc, yc, r)
Definition at line 4216 of file zipper2.f.
function dist_solid (integer e)
Definition at line 4154 of file zipper2.f.
References dist_special(), and dmin.
function dist_special (x, y, z)
Definition at line 4173 of file zipper2.f.
References cyl(), dcircle(), dmin, i, prs(), prsis(), rei(), and rerrr().
real function dot (dimension(n) v1, dimension(n) v2, n)
Definition at line 859 of file zipper2.f.
References dot(), i, and n.
subroutine draw3v (x3, y3, z3)
Definition at line 4886 of file zipper2.f.
References drawc(), xiso(), and yiso().
subroutine drawqel (real, dimension(nxl,nyl) xl, real, dimension(nxl,nyl) yl, nxl, nyl, integer e, integer ic)
Definition at line 4905 of file zipper2.f.
References color, draw3(), i, j, move3(), prsi(), and res().
subroutine dsset (mx, my, mz)
Definition at line 963 of file zipper2.f.
subroutine dsset2 (js1, jf1, jskip1, js2, jf2, jskip2, iface, mx, my, mz)
Definition at line 948 of file zipper2.f.
References dsset().
subroutine edg3d (dimension(3,mx,my) xysrf, dimension(3) x1, dimension(3) x2, i1, i2, j1, j2, mx, my)
Definition at line 817 of file zipper2.f.
References copy(), cross(), dot(), i, j, ly1, lz1, and norm3d().
subroutine el_bc_swap_ip (integer, dimension(1) p, n)
Definition at line 4087 of file zipper2.f.
References icopy(), iswap_ip(), and n.
subroutine el_swap_ip (integer, dimension(1) p, n, nmax)
Definition at line 4043 of file zipper2.f.
References copyel(), el_bc_swap_ip(), j, and n.
subroutine evalsc (x0, dimension(1) scal, dimension(3) rrl, inew)
Definition at line 1330 of file zipper2.f.
References hlegn(), i, j, nx, nz, and set_zgml().
subroutine evline (real, dimension(npt) uv, real, dimension(1) uvp, real, dimension(n1d,npt) hik, n1, n1d, npt, nskip)
Definition at line 2124 of file zipper2.f.
References i.
subroutine fd_weights_full (xx, real, dimension(0:n) x, n, m, real, dimension(0:n,0:m) c)
Definition at line 4367 of file zipper2.f.
References i, j, and n.
subroutine finde (ie, xpt1, ypt1, zpt1)
Definition at line 1299 of file zipper2.f.
References gencen().
subroutine fix_c_curve (integer e, ii, jj, kk, nxsp, nysp, nzsp, real, dimension(1) rrx, real, dimension(1) rry, real, dimension(1) rrz)
Definition at line 3816 of file zipper2.f.
References i, and i0.
subroutine fix_curve (integer e, i, j, k, nxsp, nysp, nzsp, real, dimension(1) rrx, real, dimension(1) rry, real, dimension(1) rrz, real, dimension(3,3,3) xl, real, dimension(3,3,3) yl, real, dimension(3,3,3) zl)
Definition at line 3759 of file zipper2.f.
References blank(), chcopy(), fix_c_curve(), fix_s_curve(), i, and j.
subroutine fix_s_curve (integer e, ii, jj, kk, nxsp, nysp, nzsp, real, dimension(1) rrx, real, dimension(1) rry, real, dimension(1) rrz)
Definition at line 3894 of file zipper2.f.
References i, and i0.
subroutine fndpln (ijkpln, iplan, dimension(3) vec3, dimension(3) vec, dimension(3) xpt, ie)
Definition at line 1578 of file zipper2.f.
References cross(), decod(), dmin, dotprod(), genxyz_e(), i, norm3d(), nx, nz, and sub3().
subroutine gen_int_gz (real, dimension(n,m) j, real, dimension(m,n) jt, real, dimension(n) g, n, real, dimension(m) z, m)
Definition at line 4343 of file zipper2.f.
References fd_weights_full(), i, n, and transpose_r().
subroutine genxyz_e (real, dimension(nxl,nyl,nzl) xl, real, dimension(nxl,nyl,nzl) yl, real, dimension(nxl,nyl,nzl) zl, integer e, nxl, nyl, nzl)
Definition at line 4720 of file zipper2.f.
References arcsrf_e(), drawqel(), exitt(), i, j, linquad(), ly1, lz1, set_zgml(), and sphsrf_e().
function get_ratio (i, n, ratio)
Definition at line 3720 of file zipper2.f.
References i, j, and n.
subroutine get_ratios (real, dimension(1) rrz, nzspi, real, dimension(0:1) razi)
Definition at line 3699 of file zipper2.f.
References get_ratio().
subroutine getpt3 (dimension(3) xpt, ie, character*80 text)
Definition at line 1545 of file zipper2.f.
References finde(), prs(), rerrr(), and res().
subroutine gh_face_extend (real, dimension(n,n,n) x, real, dimension(n) zg, n, integer gh_type, real, dimension(n,n,n) e, real, dimension(n,n,n) v)
Definition at line 539 of file zipper2.f.
References add2(), copy(), i, j, n, and rzero().
subroutine gh_face_extend_2d (real, dimension(n,n) x, real, dimension(n) zg, n, integer gh_type, real, dimension(n,n) e, real, dimension(n,n) v)
Definition at line 474 of file zipper2.f.
References add3(), copy(), i, j, n, and rzero().
subroutine hilite (ie, dimension(1) xp, dimension(1) yp, dimension(1) zp, iclr)
Definition at line 1972 of file zipper2.f.
References color, evline(), hlegn(), nx, nz, penw(), and vdraw3a().
subroutine hilites (ie, iside)
Definition at line 2387 of file zipper2.f.
References color, drawed(), and move().
subroutine hsplite (ie, dimension(8) liste)
Definition at line 3422 of file zipper2.f.
References copyel(), evalsc(), genxyz_e(), nx, and nz.
function ie_click (character*80 prompt)
Definition at line 3602 of file zipper2.f.
References mouse(), prs(), res(), rmin(), and xscr().
subroutine linquad (real, dimension(nxl*nyl*nzl) xl, real, dimension(nxl*nyl*nzl) yl, real, dimension(nxl*nyl*nzl) zl, nxl, nyl, nzl, integer e)
Definition at line 4565 of file zipper2.f.
References xyzlin(), and xyzquad().
subroutine map_m_to_n (real, dimension(1) a, na, real, dimension(1) b, nb, logical if3d, real, dimension(1) w, ldw)
Definition at line 4225 of file zipper2.f.
References exitt(), igllm(), specmpn(), and zwgll().
subroutine move3v (x3, y3, z3)
Definition at line 4896 of file zipper2.f.
References movec(), xiso(), and yiso().
subroutine msplit ()
Definition at line 3641 of file zipper2.f.
References convert_m_to_c_allr(), get_x27max(), ie_click(), msplite(), prs(), reii(), reiii(), rerr(), and rerrr().
subroutine msplite (ie, nxspi, nyspi, nzspi, real, dimension(0:1) raxi, real, dimension(0:1) rayi, real, dimension(0:1) razi)
Definition at line 4452 of file zipper2.f.
References copyel(), drawel(), fix_curve(), gen_int_gz(), genxyz_e(), get_ratios(), i, j, nx, nz, q_to_neklin(), rzero(), set_zgml(), and tensr3().
subroutine norm3d (dimension(3) v1)
Definition at line 1425 of file zipper2.f.
References dotprod().
subroutine octspl ()
Definition at line 3 of file zipper2.f.
References curcnt(), gencen(), hsplite(), msplit(), octsplitn(), prs(), prsi(), prsii(), qsplite(), res(), set_zgml(), sort(), swapel(), vertadj(), and zsplite().
subroutine octsplite (ie, dimension(8) liste)
Definition at line 4935 of file zipper2.f.
References copyel(), evalsc(), genxyz_e(), nx, and nz.
subroutine octsplitn (ie, liste)
Definition at line 5150 of file zipper2.f.
References msplite(), and rone().
subroutine plane_project_mesh (real, dimension(3) x0, real, dimension(3) p1, real, dimension(3) p2, real, dimension(3) p3, integer e0, integer e1, tol)
Definition at line 4842 of file zipper2.f.
References alpha, chsign(), dot(), i, sub3(), and vcross_normal().
subroutine psphsrf_e (real, dimension(mx,my,mz) xml, real, dimension(mx,my,mz) yml, real, dimension(mx,my,mz) zml, ifce, integer e, mx, my, mz, real, dimension(3,mx,mz) xysrf)
Definition at line 2227 of file zipper2.f.
References cmult(), crn3d(), cross(), dsset2(), edg3d(), i, j, ly1, lz1, mxm1(), norm3d(), set_hlin(), and tmp.
subroutine q_to_neklin (real, dimension(ldx,8) x, ldx, real, dimension(27) xq, logical if3d)
Definition at line 4807 of file zipper2.f.
subroutine qsplite (ie, dimension(8) liste)
Definition at line 2836 of file zipper2.f.
References copyel(), evalsc(), genxyz_e(), nx, and nz.
subroutine renum ()
Definition at line 1440 of file zipper2.f.
References copyel(), drwbox(), gencen(), i, j, mouse(), prs(), redraw_mesh(), and xphy().
subroutine renum_special ()
Definition at line 4117 of file zipper2.f.
References dist_solid(), dmin, drawel(), drgrid(), drmenu(), el_swap_ip(), irank(), prsis(), and refresh().
subroutine rone (real, dimension(1) x, n)
Definition at line 1036 of file zipper2.f.
References i, and n.
subroutine rotel (ie, character*1 crot)
Definition at line 1904 of file zipper2.f.
References copy(), i, and tmp.
subroutine rotelm (je, irot, character*1 crot)
Definition at line 1863 of file zipper2.f.
References i, and rotel().
subroutine rotelm1 (je, irot, character*1 crot)
Definition at line 1881 of file zipper2.f.
References i, and rotel().
subroutine set_hlin (real, dimension(mx,3,2) h, mx)
Definition at line 4780 of file zipper2.f.
References rone(), and set_zgml().
subroutine set_zgml (nxi)
Definition at line 4435 of file zipper2.f.
References legend().
subroutine setebc (ifld)
Definition at line 2153 of file zipper2.f.
References dist2(), gencen(), and mkside().
subroutine setrst2 (dimension(3) xpt, dimension(3) vec)
Definition at line 1184 of file zipper2.f.
References decod(), dotprod(), finde(), fndpln(), i, j, list, mod1(), and nx.
subroutine shift ()
Definition at line 2420 of file zipper2.f.
References glmin(), glsum(), menu(), n, plane_project_mesh(), prs(), prsrr(), prsrrr(), redraw_mesh(), rer(), rerrr(), res(), and shifter().
subroutine shift2 ()
Definition at line 3080 of file zipper2.f.
References menu(), prs(), redraw_mesh(), rer(), res(), shifter2(), stretch_outside_circ(), stretch_rad(), and stretch_theta().
subroutine shifter (Shift, Sep, character*1 dir, real, dimension(8,nelm) pts, character*1 coord)
Definition at line 2532 of file zipper2.f.
References j, prs(), and shift().
subroutine shifter2 (Shift, Sep, character*1 dir, real, dimension(8,nelm) pts, character*1 coord)
Definition at line 3401 of file zipper2.f.
References shift(), shifter2a(), shifter2b(), and shifter2c().
subroutine shifter2a (pmin, pmax, gain, Shift, Sep, character*1 dir, real, dimension(8,nelm) pts, character*1 coord)
Definition at line 3167 of file zipper2.f.
References j, prs(), and rer().
subroutine shifter2b (Shift, Sep, character*1 dir, real, dimension(8,nelm) pts, character*1 coord)
Definition at line 3199 of file zipper2.f.
References i, j, prs(), and shift().
subroutine shifter2c (Shift, Sep, character*1 dir, real, dimension(8,nelm) pts, character*1 coord, gain, qmax, qmin)
Definition at line 3292 of file zipper2.f.
References i, j, prs(), and shift().
subroutine specmpn (real, dimension(nb,nb,nb) b, nb, real, dimension(na,na,na) a, na, real, dimension(1) ba, real, dimension(1) ab, logical if3d, real, dimension(ldw) w, ldw)
Definition at line 4262 of file zipper2.f.
References exitt(), and mxm().
subroutine sphsrf_e (real, dimension(mx,my,mz) xml, real, dimension(mx,my,mz) yml, real, dimension(mx,my,mz) zml, ifce, integer e, mx, my, mz, real, dimension(3,mx,mz) xysrf)
Definition at line 687 of file zipper2.f.
References cmult(), crn3d(), cross(), dsset2(), edg3d(), i, j, ly1, lz1, mxm1(), norm3d(), set_hlin(), and tmp.
subroutine splite (je, ie, ilist, ipln, frac)
Definition at line 2653 of file zipper2.f.
References copy(), copyel(), decod(), evalsc(), genxyz_e(), i0, list, nx, and nz.
subroutine swapel (dimension(1) ind, n, nelm1)
Definition at line 444 of file zipper2.f.
References copyel(), i, j, and n.
subroutine tensr3 (real, dimension(1) v, n1, n2, n3, real, dimension(1) u, m1, m2, m3, real, dimension(1) A, real, dimension(1) Bt, real, dimension(1) Ct, real, dimension(ldw) w, ldw, logical if3d)
Definition at line 4303 of file zipper2.f.
References exitt(), i, j, and mxm().
subroutine transpose_r (real, dimension(lda,1) a, lda, real, dimension(ldb,1) b, ldb)
Definition at line 4424 of file zipper2.f.
References i, and j.
subroutine win3d (je, ie, ilist, frac)
Definition at line 1635 of file zipper2.f.
References copyel(), decod(), evalsc(), genxyz_e(), hilite(), list, nx, nz, rotelm(), and rotelm1().
subroutine wind3d ()
Definition at line 106 of file zipper2.f.
References copy(), cross(), decod(), fndpln(), gencen(), getpt3(), i, icopy(), list, mod1(), nx, nz, prs(), rer(), rerrr(), set_zgml(), setebc(), setquad(), setrst2(), sort(), sub3(), swapel(), and win3d().
subroutine xyzlin (real, dimension(nxl,nyl,nzl) xl, real, dimension(nxl,nyl,nzl) yl, real, dimension(nxl,nyl,nzl) zl, nxl, nyl, nzl, integer e)
Definition at line 4590 of file zipper2.f.
References i, ly1, lz1, map_m_to_n(), rone(), and set_zgml().
subroutine xyzquad (real, dimension(nxl,nyl,nzl) xl, real, dimension(nxl,nyl,nzl) yl, real, dimension(nxl,nyl,nzl) zl, nxl, nyl, nzl, integer e)
Definition at line 4660 of file zipper2.f.
References gh_face_extend(), gh_face_extend_2d(), j, ly1, lz1, map_m_to_n(), and xyzlin().
subroutine zip2 ()
Definition at line 347 of file zipper2.f.
References curcnt(), decod(), gencen(), getpt3(), i, i0, list, nx, nz, prs(), rerrr(), set_zgml(), setquad(), setrst2(), sort(), splite(), and swapel().
subroutine zsplite (ie, dimension(8) liste)
Definition at line 3543 of file zipper2.f.
References copyel(), evalsc(), genxyz_e(), i, j, nx, nz, and prsiii().