var searchData=
[
  ['gauss_2ef',['gauss.f',['../gauss_8f.html',1,'']]],
  ['gen_5fpoly_5fimp_2ec',['gen_poly_imp.c',['../gen__poly__imp_8c.html',1,'']]],
  ['genbox_2ef',['genbox.f',['../genbox_8f.html',1,'']]],
  ['genxyz_2ef',['genxyz.f',['../genxyz_8f.html',1,'']]],
  ['gfdm_5fop_2ef',['gfdm_op.f',['../gfdm__op_8f.html',1,'']]],
  ['gfdm_5fpar_2ef',['gfdm_par.f',['../gfdm__par_8f.html',1,'']]],
  ['gfdm_5fsolve_2ef',['gfdm_solve.f',['../gfdm__solve_8f.html',1,'']]],
  ['gfldr_2ef',['gfldr.f',['../gfldr_8f.html',1,'']]],
  ['gmres_2ef',['gmres.f',['../gmres_8f.html',1,'']]],
  ['gs_2ec',['gs.c',['../gs_8c.html',1,'']]],
  ['gs_2eh',['gs.h',['../gs_8h.html',1,'']]],
  ['gs_5fdefs_2eh',['gs_defs.h',['../gs__defs_8h.html',1,'']]],
  ['gs_5flocal_2ec',['gs_local.c',['../gs__local_8c.html',1,'']]],
  ['gs_5flocal_2eh',['gs_local.h',['../gs__local_8h.html',1,'']]],
  ['gs_5ftest_2ec',['gs_test.c',['../gs__test_8c.html',1,'']]],
  ['gs_5ftest_5fold_2ec',['gs_test_old.c',['../gs__test__old_8c.html',1,'']]],
  ['gs_5funique_5ftest_2ec',['gs_unique_test.c',['../gs__unique__test_8c.html',1,'']]]
];
